### PR TITLE
Only exclude _bootlocale with Python >= 3.10. Closes #9548.

### LINKED ISSUE #9548: Missing _bootlocale in Windows MSI in meson 0.60.1
When trying to configure any project with meson 0.60.1 on Windows installed from the provided Release MSI, I receive the following error:

```
The Meson build system
Version: 0.60.1
Source dir: C:\src\etx\src
Build dir: C:\src\etx\vbuild2
Build type: native build
Project name: project
Project version: undefined
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 138, in run
  File "mesonbuild\msetup.py", line 294, in run
  File "mesonbuild\msetup.py", line 185, in generate
  File "mesonbuild\msetup.py", line 207, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 297, in __init__
  File "mesonbuild\interpreterbase\interpreterbase.py", line 118, in parse_project
  File "mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 179, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 454, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 276, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1130, in func_project
  File "mesonbuild\interpreter\interpreter.py", line 1257, in add_languages
  File "mesonbuild\interpreter\interpreter.py", line 1295, in add_languages_for
  File "mesonbuild\compilers\detect.py", line 215, in detect_compiler_for
  File "mesonbuild\compilers\detect.py", line 212, in compiler_from_language
  File "mesonbuild\compilers\detect.py", line 623, in detect_c_compiler
  File "mesonbuild\compilers\detect.py", line 403, in _detect_c_or_cpp_compiler
  File "mesonbuild\mesonlib\universal.py", line 1385, in Popen_safe
  File "locale.py", line 628, in getpreferredencoding
ModuleNotFoundError: No module named '_bootlocale'
```

This happens both with and without --backend=vs. Discovered while testing vs2022, but I don't think the VS version matters as meson does not reach that part of the configuration (and vs2022 works fine with ninja in 0.60.0).

This is a regression from the 0.60.0 Release MSI.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
It looks like it was a bad idea to exclude it at all? Upstream pyinstaller now excludes this properly, and actual functioning builds seem to require using a properly up to date version of pyinstaller anyway?

Maybe we should just remove this attempt at hacking in early support altogether.

**Comment by jpakkane** [comment]
I removed all of that. The end result still does not build a package but the failure is in Pyinstaller somewhere.

While at it I made it work with VS 2022 preview as we'll transition to that at some point fairly soon.

**Comment by eli-schwartz** [comment]
So the commit message is no longer accurate. :p

**Comment by jpakkane** [comment]
It can be changed with the web UI by using `squash` as the merge method.

**Pull request merged**
