### PR TITLE
Added sysconfdir option. Closes #694.

### LINKED ISSUE #694: Several GNU directory options are not available
I see several [predefined directory options](https://github.com/mesonbuild/meson/blob/master/mesonbuild/coredata.py#L202), but several of the [GNU Coding Standard directories](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) are missing, notably `sysconfdir` being the main one.

### PR DESCRIPTION
**Pull request by jpakkane**
Reopened after master revert.

GNU doc page is inconsistent in what it says. The default should be $(prefix)/etc but immediately above it says it is for files such as `/etc/passwd`.

### CODE REVIEW

**Comment by nirbheek** [comment]
```
<nirbheek> jpakkane, The "default" value is PREFIX/etc, but everyone passes it manually
<nirbheek> And when you set it manually, you don't add prefix to it
<jpakkane> And the value they pass is /etc?
<__tim> that seems a silly default, even if consistent
<jpakkane> Yup.
<nirbheek> Yes, everyone who installs to root has to manually pass --sysconfdir=/etc
<nirbheek> Otherwise you don't set it and --prefix is used
```

**Comment by nirbheek** [comment]
So by default we should set it to `PREFIX/etc`, and if the user passes an absolute path, we should set it to that. However, if the user passes a relative path, Autotools doesn't accept it. In that case, we should prepend `PREFIX` to it, I think since we parse these options differently.

**Comment by jpakkane** [comment]
All install paths in Meson work the same way. If they are absolute they are used as is. If they are relative, then `prefix` is prepended.

**Comment by QuLogic** [comment]
Just because `/usr` corresponds with `/etc`, it doesn't mean that `/usr/local` corresponding with `/usr/local/etc` is that odd for a default. In fact, that makes the `/usr` install the odd-one-out.

**Comment by jpakkane** [comment]
The consensus seems to be to default to prefix/etc. People who want `/etc` know how to get it. If someone has a strong opposing opinion, please speak up now.

**Pull request merged**
