### PR TITLE
rust: Add rust_args kwarg

### PR DESCRIPTION
**Pull request by TingPing**
This is a bit ugly so alternatives are welcomed but this is functional for now.

### CODE REVIEW

**Comment by jpakkane** [comment]
Am I correct in assuming that Rust provides two different kinds of shared an static library types? One meant for linking to other Rust code and the other that C programs can link against? If yes, would it make sense to have a Rust keyword for this. Something like `rust_crate`? Which would do the same thing as this but without needing to specify compiler arguments.

**Comment by TingPing** [comment]
Yes I think a `rust_crate` keyword would be great, I just didn't see any precedent for library taking language specific ones.

**Comment by jpakkane** [comment]
`lang_` is meant as a namespace prefix for languages. Whatever special settings they need, that is where they should go.

**Comment by TingPing** [comment]
I will add a `rust_crate` kwarg at another point, for now this PR at least adds `rust_args`.

**Comment by jpakkane** [comment]
This message is posted to every outstanding merge request.

We have transitioned from Github wiki to our new documentation system that generates all documentation directly from the Git repo. This means that from now on every merge request must come with corresponding documentation changes.

If your MR requires documentation changes, do the necessary changes to files in `docs/markdown`.

If your MR adds a new feature, add a description to the release notes in `docs/markdown/Release-notes-for-0.41.0.md`.

If this commit is just a bugfix with no functional changes, you don't need to do anything.

Thank you

**Comment by jpakkane** [comment]
This should go to the release notes.

**Pull request merged**
