### PR TITLE
dependency: boost: only consult environment at initial stage

### PR DESCRIPTION
**Pull request by wberrier**
... not when getting compiler and link arguments

Would be nice to have some tests, but that requires boost in a
non-standard location.

### CODE REVIEW

**Comment by nirbheek** [comment]
Wouldn't this mean that to reset the boost location you have to delete the build directory and re-configure from scratch?

**Comment by wberrier** [comment]
That is correct, although I thought that was intended behavior?

It's my understanding that once a dependency is initially configured, it is cached and subsequent runs of meson don't configure that dependency again.

Moving the environment consultation into that initial stage makes it so you can set up your build directory with environment variables, but then you don't have to ensure those variables stick around.

This can be useful when you may have various build directories and configurations, all with different environment variables.

So yes, you would have to re-configure from scratch, but I think that's desired behavior if that means I don't have to always have my environment set up when running the build.

Do other dependencies behave differently?

Either way, this change at least makes the BOOST_INCLUDEDIR and BOOST_LIBRARYDIR behave the same: consult at initial configure time.  (NOTE: I initially added support for for consulting BOOST_INCLUDEDIR and BOOST_LIBRARYDIR, but unfortunately consulted the environment at "get_*_args" time instead of initial configure time.)

**Comment by nirbheek** [comment]
Hmm, I see what you mean. We already cache dependencies, so it makes sense to store the value of libdir in init on the object itself.

What I was thinking was that when you trigger `ninja reconfigure`, you expect *everything* to be re-checked. A simple use-case is that you upgrade some dependency and run reconfigure to force the new link flags to be picked. But that is a separate bug. We need `ninja reconfigure` to wipe the dependency cache and re-check everything from scratch.

**Comment by wberrier** [comment]
Out of curiosity, what are the issues on Windows?

For what it's worth, I use the boost dependency with and without BOOST_LIBRARYINC/INCLUDEDIR on several linux distributions without issue (other than what this pull request fixes).

It would be nice if there were some tests for these environment variables for non-standard boost locations, but I'm not sure how feasible that is.  Thoughts?

In any case, I'm looking forward to your post.

**Comment by jpakkane** [comment]
> We need ninja reconfigure to wipe the dependency cache and re-check everything from scratch.

There are use cases where you want to reconfigure without wiping. (I use it to force reconfigure when editing the source code of Meson, but presumably there are others too.)

**Comment by nirbheek** [comment]
Should we add two different ways to force reconfigure then? `reconfigure` and `wipe-reconfigure`? The latter feature is going to be needed even more because I have patches to add aggressive caching of commands that we run—compiler checks, `get_pkgconfig_variable`, etc, and they all lead to a 4x speedup for gst-build reconfigure.

**Comment by jpakkane** [comment]
Seems reasonable.

**Comment by wberrier** [comment]
> I was working on that in a branch, and decided to wait till after the release before finishing it up. I'll post it up today or tomorrow, let's not merge this for now.

Would it be so bad to merge this minor change in the meantime?

Also, I would be happy to try to assist with fixing the deficiencies of the boost dependency.  (What are they in addition to proper windows support?)

**Pull request merged**
