### PR TITLE
Add ability to add resources to jars

### LINKED ISSUE #9945: [Java/JAR] Cannot bundle resources files
**Describe the bug**
One cannot bundle resources files (images, audio, properties or other arbitrary files) in a JAR via Meson’s `jar()` function

**To Reproduce**
```meson
project('java-project', 'java', version : '0.1')
jar('project', 'com.example.Main.java', 'com.example.icon.png')
```

**Expected behavior**
Any resource file would be included in the JAR file as-is

**system parameters**
* Native build
* CentOS 7
* Python 3.6.8
* Meson 0.55.1
* Ninja 1.10.2

Ping @tristan957 as asked :-)

### PR DESCRIPTION
**Pull request by tristan957**
Previously Meson lacked the ability to add resources to jar files.

Fixes #9945

### CODE REVIEW

**Comment by tristan957** [comment]
Ping @dcbaker for a review since this is his baby :).

One thing I noticed however was that using plain strings instead of files gave the following error:

```
$ ninja -C build/
ninja: Entering directory `build/'
ninja: error: '/home/tristan957/Projects/meson/test cases/java/10 resources/resources/resource1.txt', needed by 'src/resources.jar.p/resource1.txt', missing and no known rule to make it
```

Not quite sure what I am doing wrong.

**Comment by tristan957** [comment]
@jpakkane would be cool to maybe squeeze this in the RC since I had to wait for structured sources PR to go in. For my personal projects, this doesn't matter, but this is pretty pivotal for other projects. I would hate to wait another release cycle to get this in.

**Comment by tristan957** [comment]
@dcbaker regarding the issue above it seems like `_generate_copy_target()` isn't taking into account the target subdir.

**Comment by tristan957** [comment]
I see "rust/18 structured sources" doesn't have this problem since its targets are generated at the meson.project_source_root().

**Review by dcbaker — APPROVED** [review]
I'm fine with this, it all looks good to me. It's really up to @jpakkane to decide whether it can go into the RC though.

**Comment by dcbaker** [comment]
https://github.com/mesonbuild/meson/pull/10147 should fix the subdir problem, hopefully.

**Review by dcbaker — APPROVED** [review]

**Pull request merged**
