### PR TITLE
Add thinlto support. Closes #7493.

### LINKED ISSUE #7493: Add support for ThinLTO when using Clang and LLD
**Describe the bug**
ThinLTO has significant improvements under the "Full" LTO path.
It scales incredibly well from a memory consumption point of view and gives incremental and threaded linking to a project.
ThinLTO has long been stable with other build systems also supporting it now.
https://clang.llvm.org/docs/ThinLTO.html

**To Reproduce**
Easy enough to reproduce,
`CC=clang CC_LD=lld meson -Db_lto=true <remaining options>`

Meson will only set `-flto` for the compile args in this instance

**Expected behavior**
I expect meson to check which version of clang and lld is being used, and if it is above a certain version (ThinLTO was supported back with clang 3.9, but probably shouldn't be enabled there) then by default enable the thin lto option with `-flto=thin`

Additionally a nice feature might be an option to set LTO flavour. This way people can still build with `-flto=full` for their final releases but keep thin around for their development and regression testing.
`-Db_lto_flavor=full, -Db_lto_flavor=thin`

**system parameters**
* This isn't a cross-building problem
* Linux at the very least effected, MacOS might matter as well, unsure if thinlto is supported under Windows
* Python version doesn't matter
* `git HEAD` for meson, checked the source tree and it isn't supporting thinlto
* Ninja doesn't matter here.

### PR DESCRIPTION
**Pull request by jpakkane**
Dunno if changing the type of `b_lto` is bad or not. In the short term there may be a few issues, but it is "correct" in the long term.

### CODE REVIEW

**Comment by dcbaker** [comment]
I've thought about this too, and I think we should make lto a compiler argument, not a built-in. There's not just thin lto, but lto threads, and cases where you might use two languages, but only one supports lto

**Comment by jpakkane** [comment]
I'd say LTO is more like the optimization level option and the semantics are more of "if lto is set, and the current language/compiler supports it, then use it". IIRC you can do LTO between C, C++ and Rust now and it would be inconvenient to have to toggle it on in three different places.

Note that this is set up so that compilers fall back to regular lto if thinlto is not supported.

**Comment by dcbaker** [comment]
I assume you can only lto between LLVM projects? Ie, clang and rustc?

**Review by dcbaker — APPROVED** [review]

**Comment by jpakkane** [comment]
> I assume you can only lto between LLVM projects? Ie, clang and rustc?

Yes. I don't think you could ever LTO-combine GCC and LLVM as their intermediate formats are completely different.

**Pull request merged**
