### PR TITLE
Use Github for executable hosting.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by nirbheek** [comment]
What ninja version is on the Ubuntu image now? If it's 1.8 or newer, we don't need the fixed ninja at all.

**Comment by jpakkane** [comment]
This for Appveyor. It is an .exe file.

**Comment by nirbheek** [comment]
> This for Appveyor. It is an .exe file.

Oh, right. Why aren't we downloading from upstream then? We only needed the custom build when upstream hadn't made a release.

**Comment by nirbheek** [comment]
Also, we should check if the ninja version is >=1.8 in `ensure_backend_detects_changes()` in `run_tests.py`. Currently, Linux and macOS builds are sleeping for 1s after `ninja` is run. We never updated this after Ninja made a release.

PS: I've fixed the cert issue on my server, so this is no longer urgent.

**Comment by jpakkane** [comment]
Upstream provides only a 64-bit binary on Windows.

**Comment by nirbheek** [comment]
> Upstream provides only a 64-bit binary on Windows.

And the CI is 64-bit Windows. Also, afaik almost all Windows development environments are 64-bit, because that's the only way to build apps for 64-bit Windows.

**Comment by nirbheek** [comment]
Well, I re-discovered in https://github.com/mesonbuild/meson/issues/3992 that I was wrong and ninja 1.8 didn't have @QuLogic's fix. Merging this.

**Pull request merged**
