### PR TITLE
Fix regression in test definitions

### PR DESCRIPTION
**Pull request by nirbheek**
Caused by #2236. Also add a test for this.

### CODE REVIEW

**Comment by jpakkane** [comment]
Appveyor test failure seems relevant.

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by nirbheek** [comment]
Looks like tests all pass now.

**Comment by jpakkane** [comment]
It's not green yet. 😄

**Comment by nirbheek** [comment]
That last one is gonna take 5-10 more minutes, so to speed things up I'm going to push the patch to the 0.42 branch in advance :p

Do you want it as two commits or one commit squashed?

**Comment by jpakkane** [comment]
Merged. Feel free to add it to your branch how ever you see fit.

**Comment by nirbheek** [comment]
The 0.42 branch is all pushed. I'll just test it against my list of repos locally and we can call it a release.

**Pull request merged**
