### PR TITLE
nasm: Link with windows CRT libs when nasm is used as linker language

### PR DESCRIPTION
**Pull request by xclaesse**
- nasm: Link with windows CRT libs when nasm is used as linker language

- ci: Install NASM on MSVC jobs

- interpreter: Do not ignore all exceptions when adding compiler
    
Suppressing all exceptions was hidding even syntax errors in compiler
source code. If a compiler cannot be found, a MesonException is raised,
we should only expect that type.

### CODE REVIEW

**Comment by amyspark** [comment]
Hi! Your PR is not complete, it'll still fail linker detection because the trial list hasn't been extended for NASM. See cb92f7cb3f184e220de6529dc17492c8a4536b63 and 586f2d13e6f8f1e99ee4cd10775fda9f6b258fdf.

**Comment by xclaesse** [comment]
> https://github.com/mesonbuild/meson/commit/cb92f7cb3f184e220de6529dc17492c8a4536b63

That was causing the CI failures I got. Cherry-picked it now thanks.

> https://github.com/mesonbuild/meson/commit/586f2d13e6f8f1e99ee4cd10775fda9f6b258fdf

I'm not sure to understand what MASK_LANGS does, is there a specific test-case that fails without that change?

**Comment by amyspark** [comment]
IIRC, `MASK_FLAGS` tells meson that NASM-generated objects can be linked as if they were C objects. It's related, but different to MSVC's own library requirements.

(note: it comes from the comments around here: https://github.com/mesonbuild/meson/pull/11127#pullrequestreview-1204623901)

**Comment by xclaesse** [comment]
That's clink_langs, nasm is in that list already with this PR. My understanding of MASK_FLAGS is it will not add -lc++ when there are cpp files but CUDA is the linker. In our case if there are cpp files nasm will not be the linker and we still need -lc++. I prefer keeping that part out of the pr because it's not needed to pass CI, if you have a test case that requires it, we can make another PR.

**Comment by amyspark** [comment]
I'd need ICU to merge my NASM generator first, so for the time being, I'm ok with green CI here 👍

**Review by amyspark — APPROVED** [review]

**Comment by xclaesse** [comment]
Thanks for your contribution @amyspark !

**Pull request merged**
