### PR TITLE
gtkdoc: add support for a binary wrapper

### PR DESCRIPTION
**Pull request by kanavin**
Make it possible to specify a wrapper for executing binaries.
(useful in cross-compiling)

### CODE REVIEW

**Comment by jpakkane** [comment]
What value would that have? Would it be the same as the regular exe_wrapper (if defined) or something else?

**Comment by kanavin** [comment]
> What value would that have? Would it be the same as the regular exe_wrapper (if defined) or something else?

In yocto project we do not define the regular exe_wrapper, but set:
```
gtkdoc_exe_wrapper = '${B}/gtkdoc-qemuwrapper'
```
in meson.cross.

Where ${B} is the yocto-specific build path, and the wrapper is a shell script that sets a few environment variables for qemu usermode binary, and then runs that with $@. Setting a generic exe_wrapper to the same script and passing that to gtk-doc may well work, but has not been tried - it's going to be a global change across all meson projects, so I'm a bit wary.

**Comment by dcbaker** [comment]
Why can't you just use the normal cross binaries for this? It seems like 
```ini
[binaries]
gtk-doc = wrapper
```
Should already do what you want?

**Comment by kanavin** [comment]
> Why can't you just use the normal cross binaries for this? It seems like
> 
> ```ini
> [binaries]
> gtk-doc = wrapper
> ```
> 
> Should already do what you want?

It's not that simple. gtk-doc is not a single binary, but a bunch of python scripts, and you need to pass the wrapper to one of them (gtkdoc-scangobj I think) via --run parameter, as it's using the wrapper internally. meson already has support for doing that, what was missing was configuring the wrapper and passing it to meson's own gtkdoc module.

**Comment by eli-schwartz** [comment]
I think what @dcbaker was trying to imply was, more or less, that you create a wrapper called `gtkdoc-mesonwrapper`, which when run invokes `wrapped-program --run="${B}"/gtkdoc-qemuwrapper "$@"`. Doing it this way would not require explicit support for the --run argument here.

What really makes me wonder is, why does the gtkdochelper script have an option `--run` which is never, ever used? Seems weird.

Either way, I think the exe_wrapper is the correct solution here. We should not have two exe wrapper settings in the cross file, one for gtkdoc and one for "literally everything else".

> Setting a generic exe_wrapper to the same script and passing that to gtk-doc may well work, but has not been tried - introducing the generic wrapper is going to be a global change across all meson projects, so I'm a bit wary.

And I'm a bit wary of adding unnecessary API to meson, when we could amend the PR to use the API we already have, and existing users of exe_wrapper get this added for free.

The exe wrapper is only used when *running* cross-compiled programs. Which is probably not often needed, and in any case where it would be needed, failing to set the wrapper would result in that program failing to run with "Exec format error".

(Just like gtk-scangobj, I guess.)

**Comment by eli-schwartz** [comment]
@ericonr because Void Linux actually does use the exe_wrapper and the change @jpakkane and I are suggesting would mean that stuff just magically starts working there for free (just add the qemu build helper to every gtkdoc-using package if it is not there already).

**Comment by kanavin** [comment]
> What really makes me wonder is, why does the gtkdochelper script have an option `--run` which is never, ever used? Seems weird.
> 

I think it was written so that it supports every option there is, regardless of what is actually used.

> Either way, I think the exe_wrapper is the correct solution here. We should not have two exe wrapper settings in the cross file, > The exe wrapper is only used when _running_ cross-compiled programs. Which is probably not often needed, and in any case where it would be needed, failing to set the wrapper would result in that program failing to run with "Exec format error".

Alright, I'll rework the patch to use the exe_wrapper, but it would need to be locally tested with yocto builds first, to ensure setting the wrapper globally works and doesn't interfere in other places.

**Comment by kanavin** [comment]
Patch adjusted to use the generic exe_wrapper, pls take a look.

**Comment by ericonr** [comment]
As requested, I've tested this patch on Void Linux.

I'm using the commit as backported: https://github.com/eli-schwartz/meson/commit/593d4ae40ef35b2f167b3c2f65640fd14143306c

I tested a cross build for 32-bit ARM, on a GNU libc build machine, and it worked correctly.

Unfortunately, there were issues when testing the build on musl:

```
Running custom install script '/usr/bin/meson --internal gtkdoc --sourcedir=/builddir/libvirt-glib-4.0.0 --builddir=/builddir/libvirt-glib-4.0.0/build --subdir=docs/libvirt-gconfig --headerdirs=/builddir/libvirt-glib-4.0.0/libvirt-gconfig --mainfile=Libvirt-gconfig-docs.xml --modulename=Libvirt-gconfig --moduleversion= --mode=auto --gtkdoc-scan=/usr/bin/gtkdoc-scan --gtkdoc-scangobj=/usr/bin/gtkdoc-scangobj --gtkdoc-mkdb=/usr/bin/gtkdoc-mkdb --gtkdoc-mkhtml=/usr/bin/gtkdoc-mkhtml --gtkdoc-fixxref=/usr/bin/gtkdoc-fixxref --run=/usr/bin/qemu-arm-static --scanargs=--rebuild-sections@@--rebuild-types --mkdbargs=--output-format=xml --content-files= --installdir=/usr/share/gtk-doc/html/Libvirt-gconfig --cc=arm-linux-musleabihf-gcc --ld=arm-linux-musleabihf-gcc --cflags=-I/usr/arm-linux-musleabihf/usr/include/glib-2.0 -I/usr/arm-linux-musleabihf/usr/lib32/glib-2.0/include -I/usr/arm-linux-musleabihf/usr/include/libxml2 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/usr/arm-linux-musleabihf/usr/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_48 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_48 -fno-common -W -Wabsolute-value -Waddress -Waddress-of-packed-member -Waggressive-loop-optimizations -Wall -Wattribute-warning -Wattributes -Wbool-compare -Wbool-operation -Wbuiltin-declaration-mismatch -Wbuiltin-macro-redefined -Wcannot-profile -Wcast-align -Wcast-align=strict -Wcast-function-type -Wchar-subscripts -Wclobbered -Wcomment -Wcomments -Wcoverage-mismatch -Wcpp -Wdangling-else -Wdate-time -Wdeprecated-declarations -Wdesignated-init -Wdiscarded-array-qualifiers -Wdiscarded-qualifiers -Wdiv-by-zero -Wduplicated-cond -Wduplicate-decl-specifier -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wextra -Wformat-contains-nul -Wformat-extra-args -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wformat-zero-length -Wframe-address -Wfree-nonheap-object -Whsa -Wif-not-aligned -Wignored-attributes -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Winline -Wint-conversion -Wint-in-bool-context -Wint-to-pointer-cast -Winvalid-memory-model -Winvalid-pch -Wlogical-not-parentheses -Wlogical-op -Wmain -Wmaybe-uninitialized -Wmemset-elt-size -Wmemset-transposed-args -Wmisleading-indentation -Wmissing-attributes -Wmissing-braces -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-parameter-type -Wmissing-profile -Wmissing-prototypes -Wmultichar -Wmultistatement-macros -Wnarrowing -Wnested-externs -Wnonnull -Wnonnull-compare -Wnull-dereference -Wodr -Wold-style-declaration -Wold-style-definition -Wopenmp-simd -Woverflow -Woverride-init -Wpacked-bitfield-compat -Wpacked-not-aligned -Wparentheses -Wpointer-arith -Wpointer-compare -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wpsabi -Wrestrict -Wreturn-local-addr -Wreturn-type -Wscalar-storage-order -Wsequence-point -Wshadow -Wshift-count-negative -Wshift-count-overflow -Wshift-negative-value -Wsizeof-array-argument -Wsizeof-pointer-div -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wstrict-prototypes -Wstringop-truncation -Wsuggest-attribute=cold -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsuggest-final-methods -Wsuggest-final-types -Wswitch -Wswitch-bool -Wswitch-unreachable -Wsync-nand -Wtautological-compare -Wtrampolines -Wtrigraphs -Wtype-limits -Wuninitialized -Wunknown-pragmas -Wunused -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvector-operation-performance -Wvla -Wvolatile-register-var -Wwrite-strings -Walloc-size-larger-than=2147483647 -Warray-bounds=2 -Wattribute-alias=2 -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough=5 -Wnormalized=nfc -Wshift-overflow=2 -Wstringop-overflow=2 -Wunused-const-variable=2 -Wno-sign-compare -Wno-cast-function-type -Wjump-misses-init -Wswitch-enum -Wno-format-nonliteral -Wno-format-truncation -Wframe-larger-than=4096 -fexceptions -fasynchronous-unwind-tables -fipa-pure-const -Wno-suggest-attribute=pure -Wno-suggest-attribute=const -Wno-unused-parameter -fstack-protector-strong --ldflags=-L/builddir/libvirt-glib-4.0.0/build/libvirt-gconfig -Wl,-rpath,/builddir/libvirt-glib-4.0.0/build/libvirt-gconfig -L/builddir/libvirt-glib-4.0.0/build/libvirt-glib -Wl,-rpath,/builddir/libvirt-glib-4.0.0/build/libvirt-glib -L/usr/arm-linux-musleabihf/usr/lib32 -Wl,-rpath,/usr/arm-linux-musleabihf/usr/lib32 -lvirt-gconfig-1.0 -L/usr/arm-linux-musleabihf/usr/lib32 -lvirt -lgobject-2.0 -lglib-2.0 -lxml2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/arm-linux-musleabihf/usr/lib'
--- stdout ---
Building documentation for Libvirt-gconfig
ERROR: Error in gtkdoc helper script:

ERROR: ['/usr/bin/gtkdoc-scangobj', '--types=/builddir/libvirt-glib-4.0.0/build/docs/libvirt-gconfig/Libvirt-gconfig.types', '--module=Libvirt-gconfig', '--run=/usr/bin/qemu-arm-static', '--cflags=-I/usr/arm-linux-musleabihf/usr/include/glib-2.0 -I/usr/arm-linux-musleabihf/usr/lib32/glib-2.0/include -I/usr/arm-linux-musleabihf/usr/include/libxml2 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/usr/arm-linux-musleabihf/usr/include -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_48 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_48 -fno-common -W -Wabsolute-value -Waddress -Waddress-of-packed-member -Waggressive-loop-optimizations -Wall -Wattribute-warning -Wattributes -Wbool-compare -Wbool-operation -Wbuiltin-declaration-mismatch -Wbuiltin-macro-redefined -Wcannot-profile -Wcast-align -Wcast-align=strict -Wcast-function-type -Wchar-subscripts -Wclobbered -Wcomment -Wcomments -Wcoverage-mismatch -Wcpp -Wdangling-else -Wdate-time -Wdeprecated-declarations -Wdesignated-init -Wdiscarded-array-qualifiers -Wdiscarded-qualifiers -Wdiv-by-zero -Wduplicated-cond -Wduplicate-decl-specifier -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wextra -Wformat-contains-nul -Wformat-extra-args -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wformat-zero-length -Wframe-address -Wfree-nonheap-object -Whsa -Wif-not-aligned -Wignored-attributes -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Winline -Wint-conversion -Wint-in-bool-context -Wint-to-pointer-cast -Winvalid-memory-model -Winvalid-pch -Wlogical-not-parentheses -Wlogical-op -Wmain -Wmaybe-uninitialized -Wmemset-elt-size -Wmemset-transposed-args -Wmisleading-indentation -Wmissing-attributes -Wmissing-braces -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-parameter-type -Wmissing-profile -Wmissing-prototypes -Wmultichar -Wmultistatement-macros -Wnarrowing -Wnested-externs -Wnonnull -Wnonnull-compare -Wnull-dereference -Wodr -Wold-style-declaration -Wold-style-definition -Wopenmp-simd -Woverflow -Woverride-init -Wpacked-bitfield-compat -Wpacked-not-aligned -Wparentheses -Wpointer-arith -Wpointer-compare -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wpsabi -Wrestrict -Wreturn-local-addr -Wreturn-type -Wscalar-storage-order -Wsequence-point -Wshadow -Wshift-count-negative -Wshift-count-overflow -Wshift-negative-value -Wsizeof-array-argument -Wsizeof-pointer-div -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wstrict-prototypes -Wstringop-truncation -Wsuggest-attribute=cold -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsuggest-final-methods -Wsuggest-final-types -Wswitch -Wswitch-bool -Wswitch-unreachable -Wsync-nand -Wtautological-compare -Wtrampolines -Wtrigraphs -Wtype-limits -Wuninitialized -Wunknown-pragmas -Wunused -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvector-operation-performance -Wvla -Wvolatile-register-var -Wwrite-strings -Walloc-size-larger-than=2147483647 -Warray-bounds=2 -Wattribute-alias=2 -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough=5 -Wnormalized=nfc -Wshift-overflow=2 -Wstringop-overflow=2 -Wunused-const-variable=2 -Wno-sign-compare -Wno-cast-function-type -Wjump-misses-init -Wswitch-enum -Wno-format-nonliteral -Wno-format-truncation -Wframe-larger-than=4096 -fexceptions -fasynchronous-unwind-tables -fipa-pure-const -Wno-suggest-attribute=pure -Wno-suggest-attribute=const -Wno-unused-parameter -fstack-protector-strong', '--ldflags=-L/builddir/libvirt-glib-4.0.0/build/libvirt-gconfig -Wl,-rpath,/builddir/libvirt-glib-4.0.0/build/libvirt-gconfig -L/builddir/libvirt-glib-4.0.0/build/libvirt-glib -Wl,-rpath,/builddir/libvirt-glib-4.0.0/build/libvirt-glib -L/usr/arm-linux-musleabihf/usr/lib32 -Wl,-rpath,/usr/arm-linux-musleabihf/usr/lib32 -lvirt-gconfig-1.0 -L/usr/arm-linux-musleabihf/usr/lib32 -lvirt -lgobject-2.0 -lglib-2.0 -lxml2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/arm-linux-musleabihf/usr/lib', '--cc=arm-linux-musleabihf-gcc', '--ld=arm-linux-musleabihf-gcc', '--output-dir=/builddir/libvirt-glib-4.0.0/build/docs/libvirt-gconfig'] failed with status 127
Error loading shared library libpython3.10.so.1.0: Exec format error (needed by /usr/bin/gtkdoc-scangobj)
Error relocating /usr/bin/gtkdoc-scangobj: Py_BytesMain: symbol not found
```

What happens here is that, per https://github.com/mesonbuild/meson/pull/2800/commits/9ec950c4ae5281336d4f7804dcf52943860d5d32 , all RPATH arguments are being appended into `LD_LIBRARY_PATH` env var (we should consider simply unsetting `LD_LIBRARY_PATH` instead). musl's dynamic linker isn't as forgiving as glibc's, and when it finds a library in its search path that couldn't be loaded (in this case, `libpython3.10.so` for ARM), will error out instead of proceeding to the next directory (I *think* upstream musl doesn't plan on changing that behavior).

Overall, this PR is an improvement, it just has some caveats to go with it.

**Comment by kanavin** [comment]
> --run=/usr/bin/qemu-arm-static

For what it's worth, we (Yocto project) do not pass qemu binary directly where target binaries need to be run, but wrap it inside a script that ensures everything that needs to be set is correctly set. In case of meson's exe-wrapper it looks like this and I tested that it works as it should:
```
#!/bin/sh
# Use a modules directory which doesn't exist so we don't load random things
# which may then get deleted (or their dependencies) and potentially segfault
export GIO_MODULE_DIR=/home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/glib-2.0/1_2.70.1-r0/recipe-sysroot/usr/lib/gio/modules-dummy

# meson sets this wrongly (only to libs in build-dir), qemu-wrapper_cmdline() and GIR_EXTRA_LIBS_PATH take care of it properly
unset LD_LIBRARY_PATH

PSEUDO_UNLOAD=1 qemu-x86_64 -r 3.2.0  -cpu core2duo -L /home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/glib-2.0/1_2.70.1-r0/recipe-sysroot -E LD_LIBRARY_PATH=/home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/glib-2.0/1_2.70.1-r0/recipe-sysroot//usr/lib:/home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/glib-2.0/1_2.70.1-r0/recipe-sysroot//lib  "$@"
```

**Comment by ericonr** [comment]
Using a script might still be necessary, but that isn't the issue I'm getting with musl. The failure happens in launching python for the `gtkdoc-scanobj` program, because meson passed the wrong `LD_LIBRARY_PATH` to it. QEMU, wrapped by a script or not, hasn't even come into play yet.

**Comment by eli-schwartz** [comment]
It would be fantastic if someone could figure out how to get this working on Musl too. For now, this PR represents a useful improvement over the status quo, covering the common case.

Please open another issue (or a PR!) for the additional problem.

**Pull request merged**
