### PR TITLE
Add a new compiler function 'symbols_have_underscore_prefix'

### PR DESCRIPTION
**Pull request by nirbheek**
Check if the compiler prefixes an underscore to global symbols. Very similar to `LT_SYS_SYMBOL_USCORE`. This is useful when linking to compiled assembly code, or other code that does not have its C symbol mangling handled transparently by the compiler.

C symbol mangling is platform and architecture dependent, and a helper function is needed to detect it. Eg: Windows 32-bit prefixes underscore, but 64-bit does not. Linux does not prefix an underscore but OS X does.

Also adds a test for this and fix `cc.compile` with MSVC when only doing compilation.

### CODE REVIEW

**Comment by tp-m** [comment]
The naming of the new function is not entirely intuitive imho, it sounds to me like you're checking whether the compiler prefixes underscores with something.

**Comment by nirbheek** [comment]
Suggestions for alternative names are welcome. I'm not too fond of this myself. :)

We could just use what the libtool autoconf macro uses and call it `symbol_underscore` or `symbols_are_underscored`.

**Comment by jpakkane** [comment]
`symbols_have_underscore_prefix`?

**Comment by tp-m** [comment]
Does exactly what it says on the tin and is still considerably shorter than _Bundespräsidentenstichwahlwiederholungsverschiebung_ ;)

**Comment by nirbheek** [comment]
It only checks it for C symbols though (when building with C++ we use `extern "C"`), so should it be `c_symbols_have_underscore_prefix`? Otherwise people might think that it checks if the C++ mangling has an underscore prefix (this is the disadvantage of having a descriptive name :p).

**Comment by jpakkane** [comment]
We could make the C++ compiler throw an exception if this test is attempted on it. If someone needs this in the future we can add it (but it seems very unlikely).

**Comment by msink** [comment]
`cc.name_mangle('name')`

Even in C it could be something like `@name@4`

**Comment by nirbheek** [comment]
> We could make the C++ compiler throw an exception if this test is attempted on it.

This seems like an unnecessary and potentially confusing restriction since you can compile assembly with C++ compilers and use it with `extern "C"`. We will eventually have someone file a bug about it I'm sure. ;)

I'll just call it `symbols_have_underscore_prefix` and end this bike-shedding.

> cc.name_mangle('name')
> Even in C it could be something like @name@4

That name mangling only happens on 32-bit Windows (and other 32-bit platforms) when you use different calling conventions, and in that case, you're supposed to specify in the assembly what calling convention you're using and the symbol mangling is done for you automatically.

This is about only the default C calling convention which is compiler-specific and is not handled for you automatically by the assembler on Linux, OS X, 64-bit Windows, and other platforms.

In fact, that would be even worse because people would *want to use it with C++* to call C++ functions from plain C or from assembly, which is generally a dangerous thing to do.

**Pull request merged**
