### PR TITLE
Remove XML filter from testlog.{json,txt} and std streams

### PR DESCRIPTION
**Pull request by tristan957**
This was an unintended consequence of the original patch in #11977.

### CODE REVIEW

**Comment by tristan957** [comment]
cc @benoit-pierre. I tagged it for 1.2.2 whenever that releases.

**Comment by benoit-pierre** [comment]
The testsuite needs patching too:
```diff
 unittests/allplatformstests.py | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)

diff --git i/unittests/allplatformstests.py w/unittests/allplatformstests.py
index b4bf3714a..766825d3c 100644
--- i/unittests/allplatformstests.py
+++ w/unittests/allplatformstests.py
@@ -431,9 +431,8 @@ class AllPlatformTests(BasePlatformTests):
 
         valid_string = base_string_valid + repr(invalid_string)[1:-1] + base_string_valid
         invalid_string = base_string_invalid + invalid_string + base_string_invalid
-        broken_xml_stream = invalid_string.encode()
-        decoded_broken_stream = mtest.decode(broken_xml_stream)
-        self.assertEqual(decoded_broken_stream, valid_string)
+        fixed_string = mtest.replace_unencodable_xml_chars(invalid_string)
+        self.assertEqual(fixed_string, valid_string)
 
     def test_replace_unencodable_xml_chars_unit(self):
         '''
@@ -448,6 +447,12 @@ class AllPlatformTests(BasePlatformTests):
         self.run_tests()
         junit_xml_logs = Path(self.logdir, 'testlog.junit.xml')
         subprocess.run(['xmllint', junit_xml_logs], check=True)
+        # Ensure JSON & text logs are not mangled.
+        raw_output_sample = b'\nHello Meson\n\n\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b'
+        text_log = Path(self.logdir, 'testlog.txt').read_bytes()
+        assert raw_output_sample in text_log
+        json_log = json.loads(Path(self.logdir, 'testlog.json').read_bytes())
+        assert raw_output_sample.decode('ascii') in json_log['stdout']
 
     def test_run_target_files_path(self):
         '''
```

**Comment by benoit-pierre** [comment]
I don't see an easy way to get at the command output to check it's also not mangled… ¯\\_(ツ)_/¯

**Comment by benoit-pierre** [comment]
OK, we can just patch the test `meson.build` to run its test verbosely, updated full patch:
```diff
 mesonbuild/mtest.py                                        | 12 ++++++------
 .../unit/110 replace unencodable xml chars/meson.build     |  2 +-
 unittests/allplatformstests.py                             | 14 ++++++++++----
 3 files changed, 17 insertions(+), 11 deletions(-)

diff --git i/mesonbuild/mtest.py w/mesonbuild/mtest.py
index eb56c42be..8d83d17bd 100644
--- i/mesonbuild/mtest.py
+++ w/mesonbuild/mtest.py
@@ -867,10 +867,10 @@ class JunitBuilder(TestLogger):
                     et.SubElement(testcase, 'system-out').text = subtest.explanation
             if test.stdo:
                 out = et.SubElement(suite, 'system-out')
-                out.text = test.stdo.rstrip()
+                out.text = replace_unencodable_xml_chars(test.stdo.rstrip())
             if test.stde:
                 err = et.SubElement(suite, 'system-err')
-                err.text = test.stde.rstrip()
+                err.text = replace_unencodable_xml_chars(test.stde.rstrip())
         else:
             if test.project not in self.suites:
                 suite = self.suites[test.project] = et.Element(
@@ -893,10 +893,10 @@ class JunitBuilder(TestLogger):
                 suite.attrib['failures'] = str(int(suite.attrib['failures']) + 1)
             if test.stdo:
                 out = et.SubElement(testcase, 'system-out')
-                out.text = test.stdo.rstrip()
+                out.text = replace_unencodable_xml_chars(test.stdo.rstrip())
             if test.stde:
                 err = et.SubElement(testcase, 'system-err')
-                err.text = test.stde.rstrip()
+                err.text = replace_unencodable_xml_chars(test.stde.rstrip())
 
     async def finish(self, harness: 'TestHarness') -> None:
         """Calculate total test counts and write out the xml result."""
@@ -1180,9 +1180,9 @@ def decode(stream: T.Union[None, bytes]) -> str:
     if stream is None:
         return ''
     try:
-        return replace_unencodable_xml_chars(stream.decode('utf-8'))
+        return stream.decode('utf-8')
     except UnicodeDecodeError:
-        return replace_unencodable_xml_chars(stream.decode('iso-8859-1', errors='ignore'))
+        return stream.decode('iso-8859-1', errors='ignore')
 
 async def read_decode(reader: asyncio.StreamReader,
                       queue: T.Optional['asyncio.Queue[T.Optional[str]]'],
diff --git i/test cases/unit/110 replace unencodable xml chars/meson.build w/test cases/unit/110 replace unencodable xml chars/meson.build
index 2e6b1b793..73485b073 100644
--- i/test cases/unit/110 replace unencodable xml chars/meson.build	
+++ w/test cases/unit/110 replace unencodable xml chars/meson.build	
@@ -1,4 +1,4 @@
 project('replace unencodable xml chars')
 
 test_script = find_program('script.py')
-test('main', test_script)
+test('main', test_script, verbose: true)
diff --git i/unittests/allplatformstests.py w/unittests/allplatformstests.py
index b4bf3714a..8360b7dd5 100644
--- i/unittests/allplatformstests.py
+++ w/unittests/allplatformstests.py
@@ -431,9 +431,8 @@ class AllPlatformTests(BasePlatformTests):
 
         valid_string = base_string_valid + repr(invalid_string)[1:-1] + base_string_valid
         invalid_string = base_string_invalid + invalid_string + base_string_invalid
-        broken_xml_stream = invalid_string.encode()
-        decoded_broken_stream = mtest.decode(broken_xml_stream)
-        self.assertEqual(decoded_broken_stream, valid_string)
+        fixed_string = mtest.replace_unencodable_xml_chars(invalid_string)
+        self.assertEqual(fixed_string, valid_string)
 
     def test_replace_unencodable_xml_chars_unit(self):
         '''
@@ -445,9 +444,16 @@ class AllPlatformTests(BasePlatformTests):
             raise SkipTest('xmllint not installed')
         testdir = os.path.join(self.unit_test_dir, '110 replace unencodable xml chars')
         self.init(testdir)
-        self.run_tests()
+        tests_command_output = self.run_tests()
         junit_xml_logs = Path(self.logdir, 'testlog.junit.xml')
         subprocess.run(['xmllint', junit_xml_logs], check=True)
+        # Ensure command output and JSON / text logs are not mangled.
+        raw_output_sample = '\nHello Meson\n\n\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b'
+        assert raw_output_sample in tests_command_output
+        text_log = Path(self.logdir, 'testlog.txt').read_text()
+        assert raw_output_sample in text_log
+        json_log = json.loads(Path(self.logdir, 'testlog.json').read_bytes())
+        assert raw_output_sample in json_log['stdout']
 
     def test_run_target_files_path(self):
         '''
```

**Comment by tristan957** [comment]
Please make sure I applied the patch correctly.

**Comment by benoit-pierre** [comment]
Looking good.

**Comment by benoit-pierre** [comment]
OK, so the Windows related failure is due to some [end of lines shenanigans](https://github.com/benoit-pierre/meson/actions/runs/5858924537/job/15883873847#step:6:2696) in the command's output. Let's just skirt the issue by tweaking the raw output sample:
```diff
diff --git a/unittests/allplatformstests.py b/unittests/allplatformstests.py
index e8decc42a..819cc2ee7 100644
--- a/unittests/allplatformstests.py
+++ b/unittests/allplatformstests.py
@@ -480,7 +480,7 @@ class AllPlatformTests(BasePlatformTests):
         junit_xml_logs = Path(self.logdir, 'testlog.junit.xml')
         subprocess.run(['xmllint', junit_xml_logs], check=True)
         # Ensure command output and JSON / text logs are not mangled.
-        raw_output_sample = '\nHello Meson\n\n\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b'
+        raw_output_sample = '\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b'
         assert raw_output_sample in tests_command_output
         text_log = Path(self.logdir, 'testlog.txt').read_text()
         assert raw_output_sample in text_log
```

**Comment by benoit-pierre** [comment]
The remaining cygwin failure does not look related to the change.

**Pull request merged**
