### PR TITLE
Update Users.md

### PR DESCRIPTION
**Pull request by amitdo**

### CODE REVIEW

**Comment by amitdo** [comment]
Please squash these two commits.

**Comment by amitdo** [comment]
I wonder if it fails because I changed the title.

**Comment by jpakkane** [comment]
I cancelled it manually because doc-only changes do not need test runs which are slow. I'll do it again for this one.

**Comment by amitdo** [comment]
Ah! :-)

**Comment by amitdo** [comment]
Some projects use a bot to help manage PRs. Maybe it's possible to write a bot that will cancel  the ci run for docs-only PRs.

**Comment by jpakkane** [comment]
We had one but it broke coverage reporting.

**Comment by amitdo** [comment]
You need a Smarter bot then! 😆

**Comment by nirbheek** [comment]
You can tell Travis and Appveyor to not run the CI for a commit by adding the phrase `[skip ci]` (including `[]`) anywhere in the commit message.

**Comment by amitdo** [comment]
@nirbheek, 
Thanks for the tip! Maybe this info should be added to 
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Contributing.md

**Comment by nirbheek** [comment]
Go ahead!

**Pull request merged**
