### PR TITLE
do not use universal_newlines for subprocess.Popen() for Python < 3.6

### PR DESCRIPTION
**Pull request by nioncode**
universal_newlines prior to Python 3.6 uses the default encoding returned by `locale.getpreferredlocale(False)`, which might not be the encoding that the console actually uses.
Using the wrong encoding leads to an Exception, which can be seen on a Windows machine that is set to German and uses an utf-8 console when running the meson test suite (and possibly at other places).

### CODE REVIEW

**Comment by nirbheek** [comment]
Is there a way to add this to the CI somehow so we don't break it inadvertently again? Seems like a fragile thing that someone will inevitably break.

**Comment by nioncode** [comment]
Maybe it is possible to set a different encoding for the console (or for Python) in a test case to make it break even on an English based Windows?

**Comment by nirbheek** [comment]
I couldn't find a way to do that on my Windows 8.1 machine when I was trying to reproduce this stuff locally.

**Comment by msink** [comment]
This breaks ALL tests on my computes (Win7-64 Russian)

```
call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64
py -3.6 run_tests.py --backend=ninja
```
```
test cases/common\1 trivial
stdout

---
The Meson build system
Version: 0.40.0.dev1
Source dir: F:\src\meson\test cases\common\1 trivial
Build dir: F:\src\meson\b jlj4fels
Build type: native build
Project name: trivial test
Native c compiler: cl (msvc 19.00.24213.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1


---

stderr

---
Traceback (most recent call last):
  File "F:\src\meson\mesonbuild\mesonmain.py", line 286, in run
    app.generate()
  File "F:\src\meson\mesonbuild\mesonmain.py", line 170, in generate
    g.generate(intr)
  File "F:\src\meson\mesonbuild\backend\ninjabackend.py", line 188, in generate
    with self.detect_vs_dep_prefix(tempfilename) as outfile:
  File "F:\src\meson\mesonbuild\backend\ninjabackend.py", line 174, in detect_vs_dep_prefix
    binfile.write('msvc_deps_prefix = ' + matchstr + '\n')
  File "C:\Python36-x64\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-24: character maps to <undefined>
```

**Comment by nirbheek** [comment]
It looks like that place should `open()` the file with `encoding='utf-8'`. Looks like we also need an `open_safe()` variable that's used everywhere in the codebase?

**Comment by msink** [comment]
With vs2015 backend most tests passed, only "test cases\windows\8 msvc dll versioning" fails.
All non-english error messages are totally broken - twice encoded in utf8.

But looks like this is unrelated to this path - same error in master branch too.

**Comment by nioncode** [comment]
I guess all file operations should be done in utf-8, since this should work for all backends.

`test cases\windows\8 msvc dll versioning` is broken on a regular Windows setup without cygwin or similar, because there is no `cp` binary on Windows.
I already have a fix for this, will prepare a PR soon.

**Comment by msink** [comment]
`8 msvc dll versioning` is broken, yes - but encoding of Russian error messages is broken too.
Attached full log: [meson-test-run.txt](https://github.com/mesonbuild/meson/files/857990/meson-test-run.txt)

**Comment by nioncode** [comment]
I'll try to setup a VM and test various encoding / language combinations soon.

**Comment by msink** [comment]
If console encoding is utf-8 (`chcp 65001`) - error messages are correct: [meson-test-run.txt](https://github.com/mesonbuild/meson/files/858064/meson-test-run.txt)

**Comment by jpakkane** [comment]
`detect_vs_dep_prefix` should not use `Popen_safe`. It _must not_ even try to parse the output, but instead treat it as bytes and open the file in `b' mode for that. That is what the original code did, my bad for not spotting this when the code was merged.

The real fix should be something like this:

        pc, stdo = subprocess.check_call(['cl', '/showIncludes', '/c', 'incdetect.c'],
                              cwd=self.environment.get_scratch_dir())[0:2]

        for line in stdo.split(b'\n'):
            if line.endswith(b'stdio.h'):
                matchstr = b':'.join(line.split(b':')[0:2]) + b':'
                with open(tempfilename, 'ab') as binfile:
                    binfile.write(b'msvc_deps_prefix = ' + matchstr + b'\n')
                return open(tempfilename, 'a')

**Comment by jpakkane** [comment]
The binary fix is #1616.

**Comment by jpakkane** [comment]
The binary fix has landed. Please rebase this and retest to confirm that different languages/locales work. Thanks.

**Comment by jpakkane** [comment]
This message is posted to every outstanding merge request.

We have transitioned from Github wiki to our new documentation system that generates all documentation directly from the Git repo. This means that from now on every merge request must come with corresponding documentation changes.

If your MR requires documentation changes, do the necessary changes to files in `docs/markdown`.

If your MR adds a new feature, add a description to the release notes in `docs/markdown/Release-notes-for-0.41.0.md`.

If this commit is just a bugfix with no functional changes, you don't need to do anything.

Thank you

**Comment by jpakkane** [comment]
Is this MR still relevant or are all the issues fixed by other commits?

**Comment by codicodi** [comment]
I think it's still relevant as I'm getting the following error with localized VS2017 (Polish language, console cp 852):
```
PS G:\dev\test\tmp> G:\dev\meson-master\meson.py .. --backend ninja
The Meson build system
Version: 0.41.0.dev1
Source dir: G:\dev\test
Build dir: G:\dev\test\tmp
Build type: native build
Project name: test
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\subprocess.py", line 1053, in _readerthread
    buffer.append(fh.read())
  File "C:\Python36\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 166: character maps to <undefined>

Traceback (most recent call last):
  File "G:\dev\meson-master\mesonbuild\mesonmain.py", line 301, in run
    app.generate()
  File "G:\dev\meson-master\mesonbuild\mesonmain.py", line 172, in generate
    intr = interpreter.Interpreter(b, g)
  File "G:\dev\meson-master\mesonbuild\interpreter.py", line 1236, in __init__
    self.parse_project()
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 111, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "G:\dev\meson-master\mesonbuild\interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "G:\dev\meson-master\mesonbuild\interpreter.py", line 1670, in func_project
    self.add_languages(proj_langs, True)
  File "G:\dev\meson-master\mesonbuild\interpreter.py", line 1786, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "G:\dev\meson-master\mesonbuild\interpreter.py", line 1709, in detect_compilers
    comp = self.environment.detect_c_compiler(False)
  File "G:\dev\meson-master\mesonbuild\environment.py", line 502, in detect_c_compiler
    return self._detect_c_or_cpp_compiler('c', 'CC', want_cross)
  File "G:\dev\meson-master\mesonbuild\environment.py", line 467, in _detect_c_or_cpp_compiler
    p, out, err = Popen_safe(compiler + [arg])
  File "G:\dev\meson-master\mesonbuild\mesonlib.py", line 511, in Popen_safe
    o, e = p.communicate(write)
  File "C:\Python36\lib\subprocess.py", line 836, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python36\lib\subprocess.py", line 1103, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
```
I'm not sure if fix should be applied only for Python < 3.6, though, as I'm using 3.6.1

**Comment by nioncode** [comment]
Yes, this is still relevant. I always have to apply this when running the meson test suite on my German Windows VM.
However, the PR is not up-to-date and does not fix the issue for all possible encodings.

I won't have time to work on this for the next weeks / months, so everybody should feel free to pick this up and give it a shot.

**Comment by jpakkane** [comment]
Superseded by #2331.

**Pull request closed without merging**
