### PR TITLE
Add basic Webassembly support via Emscripten.

### PR DESCRIPTION
**Pull request by jpakkane**
Don't merge yet, this has many open questions such as:

- what should the CPU and CPU family be for wasm?
- how should this be tested, wasm apps must be run via a browser?
- should we support plain emscripten too (since no-one has complained yet, maybe not)?
- should `-s WASM=1` in `always_args`?

Documentation also missing.

### CODE REVIEW

**Comment by hartenfels** [comment]
Emscripten builds Web Assembly by default, you have to pass `-s WASM=0` to turn that off: <https://emscripten.org/docs/compiling/WebAssembly.html>

And you can run the .js files with Node.js just fine, probably more convenient than firing up a browser?

**Comment by jpakkane** [comment]
One more thing to decide: what should the system be called? Based on docs there are both 32 and 64 bit wasm platforms. So should they be called `wasm32` and `wasm64` or just plain `wasm` and determine pointer size with some other mechanism? And is the wasm64 thing actually guaranteed by the relevant standard?

**Comment by hartenfels** [comment]
I've set up an example repository with a non-trivial program built with Emscripten. It does wasm by default, but you can build asm.js too without many changes. The whole thing is so quirky that just calling it `emscripten` might be better than some variant of `wasm`.

There's a Dockerfile and such to build the whole thing, which may also be useful to set up a CI environment or something. I also tried to document whatever hacks and tricks are necessary to make things actually work.

I guess this is just a request for comments and questions right now. I don't know how much of this should be patches to Meson and/or Emscripten, but this is a state that Works For Me already.

Example repo is here: https://github.com/hartenfels/meson-emscripten-example

It uses this forked repo of Meson: https://github.com/hartenfels/meson

**Comment by Akaricchi** [comment]
>One more thing to decide: what should the system be called? Based on docs there are both 32 and 64 bit wasm platforms. So should they be called wasm32 and wasm64 or just plain wasm and determine pointer size with some other mechanism? And is the wasm64 thing actually guaranteed by the relevant standard?

I would call the CPU `wasm` (perhaps with a version suffix, e.g. `wasm-mvp`), the CPU family `wasm32`/`wasm64`, and the system `emscripten`. Emscripten is not the only wasm compiler and runtime, there are non-web embeddings like https://wasmer.io/ and compilers for non-C languages that generate wasm code without Emscripten's help. Emscripten provides an array of APIs specific to its platform, and for projects like, for example, SDL, it is crucial to detect whether they should be used or not. There is also https://wasi.dev/ — an emerging candidate for a non-emscripten wasm "system".

You could even automatically support an `asmjs` "CPU" with emscripten, although that is pretty irrelevant these days.

**Comment by Akaricchi** [comment]
For what it's worth, another example of a non-trivial meson project that supports emscripten would be [Taisei](/taisei-project/taisei). It builds with unmodified Meson and contains lots of *very* emscripten-specific code scattered across the `meson.build` files. It's quite a mess.

**Comment by QuLogic** [comment]
These names may not map to anything per se, but for what it's worth, when Go added WebAssembly support, they called it `GOOS=js` and `GOARCH=wasm`.

**Comment by jpakkane** [comment]
This should now be ready for merge:

- `cpu` is `wasm32` or `wasm64`
- `cpu_family` is the same
- `system` is `emscripten`

As Webassembly is still in flux, so we can probably change things if something turns out to be completely wrong.

**Comment by jpakkane** [comment]
I can't think of anything else. Unless someone has points of contention, I'm just going to merge this.

**Comment by Akaricchi** [comment]
Some kind of support for generating `.html` targets would be nice. Here's how I currently do it:

```meson
taisei = executable('@0@.bc'.format(taisei_basename), taisei_src, version_deps,
    dependencies : taisei_deps,
    c_args : taisei_c_args,
    link_args : em_link_args,
    install : false,
)

taisei_html = custom_target(em_link_outputs[0],
    # NOTE: Unfortunately we can't just put 'taisei' directly into the command array.
    # Meson then makes an invalid assumption that we are going to execute it ("use as a generator"),
    # and aborts because there's no exe wrapper in the cross file (which wouldn't make sense to have).

    command : [
        cc.cmd_array(),
        taisei.full_path(),
        em_bundle_link_args,
        '--pre-js', em_preamble,
        '--shell-file', em_shell,
        em_link_args,
        '-o', '@OUTPUT0@',
    ],
    build_by_default : true,
    depends : [taisei],
    output : em_link_outputs,
    install : true,
    install_dir : bindir,
)
```

**Comment by jpakkane** [comment]
Sure, but those can be added in subsequent MRs.

That custom target looks weird, though. It should probably only try to complain about running the exe itself, not if you pass it as an argument to a different command. There are many use cases for that, such as building firmware upload targets from cross built executables.

**Comment by Akaricchi** [comment]
Yes, definitely. We had to resort to the same hack for a Switch homebrew port recently: https://github.com/taisei-project/taisei/commit/469d6e2f4889dfe779e0cb7be62cf3f92bad5f86#diff-9fbb37ad64805c2da3889d419806cd51R279

**Pull request merged**
