### PR TITLE
Allow emscripten to be used as non cross-compiler

### PR DESCRIPTION
**Pull request by Cloudef**
https://github.com/mesonbuild/meson/issues/6669

### CODE REVIEW

**Comment by nirbheek** [comment]
Are you planning on adding CI too? Should be relatively easy to setup a GitHub action to test this. Makes it more likely that this PR will be merged (we know for sure that it works), and also ensures that the backend won't break in the future.

**Comment by jpakkane** [comment]
There is a bit of a semantic issue here. In Meson native compilation means "targetting the current CPU + OS combo", which emscripten does not seem to do as it targets JS + WASM. Basically you should be able to have a target with one C file and one C++ file, set the C compiler to GCC, the C++ compiler to Emscripten, build the project and run it. Is it possible with this? It does not seem to be, since gcc produces elf files.

In Meson there is a way to specify that cross build executables are directly runnable, which is to set `needs_exe_wrapper` to `false`. It is used when "cross compiling" 32 bit binaries on 64 bit platforms. Can you test if it works for you (without this patch).

**Comment by Cloudef** [comment]
> Basically you should be able to have a target with one C file and one C++ file, set the C compiler to GCC, the C++ compiler to Emscripten, build the project and run it. Is it possible with this? It does not seem to be, since gcc produces elf files.

This seems like a very specific use case... Which would be already possible by setting CC and CXX accordingly, however LD is gonna trip it out, but still solvable by either making the project support this case (since I don't see why such specific case would be wanted outside some project) or writing wrapper `ld` that picks the right linker.

> In Meson there is a way to specify that cross build executables are directly runnable, which is to set needs_exe_wrapper to false. It is used when "cross compiling" 32 bit binaries on 64 bit platforms. Can you test if it works for you (without this patch).

Do I have to write a cross file for that, or can I pass that one parameter from command line?

**Comment by jpakkane** [comment]
You need a cross file.

**Comment by jpakkane** [comment]
This MR probably won't be merged as is because it changes the semantics of what a "native build" is. That would need a fair bit more discussion and the issue raised here can be worked around with `needs_exe_wrapper=false`. If it does not work then that is a bug that needs to be fixed.

Thus closing to reduce clutter on the MR page. For further discussion please open a bug if necessary. Thanks.

**Pull request closed without merging**
