### PR TITLE
Split compiler module

### PR DESCRIPTION
**Pull request by dcbaker**
This not so small series is a pretty big refactor of the compiler package, it splits all of the classes except `Compiler` out into a mixins subpackage. I'm doing this because I want to do some addtional refactoring in here to make my split linker work easier. With how big and invasive this is I'm hoping that we can have a pretty quick turn around on this as rebasing is going to be super fun.

I'm mentioning people who worked on compilers I don't have access to (pgi, armcc, armclang, elbrus, and ccrx). This is a refactor so it *shouldn't* break anything, but we all know how that theory goes, if you could give this series a go with your compiler and just make sure things are working that would bee appreciated.

@scivision, @mohdamerkhalidi @sompen @mbedarka @makise-homura @ftechz

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Flake8 detected 36 issues on f7866659810b246e036382ea82245b2a5ebcfd9f
Visit https://sider.review/gh/repos/19784232/pulls/5592 to review the issues.

<sub>posted by Sider</sub>

**Comment by ftechz** [comment]
Hey @dcbaker Had a quick check with the CCRX compiler. Works with the project I've got set up :)

**Comment by dcbaker** [comment]
Thanks for checking!

**Comment by sompen** [comment]
Hi @dcbaker  I have checked ArmCc and ArmClang compilers with the setup I have and is working as expected.

**Comment by scivision** [comment]
Oh thank you so much. I made mistakes a few times in this area in part because the files were so enormous it was tough to really read carefully. I really like that compiler families are in their own file.

**Comment by jpakkane** [comment]
I had to merge a few compiler changes needed for the point release so now this conflicts. But let's try to get this in fairly soon.

**Comment by scivision** [comment]
PGI compilers (C, Fortran) are OK with this PR.  I did have to use #5608 (unrelated bugfix) to make PGI work here.

**Comment by makise-homura** [comment]
Just checked by run_unittests.py, works normally on Elbrus compiler.

**Comment by dcbaker** [comment]
Thanks everyone for testing this! I appreciate it

**Comment by dcbaker** [comment]
@jpakkane, finally got all of the errors except the expected cygwin errors (I still need to fix those....) fixed in this series. Ready for merge?

**Comment by jpakkane** [comment]
LGTM

It should be noted that `sys.executable` is not always guaranteed to work. With the MSI installers, `sys.executable` is `meson.exe` so it would need the requisite `runpython` arguments. But since that issue has existed for a while there's no point in blocking this MR because of it.

**Comment by jpakkane** [comment]
Seems to be conflicting now. Let's get this in quick after the next rebase.

**Comment by dcbaker** [comment]
Fortunately everything rebased cleanly and when I ran unittests locally it worked. If the CI comes back green I'll go ahead and press merge.

**Pull request merged**
