### PR TITLE
docs: Fix broken page links

### PR DESCRIPTION
**Pull request by cjmayo**
Destination is the Markdown filename.

### CODE REVIEW

**Comment by QuLogic** [comment]
I think there's another one at `markdown/Reference-manual.md`, line 348: `[project build option](Build options)`.

**Comment by cjmayo** [comment]
Agreed. Added that one too.

**Comment by cjmayo** [comment]
Two more: Comparisons.md and Creating-Linux-binaries.md (used slightly less of the text for the link there too).

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
