### PR TITLE
Add option to fail fast in tests

### PR DESCRIPTION
**Pull request by NickeZ**
Add an option to fail fast for the tests. `--failfast` is already an option in the built-in `unittest` module of python. I simply extended the other test runners to also support it.

### CODE REVIEW

**Comment by NickeZ** [comment]
I also did some general cleanup of the scripts. There was a lot of global variables defined which where moved to `main()` functions.

**Comment by nirbheek** [comment]
A lot of things have changed in that file, so this PR needs conflict resolution.

**Comment by NickeZ** [comment]
If I have time I'll solve the conflicts.

**Comment by jpakkane** [comment]
Ping.

**Comment by NickeZ** [comment]
pong

**Pull request merged**
