### PR TITLE
Use recursive-include instead of graft in manifest.

### PR DESCRIPTION
**Pull request by QuLogic**
I don't really know why, but this seems to work for me...

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
++ from me

**Comment by nirbheek** [comment]
Is this still a problem?

**Comment by jpakkane** [comment]
This weekend there will be a release (hopefully). If this is still needed then, I'll merge it.

**Comment by jpakkane** [comment]
Neither of these work for me. WTF?

**Comment by jpakkane** [comment]
Neither works, needs manual workaround, so closing.

**Comment by QuLogic** [comment]
Weird, even without this fix, my sdist is the same as the repo except without the dotfiles.

**Comment by nirbheek** [comment]
Are you using setuptools? @jpakkane found that removing setuptools and using just distutils fixed it for him.

**Comment by QuLogic** [comment]
Yep; `python3 -c 'import setuptools; print(setuptools.__version__)` -> 25.1.1 (which is likely different from when I opened this PR due to Fedora upgrade.)

**Pull request closed without merging**
