### PR TITLE
Give user control of option skip_sanity_check

### PR DESCRIPTION
**Pull request by Neumann-A**
Either give the user control over `skip_sanity_check` or print an error why the user is doing something stupid. This PR uses the former approach

### CODE REVIEW

**Comment by mensinda** [comment]
Please rebase this PR on master to rerun the CI. This should get rid of the CI failures.

**Comment by vlj** [comment]
What is the status of this PR ? (there is a long chain of PR dependencies for vcpkg...)

**Comment by c72578** [comment]
@jpakkane Please have a look at this PR and merge if OK from your side.

**Comment by jpakkane** [comment]
Could you please explain a bit more what is happening here? What is the actual problem is. "Give control of option skip_sanity_check" is not very informative by itself.

**Comment by Neumann-A** [comment]
@jpakkane: there are cases where the option is simply ignored by meson. 

The previous code:
```
        if for_machine != MachineChoice.HOST:	
            return False	
        if not self.environment.is_cross_build():	
            return False
```
is returning an early false without even checking if the user provided the `skip_sanity_check` option.
As such if the user provided `skip_sanity_check=true` meson still runs the sanity check if on of the early returns fires. (Which is the case for arm crosscompiles on windows.)

**Pull request merged**
