### PR TITLE
Do not test aarch64 as the assembly has not been written.

### PR DESCRIPTION
**Pull request by jpakkane**
Originally from Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975411

### CODE REVIEW

**Comment by mimi89999** [comment]
Isn't it easier to just write that test?

**Comment by jpakkane** [comment]
> Isn't it easier to just write that test?

Patches welcome.

**Comment by mimi89999** [comment]
I think it will just be:
```
.text
.globl SYMBOL_NAME(square_unsigned)
# ifdef __linux__
.type square_unsigned, %function
#endif

SYMBOL_NAME(square_unsigned):
    mul x1, x0, x0
    mov x0, x1
    ret
```
but I need to check that on an aarch64 device.

**Comment by mimi89999** [comment]
@jpakkane It's exactly that. Just tested it. https://github.com/mesonbuild/meson/pull/8051

**Comment by jpakkane** [comment]
Great, thanks. Closing this one.

**Pull request closed without merging**
