### PR TITLE
environment: Fix passing always args to a number of less common linkers

### PR DESCRIPTION
**Pull request by dcbaker**
These are mostly (oops xilink) proprietary linkers I can't use for
various reasons.

Fixes: #6332

### CODE REVIEW

**Comment by scivision** [comment]
Cuda Windows 10: the PR reveals another error:
```
meson\test cases\cuda\1 simple>meson build --wipe
The Meson build system
Version: 0.52.999
Source dir: meson\test cases\cuda\1 simple
Build dir: meson\test cases\cuda\1 simple\build
Build type: native build
Project name: simple
Project version: 1.0.0
Cuda compiler for the host machine: nvcc (nvcc 10.1.243)
Cuda linker for the host machine: nvcc nvlink 10.1.243
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja.EXE-1.9.0.git.kitware.dyndep-1.jobserver-1 at c:\Miniconda3\Scripts\ninja.EXE
Traceback (most recent call last):
  File "meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "meson\mesonbuild\msetup.py", line 215, in _generate
    intr.backend.generate(intr)
  File "meson\mesonbuild\backend\ninjabackend.py", line 315, in generate
    self.generate_target(t)
  File "meson\mesonbuild\backend\ninjabackend.py", line 629, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "meson\mesonbuild\backend\ninjabackend.py", line 2121, in generate_single_compile
    commands = self._generate_single_compile(target, compiler, is_generated)
  File "meson\mesonbuild\backend\ninjabackend.py", line 2055, in _generate_single_compile
    commands += self.generate_basic_compiler_args(target, compiler, no_warn_args)
  File "meson\mesonbuild\backend\backends.py", line 605, in generate_basic_compiler_args
    commands += self.environment.coredata.get_external_args(target.for_machine, compiler.get_language())
  File "meson\mesonbuild\coredata.py", line 629, in get_external_args
    return self.compiler_options[for_machine][lang + '_args'].value
KeyError: 'cuda_args'
```

**Comment by scivision** [comment]
Windows Intel compiler reveals:
```
Checking that configuring works...
Traceback (most recent call last):
  File "run_project_tests.py", line 965, in <module>
    check_meson_commands_work()
  File "run_project_tests.py", line 874, in check_meson_commands_work
    raise RuntimeError('Failed to configure {!r}:\n{}\n{}'.format(testdir, e, o))
RuntimeError: Failed to configure 'test cases/common/1 trivial':
Traceback (most recent call last):
  File "meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "meson\mesonbuild\msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "meson\mesonbuild\interpreter.py", line 2158, in __init__
    self.parse_project()
  File "meson\mesonbuild\interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "meson\mesonbuild\interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson\mesonbuild\interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson\mesonbuild\interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson\mesonbuild\interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreter.py", line 2839, in func_project
    self.add_languages(proj_langs, True)
  File "meson\mesonbuild\interpreter.py", line 2950, in add_languages
    success = self.add_languages_for(args, required, MachineChoice.BUILD)
  File "meson\mesonbuild\interpreter.py", line 2969, in add_languages_for
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "meson\mesonbuild\compilers\c.py", line 64, in sanity_check
    return self.sanity_check_impl(work_dir, environment, 'sanitycheckc.c', code)
  File "meson\mesonbuild\compilers\mixins\clike.py", line 220, in sanity_check_impl
    cargs, largs = self._get_basic_compiler_args(environment, mode)
  File "meson\mesonbuild\compilers\mixins\clike.py", line 304, in _get_basic_compiler_args
    sys_args = env.coredata.get_external_args(self.for_machine, self.language)
  File "meson\mesonbuild\coredata.py", line 629, in get_external_args
    return self.compiler_options[for_machine][lang + '_args'].value
KeyError: 'c_args'

The Meson build system
Version: 0.52.999
Source dir: meson\test cases\common\1 trivial
```

**Comment by jpakkane** [comment]
Also for armclang:

```
File "/home/jpakkane/dcblinker/mesonbuild/environment.py", line 1071, in detect_c_compiler
    return self._detect_c_or_cpp_compiler('c', for_machine)
  File "/home/jpakkane/dcblinker/mesonbuild/environment.py", line 961, in _detect_c_or_cpp_compiler
    linker = ArmClangDynamicLinker(for_machine, [], version=version)
TypeError: __init__() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```

**Comment by jpakkane** [comment]
```
    def test_json_grammar_syntax_highlighting(self):

   ...

                builtin = set(each['match'].split('\\b(')[1].split(')\\b')[0].split('|'))
        self.assertEqual(builtin, set(interp.builtin.keys()))
>       self.assertEqual(funcs, set(interp.funcs.keys()))
E       AssertionError: Items in the second set but not the first:
E       'summary'
```

Errr, maybe a case of a missing rebase?

**Comment by jpakkane** [comment]
Armclang still fails, but in a different way, though:

```
  File "/home/jpakkane/dcblinker/mesonbuild/compilers/compilers.py", line 972, in get_compiler_args_for_mode
    args += self.get_always_args()
  File "/home/jpakkane/dcblinker/mesonbuild/compilers/mixins/clike.py", line 71, in get_always_args
    return ['-pipe'] + compilers.get_largefile_args(self)
  File "/home/jpakkane/dcblinker/mesonbuild/compilers/compilers.py", line 1206, in get_largefile_args
    if not (compiler.info.is_windows() or compiler.info.is_darwin()):
AttributeError: 'bool' object has no attribute 'is_windows'
```

Also remember that we do have an ARM compiler license for people on the dev team that I can hand out as needed.

**Comment by jpakkane** [comment]
It's important we get this in the next release, so this MR has an exception to the freeze deadline.

**Comment by scivision** [comment]
I am on the 54bacf0. All the above are still broken for me. I will post each result to avoid excessive long comment.

**Comment by scivision** [comment]
CUDA

```sh
meson\test cases\cuda\1 simple>meson build
```

```
The Meson build system
Version: 0.52.999
Source dir: meson\test cases\cuda\1 simple
Build dir: meson\test cases\cuda\1 simple\build
Build type: native build
Project name: simple
Project version: 1.0.0
Cuda compiler for the host machine: nvcc (nvcc 10.1.243)
Cuda linker for the host machine: nvcc nvlink 10.1.243
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja.EXE-1.9.0.git.kitware.dyndep-1.jobserver-1 at c:\Miniconda3\Scripts\ninja.EXE
Traceback (most recent call last):
  File "meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "meson\mesonbuild\msetup.py", line 215, in _generate
    intr.backend.generate(intr)
  File "meson\mesonbuild\backend\ninjabackend.py", line 315, in generate
    self.generate_target(t)
  File "meson\mesonbuild\backend\ninjabackend.py", line 629, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "meson\mesonbuild\backend\ninjabackend.py", line 2121, in generate_single_compile
    commands = self._generate_single_compile(target, compiler, is_generated)
  File "meson\mesonbuild\backend\ninjabackend.py", line 2055, in _generate_single_compile
    commands += self.generate_basic_compiler_args(target, compiler, no_warn_args)
  File "meson\mesonbuild\backend\backends.py", line 605, in generate_basic_compiler_args
    commands += self.environment.coredata.get_external_args(target.for_machine, compiler.get_language())
  File "meson\mesonbuild\coredata.py", line 629, in get_external_args
    return self.compiler_options[for_machine][lang + '_args'].value
KeyError: 'cuda_args'
```

**Comment by scivision** [comment]
PGI 19.10

```sh
meson\test cases\common\1 trivial>meson build
```

```
The Meson build system
Version: 0.52.999
Source dir: meson\test cases\common\1 trivial
Build dir: meson\test cases\common\1 trivial\build
Build type: native build
Project name: trivial test
Project version: undefined
Traceback (most recent call last):
  File "meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "meson\mesonbuild\msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "meson\mesonbuild\interpreter.py", line 2158, in __init__
    self.parse_project()
  File "meson\mesonbuild\interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "meson\mesonbuild\interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson\mesonbuild\interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson\mesonbuild\interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson\mesonbuild\interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreter.py", line 2839, in func_project
    self.add_languages(proj_langs, True)
  File "meson\mesonbuild\interpreter.py", line 2950, in add_languages
    success = self.add_languages_for(args, required, MachineChoice.BUILD)
  File "meson\mesonbuild\interpreter.py", line 2969, in add_languages_for
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "meson\mesonbuild\compilers\c.py", line 64, in sanity_check
    return self.sanity_check_impl(work_dir, environment, 'sanitycheckc.c', code)
  File "meson\mesonbuild\compilers\mixins\clike.py", line 220, in sanity_check_impl
    cargs, largs = self._get_basic_compiler_args(environment, mode)
  File "meson\mesonbuild\compilers\mixins\clike.py", line 304, in _get_basic_compiler_args
    sys_args = env.coredata.get_external_args(self.for_machine, self.language)
  File "meson\mesonbuild\coredata.py", line 629, in get_external_args
    return self.compiler_options[for_machine][lang + '_args'].value
KeyError: 'c_args'
```

**Comment by scivision** [comment]
for gcc, self.compiler_options[for_machine] has keys {'c_std', 'c_winlibs', 'c_args', 'c_link_args'} while the broken compilers have only {'c_std', 'c_winlibs'}

**Comment by scivision** [comment]
c_args etc. appear to be set in `compilers.py:get_global_options()` which is used by GCC but not the broken compilers

**Comment by scivision** [comment]
this "fixes" Intel icl but similar will be needed for other broken compilers

```patch
--- a/mesonbuild/environment.py
+++ b/mesonbuild/environment.py
@@ -1011,10 +1011,12 @@ class Environment:
                 return cls(
                     ccache + compiler, version, for_machine, is_cross, info,
                     exe_wrap, full_version=full_version, linker=linker)
+
             if 'Intel(R) C++ Intel(R)' in err:
                 version = search_version(err)
                 target = 'x86' if 'IA-32' in err else 'x86_64'
                 cls = IntelClCCompiler if lang == 'c' else IntelClCPPCompiler
+                self.coredata.add_lang_args(cls.language, cls, for_machine, self)
                 linker = XilinkDynamicLinker(for_machine, [], version=version)
                 return cls(
                     compiler, version, for_machine, is_cross, info=info,
```

**Comment by scivision** [comment]
this "fixes" Intel ifort

```patch
@@ -1176,8 +1179,10 @@ class Environment:
                 if 'Intel(R) Visual Fortran' in err:
                     version = search_version(err)
                     target = 'x86' if 'IA-32' in err else 'x86_64'
+                    cls = IntelClFortranCompiler
+                    self.coredata.add_lang_args(cls.language, cls, for_machine, self)
                     linker = XilinkDynamicLinker(for_machine, [], version=version)
-                    return IntelClFortranCompiler(
+                    return cls(
                         compiler, version, for_machine, is_cross, target,
                         info, exe_wrap, linker=linker)
```

**Comment by scivision** [comment]
PGI C and Fortran fixes

```patch
@@ -1045,10 +1047,12 @@ class Environment:
                     target, linker=linker)
             if 'PGI Compilers' in out:
                 cls = PGICCompiler if lang == 'c' else PGICPPCompiler
+                self.coredata.add_lang_args(cls.language, cls, for_machine, self)
                 linker = PGIDynamicLinker(compiler, for_machine, 'pgi', cls.LINKER_PREFIX, [], version=version)
                 return cls(
                     ccache + compiler, version, for_machine, is_cross,
                     info, exe_wrap, linker=linker)
```

```patch
@@ -1193,10 +1199,11 @@ class Environment:
                         exe_wrap, full_version=full_version)

                 if 'PGI Compilers' in out:
-                    linker = PGIDynamicLinker(
-                        compiler, for_machine, 'pgi',
-                        PGIFortranCompiler.LINKER_PREFIX, [], version=version)
-                    return PGIFortranCompiler(
+                    cls = PGIFortranCompiler
+                    self.coredata.add_lang_args(cls.language, cls, for_machine, self)
+                    linker = PGIDynamicLinker(compiler, for_machine, 'pgi',
+                        cls.LINKER_PREFIX, [], version=version)
+                    return cls(
                         compiler, version, for_machine, is_cross, info, exe_wrap,
                         full_version=full_version, linker=linker)
```

**Comment by scivision** [comment]
CUDA fix

```patch
@@ -1112,8 +1116,10 @@ class Environment:
             # the full version:
             version = out.strip().split('V')[-1]
             cpp_compiler = self.detect_cpp_compiler(for_machine)
+            cls = CudaCompiler
+            self.coredata.add_lang_args(cls.language, cls, for_machine, self)
             linker = CudaLinker(compiler, for_machine, 'nvlink', CudaCompiler.LINKER_PREFIX, [], version=CudaLinker.parse_version())
-            return CudaCompiler(ccache + compiler, version, for_machine, is_cross, exe_wrap, host_compiler=cpp_compiler, info=info, linker=linker)
+            return cls(ccache + compiler, version, for_machine, is_cross, exe_wrap, host_compiler=cpp_compiler, info=info, linker=linker)
         raise EnvironmentException('Could not find suitable CUDA compiler: "' + ' '.join(compilers) + '"')

     def detect_fortran_compiler(self, for_machine: MachineChoice):
```

**Comment by scivision** [comment]
It's quite probable the other non-GCC, non-Clang compilers are broken in the same way. How to address those? Round up some testers?

**Comment by jpakkane** [comment]
This fixes armclang on Linux:

```patch
diff --git a/cross/armclang-linux.txt b/cross/armclang-linux.txt
index 2772d827..6df78d61 100644
--- a/cross/armclang-linux.txt
+++ b/cross/armclang-linux.txt
@@ -26,7 +26,7 @@ ar = '/opt/arm/developmentstudio-2019.0/sw/ARMCompiler6.12/bin/armar'
 
 [properties]
 
-#c_args = ['--target=aarch64-arm-none-eabi']
+c_args = ['--target=aarch64-arm-none-eabi']
 
 [host_machine]
 system = 'baremetal'
diff --git a/mesonbuild/compilers/c.py b/mesonbuild/compilers/c.py
index db7abf03..20226466 100644
--- a/mesonbuild/compilers/c.py
+++ b/mesonbuild/compilers/c.py
@@ -145,7 +145,7 @@ class EmscriptenCCompiler(LinkerEnvVarsMixin, EmscriptenMixin, BasicLinkerIsComp
 
 class ArmclangCCompiler(ArmclangCompiler, CCompiler):
     def __init__(self, exelist, version, for_machine: MachineChoice,
-                 info: 'MachineInfo', is_cross, exe_wrapper=None, **kwargs):
+                 is_cross, info: 'MachineInfo', exe_wrapper=None, **kwargs):
         CCompiler.__init__(self, exelist, version, for_machine, is_cross,
                            info, exe_wrapper, **kwargs)
         ArmclangCompiler.__init__(self)
```

**Comment by jpakkane** [comment]
Merged as #6407.

**Pull request closed without merging**
