### PR TITLE
Fix gir gst regression

### PR DESCRIPTION
**Pull request by bruchar1**

### CODE REVIEW

**Comment by xclaesse** [comment]
@bruchar1 while I agree this fix this case, that means we need to do that in every single place we do `isinstance(lib, build.SharedLibrary)` in the whole Meson codebase. This is why I originally made BothLibraries subclass SharedLibrary. That got changed against my recommendation.

**Comment by xclaesse** [comment]
I think BothLibraries should exclusively be an interpreter concept. It's already a big mistake to even have that class in build.py, it should be an InterpreterObject inside interpreterobjects.py.

In build.py we need 2 classes (naming TBD):
```
class SharedLibraryWithStatic(SharedLibrary):
  def as_static(self):
    return self.static
class StaticLibraryWithShared(StaticLibrary):
  def as_shared(self):
    return self.shared
```

That way we are sure they are treaded exactly as a shared/static library everywhere, but we still can take their bother library for the specific case of as_shared() and as_static() methods.

**Comment by xclaesse** [comment]
@bruchar1 I made an alternative implementation in https://github.com/mesonbuild/meson/pull/13835. What do you think?

**Comment by bruchar1** [comment]
> @bruchar1 I made an alternative implementation in #13835. What do you think?

I like the idea. I'm trying to fix it here, since I cannot write to your branch...

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
I've reviewed this, it's correct. It fixes the problem.

We may need to have a bigger talk about handling both libraries. I'm not sure what that needs to look like. But for now lets unbreak the known broken case, and consider wider rework after that.

**Comment by tp-m** [comment]
Thanks everyone!

**Pull request merged**
