### PR TITLE
interpreter: add to_array method for bool values

### PR DESCRIPTION
**Pull request by bonzini**
This function enables a compact way to choose sources depending on configuration
options or on the build environment, like

    is_windows = host_machine.system() == 'windows'
    executable('prog', sources: [
        is_windows.to_array('util-win32.c'),
        (!is_windows).to_array('util-posix.c'),
        get_option('enable-foo').to_array('foo.c'),
        get_option('enable-bar').to_array('bar.c', 'bar-internal.c'),
        ...
    ])

### CODE REVIEW

**Comment by jpakkane** [comment]
Any particular reason you are not using the ternary operator:

```meson
executable('prog',
    is_windows ? ['util-win32.c'] : [],
    etc
)
```

Though in general the mesonific idiom is to do something like this:

```meson
all_sources = ['foo.c']
if is_windows
  all_sources += ['win.c']
endif
if whatever
  all_sources += something
endif

executable('prog', all_sources, ...)
```

**Comment by bonzini** [comment]
Regarding the second idiom, the second is a bit verbose, especially as I am converting a build system that is very configurable and used the Makefile idiom

   obj-$(CONFIG_FOO) += foo.o
   ...
    prog: $(obj-y)

I would like to maintain the same compact format.

Regarding the ternary operator it is certainly an option, but then so it is for `to_string`. I think that `to_array` is easier to parse on the brain (no need to look for the `:`, you know there's no else part) and more effective with editors (jumping to the matching `)` is easier than jumping to the `]` in the else part). It also has one fewer level of parentheses compared to `[(... ? [...]: [])]`.

**Comment by bonzini** [comment]
I pushed a small change to the release notes snippet, using a variable for the sources file to make the example a bit more idiomatic.

**Comment by jpakkane** [comment]
> I would like to maintain the same compact format.

The format is almost as compact with the ternary operator:
```meson
srcs = []
srcs += some_option ? files('foo.c') : []
srcs += other_option ? files('bar.c') : []
executable('bob', srcs, ...)
```
Given that this feature is very unlikely to be merged. It is non-obvious and looks confusing (well, to me at least).

**Comment by bonzini** [comment]
That's fine by me. Honestly this PR was just testing the waters before contributing a more complex feature.

**Pull request closed without merging**
