### PR TITLE
new wrap-mode: forcefallback

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
This can be useful to make sure that a project builds when
its fallbacks are used on systems where external dependencies
satisfy the version requirements, or to easily hack on the sources
of a dependency for which a fallback exists.

### CODE REVIEW

**Comment by nirbheek** [comment]
Nitpick: I always imagined this option to be called `onlyfallback`, although I am not married to it. :)

**Comment by MathieuDuponchelle** [comment]
travis build is screwed up, blocks on `test_testsetup_selection` half the time

**Comment by tp-m** [comment]
How about `forcefallback` ? :)

**Comment by nirbheek** [comment]
`forcefallback` is even better!

**Comment by MathieuDuponchelle** [comment]
yeah, works for me :)

**Comment by MathieuDuponchelle** [comment]
@jon-turney done, thanks!

**Comment by jpakkane** [comment]
Just two things. The FAQ addition should mention that this functionality is only available since 0.46.0.

Second of all there should be a test. Since the test suite requires zlib to be installed, there should be a test which has a "zlib subproject" that only has something like a single dummy function `int fake_zlib()` or something and a project that tries to use it with `dependency('zlib', fallback: ...)` and which checks that it picked up the fake internal zlib and not the real one.

Once those are done, this is ok to merge by anyone with admin rights.

**Comment by MathieuDuponchelle** [comment]
@jpakkane sure, will do :)

**Comment by MathieuDuponchelle** [comment]
CI still screwing up it seems, unrelated errors :(

**Comment by jpakkane** [comment]
The error message is this:

    ERROR: test_forcefallback (__main__.AllPlatformTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "run_unittests.py", line 956, in test_forcefallback
        self.build()
      File "run_unittests.py", line 587, in build
        return self._run(self.build_command + args + extra_args, workdir=self.builddir)
      File "run_unittests.py", line 537, in _run
        raise subprocess.CalledProcessError(p.returncode, command)
    subprocess.CalledProcessError: Command '['ninja', '-w', 'dupbuild=err', '-d', 'explain']' returned non-zero exit status 1

Which seems relevant.

**Comment by MathieuDuponchelle** [comment]
@jpakkane hrm you're right, thought it was stuck at the "upload artifacts" stage for some reason, any idea what could cause that issue?

**Comment by MathieuDuponchelle** [comment]
Probably the lack of exported symbols

**Pull request merged**
