### PR TITLE
Use pkg-config to find tools in the GNOME module

### LINKED ISSUE #2400: gnome.generate_gir() not using pkg-config bin path
I've installed a later version of gir in a custom directory. PKG_CONFIG_PATH is setup for this directory. meson finds the new version of gir but uses the system gir instead of the gir in the bindir of the gobject-introspection-1.0 pkg-config.

```
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Native dependency gobject-introspection-1.0 found: YES 1.54.0
```
1.54 is the new version. System vesion is 1.5.0.

### PR DESCRIPTION
**Pull request by ebassi**
We should not rely on `PATH` being overridden, and instead use pkg-config variables.

Closes #2400

### CODE REVIEW

**Comment by nirbheek** [comment]
To avoid regressing setups that don't use pkg-config but use meson (such as some windows setups), shouldn't we fallback to looking in `PATH` if the pkg-config dependency (`gio-2.0` or `glib-2.0`) was not found?

I think this change also breaks `override_find_program()` since programs are overriden by name. So the order should be: `override_find_program()`, then `pkg-config`, then `PATH`.

**Comment by xclaesse** [comment]
Yes please make sure to not break override_find_program() case, I would like to be able to use the gnome module in glib itself, and when glib is built as subproject.

**Comment by jpakkane** [comment]
> the order should be: override_find_program(), then pkg-config, then PATH.

Yes. Or possibly `PATH` before pkg-config. But override should definitely be first.

**Comment by nirbheek** [comment]
> Or possibly `PATH` before pkg-config

You might pick up the wrong pkg-config if you use `PATH` first (f.ex., `pkg-config` from the build prefix instead of `some-prefix-pkg-config` from the host prefix).

**Comment by eli-schwartz** [comment]
This was eventually fixed piecemeal by #6687, amended in #6696, made to support subprojects in #7020 (at which time it finally began respecting pkg-config first), and fixed yet again in #7072 to respect cross file wrapper overrides.

As of commit b5100fe86aa83d64957cc2e502bd515dbe24e523 it should actually work reliably. I guess it's a pity that the initial review comments here were totally forgotten about when these other PRs were submitted, as half of them could have used considerable polish for the same reason this one got stuck in limbo...

**Pull request closed without merging**
