### PR TITLE
New options for controlling test output.

### PR DESCRIPTION
**Pull request by trhd**
It is at times very inconvenient to have stdout and stderr separated in
the test logs as the relation between different messages (from stdout and
stderr) gets lost. Comparing time stamps can also be very tedious. An
option for disabling this feature thus seemed useful.

It is at times also very inconvenient to get the output of failed tests
printed to the user at the end of testing. Individual test logs can get
huge in some projects in which case the actual results of all the tests
can e.g. get flushed away from the terminal (the size of the scrollback
buffer is usually limited). An option for controlling how the output of
failed tests gets shown to the user was hence seen as a useful addition.

These changes introduce the options --no-stdsplit for disabling the
division of tests' output to stdout and stderr and --test-output for
controlling how the failed tests' output is shown during testing. The
latter expects one of the following arguments: 'none' (no logs from tests
get printed directly to the user), 'mix' (the output of failed tests gets
printed immediately to the user) and 'append' (the output of all the
failed tests gets printed to the user after the last test has been
executed).

### CODE REVIEW

**Comment by jpakkane** [comment]
All of the refactoring work is excellent and we definitely want that in. As for the actual functionality, something like this useful, but what I'm wondering if we could achieve the same without adding extra options. We don't want to end up where Git is by having a bazillion arguments for everything.

The problem of scrollback could, for example, be solved by only printing the error output if it is shorter than some threshold. 'Mix' seems also a poor choice to have because it causes output from two different sources (the framework and test itself) to be mixed. One would imagine the common use case would be to run the tests and when the first error happens the user presses `ctrl-c` to break the tests. This would then print the error messages.

**Comment by trhd** [comment]
On 12:24 Mon 14 Mar, Jussi Pakkanen wrote:
> but what I'm wondering if we could achieve the same without adding extra options.

By options here do you refer to new CLI options or does that include new
build options as well (that are configurable via mesonconf)?

I wouldn't mind dropping the command line switches from meson.py but I
think something configurable might be needed.

> The problem of scrollback could, for example, be solved by only printing the error output if it is shorter than some threshold.

I thought of this but concluded that some people might want to run the
tests in a CI configuration in which case they'd probably want to have
the whole output of the failing tests. That way there wouldn't
necessarily be a need to go through the build artifacts as the whole log
of a failing test would be visible in the "main log".

> 'Mix' seems also a poor choice to have because it causes output from two different sources (the framework and test itself) to be mixed.

I included this mainly because I think I saw somewhere somebody asking
for something like this (and it was pretty much zero extra effort). Not
100% sure anymore though.

Personally I have so far preferred the most the "none" option that was
implemented in the patches. I think the summary of all the tests is the
most important part of the output and I can dig into the log files when
needed. Even after that, I think the readability of the output of the
"mix" mode is better than that of the "append" mode. Your mileage may of
course vary.

> One would imagine the common use case would be to run the tests and when the first error happens the user presses `ctrl-c` to break the tests. This would then print the error messages.

Perhaps, but if one has a powerful multicore machine running verbose
tests in parallel then things get nasty pretty quickly.

**Comment by trhd** [comment]
Rebased, dropped the CLI options and did some cleaning up.

**Comment by jpakkane** [comment]
> That way there wouldn't necessarily be a need to go through the build artifacts as the whole log of a failing test would be visible in the "main log".

I would imagine people (I personally certainly do) want to have all tests separate. Having them all in one clump is annoying because you need to visually parse the parts to find the tests you care about and so on.

**Comment by trhd** [comment]
>> That way there wouldn't necessarily be a need to go through the build artifacts as the whole log of a failing test would be visible in the "main log".

> I would imagine people (I personally certainly do) want to have all tests separate. Having them all in one clump is annoying because you need to visually parse the parts to find the tests you care about and so on.

You lost me there a bit. How would the tests be any less separate than before? Too much info in one file? I wouldn't think that would be a problem especially in a CI environment.

Anyhow, I did update the branch. The "errorlogs" option is now just a boolean flag defining whether to print the error logs at the end of testing or not (it will print that last 100 lines from at most 10 tests).

Also, a couple of bug fixes.

**Comment by jpakkane** [comment]
After a trial merge this fails with the following:

    Traceback (most recent call last):
      File "./meson.py", line 17, in <module>
        from mesonbuild import mesonmain
      File "/home/jpakkane/workspace/meson/mesonbuild/mesonmain.py", line 37
        **({ 'choices' : c } if c and kwargs.get('action', None) != 'store_true' else {}),
                                                                                         ^
    SyntaxError: invalid syntax

**Comment by trhd** [comment]
Which python version are you using?

**Comment by jpakkane** [comment]
3.4.3

**Comment by trhd** [comment]
Should be fixed now. I had used some Python 3.5-only features.

**Pull request merged**
