### PR TITLE
dependencies/ui: Fix qt compiler detection when bindir is set

### PR DESCRIPTION
**Pull request by dcbaker**
Fixes: #4527

### CODE REVIEW

**Comment by dcbaker** [comment]
@jon-turney, does this fix your test case?

**Comment by jon-turney** [comment]
Yes, thank you.

Does this have no coverage in meson test cases?  Or does it work in CI for another reason?

**Comment by dcbaker** [comment]
I'm not sure, I could only replicated this in a debian-like environment, so I would think that it would trigger in CI?

**Comment by jon-turney** [comment]
I guess that means there is no test, then.

**Pull request merged**
