### PR TITLE
introspect: Allow listing all installed files

### PR DESCRIPTION
**Pull request by thiblahute**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
hmm, planning to make uninstall target in backends?

**Comment by thiblahute** [comment]
> hmm, planning to make uninstall target in backends?

Not really, not sure it is anyhow related, I need that information to setup extra env vars in a generic way in `gst-uninstalled` and I believe it is generally useful to have :)

**Comment by TingPing** [comment]
Can be useful for Builder also since we need a way to see installed scripts.

**Comment by TingPing** [comment]
Perhaps we should always prepend the prefix to the install path? Otherwise we can get an inconsistent mix of relative and absolute paths, the latter having no clear indication of prefix without another meson call.

**Comment by ignatenkobrain** [comment]
@TingPing hopefully, by prepend you mean join paths, not just prepend ;)

**Comment by TingPing** [comment]
Of course.

**Comment by thiblahute** [comment]
> Perhaps we should always prepend the prefix to the install path? Otherwise we can get an inconsistent mix of relative and absolute paths, the former having no clear indication of prefix without another meson call.

Done

**Comment by jpakkane** [comment]
When installing we write a list of all installed files to `meson-logs/install-log.txt`. This includes stuff like all files installed with `install_subdir`.

**Comment by thiblahute** [comment]
Well, that does not solve anything in my case (and in many cases) where we
want to have the info before installing or even building.

**Pull request merged**
