### PR TITLE
resolve symlinks passed to -C

### PR DESCRIPTION
**Pull request by bonzini**
`meson setup` is resolving symlinks for the build directory in
`validate_core_dirs`.  For consistency with it, do the same when
the build directory is passed via -C to devenv, dist, init, install
and test.
    
This ensures for example that the path to test dependencies is
computed correctly in `meson test`.
    
Fixes: #8765

### CODE REVIEW

**Comment by mensinda** [comment]
This should come with a test case, otherwise LTGM.

**Comment by bonzini** [comment]
All failures seem independent (mpi, SubprojectsCommandTests.test_purge, and coverage should have gone up rather than down.

**Review by mensinda — APPROVED** [review]
LGTM, see the discussion in #8970 for merging.

**Comment by nirbheek** [comment]
FTR: This is also in the 0.58.2 release, but the milestone only shows 0.59.1 because it was merged after 0.59.0 and will be in that stable release too.

**Pull request merged**
