### PR TITLE
BUGFIX: allow Fortran submodule to have same name as module

### PR DESCRIPTION
**Pull request by scivision**
The Fortran 2018 standard allows `submodule` to have:
* same name as ancestor `module`
* same name as `submodule` with a different ancestor

which are fixed by this PR.

This also fixes a bug where submodule filenames `*.smod` or `*.mod` depending on the compiler were not correctly generated for all compilers, causing Ninja to needlessly regenerate build.ninja for each `ninja` command.

### CODE REVIEW

**Comment by scivision** [comment]
Thanks, I made the submodule pattern a constant for DRY

**Comment by jpakkane** [comment]
:crossed_swords: conflicts.

**Comment by scivision** [comment]
Oh yea Re: merge conflict. I had to make this same area of code recursive to allow Fortran `include` directive to work. I can fix it.

**Comment by scivision** [comment]
@jpakkane I fixed the merge conflicts, this is good to go. Thanks!

**Comment by jpakkane** [comment]
This needs a test, though.

**Comment by scivision** [comment]
@jpakkane I updated the test to cover this added functionality.

**Pull request merged**
