### PR TITLE
Fix dependency('qt') crash with old Qt on OSX

### PR DESCRIPTION
**Pull request by jon-turney**
Don't fail with 'KeyError: QMAKE_XSPEC' if `qmake -query` doesn't report QMAKE_XSPEC. (Seen with Qt 4.8.7)

### CODE REVIEW

**Comment by jon-turney** [comment]
Look like this has been broken since #4845.

You can install qt4 for osx using:
```
brew tap cartr/qt4
brew install qt@4
```
but this is hard to test in CI since homebrew doesn't allow you to have both qt4 and qt5 in PATH.

**Comment by jon-turney** [comment]
> but this is hard to test in CI since homebrew doesn't allow you to have both qt4 and qt5 in PATH.

It looks like we have alredy have some similar testing in `.github/workflows/ci_frameworks.yml`, I'll see if I can extend that to cover this.

**Comment by dcbaker** [comment]
This look good to me, and I'm ready to merge if you are @jon-turney

**Comment by jon-turney** [comment]
> This look good to me, and I'm ready to merge if you are @jon-turney

Yes, thanks.

**Pull request merged**
