### PR TITLE
Clean MSI generator Try 2

### PR DESCRIPTION
**Pull request by michaelbadcrumble**
Simply updated the code to conform with Python recommendations based on PyLinter locates in the project.

### CODE REVIEW

**Comment by jpakkane** [comment]
> Uppercase to conform to Python recommendations

What recommendation is this? Why should this particular variable name be in all upper case?

**Comment by michaelbadcrumble** [comment]
The PyLinter though it was a constant, and constant usually needed to be uppercase.

**Comment by jpakkane** [comment]
That is clearly a bug in pylinter then. That is most definitely and obviously not a constant. Fixing it this way is not the right way to go, because it worsens the readability and thus understandability of the code just to conform to a broken tool. This should be dealt with a comment annotation instead, or, if Pylinter does not support that, left as is and reported as a bug upstream.

**Comment by michaelbadcrumble** [comment]
🤨
A bug in PyLinter.  Sure thing I would love to change that variable name back, but what should use in future to better avoid this mistake?

**Pull request merged**
