### PR TITLE
tvOS: added support AppleTVOS

### PR DESCRIPTION
**Pull request by roman-shpuntov**
There is difference between Apple iOS and tvOS. This patch provides tvOS support.

### CODE REVIEW

**Comment by jpakkane** [comment]
I have no experience with tvOS, but it would be nice to get full support. Does tvOS work with the same cross file as iOS or does it require something special? If it does, please add a cross file in the `cross` directory for tvOS. Then try running the cross build test suite with your cross file and report if all tests pass. Thanks.

**Comment by roman-shpuntov** [comment]
> I have no experience with tvOS, but it would be nice to get full support. Does tvOS work with the same cross file as iOS or does it require something special? If it does, please add a cross file in the `cross` directory for tvOS. Then try running the cross build test suite with your cross file and report if all tests pass. Thanks.

Yes, it does. I have tested with AppleTVOS 12.0. The result of cross test inside attached file

[result.txt](https://github.com/mesonbuild/meson/files/3281493/result.txt)

**Comment by Ericson2314** [comment]
Lets do #4852 first. In Apple's latest treatment, `macOS` `iOS` `tvOS`, and `watchOS` are all OSes with equal footing built around XNU. See http://llvm.org/doxygen/Triple_8cpp_source.html#l00511

**Comment by roman-shpuntov** [comment]
There is compatible on compiler level, but not on linking. I tried to use gstreamer for tvOS:

`ld: in /Users/roman/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/GStreamer(libglib-2_0_a_arm64_-libglib_2_0_la-garray.o), building for tvOS, but linking in object file built for iOS, for architecture arm64`

and also from #4852 

`watchOS and tvOS are distinct derivatives of iOS`


#4852 is good idea, but changes inside this patch is enough for me now.

**Comment by Ericson2314** [comment]
@roman-shpuntov Yeah the linking incompatibility makes sense. Not all userlands are binary compatible.

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
