### PR TITLE
Use 'generate_basic_compiler_args' for Vala targets

### PR DESCRIPTION
**Pull request by arteymix**
It will likely conflict with #954 as `generate_basic_compiler_args` already deal with global arguments.

### CODE REVIEW

**Comment by arteymix** [comment]
Same. I know that the order of some arguments changed (i.e. project vs global) so it's worth checking more extensively.

**Comment by jpakkane** [comment]
:crossed_swords: conflicts.

**Comment by arteymix** [comment]
It's now rebased!

**Comment by jpakkane** [comment]
LGTM.

**Comment by jpakkane** [comment]
This message is posted to every outstanding merge request.

We have transitioned from Github wiki to our new documentation system that generates all documentation directly from the Git repo. This means that from now on every merge request must come with corresponding documentation changes.

If your MR requires documentation changes, do the necessary changes to files in `docs/markdown`.

If your MR adds a new feature, add a description to the release notes in `docs/markdown/Release-notes-for-0.41.0.md`.

If this commit is just a bugfix with no functional changes, you don't need to do anything.

Thank you

**Pull request merged**
