### PR TITLE
docs: Import the website and wiki and build with hotdoc

### PR DESCRIPTION
**Pull request by thiblahute**
This allows us to more easily have the documentation in sync with
the source code as people will have to document new features etc
right at the time where they implement it.

Current version is avalaible here: https://thiblahute.github.io/jpakkane.github.io/

### CODE REVIEW

**Comment by QuLogic** [comment]
On mobile:
* The site-wide ToC is in a hidden sidebar on the left. The top shortcuts end up in the "hamburger" menu. This seems a bit confusing. A bootstrap-type layout would use the "hamburger" menu for the site-wide ToC; not sure the shortcuts should even be visible on mobile.
* Exacerbating the above, the sidebar arrow wants to hide itself. There doesn't seem to be any reason for it; the space doesn't really come back and it means you need two taps to get the arrow and then show/hide the sidebar. Sometimes it doesn't even trigger.
* The site-wide ToC does not always scroll properly; I'm not sure what causes it. It'll scroll the main content even though you aren't at the end of the ToC.

On desktop:
* The expanding Edit on GitHub button causes the page-level ToC to move around unnecessarily.
* For pages with long ToCs, scrolling a bit until the sublevels are open causes a scrollbar to appear, and shift the Edit on GitHub button a bit.
* On the Videos page, the page ToC overlaps most of the videos.

For the order:
* Maybe Quick Guide and Tutorial can be merged?
* The Manual section definitely needs adjustment, though I don't have time to go through every entry.
* Reference and Wrap manual can go nearer the end.
* Several of the Additional Documentation entries can be deleted.
* How do I do X in Meson? could maybe go in the FAQ.
* Not sure if Reproducible builds deserves a top-level entry.
* Release notes order should be reversed.

**Comment by thiblahute** [comment]
# On mobile:

* [ ] : The site-wide ToC is in a hidden sidebar on the left. The top shortcuts end up in the "hamburger" menu. 
 This seems a bit confusing. A bootstrap-type layout would use the "hamburger" menu for the site-wide ToC; not sure the shortcuts should even be visible on mobile.
* [ ] : Exacerbating the above, the sidebar arrow wants to hide itself. There doesn't seem to be any reason for it; the space doesn't really come back and it means you need two taps to get the arrow and then show/hide the sidebar. Sometimes it doesn't even trigger.
* [ ] : The site-wide ToC does not always scroll properly; I'm not sure what causes it. It'll scroll the main content even though you aren't at the end of the ToC.

# On desktop:

* [x] : The expanding Edit on GitHub button causes the page-level ToC to move around unnecessarily.
* [x] : For pages with long ToCs, scrolling a bit until the sublevels are open causes a scrollbar to appear, and shift the Edit on GitHub button a bit.
* [ ] : On the Videos page, the page ToC overlaps most of the videos.

**Comment by thiblahute** [comment]
@jpakkane I feel that the more we wait to merge the more complicated it will get to rebase from the old wiki, could we try and agree on a plan and get that done ASAP?

**Comment by jpakkane** [comment]
Current priority is the next release but we'll try to get this done immediately after that. I'll ask poeple on the IRC channel to add their comments here.

**Comment by TingPing** [comment]
I do agree some reorganization could be done with the pages, but all of my main complaints with the site itself have been fixed.

**Comment by MathieuDuponchelle** [comment]
For what it's worth, I'm making some time to address some of @QuLogic 's remaining remarks for mobile

**Comment by MathieuDuponchelle** [comment]
To see the work done on mobile:

https://people.collabora.com/~meh/meson-doc/index.html

@QuLogic , can you indicate whether this addresses some of the points you raised ?

**Comment by QuLogic** [comment]
I just tried it out on mobile and it looks pretty nice. I still think the hamburger menu is not needed. The side menus are a little bit buggy; you can make a sort of J or L shape and the "hook" doesn't need to be very big, which triggers the sidebar a bit too easily.

**Comment by TingPing** [comment]
Just do document it here, the new mobile work thinks my resolution is a phone and hides the sidebars. (This is a 1080p monitor but window at like half width)

**Comment by MathieuDuponchelle** [comment]
> Just do document it here, the new mobile work thinks my resolution is a phone and hides the sidebars. (This is a 1080p monitor but window at like half width)

It doesn't *think* anything, It's simply that below a certain width (1200 pixels) we choose to show only the content, as we consider it to have more importance than the navigation, which is still available by clicking on the arrows left and right of the navbar.

It's possible that between 992 and 1200 px I'll want to keep the sitenav and only hide the toc, but in any case if you go below a certain width, you'll always end up with the sidenavs folded.

**Comment by jpakkane** [comment]
Trying to build this with the release version of hotdoc fails with an "unknown error", which is a KeyError on `hd_utils.html` on `src/wheezy/template/engine.py` line 70.

**Comment by MathieuDuponchelle** [comment]
@jpakkane , I haven't put out a new release yet, if you want to build this *now* you'll need master. I want to validate the new output before putting out a new release, makes sense ?

**Comment by MathieuDuponchelle** [comment]
>  I still think the hamburger menu is not needed.

It is for some applications, when documenting an API it holds the API version dropdown lists for example. In our case, I think it's as valid to have it hold the shortcuts as it is for the navbar to hold them on desktops, whether the shortcuts are necessary at all is another question, but I did agree with @TingPing when I added them.

>  you can make a sort of J or L shape and the "hook" doesn't need to be very big

I can tweak the thresholds a little

**Comment by jpakkane** [comment]
> I want to validate the new output before putting out a new release, makes sense ?

Sure, but this is currently blocking other merges. We want to get this done so that the wiki does not get out of sync again.

**Comment by thiblahute** [comment]
Cherry picked latest changes fom the wiki.

**Comment by thiblahute** [comment]
Hotdoc has just been released, I think everything should be good now on our side :-)

**Comment by jpakkane** [comment]
Updated the [experimental web site](http://mesonbuild.com/experimental/).

**Comment by jpakkane** [comment]
The license requires some thinking. The wiki will have many code samples that we want people to just copy and paste to their own projects. Attribution and share alike do not really mesh with that.

**Comment by thiblahute** [comment]
> The license requires some thinking. The wiki will have many code samples that we want people to just copy and paste to their own projects. Attribution and share alike do not really mesh with that.

Indeed, it should be a very permissive license I think.

**Comment by TingPing** [comment]
We could just say all code snippets are under the CC0 (public domain).

**Comment by MathieuDuponchelle** [comment]
tbh I'd say both the documentation and code snippets are public domain to keep things simple

**Comment by jpakkane** [comment]
Public domain is legally dubious and should not be used. This is sad but that's international copyright law for you. 😢

**Comment by ignatenkobrain** [comment]
I would prefer to have docs and examples under CC0

**Comment by TingPing** [comment]
> Public domain is legally dubious and should not be used. This is sad but that's international copyright law for you. :cry:

That is why the CC0 exists it goes beyond "dedicated to the public domain" and defines as close as it can what that means for countries that do not legally have such a concept.

**Comment by QuLogic** [comment]
With a name like `tmp.json`, is that file really supposed to be added?

**Comment by MathieuDuponchelle** [comment]
@QuLogic nope, I think @thiblahute was just toying there, good catch :)

**Pull request merged**
