### PR TITLE
Rust module : Add support for cargo subprojects

### PR DESCRIPTION
**Pull request by dcbaker**
I want to preface this that this is still a work in progress, there's a *lot* left to do, but I have been able to compile a couple of simple demo projects with this, so we've gotten to the point that "something works". I'm sharing this mostly to get a little visibility into the work.

The end goal is to be able to build Rust crates as fully native Meson subprojects, there's still some work to do on a lot of fronts, but it's getting there.

### CODE REVIEW

**Comment by jpakkane** [comment]
Does someone who actually knows how this should work want to review this?

**Comment by bauen1** [comment]
Related to #2173

For fetching crates, there is [cargo-download](https://docs.rs/crate/cargo-download/0.1.2).

I was looking into setting up an embedded rust project with meson (to make it easy to integrate into C/C++ projects), and the lack of crates support is annoying. I was hacking up a way to build the crates I need with a combination of `cargo download` and `cargo build`, but this would be much better.

**Comment by dcbaker** [comment]
I might look at cargo download. My preference would be to not have *any* dependency on cargo at all, but we'll just have to see once this is actually in a state to land.

**Comment by DemiMarie** [comment]
@dcbaker I don’t think that avoiding a Cargo dependency is realistic.  Cargo does a massive amount of work related to stuff like dependency resolving, some of which is even (if I understand it correctly) NP-complete (so you won’t be able to practically reimplement it in pure Python without massive performance hits).

What I *do* consider realistic is building Rust code that vendors its dependencies (via `cargo vendor`).  That avoids having to interact with `crates.io`, which is in and of itself subtle (consider stuff like HTTP proxies, git fetching with CLI vs libgit2, etc).  In short, I recommend letting Cargo do all of the network I/O; Meson can then do the actual building.

**Comment by eli-schwartz** [comment]
Handling rust dependencies as subprojects means that none of this matters. Subprojects are a form of vendoring which uses pinned versions, so the only dependency resolution involved is "use it? Yes or no?" And if yes, "here is exactly one url which may be used to acquire it".

**Comment by dcbaker** [comment]
Right, and my plan initially is to use cargo vendor to do that vendoring. Long term i would like meson wrap to be able to handle it, which is not run so build or compile time, so the cost is paid once and then checked into git, making the cost relatively small

**Comment by Ericson2314** [comment]
FYI c.f. https://github.com/kolloch/crate2nix and https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/rust/build-rust-crate, which build Rust crates from the lockfile with little use of Cargo itself. `crate2nix` uses some libraries from Cargo just to be able to share data structures and parsing. `buildRustCrate` seems to just use `cargo metadata`.

**Comment by bonzini** [comment]
Hi @dcbaker, what is the state of this? I might be able to spend some time on it.

It seems plausible to rely solely on `cargo update` to build Cargo.lock + `cargo vendor subprojects` for the downloading, possibly mapping `meson subprojects` commands to cargo commands too.

**Comment by dcbaker** [comment]
This should really be closed in favor of #10151

The basic problem I've run into is that so many of the core types are really tied up in the interpreter, so I wrote all of the code to fix the build.py problem, and that's stalled. If you wanna help me figure out why #10714 all works fine for me but fails utterly in CI that would be super helpful :)

**Comment by bonzini** [comment]
Ok in the past I tried bisecting the failure, I can try doing that here too.

**Pull request closed without merging**
