### PR TITLE
flake8: ignore E203 (whitespace before ':')

### PR DESCRIPTION
**Pull request by msink**

### CODE REVIEW

**Comment by nirbheek** [comment]
I agree with @ignatenkobrain. This is a very widely-used part of PEP8. I've actually never seen Python code (outside of a few parts of Meson) that does not obey this.

**Comment by msink** [comment]
I too prefer not use space before colon, but Jussi consistently does.
(maybe because in Finnish colon is used like apostrophe in English)

**Comment by ignatenkobrain** [comment]
@msink in meson.build space before colon looks neat, but not in python :)

**Comment by jpakkane** [comment]
The parts where there is a space before the key (in Python) are there by accident. We should probably fix those instead.

**Pull request closed without merging**
