### PR TITLE
Make parser errors print relative path to meson.build file

### PR DESCRIPTION
**Pull request by NickeZ**
Implemented this for fun.

Fixes: #5946

### CODE REVIEW

**Comment by xclaesse** [comment]
I like they idea, I gave a quick try, and got that:
  File "/home/xclaesse/programmation/meson/mesonbuild/mlog.py", line 233, in get_relative_path
    return Path(os.path.join(*['..' for x in path.parts])) / target.name
TypeError: join() missing 1 required positional argument: 'a'

**Comment by NickeZ** [comment]
`os.path.join` isn't even necessary there. I removed it.

I tested many things:
* running`meson build` in `project` directory (where `project` has a `meson.build` file)
* running `ninja` in `project/build`. (first with a valid meson file, and then with a broken)
* running `ninja` in `build` (where `build` is in the same directory as `project`) (first with a valid meson file, and then with a broken)

Please tell me exactly what you ran that didn't work.

**Comment by jpakkane** [comment]
I tested this also and it seemed to work. @xclaesse can you still reproduce your error? If yes, how?

**Comment by xclaesse** [comment]
Can't reproduce the backtrace any more, I don't remember exactly what I was doing.

But relative path is not consistent:
```meson
project('foo')
foo = dependency ()
```

That says:  `meson.build:3:0: ERROR: Expected 1 arguments, got 0.` instead of `../meson.build`

**Comment by NickeZ** [comment]
> Can't reproduce the backtrace any more, I don't remember exactly what I was doing.
> 
> But relative path is not consistent:
> 
> ```meson
> project('foo')
> foo = dependency ()
> ```
> 
> That says: `meson.build:3:0: ERROR: Expected 1 arguments, got 0.` instead of `../meson.build`

You have to specify from where you ran meson. Did you run it in the project directory or in a build directory? And also how you ran it.

The first time you run `meson build` the working dir is actually the project dir and `meson.build` would be the correct path. If you then run `ninja -C build` the working dir is actually `build` and `../meson.build` is the correct path.

**Comment by jpakkane** [comment]
Why are you calculating the path by hand instead of using [existing pathlib functionailty](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to)?

**Comment by jpakkane** [comment]
The only reason you should get a ValueError is if the build and source dirs are on separate Windows drives. I think we even have a function that checks that and returns an absolute path if a relative can't be made.

**Comment by NickeZ** [comment]
As far as I could understand it didn't work in this case because the paths don't share ancestors.

```
>>> Path("/home/user/project/meson.build").relative_to(Path("/tmp/build"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/pathlib.py", line 876, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/home/user/project/meson.build' does not start with '/tmp/build'
```

```
>>> Path("/tmp/build").relative_to(Path("/home/user/project/meson.build"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/pathlib.py", line 876, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/tmp/build' does not start with '/home/user/project/meson.build'
```

**Comment by jpakkane** [comment]
Works for me.

**Comment by jon-turney** [comment]
This only changes one, of the several places, that a filename is attached to a MesonException.
This doesn't change how are filenames are reported in warnings, at all.

> But relative path is not consistent:
> 
> ```meson
> project('foo')
> foo = dependency ()
> ```
> 
> That says: `meson.build:3:0: ERROR: Expected 1 arguments, got 0.` instead of `../meson.build`

That the reporting doesn't change when cwd is changed for that error is easily demonstrable with that example:

```
jon@tambora /work/example
$ meson _build
The Meson build system
Version: 0.53.999
Source dir: /work/example
Build dir: /work/example/_build
Build type: native build
Project name: foo
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:2:0: ERROR: Expected 1 arguments, got 0.

A full log can be found at /work/example/_build/meson-logs/meson-log.txt

jon@tambora /work/example
$ cd ..

jon@tambora /work
$ meson example _build
The Meson build system
Version: 0.53.999
Source dir: /work/example
Build dir: /work/_build
Build type: native build
Project name: foo
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:2:0: ERROR: Expected 1 arguments, got 0.

A full log can be found at /work/_build/meson-logs/meson-log.txt
```

**Pull request merged**
