### PR TITLE
vala: Add a shared module testcase using 'GLib.TypeModule'

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by nirbheek** [comment]
Test fails with unity builds, are you looking into that?

**Comment by arteymix** [comment]
@nirbheek I have my finals this week, so maybe later on.

**Comment by jpakkane** [comment]
This message is posted to every outstanding merge request.

We have transitioned from Github wiki to our new documentation system that generates all documentation directly from the Git repo. This means that from now on every merge request must come with corresponding documentation changes.

If your MR requires documentation changes, do the necessary changes to files in `docs/markdown`.

If your MR adds a new feature, add a description to the release notes in `docs/markdown/Release-notes-for-0.41.0.md`.

If this commit is just a bugfix with no functional changes, you don't need to do anything.

Thank you

**Comment by jpakkane** [comment]
ping

**Comment by arteymix** [comment]
It should be good now, it seems like unity builds were fixed elsewhere.

**Pull request merged**
