### PR TITLE
dependency: Allow passing patterns to 'static' kwarg

### LINKED ISSUE #2765: Meson equivalent to libtool's -static-libtool-libs
The "-static-libtool-libs" argument to libtool tells it only statically link libraries that have a ".la" files, but to dynamically link other libraries.

The use-case is the following:

* A "device" SDK containing dynamic and static versions libc, libm, libpthread, openssl, etc  and the headers
* An "app SDK" built using Cerbero that contains GLib, GStreamer, etc

The device contains the .so files for libraries that are also in its SDK. I want to create the smallest possible binary for my device using GStreamer. So I want the files coming from the "app SDK" to be statically linked into my application, but the files from the "platform SDK" to be static.

Currently, the way I do it is by making sure there are no ".la" files in the "device SDK", but that the "app SDK" always has a .la file.. Then I use the "-static-libtool-libs" option to libtool and it just works.

I suggest doing the same with .pc files. I think the trick is to take the output of "pkg-config --libs --static" and of "pkg-config --libs", and if a library is in both, add it to the list of static libraries. If a library is only in "pkgconfig --libs --static" then add it to the general list.. When all the libraries have been processed, remove all "static" libs from the general list. Then we'll have 2 lists, the "static" list.. which must be statically linked, and the "general list" which must be dynamically linked...

### PR DESCRIPTION
**Pull request by xclaesse**
Passing 'static:true' to dependency() will try to static link the
    dependency, but also dependencies of the dependency, etc. This could
    lead to even static link libc and other basic system libraries, or warn
    if those static libraries cannot be found on the system.
    
    To give more flexibility, 'static' kwarg now accepts a list of patterns,
    the static library is used only if its path match one of the patterns,
    otherwise it will be kept dynamic.
    
    Closes #2765.

### CODE REVIEW

**Comment by xclaesse** [comment]
Maybe in the string array, we could also accept regex, or lib names, in addition to absolute path prefixes.

**Comment by nirbheek** [comment]
I'm not sure it's wise to encode paths in the build file itself. The paths will be very machine-specific and OS-specific.

I feel like filtering by library path is also asking the wrong question. The real question is "which libraries do you want statically linked and which will be provided by the platform". For that, maybe we could have a new function `dependencies()` which takes a dictionary of dependency names:

```meson
app_dep_names = {
  'gtk+-3.0': {'static': true},
  'gio-2.0': {'version': '>=2.56', 'static': true},
  'libffi': {'static': false}
}
app_deps = dependencies(app_dep_names)
```

The idea is that you can enumerate in one go which libraries you want static and the rest will be shared. With separate `dependency()` calls is that you would usually only specify the topmost dependency that you are using, and you had no way to specify parameters on the sub-dependencies.

```meson
pango_dep = dependency('pango', static : true) # link static
gtk_dep = dependency('gtk+-3.0') # link shared, also pulls in shared pango
# now we are linking to pango both static and shared?!
```

`app_deps` would be a `ExternalDependencies` object that can be subscripted and enumerated to yield `ExternalDependency` objects. The advantage of having a single object instead of a list is that you can call `.found()` on it.

This would solve a few other issues too, f.ex:

1. https://github.com/mesonbuild/meson/pull/1753

2. Parallelized API for finding pkg-config dependencies, which will speed up configuration

**Comment by xclaesse** [comment]
I don't think you should have to enumerate them one by one. For example I could have a custom GStreamer build installed in a prefix, and I want to static link to it (hundred of libs) but not static link on a few system libs that are part of my target platform.

Also when meson does `pkg-config --libs foo` it gets '-lbar', how can it know what to lookup in your map to know if `bar` must be static? `bar` could have a pc file name that doesn't match is library name, or could even not have .pc file at all.

But I agree just having path prefixes is not enough for all cases, but that can be extended over time too.

**Comment by xclaesse** [comment]
> I'm not sure it's wise to encode paths in the build file itself. The paths will be very machine-specific and OS-specific.

That's why my PR also support syntax like `static : '${prefix}'`, to mean "static link only libs you find into the same prefix than this dependency".

For example, I want to static link on a glib I installed into a custom prefix, but not static link on system libs like libffi (see https://gitlab.gnome.org/GNOME/glib/merge_requests/360):
```meson
app = executable('test-static-link', 'app.c',
  dependencies : dependency('gio-2.0', static : ['${prefix}'])
)
```

**Comment by nirbheek** [comment]
I see, so your use-case is an "application build file" or an "aggregating build file" that yields either a 'fat library' or an app that is statically linked with some/most libraries in a prefix and dynamically with the rest.

So, speaking about GStreamer, this build file would actually be generated at runtime and would have the correct paths encoded in it? Or would it be static and rely on `prefix` being set correctly? What about toolchain paths in that case, f.ex., MinGW which ship libraries that may or may not be available at runtime?

**Comment by xclaesse** [comment]
The GStreamer use-case is to build an app that will run on a security camera with very small disk space. So GStreamer and its needed dependencies are all static linked into the app to let linker optimize and strip unused code. GStreamer and all its deps are built with cerbero, and we want everything we built with cerbero to be static linked into the app, but keep using a few shared libs that are part of the camera's SDK that we install in another prefix.

**Comment by xclaesse** [comment]
It's pretty similar to building a GStreamer app for Android: You compile GStreamer with cerbero, then static link all libs from cerbero but keep shared the few libs from android platform.

**Comment by ocrete** [comment]
I preferred something like the approach in #2816 because with this new approach, we'd have to specify it for every dep instead of doing it globally, I don't see how this would change between dependencies.

**Comment by xclaesse** [comment]
@ocrete I think we should go one step at a time. First figure out how we can tell dependency() we want some mix of static and shared, instead of a all-or-nothing boolean switch. Once that's done, it's really easy to have a built-in option that let you set the default value of `static` kwarg on all `dependency()` calls.

**Comment by ocrete** [comment]
If #4321 is merged, we could make this pretty nice by having a "link subprojects as static" mode where we could easily make meson generate one a static binary from the whole source tree and it's subprojects, but build the rest as dynamic.

**Comment by xclaesse** [comment]
Rebased this PR on top of PR https://github.com/mesonbuild/meson/pull/4159 because I need it for the unit test.

Instead of having paths, `static` kwarg now accept pattern so we can for example have `*/gstreamer-sdk/*`, that should be much more flexible.

**Comment by xclaesse** [comment]
> If #4321 is merged, we could make this pretty nice by having a "link subprojects as static" mode where we could easily make meson generate one a static binary from the whole source tree and it's subprojects, but build the rest as dynamic.

Static link on subprojects is mostly about this PR: https://github.com/mesonbuild/meson/pull/4157. The idea is you could have default_library=shared for the master project, but set default_library=static for some subprojects.

**Pull request closed without merging**
