### PR TITLE
cmake: Change assertion int a more useful error (fixes #9925)

### LINKED ISSUE #9925: Meson told me report an "Unhandled python exception".
While defining a cross build file for `Windows`, I wrote a section for `cmake`,
```ini
[cmake]
CMAKE_C_COMPILER_WORKS = 1
```
and I forgot to wrap "1" in single quotes and it threw this unhandled exception.
```bash
❯ meson setup --cross-file=cross-windows-x86_64.ini build-win
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 180, in generate
    env = environment.Environment(self.source_dir, self.build_dir, self.options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/environment.py", line 536, in __init__
    cmakevars.host = CMakeVariables(config.get('cmake', {}))
  File "/usr/lib/python3.10/site-packages/mesonbuild/envconfig.py", line 442, in __init__
    assert isinstance(i, str)
AssertionError

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

### PR DESCRIPTION
**Pull request by mensinda**

### CODE REVIEW

**Review by dcbaker — APPROVED** [review]

**Comment by mensinda** [comment]
Not sure why the CI is failing though. It also seems to happen on master. Is that a known issue?

**Comment by eli-schwartz** [comment]
```
[6/13] "c++" "-Isubprojects\cmMod\cm_meson_testEXE.exe.p" "-Isubprojects\cmMod" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod" "-Isubprojects\cmMod\__CMake_build" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod\__CMake_build" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod\lib" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=gnu++14" "-O0" "-g" -MD -MQ subprojects/cmMod/cm_meson_testEXE.exe.p/main.cpp.obj -MF "subprojects\cmMod\cm_meson_testEXE.exe.p\main.cpp.obj.d" -o subprojects/cmMod/cm_meson_testEXE.exe.p/main.cpp.obj "-c" "../test cases/cmake/3 advanced no dep/subprojects/cmMod/main.cpp"
[7/13] "D:\a\_temp\msys64\mingw64\bin\python3.exe" "D:\a\meson\meson\meson.py" "--internal" "symbolextractor" "D:\a\meson\meson\b 23248c1576" subprojects/cmMod/libcmModLib.dll "subprojects\cmMod\libcmModLib.dll.a" subprojects/cmMod/libcmModLib.dll.p/libcmModLib.dll.symbols 
FAILED: subprojects/cmMod/libcmModLib.dll.p/libcmModLib.dll.symbols 
"D:\a\_temp\msys64\mingw64\bin\python3.exe" "D:\a\meson\meson\meson.py" "--internal" "symbolextractor" "D:\a\meson\meson\b 23248c1576" subprojects/cmMod/libcmModLib.dll "subprojects\cmMod\libcmModLib.dll.a" subprojects/cmMod/libcmModLib.dll.p/libcmModLib.dll.symbols 
[8/13] "c++" "-Imain2.exe.p" "-I." "-I..\test cases\cmake\3 advanced no dep" "-Isubprojects\cmMod\__CMake_build" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod\__CMake_build" "-Isubprojects\cmMod" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod" "-I..\test cases\cmake\3 advanced no dep\subprojects\cmMod\lib" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-O0" "-g" "-DCMMODLIB_STATIC_DEFINE" -MD -MQ main2.exe.p/main.cpp.obj -MF "main2.exe.p\main.cpp.obj.d" -o main2.exe.p/main.cpp.obj "-c" "../test cases/cmake/3 advanced no dep/main.cpp"
```

@lazka any idea? This looks like some sort of broken python again -- the program exits silently with failure.

**Comment by lazka** [comment]
This is https://github.com/msys2/MINGW-packages/issues/11864, python is crashing on exit, but no one managed to reproduce it locally yet.

**Comment by eli-schwartz** [comment]
Oh right, I even commented there, heh.

**Comment by eli-schwartz** [comment]
> Change assertion int a more useful error

Hmm, that commit message is a bit confusing due to the typo. Can we fix that? :)

**Pull request merged**
