### PR TITLE
Fixed unbound cmvers variable

### PR DESCRIPTION
**Pull request by mensinda**
Fixes a crash.

### CODE REVIEW

**Comment by jon-turney** [comment]
Can you explain why this case wasn't hit by the test added in #4444?  Is it possible to add something to exercise this case (per per http://mesonbuild.com/Contributing.html#tests)

**Comment by mensinda** [comment]
This bug is triggered when CMake is not found by meson. Since CMake is installed in all test environments this bug doesn't occur there. I will try to add a unit test for this, which should be possible since the CMake executable can also be retrieved via os.environ['CMAKE']. Though I don't know if it is OK to set environment variables in unit tests.

**Comment by lazka** [comment]
master hit this now because the azure msys2 build doesn't have cmake installed (should it? I didn't see a test difference)

**Comment by mensinda** [comment]
The test currently should only run on Linux (it is in the `linuxlike` directory). It seams like this bug was triggerd in another test case where the first dependcy method failed. In this case CMake is automatically used as a fallback. I have not looked at the specific test case yet.

In short yes.

**Comment by mensinda** [comment]
The CI still fails. I am looking into it.

**Comment by mensinda** [comment]
The caused by the CMake backend raising an exception with the message "CMake not found" but the test_dependency unit test requires an exception with the format `[Dd]ependency.*not found`. The CMake backend raises multiple other exceptions with different messages. Should I update the unit test or the messages in the exception?

**Comment by mensinda** [comment]
@lazka Actually no. Azure does not need CMake since the tests (currently) only run on Linux. Though this might change in the future.

**Comment by lazka** [comment]
thanks @mensinda. There is still an error

```
======================================================================
FAIL: test_dependency (__main__.FailureTests)
----------------------------------------------------------------------
mesonbuild.dependencies.base.DependencyException: CMake not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_unittests.py", line 117, in wrapped
    return f(*args, **kwargs)
  File "run_unittests.py", line 2999, in test_dependency
    self.assertMesonRaises(contents, match)
  File "run_unittests.py", line 2956, in assertMesonRaises
    self.init(self.srcdir, extra_args=extra_args, inprocess=True)
AssertionError: "[Dd]ependency.*not found" does not match "CMake not found." : dependency('zlibfail')
```

I've opened #4552 to install cmake for msys2 which makes things work here.

**Pull request merged**
