### PR TITLE
Use deterministic builddir so CCache works across invocations.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by nirbheek** [comment]
Can we store the ccache dir in the travis cache somewhere? Will that help?

**Comment by jpakkane** [comment]
I don't know. If we could, then it would save some time at least. I did this to speed up local development (this used to work before we went full parallel).

**Comment by nirbheek** [comment]
I realized we don't actually need to cache on Travis right now because our bottleneck is Appveyor anyway, so whatever, we can look at this later. :p

**Comment by lazka** [comment]
Just stumbled onto this code when changing something nearby:

Wouldn't setting CCACHE_BASEDIR=sometempdir be better?

**Comment by lazka** [comment]
hm, no, for some reason setting CCACHE_BASEDIR gives way worse cache hits... never mind then.

**Pull request merged**
