### PR TITLE
A few smaller D support improvements

### PR DESCRIPTION
**Pull request by ximion**

### CODE REVIEW

**Comment by jpakkane** [comment]
Please add a comment saying why we need to do `-L-L`. It is very confusing otherwise.

**Comment by ximion** [comment]
Where should I add that comment?

**Comment by jpakkane** [comment]
Above the `-L-L`s

**Comment by ximion** [comment]
Right, obviously - sorry, I misread your question (my brain substituted "why" with "where" for some reason...).

**Pull request merged**
