### PR TITLE
Fix image link names.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by mensinda** [comment]
Could you also add `fatal_warnings: true,` to the `meson.build`, so we catch this in the future?

**Comment by mensinda** [comment]
This will also make broken links hard errors.

**Comment by jpakkane** [comment]
Let's do that on a separate PR, I'm guessing it will uncover bugs so better to fix them separately.

**Review by mensinda — APPROVED** [review]
OK, sure.

**Review by mensinda — CHANGES_REQUESTED** [review]
Actually, the `osx_xcode.png` image is still missing...

**Comment by jpakkane** [comment]
Fixed.

**Review by mensinda — APPROVED** [review]

**Pull request merged**
