### PR TITLE
BUGFIX: correct missing @ before lru_cache, type hint, syntax efficiency

### PR DESCRIPTION
**Pull request by scivision**
* correct missing `@` on lru_cache decorator
* add type hinting for QA and to help gradual transition to more efficient & robust pathlib.Path vs. os.path(str)
* use modern / efficient subprocess.run(timeout) to avoid hangs

### CODE REVIEW

**Comment by xclaesse** [comment]
Does those type annotations works with Python 3.5 ? I remember there has been discussion about that and I don't think we concluded that we can depend on that just yet. But I'm not sure.

**Comment by scivision** [comment]
@xclaesse yes `typing` was added in Python 3.5: https://docs.python.org/3.5/library/typing.html

**Comment by scivision** [comment]
The part of type annotations that don't work with Python 3.5 are inline declarations:
```python
x: str = 'hi'  # python >= 3.6

# for older Python versions
x = 'hi'  # type: str  
```

**Comment by scivision** [comment]
`pathlib.Path` is also a key robustness add because it greatly clarifies the syntax and works smoothly with Pytest etc.

**Comment by dcbaker** [comment]
I'm fine with all of the changes here, but, I need to ask you to clean up your commits. In git each commit should make one logical change, and the commit message should accurately reflect that change.

There is no reason for patches 1 & 2 to be separate patches, they both touch the same file and make the same logical change.

Patch 3 does two different things. It uses a new in 3.5 helper function, and adds a timeout. Those should be two separate patches

Patch 4 is fine

Patch 5 does 4 separate things: It adds additional platforms to the list of x86 architectures, it adds type hints, it replaces if...if with if...elif, and it converts from `glob` to `pathlib`.

The reason I ask for this is that if we ever need to bisect or revert something, having each patch as a single logical change makes that possible for bisect and easier for reverting.

**Comment by jpakkane** [comment]
This change is in total so small that squashing should be just fine.

**Comment by scivision** [comment]
@jpakkane squashed and ready to go

**Comment by jpakkane** [comment]
For future reference you don't need to squash things yourself. Github lets the maintainer do that automatically on merge.

**Pull request merged**
