### PR TITLE
Add mkenum and genmarshal support

### PR DESCRIPTION
**Pull request by jpakkane**
This is #718 but mkenum converted to generate both files in a single invocation.

### CODE REVIEW

**Comment by QuLogic** [comment]
It probably works, but the question is still what to do with the individual settings.

**Comment by tp-m** [comment]
(Context: it's nice for the case where everything is based on template files, but not so nice where the templates are passed via kwargs/arguments.)

**Comment by jpakkane** [comment]
The interesting questions here, then, are:

 - are there things that you can only do with individual args but not with a template
 - what is the usage ratio of templates vs individual args (mostly templates/mostly individual/roughly the same)

If templates can do everything and there is not much usage for single args, we can probably just support the template versions and the remaining 1% can use a custom Python script much like GStreamer does now.

**Comment by nirbheek** [comment]
I did a brief survey of GNOME git repositories that I had cloned locally, and it really seems like it's 50-50. Some projects even use both templates and arguments (for separate targets). Many projects also use this to programmatically generate gsettings enum XML files from enum headers, which is very interesting and can't be done with a template.

I think we need to support both somehow. Perhaps we can have `gnome.mkenums_template` as the template version that can generate both, and `gnome.mkenums` can behave very similar to glib-mkenums in the argument form—generate one file at a time.

**Comment by nirbheek** [comment]
The two can share all the work in a common function, so there shouldn't be duplication in the module code.

**Comment by jpakkane** [comment]
If we can support both with common code and two funcs with little extra maintenance burden then I say go for it.

**Comment by jpakkane** [comment]
Superseded.

**Pull request closed without merging**
