### PR TITLE
cmake: Enable support for using -uninstalled.pc files

### PR DESCRIPTION
**Pull request by mensinda**
This PR enables the usage of `*-uninstalled.pc` files for CMake subprojects.

The test case is a bit hacky since CMake just does not like spaces in the `pkg-config` output...

Related issue: #8089

### CODE REVIEW

**Comment by jpakkane** [comment]
⚔️ conflicts. If CMake can't handle spaces then it might make sense to run it as a unittest by copying the entire tree to a spaceless dir and then running it by hand.

**Comment by mensinda** [comment]
Done, should hopefully pass now...

**Comment by jpakkane** [comment]
Msys fails. :(

**Comment by mensinda** [comment]
Seems like there are even more problems with `\` in paths (which CMake also does not correctly handle)...

I guess the only reliable way to fix this would be to always use POSIX paths for *everything*. I am afraid that I won't get this running in time for 0.57 on windows...

**Comment by kcgen** [comment]
@mensinda , just curious if this will make in the queue for 0.58?

**Comment by tristan957** [comment]
@kiwixz wanna take this PR over?

**Comment by kiwixz** [comment]
I tried rebasing it, but after 3499 commits on master there is not much that fits.  I see you're already taking care of the relative_to in #12087; so whats left is basically just the hack to remove spaces from paths (if that still needed with newer CMake ?).  If someone where to work on this, they should probably start from scratch and just salvage the test cases.

**Comment by tristan957** [comment]
@kiwixz thanks for taking a look. I will close the PR.

**Pull request closed without merging**
