### PR TITLE
gnome.mkenums: Use --output when available

### PR DESCRIPTION
**Pull request by TingPing**
TODO: Ninja doesn't seem to be passing escaped newlines to the command... so, don't merge yet.

### CODE REVIEW

**Comment by jpakkane** [comment]
The failure is weird. Could you rebase so the tests are rerun?

**Comment by jpakkane** [comment]
Please rebase.

**Comment by TingPing** [comment]
Don't merge this yet, we simply cannot have newlines in commands which the test for this relies upon so will probably have to serialize it or something. For now the capturing behavior is fine as I believe that was fixed on Windows?

**Comment by nirbheek** [comment]
Capturing is fixed on Windows, yeah. Why does the test rely on newlines in the command arguments?

**Comment by TingPing** [comment]
The mkenums command is basically writing C: https://github.com/mesonbuild/meson/blob/master/test%20cases/frameworks/7%20gnome/mkenums/meson.build#L56-L108

Which is something we should keep working, it just means it can't be a command stored in a string in ninja.

**Comment by nirbheek** [comment]
Ah, that's what you meant. Yeah, `serialise_executable()` is your friend here.

**Comment by TingPing** [comment]
I'm just going to be closing this for now. Using `--output` isn't super valuable now that capture works on Windows.

The quoting commit might still be valuable though if anybody wants to pull that in.

**Pull request closed without merging**
