### PR TITLE
ci: Add Fedora and OpenSUSE images

### PR DESCRIPTION
**Pull request by mensinda**
I have tried to fix as many test failures as possible on these images, however, I didn't manage to fix all of them. Specifically the `hdf5`, `netcdf`, `mpi` and `scalapack` tests just won't work on Fedora and OpenSUSE. Unfortunately, I don't know enough about these dependencies to fix them (ping @scivision, @dcbaker).

The docker images are hosted here: https://hub.docker.com/u/mensinda

### CODE REVIEW

**Comment by scivision** [comment]
I have noticed a few prior notes and instances of NetCDF or Scalapack causing CI problems. I don't think I have time in the near future to setup VMs for the various OS to fix these issues. So maybe it's better to skip NetCDF and Scalapack? Or even remove them from Meson? 

The long term plan is to "fix" these quirky HPC-oriented frameworks by using CMake from Meson via CMake `find_package(... COMPONENTS ...)` where I and others have worked about robust FindFoo.cmake over the years.  I think I will do that in 2Q2020. This will fix a lot of libraries in general.

**Comment by mensinda** [comment]
Skipping the tests, when the dependency isn't found shouldn't be a problem. However, with `hdf5` and `netcdf` the really annoying problem is that they **are found** but **don't compile**. I can work around this by uninstalling the packages, but this would only hide the bug.

Also, CMake `COMPONENTS` support will be added with #6569.

**Comment by scivision** [comment]
In general this type of Fortran error is caused by missing include directories:

```
    1 | use netcdf
      |    1
Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory
```

it may well be another case of messed up pkg-config files. 

In CMake FindFoo.cmake a typical technique is to:

1. find_library, find_path
2. check_fortran_source_compiles() using the libraries found

and only declaring the package found if both are OK. Maybe this is a pattern that could be in DependencyFactory?

**Comment by mensinda** [comment]
I am not sure if the `DependencyFactory` can be rewritten to support a logical and. We could add a new `DependencyChain` class for this (only found if all dependencies are found). However, I am not sure if this would be overengineered. Just doing both checks in the system dependency class might be cleaner (at least for now).

**Comment by scivision** [comment]
OK so do you mean within each dependency, do a `run_command` like check using Meson internals?

A typical example is Lapack, where many versions are not uncommon to be installed. There could be a for loop inside that tries to compile with each one until it finds one that compiles

**Comment by mensinda** [comment]
Yes, for specific dependencies that require this (and would return a false positive otherwise). Or, we make the lookup good enough so this isn't required :)

**Comment by scivision** [comment]
OK what I've been doing is for each project I have a meson_deps/meson.build that does like

```meson
cc = meson.get_compiler('c')
foreach l : ['foo','bar','baz']
   foo = dependency(l, required: false, disabler: true)
   if cc.links('foo.c', dependencies: foo)
     break
   endif
   foo = disabler()
endforeach
```

so far I just copy that project to project as needed. But OK that would be a pathway forward to do it internal to Meson dependency()

**Comment by mensinda** [comment]
For now, I went forward with removing the relevant packages from the images and allowing the framework to skip the tests.

These changes should be undone once the dependencies are fixed.

**Comment by scivision** [comment]
I think that's a good idea. Netcdf and Scalapack dependencies are a bit shaky for now on less common use cases. As a few PRs are merged, we'll have a better basis to make these dependencies more solid.

**Comment by mensinda** [comment]
OK the CI is green, and this is now ready to merge from my perspective. Does anyone have any objections / missing packages in the images?

**Pull request merged**
