### PR TITLE
Add property to disable compiler sanity checks during cross compilation.

### PR DESCRIPTION
**Pull request by jpakkane**
Ping @keith-packard can you test if this fixes your issue?

### CODE REVIEW

**Comment by Ericson2314** [comment]
Hmm, there already was some stuff where it wouldn't try to link anything for cross. Not against this in principle, but curious what the symptom of not having it is.

**Comment by keith-packard** [comment]
> Hmm, there already was some stuff where it wouldn't try to link anything for cross. Not against this on principle (I like being able to elide all environment reflection by hard-coding), but curious what the symptom of not having it is.

This variable disables the initial sanity checks at meson startup, which were otherwise unconditionally attempting to compile, link and execute a simple program using the target compiler.

**Comment by keith-packard** [comment]
> Ping @keith-packard can you test if this fixes your issue?

Yup, works great! Thanks much.

**Comment by Ericson2314** [comment]
> This variable disables the initial sanity checks at meson startup, which were otherwise unconditionally attempting to compile, link and execute a simple program using the target compiler.

Did you have an exe wrapper? If not, this is definitely a bug we should also make an issue for.

**Comment by jpakkane** [comment]
Note that this is a case of building your own libc. The compiler provides _nothing_, even `_start` or `memcpy` or anything like that. Thus it is not possible to even link an executable.

**Comment by Ericson2314** [comment]
@jpakkane Agreed, but I recall the intent was to use the presence/absence of the exe wrapper as a heuristic for whether linking ought to work in the sanity check.

**Comment by jpakkane** [comment]
In this particular case exe_wrapper is defined and it is being used to run the test suite. This is a very niche use case only encountered by unusual projects.

**Comment by Ericson2314** [comment]
Ah OK, well that explains it. Glad this option exists, glad it's not a bug after all!

**Pull request merged**
