### PR TITLE
test runner: fix excluding null options

### PR DESCRIPTION
**Pull request by ePirat**
It was impossible to specify null arguments in the exclude array,
while they were passed properly in the code, they were stringified
while the entries in the options array were just completely removed.

To fix this, do not early stringify the argument name and option
together as that would make it impossible to properly match it to
None without introducing a new special case for the string "None".
So instead they are now kept as tuples and only stringified when
its actually needed.

### CODE REVIEW

**Comment by jpakkane** [comment]
This should have a test to verify that the change is correct.

**Comment by ePirat** [comment]
@jpakkane How do I write a test for the test runner itself?

**Comment by eli-schwartz** [comment]
It would need to be a python unittest, not a project test.

**Comment by ePirat** [comment]
Are there already unit tests for the test runner I can look at as an example?

**Comment by eli-schwartz** [comment]
I don't know why I responded as I did above. I guess I didn't realize that this is about fixing/enhancing the Meson testsuite, not fixing/enhancing the end user program `meson test`.

I don't really think we need to write unittests for our unittests. But we should have at least one unittest that depends on and uses this functionality.

**Comment by ePirat** [comment]
Ping on this as my other MR depends on this and it seems nothing really is blocking this?

**Review by eli-schwartz — APPROVED** [review]
Indeed.

**Pull request merged**
