### PR TITLE
Rename test cases to remove duplicate numbers.

### PR DESCRIPTION
**Pull request by QuLogic**
These could be found with:
```bash
for d in test\ cases/*; do
  echo $d
  find "$d" -maxdepth 1 -type d | cut -d/ -f 3 | cut -f 1 -d' ' | sort -n | uniq -c | sort -n | grep -v '^      1'
done
```

### CODE REVIEW

**Comment by nirbheek** [comment]
I think it's impossible to keep the tests in order since we sometimes remove test cases and add new ones from various PRs at once. The order also doesn't matter and doing a rename like this only messes up git blame. I think we shouldn't change this.

**Comment by jpakkane** [comment]
> doing a rename like this only messes up git blame

It is just so much fun to have crappy tools that prevent you from doing the right thing. 🎉

**Comment by tp-m** [comment]
I just tried it, it doesn't mess up git blame at all for me.

**Comment by jpakkane** [comment]
Let's do this after the release.

**Pull request merged**
