### PR TITLE
tests: fix assertion rewriting when pytest is used

### PR DESCRIPTION
**Pull request by benoit-pierre**
Change [this](https://github.com/mesonbuild/meson/actions/runs/5857616111/job/15879865080?pr=12119#step:6:2698) into [this](https://github.com/benoit-pierre/meson/actions/runs/5858924537/job/15883873847#step:6:2696).

### CODE REVIEW

**Comment by eli-schwartz** [comment]
- Isn't this generally supposed to be better handled with `self.assert*()` methods?

- I'm not enthusiastic about adding a new file to the root of the repository. Is it possible to inject this for example by doing it in an if block inside `unittests/__init__.py` and still trigger the rewriting before pytest actually imports the files with the asserts that you want to rewrite? I haven't tested it but it seems plausible.

**Comment by benoit-pierre** [comment]
It's normally done automatically, but because of the way the testsuite is run and/or the way tests are named, it does not work.

> * Isn't this generally supposed to be better handled with `self.assert*()` methods?

Being able to just use assert is kind of one of the points in using pytest (why even bother with unittest?).

>     * I'm not enthusiastic about adding a new file to the root of the repository. Is it possible to inject this for example by doing it in an if block inside `unittests/__init__.py` and still trigger the rewriting before pytest actually imports the files with the asserts that you want to rewrite? I haven't tested it but it seems plausible.

There's no corresponding config option, or command line arguments. Doing it in `conftest.py` means it's automatically only done when running with pytest (if you want to keep compatibility with using unittest).

**Comment by eli-schwartz** [comment]
Sorry, by if block I meant more a try block (conditional but a very different form of it).

```python
try:
    import pytest
except ModuleNotFoundError:
    pass
else:
    pytest.register_assert_rewrite('unittests')
```

This should be harmless when running with unittest but still register the hook under pytest (while simultaneously avoiding the addition of "yet another repository root file").

**Comment by benoit-pierre** [comment]
OK, I found a simpler alternative way.

**Pull request merged**
