### PR TITLE
Allow vs_module_defs to use a custom_target

### PR DESCRIPTION
**Pull request by jon-turney**
Allow vs_module_defs to use a custom_target
Add a test and update documentation

### CODE REVIEW

**Comment by jon-turney** [comment]
I need a bit of help with this.

The test fails with the VS backend, it looks like because custom target generating the def file isn't run.

The vs_module_defs file is added to link_depends, but I don't see how that is used for dependencies in the VS backend, at all...

**Comment by jpakkane** [comment]
In VS you need to specify a dependency in the solution file. That is the only thing that houses dependencies between targets.

**Comment by jon-turney** [comment]
> In VS you need to specify a dependency in the solution file. That is the only thing that houses dependencies between targets.

I see.  So that seems to be missing from vs2010backend.py:get_target_deps for link_depends,

I created bug #1799

**Comment by jon-turney** [comment]
As requested, I have added the test from PR #1798, and added a check to skip both failing tests on VS backends.

**Pull request merged**
