### PR TITLE
New `add_test_suite` function

### PR DESCRIPTION
**Pull request by bruchar1**
This function allows to attach new suite labels to already defined tests
or benchmarks. It is used in the context you want to label a series of
test with a specific label.

### CODE REVIEW

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
> This function allows to attach new suite labels to already defined tests or benchmarks.

This sounds logically like the same reasoning used to explain:

"New function install() which allows to attach "install" and "install_dir" labels to already defined custom targets".

This is explicitly against meson's design documents as laid out by @jpakkane, the same thing ends up defined piecemeal in a variety of places.

It also relies on changing the return value of tests, instead of returning None and being incapable of assignment in the DSL, it starts returning a held object. Adding a FeatureNew for an assignment is... somewhat complicated and not being done here.

**Comment by bruchar1** [comment]
The problem I want to solve is that I have hundreds of test targets. I need to group them to be able to execute all tests related to a part of my project (e.g. tests for an executable and tests for all its dependent libraries). Adding the required suites to every test would be tedious and error prone, because if a dependency change, I have to modify every tests related to that dependency. Having the list of test of a given test suite in one place would be easier to manage.

My other idea was to add a `test_alias` function, similar to `alias_target`, but since the notion of test suite already does that, it feels more natural to use it.

**Comment by tristan957** [comment]
Could you not solve your problem like:
```meson
tests = {
  'test1': {
    # test kwargs
    'suite': ['original-suite']
  }
  # other tests...
}

foreach t, params : tests
  additional_suites = []
  if the_dep.found()
    additional_suites += 'other-suite'
  endif

  test(t, xxx, suites: params.get('suite', []) + additional_suites)
endforeach
```

**Comment by eli-schwartz** [comment]
It's not obvious to me how choosing and regularly updating which tests are appended to which array for later passing into `add_test_suite(some_tests_array)`, is more or less easy to maintain than an array of `suites_for_foobar` and updating the list of suites in place, then reusing that array for each logical group of tests. Either one requires a bit of juggling.

**Comment by bruchar1** [comment]
Thank you for your suggestions. I think I may be able to construct a datastucture while going through the build files. I was reluctant to the idea of putting all the `test` functions in a for loop as @tristan957 suggested, but finally, it may be not so bad. I will give it a try.

**Comment by jpakkane** [comment]
A main design point of Meson has always been that defined things are immutable. That is, _all_ information pertaining to a thing _must_ be present when it is defined. Altering things after the fact is not acceptable because that leads to unmaintainability. Whatever the solution to this problem ends up being, it must _not_ be this.

**Pull request closed without merging**
