### PR TITLE
Support for generating opaque directories of data

### PR DESCRIPTION
**Pull request by jpakkane**
This is designed to support arbitrary document generators (Doxygen, hdoc, Sphinx, what have you) in a straightforward way without needing to add custom code for every one of them in Meson core.

Basically the end user writes a custom script that is given specific arguments to tell where it should put its things.

This MR is not final by any means, documentation, a proper unit test and the like are missing, just posting this here to get feedback before committing too deeply. Also missing are the docs, this needs a page of its own explaining the integration interface.

### CODE REVIEW

**Comment by jpakkane** [comment]
This is green so ready for review.

**Comment by DaanDeMeyer** [comment]
Instead of a documentation generator, I was looking to integrate an image builder (mkosi) into meson. It's pretty similar to a documentation generator in this regard in that the outputs will be opaque and we don't know most of them up front. However, one output, the image manifest, will always be generated and we will need access to it so that we can pass it as an argument to other tools during the build. There seems to be no way to access the output directory of an opaque target which would be necessary to access the manifest. Could we make the output directory path available somewhere in the returned object so that we can pass paths to known files in the output directory of the opaque target as arguments to other tools?

**Comment by eli-schwartz** [comment]
That would not permit depending on such an output, as you would not know when the output file was actually created -- or updated.

Do they need to be tied together into the same target? Would a regular custom_target suffice for the named, known file?

**Comment by DaanDeMeyer** [comment]
> Do they need to be tied together into the same target? Would a regular custom_target suffice for the named, known file?

Two targets means running two commands no? I think I'm missing something about how meson works to grok this

Another idea would be to allow specifying regular outputs in the output directory that you know will always be generated alongside the opaque outputs.

**Comment by jpakkane** [comment]
Or something like:

```meson
ot = opaque_target(...)
ofile = ot.unsafe_get_file_from_outdir_that_i_know_to_exist('somefile.dat') # If it does not exist, the fault is yours.
```

**Comment by jpakkane** [comment]
In any case those can be added later.

**Comment by jpakkane** [comment]
Test failure is unrelated.

**Comment by xclaesse** [comment]
My general feeling is we should not force user to write a wrapper script, at least for the common cases like doxygen. There are basically 2 cases:

- If the underlying tool supports generating a depfile, it also must have at least a know output file to put as primary target of that depfile. That means those tools does not need a stamp file and can be supported like that:
```meson
doc = custom_target('doc', output: 'some.file', command: [tool, '--depfile=@DEPFILE@'])
install_subdir('html', from_build_dir: true)
```
- If the underlying tool does not support generating a depfile, user certainly won't be able to write one either. In that case this PR currently force user to write a useless dummy depfile for no reason. That's the case of doxygen. I would support that by allowing custom_target() to have no output kwarg, and in that case the command gets wrapped by Meson itself to create the stamp file:
```meson
doc = custom_target('doc', command: [doxygen, doxyfile])
install_subdir('html', from_build_dir: true)
```
In bot cases the biggest thing missing currently is the `from_build_dir: true` kwarg in `install_subdir`. Luckily, InstallDir class internally already supports that, it's trivial to expose it.

That said, I'm not against contracting custom_target()+install_subdir() into a single opaque_target().

**Comment by xclaesse** [comment]
@DaanDeMeyer if I understand correctly your use-case, you can use custom_target() with an output file, but you can't currently install the output dir as-is, which I'm suggesting to fix by adding `from_build_dir: true` kwarg to `install_subdir()`. Would that work for you, or am I missing something?

**Comment by DaanDeMeyer** [comment]
> @DaanDeMeyer if I understand correctly your use-case, you can use custom_target() with an output file, but you can't currently install the output dir as-is, which I'm suggesting to fix by adding from_build_dir: true kwarg to install_subdir(). Would that work for you, or am I missing something?

I'd need to be able to install only specific files, but I don't think that requires any special functionality that meson doesn't support yet.

**Comment by xclaesse** [comment]
> There are basically 2 cases

One use-case I could have forgotten: the command somehow give a list of dependency files, but not in the form of a depfile. In that case user could actually write a useful depfile using the stamp file as target. Do we have real world use-case for that, or is it purely theoretical?

**Comment by xclaesse** [comment]
> I'd need to be able to install only specific files from the build directory. Is that supported already?

If your output is opaque, how could it install only some files? You mean globbing like `*.so` for example? IMHO in that case you're better served with `meson.add_install_script()`.

**Comment by eli-schwartz** [comment]
> * If the underlying tool supports generating a depfile, it also must have at least a know output file to put as primary target of that depfile. That means those tools does not need a stamp file and can be supported like that:
> 
> 
> ```meson
> doc = custom_target('doc', output: 'some.file', command: [tool, '--depfile=@DEPFILE@'])
> install_subdir('html', from_build_dir: true)
> ```

The entire reason behind this PR was, I thought, the fact that @jpakkane does not want to allow people to have things like `from_build_dir: true`. I've gone down this road for install_man with built files already, and my understanding was that for design reasons this will never be allowed, no matter how much the internal installdata structures don't care, because it is "wrong" for function to *create* output* and another function to *install* it.

So the reason we cannot support what you suggest is because it's been declared that it looks bad.

> * If the underlying tool does not support generating a depfile, user certainly won't be able to write one either. In that case this PR currently force user to write a useless dummy depfile for no reason. That's the case of doxygen. I would support that by allowing custom_target() to have no output kwarg, and in that case the command gets wrapped by Meson itself to create the stamp file:

Why on earth not? The concept behind this PR is that meson.build doesn't know what the outputs are, which says nothing about the inputs. Furthermore, the outputs might change between runs.

So the underlying tool doesn't need to care about depfiles, and maybe cannot generate a constructively helpful one anyway, but it *can* support figuring out what the *inputs* are or were, which is all that really matters as we want the wrapper script to generate a depfile that maps `stampfile: all_inputs` and we don't care about outputs at all.

In doxygen's case, that can frequently be analyzed by reading Doxyfile in the script. Doxygen requires you to name your inputs already (a list of either/both of files to scan, and directories to scan for files to scan), then it figures out what symbols are available and produces whatever output filenames it feels like, which may include symlinks per symbol and may include whatever the source code comments say the symbols should be grouped as.

If your Doxygen inputs are files, not directories, then it is ridiculously, trivially easy to emit this. If, like `frameworks/14 doxygen/`, your project is set up to scan all files regardless of whether they are public or private headers (or you consider all headers to be public ones) then there's a limit to what you can do. You can do globbing in your wrapper script, then emit a depfile, no problem. But it will only detect when existing files change and require rerunning doxygen -- it cannot detect when new files are added to the source tree.

Either way, depfiles work.

**Comment by xclaesse** [comment]
> Why on earth not? The concept behind this PR is that meson.build doesn't know what the outputs are, which says nothing about the inputs. Furthermore, the outputs might change between runs.

If you know inputs you already put them in custom_target() intput kwarg. No depfile needed. depfile is about hidden inputs that only the tool knows, like C headers. In that case user has no clue either, they won't be able to help.

**Comment by eli-schwartz** [comment]
> If you know inputs you already put them in custom_target() intput kwarg. No depfile needed. depfile is about hidden inputs that only the tool knows, like C headers. In that case user has no clue either, they won't be able to help.

You can equally argue that if you know inputs for executable() you put them as sources, no depfile needed.

But Doxyfile can be modified by git pull and start listing new, or more, inputs.

Also, Doxyfile can specify directories, like I said, in which case a wrapper can read that and perform its own globbing.

Doxygen isn't magic, it takes configuration to determine what to scan, and it acts on parseable information to determine what files to emit. The issue is not whether this information can be determined, the issue is whether this information can be determined ***from meson.build***.

**Comment by xclaesse** [comment]
@eli-schwartz sure, you can always parse yourself to write a depfile if the tool does not. But if you have to do all the job yourself anyway, not sure to understand what's the added value of opaque_target().
```meson
doc = custom_target('doc', output: 'stamp', command: ['doxygen-wrapper.py', '--depfile=@DEPFILE@', '--stamp=@OUTPUT@'])
```

A doxygen module that would actually do the parsing and generate depfile, that would have a real added value.

**Comment by Sahnvour** [comment]
I think this feature would be very interesting for games, to have data/asset building integrated into meson.

**Comment by Sahnvour** [comment]
Is this rejected ?

**Pull request closed without merging**
