### PR TITLE
interpreter: Fix holder_map not being updated when subproject fails

### PR DESCRIPTION
**Pull request by xclaesse**
Fixes: #9038

### CODE REVIEW

**Comment by xclaesse** [comment]
This brings back the part from https://github.com/mesonbuild/meson/pull/9079 that got reverted. Let's see if it pass CI.

**Comment by nirbheek** [comment]
Should this go into 0.59.1?

**Comment by xclaesse** [comment]
I don't think https://github.com/mesonbuild/meson/pull/9079 has been partly reverted in 0.59.1, was it?

**Comment by nirbheek** [comment]
Nope, I thought maybe 9079 had been partially reverted before it was merged or something. Nothing to do here.

**Pull request merged**
