### PR TITLE
Add annotate function attribute

### PR DESCRIPTION
**Pull request by tristan957**
Couldn't figure out what compiler versions this was added in, so just hoping for the best in the top level array!

### CODE REVIEW

**Comment by tristan957** [comment]
@eli-schwartz this seems to be an undocumented clang-only attribute. Maybe this should just be rejected?

**Comment by eli-schwartz** [comment]
Perhaps. Less because of it being clang-only, I'd say, and more because of it being undocumented.

Do you need this? Is it something you would prefer not including as a cc.compiles('...') string in your meson.build?

**Comment by tristan957** [comment]
I can live with a cc.compiles

**Comment by eli-schwartz** [comment]
Okay, sounds like it's not worth it then.

**Pull request closed without merging**
