### PR TITLE
Fix new linter warnings.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
I already have a PR for this. I didn't get a chance to push a couple more commits before the weekend.

The changes here are actually wrong though.

**Comment by jpakkane** [comment]
> The changes here are actually wrong though.

In which way?

**Comment by eli-schwartz** [comment]
> > The changes here are actually wrong though.
> 
> In which way?

In particular, all the context manager stuff surrounding build_wrapper comes with a TODO comment saying it shouldn't be a context manager. Pylint is correctly emitting a warning that the context manager doesn't establish a meaningful context, so I ripped it out to make the code simpler, shorter, and less prone to flow analysis.

**Comment by eli-schwartz** [comment]
pylint is also incapable of analyzing when variables will exist in multiple conditional blocks using the same conditional, and I don't believe the solution is to add code that fails mypy strict-optional just to make pylint happy with a check that is *very* prone to false positives.

**Pull request closed without merging**
