### PR TITLE
Add support for parsing rust unit tests

### PR DESCRIPTION
**Pull request by dcbaker**
this is a pretty basic first step for rust testing. What I'd like to follow up with is a rust module method that can be passed a rust build target, and create a new executable and test target with thaat information. But for now getting support for getting the test outputs and putting them in the junit xml that meson test generates seems like a good start.

### CODE REVIEW

**Comment by anholt** [comment]
Shouldn't we also have a passing rust unit test, to make sure we're parsing its output successfully?

**Comment by anholt** [comment]
I looked into the arguments of rust test binaries, and this does seem like the right way to be running and parsing them, at least for now (apparently there's json output for tests, but that's a nightly feature)

**Comment by dcbaker** [comment]
There's several features that are "nightly only" that would be really nice to have (there's one to tell you what linker rustc is going to invoke, which would make the other bug just go away :(

I saw the json too, and wanted to use that. It looks like that landed in 2016 (https://github.com/rust-lang/rust/pull/30711)?

**Comment by dcbaker** [comment]
I've added both a case of no failing, and of all skip. It seems that we don't have a way with our test.json to give expected test results yet. I'm not sure I want to go down that path right now though.

**Comment by anholt** [comment]
rust test support lgtm, I'll leave the second commit to more of a meson insider.

**Comment by dcbaker** [comment]
#7860 contains this, with fixes. Closing in favor of that.

**Pull request closed without merging**
