### PR TITLE
Create pdb files with MSVC

### PR DESCRIPTION
**Pull request by jpakkane**
Works with pch. Does not work with object extraction. It seems to be impossible to support both because pdb files can be either per-object or per-target.

 - per-object files can have different pdb paths and they are joined during linking but for some reason pch files *must* have the path to the target
 - per-target files work but then you can't take an object file from `foo.pdb` and put it in `bar.pdb`

### CODE REVIEW

**Comment by jpakkane** [comment]
Should we just merge this to get something going so we can improve later? I can't really think of a satisfying solution that would work on all cases.

Related to that, does this branch produce pdb files that fulfill GStreamer's requirements? It is the most important downstream user and if it works for gst (even if not perfect), it should work for most projects.

**Comment by nirbheek** [comment]
I haven't had a chance to do a full review of this or test with GStreamer. I'll have something by Monday.

**Comment by jpakkane** [comment]
Cool, thanks a lot.

**Comment by nirbheek** [comment]
The patches seem to work for me for building pdbs, and I have a bunch of patches on top of this that will install them, and that does everything for GStreamer. Do you mind if I push them to this pdb branch?

**Comment by jpakkane** [comment]
Go for it.

**Comment by jpakkane** [comment]
Looks good to me. Is this ready to merge now?

**Comment by nirbheek** [comment]
The only problem here is that the PDB files aren't tracked by Ninja, so if you delete a PDB file it won't be regenerated. The rest is ok, I think.

**Comment by jpakkane** [comment]
I can live with that.

**Pull request merged**
