### PR TITLE
Change meson test's build failure exit code to 125

### PR DESCRIPTION
**Pull request by fiesh**
As discussed on IRC with @nirbheek

### CODE REVIEW

**Comment by fiesh** [comment]
I don't understand what these assertion failures at

https://dev.azure.com/jussi0947/jussi/_build/results?buildId=3072&view=logs&jobId=4765624a-838f-5591-4ff3-7f04f17a3ee2&taskId=714cceef-44b5-59ec-4770-2c7519427c15&lineStart=537&lineEnd=538&colStart=1&colEnd=1

are... help appreciated!

**Comment by scivision** [comment]
I believe these errors on `cygwin gccx64ninja`:

>  test_installed_modes_extended
> test_install_umask

Are a generally known issue unrelated to this PR, they are happening on everyone's PR. Just a different TODO.

**Comment by scivision** [comment]
In general I am supportive of using distinct error codes to have more signaling fidelity, so it seems like a nice idea

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
