### PR TITLE
auto update wrap-hg and wrap-git subproject

### PR DESCRIPTION
**Pull request by AlexandreFoley**
Using the keyword "branch" instead of "revision" in wrap-git and wrap-hg wrap files will trigger automatic pull and update of the revision identifier upon reconfiguration or regeneration of the build files.
If uncommited changes are detected in the subproject it instead print a warning and does not pull nor update.
If auto-updating is undesirable (it can cause a significant slowdown of the configuration process) the keyword revision has the same behavior as before.

### CODE REVIEW

**Comment by thiblahute** [comment]
@jpakkane It seems to be the exact branch I have been using this last few days so yeah, should be good :)

**Comment by tp-m** [comment]
imho auto-updating things over the network should always be an opt-in, and an opt-in by the user as well, not the dev who made the .wrap file and decided on something. Or at least there should be a way for users to disable this. Build stuff hitting the network unexpectedly is uncool. (I might be barking up the wrong tree entirely here, in which case please just ignore me)

**Comment by nirbheek** [comment]
I agree with @tp-m. It's for exactly this reason that everyone runs `xsltproc` with `--nonet` always. Builds should not hit the network, and wraps should only update explicitly unless set to auto-update explicitly by the user.

**Comment by nirbheek** [comment]
@AlexandreFoley also, I only noticed it a few days ago, but you should fix your commit formatting. It's very hard to read your commits. I'm actually surprised that no one else corrected you already. :)

Commit messages should have two parts: a header (less than 50 characters, but this is a soft limit) and body (wrapped at 70 characters). There must be an empty line separating the two.

See this for more details: http://chris.beams.io/posts/git-commit/

**Comment by AlexandreFoley** [comment]
@tp-m  I agree that auto updating is not welcome in general, the first problems tiblahute ran into demonstrated that nicely. Having the ability to update all subprojects with single command however is quite handy. 
The use i have for this keyword is for development where I control the subproject and update them regularly. This update feature actually does not have to hit the net. For actual distribution I wouldn't advise using it too.

As it stand it is opt-in, but i do think it would be better if it was its' own target (as Tiblahute suggested in the revert thread) doing it rather than upon reconfiguration, with no different keyword.
That way it would actually be the user's decision to pull updates at all time.
But that's more work than what i can tackle in this project at this time.

**Comment by jpakkane** [comment]
After discussion on IRC we chose to just do the revert instead of this. It was felt that automatically doing something over the network should not be done. We can come back to this after the release but for now closing this. Thanks.

**Pull request closed without merging**
