### PR TITLE
Fix some CI summary deprecation warnings

### PR DESCRIPTION
**Pull request by nirbheek**
Supposedly, breakage will happen in a few months.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
https://github.com/eli-schwartz/meson/commit/a73137d0fe3fa74e677ff2c7ca15bbb3cfc36112

At the time, I had discovered it kinda doesn't work, because updating to node 20 broke the os_comp tests. I never got around to redesigning them to free us of the oppression of github's action versions running inside arbitrary containers with older glibcs. And then just recently that hit us *again*. :)

**Comment by eli-schwartz** [comment]
The CI results are in -- this breaks the workaround introduced in #13424.

**Comment by nirbheek** [comment]
Hm, so we need to still use older node with the bionic job at least.

**Comment by nirbheek** [comment]
Now the only things left to update are checkout (for bionic) and codecov (because there's a breaking change)

**Comment by nirbheek** [comment]
No new build failures fwict, ok to merge @eli-schwartz?

**Comment by nirbheek** [comment]
Will merge this in 24h if there are no objections. I have manually verified that the CI failures are not new.

**Pull request merged**
