### PR TITLE
New logo and license text. Closes #4921. [skip ci]

### LINKED ISSUE #4921: Update Meson logo
There are many references to the old logo:
https://github.com/mesonbuild/meson/tree/master/graphics and https://github.com/mesonbuild/meson/tree/master/docs/theme/extra/images

### PR DESCRIPTION
**Pull request by jpakkane**
Fractions of license text shamelessly stolen from GNOME's trademark page. Since IANAL, not sure if the current wording is good. Comments welcome.

### CODE REVIEW

**Comment by nirbheek** [comment]
👍, the logo license text is restrictive and that's good till we know better, since Meson is not a GUI program and no distro is going to need to package it.

**Comment by mensinda** [comment]
Actually, I am currently using the (old) meson logo in the KDevelop meson plugin, so I don't know if this will be an issue. I am not good with legal stuff.

**Comment by jpakkane** [comment]
We can work something out for that.

**Comment by mensinda** [comment]
Sure, thanks. I guess the easiest way to handle this would be to install the new meson logo in `/usr/share/icons/hicolor/<resolution>/apps/meson.png`. This is what the KDevelop plugin currently does.

I think that meson installing the icon would be preferable anyway.

**Comment by jpakkane** [comment]
I would love to do that but we'd need guidance from Debian, Fedora and others. Installing restricted images might not be DFSG compliant.

**Comment by mensinda** [comment]
We would have the same legal problems with KDevelop. Is there a specific reason for the current license text? Would it be possible/desirable to switch to the Creative Commons license or something similar? That way redistributing the logo shouldn't be a problem.

**Comment by jpakkane** [comment]
The reasons for this are the same as [with GNOME's trademark policy](https://www.gnome.org/logo-and-trademarks/). Basically freely redistributing the logo _is_ the problem, we need to maintain full control over it for brand purposes.

**Comment by mensinda** [comment]
OK, I didn't know about that. It seems like that Trademark stuff is rather annoying. In that case, redistributing the logo with meson itself (and making sure that everything works out with the distributions) would be preferable.

With that in mind am I technically allowed to redistribute the old logo in the KDevelop meson plugin, or should I remove it just to be safe?

**Comment by jpakkane** [comment]
Well, _super_ technically the old logo was not licensed under anything since the Apache license in Meson was only for code. So nobody should be allowed to distribute it anywhere. But there's no reason to change anything about that, keep on distributing it until this is sorted out.

**Comment by mensinda** [comment]
Sure, thanks. Let's hope this legal mess is easy to resolve.

**Pull request merged**
