### PR TITLE
Remove escaping for triple-quoted strings

### LINKED ISSUE #3429: regression with string escaping/formatting and cc.run()
#3169 seems to have caused a regression with the GLib meson build, which does the following thing (simplified):
```
  templ = '''
#include<stdio.h>
int main(int argc, char **argv) {
  printf("%d\n", (int)@0@);
  return 0;
}'''
value_FOO = cc.run(templ.format('FOO'), name : 'FOO value').stdout().strip()
```

Let's ignore for now that this is not cross-compile friendly and should be using `cc.compute_int()` or such instead.

Since the above commit 36aab0f4b2a05a1ae4c8603e57b4c3c684fe8ea8 this now fails with `Checking if "POLLIN value" runs: DID NOT COMPILE`

The reason this fails to compile is because the code to be compiled is now (excerpt from log file):

```
Code:
#include<stdio.h>
int main(int argc, char **argv) {
  printf("%d
", (int)FOO);
  return 0;
}
Compiler stdout:
 
Compiler stderr:
 /tmp/tmpguawnoj0/testfile.c: In function ‘main’:
/tmp/tmpguawnoj0/testfile.c:5:10: warning: missing terminating " character
   printf("%d
```

As you can see, the `\n` in the multi-line string has been turned into an actual newline here. Before the commit, the code would have a backslash and an `n` character there instead.

### PR DESCRIPTION
**Pull request by NickeZ**
Fixes #3429

### CODE REVIEW

**Comment by jpakkane** [comment]
Has this been tested with the old version of glib that was broken?

**Comment by jpakkane** [comment]
Thinking about this it actually seems like a nice separation even if it came about by accident. Triple quoted strings behave roughly like "raw strings" in that they pass directly and single quoted strings have expansion and all others done.

Nevertheless this requires a regression test for the behaviour and documentation updates.

**Comment by jpakkane** [comment]
Could we add a test that replicates what the glib test did to avoid regressions? Something like:

    x = '''#include<stdio.h>
    int main(int argc, char **argv) {
      int num = 6;
      printf("This is a number: %d. \n", num);
      return 0;
    }

**Comment by nirbheek** [comment]
Done. I also tested that it breaks without the commit.

**Pull request merged**
