### PR TITLE
gnome: Add a generate_doc_from_gir method.

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
This wraps "g-ir-doc-tool"

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Please add test for this

**Comment by jpakkane** [comment]
Are these docs installed? If yes please add an install option. With that, writing the test becomes easier, too.

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by MathieuDuponchelle** [comment]
@ignatenkobrain I'll write one don't worry, you've already asked for it in that very same thread

**Comment by jpakkane** [comment]
The retest thing is a way to tell the ci machine to rerun its integration tests.

**Comment by MathieuDuponchelle** [comment]
Aha OK

**Comment by jpakkane** [comment]
Closing because this is old and conflicting. Open a new mr if still an issue. Thanks.

**Comment by MathieuDuponchelle** [comment]
Yup, sorry I should have closed this, I've shifted my focus to a better documentation tool since then :)

**Pull request closed without merging**
