### PR TITLE
link_whole should be considered a source for targets

### LINKED ISSUE #2180: Can't create a library from link_whole static libraries and without any source files
I have a project that is designed with several subprojects that are built into static libraries, then a larger library which is linked from all of them like so:

```meson
lib_wlr = library('wlroots', [],
    link_whole: [
        lib_wl_protos,
        lib_wlr_backend,
        lib_wlr_render,
        lib_wlr_types,
        lib_wlr_util,
        lib_wlr_xcursor,
    ],
    dependencies: _wlr_deps,
    include_directories: wlr_inc)
```

This fails: "Build target wlroots has no sources"

This commit includes our workaround: https://git.io/v7HNX

### PR DESCRIPTION
**Pull request by dcbaker**
Currently sources, generated sources, and objects are considered to be
sources for a target, but link_whole should also fulfill the sources
requirement.

Fixes #2180

### CODE REVIEW

**Comment by nirbheek** [comment]
Test failure looks relevant.

**Comment by dcbaker** [comment]
The output gives me no clues what's wrong and I don't have access to a windows development machine. Am i just missing something obvious in the output?

**Comment by nirbheek** [comment]
Looks like the traceback is missing in the output, but is present in the build artifact:

```
Meson encountered an error:
Could not find a C or C++ compiler. MSVC can only build C/C++ projects.
```

This is from `mesonbuild/backend/vs2010backend.py`, which tries to find an MSVC compiler on the specific target. So it looks like you need to add code to `build.py:BuildTarget().process_compilers()` for adding target compilers for `link_whole:` objects.

Unlike `ExtractedObjects` where we only link to a subset of the objects, for `link_whole:` I think it's correct to add all the compilers used by the `link_whole:` targets to the compilers of the current target.

**Comment by dcbaker** [comment]
I rebased this on #2326, which I did for other reasons, we'll see what the CI says, but I think it should fix the msvc problem.

**Comment by dcbaker** [comment]
I'm not convinced that WHOLEARCHIVE in msvc can be used without source files. It doesn't seem to trigger a link for the project. Google doesn't really turn anything up for this. I guess we could emulate this in msvc by including the object files from the whole archive instead (which would actually probably work for older vs as well). Does anyone have suggestions?

**Comment by nirbheek** [comment]
It does work for MSVC when you call the linker manually (I ran the test myself and it produced a usable DLL), but not via the VS backend for some reason. I think we're missing some syntax in the vcxproj file that will tell VS what we want to do.

The problem is, the format is not documented so the only way to figure out what's wrong is to sit down in Visual Studio, make a project that does a 'link whole' on a static library to make a DLL, and see what the syntax is. I'll look into this.

**Comment by nirbheek** [comment]
I have a fix for this, can I push it to your branch?

**Comment by dcbaker** [comment]
sure. do you need anything special from me?

**Comment by nirbheek** [comment]
Nope, just wanted to make sure that I didn't clobber with you. Pushed.

**Pull request merged**
