### PR TITLE
docs: compiler.find_library: discourage lib prefix

### PR DESCRIPTION
**Pull request by jtojnar**
I continue seeing it in the wild.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
CI failure is very relevant.

**Comment by eli-schwartz** [comment]
I do not want you to use unicode in the docs, NACK to the first commit. :)

**Comment by tristan957** [comment]
unicode is already used in the docs, for instance in the reference tables. No idea why we aren't just using `^1` there instead of superscript 1

**Comment by eli-schwartz** [comment]
Idk about that, but I do know that frivolously using ~~"typographically correct"~~ "annoying" quotes is... annoying. And it's also frivolous.

So anything that catches them and makes them error out is good in my book. Now if only we could remove them from the Unicode standard...

I think in general if your documentation relies on Unicode then you need to do some deep introspection on why you think you need it and whether that's in fact true. It probably isn't.

**Comment by tristan957** [comment]
image

**Comment by tristan957** [comment]
I also hate unicode quotes

**Comment by eli-schwartz** [comment]
Anyway this approach is totally wrong, I submitted a PR to do this correctly, by warning about it instead of burying it in docs where no one will see it.

**Pull request closed without merging**
