### PR TITLE
Windows parallel test

### PR DESCRIPTION
**Pull request by nioncode**
This properly fixes parallel `meson` unit tests on Windows.

### CODE REVIEW

**Comment by nirbheek** [comment]
The commit message of the second commit is not very descriptive. The body should contain a few sentences explaining exactly what was broken and how you fixed it. The patch may seem obvious now, but it won't be in the future. Could you please fix that? Thanks!

**Comment by nioncode** [comment]
Done.

**Comment by jpakkane** [comment]
retries = 5
        for i in range(0, retries):
            try:
                shutil.rmtree(self.dir)
                return
            except OSError:
                if i == retries:
                    raise

This will not work properly. Range() goes from zero to one minus max value so the comparison will never be true. Please also add a delay inside the loop to give the other process time to get finished. Something like `time.sleep(0,1)`.

Thanks,

**Comment by nioncode** [comment]
I never ran into issues without timeout, but I added a simple exponential backoff.

**Pull request merged**
