### PR TITLE
Fix nvcc error with threads dependency (4999)

### PR DESCRIPTION
**Pull request by jml1795**
Fixes issue #4999 @obilaniu Thanks

### CODE REVIEW

**Comment by obilaniu** [comment]
I figure #4993 probably has a similar solution - involving wrapping the underlying compiler's flags with something like `['-Xcompiler', '-fopenmp', '-Xcompiler', '-pthread']`. Maybe combine them in one PR?

**Comment by jml1795** [comment]
thats what I was thinking originally, but I think it may be a logic error higher up the call chain. I didn't have much time to dig into it but somehow `-fopenmp` was sneaking into the linker args when it looks like that is only added by the `GccCompiler`  which isn't in the `CudaCompiler` class hierarchy. Does this make sense? To be honest, I didn't get much time to look at the openmp issue though

**Comment by jml1795** [comment]
@obilaniu Verified openmp isn't going to be as simple. Should probably track that as its own issue

**Comment by jpakkane** [comment]
Let's do incremental fixes instead of megacommits. This improves things so merging. Thanks.

**Pull request merged**
