### PR TITLE
Set WINEPATH when running serialized executables

### PR DESCRIPTION
**Pull request by nirbheek**
When the exe runner is `wine` or `wine32` or `wine64`, etc. This allows people to run tests with wine.

Closes https://github.com/mesonbuild/meson/issues/3620

Also sets it for generic exe running such as with custom targets or generators.

### CODE REVIEW

**Comment by xclaesse** [comment]
I gave it a try, but getting same error as in CI:
AttributeError: 'Executable' object has no attribute 'get_transitive_build_target_deps'

**Comment by nirbheek** [comment]
@xclaesse Try again. You will also have to set `WINEPATH` to point to the MinGW DLL prefix where you get other dependencies like libffi and libintl. It should be of the form `Z:/usr/lib/foo`.

**Comment by nirbheek** [comment]
@jpakkane this PR adds cross-mingw CI, and the Docker image is missing the relevant Ubuntu packages, could you add those please? The toolchain is mingw-w64 x86_64.

**Comment by jpakkane** [comment]
Once tests pass, this is ok to merge.

**Comment by nirbheek** [comment]
> Started image build, should be uploaded in an hour or so.

I, uh, forgot to mention that we also need `wine` in the image, so all tests still fail ;)

**Comment by jpakkane** [comment]
Updated. https://twitter.com/mesonbuild/status/1003060372453150721

**Comment by nirbheek** [comment]
Is the size so large because we're also including suggested dependencies for wine? If the tests pass now, we may want to remove those to keep the image size low.

**Comment by nirbheek** [comment]
Two packages are missing: mingw-w64-i686-dev and mingw-w64-x86-64-dev. These are needed for `libwinpthread-1.dll`, which is needed by the openmp test.

**Pull request merged**
