### PR TITLE
Allow listing deprecated keyword arguments

### PR DESCRIPTION
**Pull request by ebassi**
The `permittedKwargs` decorator should have the ability to define a list of deprecated arguments, and thus warn about their use.

For a potential use of this, see PR #2216.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
probably we should implement description... so we will be able to show some hints for users..

**Comment by ebassi** [comment]
@ignatenkobrain Any preference for the syntax?

If we want to force a reason/replacement, we can simply use a dictionary:

```py3
@permittedKwargs({'foo', 'bar', 'baz'}, deprecated={'bar': 'Use baz instead'})
def foobarize(...)
    ...
```

**Comment by nirbheek** [comment]
I think we will make a lot of use for this feature, so I was thinking of a global mapping like:

 ```python
deprecation_warnings = {
    ('funcname', 'kwargname'): 'Description saying what to do',
    ('funcname2', 'kwargname2'): 'Description2 saying what to do',
}
```

In the case of LINGUAS, you want to specifically say: use the LINGUAS file instead of this kwarg, etc.

**Comment by ebassi** [comment]
@nirbheek It's kind of weird to have a global mapping when modules can deprecate keyword arguments independently; it would require modifying the central dictionary every time a module deprecates an argument. I also don't think using a tuple of `(function name, argument)` is descriptive enough if it's a dictionary that will have to be modified by multiple people, multiple times; what happens if two different modules define the same function? Unless you mean using something like `module1.foo` and `module2.foo`, but that makes it a bit meh.

**Comment by nirbheek** [comment]
I was thinking there would be one for the main meson functions (in `interpreter.py`), and one for each module that resides in `gnome.py`, etc.

**Comment by jpakkane** [comment]
Seems reasonable.

**Comment by jpakkane** [comment]
Please convert one (or several :) ) existing deprecation checks to this new one so we have an actual code using it.

**Comment by jpakkane** [comment]
ping

**Comment by jpakkane** [comment]
ping again

**Comment by ebassi** [comment]
Sorry, haven't had time to look at this again until now. Will try to come up with a separate PR that adds a global `deprecation_warnings` mapping for each module.

**Comment by ebassi** [comment]
@nirbheek Some more guidance would help.

This issue started off with getting a warning for deprecated kwargs; I still think that modifying the `permittedKwargs` decorator is the best option, and using a semi-standard `deprecated_warnings` dictionary per-module is a good thing.

The deprecations outside of `gnome.yelp()`, though, are mostly for whole methods, so that would not match what we're discussing here.

Could you please clarify how do you envision this working, and whether or not we should have the same approach for kwargs and methods?

**Comment by nirbheek** [comment]
This was implemented in https://github.com/mesonbuild/meson/pull/3486.

**Pull request closed without merging**
