### PR TITLE
interpreter: add support for --force-fallback-for

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
This new command line option allows specifying dependencies for
which to force fallback.

See the documentation for more information

Fixes: #7218

### CODE REVIEW

**Comment by tp-m** [comment]
What about its little brother `--no-fallback-for=xyz`? :)

**Comment by MathieuDuponchelle** [comment]
> What about its little brother `--no-fallback-for=xyz`? :)

See my comment @ https://github.com/mesonbuild/meson/issues/7218#issuecomment-637821295 :)

**Comment by xclaesse** [comment]
Looks good to me. I prefer without the `-for` suffix but I can live with that.

There is a corner case we should maybe clarify: `--wrap-mode=nodownload --force-fallback-for=glib`. In that case it will work only if glib has already been downloaded. Maybe just mention that in the doc?

**Comment by MathieuDuponchelle** [comment]
> Looks good to me. I prefer without the -for suffix but I can live with that.

I implemented it, I get to choose :P More seriously, in case someone wants to give a tie breaker feel free to comment, not too hard to change

> There is a corner case we should maybe clarify: --wrap-mode=nodownload --force-fallback-for=glib. In that case it will work only if glib has already been downloaded. Maybe just mention that in the doc?

Good point, I only mentioned the interaction with `nofallback`, I'll add a quick note

**Comment by dabrain34** [comment]
I like this change 
I think it would make sense to define this force fallback also in a given project
 
I mean if I understand well, you need to pass the `--force-fallback-for=glib` to force the use of fallback glib to the configure command line

**Comment by xclaesse** [comment]
> I think it would make sense to define this force fallback also in a given project `meson.build` file as a default and overriden by the command line if necessary

Do you have a specific use-case for that in mind? I don't think we should hold this PR for that, we can find a way later if needed. 

Looks all good to me, LGTM.

**Comment by xclaesse** [comment]
Oh, mmm, using this new feature and I just realized that you need to pass `glib-2.0` (the dependency  name) and not `glib` (the subproject/wrap name). Shouldn't we allow both?

**Comment by dcbaker** [comment]
This also broke CI since it added a new command line option (which we have tests for apparently)

**Comment by xclaesse** [comment]
Should be fixed by https://github.com/mesonbuild/meson/pull/7335

**Comment by xclaesse** [comment]
@MathieuDuponchelle What do you thing about https://github.com/mesonbuild/meson/pull/7334 ?

**Comment by MathieuDuponchelle** [comment]
Thanks for the fix @xclaesse , not sure why CI didn't complain here! Re #7334 it seems safe to me, and indeed friendlier.

**Comment by xclaesse** [comment]
Not your fault, it's a new test that got merged after this pr ran it's ci.

**Comment by dabrain34** [comment]
> > I think it would make sense to define this force fallback also in a given project `meson.build` file as a default and overriden by the command line if necessary
> 
> Do you have a specific use-case for that in mind? I don't think we should hold this PR for that, we can find a way later if needed.

Yes the idea would be to control that for a given dependency we prefer the fallback. Let's imagine we we are building libdrm for gstreamer plugin with a specific revision with a specific project, would be nice to have a way to force always the subropoject fallback and not have to pass always the command line in order to avoid the use of the system lib

> 
> Looks all good to me, LGTM.

**Comment by MathieuDuponchelle** [comment]
@dabrain34 , not sure I see the point, why not just use subproject() then?

**Comment by xclaesse** [comment]
@dabrain34 if for your project you always want to fallback on libdrm, I would suggest to write a native file (or cross file depending on your case) and set all options needed, such as `force_fallback_for='libdrm'` in `[built-in options]` section, once we land https://github.com/mesonbuild/meson/pull/6597. That way you only have 1 config file to pass on the command line. Does that make sense for your use-case?

**Comment by dabrain34** [comment]
It might have misunderstood as I was confused by the previous error message
So if I want a project to use an external library version, you have to include the subproject before right ?

**Pull request merged**
