### PR TITLE
Handle cmake dependencies which require a specified version

### PR DESCRIPTION
**Pull request by dcbaker**
@jekstrand asked me to take over this for him, I've rebased this and done a bit of cleanup (wrapping long lines, updating the version for 0.57) I'm assuming that this is still going to fail on Ubuntu 16.04, I'll have to fix that next.

### CODE REVIEW

**Comment by mensinda** [comment]
The test failure is relevant: `Run-time dependency cmmesonversionedtestdep found: NO (tried cmake)`

This still LGRM though since this is basically #7361

**Comment by jpakkane** [comment]
Ping. What's the status of this one?

**Comment by mensinda** [comment]
It is good to go feature wise, but the tests are failing.

**Comment by dcbaker** [comment]
@mensinda I've reworked this version quite a bit, could you give it another look?

**Review by mensinda — APPROVED** [review]
LGTM

**Pull request merged**
