### PR TITLE
Simplify list of build def files

### PR DESCRIPTION
**Pull request by xclaesse**
Refactor the code inside a common function for consistency.
    
    It's not needed to add dependencies in func_configure_file() because
    it's already done in run_command_impl(). Do it only for files from
    `input:` in the case some of them does not end up in the command
    arguments.

### CODE REVIEW

**Comment by dcbaker** [comment]
@jpakkane, I thought at one point we were telling people specifically to add string files to sources so they'd be added as dependencies, is that right? Because if it is this is a backwards compatibility problem.

Otherwise I think this is a reasonable thing to do.

**Comment by jpakkane** [comment]
I don't think we did? Regardless, maybe `run_command` should have a kwarg for defining extra dependencies to files that do not appear on the command line. Still, the current auto behaviour is kinda convenient, but I don't think there is a way to make it properly reliable against errors like these (passing `/dev/something`) as argument.

**Comment by jpakkane** [comment]
How about a compromise? Run stat on the input strings and only add a dependency on things that are actually files (and possibly directories)?

**Comment by jpakkane** [comment]
ping

**Comment by xclaesse** [comment]
Actually, I'm wondering what was the original issue here, because I see Meson already adds string paths to `self.build_def_files` only if `os.path.isfile(a)`. And python3 already returns False for `/dev/stdout`.

But still, this patch could be a nice cleanup, and I'm not sure run_command_impl() does the right thing atm:
1) It add a dependency on the executable only if its path is inside source dir. Why? Shouldn't it also add dep even on system executables?
2) For arguments, if they are path to file, it adds in build_def_files the relative path starting from sourcedir, even if it's an absolute path to some system file. It should only add the dep if its relative path is inside sourcedir (like it does for the executable path) or keep the absolute path.
3) In configure_file it calls `os.path.normpath` but not in run_command, that's inconsistent.

**Comment by xclaesse** [comment]
@jpakkane I updated this PR because I couldn't reproduce the original issue, but while working on it I noticed that there are inconsistencies. What do you think about this new PR?

**Pull request merged**
