### PR TITLE
Add representation of the C (or other language) preprocessor

### PR DESCRIPTION
**Pull request by dcbaker**
There are cases where users want/need to use the C Pre Processor directly. They might attempt this with code like:
```meson
cpp = find_program('cpp')
custom_target(..., command : [cpp, ...])
```
Of course, that runs into problems when they use a machine file, because meson uses `cpp` to mean `C++`, and they get their compiler instead of `cpp`. Of course, there's another problem, `cpp` isn't portable.

This MR attempts make that better by adding an object representation it can be gotten like this:
```meson
cc = meson.get_compiler('c')  # or cpp, objc, objc++, or any other compiler with a pre-processor
pp = cc.get_preprocessor()
if pp.has_argument('-foo')
   ...
endif
```

It provides a number of methods like the compiler object:
- cmd_array
- has_argument
- has_multi_argument
- get_supported_arguments
- first_supported_argument

But is also an `ExternalProgram`, like those returned by `find_program()` and can be used like one:
```meson
custom_target(..., command : [pp, ...])
```

This has the advantage of being portable, and has the ability to be tested like a compiler would be.

This is obviously still a WIP, it needs tests, docs, and such. I'm just trying to gauge if this is a useful solution or not.

Related: #8434

### CODE REVIEW

**Comment by dcbaker** [comment]
@jeremyhu, I know this affects you (and probably other xorg people)

**Comment by jpakkane** [comment]
How portable is this as a concept? Does MSVC provide a standalone preprocessor executable?

**Comment by eli-schwartz** [comment]
The visualstudio compiler mixin returns `['compiler', '/EP']`.

The gcc mixin doesn't return cpp either, it returns `['gcc', '-E', '-P']`

**Comment by dcbaker** [comment]
The point isn't to provide `cpp`, it's to provide a portable mechanism to get a thing that does C (or other language with a pre-processor, like D) and check to see what arguments it supports, just like we would with a compiler.

**Comment by e820** [comment]
Truly lovely addition - just gotta make sure to remember passing `-P` / `--no-line-commands` to clang-like preprocessors to avoid funky output.

**Comment by jon-turney** [comment]
> Truly lovely addition - just gotta make sure to remember passing `-P` / `--no-line-commands` to clang-like preprocessors to avoid funky output.

Not sure if this means we should assume `-P` is wanted, but that seems unsafe, as we can't know if the preprocessor output is going to be used as is, or fed into some sort of tool which can report errors (in which case #line directives are wanted to enable those errors to be reported against the source location)

**Comment by e820** [comment]
> > Truly lovely addition - just gotta make sure to remember passing `-P` / `--no-line-commands` to clang-like preprocessors to avoid funky output.
> 
> Not sure if this means we should assume `-P` is wanted, but that seems unsafe, as we can't know if the preprocessor output is going to be used as is, or fed into some sort of tool which can report errors (in which case #line directives are wanted to enable those errors to be reported against the source location)

That certainly is a justified concern. Do you a few specific ones in mind? I absolutely agree that the preprocessor representation should be generic enough but I'd also like to avoid having to perform manual compiler id checks to determine the required preprocessor flags if possible.

**Comment by dcbaker** [comment]
@e820 you shouldn't have to, the design is to something use `has_argument` or `get_supported_arguments` instead of doing ID checks, just like you would with a compiler

**Comment by dcbaker** [comment]
I've rebased this on master, but nothing more ATM. I'll try to find time to add some tests and documentation

**Comment by jon-turney** [comment]
> There are cases where users want/need to use the C Pre Processor directly. They might attempt this with code like:
> 
> ```meson
> cpp = find_program('cpp')
> custom_target(..., command : [cpp, ...])
> ```
> 
> Of course, that runs into problems when they use a machine file, because meson uses `cpp` to mean `C++`, and they get their compiler instead of `cpp`. Of course, there's another problem, `cpp` isn't portable.

Cross-referencing #8434 for that.

**Comment by xclaesse** [comment]
Oh, I did not know you were working on this, that's nice. There is a little bit of overlap with what I've been working on there: https://github.com/mesonbuild/meson/pull/10149. You worked mostly on interpreter side of preprocessor while I worked mostly on the backend side. Not sure there is much we can do in common.

Another thing I've been wanting is for example `file = cc.preprocess('foo.c')` that create a target that preprocess but not compile the file. For something like that: https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi/-/blob/meson/src/meson.build#L73.

**Comment by dcbaker** [comment]
I mostly need this because xorg had some interesting legacy code that uses the c pre processor as a code generator, but yeah, if we can make it with together that would be nice

**Comment by dcbaker** [comment]
@xclaesse I've added a completely untested `preprocess` method to the `Preprocessor` object, but I think to make it reliable I'll need your series

**Comment by xclaesse** [comment]
@dcbaker I think ideally it should somehow go through the backend to get c_args and get -I from all deps, etc. But maybe that's going too far?

**Comment by xclaesse** [comment]
let's keep that out of scope for this PR, we can think about something later.

**Comment by e820** [comment]
Any updates on this on PR?

**Comment by nirbheek** [comment]
```
<dcbaker@dcbaker:matrix.org> I think 8452 should be closed
<dcbaker@dcbaker:matrix.org> I’m on my phone though, so not logged into GitHub
```

Context: we now have `cc.preprocess()`, as pointed out by @tristan957 on matrix.

**Comment by jon-turney** [comment]
> There are cases where users want/need to use the C Pre Processor directly. They might attempt this with code like:
> 
> ```meson
> cpp = find_program('cpp')
> custom_target(..., command : [cpp, ...])
> ```
> 
> Of course, that runs into problems when they use a machine file, because meson uses `cpp` to mean `C++`, and they get their compiler instead of `cpp`. Of course, there's another problem, `cpp` isn't portable.

I think there's maybe still a small issue here that if you had a project which just used the pre-processor, and was expecting to be built in an environment where only the pre-processor (and no compiler) is available, you can't write `find_program('cpp', 'mcpp')` and have it always work, due to this confusion of identifiers.

**Pull request closed without merging**
