### PR TITLE
interpreter: Add warning function

### PR DESCRIPTION
**Pull request by alvarez86**
This is a simple implementation for #2405, as always, feedback is welcome.

### CODE REVIEW

**Comment by TingPing** [comment]
Needs to be added to docs.

**Comment by alvarez86** [comment]
@TingPing I have added the function to the docs.

**Comment by jpakkane** [comment]
This is new functionality so it should be added to the release notes. This goes as a standalone file in `docs/markdown/snippets` directory. Read `Release-notes-for-0.44.0.md` in the same dir to get the format. Once that is done, we'll get this merged. Thanks.

**Comment by alvarez86** [comment]
@jpakkane, I have added the release notes as requested.

**Pull request merged**
