### PR TITLE
Move the optimization options in the compiler config

### PR DESCRIPTION
**Pull request by robUx4**
They have no effect in the "Configuration" PropertyGroup at least in VS2017

This may fixed some of the oddities mentioned in #4394 but probably needs some testing with VS2015 and VS2010

### CODE REVIEW

**Comment by dcbaker** [comment]
In vs2015 (and I assume 2010, but I don't have it installed), what we're generating is correct, for 2017 it's not. I think we need to refactor a bit of the classes so that the 2017 backend can put these in the right place.

I think what we probably want is a helper method that takes an `Element` instance and puts the fields in it, then the 2010 and 2015 we can put them in the PropertiesGroup like we are, and in 2017 we can put them in the Compilers group.

**Comment by robUx4** [comment]
It works with the VS2015 backend as well, it uses the proper values. I cannot test on VS2010.

**Comment by robUx4** [comment]
I installed VS2010 Express and it works as well. That's logical since it sets the values for the Compiler configuration.

**Comment by robUx4** [comment]
Also I looked at an older project generating `vcxproj` that the optimizations were always put in the `CLCompile` part https://github.com/Matroska-Org/foundation-source/blob/master/corec/tools/coremake/vcxproj.inc#L309

**Comment by dcbaker** [comment]
I think this is okay to merge, just needs a rebase now.

**Comment by jpakkane** [comment]
Please rebase so the CI gets rerun and we can get this merged. Thanks.

**Comment by jpakkane** [comment]
Ping.

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by jpakkane** [comment]
Merged as #5006.

**Pull request closed without merging**
