### PR TITLE
Prevent the presence of duplicated items in .vcxproj files

### PR DESCRIPTION
**Pull request by lb90**
As outlined in this VS forum thread:

https://developercommunity.visualstudio.com/content/problem/234871/cannot-load-project-with-duplicated-project-items.html

Visual Studio cannot open projects files that have duplicated items, for example:

```
<ItemGroup>
  <CLInclude Include="glib-enumtypes.h"/>
  <CLInclude Include="glib-enumtypes.h"/>
</ItemGroup>
```

So prevent writing duplicated items in the generated .vcxproj files

Fixes issue #6147

### CODE REVIEW

**Comment by lb90** [comment]
Regarding this, I have two questions:

1. Here to remove duplicates in lists I am doing `sources = set(sources)`. That's the pythonic way, but messes up the order. This should not be a problem at all though. If needed there are other ways that preserve order. Also, we are changing the type from list to set.

2. sources is a container of [mesonlib.File](https://github.com/mesonbuild/meson/blob/46788d1b5bb72f59cc931e54912c81666ce30f84/mesonbuild/mesonlib.py#L213). The equality is defined simply by a string comparison of the path passed at construction the object. So `File('./header.h') != File(././header.h)` etc. Would it be useful to change the comparison to use absolute and normalized paths? Just asking, I'm not much knowledgable with the codebase

**Comment by jpakkane** [comment]
You should use `mesonlib.OrderedSet` to get a set that preserves the insertion order.

**Comment by lb90** [comment]
Ok, thanks! I'm going to update this PR soon

**Comment by lb90** [comment]
I did some testing. When VS loads a project it checks all items for duplicated paths and it applies both path normalization and case insensitive comparison:

- `.\foo\.\bar\..\\\a.cpp` is detected as a duplicate of `foo\a.cpp`
- `header.h` and `Header.h` are detected as duplicate items

But on the other hand it is anaware of symlinks, which it doesn't check at all. For example:

If `header2.h` is a symlink to `header.h`

```xml
<ItemGroup>
  <CLInclude include="header.h" />
  <CLInclude include="header2.h" />
</CLInclude>
```
VS loads the project

Same for directory symlinks (and junctions):

`bar` is a symlink to `foo`

```xml
<ItemGroup>
  <CLInclude include="foo\header.h" />
  <CLInclude include="bar\header.h" />
</CLInclude>
```
VS loads the project.

**Comment by jpakkane** [comment]
If VS does not care about symlink dupes, then we don't have to either. Python stdlib provides path normalization and lowercasing, so you can replicate the behaviour with those with something like:

```python
filtered = OrderedMap()
for f in filenames:
    norm_f = normalize_pathname(f)
    if norm_f not in filtered:
        filtered[norm_f] = f
```

**Comment by lb90** [comment]
[test case/common/221](https://github.com/mesonbuild/meson/tree/master/test%20cases/common/221%20source%20set%20custom%20target) is now failing but...that's actually good :-). In fact, I have tried building the test case with the vs backend on Meson master, and the generated solution does not open in Visual Studio!

**Comment by lb90** [comment]
Here's the generated vcxproj file:

```xml
<?xml version="1.0" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build" ToolsVersion="4.0">
	<ItemGroup Label="ProjectConfigurations">
		<ProjectConfiguration Include="debug|x64">
			<Configuration>debug</Configuration>
			<Platform>x64</Platform>
		</ProjectConfiguration>
	</ItemGroup>
	<PropertyGroup Label="Globals">
		<ProjectGuid>{C61C13A9-83FF-4A7E-946F-FA221F061573}</ProjectGuid>
		<Keyword>x64Proj</Keyword>
		<RootNamespace>first</RootNamespace>
		<Platform>x64</Platform>
		<ProjectName>first</ProjectName>
		<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
	</PropertyGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props"/>
	<PropertyGroup Label="Configuration">
		<ConfigurationType>Application</ConfigurationType>
		<CharacterSet>MultiByte</CharacterSet>
		<PlatformToolset>v142</PlatformToolset>
		<WholeProgramOptimization>false</WholeProgramOptimization>
		<BasicRuntimeChecks>Default</BasicRuntimeChecks>
		<UseDebugLibraries>true</UseDebugLibraries>
		<DebugInformationFormat>EditAndContinue</DebugInformationFormat>
		<BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<ClCompile>
			<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
			<AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<FunctionLevelLinking>true</FunctionLevelLinking>
			<WarningLevel>Level2</WarningLevel>
			<Optimization>Disabled</Optimization>
			<FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
			<PrecompiledHeader/>
		</ClCompile>
		<ResourceCompile>
			<PreprocessorDefinitions/>
		</ResourceCompile>
		<Link>
			<GenerateDebugInformation>DebugFull</GenerateDebugInformation>
			<AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib;%(AdditionalDependencies)</AdditionalDependencies>
			<OutputFile>$(OutDir)first.exe</OutputFile>
			<SubSystem>Console</SubSystem>
			<ProgramDataBaseFileName>$(OutDir}first.pdb</ProgramDataBaseFileName>
			<EntryPointSymbol>mainCRTStartup</EntryPointSymbol>
			<TargetMachine>MachineX64</TargetMachine>
		</Link>
	</ItemDefinitionGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.props"/>
	<ItemGroup>
		<CustomBuild Include="..\g.c">
			<Command>&quot;C:\Program Files\Python38\python.exe&quot; &quot;D:\meson_master\meson.py&quot; &quot;--internal&quot; &quot;exe&quot; &quot;--unpickle&quot; &quot;D:\221_test_case\build\meson-private\meson_exe_python.exe_a884b1451426c9888b4d9bea330ead63585bd138.dat&quot;</Command>
			<Outputs>first@exe\out_g.c</Outputs>
			<AdditionalInputs>D:\221_test_case\build\meson-private\meson_exe_python.exe_a884b1451426c9888b4d9bea330ead63585bd138.dat;D:\221_test_case\cp.py</AdditionalInputs>
		</CustomBuild>
	</ItemGroup>
	<PropertyGroup>
		<_ProjectFileVersion>10.0.30319.1</_ProjectFileVersion>
		<OutDir>.\</OutDir>
		<IntDir>first@exe\</IntDir>
		<TargetName>first</TargetName>
		<TargetExt>.exe</TargetExt>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\meson.build"/>
	</ItemGroup>
	<ItemGroup>
		<CLCompile Include="out_f.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
			<ObjectFileName>$(IntDir)meson-generated_.._out_f.c.obj</ObjectFileName>
		</CLCompile>
		<CLCompile Include="first@exe\out_g.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</CLCompile>
		<CLCompile Include="out_a.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</CLCompile>
		<CLCompile Include="out_a.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</CLCompile>
	</ItemGroup>
	<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets"/>
	<ItemGroup>
		<ProjectReference Include="D:\221_test_case\build\REGEN.vcxproj">
			<Project>{589A1963-CBE6-415F-A18F-9128D65E6381}</Project>
			<LinkLibraryDependencies>false</LinkLibraryDependencies>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include=".\gen-custom-target@cus.vcxproj">
			<Project>{7E4467C6-8CEB-44D5-AAEC-AF3F95598A41}</Project>
			<LinkLibraryDependencies>false</LinkLibraryDependencies>
		</ProjectReference>
	</ItemGroup>
</Project>
```

As you can see, it contains:

```xml
		<CLCompile Include="out_a.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</CLCompile>
		<CLCompile Include="out_a.c">
			<AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
			<PreprocessorDefinitions>%(PreprocessorDefinitions)</PreprocessorDefinitions>
			<AdditionalIncludeDirectories>first@exe;.;..\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</CLCompile>
```

With this PR Meson errors out before generating the defective vcxproj file

**Comment by lb90** [comment]
Now works great! Well, previously I did a stupid thing.

Note that Meson master generates a defective VS solution for test case common/221. Instead, with this PR the generated VS solution loads and works great.

The PR is ready because it is functioning but maybe I can change the code style a bit. I'm gonna keep it WIP for the moment - will see in the meantime if I want to make any style related change.

**Comment by lb90** [comment]
This is now ready for review

**Pull request merged**
