### PR TITLE
[WIP] CI: Port MSYS2 from azure-pipelines to github actions

### PR DESCRIPTION
**Pull request by lazka**
This uses the [msys2/setup-msys2@v2](https://github.com/msys2/setup-msys2) to set up MSYS2. The upside being that you don't have to handle the MSYS2 install/setup quirks (that's the plan at least)

----

There is still one test failing `test cases/common/234 very long command line` and I haven't  figured out why. Maybe someone has an idea.

### CODE REVIEW

**Comment by scivision** [comment]
common/234 is not specifically an MSYS2 issue, it happens with MSVC etc. and [requires Python >= 3.6 and a registry edit to fix](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation).

This test needs to be made a little more programmatic to avoid the intermittent failures. I tested on my Windows machine and this test failed at 260 character path length.

**Comment by lazka** [comment]
We patched the MSYS2 Python to be long paths aware as well, so maybe the registry entry is missing on the GHA Windows VMs vs azure pipelines?

**Comment by lazka** [comment]
Could it be that other things in the stack need to be fixed to support long paths? ninja, gcc etc?

**Comment by scivision** [comment]
Ninja will throw error if the path gets too long (the error says it's too long). MinGW seems to give weird assembler errors. I was getting all 3 types of errors intermittently till I trimmed the path length down.

I guess the idea from the end user perspective is I'd rather not assume their system has been patched, as most are probably not needing to deal with long paths.

**Comment by lazka** [comment]
Sounds good. I'm hoping Windows will switch this on by default at some point in the future.

**Comment by lazka** [comment]
Sounds good. I'm hoping Windows will switch this on by default at some point in the future.

**Comment by lazka** [comment]
Switched to the just released msys2/setup-msys2@v2

**Pull request closed without merging**
