### PR TITLE
tests: start unittesting

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by jpakkane** [comment]
This is ok, but let's merge it only after the release. We should probably also make run_tests.py execute these tests before the current ones automatically.

**Comment by ignatenkobrain** [comment]
Sure, I will take a care about running theese tests automatically

**Comment by jpakkane** [comment]
Why are you using nose instead of unittest, which comes with Python stdlib? This adds a dependency to an external project which is not nice. I really need to write the proper explanation document on why external dependencies are bad for our use case. In regular apps using external deps is exactly what you should do but build systems have weird requirements which make things complicated.

**Comment by ignatenkobrain** [comment]
* coverage report
* xunit integration
* tests generation (for functional tests)
2 features we want.

On Wed, Jul 15, 2015, 1:12 AM Jussi Pakkanen <notifications@github.com>
wrote:

> Why are you using nose instead of unittest, which comes with Python
> stdlib? This adds a dependency to an external project which is not nice. I
> really need to write the proper explanation document on why external
> dependencies are bad for our use case. In regular apps using external deps
> is exactly what you should do but build systems have weird requirements
> which make things complicated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesonbuild/meson/pull/199#issuecomment-121408022>.
>
-- 

-Igor Gnatenko

**Comment by ignatenkobrain** [comment]
Also tests discovering.

On Wed, Jul 15, 2015, 4:15 AM Igor Gnatenko <i.gnatenko.brain@gmail.com>
wrote:

> * coverage report
> * xunit integration
> * tests generation (for functional tests)
> 2 features we want.
>
> On Wed, Jul 15, 2015, 1:12 AM Jussi Pakkanen <notifications@github.com>
> wrote:
>
>> Why are you using nose instead of unittest, which comes with Python
>> stdlib? This adds a dependency to an external project which is not nice. I
>> really need to write the proper explanation document on why external
>> dependencies are bad for our use case. In regular apps using external deps
>> is exactly what you should do but build systems have weird requirements
>> which make things complicated.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mesonbuild/meson/pull/199#issuecomment-121408022>.
>>
> --
>
> -Igor Gnatenko
>
-- 

-Igor Gnatenko

**Pull request closed without merging**
