### PR TITLE
Fix public exposed secondary dependencies

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by pb-cdunn** [comment]
That worked for me. Verified on Linux that all libs now have rpath. (1 was missing without this change.)

**Review by pb-cdunn — APPROVED** [review]
Works for me. All rpaths are now in ELF header.

**Comment by jpakkane** [comment]
The tests need fixing before this can be considered.

**Comment by pb-cdunn** [comment]
Example of failing test ("OS Comp Tests / Arch Linux"):
```
[1/2] Compiling C object client.p/client.c.o
[2/2] Linking target client
FAILED: client 
cc  -o client client.p/client.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /__w/meson/meson/tmpbca1hxgu/install/val2/lib/libval2.so -Wl,--end-group -Wl,-rpath,/__w/meson/meson/tmpbca1hxgu/install/val2/lib -Wl,-rpath,/__w/meson/meson/tmpbca1hxgu/install/val2/lib -Wl,-rpath-link,/__w/meson/meson/tmpbca1hxgu/install/val2/lib
/usr/sbin/ld: warning: libval1.so, needed by /__w/meson/meson/tmpbca1hxgu/install/val2/lib/libval2.so, not found (try using -rpath or -rpath-link)
/usr/sbin/ld: /__w/meson/meson/tmpbca1hxgu/install/val2/lib/libval2.so: undefined reference to `val1'
collect2: error: ld returned 1 exit status
```

**Pull request closed without merging**
