### PR TITLE
Add `export_dynamic` argument to `executable`.

### PR DESCRIPTION
**Pull request by lamefun**
This complements the `shared_module` feature.

### CODE REVIEW

**Comment by jpakkane** [comment]
I think CMake adds this unconditionally. Is there ever a case where you would not want to have export-dynamic? Could we just have that on always?

**Comment by lamefun** [comment]
I think that other than the binary size, this flag would ever be a problem.

**Comment by jon-turney** [comment]
I think it's pretty trivial to make an example where the presence of this flag causes a different symbol to be resolved.

Whether it's useful, or something that any project relies on, I don't know.

**Comment by jpakkane** [comment]
Could we just enable it by default and fix it if someone files an actual problem with real world usage?

**Comment by nirbheek** [comment]
Note: please always add a line like "Closes #bugnumber` to the commit message so that the issue, in this case https://github.com/mesonbuild/meson/issues/2644 is closed when the PR is pushed.

**Comment by jon-turney** [comment]
> Could we just enable it by default and fix it if someone files an actual problem with real world usage?

[this](https://blog.flameeyes.eu/2008/02/why-would-an-executable-export-symbols/) has some discussion of possible problems.

**Comment by lamefun** [comment]
CMake doesn't use this by default either, you have to set ENABLE_EXPORTS target property.

**Comment by xclaesse** [comment]
I'm wondering if we should instead just expose that value to the user so he can pass it to link_args manually. The reason I'm saying this is pkgconfig.generate() method also needs a way to write that value into pc files. GLib's gmodule-expose-2.0.pc does it and it's needed to generate those pc files using meson.

The other solutions I see are creating a special Dependency object like we do for threads, or add `export_dynamic` to pkgconfig.generate() method as well.

Suggestions?

**Comment by jpakkane** [comment]
> clang  -o prog 'prog@exe/prog.c.o' -Wl,-export-dynamic -ldl  
> ld: unknown option: -export-dynamic

Apparently Apple's Clang does not support this particular flag. Is there a corresponding argument for that or do we just need to make it return `[]` on Apple?

**Comment by jpakkane** [comment]
I tested with CMake and it does not add any compiler arguments in this case. Update this so that on OSX it returns [] so the test suite passes and we'll get this merged. Thanks.

**Comment by xclaesse** [comment]
What's your suggestion for pkg-config generator while we are at it?

**Comment by jpakkane** [comment]
> What's your suggestion for pkg-config generator while we are at it?

I don't really have a good solution here. Export-dynamic is not a dependency but rather a property so exposing it as a dependency does not really make sense. Are there other flags or properties that .pc files would want to expose? IOW should we consider an approach for only this thing or for a general "mapping features into pc args" kind of thing?

**Comment by xclaesse** [comment]
I don't know for other projects, but in glib export-dynamic is the only value that comes from an autotools variable. Other flags are either already hard-coded, or come from dependencies.

You can see here the patch I proposed on glib to have export-dynamic:
https://bugzilla.gnome.org/show_bug.cgi?id=788773#c34

**Pull request merged**
