### PR TITLE
add cc.has_function_attribute('vector_size')

### PR DESCRIPTION
**Pull request by Dudemanguy**
Remembered that this was missing, so I thought I'd add it real quick.

### CODE REVIEW

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
Code looks good. Looks like the CI may need to be updated

**Comment by Dudemanguy** [comment]
>error: invalid vector element type 'int (void)'

Hmm clang seems to not like this. Should be fixable though.

**Comment by tristan957** [comment]
Potentially worth a release notes snippet and a test?

See `test cases/common/197 function attributes/meson.build`. I made a similar PR in https://github.com/mesonbuild/meson/pull/10408.

**Comment by Dudemanguy** [comment]
The tests should be good now. It's included in there. The main reason why I didn't add it a release notes snippet is because your PR didn't actually hah. I can include it if it's wanted.

**Comment by tristan957** [comment]
Oh, then I wouldn't worry about it unless someone with the merge power complains :).

**Comment by dcbaker** [comment]
I looked, we haven't added snippets for these in the past, just referenced them in the table.

**Pull request merged**
