### PR TITLE
Fix cross static linker lookup

### LINKED ISSUE #4822: Cross override for "ar" is ignored
This is a regression. Bisected, first bad commit is b53c982b58372901bfd9ffbbfe36831c85b465b4 (#4755). Pinging @Ericson2314 

Cross file:
```ini
[binaries]
c = '/home/akari/git/taisei-osx-build/osxcross/target/bin/x86_64-apple-darwin15-clang'
ar = '/home/akari/git/taisei-osx-build/osxcross/target/bin/x86_64-apple-darwin15-ar'
...........
```

Relevant build output:
```
[69/269] rm -f subprojects/cglm/libcglm.a && gcc-ar csrD subprojects/cglm/libcglm.a 'subprojects/cglm/9f68372@@cglm@sta/src_affine.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_box.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_cam.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_ease.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_euler.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_frustum.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_io.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_mat3.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_mat4.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_plane.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_project.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_quat.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_sphere.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_vec3.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_vec4.c.o'
................
ld: archive has no table of contents file 'subprojects/cglm/libcglm.a' for architecture x86_64
clang-7.0.1: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Build output prior to bad commit:
```
[70/269] rm -f subprojects/cglm/libcglm.a && /home/akari/git/taisei-osx-build/osxcross/target/bin/x86_64-apple-darwin15-ar csr subprojects/cglm/libcglm.a 'subprojects/cglm/9f68372@@cglm@sta/src_affine.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_box.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_cam.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_ease.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_euler.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_frustum.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_io.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_mat3.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_mat4.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_plane.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_project.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_quat.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_sphere.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_vec3.c.o' 'subprojects/cglm/9f68372@@cglm@sta/src_vec4.c.o'
```

### PR DESCRIPTION
**Pull request by Ericson2314**
Need to search based off of `cross_comp`, not `comp`.

Fixes #4822

### CODE REVIEW

**Comment by dcbaker** [comment]
How did we not catch this in our tests?

**Comment by Ericson2314** [comment]
@dcbaker `ar` is effectively target-agnostic in many cases, so something more than a smoke test is needed to reliably catch this.

**Comment by Akaricchi** [comment]
I believe enabling LTO will increase the probability of something like this being caught in the future.

**Comment by Ericson2314** [comment]
To be honest, I don't really have much time to figure out how to right such a test for a few days. Sorry.

**Comment by jpakkane** [comment]
Should this go in 0.49.2?

**Comment by dcbaker** [comment]
No, the offending commit landed after the 0.49 branchpoint, presumably this should block 0.50

**Comment by Ericson2314** [comment]
How far out is `0.50`? Hopefully a timescale which I could commit to writing the test :).

**Comment by jpakkane** [comment]
The official rule is "roughly one month after a stable point release". So assuming 0.49.2 comes out soon, three weeks after that is the freeze.

**Comment by Ericson2314** [comment]
BTW if this is merged, I think it will fix my https://github.com/mesonbuild/meson/pull/4772. The two together would constitute a test!

**Comment by dcbaker** [comment]
For now I went ahead and added the bug to the 0.50 milestone.

**Comment by Ericson2314** [comment]
Yeah then if we could merge this and keep open the issue, that would be ideal.

**Comment by Ericson2314** [comment]
#4772 now includes this; if that PR is fixed, then we do have a test!

**Comment by Akaricchi** [comment]
Can we merge this yet?

**Comment by dcbaker** [comment]
I think this is fine to merge as-is, even without a test. it sounds like we should get one soon anyway.

**Comment by Akaricchi** [comment]
Thank you!

**Comment by Ericson2314** [comment]
Thanks!

**Pull request merged**
