### PR TITLE
Fix ci images

### PR DESCRIPTION
**Pull request by bonzini**
I have no idea about the Arch failure:

```
2024-11-20T16:22:36.4765258Z [1/5] c++ -Isubprojects/cmMod/libcmModLib__.so.p -Isubprojects/cmMod '-I../test cases/cmake/1 basic/subprojects/cmMod' -Isubprojects/cmMod/__CMake_build '-I../test cases/cmake/1 basic/subprojects/cmMod/__CMake_build' -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu++14 -O0 -g -fPIC -g -DDO_NOTHING_JUST_A_FLAG=1 -DMESON_MAGIC_FLAG=21 -DcmModLib___EXPORTS -MD -MQ subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -MF subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o.d -o subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -c '../test cases/cmake/1 basic/subprojects/cmMod/cmMod.cpp'
2024-11-20T16:22:36.4771685Z [2/5] c++  -o subprojects/cmMod/libcmModLib__.so subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,libcmModLib__.so -Wl,--dependency-file,CMakeFiles/cmModLib++.dir/link.d
2024-11-20T16:22:36.4773648Z FAILED: subprojects/cmMod/libcmModLib__.so 
2024-11-20T16:22:36.4775912Z c++  -o subprojects/cmMod/libcmModLib__.so subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,libcmModLib__.so -Wl,--dependency-file,CMakeFiles/cmModLib++.dir/link.d
2024-11-20T16:22:36.4778166Z /usr/sbin/ld: cannot open dependency file CMakeFiles/cmModLib++.dir/link.d: no error
2024-11-20T16:22:36.4779121Z collect2: error: ld returned 1 exit status
2024-11-20T16:22:36.4783656Z [3/5] c++ -Imain.p -I. '-I../test cases/cmake/1 basic' -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -DMESON_MAGIC_FLAG=42 '-isystem../test cases/cmake/1 basic/subprojects/cmMod' -isystemsubprojects/cmMod '-isystem../test cases/cmake/1 basic/subprojects/cmMod/__CMake_build' -isystemsubprojects/cmMod/__CMake_build -MD -MQ main.p/main.cpp.o -MF main.p/main.cpp.o.d -o main.p/main.cpp.o -c '../test cases/cmake/1 basic/main.cpp'
2024-11-20T16:22:36.4787314Z ninja: build stopped: subcommand failed.
```

but the Fedora and Ubuntu ones should be easy.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> I have no idea about the Arch failure:

That is https://github.com/mesonbuild/meson/issues/13888

**Comment by eli-schwartz** [comment]
That is correct. We can therefore ignore those particular failures (which I think is 100% of the failures).

**Comment by bonzini** [comment]
Yes, the failing tests are `CI Image builder/arch` and `linux/Ubuntu Rolling/*`

**Comment by bonzini** [comment]
Ping.

**Comment by eli-schwartz** [comment]
Apologies for forgetting about this.

**Comment by eli-schwartz** [comment]
> > I have no idea about the Arch failure:
> 
> That is #13888

It appears to now be fixed on the cmake side: https://gitlab.kitware.com/cmake/cmake/-/issues/26498

**Pull request merged**
