### PR TITLE
install: Add --strip option

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Maybe we should deprecate this as a configure time option?

**Comment by dcbaker** [comment]
Can I be the annoying one? Can we keep the strip option, but just have it set the —strip flag for the ninja install target? That’s very close to 100% backwards compatible, and provides a way for people who don’t want to invoke Meson install directly to continue getting the strip behavior

**Comment by xclaesse** [comment]
I want to keep it 100% backwards compatible, just deprecated. But maybe I should revert this pr to initial version where I don't deprecated if we are in doubt?

**Comment by xclaesse** [comment]
Ok, misunderstood what you meant. We could add --strip to the ninja run target, instead of storing that info for each TargetInstallData, but if we do that we lose per-target strip value: `executable(..., override_options: 'strip=true')`. I'm not sure that's used in practice, but I'm a bit afraid of changing that, I could imagine that when you build a proprietary target you could want to force that target to be always stripped, for example.

**Comment by dcbaker** [comment]
Okay, I'd rather not deprecate `-Dstrip` then, since if we deprecate it then we also need to remove the `ninja install` target, since it can't be configured usefully (ie, you can never strip)

**Comment by eli-schwartz** [comment]
We need to what now?????

**Comment by dcbaker** [comment]
If we deprecate the -Dstrip option, then `ninja install` cannot strip installed binaries, at which point it's useless and we should remove it

**Comment by xclaesse** [comment]
> If we deprecate the -Dstrip option, then `ninja install` cannot strip installed binaries, at which point it's useless and we should remove it

Not remove it, but deprecate it too. I reverted this PR to not deprecate strip option, we can always do that later.

**Comment by dcbaker** [comment]
Deprecation is just a warning something is going to be removed in the future, right?

**Pull request merged**
