### PR TITLE
Only default to dpkg-architecture output in Debian derivatives

### PR DESCRIPTION
**Pull request by jok-ts**
Commit 28476aa7 replaced testing for debianness with trying to execute dpkg-architecture.
This is a problem when that program exists but the distribution is not a Debian derivative.

cf. https://bugs.gentoo.org/show_bug.cgi?id=591564

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@nirbheek that's actually one of the reasons why we explicitly set `--libdir`, `--datadir` and others in RPM macro.

**Comment by jpakkane** [comment]
Out of interest, why does Gentoo have `dpkg-architecture` installed? That seems a bit odd.

The bug report also mentions upcoming multilib support. Do we need to change anything Meson-side for you or will it work out of the box?

Other than that, please add yourself at the end of `authors.txt` and we'll merge this.

**Comment by jok-ts** [comment]
Done, thanks!

Gentoo has quite a few foreign build systems, but I think app-arch/dpkg was there from the beginning.
If nothing else it is used by app-arch/alien that converts between the rpm, dpkg, stampede slp, and slackware tgz file formats.

As for the multilib support, I'd expect that to be handled on the Gentoo side eventually.

**Comment by jok-ts** [comment]
PR #941 now conflicts, rebasing.

**Comment by jpakkane** [comment]
I already merged it manually. Thanks.

**Pull request closed without merging**
