### PR TITLE
Bring back the old manual search to find_library.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by rhd** [comment]
Thanks for this... but I still get the depreciation warning:

```
DEPRECATION: find_library() is removed, use the corresponding method in compiler object instead.
```

```
$ git log -n1
commit 46e1e18963dae959adf3aed2ab4da181b94062bf
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Sun Apr 3 17:57:00 2016 +0300

    Bring back the old manual search to find_library.
```

**Comment by jpakkane** [comment]
That is what should happen. The functionality is in `cc.find_library`.

**Comment by rhd** [comment]
Do you see what I'm screwing up?

```
$ rm -rf build-gcc
$ mkdir build-gcc
$ ~/src/meson/meson.py --version
0.31.0.dev1
$ cd ~/src/meson/
$ git log -n1
commit 46e1e18963dae959adf3aed2ab4da181b94062bf
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Sun Apr 3 17:57:00 2016 +0300

    Bring back the old manual search to find_library.
$ cd -
$ CXX=g++-4.8.1 CC=gcc-4.8.1 ~/src/meson/meson.py build-gcc
...
Native cpp compiler: g++-4.8.1 (gcc 4.8.1)
Native c compiler: gcc-4.8.1 (gcc 4.8.1)
DEPRECATION: find_library() is removed, use the corresponding method in compiler object instead.

Meson encountered an error in file meson.build, line 31, column 0:
Tried to assign an invalid value to variable.
```

line 31, column 0:
```
zlib = find_library('z')
```

**Comment by jpakkane** [comment]
cc = meson.get_compiler('c')
    zlib = cc.find_library('z')

**Comment by rhd** [comment]
I understand now. I thought you brought back the original `find_library`, but you moved the functionality into `cc.find_library`. Sorry. I'll test and get back to you.

**Comment by jpakkane** [comment]
Also, _never_ use `find_library` if you can avoid it. Get the zlib dependency with `zdep = dependency('zlib')`.

**Comment by rhd** [comment]
I'll go through my files and add convert to `dependency` where I can.

But, I'm having the other issues which I fixed [here](https://github.com/mesonbuild/meson/pull/493/files) in `mesonbuild/interpreter.py`

I can manually change it in my clone, but you should add add those changes to this PR.

**Comment by rhd** [comment]
Ok, here's the problem. If `dirs` is specified as part of `find_library`, it doesn't take precedence. The issue I'm having is that we have an older version of a lib installed in `/usr/lib64` but I'm trying to link against the one that lives in `/usr/local/lib`.

`find_library` attemps to just use `-l mylib` which succeeds and it ignores what I specified in the `dirs` argument.

I guess the obvious solution would be for me to go up-crapify the dev machines... but if I didn't have root, it would be a huge PITA.

Can you allow the `dirs` argument to take priority over the default method and not just get used if the default method fails?

**Comment by jpakkane** [comment]
If you do `-L/usr/local/lib -lmylib` does it find your version or the system version?

**Comment by rhd** [comment]
That's what meson is currently doing. Should gcc be acting differently?

```
FAILED: g++-4.8.1
...
 '-L/usr/local/fftw/64/lib' '-lfftw3f' '-L/usr/local/fftw/64/lib' '-lfftw3' '-L/usr/local/fftw/64/lib' '-lfftw3f_threads'
```

**Comment by jpakkane** [comment]
Now specified dirs should override builtin dirs.

**Comment by rhd** [comment]
works! :+1: 

(after I apply this diff)
```diff
diff --git a/mesonbuild/interpreter.py b/mesonbuild/interpreter.py
index ef6f3c1..b29c46d 100644
--- a/mesonbuild/interpreter.py
+++ b/mesonbuild/interpreter.py
@@ -762,12 +762,14 @@ class CompilerHolder(InterpreterObject):
         if not isinstance(required, bool):
             raise InterpreterException('required must be boolean.')
         search_dirs = kwargs.get('dirs', [])
+        if not isinstance(search_dirs, list):
+            search_dirs = [search_dirs]
         for i in search_dirs:
             if not os.path.isabs(i):
                 raise InvalidCode('Search directory %s is not an absolute path.' % i)
         linkargs = self.compiler.find_library(libname, search_dirs)
         if required and linkargs is None:
-            raise InterpreterException('Library %s not found'.format(libname))
+            raise InterpreterException('Library %s not found' % libname)
         lib = dependencies.ExternalLibrary(libname, linkargs)
         return ExternalLibraryHolder(lib)
```

**Pull request merged**
