### PR TITLE
coredata: Malformed machine file is not a Meson bug

### PR DESCRIPTION
**Pull request by xclaesse**
Fixes: #11899

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Can't check right now, what's the exact formatting of the new error message?

**Comment by xclaesse** [comment]
```
ERROR: Source contains parsing errors: '/home/xclaesse/programmation/meson-test/f1.ini'
	[line  5]: "'b']\n"
```

**Comment by xclaesse** [comment]
> Can we prefix that with something like "malformed cross file"? Or if we can get the `line XXX: "stringval"` part as a documented part of configparser.Error, even better.

It's not really documented, and I don't think we should poke at undocumented internals tbh. I added a prefix:
```
ERROR: Malformed cross or native file: Source contains parsing errors: '/home/xclaesse/programmation/meson-test/f1.ini'
	[line  5]: "'b']\n"
```

Not perfect, but it's pretty clear IMHO.

**Comment by eli-schwartz** [comment]
Looks good to me.

**Comment by eli-schwartz** [comment]
@lazka I don't understand this msys2-specific test failure:
```
================================== FAILURES ===================================
______________________________ run_unittests.py _______________________________
[gw1] win32 -- Python 3.10.12 D:\a\_temp\msys64\mingw32\bin\python3.exe
worker 'gw1' crashed while running 'run_unittests.py::AllPlatformTests::test_junit_valid_exitcode'
______________________________ run_unittests.py _______________________________
[gw2] win32 -- Python 3.10.12 D:\a\_temp\msys64\mingw32\bin\python3.exe
worker 'gw2' crashed while running 'run_unittests.py::AllPlatformTests::test_junit_valid_gtest'
______________________________ run_unittests.py _______________________________
[gw3] win32 -- Python 3.10.12 D:\a\_temp\msys64\mingw32\bin\python3.exe
worker 'gw3' crashed while running 'run_unittests.py::AllPlatformTests::test_junit_valid_tap'
```

**Comment by lazka** [comment]
hm, looks like it affects all PRs now?

Based on the crashing tests and the packages we updated yesterday it looks like a libxml2 regression.

**Comment by lazka** [comment]
This was https://github.com/lxml/lxml/pull/370. A fixed packages has been deployed, so a rerun should fix things now.

thanks for the ping

**Pull request merged**
