### PR TITLE
docs: Document pkg_config_path and cross_ options [skip ci]

### PR DESCRIPTION
**Pull request by dcbaker**
@TheQwertiest, @nirbheek

### CODE REVIEW

**Comment by nirbheek** [comment]
Why don't we combine this and https://github.com/mesonbuild/meson/pull/5233 in one PR? :)

**Comment by dcbaker** [comment]
I guess I figured this would be a quick "yeah, looks about right, press the merge button" sort of PR :)

**Comment by Ericson2314** [comment]
Woah `cross_*` is exposed, not just reserved now? We need to have that vs `build_*` and `host_*` conversation.

**Comment by nirbheek** [comment]
> We need to have that vs `build_*` and `host_*` conversation.

Yes, we can block the 0.51 release on that, but this should unblock Mesa from removing Autotools for now. The interface can be changed before release, but they'll know that this feature will exist in some form.

**Comment by Ericson2314** [comment]
@nirbheek Perfect!

**Pull request merged**
