### PR TITLE
added len() and is_empty() for interpreter String type

### PR DESCRIPTION
**Pull request by chutchinson**
I added the following functions to the interpreter String type:

**length()**
Returns the length of the string.

**is_empty()**
Determines if the string is empty by checking if it has zero length or is composed entirely of whitespace.

I've also included tests by amending **test cases/common/42 string operations**

### CODE REVIEW

**Comment by TingPing** [comment]
`array.length()` is already a function so `string.length()` is more consistent.

**Comment by jpakkane** [comment]
What do you need these for or is this just a nice-to-have?

**Comment by chutchinson** [comment]
I specifically needed a way to check if the output from an executable during build generation was empty (composed entirely of whitespace, or of zero length). The executable parses a structured file and returns a value from a section of the file - the value is used as a flag for setting configuration data conditionally for **configure_file**.

Checking for emptiness was important to my use case; perhaps string length is not as useful because you can compare against an empty string literal.

**Comment by jpakkane** [comment]
if stdout.strip() == ''

**Comment by chutchinson** [comment]
Well that's embarrassing. I didn't notice **String#strip()** looking through the documentation. Feel free to close this pull request.

**Pull request closed without merging**
