### PR TITLE
cc.has_function: Also detect implementations and redefinitions by a provided header

### PR DESCRIPTION
**Pull request by nirbheek**
Fixes https://github.com/mesonbuild/meson/issues/530.

### CODE REVIEW

**Comment by nioncode** [comment]
Works with my vs2010 and vs2015 setup. For vs2015 both, x86 and x64, work just fine.

**Comment by jpakkane** [comment]
> assert(cc.has_function('fprintf'), '"fprintf" function not found without include (should always exist).')

This is not actually true. Compiling with sufficient warnings warns about implicit warnings on C and is a compile failure on C++.

**Comment by nirbheek** [comment]
> This is not actually true. Compiling with sufficient warnings warns about implicit warnings on C and is a compile failure on C++.

Most compiler checks rely on code that generates warnings, so that's all right. This is true in autoconf, is true in a lot of checks we do in Meson, and is true in a lot of checks done as part of `configure` in cross-platform projects like glib and libffi. You just call the compiler without any extra options so the warnings are not fatal.

`cc.has_function` is supposed to work without the header being prefixed since it checks if the symbol is implemented by the standard library by linking to it. This patch adds a fallback where it uses the supplied `prefix` header(s) to detect whether symbol is made available by the standard library (directly by an inline implementation or indirectly with a differently-named symbol in the library).

All these assumptions break down with C++, so there you need to specify the header.

**Comment by jpakkane** [comment]
As an interesting coincidence, I just got this from zlib on OSX:

    warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]

This check works now and things are fine but depending on invalid code to not error out seems a bit iffy to me.

**Comment by nirbheek** [comment]
I agree, but I don't see any way around it. To be fair, all these compiler checks are terrible hacks too. Ideally each compiler would expose some sort of API to query these values but we live in a terrible world.

On the bright side, half the world would break if they ever changed this, so it's not going to change in the foreseeable future. ;)

**Pull request merged**
