### PR TITLE
Fix appveyor failures: do not use PowerShell since it triggers NativeCommandError if pacman prints to stderr

### PR DESCRIPTION
**Pull request by sarum9in**
Also use --needed for pacman to not reinstall already installed packages.

### CODE REVIEW

**Comment by sarum9in** [comment]
```text
ninja explain: deps for 'ext/tachyon@sha/tachyon_module.c.obj' are missing
ninja explain: ext/tachyon@sha/tachyon_module.c.obj is dirty
ninja explain: ext/tachyon.pyd is dirty
 
The Meson build system
Version: 0.46.0.dev1
Source dir: C:\projects\meson\test cases\python3\4 custom target depends extmodule
Build dir: C:\projects\meson\b 4345b2f618
Build type: native build
Project name: Python extension module
Native C compiler: cc (gcc 7.3.0 "cc (Rev1, Built by MSYS2 project) 7.3.0")
Build machine cpu family: x86
Build machine cpu: x86
Native dependency python3 found: YES 3.6
Configuring blaster.py using configuration
Build targets in project: 3
Found ninja-1.8.2.git at '.\ninja.EXE'
[0/1] "C:\python35\python.exe" "C:\projects\meson\meson.py" --internal regenerate "C:\projects\meson\test cases\python3\4 custom target depends extmodule" "C:\projects\meson\b 4345b2f618" --backend ninja
The Meson build system
Version: 0.46.0.dev1
Source dir: C:\projects\meson\test cases\python3\4 custom target depends extmodule
Build dir: C:\projects\meson\b 4345b2f618
Build type: native build
Project name: Python extension module
Native C compiler: cc (gcc 7.3.0 "cc (Rev1, Built by MSYS2 project) 7.3.0")
Build machine cpu family: x86
Build machine cpu: x86
Dependency python3 found: YES (cached)
Configuring blaster.py using configuration
Build targets in project: 3
Found ninja-1.8.2.git at 'C:\projects\meson\ninja.EXE'
[1/6] cc @ext/lib/tachyonlib@sha/meson-tachyonlib.c.obj.rsp
[2/6] cc @ext/lib/libtachyonlib.dll.rsp
[3/6] cc @ext/tachyon@sha/tachyon_module.c.obj.rsp
[4/6] "C:\python35\python.exe" "C:\projects\meson\meson.py" --internal symbolextractor ext/lib/libtachyonlib.dll ext/lib/tachyonlib@sha/ext/lib/libtachyonlib.dll.symbols 
[5/6] cc @ext/tachyon.pyd.rsp
[6/6] "C:/python35/python.exe" "C:/projects/meson/meson.py" "--internal" "exe" "C:/projects/meson/b 4345b2f618/meson-private/meson_exe_python.exe_cd4f05e6e9862b01dacbf041f61e713ff6e674f2.dat"
FAILED: out.txt 
"C:/python35/python.exe" "C:/projects/meson/meson.py" "--internal" "exe" "C:/projects/meson/b 4345b2f618/meson-private/meson_exe_python.exe_cd4f05e6e9862b01dacbf041f61e713ff6e674f2.dat"
Fatal Python error: PyThreadState_Get: no current thread
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ninja: build stopped: subcommand failed.
 
ninja explain: output build.ninja older than most recent input ../test cases/python3/4 custom target depends extmodule/meson.build (5428348057304666 vs 5428348057460926)
ninja explain: deps for 'ext/lib/tachyonlib@sha/meson-tachyonlib.c.obj' are missing
ninja explain: ext/lib/tachyonlib@sha/meson-tachyonlib.c.obj is dirty
ninja explain: ext/lib/libtachyonlib.dll is dirty
ninja explain: deps for 'ext/tachyon@sha/tachyon_module.c.obj' are missing
ninja explain: ext/tachyon@sha/tachyon_module.c.obj is dirty
ninja explain: ext/lib/libtachyonlib.dll is dirty
ninja explain: ext/lib/tachyonlib@sha/ext/lib/libtachyonlib.dll.symbols is dirty
ninja explain: ext/tachyon.pyd is dirty
ninja explain: ext/tachyon.pyd is dirty
ninja explain: out.txt is dirty
 
System information.
Architecture: ('32bit', 'WindowsPE')
Machine: AMD64
Platform: Windows
Processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
System: Windows
Running unittests.
```

**Comment by jpakkane** [comment]
It fails:

    Fatal Python error: PyThreadState_Get: no current thread

That's not something you see every day ...

**Comment by sarum9in** [comment]
Yea, unfortunately I just unbugged CI to run this test, so it is not clear what's wrong. I suspect some python versions got mixed up, e.g. module built for msys version is loaded into system one.

**Comment by jpakkane** [comment]
And now we remember why it was done with PowerShell in the first place:

    if %compiler%==msys2-mingw ( [yadda yadda yadda]
    The input line is too long.
    Command exited with code 255

**Comment by jon-turney** [comment]
Good grief.  How annoying.

The best I can come up with to fix this is https://github.com/jon-turney/meson/commit/aad4364acc30b7f51f4f7fda60128fc0a72b4b42

**Comment by sarum9in** [comment]
Maybe I missed something, where do you see `The input line is too long.`?

**Comment by jon-turney** [comment]
> Maybe I missed something, where do you see The input line is too long.?

The VS2017 build breaks with that error, see https://ci.appveyor.com/project/jpakkane/meson/build/5291/job/oomn3xpelf097gho#L27

**Comment by sarum9in** [comment]
Oh you are right, sorry.

**Pull request closed without merging**
