### PR TITLE
Random fixes

### PR DESCRIPTION
**Pull request by dcbaker**

### CODE REVIEW

**Comment by jpakkane** [comment]
Seems relevant:

```
ERROR: test_cross_file_system_paths (__main__.AllPlatformTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 2658, in test_cross_file_system_paths
    os.environ.pop('XDG_DATA_HOME')
  File "/usr/lib/python3.6/_collections_abc.py", line 795, in pop
    value = self[key]
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_DATA_HOME'
```

**Comment by dcbaker** [comment]
indeed it does

**Comment by jpakkane** [comment]
What is the fate of this MR?

**Comment by dcbaker** [comment]
the first patch is no longer relevant, I've rebased the second which should still be relevant.

**Comment by dcbaker** [comment]
it helps if you actually commit your changes :eyes:

**Pull request merged**
