### PR TITLE
Add found method to build target

### PR DESCRIPTION
**Pull request by jameshilliard**
This is useful if one needs to check if a build target is a disabler. I also fixed a bug where build targets wouldn't get disabled when a disabler was passed to the target's sources(this seems to be needed mostly when using generated sources).

### CODE REVIEW

**Comment by jpakkane** [comment]
Maybe we should also add an explicit function of method `is_disabler` to check for disablers.

**Comment by jameshilliard** [comment]
Yeah, that could also be useful.

**Comment by jameshilliard** [comment]
> Maybe we should also add an explicit function of method `is_disabler` to check for disablers.

I've gone ahead and added this just now along with tests.

**Comment by jameshilliard** [comment]
rebased

**Comment by jpakkane** [comment]
If we add the `is_disabler` function, is the rest of the functionality still needed?

Regardless, if you extract the `is_disabler` part into its own PR, it can be merged quite quickly as it is a clearly useful standalone function that does not have backwards compatibility questions.

**Comment by jameshilliard** [comment]
> If we add the `is_disabler` function, is the rest of the functionality still needed?

I think it's a good idea just for the nicer syntax.

> does not have backwards compatibility questions

I'm fairly sure the other changes shouldn't break backwards compatibility since they only effect cases which are fatal build errors.

**Comment by jameshilliard** [comment]
I've extracted the `is_disabler` part in #5725.

**Comment by jameshilliard** [comment]
I've rebased this so that it's just adding a `found()` method to build and custom targets along with some more tests.

**Comment by jameshilliard** [comment]
@jpakkane think this is good to merge?

**Comment by jameshilliard** [comment]
rebased

**Comment by eli-schwartz** [comment]
> I think it's a good idea just for the nicer syntax.

I think @jpakkane is right.

```meson
is_disabler(foo)

foo.found()
```

I don't really see how the latter is "nicer", and the is_disabler function that you added elsewhere seems to be serving people's needs. This PR is also quite old and doesn't apply, because no project members really seemed to feel this was needed in addition, so it never got merged.

Instead of leaving this open forever to gather more dust and false hopes, I am going to close it in favor of #5725.

**Pull request closed without merging**
