### PR TITLE
A bunch of bugfixes for Vala

### LINKED ISSUE #1084: Auto header dependencies don't work with generated enums
Given this meson.build file:

```
project('meson-enums-dependencies', 'c')

gnome = import('gnome')

enums = gnome.mkenums('enum-types',
    sources: 'enums.h',
    c_template: 'enum-types.c.template',
    h_template: 'enum-types.h.template'
)

lib1 = library('lib1', enums[0], enums[1])

executable('final', 'main.c', link_with: lib1)
```

When I build this with a clean build directory, I get the following error:

```
[0/1] Regenerating build files
The Meson build system
Version: 0.37.0.dev1
Source dir: /home/sam/meson-enums-fuckup
Build dir: /home/sam/meson-enums-fuckup/build
Build type: native build
Project name: meson-enums-dependencies
Native c compiler: ccache cc (gcc 6.2.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 4
[1/7] Compiling c object 'final@exe/main.c.o'
FAILED: final@exe/main.c.o 
ccache cc  '-Ifinal@exe' '-fdiagnostics-color=always' '-I.' '-I..' '-pipe' '-Wall' '-Winvalid-pch' '-O0' '-g' '-MMD' '-MQ' 'final@exe/main.c.o' '-MF' 'final@exe/main.c.o.d' -o 'final@exe/main.c.o' -c ../main.c
../main.c:1:24: fatal error: enum-types.h: No such file or directory
 #include "enum-types.h"
                        ^
compilation terminated.
[2/7] 'Generating enum-types.h with a meson_exe.py custom command.'
```

I can work around this issue by listing enums[1] as a source to the executable. But that's no good; imagine if I have 50 testcases for lib1 -- I shouldn't have to list the enum header file as a source for each of those testcases.

### PR DESCRIPTION
**Pull request by nirbheek**
1) Fixes #1084
2) Fixes `--target-glib=` `valac` arg when only one version requirement is passed to dependency('glib-2.0')
3) Pass `--gresources` to `valac` when a `gnome.compile_resources()` source target is in the Vala target's sources
4) Add tests for all these + for hand-written Vapi files

### CODE REVIEW

**Comment by nirbheek** [comment]
PS: I've cherry-picked the test case that @ssssam wrote for #1084 into this.

**Comment by nirbheek** [comment]
@jpakkane One of the tests needs gtk+-3 development files on Linux. Could you please update the docker image?

**Comment by jpakkane** [comment]
Updated.

**Comment by jpakkane** [comment]
The hidden assumption here is that `find_program` is only ever used for system executables that are in path and that lookup state never changes (because of, say, `.` being in path and the function is called with different working directories). This is a valid and reasonable requirement but can we guarantee it? (probably yes)

It is also a bit wonky that this function is only called once and the second argument is always the empty string. There's not much point in having it at all in this case.

**Comment by nirbheek** [comment]
This specific `find_program` is already called several times in the `gnome` module for finding `glib-mkenums` and such. It is always used for finding build tools provided by the system, and is intended as such. That one place where I added it in this PR was not using it because of an oversight.

This was added because `subprocess.Popen(['glib-mkenums', ...` fails on Windows because you need to do a manual search in `PATH`, which is what `dependencies.ExternalProgram` already does:

```
commit e933bdd87229f13766705274a8815e9f10d4fe8d
Author: Thibault Saunier <tsaunier@gnome.org>
Date:   Wed Nov 30 10:07:16 2016 -0300

    gnome: Properly search for programs
    
    Otherwise it might just fail on windows and this way
    we report a proper error message when not found.
```

**Comment by nirbheek** [comment]
That one place where the second argument to `find_program` is `''` is because the value is never used anyway because we always ignore the `MesonException` that could be raised by it.

**Pull request merged**
