### PR TITLE
Draft support for local patch files (#642)

### PR DESCRIPTION
**Pull request by 5paceToast**
TODO:
- [x] Add documentation
- [x] Add unit tests

Side effects:
- the patch filename must end with `.zip` (as is currently), or meson will fail to extract it. I'm not sure if other compression formats work.

Usage:
1. `patch_url = local`
2. Ensure a file named `$patch_filename` is present in the same directory as your `.wrap` file, and is formatted appropriately (unzip an example patch file for an example), which also means being a supported compression format (only zip has been tested so far).

Implementation notes:
- `local` is purposefully an invalid url - that makes this feature more or less backwards-compatible, in that older clients will get a fairly unambiguous warning that `local` is not a valid url.
- you should be able (theoretically) to just commit the patch into the cache directory, but I'm not aware of the location being guaranteed to be stable and will make VCS handling more difficult.
- ultimately, the purpose of the patch is to allow, as per @rib "relative paths to a .patch file".

I see this as a more edge case - useful for projects moving over to meson, that don't have (or want to expend resources) to contribute new wraps - as such, the feature is extremely minimalistic. It might take me some time to add tests/docs, so feedback/edits are welcome.

### CODE REVIEW

**Comment by jpakkane** [comment]
The basic idea is good. However some issues come to mind:

- it would be nice to make this behave the same for actual sources as well as patches
- putting the files at the root of the subprojects dir seems a bit cluttery
- etc

How about making the system work in a way where you can specify the file name and then Meson would look it up in the buildcache dir? So something like:

```
[wrap-file]
directory = ...

source_url = precached
source_filename = upstream_release-1.0.tar.gz
source_hash = ...

patch_url = precache
patch_filename = patch_to_upstream-1.0.zip
patch_hash = ...
```

So if the url is the string `precached` then Meson will assume that the file is in the `packagecache` directory?

**Comment by 5paceToast** [comment]
I agree with making this work for sources (though, admittedly, it's less required, since those tend to be available).

I don't think it's too cluttery to put them into the root of the subprojects dir though - the wrap file is there already anyways.

Regarding `precached`, technically, you already can just drop files into packagecache and have it "work" from what I recall, but most projects using meson should have `packagecache` in `.gitignore`, and creating a new directory just to host these files seems overkill to me, and just as cluttery if you only have one such project (which, since this is likely an edge case, is going to be the case quite often).

Though it'd also be nice if you could *not* have the files be zipped (since you're tracking them with git at that point).

However getting everything into this PR would be a much larger undertaking (instead of a 2-line fix, it'd require, refactoring a good chunk of `wrap.py`, to change things like detection of zip format).

I see this as a somewhat less common feature, but one that's very important, so I'd prefer to merge in the "base" functionality, and improve on it later if there's demand for it. (hell, if I get annoyed with the limitations I might do it myself at some point - that's how this PR came to be)

**Comment by rib** [comment]
Just to mention that I updated https://github.com/mesonbuild/meson/issues/642 with a comment about how I worked around this issue.

Essentially just confirming that you can already specify an invalid URL instead of "`precached`" and the cache is checked before fetching from the url. We currently rely on this behaviour. (When I say 'invalid' though, I'm not sure off the top of my head if the url maybe has to be a syntactically valid http[s], because in our case we specify a fake/unreachable https url)

Here are two projects currently using this scheme:
https://github.com/glimpse-project/glimpse
https://github.com/rib/gputop/tree/master/subprojects

(Also note they use uncompressed tarballs, so can confirm that other archive formats besides zip do work)

I tend to agree that's not an ideal approach though, e.g. for the .gitignore we're listing files individually so we don't loose track of our patch archives.

It generally feels a bit icky to be making assumptions about the way meson downloads and caches the files in this precached directory. (quoting @5paceToast "I'm not aware of the location being guaranteed to be stable"))

Personally I also think it's a bit annoying to have to create an archive of files in this case instead of specifying a subdirectory that becomes an overlay. We at least avoid compressing the tarballs we have in our repo so they don't bloat the repo, but would prefer to avoid the extra step of archiving and calculating the sha256 each time we want to tweak one of these meson.build files.

**Comment by 5paceToast** [comment]
Regarding applying the same concept to source files, I finally realized why this seemed strange - ultimately, you're either better off using a submodule at that point, or just keeping them in your source tree - that's what you're doing, after all, with said patch (if applied to sources).

The issue with using a directory as an overlay (as much as that's tempting) is that this invalidated the usage of sha256 - how would you calculate it in a stable manner across all platforms? Furthermore, I suspect that'd require a massive redesign of the wrap subsystem.

**Comment by rib** [comment]
Without looking at the implementation details to see why it might be a pain to handle, I wouldn't really expect any sha256 sum to be checked for something I'm maintaining directly in-tree because I implicitly trust it's integrity.

Even for the case of using archives to fit with the current design it'd be slightly more convenient to be able skip updating the sha256 any time an in-tree wrapper needs updating. (Though esp. if implemented in terms of fitting into the cache lookup for downloaded archives I guess that would be awkward to special case)

**Comment by textshell** [comment]
I did some similar experimentation but never got around to finish it. My idea was to just enable relative (file) urls by passing the path to the wrap file as a baseurl to urljoin. That would allow fairly flexible layout of the patches. (i.e. subproject root, a patches subdirectory, etc)
See https://github.com/textshell/meson/commit/5b4984e26c9cccf915cf4bc5988637f677aac305

**Comment by rhd** [comment]
I would love to see support for this - especially for supporting binary releases. I'd really like to have `wrap` download tarballs and I could have a simple `meson.build` that tells meson where the `lib`, `include`, etc folders are.

**Comment by textshell** [comment]
As #4327 was merged which is very similar is here anything left to do? Or can we close this as superseded by #4327

**Comment by 5paceToast** [comment]
One additional thing I'd like to see is the ability to specify a .patch patchfile (so you can commit something that's actually text, instead of a binary blob, as simple/small as it may be).
However, this didn't have that (matter for another bug/PR), and based on my understanding of #4327 this is superseeded, so I'm closing this.

**Pull request closed without merging**
