### PR TITLE
install: Don't run ldconfig on cross builds

### LINKED ISSUE #9707: ldconfig during install causes exception during cross build
**Describe the bug**
Since https://github.com/mesonbuild/meson/commit/2c3a68bc30cf6e08c2e3b77b64718ef3a0e5d78c Meson attempts to update the ld.so cache during `meson install`. In https://github.com/mesonbuild/meson/commit/6b7d43ebe0d77ac85fa2c01e0e358efc64418126 errors from ldconfig are ignored but if the ldconfig binary is not compatible with the host during a cross build then Popen throws an exception that is not caught:

`OSError: [Errno 8] Exec format error: 'ldconfig'`

The issue *can* be avoided by configuring binfmt on the host system but that wasn't necessary prior to this change (https://github.com/mesonbuild/meson/commit/2c3a68bc30cf6e08c2e3b77b64718ef3a0e5d78c).

The issue is also being tracked in the NixOS project: https://github.com/NixOS/nixpkgs/pull/144779

I'm not a meson expert or even a NixOS expert so creating a simple test project was a bit rough. Let me know if you need more information. Let me know if you need more information:

**To Reproduce**

On a Linux machine during an cross build.
Also the machine's binmft is either not configured for the target system architecture or is disabled via:
`echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status`.

Then the error will occur during the install action:
`meson install --no-rebuild`

src: nixos.c
```
#include <stdio.h>

int main(int argc, char **argv) {
    printf("Hello World");
}
```

meson.build
```
project('nixos', 'c')

cc = meson.get_compiler('c')
dirs = []
executable('nixos', 'nixos.c')
```

cross-file:
```
[properties]
needs_exe_wrapper = true

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[binaries]
llvm-config = 'llvm-config-native'
```
Meson/NixOS Log:

```
meson flags: --buildtype=plain         --libdir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/lib --libexecdir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/libexec         --bindir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/bin --sbindir=/nix/store/nqmnb64pxxzqyac4xdnsdl55  caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/sbin         --includedir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/include         --mandir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/man --infodir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/info         --l  ocaledir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01 --cross-file=/nix/store/0d6bflf42rgrrxhp10visp67scqncd4g-cross-file.conf
  The Meson build system
  Version: 0.60.2
  Source dir: /build/crossmeson
  Build dir: /build/crossmeson/build
  Build type: cross build
  Project name: nixos
  Project version: undefined
  C compiler for the host machine: aarch64-unknown-linux-gnu-gcc (gcc 9.4.0 "aarch64-unknown-linux-gnu-gcc (GCC) 9.4.0")
  C linker for the host machine: aarch64-unknown-linux-gnu-gcc ld.bfd 2.35.2
  Compiler for language c for the build machine not found.
  Build machine cpu family: x86_64
  Build machine cpu: x86_64
  Host machine cpu family: aarch64
  Host machine cpu: aarch64
  Target machine cpu family: aarch64
  Target machine cpu: aarch64
  Build targets in project: 1

  nixos undefined

    User defined options
      Cross files  : /nix/store/0d6bflf42rgrrxhp10visp67scqncd4g-cross-file.conf
      auto_features: enabled
      bindir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/bin
      buildtype    : plain
      includedir   : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/include
      infodir      : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/info
      libdir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/lib
      libexecdir   : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/libexec
      localedir    : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/locale
      mandir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/man
      prefix       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01
      sbindir      : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/sbin
      wrap_mode    : nodownload

  Found ninja-1.10.2 at /nix/store/dw1apaarjckv3myghjmw7q2y1ivpv3xi-ninja-1.10.2/bin/ninja
  meson: enabled parallel building
  @nix { "action": "setPhase", "phase": "buildPhase" }
  building
  build flags: -j16 -l16
  ^M[0/2] Compiling C object nixos.p/nixos.c.o^M[1/2] Compiling C object nixos.p/nixos.c.o^M[1/2] Linking target nixos^M[2/2] Linking target nixos
  @nix { "action": "setPhase", "phase": "installPhase" }
  installing
  install flags: install
  ^M[0/1] Installing files.
  Traceback (most recent call last):
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 138, in run
      return options.run_func(options)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 771, in run
      installer.do_install(datafilename)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 554, in do_install
      self.apply_ldconfig(dm, destdir)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 377, in apply_ldconfig
      apply_ldconfig(dm)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 259, in apply_ldconfig
      proc, out, err = Popen_safe(['ldconfig', '-v'])
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/mesonlib/universal.py", line 1393, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/nix/store/jqcpjgqzcci7284r7bp3xjy47w1qpj8y-python3-3.9.9/lib/python3.9/subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/jqcpjgqzcci7284r7bp3xjy47w1qpj8y-python3-3.9.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 8] Exec format error: 'ldconfig'
```

**Expected behavior**
The project should install without error. Meson should probably skip running ldconfig on cross builds.

**System Parameters**
* Cross build: building aarch64 on x86_64
* OS: NixOS 21.11
* Python 3.9.6
* Meson 0.60.2
* Ninja 1.10.2

### PR DESCRIPTION
**Pull request by dcbaker**
Even if we install without a DESTDIR set, we should never update
ldconfig when cross compiling.

Fixes #9707

### CODE REVIEW

**Review by eli-schwartz — APPROVED** [review]
The larger question still remains... since this has caused so many bugs already, maybe it's more trouble than it is worth, and people should be educated to run it when it is correct for them to do so.

But assuming we do keep on running ldconfig, this PR looks correct.

**Comment by dcbaker** [comment]
I guess at the least this is suitable for 0.60.3, but I'd prefer to remove it or make it opt in with a flag for 0.61

**Comment by jpakkane** [comment]
Test failure is unrelated.

**Comment by nirbheek** [comment]
> I guess at the least this is suitable for 0.60.3

It changes the on-disk format for `meson-private/install.dat`, which is not something we should change in a minor release.

**Comment by nirbheek** [comment]
Maybe we can ignore errors encountered while running ldconfig in minstall for 0.60.3?

**Comment by nirbheek** [comment]
Ah, nvm, the errors are non-fatal anyway. I will just remove this from the milestone without a replacement fix.

**Pull request merged**
