### PR TITLE
Fix d compiler abstractions

### PR DESCRIPTION
**Pull request by dcbaker**
This should fix the D compilers in a number of cases. It removes the code to treat D like it's own linker (in reality LDC and DMD do something much more annoying, they invoke gcc/clang behind our backs). I've also fixed a few other MacOS related bugs.

I've tested gdc, ldc, and dmd on Linux, and dmd and ldc on macos and windows, and there's no regressions in the test coverage from master. I've fixed all of the tests on macOS, and added ldc to the macOS image in travis so we can get some test coverage there. I've also added a couple of tests to help regressions.

Fixes: #6075
Fixes: #6359

### CODE REVIEW

**Comment by dcbaker** [comment]
@michaelbadcrumble, @GoaLitiuM, Could one or both of you test this for me and see if it works in real use cases, not just our rather limited test case coverage (assuming the CI all comes back green)?

**Comment by michaelbadcrumble** [comment]
Tested the fix on a dummy hello world program and does not fail to compiler the project.  So far it is doing good.  However object files like `tmpq7u7cra2.o` and `tmpng4k3r4y.o` are still being generated in the project root directory.

**Comment by jpakkane** [comment]
That probably needs a fix similar [to this one here](https://github.com/mesonbuild/meson/commit/63bea704dded2cd6712e1386c5beb69be688c9f7).

**Comment by jpakkane** [comment]
```
FAILED: test-urld.exe 
link @test-urld.exe.rsp
Microsoft (R) Incremental Linker Version 14.16.27034.0
Copyright (C) Microsoft Corporation.  All rights reserved.

-of=test-urld.exe test-urld@exe/test.d.obj "/nologo" "-m64" "/DEBUG" "/PDB:test-urld.pdb" "-L=phobos64.lib" "-L=C:\\Users\\VssAdministrator\\AppData\\Local\\dub\\packages\\urld-2.1.1\\urld\\.dub\\build\\library-debug-windows-x86_64-dmd_2089-F2DBBF418391CF118A711870EACD2E3A\\urld.lib" 
LINK : warning LNK4044: unrecognized option '/of=test-urld.exe'; ignored
LINK : warning LNK4044: unrecognized option '/m64'; ignored
LINK : warning LNK4044: unrecognized option '/L=phobos64.lib'; ignored
LINK : warning LNK4044: unrecognized option '/L=C:\\Users\\VssAdministrator\\AppData\\Local\\dub\\packages\\urld-2.1.1\\urld\\.dub\\build\\library-debug-windows-x86_64-dmd_2089-F2DBBF418391CF118A711870EACD2E3A\\urld.lib'; ignored
LINK : fatal error LNK1104: cannot open file 'phobos64.lib'
```

**Comment by dcbaker** [comment]
Looks like we need to set up link.exe to be invoked by ldc/dmd instead of invoke directly. I don't have my windows machine today, so I'll look at it it tomorrow and update the MR then.

**Comment by michaelbadcrumble** [comment]
Any new development regarding the d compiler abstractions @dcbaker?

**Comment by dcbaker** [comment]
I've rebased this and fixed a large number of issues. There are still some I haven't fixed on windows. I've run out of time for this week though, so I'll come back and look at it more next week. Unless someone wants to point out the obvious reason it isn't working :)

**Comment by dcbaker** [comment]
I don't have my macbook today, so I'm just kinda shooting blind at fixing the problems on macos.

**Comment by dcbaker** [comment]
I now have my macbook and I think I finally have it all working (assuming I didn't break Linux or windows)

**Comment by dcbaker** [comment]
Finally, I think this is good to go! This should have ldc and dmd working on windows, Linux, and mac, plus gdc working on linux.

**Comment by jpakkane** [comment]
Great work. This looks like it was all different kinds of terrible.

**Comment by dcbaker** [comment]
It wasn't too bad, apart from dmd. That is an infuriating compiler to deal with. And the fact that I'd buggered it up pretty bad and we weren't testing on macos so it had all kinds of broken. We should probably add a test for dmd on macos and gdc on linux. Not sure if travis is the right place for that or if we should use github actions?

**Pull request merged**
