### PR TITLE
Fail if singleline string has multiple lines

### PR DESCRIPTION
**Pull request by cmarcelo**

### CODE REVIEW

**Comment by cmarcelo** [comment]
If it is desired to keep these strings working, let me know. Because then we should fix the `lineno` accounting to work like multiline_strings. At the moment one of those single quote multi line strings cause errors after it to report a wrong line number.

**Comment by nirbheek** [comment]
@jon-turney cygwin CI is giving strange errors 

> mesonbuild.mesonlib.EnvironmentException: Unable to detect GNU compiler type:
> C:/cygwin64/lib/gcc/x86_64-pc-cygwin/6.4.0/cc1.exe: error while loading shared libraries: cygmpfr-4.dll: cannot open shared object file: No such file or directory

**Comment by jon-turney** [comment]
> cygwin CI is giving strange errors

This was due to a broken package in the cygwin package repo. It's been removed.

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
