### PR TITLE
Condense some tests

### PR DESCRIPTION
**Pull request by jpakkane**
Fewer test directories => faster test run time.

### CODE REVIEW

**Comment by nirbheek** [comment]
Looking at the numbers, this change somehow made the tests *slower*, I am confused.

**Comment by nirbheek** [comment]
Actually, maybe the test times are slower because `ccache` couldn't be used, because the dirs changed.

**Comment by nirbheek** [comment]
Conflicts.

**Comment by jpakkane** [comment]
Now seems to last roughly as long.

**Pull request merged**
