### PR TITLE
rewriter: don't output target info to stderr

### PR DESCRIPTION
**Pull request by benoit-pierre**
Send the info to stdout, where it belongs.

### CODE REVIEW

**Comment by tristan957** [comment]
Make sure to fix the test failures too

**Comment by tristan957** [comment]
Any reason you closed this?

**Comment by benoit-pierre** [comment]
It's been more than a year, what's the point?

**Comment by dcbaker** [comment]
@benoit-pierre. Yeah, we really struggle with stuff falling through the cracks. This looks fine to me, actually.

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
Unfortunately (and even the core maintainers have to do this too), we just sometimes have to ping the MR or matrix and ask for review of things. I'll merge this as long as CI is green when it's done.

**Comment by dcbaker** [comment]
@benoit-pierre A rebase may be needed to get the linters happy

**Comment by benoit-pierre** [comment]
Master is failing the lint job too, I guess due to the newly released 3.3.0 version of pylint.

**Comment by benoit-pierre** [comment]
Fix for pylint: #13695.

**Comment by dcbaker** [comment]
that's merged, thanks for doing that.

**Pull request merged**
