### PR TITLE
Use LDFLAGS only on languages that need it. Closes #5215.

### LINKED ISSUE #5215: LDFLAGS get passed to valac during sanity check
See: https://github.com/mesonbuild/meson/issues/5086#issuecomment-478881890 and later comments.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by jpakkane** [comment]
That has Cuda. Dunno how it behaves w.r.t. this. What about `clike_langs`? Though that's then two different semantics on the same list (even though their contents are the same currently).

**Comment by nirbheek** [comment]
I think D and CUDA should indeed use `LDFLAGS` because they are linked by the usual linker (GNU ld, f.ex.) afair.

**Comment by jpakkane** [comment]
Updated to be explicit.

**Comment by Ericson2314** [comment]
I was a bit confused on this because I'm not sure `vala_link_args` is used *at all*. For some reason it's left for the backend to use link args. Things are also confusing because it's the polyglot case where I don't think each input language's link args are being used.

**Pull request merged**
