### PR TITLE
Fix linking when cross-compiling and a windows resource is first object

### LINKED ISSUE #4463: Unable to link a static library with MSVC for ARM, when windows resources are included
When creating a library that contains a windows resource (to add metadata about the library), e.g. like this, building with MSVC can fail when targeting non-x86 architectures.
```
mylib_rc_obj = winmod.compile_resources(rc_file)
mylib = library('mylib', mylib_rc_obj, ...)
```
With MSVC tools, the output of `rc.exe` is an arch independent resource file (contrary to windres which by default outputs an arch specific object file). When including this in a static library, MSVC `lib.exe` will convert it into an arch specific object file. (Including it in static libraries is of course pointless, but since one doesn't know if the library is going to be static or shared, it gets included in both.)

`lib.exe` will infer what architecture to use, based on earlier object files processed, or based on the `/machine:` option. Normally the `/machine:` option isn't needed and thus Meson doesn't currently pass it.

However, if the resource file gets passed to `lib.exe` before any of the actual object files, creating the library will fail:

```
$ lib /NOLOGO /OUT:libmylib.a src/src_mylib.rc_mylib.res 'src/src@@mylib@sta/implementation1.c.obj' ...
LINK : warning LNK4068: /MACHINE not specified; defaulting to X86
src\src@@mylib@sta\implementation1.c.obj : fatal error LNK1112: module machine type 'ARM' conflicts with target machine type 'x86'
```

If the `lib.exe` invocation would include a `/machine:` parameter, this wouldn't be an issue. Being able to omit the resource file from the static library altogether (close to what is discussed in #4159) would also solve the situation, as including the resource file in the static library is mostly pointless, at least when the resource is just DLL metadata.

### PR DESCRIPTION
**Pull request by jon-turney**
Closes #4463.  Supersedes #4040.

### CODE REVIEW

**Comment by jon-turney** [comment]
While this contains a test, I couldn't actually get it to fail in CI, currently.  Notwithstanding https://github.com/mesonbuild/meson/issues/4402#issuecomment-444098349 I think this only fails when cross-compiling.

This is also probably missing the correct handling of this scenario when the visual studio linker is being used along with other language compilers (e.g. D), (if that even makes sense)

For those reasons,  this should probably be considered WIP.

**Comment by jpakkane** [comment]
Since this is marked as superseding #4040, has this been tested to work for that use case?

**Comment by jon-turney** [comment]
I could not reproduce the problem (or even get a warning) using the instructions in https://github.com/mesonbuild/meson/pull/4040#issuecomment-415110848.

Perhaps @oleavr can help?

**Comment by jpakkane** [comment]
Is the fix itself no longer considered to be WIP?

**Comment by jpakkane** [comment]
Merge window is approaching, what should we do with this?

**Comment by jon-turney** [comment]
Sorry for the slow response.

I'm going to propose this for merging as-is.

It's not the best possible PR, but I think it does fix an actual problem, and I'm unlikely to find the time to write a better PR currently.

Cross-compiling on Windows needs more work, but hopefully at some stage meson will have some CI which covers that scenario, which will exercise the test added here and show that this change addresses #4463.

(I did some manual tests with cross-compiling when writing this change to demonstrate the problem and fix it).

**Pull request merged**
