### PR TITLE
hotdoc module: run hotdoc as an external command during configure

### PR DESCRIPTION
**Pull request by eli-schwartz**
We need to run it as an external command at build time anyway, and we detect it by looking it up as an ExternalProgram. It seems odd to then import it into Meson's python interpreter and run the main function.

Moreover, this errors out when you are running two different pythons, one for Meson and one for hotdoc. For example, when hotdoc is installed normally, but you're testing Meson against a nondefault newer version of python.

### CODE REVIEW

**Review by dcbaker — COMMENTED** [review]
Shouldn't we be using `mesonlib.Popen_safe` here?

**Comment by eli-schwartz** [comment]
No, because Popen_safe is a wrapper for safely handling stdout/stderr regardless of encoding.

But in this case we only want the return code, and send stdout to `subprocess.DEVNULL` so there's nothing to try decoding in 6 different ways via try/except.

**Review by dcbaker — APPROVED** [review]

**Comment by thiblahute** [comment]
This was an optimization and now configuring GStreamer is very slow when you have hotdoc on the system.

**Comment by eli-schwartz** [comment]
It should be run a maximum of twice per `hotdoc.generate_doc()` invocation. Is gstreamer building many distinct docs (per component in the full mega-build I guess)?

**Comment by thiblahute** [comment]
It does generate 1 per plugin, so hundreds of them yes.

**Pull request merged**
