### PR TITLE
Split run_unittests.py file

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
I expect this is going to take many try-and-error until I get it to pass on CI.

**Review by dcbaker — APPROVED** [review]
If you can get the CI to pass you have my acked-by on this. I didn't look at it closely, but it I did look at the run_unittests.py changes, at those seem reasonable.

**Comment by jon-turney** [comment]
Nice.  this also needs to change the path filters in the CI configuration files so CI which runs unittests runs on changes just in unittests/

**Review by mensinda — APPROVED** [review]
This also gets my stamp of approval (haven't looked through at all the changes though :D)

**Comment by xclaesse** [comment]
> This also needs to change the path filters in the CI configuration files so CI which runs unittests runs on changes just in unittests/

oh good point, forgot that, done.

**Pull request merged**
