### PR TITLE
wrap files: variable expansion and hash url

### PR DESCRIPTION
**Pull request by seingierf**
Expand environment variables and format strings that refer to other values in the same section.
Allow hash to be checked against a sha256 digest file instead of the plain hash value.

A typical usage of this feature allows to build various flavours of the wrap subproject that differ only by the package version or a git commit id, using the same wrap file.

Example:

```
[wrap-file]
package_name = glib-${GLIB_VERSION}.${GLIB_PATCH_LEVEL}
source_filename = %(package_name)s.tar.xz
directory = %(package_name)s
source_url = https://download.gnome.org/sources/glib/${GLIB_VERSION}/%(source_filename)s
source_hash_url = https://download.gnome.org/sources/glib/${GLIB_VERSION}/%(package_name)s.sha256sum
```

```sh
GLIB_VERSION=2.76 GLIB_PATCH_LEVEL=1 meson setup build
```

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> Expand environment variables and format strings that refer to other values in the same section.

This would mean that the wrap file fails entirely, if the environment variables are not set. It would even fail when reconfiguring the build, which happens automatically if you modify meson.build and run `ninja`.

> Allow hash to be checked against a sha256 digest file instead of the plain hash value.

This is equivalent to removing the hash feature altogether. Downloading a hash file from the Internet and checking against it does not serve any purpose. It doesn't tell you a security property of the archive file (that the file contains the same source code as a previously vetted file).

**Comment by xclaesse** [comment]
If you want to test different versions, use a wrap-git and just checkout the commit/tag you want.

**Comment by seingierf** [comment]
> > Expand environment variables and format strings that refer to other values in the same section.
> 
> This would mean that the wrap file fails entirely, if the environment variables are not set. It would even fail when reconfiguring the build, which happens automatically if you modify meson.build and run `ninja`.

True. The project will not build either if the compiler is not in `$PATH` or if `PKG_CONFIG_PATH` is not set properly depending on the project's requirements.
As for the reconfigure stage, it would not fail if the variables were exported instead of setting them on the command line.
Using gcc-toolset on Redhat hosts, for example, requires setting up environment variables in the current shell by running the `scl enable` command prior to using the compiler.
The point is that the PR does not enforce changes on users or existing projects but extends the syntax of wrap files in a way that could be useful in some CI environments.
Default values could even possibly be set by using the shell-style `${VAR:-default}` syntax.

> 
> > Allow hash to be checked against a sha256 digest file instead of the plain hash value.
> 
> This is equivalent to removing the hash feature altogether. Downloading a hash file from the Internet and checking against it does not serve any purpose. It doesn't tell you a security property of the archive file (that the file contains the same source code as a previously vetted file).

As noted in [this github PR](https://github.com/orgs/community/discussions/16426), the usefulness of hashes is not limited to security purposes.
It also provides some degree of confidence in the integrity of downloaded files.

I feel like the aforementioned security issue is not directly related to the `hash_url` suggestion in this PR.
`hash_url` gives the location of a digest file, which can be local, using the `file://` scheme, or a trusted https server that may be internal to a corporation rather than exposed on the Internet.

My example uses urls from the glib project because they provide https urls for both release assets and their corresponding sha256sums.
I understand the server that hosts the glib releases may get compromised but to be fair, on most occasions, people usually download releases from a "trusted" location (gitlab, github, over https) and also "trust" the checksum that is provided in release notes or the same page they downloaded the archive from.
Again, please note that no change is enforced on the user, they can still provide hard coded hashes in wrap files if they feel more confortable with it.

**Comment by eli-schwartz** [comment]
> True. The project will not build either if the compiler is not in `$PATH` or if `PKG_CONFIG_PATH` is not set properly depending on the project's requirements.

Untrue.

PATH doesn't have this problem to begin with, and PKG_CONFIG_PATH is not necessary for the same reason -- because by default, the *system environment* is acceptable to build against.

But also, both found compilers and pkg_config_path are core meson options / cross file properties that get frozen at first configure. Different from free-form environment variables.

> As noted in this github PR, the usefulness of hashes is not limited to security purposes.
> It also provides some degree of confidence in the integrity of downloaded files.

Arbitrary individuals on the Internet asking GitHub to do something, can certainly note whatever they wish to note -- but that doesn't mean other people are obligated to agree that they are an authority on the subject or that the note is correct.

And meson doesn't use hashes out of concern for interrupted, truncated downloads -- but rather,  for its security properties. TOFU does provide a lot of value.

> `hash_url` gives the location of a digest file, which can be local, using the `file://` scheme, or a trusted https server that may be internal to a corporation rather than exposed on the Internet.

I think we both know that that's not the primary goal here, nor how it's going to be used in practice. A better argument would be to support setting the hash itself from a variable, or restricting file loads to file://

**Comment by eli-schwartz** [comment]
It might be more interesting to support a method of switching between multiple hidden wraps via a primary proxy file rather than building new wraps on the fly. This currently doesn't work by simply renaming the wrap files to be versioned because they have conflicting provide names.

**Pull request closed without merging**
