### PR TITLE
Skip Py2 tests correctly also on other systems than Debian

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by dcbaker** [comment]
systemd says you need the `os-version` file, so pretty much every Linux system is going to have it. We should just drop that condition and run the pkg-config code always (or at least when there is pkg-config) for Windows we should probably be checking if `py -2` works. For mac I'm not sure.

**Comment by mimi1vx** [comment]
@dcbaker all modern distributions use `/etc/os-release` :D but probably better test  here will be use `sys.plattform`

**Comment by eli-schwartz** [comment]
```
if is_windows():
    do_stuff()
if os.path.exists('/etc/os-release'):
    do_other_stuff()
```

The second check should just be `elif True:`...

On any Debian system that doesn't have os-release, the python2 version will be older than Bullseye, which the code was designed to check for in the first place.

I agree this should just key off of the platform, and unconditionally check for python2 via pkg-config on all non-Windows systems, since all non-Windows systems have pkg-config and meson already expects pkg-config to exist.

**Comment by jpakkane** [comment]
> unconditionally check for python2 via pkg-config 

With `pkg-config --exists python2`?

**Comment by dcbaker** [comment]
Probably something like:

```python
if is_windows():
    has_py2 = subprocess.call(['py', '-2'], ...)
else:
    has_py2 = subprocess.call(['pkg-config', '--exists', 'python2'], ...)
```

**Comment by mimi1vx** [comment]
> Probably something like:
> 
> ```python
> if is_windows():
>     has_py2 = subprocess.call(['py', '-2'], ...)
> else:
>     has_py2 = subprocess.call(['pkg-config', '--exists', 'python2'], ...)
> ```

ant then check for  python2 devel files ?

**Comment by dcbaker** [comment]
pkg-config is checking for the devel files, and on windows you can't split them (I think)

**Comment by mimi1vx** [comment]
looks like somebody implemented Your idea :D :+1:

**Pull request closed without merging**
