### PR TITLE
Fix `c_compiler`.get_define parsing unintentional whitespace as defined variable

### PR DESCRIPTION
**Pull request by HaSa1002**
This is my attempt to fix https://github.com/mesonbuild/meson/issues/10179
I don't use python often and I had trouble setting up my dev environment for meson.

I feel like using this more explicit path should be robuster against wrong whitespaces.

### CODE REVIEW

**Comment by tristan957** [comment]
It would be nice to get a minimal reproducer to throw in `test cases` that way it doesn't regress.

**Comment by HaSa1002** [comment]
I am on holiday for 1,5 weeks now. I know, I have seen some info about how to make tests but that is nothing I can do on the fly. Anyway, I *think* this should be enough to reproduce this behaviour:
```python
cc = meson.get_compiler('c')
assert(cc.get_define('THIS_IS_PROBABLY_NOT_DEFINED') == '')
assert(cc.get_define('__DATE__) != '')
```

**Comment by tristan957** [comment]
Would that test fail on Meson master?

**Comment by HaSa1002** [comment]
Well... I hope so. The first use case is basically the issue I encountered to begin with (see the linked issue and the linked pr in the linked issue). It *may* fail on some MSVC instances (it did reliably when meson was invoked using the msvc dev command prompt). Instead of redefining and relying on the delimiter to check if the define is defined, I just added another text that can be checked against. So the check itself is more robust. This is basically juggling with standard output.

**Comment by tristan957** [comment]
I fixed the bugs in that snippet and neither of the asserts failed for me.

**Comment by HaSa1002** [comment]
Do you invoked meson using the x64 native command prompt? I only reliably reproduced it there. One with GH Actions and using the dev command prompt. Alternately you can try to build the libpng wrap in a project (again if invoked using the dev tools).

**Comment by xclaesse** [comment]
I can't reproduce this issue neither, something is weird with @HaSa1002 setup, as far as I know he's the only one who ever had that issue. Not saying he did anything wrong, but I feel we haven't found the real root cause here. It could be his Windows language has an effect, or a bug in a very specific MSVC version, some extra cflag... who knows...

**Comment by gregsskyles** [comment]
FWIW, I can't reproduce this bug with the latest release either; I'm guessing there's something else besides just VS 2019 needed to cause the issue.
Here's a log of what I did:
```
C:\Users\GregSkyles>cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\"

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.10.2
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cd \Users\GregSkyles\source\test-vs-env

C:\Users\GregSkyles\source\test-vs-env>meson init test-vs-env
Using "test-vs-env" (name of current directory) as project name.
Using "test-vs-env" (project name) as name of executable to build.
Defaulting to generating a C language project.
Sample project created. To build it run the
following commands:

meson setup builddir
meson compile -C builddir


C:\Users\GregSkyles\source\test-vs-env>rem  edit meson.build to add asserts

C:\Users\GregSkyles\source\test-vs-env>type meson.build
project('test-vs-env', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('test_vs_env', 'test_vs_env.c',
  install : true)

cc = meson.get_compiler('c')
assert(cc.get_define('THIS_IS_PROBABLY_NOT_DEFINED') == '')
assert(cc.get_define('__DATE__') != '')

test('basic', exe)

C:\Users\GregSkyles\source\test-vs-env>meson setup build .
The Meson build system
Version: 0.62.0
Source dir: C:\Users\GregSkyles\source\test-vs-env
Build dir: C:\Users\GregSkyles\source\test-vs-env\build
Build type: native build
Project name: test-vs-env
Project version: 0.1
C compiler for the host machine: cl (msvc 19.29.30038.1 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x64")
C linker for the host machine: link link 14.29.30038.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Fetching value of define "THIS_IS_PROBABLY_NOT_DEFINED" :
Fetching value of define "__DATE__" : "Mar 28 2022"
Build targets in project: 1

Found ninja-1.10.2 at "C:\Program Files\Meson\ninja.EXE"

C:\Users\GregSkyles\source\test-vs-env>
```

**Comment by xclaesse** [comment]
That said, I think this PR is a good idea because it distinguish between undefined and defined with empty value which could be generally useful. At least I prefer that over the original idea of stdout.strip().

**Comment by xclaesse** [comment]
CI fails with:

```
test cases\common\132 get define\meson.build:15:4: ERROR: Assert failed: _WIN32 value is 1
        
         instead of 1
```

That's weird... There is definitely something going on with whitespaces. I think it's because the value is inside the `#else` case now. Wondering if we should have a delimiter before **and after** the value to be sure?

**Comment by xclaesse** [comment]
To be fair, nothing forbid the preprocessor to add whitespaces there if it wants, we are probably relying on UB here anyway.

**Pull request closed without merging**
