### PR TITLE
vs2010: Support source files with same name from different subdirs

### PR DESCRIPTION
**Pull request by nioncode**
Fixes test case 54.
This also adds a test case for extracting objects with the same source filename.

### CODE REVIEW

**Comment by jpakkane** [comment]
This is good stuff but I'm not entirely a fan of how Meson does this currently. Maybe having a simpler layout would make sense. For example we could name objects files like this:

    [in source dir] src/foo.c -> s_src_foo.c.o
    [in build dir] src/private/foo.c -> b_src_private_foo.c.o

This would be simpler and unique because of the file system (unless someone does funky stuff with files with underscores in their name).

Again, this is not directly related to this MR but something we might think about.

**Comment by nioncode** [comment]
Isn't that what the ninja backend already does, except for the distinction of source and build dir?

I think we should not enforce any naming scheme and leave it to the backend to decide how to name the object files. For example, in the vs2010 backend it is costly to change the object filename from the default, because msbuild then can not batch the compilation together, but invokes the compiler for each source file that has a custom object output filename, which is quite slow.

**Comment by jpakkane** [comment]
Different backends have free reign on how they name their output files, yes. However in this particular case the patch adds `sources_conflicts` into the build object. This is an implementation detail of vs2010 and nobody else should need to know about it (they may have completely different views on conflicts and the internal representation should not depend on those). Please isolate the conflict detection and handling code inside the VS backend. Thanks.

**Comment by nioncode** [comment]
Done. Sorry, deleted the branch by mistake.

**Pull request merged**
