### PR TITLE
wrap: If the directory exists in a sub-subproject, uses it inplace

### PR DESCRIPTION
**Pull request by xclaesse**
A subproject could have a sub-subproject as a git submodule, or part of
    the subproject's release tarball, and still have a wrap file for it
    (e.g. needed for [provide] section). In that case we need to use the
    source tree for the sub-subproject inplace instead of downloading a new
    copy into the main project.
    
    This is the case with GLib 2.74, it has a subproject "gvdb" as git
    submodule, and part of release tarball, it ships gvdb.wrap file as well.

### CODE REVIEW

**Comment by xclaesse** [comment]
@nirbheek only the last commit needs to be backported, the rest is just cosmetic cleanups.

**Comment by xclaesse** [comment]
See https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2906 for a workaround at the glib level.

**Comment by eli-schwartz** [comment]
First commit is wrong because not all subprojects have wrap files.

I suspect this is what is causing the test failure, too.

**Comment by xclaesse** [comment]
@eli-schwartz right, that was a bad rebase conflict resolution. Fixed.

**Review by eli-schwartz — APPROVED** [review]

**Pull request merged**
