### PR TITLE
cmake: Fix CMake LLVM dependency error (fixes #10322)

### LINKED ISSUE #10322: llvm: AttributeError: 'LLVMDependencyCMake' object has no attribute 'found_modules'
**Describe the bug**
Somehow the dependency on LLVM does not work anymore. I'm pretty sure this was different on prior Meson versions but cannot track it down.

**To Reproduce**
This meson.build file triggers the error:
```
project('testa', 'cpp')
llvm = dependency('llvm')
```
Error:
```
The Meson build system
Version: 0.62.1
Source dir: /home/gerion/test
Build dir: /home/gerion/test/build
Build type: native build
Project name: testa
Project version: undefined
C++ compiler for the host machine: ccache c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: The LLVM dependency was not found via CMake since both a C and C++ compiler are required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/msetup.py", line 301, in run
    app.generate()
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreter/interpreter.py", line 2700, in run
    super().run()
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 567, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreter/interpreter.py", line 1620, in func_dependency
    d = df.lookup(kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 352, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 93, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/dependencies/detect.py", line 120, in find_external_dependency
    details = d.log_details()
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/dependencies/cmake.py", line 621, in log_details
    modules = [self._original_module_name(x) for x in self.found_modules]
AttributeError: 'LLVMDependencyCMake' object has no attribute 'found_modules'

meson.build:2:0: ERROR: Unhandled python exception
```

**Expected behavior**
LLVM should be found.

**Additional information**
Changing the project language to `c` leads to the same error. Changing the project language to `c` _and_ `cpp` fixes the error:

meson.build
```
project('testa', 'c', 'cpp')
llvm = dependency('llvm')
```
Output:
```
The Meson build system
Version: 0.62.1
Source dir: /home/gerion/test
Build dir: /home/gerion/test/build
Build type: native build
Project name: testa
Project version: undefined
C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
C++ compiler for the host machine: ccache c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found CMake: /usr/bin/cmake (3.18.4)
WARNING: Ignoring LLVM CMake dependency because dynamic was requested
llvm-config found: YES (/usr/bin/llvm-config-13) 13.0.1
Run-time dependency LLVM found: YES 13.0.1
Build targets in project: 0

Found ninja-1.10.1 at /usr/bin/ninja
```

Setting config-tool as search method works, too:
```
project('testa', 'cpp')
llvm = dependency('llvm', method: 'config-tool')
```
Output:
```
The Meson build system
Version: 0.62.1
Source dir: /home/gerion/test
Build dir: /home/gerion/test/build
Build type: native build
Project name: testa
Project version: undefined
C++ compiler for the host machine: ccache c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
llvm-config found: YES (/usr/bin/llvm-config-13) 13.0.1
Run-time dependency LLVM found: YES 13.0.1
Build targets in project: 0

Found ninja-1.10.1 at /usr/bin/ninja
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?: native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Debian 11 (with llvm-13 and llvm-12 backports)
* what Python version are you using e.g. 3.8.0: 3.9.0
* what `meson --version`: 0.62.1

### PR DESCRIPTION
**Pull request by mensinda**

### CODE REVIEW

**Comment by mensinda** [comment]
The mypy error looks unrelated...

**Comment by eli-schwartz** [comment]
> The mypy error looks unrelated...

Correct. I have another PR to fix that, but I don't know why it is necessary. :( It feels like mypy "should" know this and allow it, as it used to.

**Comment by jpakkane** [comment]
That has been merged, a rebase should make it go green.

**Comment by jpakkane** [comment]
That LGTM warning seems relevant. Is it just a matter of adding a `super` init call?

**Comment by mensinda** [comment]
> That LGTM warning seems relevant. Is it just a matter of adding a super init call?

It is complaining about the `ExternalDependency.__init__(self, DependencyTypeName('cmake'), env, kwargs)` call. It thinks that there is a possibility that the constructor may be called twice (via the already existing `super().__init__()` call). However, this is not the case because of the `return` in the same `if` branch.

I would like to keep the `ExternalDependency.__init__()` call regardless, because the goal is to still initialize the object as best as possible without calling the `CMakeDependency` constructor. The real fix here would be to *not* have the dependency detection logic in the constructor, but in a separate, abstract method instead.

**Pull request merged**
