### PR TITLE
Do not recurse into subdirs that are symlinks. Closes #1749.

### LINKED ISSUE #1749: Building in a dir with recursive symlinks is not handled correctly...
If you have a directory structure like this:

junk/
junk/junk symlink -> ../junk

mesonbuild will recurse until erroring out.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by nirbheek** [comment]
This is throwing the baby out with the bathwater. Here is what actually happens in that case:

```
The Meson build system
Version: 0.41.0.dev1
Source dir: /tmp/meson
Build dir: /tmp/meson/build
Build type: native build
Project name: test
Native c compiler: ccache cc (gcc 6.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/meson.build, line 1, column 0:
Nonexistent build def file test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/test/meson.build.
```

Which is what every other program would do because there is a maximum limit on symlink recursion. There is no bug here.

**Comment by nirbheek** [comment]
And in any case, this would only happen if you specially craft a tree that looks like this:

```
meson.build
test/meson.build
test/test -> ../test
```

contents of `meson.build`:
```
...
subdir('test')
```

contents of `test/meson.build`:
```
subdir('test')
```

There is no way this happens accidentally, and if it does, it's your own fault.

**Comment by jpakkane** [comment]
Subprojects are still allowed to be symlinks, this is only for `subdir`. One of the main design goals has been to never be allowed to enter the same directory twice. In fact I thought that I had done this check earlier but apparently had not.

**Comment by jpakkane** [comment]
A different way to solve this would be to use `os.path.realpath` on directory names before checking whether they have been visited.

**Comment by nirbheek** [comment]
Instead of completely disallowing symlinks, we should detect cycles and error out if we enter the same directory again because of a symlink.

**Comment by nirbheek** [comment]
`os.path.realpath` would do it to check for cycles, but we should do the "is subdir of current directory" check on the symlink, not on the real path. That way people can still use symlinks to enter a directory once.

**Comment by jpakkane** [comment]
Realpath protects against other errors too. For example if you have a directory `foo` and symlink `bar -> foo` then doing `subdir('foo') subdir('bar')` should error out even though it is not a cycle.

We can limit that symlinks can only go to a subdir of the current dir, but can we loosen this requirement? As an absolute requirement the symlink must point inside the source tree (and not inside the build dir if it is inside the source tree). A reasonable limitation would also be to not cross the subproject boundary. We currently don't permit going up the tree so a better stricter requirement would be that the symlink must point to a subdirectory of the current directory.

**Comment by nirbheek** [comment]
All we need to do is use realpaths as keys in `self.visited_subdirs`, and that will cover everything. You won't be able to revisit a directory and you will be able to visit symlink subdirs exactly once.

**Comment by jpakkane** [comment]
Updated to do just that.

**Comment by jpakkane** [comment]
Merged manually.

**Pull request closed without merging**
