### PR TITLE
Remove duplicates in generated pkgconfig required versions

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by jpakkane** [comment]
Could a test be added to this to ensure it is working?

**Comment by xclaesse** [comment]
Added a test.

**Comment by jpakkane** [comment]
The test only checks that you can put the dep in there twice FWICT. Should it not parse the result file and verify that the dependency is there only once?

**Comment by xclaesse** [comment]
There is a unit test that parse it already. I verified that it fails without the patch and succeed with it.

**Comment by jpakkane** [comment]
Excellent.

**Pull request merged**
