### PR TITLE
cmake: Use trace for missing link flags (fixes #6386)

### LINKED ISSUE #6386: CMake subproject does not add -pthread to the linker command line
**Describe the bug**

I've been trying to make [reproc](https://github.com/DaanDeMeyer/reproc) useable as a meson subproject. The current issue is that demo executables fail to link due to `-pthread` not being added to the linker command line by meson.

**To Reproduce**

meson.build:

```
project('tutorial', 'c')

cmake = import('cmake')

reproc = cmake.subproject('reproc')
libreproc = reproc.dependency('reproc')

executable('demo', ['main.c'], dependencies: [libreproc])
```

main.c (one of reproc's examples):

```c
#include <reproc/reproc.h>

#include <stdio.h>
#include <stdlib.h>

// Forwards the provided arguments to `reproc_start` which starts a child
// process that inherits the standard streams of the parent process. It will
// read its input from the stdin of this process and write its output to the
// stdout/stderr of this process.
int main(int argc, const char *argv[])
{
  if (argc <= 1) {
    fprintf(stderr,
            "No arguments provided. Example usage: ./inherit cmake --help");
    return 1;
  }

  reproc_t *process = reproc_new();

  reproc_options options = { .redirect = { .in = REPROC_REDIRECT_INHERIT,
                                           .out = REPROC_REDIRECT_INHERIT,
                                           .err = REPROC_REDIRECT_INHERIT } };
  int r = -1;

  r = reproc_start(process, argv + 1, options);
  if (r < 0) {
    goto cleanup;
  }

  r = reproc_wait(process, REPROC_INFINITE);
  if (r < 0) {
    goto cleanup;
  }

  r = reproc_exit_status(process);

cleanup:
  reproc_destroy(process);

  if (r < 0) {
    fprintf(stderr, "%s\n", reproc_error_string(r));
  }

  return abs(r);
}
```

```sh
git clone https://github.com/DaanDeMeyer/reproc.git subprojects/reproc
meson build
ninja -C build
```

**Expected behavior**

The build succeeds and I can run `build/demo cmake --help`. Instead, linking fails because `pthread_sigmask` cannot be found.

reproc enables `THREADS_PREFER_PTHREAD_FLAG` before calling `find_package(Threads)`. The pthreads dependency is added to reproc with `target_link_libraries(reproc PRIVATE Threads::Threads)`. Changing `PRIVATE` to `PUBLIC` or disabling `THREADS_PREFER_PTHREAD_FLAG` does not fix the issue.

**system parameters**
* Platform: Native
* OS: Arch Linux
* Python 3.8.1
* meson 0.52.1
* ninja 1.9.0

### PR DESCRIPTION
**Pull request by mensinda**
This is necessary for static libraries since the CMake file API does not add link flags here.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
I'm still getting undefined reference to `pthread_sigmask` it seems. I cloned your fork, switched to the `cmStaticFix` branch and I'm running `meson/meson.py build` to configure the project.

**Comment by mensinda** [comment]
I am unable to reproduce this with this PR.
Could you please paste the generated `<build dir>/subprojects/reproc/meson.build`

My main `meson.build`:
```meson
project('tutorial', 'c')

cmake = import('cmake')

reproc = cmake.subproject('reproc')
libreproc = reproc.dependency('reproc')

executable('demo', ['main.c'], dependencies: [libreproc])
```

**Comment by DaanDeMeyer** [comment]
I was wrong, the reproduce I listed now works correctly. However, when enabling all of reproc's developer options, the issue persists (those are enabled by default on my machine via an environment variable which is why you couldn't reproduce).

If you add `REPROC_DEVELOP=ON` and `REPROC_SANITIZERS=OFF` to `cmake_options`, you should get an undefined reference to `pthread_sigmask`. I'll do some further debugging to see which option exactly is causing the error.

**Comment by DaanDeMeyer** [comment]
`REPROC_OBJECT_LIBRARIES` (which makes reproc and reproc++ CMake object libraries) is causing the issue. I'm not sure meson even supports object libraries so this might be a non-issue.

**Comment by mensinda** [comment]
Object libraries are currently only partially supported. It is only possible to use them [internally in CMake files](https://github.com/mesonbuild/meson/blob/master/test%20cases/cmake/5%20object%20library/subprojects/cmObjLib/CMakeLists.txt). Using them in meson directly is only possible if you manually add the required dependencies.

Also, meson does not even have the concept of object libraries. There are only static libraries on which you can call [extract_objects](https://mesonbuild.com/Reference-manual.html#build-target-object).

**Pull request merged**
