### PR TITLE
Use isort

### PR DESCRIPTION
**Pull request by dcbaker**
I sort is handy linter/rewriter utility for managing python imports. It's reasonably configurable, but ensures that imports are handled consistently, and in PEP8 *order* (stdlib, newline, third party, newline, first party). The actual layout is more flexible.

While I'm sure everyone will have an opinion on how it should look, I've tried to take the two guiding principles in selecting which format to use:
1. minimize git diffs
2. maximize readability
3. minimize vertical space use
4. maximize horizontal space use (helps with 2)

Therefore, I've picked a format that makes `from X import`s look like this:
```python
from X import Y
from X.Z import (
    Import0, Import1, Import2, Import3, Import4, #until end of line reached
    Import10,
)
```
If the `from` import fits on one line, it will do so, without braces.
If it it does not it will be placed with the `from X import (` on it's own line. This makes the from line somewhat more readable in my opinion, but more importantly by placing the actual imports on their own line, they maximize the amount of horizontal space they use. This means that they will end up using less vertical space in cases where the the module name is long (fairly common in Meson), or the number of imports from the module is large (also fairly common in Meson). The closing `)` is placed on it's own line because this minimizes git diffs when a new line is added or subtracted.

I've also added an additional github test to enforce that isort has been used before merging.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I've been playing with this too, fiddling with config files. My current level of tweaking looks like this:
```
[settings]
src_paths=mesonbuild
combine_straight_imports=true
include_trailing_comma = true
multi_line_output=5
use_parentheses=true
known_typing=typing
sections=FUTURE,STDLIB,TYPING,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```

I don't love it, though, because things like `from X import YYY as y` cause all existing grouped imports to be alphabetically divided in three or something. I'd also like isort to NOT modify existing grid-wrapped imports, every time one is removed, to reshuffle the ENTIRE grid for max line length. Instead I just want removed imports to be removed from the middle of the line resulting in lines getting shorter, but easier to read diffs. If imports are then later added to that grid, the lines will grow longer again. If not, we shouldn't reflow them except in rare cases.

I think it's not practical to enforce it in CI until new features are added to isort to control this.

**Comment by eli-schwartz** [comment]
Submitted https://github.com/PyCQA/isort/issues/2102 for one of those issues, BTW.

**Comment by dcbaker** [comment]
I'm absolutely against the `combine_straight_imports`, that makes the imports *really* hard to read, IMO, and it's a super uncommon style in python projects, and It's against PEP8 which is super clear that `import foo` should go on it's own line, and we try to follow PEP8 as much as possible.

I'm kinda mixed on the reflowing grid wrapped imports. On the one hand the minimal diffs are nice, on the other hand, things should be sorted for easy reading, and ending up with funny spacing makes this harder to read (which is why so much modern formatting of text has gone to justified block formatting, it's actually easier to read)

consider some of the cases we have that are like:
```python
from mesonlib import (AThing, AZThing,
                      Beer,
                      Cactus, Cauliflower, Cumin, Dill, Eggplant,
                      Foxglove, Gilded, Honey,
                      Igloos, Jewlery, Kilbasa, Lavender, Money)
```
Which uses a more vertical space and is harder to read than;
```python
from mesonlib import (AThing, AZThing, Beer, Cactus, Cauliflower,
                      Cumin, Dill, Eggplant,  Foxglove, Gilded, Honey,
                      Igloos, Jewlery, Kilbasa, Lavender, Money)
```

I guess to me minimizing diffs is a nice to have, but making imports readable is a must have

**Comment by eli-schwartz** [comment]
I find them both very readable, and my opinion on the matter is that this is a case where the CI should not be gated on perfectly balancing the lengths, but rather, commit authors should use their best judgment. That's why I'm suggesting that what we really need is an isort option to ***abdicate judgment***, since it is incapable of telling how subjectively unreadable it is.

It would remain possible to do a one-shot global rebalancing.

**Pull request closed without merging**
