### PR TITLE
Add LANG to Dockerfile

### PR DESCRIPTION
**Pull request by NickeZ**
This is required to use utf8 filenames.

### CODE REVIEW

**Comment by NickeZ** [comment]
Yeah that makes sense, one benefit is that  C.utf-8 doesn't depend on the `locales` package. I changed and verified that this image also works with UTF-8 characters in file names.

**Comment by NickeZ** [comment]
Is CI failure related?

```
meson.build:1:0: ERROR: Unknown compiler(s): [['clang']]
The follow exceptions were encountered:
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang': 'clang'"
```

**Comment by jpakkane** [comment]
I may have crapped the image. A new one is getting built at the moment.

**Comment by NickeZ** [comment]
But as far as I understand you are not using the `Dockerfile` for anything in CI. So you can merge this if you approve?

**Pull request merged**
