### PR TITLE
mesonbuild: Recognise risc-v architecture

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by rossburton** [comment]
Do those names match what platform.machine() gives under Python on target?

**Comment by rossburton** [comment]
Also to make the CI pass, you need to expand the documentation too.

**Comment by jpakkane** [comment]
Are you aware if these names are what all other build systems et al use for RISCV or are there some other terms as well?

**Comment by kraj** [comment]
riscv32 support is just being added to glibc so not many distros are out there yet and riscv64 is common yes.

**Comment by jpakkane** [comment]
And the glibc names are riscv32 and riscv64?

**Comment by jpakkane** [comment]
And to highlight this question from above:

> Do those names match what platform.machine() gives under Python on target?

**Comment by kraj** [comment]
Here is output from python on qemuriscv64

```
root@qemuriscv64:~# python
Python 2.7.15 (default, Jul 21 2018, 18:17:04)
[GCC 8.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print platform.machine()
riscv64
>>>
```

**Comment by jpakkane** [comment]
Great, thanks.

**Pull request merged**
