### PR TITLE
Fix searching of shared libraries on OpenBSD

### PR DESCRIPTION
**Pull request by nirbheek**
commit e75f43a87e86051f927c462dce30a31a189ecbc3

    find_library: Fix manual searching on OpenBSD
    
    On OpenBSD, shared libraries are called libfoo.so.X.Y where X is the
    major version and Y is the minor version. We were assuming that it's
    libfoo.so and not finding shared libraries at all while doing manual
    searching, which meant we'd link statically instead.
    
    See: https://www.openbsd.org/faq/ports/specialtopics.html#SharedLibs
    
    Now we use file globbing to do file searching, and pick the first one
    that's found.
    
    Closes https://github.com/mesonbuild/meson/issues/3844

commit 06e87d19bea88e5c74c9eec0e37d5b58d1321749

    get_library_naming: Use templates instead of suffix/prefix pairs
    
    This commit does not change functionality, and merely sets the
    groundwork for a more flexibly naming implementation.

@ajacoutot @kernigh: can you please test this? There's no CI for OpenBSD so we have no idea if this works there or not.

### CODE REVIEW

**Comment by ajacoutot** [comment]
Hi @nirbheek 
Patching over master code, it seems worse now:
```
cc  -o libappstream-builder/libappstream-builder.so.3.3 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-app.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-context.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-package.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-package-cab.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-package-deb.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-task.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-utils.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-plugin.c.o' 'libappstream-builder/libappstream-builder@@appstream-builder@sha/asb-plugin-loader.c.o' -L/usr/local/lib -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libappstream-builder.so.3.3 -O2 -pipe libappstream-glib/libappstream-glib.so.3.3 -Wl,--version-script,/hack/objdirs/pobj/appstream-glib-0.7.9/appstream-glib-0.7.9/libappstream-builder/appstream-builder.map /usr/local/lib/libglib-2.0.a /usr/local/lib/libintl.a -Wl,-E -pthread /usr/local/lib/libgmodule-2.0.a /usr/local/lib/libgdk_pixbuf-2.0.a /usr/local/lib/libgobject-2.0.a /usr/local/lib/libarchive.a /usr/local/lib/libsoup-2.4.a /usr/local/lib/libgio-2.0.a /usr/local/lib/libyaml.a -Wl,--end-group -Wl,-z,origin '-Wl,-rpath,$ORIGIN/../libappstream-glib' -Wl,-rpath-link,/hack/objdirs/pobj/appstream-glib-0.7.9/build-amd64/libappstream-glib 
```

I'll try and get you more info soon.
Thanks.

**Comment by nirbheek** [comment]
Ah, the priority is wrong. Let me fix that.

**Comment by ajacoutot** [comment]
Indeed, I just figured that if there's no static archive it will properly use the so file, otherwise it will use the static one by default :-)

**Comment by ajacoutot** [comment]
Works perfectly \o/
Thanks a lot @nirbheek

**Comment by nirbheek** [comment]
> Works perfectly \o/

Thanks for testing. Will merge it for the stable release as soon as the tests pass. :)

**Pull request merged**
