### PR TITLE
New testing tool

### PR DESCRIPTION
**Pull request by jpakkane**
DO NOT MERGE YET!

Something to get #708 going. A new executable to run tests in various configurations. The idea is that Ninja would have only `test` and `test-without-subprojects` and everything else would be accessed via this helper, including tools like Valgrind. Getting arguments etc through the pipeline is a fair bit of work and the end result is not massively usable.

Things that this allows you to do:

```
mesontest --repeat=100 mytest
mesontest --repeat=100 --wrapper=valgrind mytest
mesontest --repeat=100 --wrapper='valgrind --tool=helgrind' mytest
mesontest --repeat=100 --gdb mytest
```

### CODE REVIEW

**Comment by tp-m** [comment]
Will it be possible to specify additional environment variables for various standard wrappers such as gdb or valgrind? e.g. when running tests in gdb we'd need to tell GStreamer not to fork for the plugin scanning.

**Comment by jpakkane** [comment]
It's a command line tool so you can already do that with `FOOBAR=bob mesontest <args>`. We could add some helper args, though, if there is need for them.

**Comment by tp-m** [comment]
Sure, but users of the tool may not know what we (who wrote the code/tests) want passed :) Ideally it should work automatically just like the env vars specified in the tests. Maybe something like extra_env_{gdb,valgrind} : [ ... ] or such? Anyway, minor issue in the grand scheme of things, just thought of it and wanted to mention it :)

**Comment by jpakkane** [comment]
There are two different cases here. The first one is the common one: run all tests, store output for analysis. The second one is very project and bug specific: run 1000 times, run with a wrapper, run under gdb etc.

There are a ton of different ways to do the latter. Providing all possible combinations as Ninja targets is very confusing, makes the number of kwargs explode and has poor usability. What really is wanted for this case is a cli tool to run the tests in any way people see fit. Modifying your test setup via Meson configuration means that Meson reconfigures itself on every change. This is not very nice.

The proposed workflow would thus be something like this:

 - run all tests with `ninja test`
 - if any one of them fails, run it with your special setup using `mesontest`
 - projects would probably write setups they deem useful (tests a, b, d, and e 100x under Valgrind) into standalone scripts, possibly with corresponding `run_targets`

In this way we expose everything for easy CLI usage (and IDE integration) while keeping the core of Meson unaware of the details of how tests are run. The current Valgrind setup is a big wart on the cleanliness of test setup code.

**Comment by thiblahute** [comment]
fwiw the end goal of that is pretty similar to what we do in [gst-validate-launcher](https://phabricator.freedesktop.org/diffusion/GSTDEV/browse/master/validate/launcher) in the sense that the two things are about launching tests with parameters, under valgrind, under gdb, forever... etc, etc

I was wondering if it would make sense to unify the two things? Basically having it in meson and use it in GstValidate having the test definitions in meson.build files instead of our current python based test definitions.

Currently the GstValidateLauncher also lets people subclass the Test class and basically interact with the subprocess, launch another process (for example to start an http server), check other factors of failure than just the return code (and basically give more information about why it failed etc...) is that something you could consider in scope?

That tool already has a lot of feature and I bet big parts of it could be reused.

**Comment by jpakkane** [comment]
All of these are things we intend to provide. However I would imagine that many projects will write their own test runner tools for their special needs. This is why all information about running tests is exposed via `mesonintrospect`. I have not gone through gstvalidate's code but I would imagine making it import test setup data would be straightforward.

As for merging code, that repo seems to be under LGPL2 so we can't take that unfortunately (though if all of it is your code relicensing could be possible).

**Comment by thiblahute** [comment]
I will investigate that, about re-licensing, I am the copyright owner of all the interesting files so there is no problem if it is useful.

**Comment by thiblahute** [comment]
btw, I pushed a few commits on top of your branch here: https://github.com/thiblahute/meson/commits/newtest

**Comment by jpakkane** [comment]
Having both valgrind args and gdb args is a bit suspect. If we add more wrapper tools (including lldb) then the number of arguments grows and grows. The test runner should probably not know anything of these but just get a general array to put in front of of the command. The idea is to also get all valgrind stuff away from Meson core.

**Comment by thiblahute** [comment]
Yeah, I was expecting such an answer, but here we need some special env vars to be set when running inside gdb and with such argument we can do `set environment VAR=value` -- Is there a big issue about having many possible arguments?

**Pull request merged**
