### PR TITLE
pkgconfig: Set PKG_CONFIG in env for devenv and g-ir-scanner

### PR DESCRIPTION
**Pull request by xclaesse**
The pkg-config binary could come from meson.override_find_program(), or machine file. In those case we need PKG_CONFIG env for external tools to find it.

### CODE REVIEW

**Comment by xclaesse** [comment]
This is needed for g-ir-scanner to find pkg-config there: https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/main/giscanner/pkgconfig.py#L30.

**Comment by ylatuya** [comment]
I was trying a similar approach and hit the same issue. This doesn't work since `find_external_program` does not finds correctly pkg-config, which is provided by a wrap like this:

```
meson.override_find_program('pkg-config', find_program('pkg-config.exe'))
```

In the logs I can see:

```
win-pkgconfig| Project name: win-pkgconfig
win-pkgconfig| Project version: 0.29.2
win-pkgconfig| Message: Downloading pkg-config.exe binary for Windows...
win-pkgconfig| Program pkg-config.exe found: YES (C:\gstreamer\subprojects\win-pkgconfig\pkg-config.exe)
win-pkgconfig| Build targets in project: 0
win-pkgconfig| Subproject win-pkgconfig finished.
[...]
gstreamer| Did not find pkg-config by name 'pkg-config'
gstreamer| Found Pkg-config: NO
```

`PkgConfigDependency.search_pkgbin` should do the equivalent to `find_program('pkg-config')`

**Comment by xclaesse** [comment]
> This doesn't work since `find_external_program` does not finds correctly pkg-config
> `PkgConfigDependency.search_pkgbin` should do the equivalent to `find_program('pkg-config')`

I'm writing a unit test for that, and you were right. I'll try to find a solution.

**Comment by xclaesse** [comment]
> I'm writing a unit test for that, and you were right. I'll try to find a solution.

It's actually way too complicated to get it working through override_find_program(), the problem is PkgConfigDependency does not have access to the interpreter. I don't know how to fix that without doing ugly hacks or way too big refactoring.

Note that this PR was not useless either, it sets PKG_CONFIG to the value from cross file, which at least makes g-ir-scanner consistent in using the same pkg-config as Meson.

**Pull request closed without merging**
