### PR TITLE
pkgconfig module: automatic add Requires from libraries dep if no Req…

### PR DESCRIPTION
**Pull request by KrullKorg**
…uires is specified.

### CODE REVIEW

**Comment by jpakkane** [comment]
Is this something we can reliably determine like this. IIRC pkgconfig can have private depends (`Libs.private` at least) and there does not seem to be a simple way to tell if a dep should be private or public. Would it be better to add new keywords for these? It would be more explicit as well.

**Comment by KrullKorg** [comment]
i think that for the majority of cases that patch can be useful; if someone needs Libs.private can explicitly provides the Requires field and then the Libs.private field

**Comment by nirbheek** [comment]
We need to figure out when `Requires.private` vs `Requires` is used before we can merge this. It needs a bit of research. I think most pkg-config files have random stuff inserted in there.

**Comment by jpakkane** [comment]
This is a bit old MR and the pkg-config module has changed a lot during this time (and is changing more as we speak). Thus closing, but if this is still an issue for you, please open a bug explaining your use case and how you would want it to work. Thanks.

**Pull request closed without merging**
