### PR TITLE
various micro-optimizations 

### PR DESCRIPTION
**Pull request by eli-schwartz**

### CODE REVIEW

**Comment by dcbaker** [comment]
This is literally all in my pylint series already

**Comment by eli-schwartz** [comment]
> This is literally all in my pylint series already

Huh, I did not realize pylint could do that. This was something I've wanted to get around to for a while, and just got prompted by my imports moving PR...

**Comment by eli-schwartz** [comment]
There's now two useful-ish commits here, one replaces set() with a set literal and another finally adds `__future__.annotations` anywhere it wasn't already.

**Comment by eli-schwartz** [comment]
On the topic of `foo([list comprehension])` to generator expressions, for anything other than all/any there's no short-circuiting to do. In theory, they are nice anyway due to list allocation (PEP 289 literally talks about this) and at least should save memory, but supposedly they are also often slower. Know anything about this? My first version of the dropped patch actually was going to change a bunch of other builtin functions too. :/

**Comment by eli-schwartz** [comment]
Some of these optimizations are now detected by pylint too. :)

Added even more, rebased. This fixes CI.

**Review by dcbaker — APPROVED** [review]
I didn't look at the one to add `__future__.annotations`, I'll trust you on that one.

**Comment by eli-schwartz** [comment]
That one is slightly rebased so I think there may be duplicates that collapsed down to whitespace reformatting.

But really it just adds the same thing to every file that doesn't already have it, where currently a dozen different PRs each potentially add it to *one* file while otherwise modifying it.

It just feels more orderly to do it once, and in a commit that is dedicated to just that. :D

**Comment by eli-schwartz** [comment]
@nirbheek In order for the linting CI to succeed we are going to need at least the "simplify instantiation of ..." commit and the ones that mention pylint 2.16, so I have tagged this PR with the stable milestone.

**Pull request merged**
