### PR TITLE
devenv: Resolve executable in devenv's PATH

### PR DESCRIPTION
**Pull request by xclaesse**
Fixes: #10815

### CODE REVIEW

**Comment by xclaesse** [comment]
Merging since reporter confirmed that fixes the issue.

**Comment by eli-schwartz** [comment]
So, that has a CI failure...

@lazka,

```
"clang++"  -o sum.exe sum.exe.p/sum.c.obj "-Wl,--allow-shlib-undefined" "-Wl,--start-group" "-lpthread" "D:/a/msys64/mingw64/bin/libzstd.dll" "-LD:/a/_temp/msys64/mingw64/lib" "-lLLVMX86CodeGen" "-lLLVMCFGuard" "-lLLVMX86Desc" "-lLLVMX86Info" "-lLLVMMCJIT" "-lLLVMExecutionEngine" "-lLLVMRuntimeDyld" "-lLLVMOrcTargetProcess" "-lLLVMOrcShared" "-lLLVMAMDGPUTargetMCA" "-lLLVMMCA" "-lLLVMAMDGPUDisassembler" "-lLLVMMCDisassembler" "-lLLVMAMDGPUAsmParser" "-lLLVMAMDGPUCodeGen" "-lLLVMMIRParser" "-lLLVMGlobalISel" "-lLLVMSelectionDAG" "-lLLVMAMDGPUDesc" "-lLLVMAMDGPUUtils" "-lLLVMAMDGPUInfo" "-lLLVMPasses" "-lLLVMObjCARCOpts" "-lLLVMCoroutines" "-lLLVMipo" "-lLLVMInstrumentation" "-lLLVMVectorize" "-lLLVMLinker" "-lLLVMIRReader" "-lLLVMAsmParser" "-lLLVMFrontendOpenMP" "-lLLVMAsmPrinter" "-lLLVMCodeGen" "-lLLVMTarget" "-lLLVMScalarOpts" "-lLLVMInstCombine" "-lLLVMAggressiveInstCombine" "-lLLVMTransformUtils" "-lLLVMBitWriter" "-lLLVMAnalysis" "-lLLVMProfileData" "-lLLVMSymbolize" "-lLLVMDebugInfoPDB" "-lLLVMDebugInfoMSF" "-lLLVMDebugInfoDWARF" "-lLLVMObject" "-lLLVMTextAPI" "-lLLVMMCParser" "-lLLVMMC" "-lLLVMDebugInfoCodeView" "-lLLVMBitReader" "-lLLVMCore" "-lLLVMRemarks" "-lLLVMBitstreamReader" "-lLLVMBinaryFormat" "-lLLVMSupport" "-lLLVMDemangle" "-lpsapi" "-lshell32" "-lole32" "-luuid" "-ladvapi32" "-lz" "-lxml2" "-pthread" "D:/a/_temp/msys64/mingw64/lib/libz.dll.a" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-loleaut32" "-lcomdlg32" "-Wl,--end-group"
clang++: error: no such file or directory: 'D:/a/msys64/mingw64/bin/libzstd.dll'
```

Which is probably coming from [llvm_dep](https://github.com/mesonbuild/meson/blob/7e4188a53fdebda6a06b6ac3bd4bc4e51411702d/test%20cases/frameworks/15%20llvm/meson.build#L29-L36), and llvm just updated to 15 in MSYS2.

But this seems quite wrong, all the other msys2 paths are `D:/a/_temp/msys64`, including other DLLs in the same link line. Is the LLVM package currently broken?

**Comment by lazka** [comment]
Thanks, I'll have a look.

We have been building lots of packages with it, so not broken in general.

**Comment by lazka** [comment]
Please try again now (maybe just restart the failing job in this PR?)

**Comment by xclaesse** [comment]
@lazka I see that recent PRs are passing, do I think it's solved. Thanks!

**Comment by lazka** [comment]
I just uploaded some minutes ago, so that would be fast :) but anyway, ping me in case there are more regressions.

**Pull request merged**
