### PR TITLE
Improvements for the pkgconfig module

### PR DESCRIPTION
**Pull request by arteymix**
Prepend instead of appending a space so that we never end with a trailing space.

### CODE REVIEW

**Comment by arteymix** [comment]
@ignatenkobrain I have other fixes for the pkgconfig module, would you prefer a separate PR?

**Comment by arteymix** [comment]
Just renamed the PR to make it more correct. It just include simple fixes and missing features based on the [Guide to pkg-config](https://people.freedesktop.org/~dbn/pkg-config-guide.html)

**Comment by TingPing** [comment]
Patch to test the validity of the generated file to avoid these mistakes:

```diff
From 0ca351d1038fb6ed65653eea0615ea7c86dc204a Mon Sep 17 00:00:00 2001
From: Patrick Griffis <tingping@tingping.se>
Date: Fri, 7 Oct 2016 12:25:01 -0400
Subject: [PATCH] tests: Test validity of pkgconfig.generate() output

---
 test cases/common/51 pkgconfig-gen/meson.build | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/test cases/common/51 pkgconfig-gen/meson.build b/test cases/common/51 pkgconfig-gen/meson.build
index b5f6921..fe99168 100644
--- a/test cases/common/51 pkgconfig-gen/meson.build	
+++ b/test cases/common/51 pkgconfig-gen/meson.build	
@@ -17,3 +17,9 @@ pkgg.generate(
   requires_private : ['gio-2.0', 'gobject-2.0'],
   libraries_private : '-lz',
 )
+
+pkgconfig = find_program('pkg-config')
+test('pkgconfig-validation', pkgconfig,
+  args: ['--validate', 'simple'],
+  env: ['PKG_CONFIG_PATH=' + meson.current_build_dir() + '/meson-private'],
+)
-- 
2.10.0
```

**Comment by arteymix** [comment]
Here's a summary of the changes:

 - remove trailing spaces
 - fix typo for `Library` -> `Libs` and `CFlags` -> `Cflags`
 - add `URL` and `Conflicts`
 - make handling of libraries uniform for `Libs` and `Libs.private`
 - accept strings for `Libs` and `Libs.private`

I also included a validity check from @TingPing which appears to break on AppVeyor.

Feel free to review at this point!

**Comment by TingPing** [comment]
> I also included a validity check from @TingPing which appears to break on AppVeyor.

Probably just put the test in a conditional if not pkgconfig.found().

**Comment by arteymix** [comment]
What is the alternative on Windows for checking dependencies?

It's a bit weird to make `pkg-config` optional inside a pkg-config test.

**Comment by TingPing** [comment]
> What is the alternative on Windows for checking dependencies?

You can use pkg-config on Windows they just need to build it.

**Comment by nirbheek** [comment]
I'd recommend making the test conditional on whether pkg-config was found. Our CI doesn't have `pkg-config`, and we only require it for linuxlike tests.

**Comment by nirbheek** [comment]
Could you please rebase on top of master and push again? There's merge conflicts and the CI failed for some reason.

**Comment by ignatenkobrain** [comment]
@nirbheek rebased ;)

**Comment by nirbheek** [comment]
The test failure is unrelated to your changes. I seen it too on my machine too, sometimes.

**Comment by nirbheek** [comment]
Test failure was a bit involved. Fix is in #897.

**Comment by jpakkane** [comment]
The merged pkgconfig fixes caused conflicts again. :(

**Comment by nirbheek** [comment]
Should probably see the result of #899 before rebasing this because that will cause conflicts again (or just rebase and push this before #899).

**Comment by jpakkane** [comment]
Let's do #899 first. If someone creates a pkg-config MR in the mean time, it will have to wait for this one.

**Comment by jpakkane** [comment]
Now's the time. :)

**Comment by arteymix** [comment]
Ok, everything is rebased now :)

**Pull request merged**
