### PR TITLE
Update one extra use of unversioned python

### PR DESCRIPTION
**Pull request by seb128**
Thanks Stefano Rivera <stefanor@ubuntu.com> for the patch

### CODE REVIEW

**Comment by jpakkane** [comment]
Test failure seems relevant:

```
Program python3 found: YES (/usr/bin/python3)

meson.build:20:2: ERROR: Assert failed: Didn't load python from config file

meson.build:20:2: ERROR: Assert failed: Didn't load python from config file
A full log can be found at /home/runner/work/meson/meson/tmp86r_ijzv/meson-logs/meson-log.txt

Build started at 2020-02-19T08:57:09.509698
```

**Comment by seb128** [comment]
Indeed, a bit weird though, the patch is applied to the ubuntu package and tests are not failing there...

**Comment by LocutusOfBorg** [comment]
looks like #6703 might be the best solution

**Comment by seb128** [comment]
let's close this one then, it needed work anyway

**Pull request closed without merging**
