### PR TITLE
Try #2: De-dup rpath arguments on apple clang

### PR DESCRIPTION
**Pull request by nirbheek**
Continuation of https://github.com/mesonbuild/meson/pull/13819.

CC: @eli-schwartz

### CODE REVIEW

**Comment by nirbheek** [comment]
Basically, this is a more restricted version of the previous PR, and will only de-dup when:

1. There's a comma at the end
2. There's something after the comma

In these cases it is not supposed to (and will not) slurp the next argument. I looked into adding more advanced de-dup that looks at the next argument, but it made argument construction very slow.

**Review by thesamesam — APPROVED** [review]

**Comment by eli-schwartz** [comment]
> I looked into adding more advanced de-dup that looks at the next argument, but it made argument construction very slow.

Yeah that makes sense I guess. Disappointing but hopefully most people are using the version with `,` especially given that was the Apple reproducer. It's definitely better than nothing.

**Comment by nirbheek** [comment]
We can probably make it happen if we rewrite CompilerArgs in C.

**Comment by eli-schwartz** [comment]
I'm not necessarily opposed but it would have to be 100% optional to avoid breaking the use case of running meson directly from the git repository... that might make it less of an interesting change to make. :)

**Pull request merged**
