### PR TITLE
Add preserve_path_from argument when running moc in `headers` mode.

### LINKED ISSUE #10955: Qt compile_moc() doesn't support files with the same name
**Describe the bug**

When using Qt's compile_moc(), files that have the same file name, while being placed in different sub directories in the source tree, produce a configure-time error:

```
ERROR: Multiple producers for Ninja target "app.p/moc_value.cpp". Please rename your targets.
```

or

```
ERROR: Multiple producers for Ninja target "app.p/value.moc". Please rename your targets.
```

depending on whether one is using the `headers` or `sources` keyword argument.

**To Reproduce**

This minimal meson.build file:

```
project('bug', 'cpp')
qt = import('qt6')
app_sources = files('app.cpp')
app_sources += qt.compile_moc(sources: [
    'one/value.h',
    'two/value.h'])
executable('app', sources: app_sources)
```

Files `one/value.h` and `two/value.h` must exist, but can, for this error at configure time, be empty.

**Expected behavior**

There is no technical reason, why this shouldn't work. CMake can do it and a handcrafted Makefile certainly can as well. The moc files need either be placed in separate directories (CMake creates unique build directories for this) and the include paths to these directories have to be provided at compile time. Or the filenames have to be prefixed with the directory ('one_value.moc' / 'two_value.moc'), which seems more mesonic, but creates a problem when you want to include these files again ('#include "one_value.moc"' instead of the canonic '#include "value.moc"' in both files, trusting the include paths to be correct.)

**system parameters**

* Native linux build.
* python 3.10.4
* meson 0.63.2
* ninja 1.10.1

### PR DESCRIPTION
**Pull request by punytroll**
This fixes #10955 partially.

When using the sources kwarg, the moc tool generates .moc files. Those are meant to be #included in a .cpp file, which makes it necessary to add the correct -Ibuild/dir flag to the correct .cpp file compiling command. I'm not sure whether this is wanted or even possible ...

### CODE REVIEW

**Comment by tristan957** [comment]
Would be useful if you edit an existing `compile_moc` test to run into the same issues that you ran into

**Comment by punytroll** [comment]
Hey @tristan957 ,
finally got time to do this. :) I think that would be beneficial; you're right.
Unfortunately I have no clue, where to put the test. It seems `test cases/frameworks/4 qt` is a good place, but there is so much stuff in there. Can I just add a subdirectory with a self-sufficient test case?

**Comment by punytroll** [comment]
OK, I added a test setup. I am not at all happy to restrict the test to Qt 6 but I wouldn't know how else to do it. Also, having this test not as a self-contained entity but as part of this all-encompassing Qt module test is frustrating to say the least. There is no guessing of how much these tests might interact with each other and having some arbitrary directories `one` and `two` in here is confusing for everybody after me. Can this be done any more sensible?

**Comment by tristan957** [comment]
@xclaesse maybe you can provide some testing guidance?

**Comment by punytroll** [comment]
Any further thoughts on this? I'd like to see this functionality added at some point in the future ... :)

**Comment by tristan957** [comment]
@eli-schwartz could you help provide input? Ideally this could go in before 1.0.0 :)

**Comment by punytroll** [comment]
Some time has passed and again, I am in need of this change. Is there something I can do to get this along?

**Comment by tristan957** [comment]
cc @eli-schwartz | @xclaesse. Could we get this in for 1.1.0?

**Comment by bruchar1** [comment]
:+1: I need this feature too.

Would be useful to add this to `compile_resources` and `compile_ui` as well.

I would rather add the `preserve_path_from` to each function, and update documentation accordingly. Will require a release snippet as well.

**Comment by eli-schwartz** [comment]
@punytroll I think maybe this would be much more palatable to you if we just changed the test itself to be parameterized by Qt version using an option plus test.json, rather than doing it in a foreach loop?

Would that be sufficient or do you really desire that it be run as multiple different test case directories each testing one or two things? (I'm not entirely sure I see the necessity of this, but maybe I'm missing something.)

**Pull request closed without merging**
