### PR TITLE
docs: Document buildtarget.get_id() [skip ci]

### PR DESCRIPTION
**Pull request by dcbaker**

### CODE REVIEW

**Comment by jpakkane** [comment]
I feel a bit bad about this one. `get_id` is a poor name, dunno what I was thinking about there. Maybe it was supposed to be only an internal method and not actually exposed to the public (does not make the name any better). Should this be properly hidden instead, I'd imagine most people would use `private_dir_include` instead?

**Comment by dcbaker** [comment]
@jpakkane, someone's using it: https://github.com/mesonbuild/meson/issues/5995

Maybe it would be better to alias it and mark `get_id` as deprecated?

**Comment by marc-hb** [comment]
> @jpakkane, someone's using it: #5995

I'm just evaluating Meson for now, don't count me as an actual user. No one should be using undocumented APIs :-)

BTW using `get_id()` in `configure_file()` is actually harder than I thought *if* you want proper dependencies because of an obvious circular... dependency. I found this hardcoding workaround + mitigation with an `assert`.  Any better idea to break the circular dependency?

```
# Can't call myexe.get_id() yet because myexe doesn't exist yet
myexe_id = 'myexe.elf@exe' #  myexe.get_id()     #    <= circular dependency
# https://github.com/mesonbuild/meson/pull/291
objs_dir = '?'.join(myexe_id.split('@')) + '/'

ld_template = 'template.ld'
ld_script   = 'script.ld'

generated_ld_script = configure_file(
  input: ld_template,
  output: ld_script,
  configuration : { 'OBJSDIR': objs_dir },      #     <= circular dependency
)

myexe = executable(
   'foo.S', 'bar.c',
   ...
   link_args : [ ..., '-Wl,--script=' + ld_script ],
   link_depends: generated_ld_script,          #     <= circular dependency
)

assert(myexe_id == myexe.get_id(),
       'myexe has changed name, you must update myexe_id')
```

template.ld
```
SECTIONS
{
	.text : {
		@OBJSDIR@foo.S.obj(.text)
  ...
```

**Comment by tristan957** [comment]
This seems to have gotten lost in the dust too. What is the status of this method? Does it still exist?

**Comment by tristan957** [comment]
Since it seems like Meson has gone down the "if it isn't documented" it isn't stable route, then we could just close this and maybe remove the method? It isn't clear if that is the path that should be taken or it should simply be renamed.

**Comment by eli-schwartz** [comment]
Was working on that. :P

**Pull request closed without merging**
