### PR TITLE
Do some of the easy type checking of in the interpreter

### PR DESCRIPTION
**Pull request by dcbaker**
This covers most of the functions that are easy to type check.

### CODE REVIEW

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by jpakkane** [comment]
Conflicts again...

**Review by mensinda — APPROVED** [review]
LGTM

**Comment by dcbaker** [comment]
I'd honestly like to wait until after 0.59 is released at this point, rather than risk a regression in the rc.

**Comment by eli-schwartz** [comment]
In commit 6f6db0f2e36c61c309ff8805e0331ec80d807ecd
> interpreter: use typed_pos_args configuration_data

Apparently now the optional dict argument to configuration_data is always there, and the following meson.build triggers an incorrect FeatureNew:

```meson
config = configuration_data()
```

Discovered in wrapdb -> cmocka

```
$ git clone https://github.com/mesonbuild/wrapdb && cd wrapdb && meson setup builddir -Dwraps=cmocka
[...]
cmocka| WARNING: Project targeting '>= 0.48.0' but tried to use feature introduced in '0.49.0': configuration_data dictionary.
[...]
```

**Comment by xclaesse** [comment]
@eli-schwartz @dcbaker https://github.com/mesonbuild/meson/pull/9083.

**Pull request merged**
