### PR TITLE
pkgconfig: add support for extra_cflags

### PR DESCRIPTION
**Pull request by bruce-richardson**
Allow the user to pass in arbitrary cflags for putting into the pkgconfig
file generated.

### CODE REVIEW

**Comment by jpakkane** [comment]
This is good stuff, I'm just wondering if `extra_cflags` is a good name, because it implies C but pkgconfig is language neutral. We also try to consistently use `args` instead of `flags`. So maybe this should be called `extra_compile_args`?

**Comment by nirbheek** [comment]
> This is good stuff, I'm just wondering if extra_cflags is a good name, because it implies C but pkgconfig is language neutral

The field in the pkg-config file is called `Cflags:` so this is the correct terminology, unfortunately. 

Everywhere else in Meson we use 'compile_args`, but since this is an interface that will directly apply to a pkg-config file, I think `extra_cflags` makes more sense and is what the user would expect.

**Comment by bruce-richardson** [comment]
I'm ok with modifying the value name in the patch, but I do agree with @nirbheek that having cflags in the name would improve usability as it maps directly to the relevant field in the .pc file.

**Comment by jpakkane** [comment]
Let's stick with cflags then.

**Pull request merged**
