### PR TITLE
run_command: add env kwarg

### PR DESCRIPTION
**Pull request by jtojnar**
See https://github.com/mesonbuild/meson/issues/2723

### CODE REVIEW

**Comment by jpakkane** [comment]
This is new functionality so it should have a release note snippet. The external commands page should also be updated to mention the new kwarg.

**Comment by jtojnar** [comment]
On the external commands page, should I change the current example, add a new one or just mention the kwarg in a single sentence.

**Comment by jpakkane** [comment]
Add a new example showing how to use the env kwarg while mentioning that it is only available since 0.50.0.

**Comment by jtojnar** [comment]
Updated the docs. Unfortunately, I could not come up with non-synthetic example.

I actually intended to do this only to complement adding `env` kwarg to `run_target` (https://github.com/mesonbuild/meson/issues/2723) and do not really need this. But since that [turned out](https://github.com/mesonbuild/meson/issues/541#issuecomment-221753540) to be non-trivial and I could not deliver it, I am not sure if we should add this.

**Comment by jtojnar** [comment]
Also the External commands page lacks the `check` kwarg example.

**Pull request merged**
