### PR TITLE
Support additional search paths in find_program

### PR DESCRIPTION
**Pull request by xedrac**
Sometimes you need to search for a program or script that is not located in your top-level source directory, or build directory.

### CODE REVIEW

**Comment by xedrac** [comment]
It appears my added test case is failing when run via 'run_tests.py', with the error "Reason: Generating the build system failed."  Interestingly, when I build the test case directly, it doesn't complain.

**Comment by QuLogic** [comment]
Meson is not run from the test case directory, so `scripts` is not in the current directory and thus not in the search path.

**Comment by jpakkane** [comment]
Thinking about this further, we already changed the search behaviour recently to take multiple names and paths. Thus you should be able to do this:

    find_program(join_paths(meson.current_build_dir(), 'fooprog')

**Comment by xedrac** [comment]
Using join_paths() does appear to work, although I think the syntax is not nearly as readable.  What do you think about modifying my patch to use join_paths() internally so that the interface can just use a kwarg?

**Comment by xedrac** [comment]
I modified the patch to emulate join_path() internally.  While this does make the interface unquestionably cleaner IMO, it does have the potential downside of looking in paths that were never really intended.  For example:

`find_program('one.py', 'two.py', search_paths : 'scripts')`

If I know that 'one.py' exists in the current source dir, but 'two.py' only exists in the 'scripts' dir, then we have the unfortunate side-effect of first searching for 'two.py' in the current source dir.

Personally I find this acceptable, but I understand if you do not.

**Comment by jpakkane** [comment]
From IRC:

    11:57 < nirbheek> __tim, find_program('/sbin/prog', '/bin/prog', '/opt/foo/bar/prog')
    11:57 < nirbheek> It was decided that adding a kwarg to search in some dirs doesn't really improve upon that
    11:58 < nirbheek> Because, for instance, you would have to decide which basenames to check in the dirs (all of them? isn't that a 
                      waste?), etc
    11:58 < nirbheek> It's perhaps more obvious to just specify a list of all places where it could be
    11:58 < nirbheek> And names

**Comment by jpakkane** [comment]
The method discussed above seems to be the consensus on how to do this. If someone feels very strongly against that, please speak up now. If no points are raised I'll close this in a day or two.

**Comment by tp-m** [comment]
I'm happy with the approach suggested by nirbheek, it just didn't occur to me :)

**Comment by nirbheek** [comment]
Closing, then. Do tell us if the existing method doesn't work for you, @xedrac.

**Pull request closed without merging**
