### PR TITLE
VS backends can read platform toolsets from environment

### PR DESCRIPTION
**Pull request by xarkes**
I added this feature because having hardcoded PlatformToolset is very uncomfortable for my projects.

### CODE REVIEW

**Comment by xarkes** [comment]
I think https://github.com/mesonbuild/meson/issues/429 is related to this. I used environment because it is a simple and efficient way of doing it.

**Comment by jpakkane** [comment]
Is `PlatformToolset` set by the MSVC compiler environment and is it guaranteed to be always defined?

**Comment by xarkes** [comment]
Not at all, this is just a custome environment variable I added so I can choose which Platform Toolset I want to use. Anyway if it is not defined, it provides the default value as before.

**Comment by jpakkane** [comment]
In Meson we avoid environment variables as much as possible. They are unexpected hidden state that cause hard to debug problems when things go wrong. Whatever the underlying issue is, it needs to be fixed properly.

**Comment by xarkes** [comment]
I understand this but I don't understand why instead of giving an alternative to environment variables (which as I said in my first comment, I made this choice without any specific reason) you are closing this pull request.

**Comment by jpakkane** [comment]
This feature obviously needs more thinking. I'm currently doing (late-)spring cleaning of the MR page and closing all those issues that are lingering or require a lot of work, because the amount of open MRs has grown too large to be manageable.

**Pull request closed without merging**
