### PR TITLE
rust: Generate a rust-project.json file when rust targets are present

### PR DESCRIPTION
**Pull request by dcbaker**
When at least one Rust target is present, we now generate a
rust-project.json file, which can be consumed by rust-analyzer. This is
placed in the build directory, and the editor must be configured to look
for this (as it is not a default search path).

Fixes: #10678

### CODE REVIEW

**Comment by dcbaker** [comment]
I would really appreciate if someone could test this, as my distro (nixos) requires some hackery to work, since the source is not installed in the sys_root, but in a separate folder.

**Comment by karolherbst** [comment]
Tried that out locally with vscode and rust-analyzer and it seems to work fine.

Just requires a `"rust-analyzer.linkedProjects": [ "build_code/rust-project.json" ]` added to the workspace settings, which I hope we can do automatically with the meson extension.

**Comment by LingMan** [comment]
Looks good here, too. Code completion, jumping to definitions, finding references, showing inline type annotations. All works.

You already know this, but for the record: Compilation errors and warnings are not shown with this yet, since calls to `cargo check` are disabled when a rust-project.json is given. Theoretically a custom command can be provided by adding `"rust-analyzer.checkOnSave.overrideCommand": ["cargo", "check", "--message-format=json"]` to the workspace settings , but so far the right invocation elides me.

**Comment by dcbaker** [comment]
I think `rustc —error-format=json -o /dev/null` will give the right errors, but cargo check also doesn’t do any codegen, and I haven’t figured out how to do that yet

**Comment by LingMan** [comment]
The difference between `cargo check` and `cargo build` appears to be `--emit=dep-info,metadata` vs `--emit=dep-info,metadata,link`.
If you pass `-v` to cargo, it prints the exact rustc commands it runs.

**Comment by dcbaker** [comment]
Excellent, thanks. I think I'm going to add code to the vscode-meson extension to offer to set some of these options for you

**Review by eli-schwartz — APPROVED** [review]

**Pull request merged**
