### PR TITLE
Add a new 'environment' object to be used to build test environment

### PR DESCRIPTION
**Pull request by thiblahute**
Allowing user to extend an existing path instead of overriding it

### CODE REVIEW

**Comment by jpakkane** [comment]
This needs better tests. At least:

 - test that `@@FOO@@` reads back as `@FOO@` rather than get expanded
 - test that expand actually works for a different varname, eg `FOO=@PATH@` and check that these are equivaelnt
 - tests that expand works in the same variable, `PATH=@PATH@:somesuffix` should contain both pieces (what to append to `PATH` does not matter because the test app does not need to invoke anything)

**Comment by jpakkane** [comment]
It turns out we need to support extending even when the original variable is empty. That is extending the empty variable with `foo` should result in `foo` and not `:foo`.

There does not seem to be a simple expansion syntax for this. How about something like this then:

    e = environment()
    e.set('BAZ', 'somevalue')
    e.append('FOO', value='suffix', separator=':') # if FOO=bob then => bob:suffix
    e.prepend('BAR' value='prefix', separator=':') # if BAR is empty then => prefix
    test(..., env : e)

**Comment by tp-m** [comment]
While we're at it, how about an `e.get('BAZ')` as well? Could be useful for e.g. printing messages like with what PKG_CONFIG_PATH it was called and such.

**Comment by thiblahute** [comment]
I went with:

```
e = environment()
e.set('BAZ', 'somevalue')
e.append('FOO', 'suffix', 'suffix1', separator=':') # if FOO=bob then => bob:suffix
e.prepend('BAR', 'prefix', separator=':') # if BAR is empty then => prefix
e.prepend('PATH', '/new/path') # separator defaults to os.pathsep
test(..., env : e)
```

**Comment by thiblahute** [comment]
> While we're at it, how about an e.get('BAZ') as well? Could be useful for e.g. printing messages like with what PKG_CONFIG_PATH it was called and such.

I think it would rather be meson.get_environ('BAZ') so not really related.

**Comment by jpakkane** [comment]
If I read this correctly, the environment variable expansion is done during Meson runtime and the operation unsets every envvar that is not in the list. We should do the expansion at test runtime instead and preserve all envvars that are not specifically listed (which e.g. clobbers `PATH` which we definitely don't want). People may want to run tests with different envvars on during debugging (such as adding more logging or the like). We also need to expose this information in `mesonintrospect` so IDEs and the like can replicate.

`EnvironmentVariables` should then become a class that just stores these operations in an array and does not deal with kwargs, but takes the separator directly.

For simplicity and backwards compatibilty, we should probably still accept an array of strings to env and convert it to an object on the fly.

**Comment by thiblahute** [comment]
The expension is done [at test time](https://github.com/mesonbuild/meson/pull/781/commits/612c687eceb2551d3b7d9e124748c592638dc4ff#diff-ac6e294be7e5b8c11d8b551e96fae7b6R132)

> EnvironmentVariables should then become a class that just stores these operations in an array and does not deal with kwargs, but takes the separator directly.

This is what I am doing, though I store it in tuples of the form `(operation_method, name, values, extra_args)`

> For simplicity and backwards compatibilty, we should probably still accept an array of strings to env and convert it to an object on the fly.

It is still supported and tested.

**Comment by thiblahute** [comment]
And about `mesonintrospect` test.env will be a `EnvironmentVariables` object if it is what the user used and it will the be able to retrieve the env as a dict as user was expecting doing `env.get_env()` maybe not the best naming though.

**Comment by jpakkane** [comment]
Argh, I missed the `child_env.update`, of course it works just fine.

The format of any `mesonintrospect` output is not really finalised (or even close) yet because there are no users yet. I hope to hammer them out next week at LAS with Christian.

**Comment by jpakkane** [comment]
One minor thing, `get_value` should verify that `separator` is a string. `@stringargs` only checks positional arguments.

**Comment by thiblahute** [comment]
> One minor thing, get_value should verify that separator is a string. @stringargs only checks positional arguments.

Done

**Pull request merged**
