### PR TITLE
Add MicroBlaze CPU family

### PR DESCRIPTION
**Pull request by nathanrossi**
Add the CPU family for the MicroBlaze processor.

### CODE REVIEW

**Comment by scivision** [comment]
Thanks! A couple curious questions to help others understand if they run into a future limitation (if you know offhand--thanks!):

* were you running Python on the MicroBlaze soft CPU or cross-compiling for MIcroBlaze?
* If Python was on MicroBlaze, what version was it (e.g. 3.5 or ?)

**Comment by nathanrossi** [comment]
I have been cross compiling for MicroBlaze. Though very slow native execution with QEMU does work, tested with python 3.7.4 (using an OpenEmbedded built toolchain/distro).

**Comment by scivision** [comment]
@jpakkane is there anything you'd like to see before merging?

**Comment by jpakkane** [comment]
Are all Microblaze processors the same, or are there variants like 32/64 or similar to `armv7hle` et al?

**Comment by nathanrossi** [comment]
@jpakkane MicroBlaze has a variety of configuration options that enable instructions as well as 32/64 bit (though 64-bit support is not in upstream gcc). There are no pre-configured options/tunes like `armv7hle` due to the scope of configuration (>12 versions, 10 options, >12000 variants). All processor configuration options are expected to be provided by the user since the user has full control of the configuration for synthesis on the FPGA. Currently with meson this is done by passing the options using `--cross-file` with values set for `c`, `c_args`, etc.

**Comment by jpakkane** [comment]
We make a separation between 32 and 64 bith processors, as you can see in the table. Thus we should have separate values for those, such as `microblaze32` and `microblaze64` or `microblaze` and `microblaze64`. The exact value depends on how upstream wants to name things.

If 64 Microblaze processors do not yet exist we don't have to add them, but our choice of names should be ready for when those will appear.

**Comment by nathanrossi** [comment]
@jpakkane I think following the same convention as other processors have done when 64-bit was added later makes sense (e.g. `microblaze` and `microblaze64`). There does not appear to be any changes in any upstream projects (gcc, glibc, etc.) yet for 64-bit MicroBlaze, however Xilinx does have some custom patches for gcc (https://github.com/Xilinx/meta-xilinx/blob/master/meta-xilinx-bsp/recipes-microblaze/gcc/gcc-8/0041-Intial-commit-for-64bit-MB-sources.patch#L55) which indicates the intention to use `microblaze64` whilst leaving `microblaze` as is for 32-bit.

**Pull request merged**
