### PR TITLE
Only add build dir inlude directives if the corresponding dir exists.

### LINKED ISSUE #1185: Compilation error when using include_directories() object in subdirectory
In the setup, which uses '-Wmissing-include-dirs' together with '-Werror' treating all warnings as errors gcc compiler returns an error. Here is the simplified example:
git@bitbucket.org:adel-mamin/meson-test.git
If I compile it with gcc I get the following error:
> ninja
[1/5] Compiling c object 'subdir/liba@sha/a.c.o'
FAILED: subdir/liba@sha/a.c.o
cc  '-Isubdir/liba@sha' '-Isubdir' '-I../subdir' '-Iinclude' '-I../include' '-pipe' '-Wall' '-Winvalid-pch' '-Wmissing-include-dirs' '-Werror' '-O0' '-g' '-fPIC' '-MMD' '-MQ' 'subdir/liba@sha/a.c.o' '-MF' 'subdir/liba@sha/a.c.o.d' -o 'subdir/liba@sha/a.c.o' -c ../subdir/a.c
cc1: error: include: No such file or directory [-Werror]
cc1: all warnings being treated as errors
[2/5] Compiling c object 'mytest@exe/main.c.o'
ninja: build stopped: subcommand failed.

### PR DESCRIPTION
**Pull request by jpakkane**
Closes #1185.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
it fixes bug described in #1185

**Comment by nirbheek** [comment]
Need a test for this so we don't accidentally break it again. The original bug already contains such a test case.

**Comment by jpakkane** [comment]
Error is unrelated but why does it only happen in this MR?

**Comment by nirbheek** [comment]
What error is that?

**Comment by ignatenkobrain** [comment]
@jpakkane, which error?

**Comment by jpakkane** [comment]
NM, this page had not updated itself properly.

**Pull request merged**
