### PR TITLE
path() vs full_path() method

### LINKED ISSUE #6375: Suggested improvement: change external program object
Meson 0.52.999

The [external program object](https://mesonbuild.com/Reference-manual.html#external-program-object) has method `path()`. But build object and custom target object have a `full_path()` method. This caused me a momentary, "WTF?", when I ran an experiment that substituted the object returned by `executable()` with one returned by `find_program()` because this line failed:

```
shell_var = 'SHELL=' + ksh.full_path()
```

I propose adding a `full_path()` method to an external program object and deprecating the existing `path()` method. Also, including an example, like that above, for one situation where invoking `full_path()` or `path()` would be necessary. That, however, raises an interesting question. Should those objects have a `__str__()` method that simply defers to `full_path()` so that the explicit method call can be elided?

I've had three commits merged and would be happy to implement this idea if the core dev team thinks the unification of those three objects has merit.

### PR DESCRIPTION
**Pull request by krader1961**
I'm happy to also add a commit that explicitly issues a deprecation warning if the `full_path()` method is used. Conversely, the docs could simply document it is an alias of `path()` without the deprecation warning if the Meson devs feel that `full_path()` can never be removed but still value consistency among the three object types.

Resolves #6375

### CODE REVIEW

**Comment by krader1961** [comment]
Thanks, @eli-schwartz, for implementing a variation of my change and closing/rejecting my pull-request. One of the things that drives me crazy is seeing open pull-requests that are more than a year old.  Please deal with all the other ancient P.R.s  that are unlikely to merge cleanly and given their age are likely irrelevant. IMHO, far too many people create a P.R. before there is a reasonable discussion about the merits of their proposed change. Which might include my P.R. to resolve issue #6375.

**Comment by eli-schwartz** [comment]
I semi-regularly go through old issues and PRs, trying to figure out whether they are still relevant and closing them if possible. :)

Unfortunately, it's not always immediately apparent... and for issues that were never resolved, even if a PR is very old and can't merge cleanly I hesitate to close it since it still acts as documentation of a change that is wanted. In theory they could still be picked up and rebased with some pain (and on rare occasions this even works out).

In this case someone else (not me) fixed the same issue but without realizing there was a related PR already open, which is something that in a perfect world would have been referenced from the start.

**Comment by eli-schwartz** [comment]
Actually I thought this PR would have been a decent change if it had been reviewed at the time you submitted it, but apparently it got overlooked and dated. :( I only joined the project since then, but that's something I'd like to see happen less often (ideally never).

**Comment by krader1961** [comment]
> for issues that were never resolved, even if a PR is very old and can't merge cleanly I hesitate to close it since it still acts as documentation of a change that is wanted.

I'm a grey beard who earned my first programming paycheck in 1979 so there may be something of a "get off my lawn" feel to my comments. Nonetheless, a pull-request more than a year old in any project I've ever contributed to should be summarily closed in my opinion. If there is value in the PR it is presumably linked to, and otherwise extensively discussed, in an open issue. I have never seen a pull-request more than a year old that should be merged. And that includes this PR that I opened. It was apparently not merged because there is a significant backlog of PR's that need triage.

**Pull request closed without merging**
