### PR TITLE
Shaderc pkg config

### PR DESCRIPTION
**Pull request by dcbaker**
Shaderc finally added pkg-config files. This patch makes pkg-config the primary way to find shaderc, and smooths out the oddities of the way they've done their pkg-config files.

### CODE REVIEW

**Comment by dcbaker** [comment]
@Akaricchi

**Comment by Akaricchi** [comment]
Yeah I saw the commit. I was planning to do the PR myself, but I had to go vent off some rage and frustration after seeing **three** .pc files in there and the following remark:
>Extracts the current version from the file CHANGES

I think Meson should try to query all of the possible pkg-config names, prioritizing the static ones if `static` is true and the shared one otherwise, and vise versa. With all the other dependencies (at least those that use pkg-config and aren't maintained by CMake/Windows idiots), `static` acts as a hint, not an order. I think it's important to stay consistent with those semantics. Many distributions do not package static libraries, and in some environments *only* the static library will be available (MXE `-static` targets, my Taisei cross toolchains...).

My 'system' method for shaderc already handles that. I'm willing to write the pkg-config logic too if you approve.

**Comment by dcbaker** [comment]
Is static just a hint? internally we have four different levels, "must be static", "prefer static", "prefer shared", "must be shared". It would be really nice if we could expose those externally.

At least they did what I asked and called the shared one `shaderc`, which will do the right thing in 99% of cases on Linux and *BSD.

**Comment by Akaricchi** [comment]
>Is static just a hint?

At least with pkg-config based dependencies, yes. Here's what happens if you pass `static : true` when the system only has shared libraries:

```
Found pkg-config: /usr/bin/pkg-config (0.29.2)
WARNING: Static library 'freetype' not found for dependency 'freetype2', may not be statically linked
WARNING: Static library 'bz2' not found for dependency 'freetype2', may not be statically linked
Dependency freetype2 found: YES 22.1.16
WARNING: Static library 'png16' not found for dependency 'libpng', may not be statically linked
Dependency libpng found: YES 1.6.36
WARNING: Static library 'SDL2' not found for dependency 'sdl2', may not be statically linked
WARNING: Static library 'asound' not found for dependency 'sdl2', may not be statically linked
WARNING: Static library 'ts' not found for dependency 'sdl2', may not be statically linked
Dependency sdl2 found: YES 2.0.9
WARNING: Static library 'SDL2_mixer' not found for dependency 'SDL2_mixer', may not be statically linked
WARNING: Static library 'SDL2' not found for dependency 'SDL2_mixer', may not be statically linked
WARNING: Static library 'asound' not found for dependency 'SDL2_mixer', may not be statically linked
WARNING: Static library 'ts' not found for dependency 'SDL2_mixer', may not be statically linked
Dependency sdl2_mixer found: YES 2.0.4
WARNING: Static library 'webp' not found for dependency 'libwebp', may not be statically linked
Dependency libwebp found: YES 1.0.0
WARNING: Static library 'webpdecoder' not found for dependency 'libwebpdecoder', may not be statically linked
Dependency libwebpdecoder found: YES 1.0.0
Dependency zlib found: YES 1.2.11
WARNING: Static library 'zip' not found for dependency 'libzip', may not be statically linked
WARNING: Static library 'bz2' not found for dependency 'libzip', may not be statically linked
Dependency libzip found: YES 1.5.2
WARNING: Static library 'crypto' not found for dependency 'libcrypto', may not be statically linked
Dependency libcrypto found: YES 1.1.0h
```

>internally we have four different levels, "must be static", "prefer static", "prefer shared", "must be shared". It would be really nice if we could expose those externally.

Agreed, but that is obviously out of scope right now. The existing convention should be followed until something better is implemented.

>At least they did what I asked and called the shared one shaderc, which will do the right thing in 99% of cases on Linux and *BSD.

In native builds, yes, but it won't do the right thing with all of my static-only cross toolchains.

**Comment by Akaricchi** [comment]
I also just realized that the behavior might be somewhat broken there, because it will attempt to link to the private libraries despite the warnings. So if the corresponding shared library is also missing, linking will fail. I just had an odd case where SDL2 pulled in `libts` via `Libs.private`, and for some reason, my system was missing the `libts.so` symlink. So `-lts` would not work, even though the SDL2 shared library works, because it's linked to the fully qualified soname. This probably warrants a separate issue.

**Comment by jpakkane** [comment]
Is this good enough to merge or are there still things that need fixing?

**Comment by dcbaker** [comment]
@Akaricchi, does this look more like what you were hoping to see?

**Comment by Akaricchi** [comment]
@dcbaker, I would reorder the list as `['shaderc', 'shaderc_static', 'shaderc_combined']`, and then instead of `c.reverse()` use `c.append(c.pop(0))` to move `shaderc` to the last place in the static linking case. This way `shaderc_static`  will be always preferred over `shaderc_combined` for consistency. But other than that it looks good. Really sorry that we've got to deal with this braindeath :/

**Comment by dcbaker** [comment]
Yeah, I've replaced the logic so that shared is shared, combined, static; and static is combined, static, shared

**Pull request merged**
