### PR TITLE
Fix meson dist with relative submodule URLs

### PR DESCRIPTION
**Pull request by drobilla**
See the last commit message for details.

### CODE REVIEW

**Comment by drobilla** [comment]
I'm not sure what makes sense with submodules in the grand scheme of things, this just seemed like an outright bug that could be fixed, so I tried to make it work.

From a user perspective one thing that still seems odd about this is that, if you have subprojects as submodules, they will be included in the archive unconditionally.  One might want to exclude them and rely on wrap files to fetch things for users if they need them, but `meson dist` has no option for this.  Though `--include-subprojects` is somehow in a similar vein... submodules aren't necessarily subprojects.  🤷

**Comment by eli-schwartz** [comment]
Great work! The overall approach seems sane here, and the first two commits especially seem good to have anyway so thank you for factoring out each discrete change into its own commit.

> From a user perspective one thing that still seems odd about this is that, if you have subprojects as submodules, they will be included in the archive unconditionally. One might want to exclude them and rely on wrap files to fetch things for users if they need them, but `meson dist` has no option for this. Though `--include-subprojects` is somehow in a similar vein... submodules aren't necessarily subprojects. shrug

Shower thoughts here (literally, actually) as I don't have much time today:

Maybe we could compare each submodule and, if it is in the subprojects directory and has an associated wrap file, ignore it by default, unless `--include-subprojects` is used?

This seems like an additional change, above and beyond "fix relative urls", so it's okay to not fix it right now. :D

**Comment by drobilla** [comment]
> Maybe we could compare each submodule and, if it is in the subprojects directory and has an associated wrap file, ignore it by default, unless --include-subprojects is used?

Hmm, good idea.  Seems like that would cover most of what people might want to do, without really breaking anything or adding new options.  I'll have a go.

**Comment by eli-schwartz** [comment]
I completely forgot all about this PR. :D Meanwhile, I ended up taking a completely different approach to completely rewriting `meson dist` in #9210 

My rewrite uses git archive and assumes you have inited the submodule yourself in the actual project tree, so it doesn't need to rewrite .gitmodules -- it is also marked as fixing #8144 which this PR would have fixed too, I guess.

I'm going to close this PR since the thing it is solving is solved a different way, but 

> Maybe we could compare each submodule and, if it is in the subprojects directory and has an associated wrap file, ignore it by default, unless `--include-subprojects` is used?

This is welcome to receive a new PR.

**Comment by drobilla** [comment]
Heh, no worries, me too (or at least it was on a back burner).  Not needing to rewrite .gitmodules is nice.  I'll revisit this on the node with my project structure soonish.

**Pull request closed without merging**
