### PR TITLE
Add string.parse_json method and a "dictionary" type

### PR DESCRIPTION
**Pull request by kshpytsya**
Intended to provide a convenient way to retrieve complex information from external sources, such as e.g. `run_command(...).stdout()`.

### CODE REVIEW

**Comment by tp-m** [comment]
Out of curiosity: what do you need this for, how do you use it?

**Comment by jpakkane** [comment]
All new core functionality must have a strong use case behind it. What are you trying to achieve with this, specifically?

**Comment by kshpytsya** [comment]
@jpakkane This is partially related to my comment/question [here](https://github.com/mesonbuild/meson/pull/1278#issuecomment-271326461). I saw your reply there and I am well aware of the constraint of not making meson a Turing complete language.
It is hard to add anything other than restating my initial pull request comment.
Of course, one can use "string.split()" and pray that delimiter character is chosen properly and indexes in the sequence expected by the meson part and producer counterpart are kept in sync. But I believe dictionaries are less error prone and more human-friendly.

**Comment by jpakkane** [comment]
But what do you want to _do_ with the JSON dicts? What specific problem do you have and why have you chosen this specific approach to solve it?

**Pull request closed without merging**
