### PR TITLE
devenv: various improvements

### PR DESCRIPTION
**Pull request by xclaesse**
commit 9f7ce6aff2e17ba320015faffbb2f536f62cf458 (HEAD -> devenv)

    devenv: Always include env for HOST machine
    
    Cross compiled executables could still be run with an exe wrapper, or
    with proper binfmt installed.
    
    Fixes: #10999

commit 675baa28371f0c3b5106f7d6c952d47e88aa7fc8

    devenv: Add executables locations to both PATH and WINEPATH
    
    Handles the case when wine-binfmt is installed, which makes .exe files
    executable without without specifying an exe wrapper.

commit c7c7af30ac91c72086d7591ec295c044e5c58825

    devenv: Do not include system values in --dump
    
    This makes --dump print variables like `FOO=/path:$FOO:/another/path`.

commit a53d1640b3f68c51968067be300e10bc158b9699

    devenv: Add more info how to get gdb scripts working
    
    Now that top builddir is not the default workdir any more, the .gdbinit
    file we write there won't be loaded automatically unless user cd there,
    or use --init-command. There is also a global setting that user has to
    set to allow automatically loading .gdbinit file.

commit 8e20ba6ee46a2129d06c34d46672e0c000df8e18

    devenv: Add --workdir option
    
    Most of the time it is preferable to remain the the top source dir
    instead of going into the builddir. Add --workdir argument to be able to
    have a different workdir than builddir, but keep it default to builddir
    for backward compatibility, and also because it makes gdb integration
    better.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
It's not clear to me that this change is a good thing. For example, I've in the past used devenv to make `ninja` work without options as well as to actually run the results.

Also, the fact that it breaks seamless gdb integration? seems like a good indicator that this breaks some workflows.

Assuming this PR is accepted, it definitely needs to have a release notes snippet.

**Comment by tristan957** [comment]
What is the gdb integration that breaks?

**Comment by xclaesse** [comment]
@eli-schwartz For context, GStreamer has gst-env.py script (on which meson devenv is based) but they have sourcedir as workdir by default. They would like to slowly migrate to "meson devenv" by making gst-env a small wrapper script on top of meson devenv, but they would need to be able to change workdir back to sourcedir for compat. So changing the default is not really important actually, as long as we have an option.

**Comment by xclaesse** [comment]
> What is the gdb integration that breaks?

When your project contains gdb scripts, meson devenv writes a `.gdbinit` file at the root of your builddir that config paths to automatically load all those gdb scripts. But gdb autoload that .gdbinit by default only if it's in the current workdir.

**Comment by ndufresne** [comment]
@xclaesse quick correction, perhaps just a typo, but we have "current dir" maintained, and not the sourcedir as you stated. In general, gst-env.py (which is what we try and replace with meson devenv) is used in script like:

```
./get-env.py <some-commend>
```

About the new option `-w/--workdir`, how do I tell it to use the current dir ? Do I need to pass `.` or something ?

**Comment by xclaesse** [comment]
> we have "current dir" maintained, and not the sourcedir as you stated

Most of the time that would be the same dir, but not always indeed.

> About the new option `-w/--workdir`, how do I tell it to use the current dir ? Do I need to pass `.` or something ?

Yes, `--workdir .` maintains current dir.

**Comment by ndufresne** [comment]
By the way, the GDB integration does not work on Fedora:

```
warning: File "/home/nicolas/Sources/gstreamer/build/.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/lib/golang/src/runtime/runtime-gdb.py".
```

**Comment by xclaesse** [comment]
@ndufresne you need to add `add-auto-load-safe-path /path/to/gstreamer/builddir` in your `~/.gdbinit`. This PR adds a message that tells you that, otherwise it's not easy to discover.

**Comment by xclaesse** [comment]
@ndufresne added a fix for https://github.com/mesonbuild/meson/issues/10999, can you give it a try please?

**Comment by xclaesse** [comment]
Updated this PR to allow running devenv when cross compiling, tested that is works when cross compiling for aarch64 on my Ubuntu laptop with qemu installed. qemu binfmt magic happens and executables can be run transparently. I just have to do `export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu` manually, but I don't think that's something Meson can guess itself.

**Comment by ndufresne** [comment]
I just tested, the workdir part works very well. The env now contains LD_LIBRARY_PATH, so the dump can be used on target for me (I'm using NFS for the target). The only thing that does not works out of the box for me is the binfmt. This is because my binfmt setup is not aware of my rootfs (I got multiple rootfs, so its not really feasible). The fix is extremely simple, I just need to:

```
QEMU_LD_PREFIX=/srv/nfs/renegade
```

And the problem is solved. Note that this path is (and I think will always be) the value of sys_root = '/srv/nfs/renegade' in my cross file.

**Comment by ndufresne** [comment]
With this working though, I see a lot of cool things we could do now, since we could cross-build gobject introspection, hotdoc, etc.

**Comment by xclaesse** [comment]
> Note that this path is (and I think will always be) the value of sys_root = '/srv/nfs/renegade' in my cross file.

Do you think we should always set `QEMU_LD_PREFIX` to sys_root from cross file, or is that something specific to your setup? Seems to make sense to have it by default.

**Comment by ndufresne** [comment]
I'm not like 100% confident, but I think it is the right thing to do for most cases, its also not a path, so its very easy to override if needed.

**Comment by ndufresne** [comment]
In theory, I think during compilation, the linker do receive that path, and it really means the same thing as when you want to resolve at the run-time.

**Comment by xclaesse** [comment]
> In theory, I think during compilation, the linker do receive that path, and it really means the same thing as when you want to resolve at the run-time.

I think currently Meson only use that for setting `PKG_CONFIG_SYSROOT_DIR`, it is not given to compiler/linker unless you add `--sysroot=/path` to your `c_args` and/or `c_link_args`. But I think you're right it's a nice usage of that property.

**Comment by ndufresne** [comment]
The last updated:
```
[nicolas@whitebuilder gstreamer]$ meson devenv -C build/ --workdir .
Traceback (most recent call last):
  File "/home/nicolas/Sources/meson/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/home/nicolas/Sources/meson/mesonbuild/mdevenv.py", line 162, in run
    cmd = ' '.join(exe_wrapper.get_command())
AttributeError: 'NoneType' object has no attribute 'get_command'

ERROR: Unhandled python exception
```

**Comment by ndufresne** [comment]
> 

```diff
diff --git a/mesonbuild/mdevenv.py b/mesonbuild/mdevenv.py
index 9e53eb851..de87190c5 100644
--- a/mesonbuild/mdevenv.py
+++ b/mesonbuild/mdevenv.py
@@ -159,9 +159,10 @@ def run(options: argparse.Namespace) -> int:
     if b.environment.need_exe_wrapper():
         m = 'An executable wrapper could be required'
         exe_wrapper = b.environment.get_exe_wrapper()
-        cmd = ' '.join(exe_wrapper.get_command())
-        if cmd:
-            m += f': {cmd}'
+        if exe_wrapper:
+            cmd = ' '.join(exe_wrapper.get_command())
+            if cmd:
+                m += f': {cmd}'
         mlog.log(m)
 
     install_data = minstall.load_install_data(str(privatedir / 'install.dat'))
```

**Comment by ndufresne** [comment]
Another one, if I don't pass the builddir:

```
meson devenv 
Traceback (most recent call last):
  File "/home/nicolas/Sources/meson/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/home/nicolas/Sources/meson/mesonbuild/mdevenv.py", line 143, in run
    privatedir = Path(options.builddir) / 'meson-private'
  File "/usr/lib64/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib64/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by xclaesse** [comment]
Fixed both issues.

**Comment by ndufresne** [comment]
Sorry for the long delay, some more round of testing. The latest version uses single quote, which prevents bash from interpreting the env in the path used to append. If I edit the dump to use double quote, then it works as expected.

**Pull request merged**
