### PR TITLE
 Add support for uic_extra_arguments to qt5

### LINKED ISSUE #4177: Add support for ui_extra_arguments to qt5
Just like https://github.com/mesonbuild/meson/pull/2529 adds moc_extra_arguments, ui_extra_arguments would be useful to override translator function (hello gettext/i18n).

### PR DESCRIPTION
**Pull request by Salamandar**
Just like https://github.com/mesonbuild/meson/pull/2529 adds moc_extra_arguments, ui_extra_arguments would be useful to override translator function (hello gettext/i18n).

Will close #4177

### CODE REVIEW

**Comment by jpakkane** [comment]
The Qt5 module documentation page needs to be updated as well.

**Comment by jpakkane** [comment]
ping

**Comment by Salamandar** [comment]
Will do tomorrow !

**Comment by Salamandar** [comment]
I rebased to have a cleaner history, sorry for the inconvenience.

**Pull request merged**
