### PR TITLE
Drop emacs meson-mode

### PR DESCRIPTION
**Pull request by elmarco**
The one on MELPA is way more advanced: https://melpa.org/#/meson-mode
https://github.com/wentasah/meson-mode

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Would it be worth merging improvements instead?

**Comment by elmarco** [comment]
> Would it be worth merging improvements instead?

Merging isn't really the appropriate word here, it's a very different best.

@wentasah would you like to move the emacs mode maintainance back to meson project?

**Comment by dcbaker** [comment]
I think this is the right thing to do even if we were to move the meson-mode code into the meson project. If we move it back it should probably be treated like the vscode extension and live in its own repo under the project.

**Review by dcbaker — APPROVED** [review]

**Comment by wentasah** [comment]
> @wentasah would you like to move the emacs mode maintainance back to meson project?

Hi, I wouldn't mind moving meson-mode under the mesonbuild organization. In the best case, it will get more visibility and attract more contributions. In the worst case, it will stay the same as now. Is there anything that must be changed for this move to happen, e.g. licensing, maintenance process, etc.?

**Comment by dcbaker** [comment]
Up to @jpakkane  on that, but I’ve done the transfer before and can help with that process if we decide to do it

**Pull request merged**
