### PR TITLE
envconfig: Add MicroBlaze CPU family

### PR DESCRIPTION
**Pull request by jae1leegmail**
Add the CPU family for the MicroBlaze processor.

Signed-off-by: Nathan Rossi <nathan@nathanrossi.com>

### CODE REVIEW

**Comment by scivision** [comment]
It looks like you're wanting to merge into 0.51.x but I don't believe any more 0.51.x releases are planned @jpakkane ?

**Comment by scivision** [comment]
It looks like you're wanting to merge into 0.51.x but I don't believe any more 0.51.x releases are planned @jpakkane ? This was merged in master in #5938

**Comment by jpakkane** [comment]
That is correct. Closing. Thanks.

**Comment by jae1leegmail** [comment]
ah ok thanks for the reply

**Pull request closed without merging**
