### PR TITLE
WIP: add project and global arguments to swift compile

### PR DESCRIPTION
**Pull request by glslang**
Hi,

This is more of a feature request with code. I'm trying to get an equivalent of the test in this PR to work.
It's a bit like the mixed test but with a modulemap.

All is required is to pass extra '-I' and '-L' to swift compiler.

ATM the swift target ignores include_directories/dependencies passed to the executable function so it's not really possible to pass includes from a dependency.

The modulemap can be from an external library so it's not always an option to pass the include file into executable as the 5 mixed test does.

This PR simply adds project and global arguments to the compile line and that can be anything accepted for swiftc.

Either way hopefully the test demonstrates the issue.

### CODE REVIEW

**Comment by jpakkane** [comment]
> ATM the swift target ignores include_directories/dependencies passed to the executable function

Then this is an actual bug, which needs to be fixed properly.

Having to do something like this:

> add_project_arguments(['-I' + meson.source_root()], language : 'swift')

is just plain wrong and a terrible user experience.

**Comment by glslang** [comment]
I do agree that is not very good although to make it comparable with the C/C++ backend generation, global and local arguments probably need to be supported as well. If nothing else swift compiler has a few many options.

The problem is that swift/rust and other targets appear to ignore dependencies for the ninja backend and I don't know if there's a reason for that.

I'm quite happy to give a go at making swift target comparable to C/C++ in terms of handling dependencies and so on but since it doesn't appear to do it, I was also wondering if there's a particular good reason for it.

**Comment by jpakkane** [comment]
If they don't work properly it's most likely because they have not seen much use and thus not many development resources.

> global and local arguments probably need to be supported as well

Yes. But include_directories needs to work as well and all our documentation and code samples should do "the right thing" because people tend to copy those directly in their own projects.

**Comment by jpakkane** [comment]
The rebase seems to have gotten mixed up somehow.

**Comment by glslang** [comment]
Ooops. Apologies. Messed up here. Wrong branch. Preparing a new patch. Will close this one and reopen.

**Pull request closed without merging**
