### PR TITLE
Fix pylint.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Slightly confused why #11779 got merged without first clicking "approve CI from first-time contributor" or whatever the wording is.

**Comment by jpakkane** [comment]
Some of the tests were run and showed green. The conflict probably comes from merging other MRs before that one.

**Comment by eli-schwartz** [comment]
I only see the MSVC azure CI having run at all. (4 checks run)

There's no conflict -- that PR originally imported contextlib and used it, but was rebased to not use it and neglected to remove the import that it added.

**Comment by jpakkane** [comment]
That would be my bad then. Such is life, but it is fixed now.

**Review by tristan957 — APPROVED** [review]

**Pull request merged**
