### PR TITLE
install: restore the SELinux context on install

### LINKED ISSUE #1967: SELinux context wrong after install
The selinux context is wrong after a ninja install. Found this during the libinput installs  and that's just a normal .so file. For the example here I'm using libratbag because we're overwriting system files and it doesn't matter much if libratbag breaks, your desktop won't go down because of it. The reason I'm picking an existing library is because that has a guaranteed SELinux context after system install as opposed to something new that may fall through the cracks of the SELinux policy.

Reproducer:

* Fedora 25 with SELinux enabled (i.e. standard config)
*  sudo dnf install -y libratbag

The context is:
```
$ ls -lZ /usr/lib64/libratbag.so.4.0.3
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0 155944 Jun  6 23:41 /usr/lib64/libratbag.so.4.0.3
```
meson.build file
```meson
project('test', 'c', version : '0')
lib_test = shared_library('ratbag',
	'test.c',
	 version : '4.0.3', # Matches F25 soname
	 install: true)
```

```
$ touch test.c
$ meson builddir --prefix=/usr
$ ninja -C builddir
$ sudo ninja -C builddir install

$ ls -lZ /usr/lib64/libratbag.so.4.0.3
-rwxrwxr-x. 1 root root unconfined_u:object_r:user_tmp_t:s0 7904 Jun 20 11:58 /usr/lib64/libratbag.so.4.0.3

# must run restorecon to fix it
$ sudo restorecon /usr/lib64/libratbag.*
$  ls -lZ /usr/lib64/libratbag.so.4.0.3
-rwxrwxr-x. 1 root root unconfined_u:object_r:lib_t:s0 7904 Jun 20 11:58 /usr/lib64/libratbag.so.4.0.3
```
Note how it's still ```unconfined_u``` instead of ```system_u``` after restorecon but at least this doesn't trigger SELinux denials anymore. In the case of libinput a denial prevents gdm from starting up, which is a tad annoying to some users :)

Autotools uses ```/usr/bin/install``` instead and that works (even when run manually):
````
$ sudo /usr/bin/install builddir/libratbag.so.4.0.3 /usr/lib64/libratbag.so.4.0.3 
$ ls -lZ /usr/lib64/libratbag.so.4.0.3 
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0 7904 Jun 20 12:05 /usr/lib64/libratbag.so.4.0.3
````

### PR DESCRIPTION
**Pull request by whot**
Try to restore the context for SELinux. If we fail on running
'selinuxenabled', quietly ignore the error and continue. If we fail on the
actual restorecon call, we print a message but disable SELinux - chances are
high that if one restorecon fails, others will too and that's likely a system
setup issue.

Fixes #1967

### CODE REVIEW

**Comment by jpakkane** [comment]
I don't really grok SELinux, but is there a way to add a test for this?

**Comment by whot** [comment]
I can't really think of a good test for this. First, we're only calling out to binaries here, so any actual changes depend on how those binaries work. Second, we're restoring system policy here and that is usually only defined for system files. So to test this, we'd need to install or overwrite an existing system file, then compare the selinux attributes of the previous vs newly installed file. I don't think that's a good option.

**Comment by astavale** [comment]
I find the phrase "disabling SELinux" in "{!r}: Failed to restore SELinux context, disabling SELinux..." alarming. Disabling SELinux means editing /etc/selinux/config in some distros or adding `selinux=0` as a kernel parameter to your boot loader. For an example see [How do I turn SELinux off in Red Hat Enterprise Linux?](https://access.redhat.com/solutions/3176).

There is no way that Meson should be that invasive. I'm hoping this is just bad phrasing and really what is happening is Meson won't try to use `restorecon` again if it fails once during that install. May be something like "{!r}: Failed to restore SELinux context, will no longer attempt to restore during this install..." would be better.

**Comment by whot** [comment]
>  I'm hoping this is just bad phrasing and really what is happening is Meson won't try to use restorecon again if it fails once during that install.

Yep, sorry, that's just bad phrasing and it does exactly what you wrote. I'll fix this.

**Comment by whot** [comment]
Force-pushed, new wording is "Failed to restore SELinux context, ignoring SELinux context for all remaining files..."

**Pull request merged**
