### PR TITLE
fix error when show default config of list

### PR DESCRIPTION
**Pull request by clouds56**
the error would occurs when specifying c_winlibs

### CODE REVIEW

**Comment by dcbaker** [comment]
After a bit of looking I reproduced this bug, but I think your fix is it going to break `meson configure`. It looks like the caller in msetup.py doesn't correctly check if it's passing a list in, and thus getting a list out. I think you need some of the `if isinstance(x, list): ... else: ...` logic in msetup.py.

**Comment by clouds56** [comment]
So how it would break `meson configure` here? Sorry I'm not familiar with all the respects in meson.

**Comment by dcbaker** [comment]
Have a look in `mconf.py`, there are several callers in their that hand `make_lower_case` a list and expect to get a list of strings back, with your change they'd get a string back.

**Comment by clouds56** [comment]
Thanks for that information, updated.
I'm choosing directly format it into string, since I've got no idea what's inside opt_value here, maybe list of list, dict or any other thing.

**Pull request merged**
