### PR TITLE
Fortran fixes

### PR DESCRIPTION
**Pull request by dcbaker**
Just a couple of things I noticed working on ICL support.

### CODE REVIEW

**Comment by dcbaker** [comment]
@scivision, you're the resident fortran expert, does this look okay?

**Comment by scivision** [comment]
There is a tweak I'd like to make to the test code, which is technically not valid fortran code. I may need till the weekend to get to this. Thanks!

**Comment by dcbaker** [comment]
No problem, I'm just trying to peel stuff out of my ICL branch that aren't directly related to ICL/ifort since that code will probably take longer to finish and land than this will.

**Comment by dcbaker** [comment]
@scivision, gentle ping.

**Comment by jpakkane** [comment]
Repinging @scivision.

**Comment by scivision** [comment]
Thanks I have some other stuff I have to do first, sorry about the delay.

**Comment by jpakkane** [comment]
Let's merge this now then. Other fixes can be done in subsequent MRs.

**Comment by scivision** [comment]
Thank you. I think it was important to get all that ICL stuff done and I will start working on Ifort for Windows based on these dcback PRs merged to master. Thanks, I was just tied up for a month.

**Pull request merged**
