### PR TITLE
Coalesce restorecon calls into one.

### LINKED ISSUE #2596: Reduce number of selinuxenabled and restorecon calls
Currently, when installing headers, meson will execute `selinuxenabled` for each header, and if enabled, call `restorecon` to alter the selinux context.

This has a fairly high overhead at install time.

If I make a dummy `selinuxenabled` shell script that just does `exit 1`, the time to install Builder's header files goes from a couple of seconds down to imperceptible.

There seems to be a couple of strategies to improve the performance here, and mix-n-match as appropriate.

 * Use /usr/bin/install when available to install files instead of Python's copy_file(). This would probably gain some optimizations they do there for faster copies (not a big deal) but also allow for the `-Z --context=ctx` option.
 * Cache the result of `selinuxenabled`
 * Cache the location of `which restorecon` to avoid traversing `$PATH` for each `execve()`.
 * Coalesce `restorecon` calls. It's not clear to me if these can be coalesced into a single call, or per-directory. `man restorecon` does imply that you can call it with multiple files at least.

### PR DESCRIPTION
**Pull request by QuLogic**
Locally, this reduces the test suite time from 3m12s to 2m57 or ~7.8%.

Fixes #2596.

cc @chergert

### CODE REVIEW

**Comment by jpakkane** [comment]
If there are many files to install then this will overflow the maximum length for a command. Perhaps it should do the updates in clumps of 20 files or so?

**Comment by chergert** [comment]
Even with this patch applied, the performance difference between having a dummy `selinuxenabled` returning `1` and not is roughly 50% of the Builder install time. 1.2 seconds vs 2.6 seconds averaged on my machine.

A single `restorecon` on all of the installed files is only `0.03` seconds. So something still seems unaccounted for.

**Comment by QuLogic** [comment]
Is that before or after meson has called `restorecon` for the install?

**Comment by chergert** [comment]
Since my script `selinuxenabled` returns `1`, `restorecon` should have never been called by meson.

**Comment by jpakkane** [comment]
Let's merge this now because it already improves the situation.

**Pull request merged**
