### PR TITLE
Add suffix options to cross files

### LINKED ISSUE #1802: Add name_suffix option to cross-files
For cross-compiling to platforms such as Emscripten, it would be useful to be able to define name_suffix for all targets. 

Cross-file example:
```
[binaries]
c = '/opt/emsdk-portable/emscripten/1.37.9/emcc'
cpp = '/opt/emsdk-portable/emscripten/1.37.9/em++'
ar = '/opt/emsdk-portable/emscripten/1.37.9/emar'

[properties]
root = '/opt/emsdk-portable/emscripten/1.37.9/system'
c_args = ['-s', 'WASM=1', '-O2']
c_link_args = ['-s', 'WASM=1','-O2']
cpp_args = ['-s', 'WASM=1','-O2']
cpp_link_args = ['-s', 'WASM=1','-O2']
name_suffix='js'

[host_machine]
system = 'emscripten'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
```

### PR DESCRIPTION
**Pull request by noverby**
Add the following properties to the cross file specification:
* exe_suffix
* static_lib_suffix
* shared_lib_suffix
* shared_module_suffix

Fixes  #1802

### CODE REVIEW

**Comment by nirbheek** [comment]
Can we get some tests for this or is the toolchain too difficult to setup? Also what toolchain outputs axf?

**Comment by noverby** [comment]
The Emscripten toolchain is not hard to setup but the size of it is 1.7 Gb. So we might not want it in the CI image. 

It is not my expertice, but according to [stackoverflow](https://stackoverflow.com/questions/17761328/what-are-axf-files) the RealView compiler outpus axf. I don't know how to test it.

**Comment by nirbheek** [comment]
Thinking again, it should be enough to have a test that sets this for a C compiler during cross-compilation. We just need to verify that the options work.

**Comment by nirbheek** [comment]
@jpakkane does this feature look ok to you?

**Comment by jpakkane** [comment]
Conceptually this is nice. Needs the requisite doc updates and the test mentioned above.

**Comment by jpakkane** [comment]
ping

**Comment by noverby** [comment]
Sorry but I have to postpone this tomorrow.

**Comment by noverby** [comment]
For testing should I just create a cross file with the options set and add it to `run_tests.py`?

**Comment by jpakkane** [comment]
It should probably be  in `run_unittests.py`.

**Comment by jpakkane** [comment]
Ping.

**Comment by Totto16** [comment]
Any updates on this? Since it would really be nice, to change 
```yaml
[properties]
    exe_suffix=html
```
 to force emscripten to also build the html

**Pull request closed without merging**
