### PR TITLE
javac: Don't fail if there's no JVM

### PR DESCRIPTION
**Pull request by nirbheek**
A JVM is not required to compile Java executables. Without this, we error out with an exception if `javac` is found but `java` isn't:

```
[...]
File "mesonbuild/interpreter.py", line 1759, in detect_compilers
  comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
File "mesonbuild/compilers.py", line 1279, in sanity_check
  pe = subprocess.Popen(cmdlist, cwd=work_dir)
File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
  restore_signals, start_new_session)
File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
  raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'java'
```

### CODE REVIEW

**Comment by jpakkane** [comment]
Java is required to run unit tests and final executables, though. Is there ever a case where JVM would not be available? All distributions I have seen ship the JVM as part of the JDK.

**Comment by nirbheek** [comment]
On Fedora, java-1.8.0-openjdk-devel doesn't install the JRE which has `java`. The same thing happens on Gentoo as well. Debian and Ubuntu make the JDK pull in the JRE though.

This can also happen when you're building with the Android SDK, but I'm sure there are other problems in using Meson for that. :)

**Comment by jpakkane** [comment]
I'm not a Fedora specialist but this is what the command line gives me:

    dnf repoquery --requires java-1.8.0-openjdk-devel 
    ...
    java-1.8.0-openjdk = 1:1.8.0.111-1.b16.fc24
    java-1.8.0-openjdk = 1:1.8.0.91-7.b14.fc24

But still, not having a JVM means that you can't run any of the code or tests you have built. That does not seem like a useful development environment.

The Android case makes sense, but we should then check for Dalvik or whatever it was that they use inside ADK these days.

**Comment by nirbheek** [comment]
It might not be a useful development environment, but it is a useful environment for build bots.

**Comment by jpakkane** [comment]
But shouldn't build bots run tests after building? That's what Debian & others seem to do (and it is in fact mandatory on Debian at least).

**Comment by nirbheek** [comment]
I'm ok with making this a hard error till we figure out a decent cross-compile story with Android, J2ME, etc. Although I suspect that that will involve people setting `JAVA_HOME` and such, and just using it as though it was a native Java environment in which case we'll have to come back to this.

I'll defer to your preference. :)

**Comment by jpakkane** [comment]
Hard fail with a message like this seems to be the simplest solution: "Java virtual machine is required to enable Meson's Java build support. Please install a JVM. If you have specific needs where this requirement does not make sense, please open a bug with a detailed description of your build setup. Thanks."

**Comment by nirbheek** [comment]
Done!

**Pull request merged**
