### PR TITLE
Make installing generated man files easier

### PR DESCRIPTION
**Pull request by dcbaker**
Something that's long been a wart in meson is using man pages. If you man pages are static files you can pass them to `install_man`, which handles figuring out where to install the man pages to. For generated man pages (using either `configure_file` or `custom_target`) you must manually build the install directory. This is neither dry nor pleasant. We've discussed allowing passing these targets to `install_man`, but that creates an odd system where you either set `install : true; install_dir : ...` OR pass it to `install_man`, and violates the design goal of meson that all information about a target should be provided at target creation time.

This then, keeps all of those constraints by introducing an `'@MANDIR@'` special value that can be passed to `custom_target` and `configure_file`'s `install_dir` keyword arguments. Meson will then use the same logic it uses in `install_man` to calculate the correct install location for the target automatically.

For example:
```meson
custom_target(
  output : 'page.1',
  install : true,
  install_dir : '@MANDIR@',
)
```

Along the way I had to do a bit of refactoring, so there're some cleanups and type annotations and such in here as well. The only one of these that is significant is `Better documentation and argument checking for multiple install_dirs`, which adds and moves so argument validation logic around.

Fixes: #1550
Fixes: #2025

### CODE REVIEW

**Comment by jpakkane** [comment]
Could (and indeed should) this be made general. That is so it would work with other things as well? So instead of this:

`´`
install_dir: get_option('datadir') / 'myproj'
```

you could have something like:

```
install_dir: '@datadir@/myproj'
```

**Comment by dcbaker** [comment]
There is a difference here between `get_option('mandir')` and `@MANDIR@`, because the latter expands to `get_option('mandir') / man${section}'`

**Comment by bonzini** [comment]
What happens if someone thinks its funny to specify `@MANDIR@` as their mandir, and an existing meson.build uses `get_option('mandir') / 'man1'`?

**Comment by eli-schwartz** [comment]
What happens if someone wants to actually create a literal custom target output file named `@MESON_VARIABLE@` for a given value of documented meson variable replacements?

**Comment by dcbaker** [comment]
I think given #8398 it probably makes more sense to not use a special value, and to use a module for this instead.

**Pull request closed without merging**
