### PR TITLE
Update expected skip condition for llvm framework test on msys2

### PR DESCRIPTION
**Pull request by jon-turney**
Supersedes: #9534, #9547

### CODE REVIEW

**Comment by jon-turney** [comment]
Test is now expected to run, not skip on msys2 with clang.  So change the skip_on_jobname from 'msys2' to 'msys2-gcc', as it's only expected there.

**Comment by jon-turney** [comment]
Now that the run is expected, we can see that it is failing during the build stage, for reasons I don't understand:

```
[1/2] "clang" "-Isum.exe.p" "-I." "-I..\test cases\frameworks\15 llvm" "-ID:/a/_temp/msys64/mingw64/include" "-fcolor-diagnostics" "-DNDEBUG" "-Wall" "-Winvalid-pch" "-std=c99" "-O0" "-g" "-pthread" "-D_FILE_OFFSET_BITS=64" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" -MD -MQ sum.exe.p/sum.c.obj -MF "sum.exe.p\sum.c.obj.d" -o sum.exe.p/sum.c.obj "-c" "../test cases/frameworks/15 llvm/sum.c"
[2/2] "clang++"  -o sum.exe sum.exe.p/sum.c.obj "-Wl,--allow-shlib-undefined" "-Wl,--start-group" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUAsmParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUCodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUDesc.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUDisassembler.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUInfo.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUUtils.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAggressiveInstCombine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAnalysis.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAsmParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAsmPrinter.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBinaryFormat.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitWriter.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitstreamReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCFGuard.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCore.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCoroutines.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoCodeView.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoDWARF.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoMSF.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDemangle.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMExecutionEngine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMFrontendOpenMP.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMGlobalISel.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMIRReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMInstCombine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMInstrumentation.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMLinker.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMC.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCDisassembler.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCJIT.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMIRParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMObjCARCOpts.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMObject.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMOrcShared.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMOrcTargetProcess.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMPasses.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMProfileData.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMRemarks.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMRuntimeDyld.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMScalarOpts.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMSelectionDAG.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMSupport.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTarget.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTextAPI.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTransformUtils.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMVectorize.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86CodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86Desc.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86Info.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMipo.a" "D:/a/_temp/msys64/mingw64/lib/libz.dll.a" "advapi32.lib" "ole32.lib" "psapi.lib" "pthread.lib" "shell32.lib" "uuid.lib" "-pthread" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
FAILED: sum.exe 
"clang++"  -o sum.exe sum.exe.p/sum.c.obj "-Wl,--allow-shlib-undefined" "-Wl,--start-group" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUAsmParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUCodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUDesc.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUDisassembler.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUInfo.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAMDGPUUtils.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAggressiveInstCombine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAnalysis.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAsmParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMAsmPrinter.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBinaryFormat.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitWriter.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMBitstreamReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCFGuard.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCore.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMCoroutines.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoCodeView.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoDWARF.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDebugInfoMSF.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMDemangle.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMExecutionEngine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMFrontendOpenMP.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMGlobalISel.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMIRReader.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMInstCombine.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMInstrumentation.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMLinker.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMC.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCDisassembler.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCJIT.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMCParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMMIRParser.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMObjCARCOpts.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMObject.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMOrcShared.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMOrcTargetProcess.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMPasses.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMProfileData.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMRemarks.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMRuntimeDyld.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMScalarOpts.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMSelectionDAG.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMSupport.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTarget.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTextAPI.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMTransformUtils.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMVectorize.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86CodeGen.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86Desc.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMX86Info.a" "D:/a/_temp/msys64/mingw64/lib/libLLVMipo.a" "D:/a/_temp/msys64/mingw64/lib/libz.dll.a" "advapi32.lib" "ole32.lib" "psapi.lib" "pthread.lib" "shell32.lib" "uuid.lib" "-pthread" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
clang++: error: no such file or directory: 'advapi32.lib'
clang++: error: no such file or directory: 'ole32.lib'
clang++: error: no such file or directory: 'psapi.lib'
clang++: error: no such file or directory: 'pthread.lib'
clang++: error: no such file or directory: 'shell32.lib'
clang++: error: no such file or directory: 'uuid.lib'
ninja: build stopped: subcommand failed.
```

**Comment by dcbaker** [comment]
Those like windows only libs, are they supposed to be used with msys? It almost looks like we've found an llvm we shouldn't have

**Comment by jon-turney** [comment]
> Those like windows only libs, are they supposed to be used with msys? It almost looks like we've found an llvm we shouldn't have

It looks like those are coming from msys2's LLVMExports.cmake, so guessing wildly, maybe that doesn't understand correctly about msys2?

**Comment by jeremyd2019** [comment]
I'm not seeing anything in msys2's clang package to make me think it's doing something like that.  Maybe https://github.com/mesonbuild/meson/blob/4f4259de1b0d40c385d017675245e5d662017d0e/mesonbuild/dependencies/cmake.py#L619-L625 ?
I'm not familiar enough with meson to know if it already knows mingw vs 'normal' windows there

**Comment by jon-turney** [comment]
>  Maybe?

Yeah, that does look suspicious.  I was kind of assuming that dependency(method: 'cmake') works on msys2, but maybe that's not the case...

**Comment by eli-schwartz** [comment]
@mensinda

**Comment by jon-turney** [comment]
Yeah, that seems to be the spot.  

I'm not sure that comment is correct.  This list of libraries ends up in dep.link_args, which I thought is compiler-neutral and gets massaged into a compiler appropriate format when output by the backend?

That line was added in 6a0fabc6472f49621260de215f128a31ae70219b (PR #6980), which was accepted without a regression test.

**Comment by dcbaker** [comment]
The good news is that comment isn't right, we *do* have a compiler environment. you should have `self.clib_compiler` there, which is a CCompiler, and `self.environment`, so we should be able to do something like
```python
libs += self.clib_compiler.find_library(j, self.env, [])
```

**Comment by jon-turney** [comment]
> so we should be able to do something like

Indeed, that seems to work.  Thanks.

We don't have any CI coverage of LLVM with MSVC, which I guess is the scenario in #6980, but I guess this is an improvement.

**Review by dcbaker — APPROVED** [review]

**Comment by dcbaker** [comment]
Awesome, thanks for figuring this out!

**Comment by jon-turney** [comment]
> We don't have any CI coverage of LLVM with MSVC, which I guess is the scenario in #6980,

Looked at that a bit more since both LLVM and CMake are present in the Azure VM image, so perhaps only a bit of configuration to find it.  However, it seems that the Windows installer from llvm.org doesn't provide the required .cmake files (or llvm-config), so we are out of luck.

**Pull request merged**
