### PR TITLE
Rust: Add test for include_bytes!()

### PR DESCRIPTION
**Pull request by cmarcelo**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
May I ask what motivated you want to regression-test that this feature of the rust compiler works when done from meson? :)

**Comment by cmarcelo** [comment]
> May I ask what motivated you want to regression-test that this feature of the rust compiler works when done from meson? :)

Was looking at the behavior of a different language that hasn't landed yet, in which a similar feature would've fail. Created the test while understanding about the problem. It is fine to close it if is out of scope for Meson, I was myself a bit unsure if this is the best way to test it.

There are two failure modes for such kind of feature: (1) compiler can't find the file  (2) if I change the "included" file compiler doesn't get it.  I don't know enough of the unit tests yet to provide a test for (2).  In Rust those two are covered by the fact that it produces (and Meson/Ninja will use) the dependency information.

**Comment by eli-schwartz** [comment]
I'm no expert on rust, but I thought I recalled that using include_bytes is indeed something that might not work, but specifically it might not work when either one or the other of the .rs file or the included data file is generated. In particular, that usually means that the data file is referenced via an environment variable macro, which becomes a whole issue of how to pass an environment variable definition to a `library('foo', 'foo.rs')`

However this test case doesn't seem to be attempting to tickle that edge case.

> It is fine to close it if is out of scope for Meson, I was myself a bit unsure if this is the best way to test it.

It's in scope for meson, as long as there's a concern that meson needs to do something to make it work and we need to run a CI job to guarantee it keeps working.

(It isn't in scope for meson, if the status of it working or not working is nothing to do with meson. There's a nearly unlimited number of possible compiler features, and we can't check all of them -- and the compilers already have CI to make sure those work. We're mostly interested in where those features intersect with the build rules that meson creates.)

Again, like I said, I'm no expert on rust, so I'm mainly trying to clarify whether you think it's important to regression-test this.

**Comment by cmarcelo** [comment]
> However this test case doesn't seem to be attempting to tickle that edge case.

I'm not looking at that edge case at all.

> > It is fine to close it if is out of scope for Meson, I was myself a bit unsure if this is the best way to test it.
> 
> It's in scope for meson, as long as there's a concern that meson needs to do something to make it work and we need to run a CI job to guarantee it keeps working.
>
> (It isn't in scope for meson, if the status of it working or not working is nothing to do with meson. There's a nearly unlimited number of possible compiler features, and we can't check all of them -- and the compilers already have CI to make sure those work. We're mostly interested in where those features intersect with the build rules that meson creates.)

This test as-is should run on CI (the previous failures I've seen here were due me forgetting the test.json file). As I mentioned before a more meaningful test would be verify that Meson triggers a rebuild when the include file changes -- i.e. ensure that Meson/Ninja is aware of the dependencies and include them in the build rules. I'll see if I can write such kind of test then.

Closing this, sorry for the noise.

**Comment by eli-schwartz** [comment]
> As I mentioned before a more meaningful test would be verify that Meson triggers a rebuild when the include file changes -- i.e. ensure that Meson/Ninja is aware of the dependencies and include them in the build rules. I'll see if I can write such kind of test then.

That will probably have to be a unittest, instead of a project test. You can stick it in `test cases/unit/` and run it in unittests/*.py`, which allows you to configure and build, then update the mtime of one of the files, then try rebuilding. We even have a custom assert method to check whether a rebuild is a no-op.

**Pull request closed without merging**
