### PR TITLE
Compare full path for Fortran file using itself (closes #4974)

### LINKED ISSUE #4974: dependency cycle for Fortran file with two modules (one using the other)
```python
# meson.build
project('libamrex', 'fortran')
library('badmodule', 'src/badmodule.f90')
```

```fortran
# src/badmodule.f90
module foo
end module foo

module bar
contains
   subroutine baz
      use foo
   end subroutine baz
end module bar
```

Error message:
```shell
> mkdir build; meson build; ninja -C build
The Meson build system
Version: 0.49.2
Source dir: /home/mark/repos/mfix-exa/subprojects/libamrex
Build dir: /home/mark/repos/mfix-exa/subprojects/libamrex/build
Build type: native build
Project name: libamrex
Project version: undefined
Native Fortran compiler: gfortran (gcc 8.2.0 "GNU Fortran (Ubuntu 8.2.0-7ubuntu1) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2.git.kitware.dyndep-1.jobserver-1 at /home/mark/.local/bin/ninja
ninja: Entering directory `build'
ninja: error: dependency cycle: badmodule@sha/src_badmodule.f90.o -> badmodule@sha/foo.mod -> badmodule@sha/src_badmodule.f90.o
```

If `badmodule.f90` is not in `src/` but in the top level directory, then the build works.

### PR DESCRIPTION
**Pull request by mwm126**

### CODE REVIEW

**Comment by scivision** [comment]
The failure is like for `test cases/fortran/4*`:
```
ninja: error: dependency cycle: selfdep@exe/selfdep.f90.o -> selfdep@exe/geom.mod -> selfdep@exe/selfdep.f90.o
```

**Comment by scivision** [comment]
see https://github.com/mesonbuild/meson/pull/4979

**Comment by jpakkane** [comment]
Does that have everything this one? If yes, can this be closed?

**Comment by scivision** [comment]
Yes this can be closed. #4979 corrects the logic attempted in #4975

**Pull request closed without merging**
