### PR TITLE
Disable asan memory leak checks on a Cuda test.

### PR DESCRIPTION
**Pull request by jpakkane**
Should fix Arch Cuda CI failure.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
@obilaniu since you've touched the cuda module a lot, perhaps you know why this started to fail to begin with?

**Comment by obilaniu** [comment]
@eli-schwartz Hard to say! I *did* touch #8396 concerning the sanitizers, but that was CUDA test case 15. This is test case 16 concerning support for multiple CUDA standards, reported #8523 and fixed in #8527 / #8596.

That was 3 months ago. At the time, I seem to recall the CUDA Arch runner was using GCC 10 and CUDA 11.2; Now I see it is using GCC 11 and CUDA 11.3. Perhaps mixed C++ standards and sanitizers play badly, or the new GCC or CUDA Toolkit expose a problem?

**Comment by eli-schwartz** [comment]
When I was trying to figure out why it failed, I tried running multiple cuda test cases locally using meson.py setup builddir. They all produced asan erroring executables, but only one test case actually executes the program in a testsuite.

So it's either a general problem with the cuda toolkit itself, or a problem with all our example program sources. I really don't think it's about any PR specifically.

I was hoping maybe you knew some answer like "yeah, current versions of cuda are just buggy".

**Comment by obilaniu** [comment]
@eli-schwartz It looks like `libcuda` does weird things that play poorly with ASAN.

- https://github.com/google/sanitizers/issues/629
- https://github.com/NVIDIA/DALI/pull/362

**Pull request merged**
