### PR TITLE
interpreter: Add support for dict addition

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by jpakkane** [comment]
This requires a lot more tests:

- adding two dictionaries that have the same key should end up with the value from the second dict (or possibly a hard error?)
- when doing `c = a + b` the code should check that `c` does have the new keys in `b` but that `a` does not
 - when first doing `a = b` and then doing `a += d` the code should check that `b` has not been changed

Also all the requisite documentation updates.

**Comment by xclaesse** [comment]
@jpakkane right, added those cases now.

**Comment by nirbheek** [comment]
> adding two dictionaries that have the same key should end up with the value from the second dict

I agree, this is necessary for the workflow described in https://github.com/mesonbuild/meson/issues/3931:

```meson
backends = {'video': ['foo', 'bar']}
copy = backends
backends += {'video': backends['video'] + ['faz']}
# backends is now {'video': ['foo'. 'bar', 'faz']}
# copy remains {'video': ['foo'. 'bar']}
```

**Comment by jpakkane** [comment]
⚔️ conflicts. Also needs the requisite documentation updates, but other than that looks good.

**Comment by xclaesse** [comment]
> crossed_swords conflicts. Also needs the requisite documentation updates, but other than that looks good.

Done.

**Pull request merged**
