### PR TITLE
strip trailing backslash from WindowsSDKVersion

### LINKED ISSUE #1537: VS 2017 backend emits bad WindowsTargetPlatformVersion value
When I tried generating a VS 2017 solution, the generated app.vcxproj contained this:

```
<WindowsTargetPlatformVersion>10.0.14393.0\</WindowsTargetPlatformVersion>
```

Which then causes errors in other `.targets` files attempting to do a numeric comparison against that.
This value is probably taken straight from one of these environment variables:

```
WindowsSDKLibVersion=10.0.14393.0\
WindowsSDKVersion=10.0.14393.0\
```

The trailing backslash is a bit suspect, but may be there intentionally so it can be concatenated to 
```
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
```
directly.

### PR DESCRIPTION
**Pull request by melak47**
This fixes #1537.

### CODE REVIEW

**Comment by nirbheek** [comment]
Please add yourself to the end of authors.txt and we'll get this merged, thanks!

**Comment by melak47** [comment]
@nirbheek is my github user name sufficient?

**Comment by jpakkane** [comment]
You can choose yourself how you want to be listed there.

**Comment by melak47** [comment]
Alright, done.

**Pull request merged**
