### PR TITLE
backends/vs: Set ObjectFileName for generated sources.

### PR DESCRIPTION
**Pull request by anarazel**
When a static library B to a static library A with generated sources, B
directly references the object file corresponding to the generated source in
A. For that reference in B object_filename_from_source() is used.  But A did
not specify the object file name, ending up with cl.exe's default.

This contains the test @jenatali wrote in #9259 / #9235

### CODE REVIEW

**Review by jenatali — APPROVED** [review]
Looks good and it fixes the test, thanks!

**Comment by anarazel** [comment]
I thought the stuff in `platform_fix_name()` should take care of this, but apparently not... 
```
2021-09-18T01:03:03.2084391Z Extra file usr/bin/cygboth_lib.dll found.
2021-09-18T01:03:03.2158539Z Expected file usr/bin/libboth_lib.dll missing.
2021-09-18T01:03:03.2175087Z 
2021-09-18T01:03:03.2180060Z Install dir contents:
2021-09-18T01:03:03.2193437Z   - usr/bin/cygboth_lib.dll
2021-09-18T01:03:03.2251082Z   - usr/lib/libboth_lib.a
2021-09-18T01:03:03.2252494Z   - usr/lib/libboth_lib.dll.a
```

**Comment by eli-schwartz** [comment]
Take a second look at https://mesonbuild.com/Contributing.html#installed

`"type": "file"` explicitly does absolutely zero reprocessing whatsoever, no matter what, `"type": "expr"` invokes platform_fix_name, and `"type": "shared_lib"` expects you to call the file `both_lib` and it will add the correct platform name.

**Comment by anarazel** [comment]
> Take a second look at https://mesonbuild.com/Contributing.html#installed

> "type": "file" explicitly does absolutely zero reprocessing whatsoever, no matter what, "type": "expr" invokes platform_fix_name, and "type": "shared_lib" expects you to call the file both_lib and it will add the correct platform name.

Ah, somehow I had missed part of that. Thanks. Let's see whether this works on cygwin as well...

**Comment by anarazel** [comment]
@eli-schwartz 
> "type": "shared_lib" expects you to call the file both_lib and it will add the correct platform name.

Seems like that doesn't quite work? With gcc on windows CI says (and I now reproduced):
```
Reason: 
Extra file usr\bin\libboth_lib.dll found.
Extra file usr\lib\libboth_lib.dll.a found.
Expected file usr\lib\both_lib.dll.a missing.
Expected file usr\bin\both_lib.dll missing.

Install dir contents:
  - usr\bin\libboth_lib.dll
  - usr\lib\libboth_lib.a
  - usr\lib\libboth_lib.dll.a
```
For 
```
  "installed": [
    {"type": "file", "file": "usr/lib/libboth_lib.a"},
    {"type": "implib", "file": "usr/lib/both_lib"},
    {"type": "pdb", "file": "usr/bin/both_lib"},
    {"type": "shared_lib", "file": "usr/bin/both_lib"}
  ]
```
So neither implib nor shared_lib seem to deal with the variance around the lib prefix? Even though the docs say:
> For shared libraries, always written as name. The appropriate suffix and prefix are added by platform

Seems like prefix handling is missing?

It seems a bit absurd to have installed-specs for gcc, msvc, cygwin :(. But unless I miss something, that's kind of required for shared libs right now?

**Comment by jenatali** [comment]
Confirmed that this fixes my original repro in the Mesa repo, FYI. Thanks again.

**Review by dcbaker — APPROVED** [review]

**Pull request merged**
