### PR TITLE
mintro: AST JSON printer

### PR DESCRIPTION
**Pull request by mensinda**
Adds the `--ast` command to `meson introspect` to dump the raw meson AST as JSON.

### CODE REVIEW

**Comment by mensinda** [comment]
The both linter CI's are failing on checkout (for whatever reason) and I don't know why OpenSUSE didn't start yet.

**Comment by mensinda** [comment]
Ping. The CI error seems to be unrelated.

**Comment by jpakkane** [comment]
What is the eventual use case for this?

**Comment by mensinda** [comment]
This was discussed in the IRC a while back (I think around December 2019). Essentially someone wants to do a more advanced analysis of meson files (which options influence which dependency, etc.), than what we are willing to provide in the introspection API.

Also, this might be useful for IDE's to do better syntax highlighting, since they now no longer have to implement there own lexer + parser for meson.

**Comment by mensinda** [comment]
Updated the version to 0.55.0

**Comment by mensinda** [comment]
ping :)

**Comment by jpakkane** [comment]
The documentation should say that the format is not guaranteed to be stable.

**Comment by mensinda** [comment]
Rebased and updated the docs.

**Comment by mensinda** [comment]
The CI failure is unrelated (the same happens on master)

**Pull request merged**
