### PR TITLE
Prohibit absolute paths in subdir().

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by nirbheek** [comment]
Shouldn't this be stricter? You should only be allowed to `subdir()` into a directory that is actually a subdir of the current directory. I think you can still `subdir()` into an arbitrary src directory with a relative path.

**Comment by jpakkane** [comment]
if '..' in args[0]:
            raise InvalidArguments('Subdir contains ..')

**Comment by nirbheek** [comment]
Ah, sorry, so we don't allow that. But isn't that check too broad? It means you can't have a directory called `name..something`. Maybe split it into parts with `pathlib` and check if one of the parts is `..`? Something like:

```
if '..' in pathlib.PurePath(args[0]).parts:
```

**Comment by jpakkane** [comment]
I have no sympathy for people naming their directories like that. :) Never seen that in the wild. No-one has complained about it.

**Comment by nirbheek** [comment]
I don't see why we should ever reject valid directory names though. Especially since thanks to `pathlib`, we don't have to worry about any corner-cases. That check is always going to be correct.

**Comment by sardemff7** [comment]
Why would you restrict using an absolute path? I use that feature in my project and it’s very handy.
My project is plugin-based; these plugins are in their own subdir and some of them are optional.
I also have a git submodule that I use for several other projects, containing main loop integrations for X11, Wayland, ALSA and others:
```
plugins/gui/xcb
plugins/gui/wayland
plugins/sound/alsa
src/mainloop-submodule/xcb
src/mainloop-submodule/wayland
src/mainloop-submodule/alsa
```
With absolute paths in `subdir()`, I can easily put all the conditionals in one place, making my `meson.build` files readable.
My files are complex enough currently, I would rather not split the `subdir()` part to the toplevel file.

**Comment by nirbheek** [comment]
Could you link me to your project? I'm curious as to how you're using this. We have the same setup in gstreamer and the way we do it is not cumbersome at all.

**Comment by TingPing** [comment]
There is no reason to prevent nested dirs like that and I don't think thats what this issue is over?

**Comment by nirbheek** [comment]
Yeah, this is about fixing https://github.com/mesonbuild/meson/issues/1358.

**Comment by nirbheek** [comment]
Speaking of which, that should be mentioned in the commit message.

**Comment by sardemff7** [comment]
The [relevant file](https://github.com/sardemff7/eventd/blob/wip/meson/plugins/nd/meson.build). I use `subdir(join_paths(meson.source_root(), 'src', 'libgwater', 'wayland'))` in it, because *all* the Wayland stuff is in this file only. Without absolute `subdir()` (I don’t care if it’s a special command like `subdir_from_root()` btw), I would have to put more conditionals in the toplevel file.

**Comment by TingPing** [comment]
I think the goal is simply clarity, and `src/foo/bar` somehow subdiring `src/baz/stuff` is quite obscure.

**Comment by nirbheek** [comment]
I can't make out what the `meson.build` files in `src/libgwater/xcb` are supposed to do, but those directories only have one source file each, so it looks like you can put the conditional in there instead of in the top-level meson.build file.

**Comment by sardemff7** [comment]
Not to me, I just happen to have a git submodule at the toplevel that the core part doesn’t use.
OTOH, hiding a git submodule in a sub-sub-sub-dir is obscure to me, and cluttering the toplevel `meson.build` sounds annoying.

And yes, I am aware I only use this in one `meson.build` in this project, but I do use it in several subdir in other projects of mine I would like to port to Meson too.

I cannot put conditionals in `src/libgwater/*` because this is a git submodule, shared by several projects (not all mine) that do not share the same options.

**Comment by nirbheek** [comment]
Could you show me exactly what the subdir `meson.build` file is? The best way to solve that use-case is to use subprojects. This is exactly what that was made for—including resources from other projects.

**Comment by sardemff7** [comment]
```
gw_glib = dependency('glib-2.0', version: '>= 2.36')
gw_wayland_wayland = dependency('wayland-client', version: '>= 1.1.91')

libgwater_wayland_inc = include_directories('.')
libgwater_wayland_dep = [ gw_wayland_wayland, gw_glib ]
libgwater_wayland_lib = static_library('libgwater-wayland', [
		config_h,
		'libgwater-wayland.h',
		'libgwater-wayland.c',
	],
	dependencies: libgwater_wayland_dep,
	include_directories: libgwater_wayland_inc,
)

libgwater_wayland = declare_dependency(link_with: libgwater_wayland_lib, include_directories: libgwater_wayland_inc, dependencies: libgwater_wayland_dep)
```

I *think* I could drop the `config_h` thing, would have to triple-check my code for that.
If I can drop it, then using subprojects would be technically possible.

**Comment by TingPing** [comment]
> I cannot put conditionals in src/libgwater/* because this is a git submodule, shared by several projects (not all mine) that do not share the same options.

Perhaps it should be a subproject then?

**Pull request merged**
