### PR TITLE
RFC: Use git-ls-files for dist-git

### PR DESCRIPTION
**Pull request by elmarco**
By using git-ls-files, we can make dist work without cloning the repo/submodules, so it should also work fine offline. Furthermore, it also takes into accound modified files, which allows to verify make dist work before committing.

Though this may be detrimental to current users of mesons that may expect the command to work with the committed files. Imho, either meson should put a big fat warning, or meson should generate a -dirty version using an approach similar to what #688 requests (which I am also looking at).

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
honestly, I'm very against making archive out of dirty tree... probably only when people pass `--dirty` to dist or such.

**Comment by elmarco** [comment]
I think I was explicit enough that this is a change of behaviour, but it is also what I needed... meson could easily add -dirty name in the resulting tarball though, I think this would be quite explicit enough.

**Comment by jpakkane** [comment]
The current behaviour is deliberate because we probably need to add the possibility to run scripts that do arbitrary operations on the source tree before compressing. See #2166 for example.

**Comment by jpakkane** [comment]
Since this does not seem to be able to support #2166 closing to reduce clutter on the MR page. Thanks.

**Comment by elmarco** [comment]
I am not convinced the two requeriements are incompatible, but fine, I'll reopen if I have a more complete solution.

**Pull request closed without merging**
