### PR TITLE
Add a test for link_depends using a custom target

### PR DESCRIPTION
**Pull request by jon-turney**

### CODE REVIEW

**Comment by jon-turney** [comment]
Test fails for all VS backends

**Comment by nirbheek** [comment]
Please add this test to #1792 and skip it (and the test in #1792) when the backend is vs like so:

```meson
if meson.backend().startswith('vs')
  # FIXME: Broken on the VS backends
  error('MESON_SKIP_TEST see https://github.com/mesonbuild/meson/issues/1799')
endif
```

**Comment by jon-turney** [comment]
Incorporated into PR #1792

**Comment by jon-turney** [comment]
@nioncode ping

**Pull request closed without merging**
