### PR TITLE
BUGFIX: Fortran: use, module, submodule with inline comment

### LINKED ISSUE #5513: No dependency if comment follows fortran module statement
Meson 0.51.0. If there is a comment after the fortran module declaration like
```
module nice !
```
this module is not added as a dependency for another source-file with `use nice`.

### PR DESCRIPTION
**Pull request by scivision**
in response to #5513, tests for Fortran module name with inline comment.

The Fortran regex patterns for module, submodule and include were not correct--they could not tolerate inline comments.

1. apply fix to regex in ninjabackend.py
2. add inline comment tests for Fortran use, module, submodule, include
3. fix syntax error (unrelated, just saw it)
4. fix type hinting in the function (unrelated, just saw it)

Fixes #5513

### CODE REVIEW

**Comment by dcbaker** [comment]
This all looks pretty reasonable (I mean, as reasonable as regex can possibly look :) ), assuming that the tests come back green I'll merge this.

**Comment by scivision** [comment]
Yes this was a perfect example of: if it isn't tested, it's broken.  I think I've done that a few times in Meson....

**Comment by dcbaker** [comment]
I've done a bunch of that myself.

**Comment by dcbaker** [comment]
build failures seem relavent

**Comment by scivision** [comment]
OK I had to get more specific in ignoring `module procedure` in 927ce94

**Pull request merged**
