### PR TITLE
Simplify has_function and fix SDK targetting on macOS

### PR DESCRIPTION
**Pull request by nirbheek**
Derived from https://github.com/mesonbuild/meson/pull/3902

### CODE REVIEW

**Comment by nirbheek** [comment]
@xclaesse it was pointed out on #3902 that these changes might break with the Android NDK. You added the android CI run for glib, could you do the same for meson so we have better coverage there?

**Comment by jpakkane** [comment]
It seems that just plain GCC fails too.

**Comment by nirbheek** [comment]
Sigh, yeah, I'll look into this more in the coming days.

**Comment by ePirat** [comment]
As already mentioned in the original PR, the failing test seem to be:

`ERROR:  Assert failed: built-in alloca must not be found with #include and #undef`

I do not understand why `alloca` must not be found when it is undef'd?

**Comment by ePirat** [comment]
@nirbheek Ping?

**Comment by ePirat** [comment]
@nirbheek @jpakkane Ping again…

**Comment by jpakkane** [comment]
Please rebase so we can see what the status against current master is. Thanks.

**Comment by jpakkane** [comment]
Superseded by #6136.

**Pull request closed without merging**
