### PR TITLE
Fully annotate the envconfig and mlog modules

### PR DESCRIPTION
**Pull request by dcbaker**
Mostly this is just type annotations, but there are a few fixes in here to correct situations that work, but are not strictly type correct. I picked these two as a starting point as they're relatively contained and relatively simple.

You can verify these with `mypy --follow-imports=silent --strict $module`. There is one warning in envconfig about using an untyped function from another module, but other than that this is clean. If there's interest I'll create a CI job to run against modules as they become fully typed so that we can ensure that the type safety isn't broken.

### CODE REVIEW

**Comment by nirbheek** [comment]
> If there's interest I'll create a CI job to run against modules as they become fully typed so that we can ensure that the type safety isn't broken.

I don't think anyone would object to more CI ;(

**Comment by jpakkane** [comment]
```
  File "D:\a\1\s\mesonbuild\envconfig.py", line 137, in Properties
    def __eq__(self, other: typing.Any) -> typing.Union[bool, NotImplemented]:
  File "C:\Python3\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "C:\Python3\lib\typing.py", line 348, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Python3\lib\typing.py", line 348, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Python3\lib\typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got NotImplemented.
```

**Comment by dcbaker** [comment]
Along with fixing the unit tests, I've added a few annotations to mesonlib to get rid of the "untyped function in typed context" errors. I can add a CI job, but we'll need to install mypy in the ci image.

**Comment by dcbaker** [comment]
Actually, I wonder if we can configure sider to run mypy for us?

**Pull request merged**
