### PR TITLE
Save/reload windows target platform version for vs2017

### LINKED ISSUE #1847: vs2017 backend REGEN target fails to find WindowsSDKVersion
The vs2017 backend seems to need the `WindowsSDKVersion` environment variable in order to work. If you invoke it from the developer command line, it works, but if you invoke this target through the normal IDE, this environment variable is not set, and so it fails.

Is this environment variable something we'd expect to change, or would it make sense to bake it into the `REGEN` project so that it doesn't matter that it's not set after the initial `meson build`? Alternately, is there a way to modify the `REGEN` project to use all of the developer environment variables?

```
1>------ Build started: Project: REGEN, Configuration: debug Win32 ------
1>Checking whether solution needs to be regenerated.
1>Traceback (most recent call last):
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 298, in run
1>    app.generate()
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 165, in generate
1>    g = vs2017backend.Vs2017Backend(b)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\backend\vs2017backend.py", line 27, in __init__
1>    self.windows_target_platform_version = os.getenv('WindowsSDKVersion', None).rstrip('\\')
1>AttributeError: 'NoneType' object has no attribute 'rstrip'
1>The Meson build system
1>Version: 0.40.1
1>Source dir: C:\Users\acfoltzer\Source\Repos\OpenUxAS
1>Build dir: C:\Users\acfoltzer\Source\Repos\OpenUxAS\build
1>Build type: native build
1>Traceback (most recent call last):
1>  File "C:\Program Files\Python36\Scripts\meson.py", line 37, in <module>
1>    sys.exit(main())
1>  File "C:\Program Files\Python36\Scripts\meson.py", line 34, in main
1>    return mesonmain.run(launcher, sys.argv[1:])
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 260, in run
1>    sys.exit(run_script_command(args[1:]))
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 248, in run_script_command
1>    return cmdfunc(cmdargs)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 56, in run
1>    regen(regeninfo, mesonscript, backend)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 42, in regen
1>    subprocess.check_call(cmd)
1>  File "C:\Program Files\Python36\lib\subprocess.py", line 291, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command '['C:\\Program Files\\Python36\\python.exe', 'C:\\Program Files\\Python36\\Scripts\\meson.py', '--internal', 'regenerate', 'C:\\Users\\acfoltzer\\Source\\Repos\\OpenUxAS\\build', 'C:\\Users\\acfoltzer\\Source\\Repos\\OpenUxAS', '--backend=vs2017']' returned non-zero exit status 1.
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "REGEN.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### PR DESCRIPTION
**Pull request by dndanik**
Fixes #1847

### CODE REVIEW

**Comment by nirbheek** [comment]
A better way would probably be to store it in the correct place in the visual studio solution(s).

**Comment by dndanik** [comment]
Parse solution and read version before regen? If visual studio or user modifies the solution platform version can be lost.

**Comment by nirbheek** [comment]
> Parse solution and read version before regen?

Hum, I just realized that we rewrite the solutions from scratch when we regen, so we have to store it externally. However, `WindowsSDKVersion` is not the only env var we have to restore on regen: we have to restore all vars exported by the Visual Studio prompt, so I think this needs to be solved in a more generic way.

**Comment by dndanik** [comment]
Restore all variables or only visual studio specific?
Restore everything or only missing vars after reading currently exported?

**Comment by nirbheek** [comment]
> Restore all variables or only visual studio specific?
> Restore everything or only missing vars after reading currently exported?

That's exactly what @jpakkane and I were discussing at GUADEC on Sunday. This is a difficult problem, and the current-best solution we've got is that we add support in Meson for automatically searching for VS installations and extracting the env: https://github.com/mesonbuild/meson/issues/2622

I already wrote code to do this in another project: https://github.com/GStreamer/cerbero/blob/master/cerbero/ide/vs/env.py#L87

This would be enabled by a new command-line option (not sure what it would be called), and the command-line option itself would be stored and re-used on regen (which means the VS env would be extracted again by us on regen and used). This means we don't have to store any env vars.

**Comment by dndanik** [comment]
>  This would be enabled by a new command-line option
Is this being worked on? If not i'll try to implement automatic search.
Can i reuse code from cerbero?

**Comment by dndanik** [comment]
Can vswhere.exe be shipped with windows meson installer like ninja?

**Comment by nirbheek** [comment]
> Can vswhere.exe be shipped with windows meson installer like ninja?

That's not going to be useful. It can only locate VS 2017 and newer installations, and it installed by those versions in a standard location. So if it can be useful, it will exist.

**Comment by dndanik** [comment]
`vswhere` has what they call legacy support. It can detect root installation directory for vs2010 and newer.

**Comment by nirbheek** [comment]
> vswhere has what they call legacy support. It can detect root installation directory for vs2010 and newer.

Why can't we read the registry for that? `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0` key `InstallDir`, etc.

**Comment by nirbheek** [comment]
We should not require the MSI for this feature because the `pip` installation path is easier in many automated cases, and is the currently best-tested mechanism anyway. We don't even have CI for the MSI installer, and there are known bugs with it.

**Comment by dndanik** [comment]
Well, we can. But we can't for vs2017. `vswhere` is shipped with newer vs2017 versions, but its not in standard paths, so its not usable. 

What I meant is because `vswhare` is universal and the only possible solution for vs2017 it should be used by default. Registry can be used as fallback. Maybe its possible to implement vs2017 support in python.

**Comment by nirbheek** [comment]
> What I meant is because vswhere is universal and the only possible solution for vs2017 it should be used by default. Registry can be used as fallback.

Great, because that's what I've been saying too. We don't need to require `vswhere` for searching, but we can use it when it's available.

**Comment by jpakkane** [comment]
Is this ready to merge as is?

**Comment by nirbheek** [comment]
> Is this ready to merge as is?

No, we should not merge this since it's an incomplete solution. @dndanik were you able to find time to implement the alternative solution I proposed?

**Comment by jpakkane** [comment]
ping

**Comment by john-preston** [comment]
I've started playing with meson vs2017 backend and immediately bumped into this issue.

I generate the initial project from "x86 Native Tools Command Prompt for VS 2017", then I change "meson.build" and it causes REGEN, which resets:

- Platform from Win32 to x64
- WindowsTargetPlatformVersion from the valid SDK version to empty string (which defaults to 8.1 that isn't even installed in my system)

I think there could be more dependencies on the environment in case of more complex projects.

If I understand correctly, this case won't be solved by "automatically searching for VS installations and extracting the env", because I need REGEN to use the same environment that was used for the initial solution generation (it could be x86 or x64 command prompt or whatever).

So it looks like the environment should be saved after all (at least VS-related) and passed to the REGEN. Or did I miss something?

**Comment by jpakkane** [comment]
Is this still needed after #4545 has been merged?

**Comment by jpakkane** [comment]
Asking again: Is this still needed after #4545 has been merged?

**Comment by jpakkane** [comment]
As there have been no replies, I'm going to assume that this is no longer needed and will close it down. If this is still relevant, please reopen.

Thanks,

**Pull request closed without merging**
