### PR TITLE
ci: Don't search for llvm modules with LLVM 16.0.x

### PR DESCRIPTION
**Pull request by nirbheek**
See: https://github.com/mesonbuild/meson/issues/11642

The idea is to keep bumping this version as new LLVM versions are released till this is fixed. That way we won't just forget to re-enable the test once the issue is fixed.

### CODE REVIEW

**Comment by rilian-la-te** [comment]
Bug occurs only with static LLVM?

**Comment by nirbheek** [comment]
> Bug occurs only with static LLVM?

The dynamic test gets skipped because the modules aren't found. I just wanted to be hyper-specific.

**Comment by rilian-la-te** [comment]
@nirbheek did you tried to update `LLVM_MESON_PACKAGE_NAMES` and `LLVM_MESON_VERSIONS`?

**Comment by nirbheek** [comment]
`get_llvm_tool_names()` is already up-to-date, so I am not sure what you are suggesting. If you'd like to take a look, I pasted some info here: https://github.com/mesonbuild/meson/pull/11682#issuecomment-1512120921

And we've been tracking this here: https://github.com/mesonbuild/meson/issues/11642

**Comment by eli-schwartz** [comment]
Updating the tool names fixed about half the cmake+llvm jobs, there used to be a lot more failures.

**Pull request merged**
