### PR TITLE
Add option to run a subset of project tests only.

### PR DESCRIPTION
**Pull request by jukkalaurila**

### CODE REVIEW

**Comment by jukkalaurila** [comment]
The AppVeyor test failure is just a timeout on one run, looks spurious. https://ci.appveyor.com/project/jpakkane/meson/build/5229/job/u0kmi7e2j17e54ke/messages

**Comment by jpakkane** [comment]
Is this really needed. During all of my development the only runs I have needed to do are "run this one test" and "run all tests".

Regardless, we should not expose regexes in command lines. We are actively avoiding having regexes in general and exposed on command lines in general.

**Comment by jukkalaurila** [comment]
When trying to make a particular backend work right and when trying to find which dependencies are the correct ones I found it helpful to be able to run just a subset of tests. Another way of making that iteration faster is by remembering which tests failed and having an option to rerun only those tests. I have some code for that but it isn't ready for merge and the regex approach seems simpler since it's stateless.

Do you not want this feature at all, or do you just not want it implemented with regexes? This is an internal development tool, would this be a place where practicality might beat purity?

**Comment by asartori86** [comment]
@jukkalaurila @jpakkane I also find myself run a subset of tests. If @jpakkane doesn't like to have regex, you can still achieve what you need relying the `suite` keyword of `test()`. I organize my tests in `folder/subfolder/subsubfolder/test_name` and my `meson.build` inside the `tests` folder looks like
```
_tests = ['folder/subfolder/test_01',
               'another/folder/test_01',
               'dir/test_0x']

foreach _t : _tests
    test(_t, executable, suite: _t.split('/'))
endforeach
```

in this way I have the ability to run all and only the tests inside a folder named 'folder' as follows
```
meson test --suite project_name:folder
```

you may want to watch my PR #3369

**Comment by nirbheek** [comment]
> If @jpakkane doesn't like to have regex, you can still achieve what you need relying on the suite keyword of test()

This not about `meson test`, but about `run_project_tests.py` which runs Meson's regression tests.

I think the same thing can be achieved by having a way to pass (multiple) folders inside `test cases` using shell globbing, and selecting folders which contain a `meson.build` file. Maybe we want to do that instead, @jukkalaurila?

**Comment by nirbheek** [comment]
Ping?

**Comment by jon-turney** [comment]
> Is this really needed. During all of my development the only runs I have needed to do are "run this one test" and "run all tests".

Running tests through the project test frame also checks the installed files.  Something like this would have been useful when working on #4480.

**Comment by nioncode** [comment]
Ping

**Comment by jpakkane** [comment]
Superseded by #5515.

**Pull request closed without merging**
