### PR TITLE
Do not automatically set warning flags if buildtype is 'plain'

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by martin-ejdestig** [comment]
Reintroduces weird behavior with mesonconf fixed in https://github.com/mesonbuild/meson/pull/404 .

**Comment by martin-ejdestig** [comment]
Well, not only with mesonconf. See #404 for more details. Do not know which way to go but if this is preferred should werror not be aligned as well? And mesonconf display more clearly that those options are ignored.

(Personally I think that this should be reverted. warning_level and werror can be disabled manually when passing build type plain. But I may just have a weird preference for always building with warnings turned on to the max and have them be errors.)

**Comment by jpakkane** [comment]
There are several use cases (chiefly distro package building) where people want to set all compiler flags from the outside. Because of this werror by default is also not a very good idea because compilers get new warnings all the time, which may render packages unbuildable with newer compilers.

**Comment by martin-ejdestig** [comment]
Yes, I understand. But should 'plain' not remove -Werror as well then? Seems like that is what distro packagers want to get rid of more so than warning flags. It would also be nice if it was communicated better how werror and warning_level are used with 'plain' (maybe wiki has been updated, I have not checked, but also in e.g. mesonconf... right?).

It is also not possible to get standard warnings now if one wants to build with custom optimization flags, but I guess I have to live with that. :(

**Comment by martin-ejdestig** [comment]
Or... maybe only remove -Werror (since that is what will prevent distros from actually building) and leave other warning flags be? (I want to have my cake! :)

**Pull request merged**
