### PR TITLE
Fix many things have have been slightly broken in OSX

### PR DESCRIPTION
**Pull request by jpakkane**
Basically this steals even more stuff from CMake's implementation:

 - pad rpath entry to maximum size
 - use absolute paths for rpaths

Still needs to be added:

 - version flags (see #2577)
 - do the otool magic on install

### CODE REVIEW

**Comment by mojca** [comment]
I tested this with a simple setup:

`testbin.cpp`
```
#include "testlib.h"
#include <iostream>
int main()
{
    std::cout << answer() << std::endl;
    return 0;
}
```
`testlib.h`:
```
#pragma once
int answer();
```
`testlib.cpp`:
```
int answer() { return 42; }
```

`meson.build`:
```
project('Test libraries on mac', 'cpp')

testlib = shared_library('testlib', 'testlib.cpp', install: true)
executable('testbin', 'testbin.cpp', link_with : testlib, install: true)
```

And running
```
meson --prefix /tmp/inst <sources>
DESTDIR=/tmp/dest ninja install
# as well as once without `DESTDIR`
```

I end up with
```
/tmp/inst/lib/testlib.dylib
/tmp/inst/bin/testbin
```
with
```
> otool -L /tmp/inst/bin/testbin
 /tmp/inst/bin/testbin:
	@rpath/libtestlib.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

>  /tmp/inst/bin/testbin
dyld: Library not loaded: @rpath/libtestlib.dylib
  Referenced from: /tmp/inst/bin/testbin
  Reason: image not found
Abort trap: 6
```

Note that the binary works as long as `libtestlib.dylib` is in the current folder which is why you don't notice the failure right away.

**Comment by jpakkane** [comment]
Can you try writing the same in CMake and trying it out? It would be interesting to know if and how they do it. Thanks.

**Comment by mojca** [comment]
I need some more time to figure out what's the proper `CMakeLists.txt` file since a very simple example results in an equally broken library. I've put the (so far incomplete) sources [here](https://github.com/mojca/test-meson-libraries).

**Comment by jpakkane** [comment]
Thanks. I'll merge this now because it improves things and does not seem to regress anything. We can fix the other issues in other MRs.

**Pull request merged**
