### PR TITLE
Workaround for Debian bug 912563.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by tp-m** [comment]
Would be great if you could flesh out the description a bit, so there's a hint of what the problem is and what it affects in the commit message without people having to visit the debian bug. For bonus points, link to debian bug too ;)

**Comment by dcbaker** [comment]
Can you build wmf without freetype?

**Comment by jpakkane** [comment]
I don't know. But since this is blocking transitions in Debian and libwmf is currently unmaintained so ...

**Comment by dcbaker** [comment]
Doesn't look like it is required from a quick glance at their configure.ac, can we add `required : false` to the freetype dependency, just in case?

**Comment by jpakkane** [comment]
I guess it depends on whether we want it to fail when Freetype dev packages are missing even though they are necessary or when whey are missing and necessary.

I hate every single project that insists on inventing its own broken pkg-config replacement so very, very, very much.

**Comment by dcbaker** [comment]
Sigh. I also hate the *-config tools.

**Comment by dcbaker** [comment]
I also really wish that some of these packages that people really want to keep using but are unsupported could get some life breathed back into them. A gitlab or github or something where various distro people could at least fix things like "doesn't have pkg-config", or "the dang *-config tools lies"

**Pull request merged**
