### PR TITLE
Report parisc64 as parisc. Closes #4714.

### LINKED ISSUE #4714: Unknown CPU family 'parisc64'
The HP PA-RISC processors can do 64 bit for ages. However many of the "smaller" (e.g. my C3600) machines are usually operated with a 32 bit kernel if they have less than 4GB RAM:

```
Linux voyager 4.16.0 #1 Tue Apr 3 23:20:04 CEST 2018 parisc PA8600 (PCX-W+) 9000/785/C3600 GNU/Linux
```

Machines with more RAM or certain types of machines require a 64 bit kernel:

```
Linux pioneer 4.19.9 #2 SMP Fri Dec 14 18:57:12 CET 2018 parisc64 PA8800 (Mako) 9000/785/C8000 GNU/Linux
```

The twist is: there is no 64 bit userspace on these machines, so regardless of what the kernel says, the userspace is always 32 bit.

cpuinfo of my C8000 (only first processor):
```
processor       : 0
cpu family      : PA-RISC 2.0
cpu             : PA8800 (Mako)
cpu MHz         : 1000.000000
physical id     : 0
siblings        : 2
core id         : 0
capabilities    : os64 iopdir_fdc needs_equivalent_aliasing (0x35)
model           : 9000/785/C8000
model name      : Crestone Peak Fast?
hversion        : 0x000088b0
sversion        : 0x00000491
I-cache         : 32768 KB
D-cache         : 32768 KB (WB, direct mapped)
ITLB entries    : 240
DTLB entries    : 240 - shared with ITLB
bogomips        : 1988.60
software id     : 6266852346624179925
```

For reference, this is my single-core C3600 running a 32 bit kernel:
```
processor       : 0
cpu family      : PA-RISC 2.0
cpu             : PA8600 (PCX-W+)
cpu MHz         : 552.000000
capabilities    : os32 os64 nva_supported (0x03)
model           : 9000/785/C3600
model name      : Allegro W+
hversion        : 0x00005cf0
sversion        : 0x00000481
I-cache         : 512 KB
D-cache         : 1024 KB (WB, direct mapped)
ITLB entries    : 160
DTLB entries    : 160 - shared with ITLB
bogomips        : 1099.77
software id     : 2001234816
```

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by dcbaker** [comment]
So I talked with one of the gentoo parisc maintainers. I'm not sure that this is the right thing to do, he said this is active work to get a 64bit userland for parisc on Linux. I'm wondering if we really need to differentiate 64 bit kernel and 64 bit userland somehow.

**Comment by jpakkane** [comment]
Is there going to be multi-arch support like with x86_64? That is that you can run both 32 and 64 bit userlands at the same time?

**Comment by dcbaker** [comment]
I'll ask

**Comment by dcbaker** [comment]
It seems like the plan is to allow a 64bit kernel to run both a 32 bit and 64 bit userland.

Matt seems to think this patch is fine as-is though for now. If the 64bit userland actually happens we can re-evaluate then?

**Comment by jpakkane** [comment]
They are the subject matter experts. If it's fine by them. it's fine by me.

**Pull request merged**
