### PR TITLE
gtkdoc: Pass the linker down to gtkdoc-scangobj

### PR DESCRIPTION
**Pull request by xclaesse**
This fixes issue #2540

### CODE REVIEW

**Comment by jpakkane** [comment]
The commit message should end with `Closes #2540.` This will cause the bug to be autoclosed on merge.

**Comment by xclaesse** [comment]
I didn't know that trick. I pushed a new commit. Thanks.

**Comment by jpakkane** [comment]
Thanks.

**Comment by QuLogic** [comment]
It also works in the description field. https://help.github.com/articles/closing-issues-using-keywords/

**Pull request merged**
