### PR TITLE
Fix Visual Studio version detection for the `vs` backend

### LINKED ISSUE #2848: Visual Studio REGEN target fails when using `vs` backend
The version auto-detection does not work when building the `REGEN` target in Visual Studio, if meson was initially invoked with `--backend=vs`.

```
1>------ Build started: Project: REGEN, Configuration: debug Win32 ------
1>Checking whether solution needs to be regenerated.
1>The Meson build system
1>Version: 0.45.0.dev1
1>Source dir: C:\msys64\home\Polarina\mysa
1>Build dir: C:\msys64\home\Polarina\mysa\build
1>Build type: native build
1>Traceback (most recent call last):
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 365, in run
1>    app.generate()
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 151, in generate
1>    self._generate(env)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 174, in _generate
1>    g = vs2010backend.autodetect_vs_version(b)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 38, in autodetect_vs_version
1>    if vs_version == '14.0' or 'Visual Studio 14' in vs_install_dir:
1>TypeError: argument of type 'NoneType' is not iterable
1>Traceback (most recent call last):
1>  File "C:\Users\Polarina\AppData\Local\Programs\Python\Python36-32\Scripts\meson.py", line 26, in <module>
1>    sys.exit(main())
1>  File "C:\Users\Polarina\AppData\Local\Programs\Python\Python36-32\Scripts\meson.py", line 23, in main
1>    return mesonmain.run(sys.argv[1:], launcher)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 322, in run
1>    sys.exit(run_script_command(args[1:]))
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 278, in run_script_command
1>    return cmdfunc(cmdargs)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 55, in run
1>    regen(regeninfo, mesonscript, backend)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 41, in regen
1>    subprocess.check_call(cmd)
1>  File "c:\users\polarina\appdata\local\programs\python\python36-32\lib\subprocess.py", line 291, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command '['c:\\users\\polarina\\appdata\\local\\programs\\python\\python36-32\\python.exe', 'C:\\Users\\Polarina\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\meson.py', '--internal', 'regenerate', 'C:\\msys64\\home\\Polarina\\mysa\\build', 'C:\\msys64\\home\\Polarina\\mysa', '--backend=vs']' returned non-zero exit status 1.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "REGEN.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### PR DESCRIPTION
**Pull request by polarina**
When Visual Studio invokes the REGEN target, only the
VisualStudioVersion environment variable is set and VSINSTALLDIR left
unset. The version checker did not like this state of affairs.

Fixes #2848

### CODE REVIEW

**Comment by nirbheek** [comment]
This gets rid of the error, but it's not the correct solution. We should store the VS version being used in coredata and reuse it on regen so we don't have to do autodetection at all. With this patch, the autodetection might detect the wrong version on regen.

**Comment by polarina** [comment]
Would it not be appropriate auto-detect the VS version the solution file is opened in? For example, I invoke meson from the VS2015 dev console, open it up in VS2017 and hit REGEN.

Nevertheless, I still believe the patch is needed. It'll fail the same way if VSINSTALLDIR is not defined when meson is invoked from a VS2017 dev console.

**Comment by nirbheek** [comment]
> Would it not be appropriate auto-detect the VS version the solution file is opened in? For example, I invoke meson from the VS2015 dev console, open it up in VS2017 and hit REGEN.

In the case you're talking about, the behaviour should be to generate VS2015 files again, since running REGEN from inside VS2017 won't give us the VS2017 dev tools environment and we might generate subtly-wrong solutions.

VS 2017 can handle solutions generated for VS2015 just fine, so that's safer.

What's more interesting is what to do if you configure a project inside the VS2015 dev tools env, and then regen inside the VS2017 dev tools env. I think in that case we should use the new env since that is what people will expect. This does, however, raise interesting questions about how to handle, for instance, cached dependencies.

**Comment by nirbheek** [comment]
> Nevertheless, I still believe the patch is needed. It'll fail the same way if VSINSTALLDIR is not defined when meson is invoked from a VS2017 dev console.

I don't think that case can ever occur unless you have a broken dev env. IIRC, `VSINSTALLDIR` is always defined, but you can't always look at its value to figure out what version of VS you have since the user can change it.

However, yes, we should merge this patch anyway, but please rephrase the commit message to say that.

**Comment by nirbheek** [comment]
> However, yes, we should merge this patch anyway, but please rephrase the commit message to say that.

On second thoughts, we should probably consider `VSINSTALLDIR` not being defined to be an error condition and error out with a nice `MesonException` message.

**Pull request merged**
