### PR TITLE
Upgrade CI image to Ubuntu Zesty.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm still getting:
```
Failed test during validate: 'test cases/frameworks/14 doxygen'
Reason: Expected file usr/share/doc/spede/html/classComedy_1_1Comedian.png missing.
Expected file usr/share/doc/spede/html/classComedy_1_1Spede.png missing.
```
Is zesty doxygen still too old?

**Comment by jpakkane** [comment]
This is weird, because the current CI is running Zesty and it passes without issues. What distro and version are you using?

For comparison the test also passes on Debian Sid and Fedora (don't remember offhand which version).

**Comment by QuLogic** [comment]
Fedora 25; doxygen 1.8.13. Instead of those files, I have `classComedy_1_1Comedian__inherit__graph.png`, `classComedy_1_1Spede__coll__graph.png`, `classComedy_1_1Spede__inherit__graph.png`, and a few others with mostly unspecific names.

**Comment by jpakkane** [comment]
I have no idea what is going on there. Doxygen 1.8.13 on Fedora passes tests on current trunk without any issues.

**Comment by nirbheek** [comment]
Same version of Doxygen as @QuLogic:

> Failed test during validate: 'test cases/frameworks/14 doxygen'
> Reason: 
> Expected file usr/share/doc/spede/html/classComedy_1_1Spede.png missing.
> Expected file usr/share/doc/spede/html/classComedy_1_1Comedian.png missing.

The following files were installed:

> usr/share/doc/spede/html/classComedy_1_1Comedian__inherit__graph.png
> usr/share/doc/spede/html/classComedy_1_1Spede__coll__graph.png
> usr/share/doc/spede/html/classComedy_1_1Spede__inherit__graph.png

**Pull request merged**
