### PR TITLE
mesontest: Allow defining 'arbitrary' extra variables for test

### LINKED ISSUE #1105: mesontest: Allow passing extra data to test runner to run, for example inside GDB or valgrind
The conversation started here: https://github.com/mesonbuild/meson/pull/1087

Basically in GStreamer we need to set several env variable so the test can run in GDB:

For gdb:
 * `CK_FORK=no`

For Valgrind:
 * `CK_DEFAULT_TIMEOUT=360`
 * `G_SLICE=always-malloc`

We do not want to need our users to know about that as it is not intuitive and even myself that I am very aware of that forgot and got weird results making me loose time for nothing.

My approach in the previously linked pull request is to allow extra data in the `test` target to be consume at later time in the `mesontest` tool or possibly in other specific tool from meson users.

I implemented it with `gdb_env` as an extra argument known by the `mesontest` tool and we would need to add at least `valgrind_env` in there too.

### PR DESCRIPTION
**Pull request by thiblahute**
Those should be used exclusively by the mesontest tool
currently we support only 'gdb_env' in the test tool

Fixes #1105

### CODE REVIEW

**Comment by jpakkane** [comment]
I'm really not fond of this approach. This means that there can only be one set of these settings and in order to change them you need to edit the build definition files. The design of Meson has been to keep as much stuff away from build definitions as possible (see for example cross compilation args which are in the cross file).

As an example there are many different ways to set up what settings should be used for Valgrind (which tool to use, settings, suppressions etc). Putting all of that inside `meson.build` files make it bloaty and hard to understand.

Could we instead do this by having a standalone file that has all the extra settings? Then you could do something like this:

    mesontest.py --settings gdb_state.txt <test name>
    mesontest.py --settings plain_valgrind.txt <other args>
    mesontest.py --settings helgrind_valgrind.txt <other args>

And so on. This way `meson.build` only defines *what* is needed to run a test, not *how* it should be run. If projects have some specific setup they use often, they can create a `run_target` for it.

**Comment by thiblahute** [comment]
> And so on. This way meson.build only defines what is needed to run a test, not how it should be run. If projects have some specific setup they use often, they can create a run_target for it.

Well in the 2 examples it is really about what is needed to run the tests inside GDB and valgrind, that setting approach might make sense for more specific case but I do not think the user should specify anything else than --gdb to run a test in GDB.

**Comment by jpakkane** [comment]
That would still be possible. Settings is just for extra stuff (though it could also contain some directive to use gdb).

**Comment by thiblahute** [comment]
Then I do not understand what you mean I guess, how would you have a GStreamer developer launch a specific test inside GDB with what you descibe?

**Comment by jpakkane** [comment]
If you just want to run it under gdb:

    mesontest.py --gdb testname

If you wish to add more settings in the environment:

    mesontest.py --gdb --settings gdbsettingsfile.txt testname

**Comment by thiblahute** [comment]
Right, so to run GStreamer tests you need to set some special settings
because otherwise test will not run under gdb (as they will run in a fork),
I really want to avoid that.

**Comment by jpakkane** [comment]
Yes, we want to support that but putting this stuff in Meson files is not good due to the following reasons:

 - you can have only one setting for gdb (and others), but you may want to run stuff with different gdb setups
 - the same for Valgrind, which has many different setups
 - if the settings are in Meson files, then changing requires Meson reinit before they are usable
 - adding lots of test configuration settings makes build definition files poorly readable

We need to come up with a better user experience for this use case. Maybe something like I mentioned above, maybe something completely different.

**Comment by thiblahute** [comment]
I think we are confusing 2 scenarios here, 1. the various possible settings of the wrapper 2. the minimal set of env variables and possibly parametters for the wrapper to be usable for the tests, that part should be described in the meson build definition I believe.

I am trying to solve 2) in that issue, nothing more.

**Comment by jpakkane** [comment]
Let's bring this down to a bit more concrete level. We are going to need to be able to run Valgrind with many settings (memcheck and hegrind, with and without suppression files). We are probably going to need to do gdb with multiple settings too. How would this setup look like in your proposed method? Where would the settings be saved? How would one invoke them?

**Comment by thiblahute** [comment]
My proposal is not solving that at all, just solving the case where to just run the test in GDB/valgrind (with any setting), you need to set the env var `CK_FORK=no` and `G_SLICE=always-malloc` so that the tool can run properly, this is the problem I want to fix and I want it to be transparent to the user (today I lost time again because I forgot to set `CK_FORK` using `--gdb`... :))

**Comment by jpakkane** [comment]
> just solving the case where to just run the test in GDB/valgrind (with any setting)

What if you don't have one setting but two? Say for some debugging you need `FOO=bar` and for other debugging `FOO=baz`?

An alternative way of saying the same is what happens if sometimes you need to do gdb _without_ those settings? Editing Meson files to get rid of them is not a particularly nice user experience.

The reason I'm focusing on this is that these two cases are very tightly tied together. Any solution we come up with must provide for both of these. Only doing one of them is not nice.

As an example, we could make a new option, say `gdb_env` that is used for this. Then you could set a default value in project options and still change it when needed.

**Comment by thiblahute** [comment]
> As an example, we could make a new option, say gdb_env that is used for this. Then you could set a default value in project options and still change it when needed.

Well it is basically what I am meaning to do here, just that I am doing it generically so that we do not have the knowledge of what gdb is in meson core, but only in the test launcher. I did it that way moving away that knownledge from meson core because in https://github.com/mesonbuild/meson/pull/730 you said:

> Having both valgrind args and gdb args is a bit suspect. If we add more wrapper tools (including lldb) then the number of arguments grows and grows. The test runner should probably not know anything of these but just get a general array to put in front of of the command. The idea is to also get all valgrind stuff away from Meson core.

**Comment by nirbheek** [comment]
Branch now has conflicts.

**Comment by tp-m** [comment]
It's not just environment variables, what about command line args for suppression files?

This stuff needs to be set in the meson.build file IMHO, everything else is not user friendly and renders the new tool not as useful as it could be (then we might just as well write our own test runners).

**Comment by jpakkane** [comment]
The design of Meson has been to keep separate things as separate as possible. For example all cross compilation information is stored in the cross file rather than being splattered all over the build definitions. Similarly here we should only define the core properties of a test in meson.build and have a different mechanism for running it with different environments etc.

As a wild speculation we could define a standalone file that describes a test setup. You would use it something like this:

    mesontest --settings ../testsetup/gdb.testset --repeat 1000 mytest
    mesontest --settings ../testsetup/valgrind.testset mytest
    mesontest --settings ../testsetup/helgrind.testset mytest

**Comment by jpakkane** [comment]
Or how about this: we create a file at the top level called, say, `meson_testsetup.txt`, which behaves like `meson_options.txt`. Its contents would be roughly like the following:

    test_setup('valgrind', wrap : ['valgrind'])
    test_setup('gdb', gdb : true, env : ['CK_FORK=no', 'G_SLICE=always-malloc'], repeat=1000)

And which you would then use with:

  mesontest --setup=gdb mytest

**Comment by nirbheek** [comment]
What's the advantage of putting it in a separate file vs putting it next to the tests themselves? I think having a proliferation of files which have to be checked and edited whenever you want to change something is an anti-pattern. It hearkens to m4 where everything is not defined in configure.ac, and you often need to look in several different m4 directories to check where things might be getting pulled in from.

I think those functions could easily be placed in meson.build files.

**Comment by jpakkane** [comment]
Now that we have a proper syntax, I guess we could put those in the meson.build files, maybe `meson.add_test_setup(...)`. I originally came up with the standalone file for reasons such as:

 - all test setup code is in one place, no need to hunt for definitions in your build files
 - if if is a standalone file, it can be parsed by mesontest, so test setups can be changed without needing to reconfigure the project

But these are not that important. Usability and understandability are the most important things.

**Comment by trhd** [comment]
How about allowing users to define their own wrappers? Meson could include sensible defaults for wrappers such as valgrind and gdb but those should be easily overridable.

E.g. one could have in their source directory files such as:

valgrind.wrap (/.mesonwrap/.wrapconf/.wrapper/.whatever)
gdb.wrap
gdb-alternative.wrap
my-fancy-own-thing.wrap

These files could then include things like the wrapper command, custom environment variables and extra arguments for the wrapper. .

These could be used in the following manner:

mesontest -C build --wrap valgrind
mesontest -C build --wrap gdb
mesontest -C build --wrap gdb-alternative
mesontest -C build --wrap my-fancy-own-thing

If too many .wrap files sounds frightening then all the wrappers could be defined in a single file (or even in the main meson.build). Overridability and the ability of creating your own wrappers being the key here.

I think @jpakkane was thinking something similar above with the test_setup() approach, but I don't really see the benefit of introducing a "setup" abstraction here. "Setups" could perhaps be used to define some sort of test sets but including wrapper arguments in those wouldn't feel right to me.

E.g.:

mesontest -C build --setup ci-tests
mesontest -C build --setup ci-tests --benchmark --wrap fancy-profiler
mesontest -C build --setup stress-testing --wrap valgrind

**Comment by jpakkane** [comment]
We already have what you call setups, they are called "suites". Those define which subset of tests to run. Setups define how they are run.

**Comment by jpakkane** [comment]
This is implemented in the test setup branch which was just merged. Closing.

**Pull request closed without merging**
