### PR TITLE
Fix meson multiple version contraint error

### PR DESCRIPTION
**Pull request by mikolajpp**
As per #3133, this fixes the bug.

### CODE REVIEW

**Comment by sarum9in** [comment]
I think failure is relevant. The following test is supposed to fail, but it passes.

`meson.build`:
```meson
project('master', 'c')

x = subproject('foo', version : '>1.0.0')
```

`subprojects/foo/meson.build`:
```meson
project('foo', 'c', version : '1.0.0')
```

**Comment by mikolajpp** [comment]
This is strange, but I am not at all familiar with meson codebase. My change uses an array of constraints which meson is supposed to support but does not.

I thought this was simple enough, but it seems it will need more digging.

**Comment by sarum9in** [comment]
Unless you figure this out faster I will try to debug it this weekend :)

**Comment by nirbheek** [comment]
@sarum9in were you able to find some time for this?

**Comment by sarum9in** [comment]
Hmm github is weird, I managed to fix this code, but force push closed the issue, follow up in #3671

**Pull request closed without merging**
