### PR TITLE
boost: Allow older behavior with a warning

### LINKED ISSUE #2813: Boost not detected on Fedora 27
I installed `boost-devel` as well as `boost-static` using `dnf` on Fedora 27. I am including boost in a Meson project with

```
dep_boost = dependency('boost', modules : ['filesystem', 'system', 'asio'])
```

Which results in the following error messages:

```
WARNING: Invalid Boost modules: asio
Dependency Boost (filesystem, system, asio) found: NO

Meson encountered an error in file meson.build, line 69, column 0:
Dependency "boost" not found
```

I also installed `boost-*`, which didn't help. Meson version is `0.44.0`. Works fine with `0.42.1`.

To me this does not seem to be related to #2547 and #2564, my locale is English.

### PR DESCRIPTION
**Pull request by NickeZ**
Fixes #2813

### CODE REVIEW

**Comment by NickeZ** [comment]
@nirbheek I think this allows exactly the same behavior as the previous version.

**Comment by nirbheek** [comment]
This implementation will silently ignore all invalid modules, not just header-only modules. Do we want to do this or do we want to maintain a list of header-only modules we were previously allowing and silently ignore only those?

**Comment by NickeZ** [comment]
> silently ignore all invalid modules, not just header-only modules

I'm not really sure how to interpret you. It prints a warning when it ignores an invalid module. And it only accepts header directories in `<include-dir>/boost` as modules. The only difference to the old-old implementation is that this prints a warning.

In general, most of the modules are header-only and most of the rest can be configured to be used as header-only. I'm not sure how to compile a list of "previously accepted header-only libs". IMO the only way to compile such a list would be to go through the documentation for each module on the boost website. Each module is documented differently which makes it tedious.

**Comment by nirbheek** [comment]
> I'm not really sure how to interpret you. It prints a warning when it ignores an invalid module.

I meant, that earlier we would error out if we found an unknown module, and we accepted header modules just fine. Now it seems we will warn if any unknown module is used without erroring out?

If this change sounds ok to you, we can do it. I just want to be sure. :)

Perhaps we should error out on unknown modules and warn on header modules? Unless that's too much work or you think that's not the right way to do things.

**Comment by NickeZ** [comment]
>  Now it seems we will warn if any unknown module is used without erroring out?

I think we agree and that we only misunderstood each other. I made a failing test to prove that it fails if you write something arbitrary, like "abc", as a module.

> Perhaps we should error out on unknown modules and warn on header modules?

This is exactly the behavior I intended to implement (and hopefully have implemented).

**Comment by NickeZ** [comment]
rebased because of flaky test

**Pull request merged**
