### PR TITLE
Enable get_pkgconfig_variable for python3 dependencies (if pkg-config is used)

### PR DESCRIPTION
**Pull request by madebr**
fixes mesonbuild/meson#2508

My first PR for meson..

### CODE REVIEW

**Comment by jpakkane** [comment]
Please update one of the Python 3 tests to use this new functionality. I.e. call it and check that the result is (somehow) valid.

**Comment by jpakkane** [comment]
ping

**Comment by madebr** [comment]
pong

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
