### PR TITLE
Bug fix - KeyError on subproject without default options

### PR DESCRIPTION
**Pull request by dimkr**

### CODE REVIEW

**Comment by jpakkane** [comment]
Please add yourself at the end of `authors.txt`. Thanks.

**Comment by dimkr** [comment]
@jpakkane, this occured when I called `subproject()` without specifying `default_options`, while `default_project_options` isn't empty.

**Comment by nirbheek** [comment]
I have a test for this already, with your permission @dimkr can I push it to this PR?

**Comment by dimkr** [comment]
@nirbheek, that was quick! I was going to push a test I just wrote, but you beat me to it. Go ahead.

**Comment by nirbheek** [comment]
PR is ready to merge.

**Pull request merged**
