### PR TITLE
Detect OpenMP on macOS with Apple's Clang (rebased on `master`)

### PR DESCRIPTION
**Pull request by lesteve**
Supersedes and closes #13079. I followed @tristan957's advice in https://github.com/mesonbuild/meson/pull/13079#issuecomment-2186833677.

### CODE REVIEW

**Comment by jpakkane** [comment]
[Do not use merges, only rebases](https://mesonbuild.com/Contributing.html#keeping-pull-requests-up-to-date).

**Comment by lesteve** [comment]
OK thanks a lot for your feed-back, I used rebase this time and force pushed.

> sorry for dropping the ball on this, I've been super busy at work the last few weeks and haven't had as much time for keeping track of Meson stuff,

@dcbaker no worries, I completely understand and thanks a lot for you work on this!

**Comment by jpakkane** [comment]
Since this is a fairly hefty change, it will only be considered for 1.5 if there is an rc2.

**Comment by eli-schwartz** [comment]
I think we are going to want an rc2 anyway. Changes look good to me. In it goes.

**Comment by lesteve** [comment]
Great to see this merged, thanks a lot everyone!

**Pull request merged**
