### PR TITLE
Support / operator on lists

### PR DESCRIPTION
**Pull request by bonzini**
This makes it easy to create an array of filenames inside a subdirectory.  For example, suppose various directories in a project have a `trace-events` file, they can all do:

    trace_subdirs += [meson.current_source_dir()]

and then the result can be used like this:

    custom_target(..., sources: trace_subdirs / 'trace-events')

Of course it is also possible to do, in each subdir, something like `trace_events_files += files('trace-events')`. However, that introduces duplication and it does not enforce uniform file names because it allows the usage of arbitrary names. (_EDIT_: unfortunately `files` does not work, see [here](https://github.com/mesonbuild/meson/pull/5082#issuecomment-473813351)).

### CODE REVIEW

**Comment by dcbaker** [comment]
I'm pretty strongly against this. It's too much magic and it's not at all clear what this would do in all cases. What happens in the following cases:
```meson
a = files('foo.c, 'bar.c')  # files returns a list
b = a / 'foobar'

b = ['subdir1', 'subdir2']
c = b / 'subsubdir'

c = [0]
d = c / 'foo'
```

I can come up with a bunch more cases where this is going to be a nightmare. honestly this can already be handled easily and explicitly with a foreach loop:
```meson
trace_subdirs = ['subdir1', 'subdir2']
_temp = []
foreach s : trace_subdirs
  _temp += s / 'trace-events'
endforeach
trace_subdirs = _temp
```

**Comment by jpakkane** [comment]
> Of course it is also possible to do, in each subdir, something like trace_events_files += files('trace-events').

This is the "mesonic" way of doing things and something we have recommended people to do for a long time.

**Comment by bonzini** [comment]
@dcbaker All of these behave in pretty much the only expected way: string operators are auto-listified, everything else gives an error

``` meson
a = files('foo.c', 'bar.c')  # files returns a list
b = a / 'foobar'
# -> ERROR: The division operator can only append to a string.

b = ['subdir1', 'subdir2']
c = b / 'subsubdir'
# -> c = ['subdir1/subsubdir', 'subdir2/subsubdir']

c = [0]
d = c / 'foo'
# -> ERROR: The division operator can only append to a string.
```

I can certainly use foreach and `+=`, but (besides being quadratic due to variable immutability) imperative idioms are unnecessarily harder to-read. This seemed very natural to me as a "mesonic" expression of Bourne shell `{a,b,c}/file.c` or Makefile `$(var:%=%/file.c}`.

@jpakkane: 

> > Of course it is also possible to do, in each subdir, something like `trace_events_files += files('trace-events').`
>
> This is the "mesonic" way of doing things and something we have recommended people to do for a long time.

And it has the disadvantage that now people can name the file the way they want; it reduces consistency. If you mean that you have recommended people to use `files` instead of `meson.current_source_dir()`, then I totally agree and that's exactly why I also would like to have `path()` so that file objects are used more.

**Comment by jpakkane** [comment]
> And it has the disadvantage that now people can name the file the way they want

That's more of a code review question, since you can't really force naming any other way. For example assume you have an array `foo` that is set up in the way you describe. There is nothing preventing someone from later on doing this:

```meson
foo += wrongly_named_file
```

**Comment by bonzini** [comment]
Everything is ultimately a matter of code review, but code can be written to make it easier or harder to follow the conventions. My intent with this feature and `path()` is to make it easier to establish conventions that code review will enforce over a few dozen `meson.build` files.

(Besides, it's not true that you can have `foo += wrongly_named_file` if foo is defined and used in the same file).

**Comment by bonzini** [comment]
Also, passing file names from the subdirectories makes it harder to build output files (each `trace-events` file results in a `trace-events.h` file, plus there is a single project-global `trace-events.c` file). So `files(...)` would not be a good replacement; only @dcbaker's suggested foreach loop could be (but I still maintain it is too ugly compared to `dirs / 'trace-events'` and `dirs / 'trace-events.h'`).

**Comment by nirbheek** [comment]
All features require maintenance, so we only add features when there's a use-case that would be impossible without it, or if the syntactical improvement would be widely appreciated. This doesn't really fit that at all. We can of course revisit this in the future if the situation changes.

**Comment by bonzini** [comment]
Should I resubmit the first patch separately?

**Comment by nirbheek** [comment]
> Should I resubmit the first patch separately?

Yes, please!

**Comment by bonzini** [comment]
Ok, done. I'll close this and #4923 for now. I hope I will be able to show a compelling example after I can publish my conversion of QEMU, for now it's not a blocker.

**Pull request closed without merging**
