### PR TITLE
Detect (non-Apple) clang as objc compiler

### PR DESCRIPTION
**Pull request by hasebastian**

### CODE REVIEW

**Comment by nirbheek** [comment]
So, this was never noticed in the Travis CI because we don't set `OBJCC` and `OBJCXX` in `.travis.yml` while running `./run_tests.py`. Could you please fix that and also add yourself to `authors.txt`?

**Comment by jpakkane** [comment]
Please add yourself at the end of `authors.txt` and we'll merge this.

**Comment by jpakkane** [comment]
This has merge conflicts, please rebase against master.

**Comment by nirbheek** [comment]
Fwiw, I've included your commits in #1408, so you can close this if you like instead of doing a rebase. Your patches will make it into master. :smile:

**Comment by nirbheek** [comment]
This has been merged, thanks!

**Pull request closed without merging**
