### PR TITLE
Bump minimum supported Python from 3.4 to 3.5.

### PR DESCRIPTION
**Pull request by jpakkane**
The time has come.

### CODE REVIEW

**Comment by nirbheek** [comment]
Maybe we should get @ignatenkobrain's opinion on this for RHEL EPFL support. I, personally, don't mind supporting Python 3.4 right now since there's no compelling feature that I want from Python 3.5.

**Comment by ignatenkobrain** [comment]
We still don't have 3.5+ in EPEL =(

**Comment by jpakkane** [comment]
How long will it take until either:

 - EPEL does have 3.5
 - every distro that still uses EPEL for Python 3 goes EOL

**Comment by TingPing** [comment]
> every distro that still uses EPEL for Python 3 goes EOL

RHEL 7 goes into extended support in 2024 I believe, which gives it a few more years of support past that.

**Comment by jpakkane** [comment]
I can categorically say that we are _not_ going to wait until 2024 to upgrade the Python dependency.

**Comment by nirbheek** [comment]
I have always been in favour of a policy saying that as soon as we require a large enough feature from Python 3.5 to implement something in Meson, we should bump the requirement. Otherwise there is no rational reason to upgrade the requirement.

Off the top of my head, one such feature is the async/await stuff, but till we actually use it...

**Comment by nirbheek** [comment]
Another reason to bump would be when Python 3.4 gets EOLed. It is still getting security updates, unlike Python 3.3 which *has* been EOLed as of September 2017. I expect it will be EOLed sometime in 2018.

**Comment by ignatenkobrain** [comment]
Let's jump directly to 3.6 and use `typing`! Now EPEL has 3.6 :P

**Comment by jpakkane** [comment]
We can't do 3.6 yet because Debian stable has 3.5, but I'll merge this as soon as the tests pass.

**Pull request merged**
