### PR TITLE
Fix path for str arguments to depend_files

### LINKED ISSUE #2633: depend_files in subdir looks in parent
Not sure if this is by design, but if I have a subdir with the files `foo.in` and `file`, and:

~~~Meson
# meson.build
subdir(src)

# src/meson.build
custom_target('foo',
  build_by_default : true,
  depend_files : 'file',
  input : 'foo.in',
  output : 'foo.out',
  command : [
    ...
  ]
)
~~~

then building fails with

> ninja: error: '../file', needed by 'src/foo.out', missing and no known rule to make it

whereas if I use `files('file')` instead of `'file'` it works.

If I put `file` in the parent folder it also builds. I kind of assumed that referring to `'file'` inside the build file of the subdir would just work, like referring to `'foo.in'` does.

### PR DESCRIPTION
**Pull request by jibsen**
This is an attempt to fix #2633.

I can't get the unit tests to run locally (looks like it fails due to meson not being on same drive as temp directory), so opening a PR to see what CI says.

### CODE REVIEW

**Comment by jpakkane** [comment]
This should have a corresponding test so we don't regress accidentally in the future.

**Comment by jibsen** [comment]
Not sure what the process is for adding tests, but I made an attempt.

**Comment by jibsen** [comment]
Let me know if this needs a rebase at some point, I believe the test directory number is taken now.

**Comment by jibsen** [comment]
The test fails with current master on the ninja backend because it actually checks the dependency is there. It doesn't fail with the vs backend because even though the path is wrong and points to a non-existent file, it doesn't seem to complain. I checked the vcxproj file and the path looks correct after this commit.

**Comment by jibsen** [comment]
The CI fail looks unrelated.

**Pull request merged**
