### PR TITLE
FAQ.md: Add an entry for generated headers

### PR DESCRIPTION
**Pull request by nirbheek**
Closes https://github.com/mesonbuild/meson/issues/5624

### CODE REVIEW

**Comment by tp-m** [comment]
Not directly related, but I wonder if we already have an FAQ entry for "Do I need to specify headers in the sources list?"

**Comment by nirbheek** [comment]
> Not directly related, but I wonder if we already have an FAQ entry for "Do I need to specify headers in the sources list?"

Added since it was somewhat related.

**Comment by eli-schwartz** [comment]
The docs look reasonable to me and give a great answer to the question that was confusing me in the referenced issue.

**Comment by jpakkane** [comment]
Good stuff.

**Pull request merged**
