### PR TITLE
Add test for VS building installable static lib linking against lib with generated source

### PR DESCRIPTION
**Pull request by jenatali**
See https://github.com/mesonbuild/meson/issues/9235

### CODE REVIEW

**Comment by xclaesse** [comment]
Thanks, easier for me to run it locally. I can even reproduce on Linux with ninja backend:
```
[3/7] Compiling C object libstatic_lib.a.p/meson-generated_.._generated.c.o
FAILED: libstatic_lib.a.p/meson-generated_.._generated.c.o 
ccache cc -Ilibstatic_lib.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libstatic_lib.a.p/meson-generated_.._generated.c.o -MF libstatic_lib.a.p/meson-generated_.._generated.c.o.d -o libstatic_lib.a.p/meson-generated_.._generated.c.o -c generated.c
cc: error: generated.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
```

**Comment by jenatali** [comment]
Hm, that looks to be a different error, seems the trivial python script I used for copying the file (wasn't sure if `configure_file` would reproduce it, and Windows doesn't have a `copy.exe`) might not be portable.

**Comment by jenatali** [comment]
My bad, didn't test thoroughly enough, had a local `generated.c` file, the copy script didn't actually work.

**Comment by jenatali** [comment]
There we go, looks like there needs to be a `json` file added to make the successful ninja tests happy, but the VS job "vs2019 vc2019x64vs" job reproduced the exact error I was seeing.

**Comment by eli-schwartz** [comment]
@xclaesse I cannot reproduce your "I can even reproduce on Linux with ninja backend".

```
$ ninja -v  libstatic_lib.a.p/meson-generated_.._generated.c.o 
[1/2] /usr/bin/python ../copyfile.py ../generated_source.c generated.c
[2/2] ccache cc -Ilibstatic_lib.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libstatic_lib.a.p/meson-generated_.._generated.c.o -MF libstatic_lib.a.p/meson-generated_.._generated.c.o.d -o libstatic_lib.a.p/meson-generated_.._generated.c.o -c generated.c
```
[build.ninja](https://github.com/mesonbuild/meson/files/7133720/build.ninja.txt)

**Comment by xclaesse** [comment]
> @xclaesse I cannot reproduce your "I can even reproduce on Linux with ninja backend".

it was a bug in the test case, @jenatali updated it since.

**Comment by eli-schwartz** [comment]
Ah okay, yeah, that would make more sense.

As for actual Linux errors, idk what's wrong with the CI, it is failing in mpi. Probably transient errors?

**Comment by jenatali** [comment]
Closing since this was merged via #9274

**Pull request closed without merging**
