### PR TITLE
Patches pending for 0.58.2 milestone

### PR DESCRIPTION
**Pull request by bonzini**
Since I would like to use a 0.58 release with #8900, maybe I can help by doing the backports in the [0.58.2 milestone](https://github.com/mesonbuild/meson/milestone/63?closed=1) myself. :)

### CODE REVIEW

**Comment by jpakkane** [comment]
The release is done automatically by a script based on milestone tags. This is up to @nirbheek.

**Comment by bonzini** [comment]
Ok, there are some conflicts though.

**Comment by nirbheek** [comment]
This is the script that I use: https://github.com/nirbheek/stable-release-script

Thanks for opening this PR, I will use it to resolve the cherry-pick conflicts I find when preparing the branch.

If there are no other issues that need to go into a stable release, I can cut 0.58.2 tomorrow.

**Comment by bonzini** [comment]
#8972 would be nice because it's a regression, but it's not in mainline yet.

**Comment by nirbheek** [comment]
> #8972 would be nice because it's a regression, but it's not in mainline yet.

We aren't in a hurry to make this release AFAIK, should be fine to wait.

**Comment by jpakkane** [comment]
I missed that it was a regression, so should have been merged before rc1. If there is an rc3 then we'll definitely merge it in. However at the moment it does not seem like there will be a third one. Putting it in a release now without an rc is a bit risky.

How about merging it to master immediately on release and putting it in 0.59.1 and you can put it in 58.2 if you want?

**Comment by nirbheek** [comment]
> How about merging it to master immediately on release and putting it in 0.59.1 and you can put it in 58.2 if you want?

Sounds good to me. In the past we've stopped doing stable releases for a release after a new release is made, but that's actually not the common practice. It is definitely useful to continue doing stable releases as long as people have confidence that stable releases don't break their builds.

**Comment by nirbheek** [comment]
@bonzini your backport of the text-encoding / pathlib patches was super useful, thanks! I've manually merged those three patches from this branch and cherry-picked the remaining patches (incl two new ones that were added to the milestone after this PR was made). Closing this MR now :slightly_smiling_face:

**Pull request closed without merging**
