### PR TITLE
Bump minimum supported Python version to 3.6. Closes #6297.

### LINKED ISSUE #6297: Minimum supported Python 3 version bump
At some point we should update the minimum version of Python 3. Here's what the distros currently have:

 - Debian stable, 3.7
 - Ubuntu Xenial, 3.5
 - Ubuntu Bionic, 3.6
 - RHEL 8, 3.6???
 - SLES 15, I could not find out by googling

Xenial is _probably_ old enough that we don't have to keep supporting it. 3.6 seems to be widely available, but is that so. Are there platforms where we'd need to support 3.5?

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by mensinda** [comment]
Bionic (18.04) does have python 3.6, so we don't need to remove it, or am I missing something?

https://packages.ubuntu.com/search?keywords=python3&searchon=names&suite=bionic&section=all

**Comment by jpakkane** [comment]
That was unintentional. Fixed.

**Comment by mensinda** [comment]
Is keeping Ubuntu 16.04 around intentional?

**Comment by ignatenkobrain** [comment]
CentOS has 3.6, so fine fro RHEL/Fedora POV.

+1

**Comment by nirbheek** [comment]
I would like to add a warning for people who are using Python 3.5 for one release before we do this. If for no other reason than to give people a heads-up.

**Comment by xclaesse** [comment]
+1 for having a warning cycle.

**Comment by jpakkane** [comment]
This goes in immediately after 0.56.0 is done.

**Comment by jpakkane** [comment]
Apparently Azure conf also needs updating:

```
Meson works correctly only with python 3.6+.
You have python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)].
Please update your environment
```

**Review by scivision — APPROVED** [review]
I think this is a good deprecation cycle / approach

**Comment by alanc** [comment]
Shouldn't [docs/markdown/Getting-meson.md](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Getting-meson.md) also be updated to list 3.6 instead of 3.5??

**Comment by jpakkane** [comment]
It should. #8155.

**Pull request merged**
