### PR TITLE
Fix excluding sources for static lib in both_libraries()

### PR DESCRIPTION
**Pull request by xclaesse**
When using both_libraries(), or library() with default_library=both, we remove all sources from args and kwargs when building the static library, and replace them by the objects from the shared library. But sources could also come from any InternalDependency, in which case we currently build them twice (not efficient) and link both objects into the static library (probably harmless?). It also means that when we needlessly build those source for the static library, it miss order dependency on generated headers that we removed from args/kwargs, which can cause build errors in the case the source from static lib is compiled before the header in shared lib gets generated.

This happened in GLib:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2917.

Fix that by letting StaticLibrary class process all args/kwargs and remove sources afterward, when they all have been extracted.

### CODE REVIEW

**Comment by dcbaker** [comment]
This completely drops the workaround for the cases where we can’t reuse the object files

**Comment by xclaesse** [comment]
> This completely drops the workaround for the cases where we can’t reuse the object files

I don't think so, in that case it does not remove sources from static_lib.

**Comment by xclaesse** [comment]
CI failure is interesting, I'm impressed we have a test for that: With both_libraries(), link_with to an uninstalled static library is converted by the static library by adding to self.objects, but the shared lib does not do that. So when we do `static_lib.objects = [shared_lib.extract_all_objects()]` we lose some objets that we actually need.

@dcbaker unrelated, but while digging this, I think we lose sources passed as `declare_dependency(sources: structured_sources())`. BuildTarget.process_sourcelist() ignore them and it could be called from BuildTarget.add_deps().

**Comment by xclaesse** [comment]
Hmm, LGTM does not like my trick, it's true that it is generally bad to call overridden method from init, but in this case it's safe. Changed to use a class attribute instead of overriding process_sourcelist() method.

**Comment by xclaesse** [comment]
This is ready for review.

**Comment by nirbheek** [comment]
This seems too dangerous to backport directly to a stable release, IMO. I think it should go into the master branch and get some testing before we can backport it.

**Comment by xclaesse** [comment]
@nirbheek I agree, maybe backport in future 0.63.4 after it has been released and tested a bit in 0.64.0.

In all cases, review would be welcome to merge in master first.

**Comment by xclaesse** [comment]
@nirbheek @eli-schwartz can I get a review please, seems it completely breaks static link of glib 2.74.

**Comment by xclaesse** [comment]
Kind reminder for a review please :pray: GLib 2.74 is currently broken when building with default_library=both: https://github.com/mesonbuild/meson/issues/10907.

**Comment by xclaesse** [comment]
ping?

**Pull request merged**
