### PR TITLE
Added .so to list possible darwin dynamic library suffixes

### PR DESCRIPTION
**Pull request by gsobala**
Occasionally darwin libraries can be .so rather than .dylib e.g. tensorflow_cc.so

### CODE REVIEW

**Comment by nirbheek** [comment]
For purposes of documenting in the commit, could you find out why exactly Tensorflow uses `.so` for the library?

**Comment by gsobala** [comment]
tensorflow_cc is a c++ API for Tensorflow (https://github.com/FloopCZ/tensorflow_cc) which was primarily written for Linux but is also compilable on Darwin. Possibly through laziness, possibly just to have consistent filenames, the developers did not opt to change the suffix from the Linux default when this is compiled on Darwin. 

The reason why I feel this PR is valid is that the Darwin linker is perfectly capable of detecting a library with a suffix of `.so` e.g. if `-ltensorflow_cc` is used and if it lies in a normal library dir. However it does not, hence a directory needs to be passed to find_library() and hence the need for find_library() to match by filename.

**Comment by nirbheek** [comment]
Sounds good. Please update the commit message and the tests. The CI failure is relevant.

**Comment by gsobala** [comment]
I confess I do not know how to write a test for this as it is entirely macos dependent. Given that it is only a very small code change, is a test necessary?

**Comment by nirbheek** [comment]
We already have a test for this, which is run on all platforms and mocks all platforms to figure out if the library naming is as expected. This test needs to be updated. See the CI failure.

**Pull request merged**
