### PR TITLE
Meson recognize .C files as C sources while it is C++ Option 2

### PR DESCRIPTION
**Pull request by jeandet**
This PR adds .C as C++ extension and makes Meson case sensitive for
file extension detection only for C and C++ compilers.

See PR #3409 
@textshell if you have comments, you are welcome :)

### CODE REVIEW

**Comment by nirbheek** [comment]
Closing due to inactivity, let's discuss this in an issue and commit to whether we want to do it at all, before we discuss how to implement it.

**Comment by Volker-Weissmann** [comment]
@nirbheek @jpakkane Is there anything wrong with this PR except for the lack of test cases? If not, I'm going to add these, if yes, can you provide an example where this PR creates problems?

**Comment by jpakkane** [comment]
There are projects that use .C as an extension for plain C. I wish I was kidding but I'm not. There's no way to make this work for everybody and then you end up with the case that compilers start fighting over which one should do the compilation. FWICT the recommenden best practices of C++ nowadays is to not use `.C` as a file extension.

**Comment by Volker-Weissmann** [comment]
First of all, I would mention the following important fact in case you don't already know that.
If you have a *.C file that contains valid C that is not also valid C++, you cannot translate it using gcc or clang, because gcc and clang will compile a *.C file using its C++ compiler. Not even --std=c90 can change that.
With the way meson currently works this might lead to strange bugs, because meson thinks the file is c, but compiles it using a c++ compiler.
It is probably best if meson errors out if meson has a .C file, that should be c-compiled, but the compiler found is gcc or clang.

I don't know which projects use *.C for plain C, but they are not using gcc or clang.

I only see this solution:
Let the user write one of these:
```
files('file.C', language : 'c')
files('file.C', language : 'cpp')
```
Note that I'm not suggesting that you should be able to write
```
files('file.arbitraryExtension', language : 'arbitraryLanguage')
```
Such a feature would be impossible, because e.g. gcc will refuse to compile for example `file.txt` or `file.abcd`.
'.C', 'c' and '.C', 'cpp' are the only two extension-language combinations that need to be accepted.
The devs can then bitchfight about whether  `files('file.C'` should default to `files('file.C', language : 'c')` or `files('file.C', language : 'cpp')`, I don't care. 

We could then change `can_compile` to something like this
```python
def can_compile(self, src: 'mesonlib.FileOrString') -> bool:
	if isinstance(src, mesonlib.File):
+               if src.language_kwarg is not None:
+                   assert(src.fname.endswith('.C'))
+                   assert(src.language_kwarg in ['c', 'cpp'])
+                   return self.language == src.language_kwarg
		src = src.fname
	suffix = os.path.splitext(src)[1].lower()
	return bool(suffix) and suffix[1:] in self.can_compile_suffixes
```


> FWICT the recommended best practices of C++ nowadays is to not use .C as a file extension.

Can you give me a source for that? Not that I would disagree, but I could use a nice link from an authority as an argument if I try to convince idiots to following best practices.

We could print a warning to the user if he uses *.C files

If physicists would follow recommended best practices when writing C++, my life would be a lot easier...

**Pull request closed without merging**
