### PR TITLE
Skip gnome tests if gir is missing

### PR DESCRIPTION
**Pull request by NickeZ**
I seem to have all libs except gobject-introspection on my newly installed ubuntu.

### CODE REVIEW

**Comment by jpakkane** [comment]
In general we don't want to skip framework tests on Linux because it is too easy to accidentally lose the dependencies on CI images which means that they won't be tested any more.

**Comment by NickeZ** [comment]
Then i suggest that we provide a list of packages needed to develop on meson. Given the strong "no dependencies" opinion here I'm surprised that you need to install more than a compiler to run the tests.

**Comment by NickeZ** [comment]
Another option I thought of is to skip everything that is "exotic" and explicitly state that they are installed with flags/flag. That way we can ensure that we build everything on CI and catch invalid changes to the docker images. I'm thinking something like `--have-all`, `--have-boost`, `--have-gnome`, `--have-cross-arm`, and so on, as arguments to `run_tests.py`.

Anyway I think the code snippet below is "hazardous". I would prefer if we only could skip tests from the test framework and not from the project that is being built.

```
if not glib.found()
  error('MESON_SKIP_TEST glib not found.')
endif
```

**Comment by nirbheek** [comment]
One solution would be to add a new way for tests to error out `error('MESON_SKIP_DEP ....')` which would be an error when running under CI and just skip the test otherwise.

**Pull request closed without merging**
