### PR TITLE
D: Add conditional debug compilation flags

### LINKED ISSUE #4034: No support for conditional debug compilation in D
Similar to D's [version identifiers](http://mesonbuild.com/D.html#compiling-different-versions), D also supports conditional compilation with debug flags, with various levels of 'debugness' and debug identifiers. For example with DMD compiler, debug builds should always have the `-debug` flag (not to be confused with `-g`) passed on compilers, which compiles the code inside `debug { }` blocks. The level of 'debugness' can be defined with `-debug=3`, where all the debug levels from 1 to 3 are compiled, and on top of that, extra debug identifiers can also passed with `-debug=DebugFeature`, which similarly compiles the code inside `debug (DebugFeature) { }` block, just like with version identifiers.

I can start working on this after the D fixes for Windows are merged in, if nobody has any objections against it.

### PR DESCRIPTION
**Pull request by GoaLitiuM**
Fixes #4034.

### CODE REVIEW

**Comment by jpakkane** [comment]
Would it make more sense to have a language-level option for this debug level so you can set it once and have the value in every target?

**Comment by GoaLitiuM** [comment]
I'm not sure about that. For `-debug(=1)` it might make sense, but it might be desirable to have different levels of debugging enabled in different parts of the project or in dependencies. This is the D equivalent of C's `#ifdef DEBUG` and `#ifdef DEBUG && DEBUG_FEATURE`.

**Comment by jpakkane** [comment]
We have a bunch of other options that depend on the build type but they are reset to the original values when changing build types with `meson configure`. This one does not, its value persists over build type changes. On the other hand it also behaves differently because you can put extra stuff in it and you would expect those to persist over built type changes.

How do people use these settings when building D with other build systems? Do they default to all debug off and only add 1 when explicitly added? Do they have 1 enabled always? Do they do roughly what this does, that is, have it enabled for debug builds and off for everything else?

**Comment by jpakkane** [comment]
I guess the real question here is whether there is a need to change the debug level of all targets in a project at once or do people just add debug levels to a single target temporarily. If the former then we should have a top level option for that, if the latter then we could do something like this:

 - if a target has specified debug options, use those (and only those)
 - if there are no debug options, use `1` if building `debug` and nothing otherwise

**Comment by GoaLitiuM** [comment]
I don't see how those two options are mutually exclusive assuming the target level options were to override the top level identifiers. If so, we should start with what we know for sure is needed: pass `-debug=1` to compilers by default for debug builds (like in dub project), and provide the tools to override it with target level options when needed.

**Comment by GoaLitiuM** [comment]
I dropped the language-level options, keeping the build target changes and `-debug=1` for debug builds intact.

**Comment by jpakkane** [comment]
Let's do this then. If and when usage in the real world provides new needs and/or features please open new MRs.

Until the next major release is out, we can change this is backwards-incompatible ways. After that we should avoid that as much as possible. Thus if any problems pop up, please file MRs as soon as possible.

**Pull request merged**
