### PR TITLE
Preliminary support for object library

### PR DESCRIPTION
**Pull request by 0x1997**
See #621. There are no tests and only the ninja backend is supported.

### CODE REVIEW

**Comment by nirbheek** [comment]
Is this only for the use-case in #621? If so, wouldn't it be more useful to add support for `-Wl,--whole-archive` when linking to arbitrary static libraries? We discussed (https://github.com/mesonbuild/meson/issues/484#issuecomment-203849249) how this sort of thing is very useful in creating "fat shared libraries" that simply bundle all the dependencies inside them. Even MSVC supports this under [`/WHOLEARCHIVE`](https://msdn.microsoft.com/en-us/library/mt732963.aspx)

`ObjectLibrary` only works as a built target inside a single project, but `--whole-archive` support would allow this to be used with both internal dependencies and arbitrary external dependencies. I was thinking that something like this would work well:

```
some_lib = shared_library(...)
other_lib = static_library(...)
library(..., link_with : some_lib, link_whole : other_lib)
```

```
other_dep1 = declare_dependency(..., link_with : ...) # Internal static library dependency
other_dep2 = dependency('gstreamer-1.0', static_libs=True) # External static library dependency
library(..., dependencies : some_dep, dependencies_whole : [other_dep1, other_dep2])
```

This requires support for defining external dependencies that only use static-libs, but that can be done in another PR. I think it makes sense to start by adding support only for internal dependencies at first.

**Comment by 0x1997** [comment]
@nirbheek Well, the point of object library is that the unnecessary generation of the static library can be avoided. And static libraries don't need `-fPIC` and are generally not compiled with it, so `-Wl,--whole-archive` is not an option anyway.

**Comment by nirbheek** [comment]
Generating a static library is not an expensive process unless your archive is a gigabyte in size.

libtool defaults to building static libraries with `-fPIC` and you don't need that on Windows at all. Almost all static libraries that ship on your system are built with `-fPIC`. In the same bug that I linked to, I also proposed that we should also always build static libraries with `-fPIC` since the performance difference is completely negligible on processors these days.

**Comment by jpakkane** [comment]
Meson already has the facilities to do this. You can use the objects from a target directly in another target by doing something along the lines of this:

    executable('foo', 'foo.c', built_lib.extract_all_objects(), ..)

Granted we could perhaps make this easier but preferably not with an object library type.

>  Even MSVC supports this under /WHOLEARCHIVE

Unfortunately only starting with VS 2015.

> Generating a static library is not an expensive process unless your archive is a gigabyte in size.

Which means you really want to use the lib, otherwise your linker command line explodes in size.

> performance difference is completely negligible on processors these days.

This is not actually true. I did some simple measurements which showed a 1% improvement (using only one lib). In supercomputer/datacenter scale this is huge. According to Alexandrescu if he could improve Facebook's [some computation, don't remember which], simply the savings in electricity would pay his salary for on the order of tens of years.

**Comment by nirbheek** [comment]
> > performance difference is completely negligible on processors these days.

> This is not actually true. I did some simple measurements which showed a 1% improvement (using only one lib). In supercomputer/datacenter scale this is huge. According to Alexandrescu if he could improve Facebook's [some computation, don't remember which], simply the savings in electricity would pay his salary for on the order of tens of years.

I was thinking that for workloads where a 1% improvement makes such a big difference, we could add a keyword argument to `static_library` called `pic` which defaults to `True` but can be set to `False` if you know you won't be using the objects in a shared library. But I really think it makes sense to default to `pic` for static libraries + mentioning all this in the documentation.

**Comment by jpakkane** [comment]
There does not seem to be uptake for this feature at the moment so closing.

**Comment by obilaniu** [comment]
@jpakkane There are other usecases that can benefit from individualized compile flags. For instance, most files shouldn't be compiled with `-ffast-math`, but optimized routines isolated to separate file can benefit greatly. Creating a shared lib for them, linking it, then using `.extract_all_objects()` and relinking them with the rest of the functions they naturally belong with seems pointless and wrong.

Perhaps the compiler I-C-E's or miscompiles code with a certain optimization, and it would be desirable to disable it. Or perhaps you're using `-Werror` and strict compile flags, but are willing to make an exception for a specific file which was coded a long time ago, has stood the test of time but gives a warning that you have checked can be ignored safely.

> Granted we could perhaps make this easier but preferably not with an object library type.

The current way to do this with dummy shared or static libraries and `.extract_all_objects()` works but is inelegant and pollutes the filesystem with libraries that should not actually "exist". It also forces users to give pairwise non-conflicting filesystem names to every such collection of object files.

I propose that the functions `static_library()` and `shared_library()` be kept (to communicate the intent of the compilation, e.g. PIC or no PIC), but if those functions are given no library name or an empty name `""`, then they act as anonymous bundles of object files that are not linked into a library, but can be used as inputs to other `static_library()`, `shared_library()` and `executable()`'s.

This is a feature I would use, and I feel is missing. Otherwise, Meson is an excellent build system. Great work Jussi!

**Comment by nirbheek** [comment]
The way this is usually done is with a static library that you just link in everywhere else. Why would that not work in your case?

**Comment by obilaniu** [comment]
@nirbheek I don't think that is how it's commonly done; Certainly none of Make, CMake or Qbs proceed that way for flag customizations to individual files.

What they do is that they divorce the concept of compiling a set of object files from the linking of those object files. Meson maries them, leading to the unnecessary linking and creation on the filesystem of named libraries and archives.

Having nameless `static_library/shared_library/executable` entities represent non-terminal object-file selection stages of linking would elegantly solve this problem, and would not exclude your way of proceeding.

Moreover the concept is applicable to shared libraries too. Specifically, I wish to apply the custom warning and optimization flags to specific sources that will become part of a shared library, and thus I do want `-fPIC`, but I _don't_ want to create a shared library out of that object file subset, nor do I wish to be bothered to give it a filesystem name (e.g. `libdummy.so`), since I will be discarding it anyways, extracting any or all object files I want from that subset and linking them myself into the real shared libraries.

**Comment by obilaniu** [comment]
Here is ([anonymous-libs.txt](https://github.com/mesonbuild/meson/files/514632/anonymous-libs.txt)) an extremely basic patch permitting what I had in mind for the Ninja backend. It allows for empty-named "anonymous" libraries and allows one to either `.extract_all_objects()` or to `link_with` it. The collection of object files they represent is not linked.

E.g. something similar to

```python
# Top-level project statement
project('name', 'c', 'cpp')

# Sources
optimizedSrcs = files('kernels.c')
regularSrcs   = files('main.c')

# Dependencies
cc   = meson.get_compiler('c')
m    = cc.find_library('m', required: true)
deps = [m]

# Compile the optimized kernels with special flags. Use anonymous library.
optLib = shared_library('', optimizedSrcs, c_args: ['-ffast-math', '-fomit-frame-pointer'])

# Compile and link the rest as normal.
exe = executable('exe', regularSrcs, link_with: [optLib], dependencies: deps)
```

But for my lack of familiarity with Meson's internals and other languages and backends, I'd be willing to help program a more complete patch that would:
- Check that only _compilation_-related flags, not _link_-related flags, are allowed for anonymous libraries.
- Propagate dependencies from anonymous libraries to the named libraries that use them.
- Add testcases.

I encountered one potential problem (which I resolved with a nasty hack in `backend/backends.py` in the patch above), namely that the linker is selected by looking at source files, and if a library is constituted only of object files from elsewhere then Meson errors out with `Unreachable code` because it fails to pick a compiler with which to perform the link.

**Comment by jpakkane** [comment]
The only change needed to make this work with current code is this:

    optlib = static_library('fmathfiles', <other args>)

That seems like an awful lot of work just to avoid writing one library file name. Libraries by default are not installed so the only downside is the few kilobytes of extra disk space used to store the files, which is completely irrelevant.

> Specifically, I wish to apply the custom warning and optimization flags to specific sources that will become part of a shared library, and thus I do want -fPIC, but I don't want to create a shared library out of that object file subset

This will work once the currently pending fpic MR lands.

> It also forces users to give pairwise non-conflicting filesystem names to every such collection of object files.

This is not the case, object files are stored in the private directory of each target and Meson does all the necessary gymnastics to make filenames not clash. If there is a clash, file a bug and we'll fix it.

**Comment by obilaniu** [comment]
> This will work once the currently pending fpic MR lands.

Great! I'll await it with anticipation.

> This is not the case, object files are stored in the private directory of each target and Meson does all the necessary gymnastics to make filenames not clash. If there is a clash, file a bug and we'll fix it.

If I create two dummy static libraries

```python
objSubset1 = static_library('noname', srcSubset1)
objSubset2 = static_library('noname', srcSubset2)
```
, I get `Tried to create target "noname", but a target of that name already exists.` So I do have to give nonconflicting names to each subset of object files I pick.

> the only downside is the few kilobytes of extra disk space used to store the files, which is completely irrelevant.

There's not just a space saving but also a time saving in not linking things that won't be used, which helps Meson's claim at the speed crown. Although, granted, most libraries are not that big, some are impressively large due to C++ templating, and/or slow linkers due to bad `__attribute__ ((visibility ("hidden")))` hygiene (or equivalent).

**Comment by jpakkane** [comment]
> So I do have to give nonconflicting names to each subset of object files I pick.

This is true, but on the other hand giving each a proper name makes them self-documenting. This also gives each one a private dir to store the object files in, otherwise they would need to be dumped in some global dir which has its own problems (like having two different object targets which both have a file `foobar.c` which would then possibly conflict).

> a time saving in not linking things that won't be used

Static linking is roughly the same as tarring (without compression). It does not really do anything much, time is spent only when the `.a` file is linked to the final target. One also assumes that in the common case almost all files are in the main target and only one or possibly a few are in the special library, so it should be quite small.

**Pull request closed without merging**
