### PR TITLE
run_target: Add env kwarg

### PR DESCRIPTION
**Pull request by xclaesse**
Re-implement it in backend using the same code path as for
custom_target(). This for example handle setting PATH on Windows when
command is an executable.

### CODE REVIEW

**Comment by jpakkane** [comment]
According to Git bisect, this change broke the cross file test: https://github.com/mesonbuild/meson/pull/8313/checks?check_run_id=1849734517

**Comment by jpakkane** [comment]
Specifically, the code no longer checks that the exe wrapper is valid when it encounters a run target (and presumably a custom target).

**Comment by xclaesse** [comment]
@jpakkane Sorry, I don't understand how this has not been catched by the CI before merging. Made a fix there: https://github.com/mesonbuild/meson/pull/8314

**Comment by tristan957** [comment]
@xclaesse thanks for your work on this issue. I am excited to use it :).

**Pull request merged**
