### PR TITLE
interpreter: Fix holder_map not being updated when subproject fails

### PR DESCRIPTION
**Pull request by xclaesse**
Fixes: #9038

### CODE REVIEW

**Comment by xclaesse** [comment]
CC @mensinda

**Comment by mensinda** [comment]
Good catch! I guess you could also remove [these lines](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter/interpreter.py#L860-L861) with your fix then, or am I missing something.

Thanks for fixing this.

**Comment by xclaesse** [comment]
> I guess you could also remove [these lines](https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter/interpreter.py#L860-L861) with your fix

Indeed, done now.

**Review by mensinda — APPROVED** [review]
LGTM, assuming the CI is "green".

**Comment by xclaesse** [comment]
@mensinda While at it, I noticed the summary suffers the same issue. Added a commit for that.

**Review by mensinda — APPROVED** [review]

**Comment by jpakkane** [comment]
This had to be reverted from master to bring CI to green. Please reopen.

**Comment by xclaesse** [comment]
Ok, sorry for the trouble, I opened a new PR to bring that back, and see if that can pass CI. https://github.com/mesonbuild/meson/pull/9123.

**Pull request merged**
