### PR TITLE
Enable colors with Clang

### PR DESCRIPTION
**Pull request by rzlourenco**
This PR enables colors when compiling with Clang. The earliest reference I found to the flag's existence was on the [Clang 3.3 User's Manual](http://releases.llvm.org/3.3/tools/clang/docs/UsersManual.html#formatting-of-diagnostics), but to be honest I didn't took too hard. It seems that the "auto" option is no option at all.

### CODE REVIEW

**Comment by nirbheek** [comment]
It was also in [at least 3.1](http://releases.llvm.org/3.1/tools/clang/docs/UsersManual.html#opt_fcolor_diagnostics), which was released 5 years ago in 2012. I can't find any user manuals older than that.

I think it's ok to enable it unconditionally tbh. Unlike GCC, no one is using older Clang versions.

**Comment by rzlourenco** [comment]
Oh, thanks. I've updated my pull request. Should I update it to enable coloring unconditionally? My opinion is that since we have a choice for the other compilers, we should have the choice for Clang too, though my original motivation was just having color.

**Comment by jpakkane** [comment]
Since this is a common option, they should have the same options in all compilers if possible. If, for some reason, you mix Gcc and Clang (or any other compiler) the code might ask for value `auto` from the Clang compiler (because the option values come from Gcc). Please add an `auto` option and make it do the same as `always`.

**Comment by nirbheek** [comment]
By unconditionally I meant don't bother with a version check.

**Comment by rzlourenco** [comment]
Done and done!

**Comment by jpakkane** [comment]
Please add yourself at the end of `authors.txt` and we'll get this merged. Thanks.

**Pull request merged**
