### PR TITLE
azure: Fix vs2015

### PR DESCRIPTION
**Pull request by mensinda**

### CODE REVIEW

**Comment by mensinda** [comment]
Now seeing that vs2015 (or rather choco) seems to work again (for some reason), I am not sure if this PR is still required. However, it does remove Chocolatey out of the equation, which is one less potential point of failure.

See [this log](https://dev.azure.com/jussi0947/jussi/_build/results?buildId=4624) for the choco error.

**Comment by scivision** [comment]
I've had to reset the vs2015 runs numerous times in the past few weeks on different PRs for exactly that Choco failure.

 Is it worth jumping ahead to https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe ?

**Comment by jpakkane** [comment]
LGTM.

**Comment by mensinda** [comment]
My hope in choosing 3.7.5 instead of 3.8.0 was that a higher patch version number should correlate to fewer bugs 😄. Also, 3.7.5 should be good for a couple of years, since we are now only considering upgrading to 3.6 anyway.

Now I am curious, how did you manage to reset the Azure runs? I am only able to do this with travis.

**Comment by scivision** [comment]
No problem, vs2015 has been problematic enough over time, so choosing a more mature Python 3.7.5 is fine. The GitHub Actions are generally set to the latest Python release, so within a few days of a new release e.g. Python 3.8.1 the Actions will be on that. No need to torture vs2015 more.

---

to reset only the failed Azure Pipeline(s), don't click on the generic `mesonbuild.meson` job from this GitHub PR "conversation" page, but rather click on "Details" on any one of the specific failed Pipelines on this "conversation" page. Then, in the upper right hand of that page, there is a dropdown menu button with non-default option saying something like "rerun failed checks". The default of the dropdown is something like "rerun all" so it's not obvious.

**Comment by mensinda** [comment]
@scivision Thanks. I was always looking for a way to do this on https://dev.azure.com itself.

**Comment by scivision** [comment]
Yes it seems strange that that option is not an azure itself. Thankfully Travis has that option built in

**Pull request merged**
