### PR TITLE
Revert "Merge pull request #1145 from AlexandreFoley/wrap-fix"

### PR DESCRIPTION
**Pull request by jpakkane**
This reverts commit 541dd92ef7a10b0f657f3c8532ffb71a8d921f54, reversing
changes made to 155617e539a9aeccda6bd186398123b9d5521ed4.

### CODE REVIEW

**Comment by AlexandreFoley** [comment]
>That change breaks my workflow where I am developing in gst-build rebuilding when necessary pretty badly as each time I build it will try to pull and checkout from the infos in the .wrap files.
>
>Also in gst-build we have a special update target that pull --rebase (making sure autoStash is on so we avoid issue when the user is working on a repo).
>
>I am not sure what would be the best way to do it in meson upstream but this does not work for us.
>
>Also if a subproject repo is being worked on, I get the following backtrace:
>
>error: Your local changes to the following files would be overwritten by checkout:
	gst/gst_private.h
	gst/gstbin.c
	gst/gstelement.c
	gst/gstinfo.c
	gst/gstobject.c
Please commit your changes or stash them before you switch branches.
Aborting
error: Your local changes to the following files would be overwritten by checkout:
	gst/gst_private.h
	gst/gstbin.c
	gst/gstelement.c
	gst/gstinfo.c
	gst/gstobject.c
Please commit your changes or stash them before you switch branches.
Aborting
Traceback (most recent call last):
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonmain.py", line 286, in run
    app.generate()
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonmain.py", line 174, in generate
    intr.run()
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 2207, in run
    super().run()
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 124, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 180, in evaluate_statement
    return self.evaluate_foreach(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 328, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 150, in evaluate_statement
    return self.function_call(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 371, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1379, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1389, in do_subproject
    resolved = r.resolve(dirname)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/wrap/wrap.py", line 126, in resolve
    self.get_git(p)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/wrap/wrap.py", line 155, in get_git
    cwd=checkoutdir)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', 'master']' returned non-zero exit status 1
FAILED: build.ninja 


This is the problem encountered by thiblahute. I think it might be better to have it here too.

**Comment by AlexandreFoley** [comment]
An obvious solution would be to add an on or off switch that prevent pulling from the remote repo.
Another would be to try to detect presence of uncommited changes in the repo and not pull and update in such a case. (I am uncertain if it would actually solve tiblahute's problems with this change)

Adding an on or off switch seems safer to me, but we'd need to choose what the default position should be. I'd obviously advocate for pull and update upon reconfiguration to be on by default.

**Comment by thiblahute** [comment]
I think we should have a switch but it should probably be settable in the project itself, and we could add an `update` target automatically if it is set off?

**Comment by AlexandreFoley** [comment]
>I think we should have a switch but it should probably be settable in the project itself

 You mean in the meson.build file of the main project? I don't think details of how wrap works and what it can do should leak into the build description. As far as the project meson.build file is concerned, I think it should remain a subproject no different then if it was just placed there by the user.

I have modified the implementation for auto updating so that old behavior is preserved by default.

The way i did this is that i added a new keyword to the wrap files for git and mercurial. This new keyword is "branch" and replace the keyword "revision" if you choose to use it. When this new keyword is used meson will attempt update on reconfiguration but not if there are uncommitted changes in the repo.

the modifications are here:
https://github.com/AlexandreFoley/meson/tree/059563e97de60faf9f948fd41127fb5134f3033e

Can you try it out and tell me if there are still any incompatibility with your workflow?

On another subject entirely. Thiblahute, you're the author of the push-url feature of wrap. Are you aware that this function can only be triggered right after cloning a repository? (or is it? I guess i could be wrong) Is this the intended behavior? I am somewhat puzzled by the usefulness of pushing one single time after cloning the repo, and i have to question whether it belong in what is intended as a distribution tool.

**Comment by AlexandreFoley** [comment]
Also, i moved the updating feature in separate functions. I think it paves the way to realizing your suggestion of creating a target to update subproject (That's a pretty neat idea).
On the flip side, i don't know how to proceed to create a new target and I don't really have time to find out at the moment.

**Comment by thiblahute** [comment]
> You mean in the meson.build file of the main project? I don't think details of how wrap works and what it can do should leak into the build description. As far as the project meson.build file is concerned, I think it should remain a subproject no different then if it was just placed there by the user.

Yeah, that is what I meant but I guess you are right, it does not belong there.

> The way i did this is that i added a new keyword to the wrap files for git and mercurial. This new keyword is "branch" and replace the keyword "revision" if you choose to use it. When this new keyword is used meson will attempt update on reconfiguration but not if there are uncommitted changes in the repo.

To be able to rebase even if there are changes we use `rebase.autoStash` in our [update target](https://cgit.freedesktop.org/gstreamer/gst-build/tree/git-update#n45) it is quite useful fmpov but maybe to agressive if the update has been automatically triggered and not explicitely asked by the user.

> the modifications are here:
> https://github.com/AlexandreFoley/meson/tree/059563e97de60faf9f948fd41127fb5134f3033e

> Can you try it out and tell me if there are still any incompatibility with your workflow?

Will do tomorow.

> On another subject entirely. Thiblahute, you're the author of the push-url feature of wrap. Are you aware that this function can only be triggered right after cloning a repository? (or is it? I guess i could be wrong) Is this the intended behavior? I am somewhat puzzled by the usefulness of pushing one single time after cloning the repo, and i have to question whether it belong in what is intended as a distribution tool.


Setting the `push` URL of a repo last for the whole lifetime of the repo, basically when we clone a new repo where `push-url` has been set, the clone repo will have 2 urls:

```
 INSERT  gst-master  thiblahute  ⓔ  env  ⋯  gstreamer  gst-build  gstreamer  1  git remote -v                                                                                1  ⌆ 15   help_pipeline 
origin	git://anongit.freedesktop.org/gstreamer/gstreamer (fetch)
origin	ssh://git.freedesktop.org/git/gstreamer/gstreamer (push)
```

this means that if the user as write access in that repo, he will be able to push the changes he made, this is just for convenience and it avoid GStreamer developers (with write access) to have to set the git repo URL to each and every GStreamer module present in our `gst-build` 'aggregator' module.

> Also, i moved the updating feature in separate functions. I think it paves the way to realizing your suggestion of creating a target to update subprojects (That's a pretty neat idea).
> On the flip side, i don't know how to proceed to create a new target and I don't really have time to find out at the moment.

Yeah, that would be nice, though we should make sure we have feature parity with our current update target in `gst-build` :) (and yes I should probably have developed that upstream instead of in `gst-build` :/)

**Comment by thiblahute** [comment]
I am getting the following tracback with your branch:

```
Traceback (most recent call last):
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/meson.py", line
17, in <module>
    from mesonbuild import mlog, mesonmain
  File
"/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonmain.py",
line 18, in <module>
    from . import environment, interpreter, mesonlib
  File
"/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py",
line 23, in <module>
    from .wrap import wrap
  File
"/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/wrap/wrap.py",
line 209
    revision = p.values.get('revision')
```

**Comment by AlexandreFoley** [comment]
Aw crap. 
The bad indentation is fixed now.

P.S. Thank you for the explanation of the push-url keyword. I had completly misunderstood what it does.

**Comment by thiblahute** [comment]
That branch works for me.

**Comment by jpakkane** [comment]
If that branch works for all cases, please file a MR and we'll merge that instead of this.

**Pull request merged**
