### PR TITLE
Add global_source/build_root()

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by emersion** [comment]
LGTM!

**Comment by eli-schwartz** [comment]
Should the FeatureDeprecated for `meson.source_root()` etc. be updated to also mention this in an either/or?

**Review by eli-schwartz — APPROVED** [review]

**Comment by xclaesse** [comment]
> Should the FeatureDeprecated for `meson.source_root()` etc. be updated to also mention this in an either/or?

Good point, I updated to `use meson.project_source_root() or meson.global_source_root() instead.`.

**Review by dcbaker — APPROVED** [review]
LGTM, thanks for doing this

**Pull request merged**
