### PR TITLE
Document dependency(method:) values

### PR DESCRIPTION
**Pull request by jon-turney**
Make a start at document the values for dependency(method:)

### CODE REVIEW

**Comment by jon-turney** [comment]
Notes:

method: doesn't do anything in the default (non-custom) dependency detector.

There are `system` and `sysconfig` values for method:.  There's only one use of the latter, and it's unclear to me what the difference in meaning is supposed to be.

**Comment by nirbheek** [comment]
This is great documentation! Do you also think we should mention the version(s) that added these methods?

**Comment by nirbheek** [comment]
> There are system and sysconfig values for method:. There's only one use of the latter, and it's unclear to me what the difference in meaning is supposed to be.

`sysconfig` refers to the python module that contains information about the system and the python installation.

`system` for GL dependency means manual searching on the system for the GL dependency, but this is quite broken: see https://github.com/mesonbuild/meson/issues/3679

**Comment by jon-turney** [comment]
> Do you also think we should mention the version(s) that added these methods?

I did some archeology, but didn't immediately find any methods being added to a detector.

I've added some documentation of the version that various detectors appeared in.

N.B. libwmf was added in 0.44.0, but isn't the release note for that, and so it currently missing an appropriate FeatureNew annotation.

**Pull request merged**
