### PR TITLE
Force cross -- includes #5785 

### PR DESCRIPTION
**Pull request by Ericson2314**
This rather obscure functionality is nevertheless useful for certain
automations. See docs for details.

Includes #5785 to avoid conflict. Hopefully that other one is so trivial it will be merged shortly.

### CODE REVIEW

**Comment by nirbheek** [comment]
I'm wondering why we need this, why aren't we setting `is_cross` to `true` when a cross file is specified? IIRC we used to not do that earlier because people were using `--cross-file` as a hack for native compilation because we didn't have `--native-file`, but that's fixed now.

**Comment by jpakkane** [comment]
I agree, having one and only one way of setting something is always preferable.

**Comment by Ericson2314** [comment]
No it doesn't do that any more. Effectively, `--cross-file` is the "host file", not the "cross file". `matches_build_machine` checks whether the host platform is different than the build platform, which it isn't if the cross file and native file are different.

This is good for distros and other stuff which could always pass both files. `--force-cross` is also be good for that, but represents and additional stringent step which isn't suitable for native-only packages. I want my distro's packages to opt-out of `--force-cross`, but never need to opt out of the cross file being specified.

**Comment by Ericson2314** [comment]
CC @TheQwertiest

**Comment by jpakkane** [comment]
> This is good for distros and other stuff which could always pass both files.

Why? I can't think of a reason for this. What values would those have? 99% of all distro package building is native compilation. If they wanted to always pass both they would have to go out of their way to create a "cross" file that is the same as a native file.

**Comment by Ericson2314** [comment]
@jpakkane On NixOS we always specific the build and host machine separately, and native is simply when they are different. (Exherbo also works this way fwiw) The easiest thing to do is just always turn both our machine representations into both of meson's files.

**Comment by bonzini** [comment]
Not needed anymore, since now the presence of a cross file is what defines a build being "cross"

**Pull request closed without merging**
