### PR TITLE
Qt5 Module: Fix handling of File objects for qresources.

### PR DESCRIPTION
**Pull request by leiflm**
This adds support for File objects handling to the `qresources`.
It is particularly useful when using subprojects to provide
resource files.

### CODE REVIEW

**Comment by leiflm** [comment]
I'm not entirely sure about this. Why would the input (`rcc_files`) be a `String` instead of a `File` array in the first place?! 🤔 

If that's intended: Maybe extend `mesonlib.File` to implement `os.PathLike` instead of this approach?

**Comment by QuLogic** [comment]
I don't think this is right; why add an extra loop with conversions? IMO, `parse_qrc` should be updated to understand `File` objects instead.

**Comment by leiflm** [comment]
Problem is that `rcc_files` is used repeatedly. My prior version patched just `parse_qrc`, but that is insufficient.

**Comment by QuLogic** [comment]
Yes, to find a basename; that should also be edited to work with `File`. The other case is a custom target, which already understands `File`.

**Comment by leiflm** [comment]
Yeah. I had that covered too. But then I thought why make two handling exceptions (for now) instead of a single point of input data homogenisation?
And, as I said, if File supported `os.PathLike` neither would be necessary.

**Comment by leiflm** [comment]
this seems to be a duplicate of #2315. Which way do the devs want to pursuit?

**Comment by jpakkane** [comment]
Having both strings and Files in this array is a leftover from the old times when we did that. All functions that take actual file arguments should convert them to File objects immediately with `source_strings_to_files`. Though maybe no module has yet used it so it's not properly exposed there ...

**Comment by leiflm** [comment]
is it correct, that the `File` class does not provide any means to access just the `fname` (i.e. basename)?

**Comment by jeandet** [comment]
If #2573 is merged, the problem is solved.

**Comment by leiflm** [comment]
@jeandet
> If #2573 is merged, the problem is solved.

well it breaks paths if files are located in a Subprojects.

The root path is then the parenting project :-/

**Comment by leiflm** [comment]
For some reason [state.subdir](https://github.com/mesonbuild/meson/blob/cde0f4fca18b15a86218911d8519e1d334a27c7f/mesonbuild/modules/qt.py#L82) is always empty :-/

**Comment by tracernz** [comment]
@leiflm If you've got time to work on this please do. Closed my PR as I haven't managed to get back to it for a long time.

**Comment by leiflm** [comment]
@jeandet stil broken with subprojects providing `File`s:
```
Traceback (most recent call last):
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/mesonmain.py", line 353, in run
    app.generate()
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/mesonmain.py", line 152, in generate
    self._generate(env)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/mesonmain.py", line 200, in _generate
    intr.run()
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreter.py", line 2839, in run
    super().run()
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 202, in evaluate_statement
    return self.assignment(cur)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 610, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 204, in evaluate_statement
    return self.method_call(cur)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 440, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreter.py", line 1129, in method_call
    value = fn(state, args, kwargs)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 80, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/interpreterbase.py", line 102, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/modules/qt.py", line 110, in preprocess
    qrc_deps += self.parse_qrc(state, i)
  File "/home/foo/py3/lib/python3.6/site-packages/meson-0.44.0.dev1-py3.6.egg/mesonbuild/modules/qt.py", line 71, in parse_qrc
    abspath = os.path.join(state.environment.source_dir, fname)
  File "/home/foo/py3/lib64/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/foo/py3/lib64/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'File'
```

**Comment by jeandet** [comment]
@leiflm this has been fixed in #3326

**Pull request closed without merging**
