### PR TITLE
Raise an exception if we cannot detect the MSVC compiler target architecture

### PR DESCRIPTION
**Pull request by lb90**
Discussed in #6128

### CODE REVIEW

**Comment by jpakkane** [comment]
Could the error message give some hints as to why this has happened or how the issue might be fixed?

**Comment by lb90** [comment]
I have changed the commit to add some contextual information. Now the output looks like this:

```
D:\>python meson\meson.py glib glib_aaa --backend=vs2019 --buildtype=debug
The Meson build system
Version: 0.52.999
Source dir: D:\glib
Build dir: D:\glib_aaa
Build type: native build
Project name: glib
Project version: 2.63.1

meson.build:1:0: ERROR: Failed to detect MSVC compiler target architecture: 'cl /?' output is
Microsoft (R) C/C++ Optimizing Compiler versione 19.23.28106.4 per x64

A full log can be found at D:\glib_aaa\meson-logs\meson-log.txt

D:\>
```

**Comment by jpakkane** [comment]
Is that an actual error message? Why does it not detect x64? It is written quite plainly in the output.

**Comment by scivision** [comment]
It's the non-English language `per x64`
The discussion in the associated issues thought either

* not qualifying on the English `for x64`
* switching the codepage

could work. Additionally, this PR is to avoid a nowadays confusing default of x86 when Meson doesn't detect the version due to the associated Github issues.

**Comment by scivision** [comment]
I think it was this line that was changed in 0.52.0, adding `for` that causes the issue.
https://github.com/mesonbuild/meson/pull/6153/files#diff-638d32e2abc720f45ee2279d5befe1e5R994

* could we assume non-Latin character locales will still say x64
* will right to left languages (e.g. Arabic) cause an issue with using a regex that looks for x64 to the "right" of other characters without using `for`?

**Comment by lb90** [comment]
Hi @scivision!

1. Yes
2. Much probably RTL / LTR are just done at the presentation level when displaying, i.e. the strings that cl outputs are always the same (so not reversed), but the Command Prompt displays them reversed.

@jpakkane I can still change the error message in another PR. Should it be something like:

`Failed to detect MSVC compiler target architecture. Could not match regular expression ' for .*(x86|x64|ARM|ARM64)$' in 'Microsoft (R) C/C++ Optimizing Compiler versione 19.23.28106.4 per x64'`

It would be great if we could land a workaround for the regex mismatch for the 0.52.1 release

**Pull request merged**
