### PR TITLE
linkers: Fix AppleDynamicLinker not returning any RPATHs to remove

### PR DESCRIPTION
**Pull request by pbrzez**
Fixes another regression from https://github.com/mesonbuild/meson/pull/13012 - before it, all RPATHs were removed on install, now none of them were :)

That PR relied on rpath_dirs_to_remove being present and correctly filled, which was never the case for the AppleDynamicLinker. The result was that all the build-dir-only RPATHs were being carried over to the installed files. For example, in a local GStreamer build, I was seeing paths like `@loader_path/../../../gstreamer/gst` present after installation, which were only valid in the builddir and should've been removed.

I implemented returning the list of RPATHs to remove in AppleDynamicLinker, doing pretty much the same thing as what's in the GnuLikeDynamicLinkerMixin. Thanks to that, depfixer now correctly removes build-time Meson-created RPATHs, as it used to before 1.4.1.

I also added a unit test trying to prevent a similar scenario (on macOS only) in the future.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Thank you, I'm rather disappointed that that PR apparently never got tested by the people who had macOS hardware...

**Comment by eli-schwartz** [comment]
I reflowed the commit message a bit for better readability in git log:

`git range-diff origin/master 745d42825 4b0d4e548`
```
1:  745d42825 ! 1:  4b0d4e548 linkers: Fix AppleDynamicLinker not returning any rpaths to remove
    @@ Metadata
      ## Commit message ##
         linkers: Fix AppleDynamicLinker not returning any rpaths to remove
     
    -    Fixes regression from commit 78e9009.
    +    Fixes regression from commit 78e9009ff9d36925e04f329f9082841002ddd848.
     
    -    The above commit relied on rpath_dirs_to_remove being present and correctly filled, which was never the case for the
    -    AppleDynamicLinker. The result was that all the build-dir-only RPATHs were being carried over to the installed files.
    +    The above commit relied on rpath_dirs_to_remove being present and
    +    correctly filled, which was never the case for the AppleDynamicLinker.
    +    The result was that all the build-dir-only RPATHs were being carried
    +    over to the installed files.
     
    -    This commit implements returning the list of RPATHs to remove in AppleDynamicLinker, doing pretty much the same thing
    -    as what's in the GnuLikeDynamicLinkerMixin. Thanks to that, depfixer now correctly removes build-time Meson-created
    -    RPATHs, as it used to before 1.4.1.
    +    This commit implements returning the list of RPATHs to remove in
    +    AppleDynamicLinker, doing pretty much the same thing as what's in the
    +    GnuLikeDynamicLinkerMixin. Thanks to that, depfixer now correctly
    +    removes build-time Meson-created RPATHs, as it used to before 1.4.1.
     
      ## mesonbuild/linkers/linkers.py ##
     @@ mesonbuild/linkers/linkers.py: class AppleDynamicLinker(PosixDynamicLinkerMixin, DynamicLinker):
```

**Comment by eli-schwartz** [comment]
@grobian

**Comment by grobian** [comment]
> Thank you, I'm rather disappointed that that PR apparently never got tested by the person who had macOS hardware and developed the code and was in a position to test it...

I'm sorry if I caused this.  To the best of my knowledge and testing the patch worked.

**Pull request merged**
