### PR TITLE
Fix creation of objects with duplicate names

### PR DESCRIPTION
**Pull request by QuLogic**
I ran into this myself with something, so this fixes up some issues when source files use the same filename in different directories. This would normally cause a clash of object names with a cryptic message (cf #1494), but there's no reason meson can't produce unique names as in here.

Also, use `object_filename_from_source` to generate the object name, which should make it consistent with the name expected when object files are extracted since it's used there as well.

### CODE REVIEW

**Comment by jpakkane** [comment]
Failures are relevant. The unity one is especially important.

**Comment by QuLogic** [comment]
I thought the `sources_conflicts` dictionary in the `Vs2010Backend` would handle these duplicate names, but it appears not to be the case?

**Comment by QuLogic** [comment]
> cl : Command line error D8036: '/Foa.out@exe\file.obj' not allowed with multiple source files [C:\projects\meson\b j2yrrkxx\a.out@exe.vcxproj]

Has the VS backend's duplicate source name handling always been broken?

**Comment by nirbheek** [comment]
> Has the VS backend's duplicate source name handling always been broken?

What do you mean? Isn't this the same problem as the ninja backend, that the output object is being created from the basename instead of the relative path?

**Comment by QuLogic** [comment]
Then what's the point of the `sources_conflicts` dictionary?

**Comment by nirbheek** [comment]
Oh, I missed that from your previous comment. Yes, looks like that broke at some point, should've had a test for it. ;)

I think that whole `self.resolve_source_conflicts()` function seems weird. That functionality should be replaced with `self.object_filename_from_source()` so we have consistency between backends.

**Comment by QuLogic** [comment]
Well, let's see what happens when we replace that with the new version.

**Comment by QuLogic** [comment]
Success!

**Comment by nirbheek** [comment]
Let's try to get this in soon so we can see what the fallout is

**Pull request merged**
