### PR TITLE
Qt5-Module: add `name` option to rcc

### PR DESCRIPTION
**Pull request by thillux**
This patch sets the --name option for files processed with
rcc. It generates an additional initialization function,
which can be used with static linking.

Signed-off-by: Markus Theil <markus.theil@tu-ilmenau.de>

### CODE REVIEW

**Comment by thillux** [comment]
This commit should fix #2297.

**Comment by jpakkane** [comment]
This does not work when there is more than one input file:

    Meson encountered an error:
    Command cannot have '@BASENAME@' when there is more than one input file

This is understandable, since `@BASENAME@` comes from the input file name and if there are more than one, it is ambiguous what that should be.

If you only need a unique string, then probably you could do something like:

    'command': [self.rcc, '-name', name,  '-o', '@OUTPUT@', '@INPUT@']

Please also add a test for the issue this fixes so we won't regress this accidentally in the future. Thanks.

**Comment by thillux** [comment]
I modified the behavior of the rcc code to create one output file per qrc file if no common name is set. This is the mode I found in Qt5CoreMacros.cmake of cmake.

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
