### PR TITLE
WIP Add support to read environment variables

### LINKED ISSUE #9: Provide access to environment variables in build files
How would I include the value of an environment variable in either my meson.build or meson_options.txt files?  Is that even possible?

E.g.
option('someoption', type : 'string', value : ${SANDBOX})

### PR DESCRIPTION
**Pull request by snsmac**
Hello,

this code adds the function env_var to the build_machine object.
This method can be used to read an environment variable or check if it is set.

I did not write documentation or tests yet, because i would first like to know if this functionality is wanted and if the function names are ok.

This would fix #9

### CODE REVIEW

**Comment by jpakkane** [comment]
We have not had a function to read environment variables on purpose. They are hidden global variables, and their usage should be avoided whenever possible. Unless you have a very, very, very good use case for this that can not be done without envvars, this PR will be closed.

**Comment by snsmac** [comment]
I use it to write some values that the GitlabCI system sets into a config file. This helps me to find issues with the CI/Build system. But i can understand why this feature is problematic. Currently i use this workaround:
`pymodule = import('python3')
python3 = pymodule.find_python()
ci_pipeline = run_command(python3, '-c', 'import os; print(os.getenv("CI_PIPELINE_ID", ""))')`

**Comment by jpakkane** [comment]
A better solution would be to have a build option `ci_id` and then set your CI pipeline launcher command to be something like:

    meson -Dci_id=$CI_PIPELINE_ID <other options>

**Comment by Cwiiis** [comment]
I just ran into this on an Android project. It's convention for Android to have certain environment variables set, which you can then reference in include paths, linker flags, etc. The Android SDK/NDK, afaik, doesn't provide any binary for discovering these paths.

It seems pretty clunky to have to start specifying options to allow these paths to be specified when they're in the environment. I've gone with the Python work-around listed above for now, but is this something that's likely to ever be reconsidered? (or does anyone have any suggestions for this particular use-case?)

**Comment by nirbheek** [comment]
> I just ran into this on an Android project. It's convention for Android to have certain environment variables set, which you can then reference in include paths, linker flags, etc. The Android SDK/NDK, afaik, doesn't provide any binary for discovering these paths.

This case is actually exactly why we don't provide this feature. The correct way to make this work is to add an `android` module to Meson that handles all this so all code can use it, instead of people cargo-culting code across build files.

I would highly recommend that instead of doing that python workaround, you submit a module that does that instead.

**Pull request closed without merging**
