### PR TITLE
Fix broken env.append

### PR DESCRIPTION
**Pull request by nils-werner**
This PR fixes issue #12327 by 

 1. Creating a test-case that reproduces the issue (tested in isolation only, I did not run the entire test-suite).
 2.  Reverting commit 2cb7350d1679fb61826bf4aebfb0f75a9b9103e3 which introduced the issue.

Unfortunately I don't really understand what the original commit was doing, but this revert fixes the issue for me.

### CODE REVIEW

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
Thanks for the test case. I see why this happened.

Reverting the commit is definitely wrong. The issue is that environment settings for a target can either *set* or *append* an environment variable, and the `env` binary can be used to *set* a variable but not append. We should update the code instead to also check whether environment variables are being appended/prepended, before deciding it's safe to use the external env program.

**Comment by nils-werner** [comment]
> It was optimizing `env.set()` to not require running a complicated python program shipped with meson, if the external `env` program was available. That much worked fine -- but the implementor was unfamiliar with the practical use of append/prepend... ;)

Well, I understood the intention, but I didn't understand what it was doing to achieve its goal :-D

Is this enough to get you pointed in the right direction for a fix, or would you like me to investigate further and try to come up with a fix?

**Comment by nils-werner** [comment]
> Reverting the commit is definitely wrong.

Can't we just revert the commit (which, as I understand, was merely a performance-optimization) to fix the regression it caused, and then find another solution to implement this optimization?

**Comment by eli-schwartz** [comment]
Due to the holidays I probably won't have time to look at this until Thursday. Still, that is soon enough that we're highly unlikely to release a new version between now and then.

That being the case, I'm not convinced it's urgent to merge this now in order to be undone later.

**Comment by nils-werner** [comment]
Ah no sorry, I didn't mean to rush you!

I just thought it could be wise to fix the regression first, and get it covered by a test. And then, with the test in place, try doing the optimization again.

**Comment by nils-werner** [comment]
No worries, thanks for your hard work!

**Comment by jpakkane** [comment]
This MR was unfortunately faulty. It uses `bash`, which is prohibited. The project does not permit using _any_ unix tools. They are not available on pure Windows, which this merge now breaks. Unfortunately we don't have a CI setup that would be bashless Windows.

The "proper" way to do this is to write a Python script that does the thing that needs to happen and calling that instead.

**Pull request merged**
