### PR TITLE
Fix scanning of Fortran sources created during configuration

### PR DESCRIPTION
**Pull request by aradi**
Fixes issue #1348 for Fortran sources generated during configuration. Sources generated by ``generator()`` and ``custom_target()`` are still not scanned.

### CODE REVIEW

**Comment by aradi** [comment]
Of course, sorry for forgetting about the test! See last commit.

**Comment by jpakkane** [comment]
Please update the test so it creates an executable and runs it with `test()`. Currently this only tests that the code compiles but not what comes out. If there was a bug that, for example, drops all pregenerated sources to the floor rather than compiling we would not notice it. Make sure the main program is in a non-generated source so we test a mixture of gen and non-gen sources. Thanks.

**Comment by aradi** [comment]
With pleasure, see last commit. By the way, Fortran tests 5 and 6 do not have a ``test()`` statement either. Is that on purpose?

**Comment by jpakkane** [comment]
Probably just an oversight.

**Pull request merged**
