### PR TITLE
rpm macros: export *FLAGS

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by jpakkane** [comment]
Looking at this now, the simpler solution would be to remove the semicolons after the declarations (the set vars only live until a semicolon). So from this:

    CFLAGS="%{optflags}" ; \

to this

    CFLAGS="%{optflags}" \

**Comment by ignatenkobrain** [comment]
@jpakkane Then it will appear in log in oneline, which is not looks good when inspecting projects

**Comment by jpakkane** [comment]
In that case you can do the exports like this:

    export CFLAGS="%{optflags}"
    export CXXFLAGS=...

**Comment by ignatenkobrain** [comment]
@jpakkane done

**Pull request merged**
