### PR TITLE
mdist: use git archive with git repositories for correctness

### LINKED ISSUE #2287: ninja dist should respect gitattributes export-ignore
Quoting from the [manpage](https://manpages.debian.org/unstable/git-man/gitattributes.5.en.html#Creating_an_archive) for gitattribute

`Files and directories with the attribute `export-ignore` won’t be added to archive files.`

It would be great if `ninja dist` would respect that and not include files with that attribute in the tarball it generates.

### LINKED ISSUE #3081: Exclude files from ninja dist?
Looking into meson bu I could not find anything in the docs how to exclude files from ``ninja dist``. I don't want to have my transiflex or travis configuration files included in the tarball.

### LINKED ISSUE #8144: dist failure with relative submodule paths
**Describe the bug**

dist fails with git submodules using relative paths.

**To Reproduce**

The entire tree is at https://gitlab.freedesktop.org/xdg/shared-mime-info/-/tree/40db4c7adba8a5cc586e24f5b4b5aff0b2a81bcc, see .gitlab-ci.yml there for how it's built in CI. The xdgmime submodule is defined as `../xdgmime.git`

CI failure log is at https://gitlab.freedesktop.org/xdg/shared-mime-info/-/jobs/6403481 -- essentially it seems meson is trying to checkout the submodule from a directory relative to the main project working dir, whereas it should treat relative submodule path as relative to the superproject's default remote repo; https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-add-bltbranchgt-f--force--nameltnamegt--referenceltrepositorygt--depthltdepthgt--ltrepositorygtltpathgt

**Expected behavior**

Working submodule checkout during dist.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

### PR DESCRIPTION
**Pull request by eli-schwartz**
Fixes various inconsistencies:
- gitattributes is respected
  - export-subst
  - export-ignore
- submodules with relative paths are not checked out relative to the
  local clone (which does not work anyway)
- no need to manually remove gitfiles with inaccurate heuristics

Fixes #2287
Fixes #3081
Fixes #8144

### CODE REVIEW

**Comment by xclaesse** [comment]
I've always wondered why we were not doing that and have been assuming @jpakkane had a reason.

**Comment by eli-schwartz** [comment]
The lint_mypy failure is not actually my fault. @mensinda is there some way to automatically tell that open() doesn't take an encoding parameter because it's from the tarfile module, not the built-in function or io.open?

**Comment by eli-schwartz** [comment]
@xclaesse the reason is "because submodules looked hard". :)

**Comment by mensinda** [comment]
Yes, there is. You can turn it of with a comment. We already use tarfile somewhere and it should be there on the same line.

Can't be more specific because I can't look it up right now.

On 2 September 2021 14:12:06 CEST, Eli Schwartz ***@***.***> wrote:
>The lint_mypy failure is not actually my fault. @mensinda is there some way to automatically tell that open() doesn't take an encoding parameter because it's from the tarfile module, not the built-in function or io.open?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mesonbuild/meson/pull/9210#issuecomment-911604924
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eli-schwartz** [comment]
I was hoping for something slightly more "automatic", but I guess the manually manual way works too...

**Comment by xclaesse** [comment]
@eli-schwartz fair enough. Note that we now also support dist for a subproject that is in the same git repo of its parent project. We're going to use that feature for GStreamer. IIRC I made a unit test for that, so CI should tell if that still works.

**Comment by eli-schwartz** [comment]
Maybe that's the reason why CI fails in the "samerepo" setup...

**Comment by xclaesse** [comment]
> The lint_mypy failure is not actually my fault. @mensinda is there some way to automatically tell that open() doesn't take an encoding parameter because it's from the tarfile module, not the built-in function or io.open?

Probably that syntax: `tar = tarfile.open(xz_distfile, "r:xz")  # [ignore encoding]`

**Comment by xclaesse** [comment]
> Maybe that's the reason why CI fails in the "samerepo" setup...

It's failing for the `--include-subprojects` test case, that's another pitfall that I forgot.

**Comment by xclaesse** [comment]
subprojects could themself have submodule... recursively... not sure that case ever worked tbh.

**Comment by eli-schwartz** [comment]
- free function rename now that it doesn't actually clone anything
- the case of project root not being repo root, is now corrected to actually pass in the temporary distdir for copying (oops) and pass the subdir as `subdir=` instead of `revision=` (also oops)

And with that, `./run_unittests.py test_dist_git` as flagged by the CI as a relevant test to verify this PR... now passes locally.

**Comment by eli-schwartz** [comment]
(I lied, I have local gitconfig which borks things up. Might as well add the changes I needed here too.)

**Comment by xclaesse** [comment]
LGTM, seems to be a safer way indeed.

**Pull request merged**
