### PR TITLE
dub: enhance dependency handling

### LINKED ISSUE #3568: Meson doesn't handle 'link_args' correctly for non-gnu D compilers
Sample config
```
project('test-project', 'd')

libabc_dep = dependency('libabc')

test_exe = executable('test', 'app.d',
                        #d_args: ['-I/usr/include', '-L/usr/lib'],
                        dependencies: libabc_dep
)
```
When compiling the `test_exe` target, the compiler fails to add the arguments specified in the pkgconfig (usually, `-I/usr/include` and `-L/usr/lib`). If I add the right arguments to `d_args`, as shown in the commented code, it works.

I have only tried to link dependencies provided by pkgconfig. I also tried compiling with both LDC and DMD, same result.

### LINKED ISSUE #4032: Dub method for dependencies
The dependency search for Dub method dependencies always seems to find that the library was built with dmd even when it was built with ldc2.
```
Found DUB: /usr/bin/dub (DUB version 1.10.0, built on Jul  3 2018)
ERROR: Dependency unit-threaded found but it was compiled with dmd and we are using ldc
Dependency unit-threaded found: NO 

meson.build:38:0: ERROR:  Dependency "unit-threaded" not found, tried 
```

Update: building everything with dmd does work, building with ldc2 always fails.

### PR DESCRIPTION
**Pull request by FFY00**
fixes #4032: meson now checks properly for the compiler used to compile dub dependencies

fixes #3568: applied the following patch https://paste.debian.net/1039317/

meson now adds flags for native dependencies required by dub modules

meson now checks for the D version implemented by the compiler used to build dub dependencies (execpt gdc which doesn't support this)

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Flake8 detected 12 issues on 43d4e36bd308adf5124008911c75d2f33611b666
Visit https://sider.review/gh/19784232/pull_requests/4084 to review the issues.

**Comment by textshell** [comment]
I think patch https://paste.debian.net/1039317/ is superceeded by https://github.com/mesonbuild/meson/pull/4080

So that should likely be handled by that PR.

**Comment by ignatenkobrain** [comment]
Flake8 detected 11 issues on a44820c07bc923aa80e0e7e77320a0807d05fd00
Visit https://sider.review/gh/19784232/pull_requests/4084 to review the issues.

**Comment by ximion** [comment]
@FFY00 I am not sure how quickly I can get into writing an unittest for that, so if you want to, you could write the test and take over the PR (otherwise I'll likely get back to this some point next week).

**Comment by FFY00** [comment]
For that, we would need other D compiler in the docker image. @jpakkane can you do that? Also, how do deal with a unnittest that is expected to fail?

**Comment by jpakkane** [comment]
> For that we would need other D compiler in the docker image.

What packages do you need to get added?

Also Add them to `ciimage/Dockerfile` but only after the fact (the CI image is not automatically regenerated for pull requests because it would take too long).

**Comment by FFY00** [comment]
Yes, we could install `dmd`.

**Comment by ximion** [comment]
@jpakkane @FFY00 Adding LDC is probably easiest, because that is properly packaged in both Ubuntu and Debian (as well as Fedora & Co.).

**Comment by FFY00** [comment]
`ldc` it is. We don't actually need to call it so it shouldn't matter that much. We need the binary present in the system so that meson detects it.
How do we implement the unnittest? The test should only pass if meson is able to detect the compiler mismatch. This would give a fail error, but catching a fail error is not enough, we need to catch a specific error.

**Comment by GoaLitiuM** [comment]
The commit message refers to DMD while it's actually installing LDC instead. There is also this handy install script to install DMD and other compilers and tools too: https://dlang.org/install.html

**Comment by FFY00** [comment]
Oh, sorry. Forgot to change the commit message when I edited it. Regarding the script, I think installing from the repos is way better.

**Comment by jpakkane** [comment]
Interestingly ldc should already be in the CI image, because we install `dub` and that depends on `default-d-compiler` which depends on `ldc`. At least when I manually go in the container, running `ldc2` works.

**Comment by ximion** [comment]
@jpakkane Indeed! An explicit dependency makes sense though, in case we ever change the default DC on amd64...

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by jpakkane** [comment]
Don't do merges but instead keep the branch up to date by rebasing.

**Comment by FFY00** [comment]
Great, github is not detecting my changes. What should I do? Open other PR?

Check the commit hashes in the PR and in my fork https://github.com/FFY00/meson/commits/pr-fix-dub-dependencies.

**Comment by ljmf00** [comment]
just tried now with `gtk-d` and can't get the dependency:
```
ERROR: gtk-d found but it wasn't compiled with ldc
Dependency gtk-d found: NO
```
I'm using `meson==0.48.0.dev1` 2635546f53c68d035fe0074836ec0732df920a99

**Comment by FFY00** [comment]
Should be fixed now. Added check to assert that `targetType` is `library` and fixed how subpackages are handled.

**Comment by FFY00** [comment]
The problem here was raise because `gtk-d` doesn't have a configuration in the main packages, only in the subpackages. You still can't do `dependency('gtk-d', method: 'dub')`, obviously, but `dependency('gtk-d:gtkd', method: 'dub')` should be working fine. `DubDependency` was previously failing to resolve subpackges when the main package didn't have a default configuration.

**Comment by jpakkane** [comment]
It would be great to have a test for this. Is there some other way of achieving that than installing gtkd in the CI image?

**Comment by FFY00** [comment]
We can publish a dub package for this effect. Also, how do I deal with tests that are meant to fail (ex. if it's the wrong target type or wrong compiler)?

**Comment by jpakkane** [comment]
Put in in the `unit tests/failing` (or one of the other ones depending on when it needs to fail) directory.

**Comment by jpakkane** [comment]
It seems the MR still does not have the tests. It also :crossed_swords: conflicts in the Dockerfile...

**Comment by jpakkane** [comment]
We have a policy that all code being used in tests must be in repos that we control (for obvious reasons). If you give me the code with instructions, I'll get it set up.

**Comment by FFY00** [comment]
Just create an empty repo and I'll submit a PR. Could be something like `meson-dub-dummy`. After the code gets merged you just need to go to https://code.dlang.org and register the package.

**Comment by jpakkane** [comment]
https://github.com/mesonbuild/dubtestproject

**Comment by jpakkane** [comment]
Dub requires at least one tag on the repo. What should I add?

**Comment by FFY00** [comment]
`v1.0.0`?

**Comment by jpakkane** [comment]
Done: https://code.dlang.org/packages/dubtestproject

**Comment by FFY00** [comment]
Is anything else needed?

**Comment by FFY00** [comment]
Is anything else needed?

**Comment by FFY00** [comment]
Just a quick update. The version mismatch protection now works on Arch Linux's gdc as I passed the D version through `--with-pkgversion` ([here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/gdc#n104)) so it would be avaliable via `gdc --version`. I suggest that other distributions do the same if they're not already.

**Comment by jpakkane** [comment]
Trying to build the CI image fails with an error message saying that it cannot determine the ldc compiler because of `/bin/sh: 1: ldc: not found`. Given that there is no executable in Ubuntu with the name `ldc`, only `ldc2` this seems like a correct error message. Dunno why that is though.

**Comment by jpakkane** [comment]
Now it says "Main package must have a binary target type, not none. Cannot build".

**Comment by FFY00** [comment]
Oh, sorry forgot about that haha.

**Comment by jpakkane** [comment]
The image has finally been updated. I retriggered Travis, let's see what happens.

**Comment by FFY00** [comment]
All the CI tests passed. Is this ready now?

**Comment by jpakkane** [comment]
I tried to run this test manually inside the container the build fails for the wrong reason. It fails due to a version number check being wrong (which is a bug in Meson, there is already a PR).

If you fix that then the build actually passes which is incorrect because it is in the `failing` subdir meaning it should fail the configure step.

When using GDC it reports that the dependency is built with the wrong compiler but does not error out (because `required` is `false`).

When using LDC it finds `test2` but not `test1`. In either case it passes without error.

This is the problem with failing tests. You have to be very careful that they fail for the right reasons _and_ that they keep on failing in the future for the same reason.

It would be better if the test were to use the dependency to build something and thus would only pass if the build succeeds.

**Comment by FFY00** [comment]
Should be working now. Please retry :grin:.

**Pull request merged**
