### PR TITLE
small fixes for haiku

### PR DESCRIPTION
**Pull request by dcbaker**
This is a few small fixup for the haiku os that I created while working on building mesa. most of these changes are pretty minor, except for the fact that haiku does not have (and does not accept) -pthreads either to the compiler or the linker.

### CODE REVIEW

**Comment by dcbaker** [comment]
I haven't tried to cross compile for haiku. I konw that the test suite fails a lot of tests natively becuase hakiu doesn't have a `/usr/`, and thus no `/usr/bin/env` (they have `/bin/env` instead).

**Comment by nirbheek** [comment]
When using `find_program()` on such scripts, we should do the same thing as Windows where we ignore `/usr/bin/env` completely and use whatever is after that as the actual interpreter.

**Comment by nirbheek** [comment]
I just added a commit that does that for Haiku, does that improve things?

**Comment by dcbaker** [comment]
That seems like it should, I'll try running them later and see how things
look.

I'm on mobile, please excuse autocorrect fail.

**Pull request merged**
