### PR TITLE
cmake: Various fixes

### PR DESCRIPTION
**Pull request by xclaesse**
I tried to build AOM (https://aomedia.googlesource.com/aom/) as a Meson subproject, and I'm hitting many issues. Here is a patchset of various fixes needed. There are still other issues, notably lack of support for objects library.

### CODE REVIEW

**Comment by xclaesse** [comment]
@mensinda This is a subset of https://github.com/mesonbuild/meson/pull/5961 excluding big changes.

**Comment by mensinda** [comment]
What is the problem wit declaring a dependency for header only libraries?

If I see this correctly, this would break the following code for header only libraries:
```meson
cm = import('cmake')
sub = cm.subproject('headerOnly')

executable('exe', ['main.cpp'], dependencies: [sub.depenency('foo')])
```

But, besides that, overall good changes.

**Comment by mensinda** [comment]
Also, object libraries should alrady be supported. I will try looking into AOM.

**Comment by xclaesse** [comment]
> What is the problem wit declaring a dependency for header only libraries?

Hm, headers is a good point, you're right. But it does it for executables too, I've seen that in AOM generated meson.build:
```meson
lossless_encoder = executable(...)
lossless_encoder_dep = declare_dependency(..., link_with : lossless_encoder)
```

I'm surprised meson don't error out on such code.

**Comment by mensinda** [comment]
Yeah, this should not happen for executables. Good catch.

**Comment by xclaesse** [comment]
Actually, the commit message was misleading, it still generate declare_dependency() for `header_only`. It's only `shared_module` and `executable` that are not excluded now.

**Comment by xclaesse** [comment]
> Also, object libraries should alrady be supported. I will try looking into AOM.

Sorry, it was not about object libraries, but custom targets. This cmake snippet does not generate any `run_target()` in meson.
```
  add_custom_target(generate_exports
                    COMMAND ${CMAKE_COMMAND}
                            -DAOM_ROOT="${AOM_ROOT}"
                            -DAOM_CONFIG_DIR="${AOM_CONFIG_DIR}"
                            -DAOM_TARGET_SYSTEM=${AOM_TARGET_SYSTEM}
                            -DAOM_SYM_FILE="${aom_sym_file}"
                            -DAOM_MSVC=${MSVC}
                            -DAOM_XCODE=${XCODE}
                            -DCONFIG_NAME=$<CONFIG>
                            -DCONFIG_AV1_DECODER=${CONFIG_AV1_DECODER}
                            -DCONFIG_AV1_ENCODER=${CONFIG_AV1_ENCODER}
                            -DCONFIG_INSPECTION=${CONFIG_INSPECTION}
                            -DENABLE_TESTS=${ENABLE_TESTS}
                            -P
                            "${AOM_ROOT}/build/cmake/generate_exports.cmake"
                    SOURCES ${AOM_EXPORTS_SOURCES}
                    DEPENDS ${AOM_EXPORTS_SOURCES})
```

**Comment by xclaesse** [comment]
@mensinda Added one patch that I forgot to make the SOVERSION stuff work.

**Comment by xclaesse** [comment]
> > Also, object libraries should alrady be supported. I will try looking into AOM.
> 
> Sorry, it was not about object libraries, but custom targets.

Reported there to not forget: https://github.com/mesonbuild/meson/issues/5983

**Pull request merged**
