### PR TITLE
WIP: Add unit tests for sanitizer=address

### PR DESCRIPTION
**Pull request by NickeZ**
Also fixes a bug in `run_project_tests.py` regarding running tests that should fail at `ninja test`

### CODE REVIEW

**Comment by NickeZ** [comment]
My tests work:

* Succeeded test: test cases/common/187 sanitizer address
* Succeeded test: test cases/failing test/1 sanitizer address

Are tests flaky?

**Comment by NickeZ** [comment]
Failures seem to be other tests that also get `sanitize=address` because of my tests. Could that meant that there is some caching bug in the test framework?

```
Mesonlogs of failing tests
The Meson build system
Version: 0.46.0.dev1
Source dir: /root/test cases/d/2 static library
Build dir: /root/b 3da35d46ad
Build type: native build
Project name: D Static Library
Native D compiler: gdc (gcc 7.2.0-8ubuntu3 "gdc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
Found ninja-1.8.2.git at /root/tools/ninja
[0/1] /usr/bin/python3 /root/meson.py --internal regenerate '/root/test cases/d/2 static library' '/root/b 3da35d46ad' --backend ninja
The Meson build system
Version: 0.46.0.dev1
Source dir: /root/test cases/d/2 static library
Build dir: /root/b 3da35d46ad
Build type: native build
Project name: D Static Library
Native D compiler: gdc (gcc 7.2.0-8ubuntu3 "gdc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
Found ninja-1.8.2.git at /root/tools/ninja
[1/4] gdc  -Iapp_s@exe -I. '-I../test cases/d/2 static library' -fdiagnostics-color=always -fsanitize=address -fno-omit-frame-pointer -Wall -Wdeprecated -g -O0 -MD -MQ 'app_s@exe/app.d.o' -MF 'app_s@exe/app.d.o.deps' -o 'app_s@exe/app.d.o' -c '../test cases/d/2 static library/app.d'
[2/4] gdc  -Istuff@sta -I. '-I../test cases/d/2 static library' -fdiagnostics-color=always -fsanitize=address -fno-omit-frame-pointer -Wall -Wdeprecated -g -O0 -fPIC -MD -MQ 'stuff@sta/libstuff.d.o' -MF 'stuff@sta/libstuff.d.o.deps' -o 'stuff@sta/libstuff.d.o' -c '../test cases/d/2 static library/libstuff.d'
[3/4] rm -f libstuff.a && ar csrD libstuff.a 'stuff@sta/libstuff.d.o'
[4/4] gdc  -o app_s 'app_s@exe/app.d.o' -fsanitize=address libstuff.a  
1/1 linktest_static                         FAIL     0.10 s
```

**Comment by jpakkane** [comment]
I merged one change that might help with this. Please rebase to test.

**Comment by NickeZ** [comment]
Still leaking data between tests.

**Comment by NickeZ** [comment]
It still doesn't work

**Comment by nirbheek** [comment]
@jpakkane @NickeZ what's next?

**Comment by jpakkane** [comment]
Can you test changing `run_tests.py` function `run_configure` to always run the configure out-of-process? It would tell us if there is a lingering state problem or something else.

**Comment by nirbheek** [comment]
Maybe we should have a special mode in which we run *all* tests with `AddressSanitizer`? Then that can be a separate run in Travis that's executed on macOS and Linux.

**Comment by jpakkane** [comment]
Seems reasonable, it would catch things like the Gnome regression where asan always has to come first.

**Pull request closed without merging**
