### PR TITLE
Add options for standard parameter for nvc and nvc++

### LINKED ISSUE #13271: can't set the c++ standard correctly with newer versions of nvc++
**Describe the bug**
When you try to set cpp_std in the normal way meson errors out without event trying.
nvc++ claims that it supports the following strings `-std=c89|c90|c99|c11|c17|c18|gnu90|gnu89|gnu99|gnu11|gnu17|gnu18|c++98|c++03|c++11|c++14|c++17|c++20|c++23|gnu++98|gnu++03|gnu++11|gnu++14|gnu++17|gnu++20`

**To Reproduce**
meson.build `project('X', 'cpp', default_options: ['cpp_std=c++23'])`
run with `CXX=nvc++ meson setup build`
which outpts `meson.build:1:0: ERROR: None of values ['c++23'] are supported by the C++ compiler. Possible values are ['none']`

**Expected behavior**
everything should be build with `-std=c++23`

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) CentOS Linux 7
* what Python version are you using e.g. 3.8.0: Python 3.11.3
* what `meson --version` 1.4.1
* what `ninja --version` if it's a Ninja build. 1.11.1

### PR DESCRIPTION
**Pull request by kjmeagher**
fixes #13271

### CODE REVIEW

**Comment by kjmeagher** [comment]
I don't understand why the cygwin test is failing, any advice would be appreciated

**Comment by eli-schwartz** [comment]
Probably needs a release notes snippet, e.g. something like "nvc and nvc++ now support setting the std".

**Comment by kjmeagher** [comment]
@eli-schwartz is there somewhere I should add the release notes? there is currently no file for release notes for the next release?

**Comment by eli-schwartz** [comment]
The release notes management is described at https://mesonbuild.com/Contributing.html#documentation

**Pull request merged**
