### PR TITLE
Fix regular expression for MSVC target arch detection

### LINKED ISSUE #6128: Wrong cpu  detection for 'x86_64' windows
In ‘x64 Native Tools Command Prompt for VS 2017’, the cpu detected by meson  is 'x86' ？

``` shell
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```

```shell
D:\opt\glib-2.62.2\_build>meson .. --buildtype=release --prefix="D:\opt\glib\"
The Meson build system
Version: 0.52.0
Source dir: D:\opt\glib-2.62.2
Build dir: D:\opt\glib-2.62.2\_build
Build type: native build
Project name: glib
Project version: 2.62.2
C compiler for the host machine: cl (msvc 19.16.27034)
C linker for the host machine: link 19.16.27034
C++ compiler for the host machine: cl (msvc 19.16.27034)
C++ linker for the host machine: link 19.16.27034
Host machine cpu family: x86
Host machine cpu: x86
```

And I tried in vs2013 , 2015, got the same result.

### PR DESCRIPTION
**Pull request by lb90**
Make it work regardless of MSVC output language

Fixes #6128

### CODE REVIEW

**Comment by lb90** [comment]
This is a refinment of a107eab. With this the RE works in all languages and still correctly differentiates between ARM and ARM64 architectures.

**Comment by scivision** [comment]
Thanks I dropped the ball on making this improvement, which is consistent with the intention of that Git commit.

**Comment by scivision** [comment]
Ugh, and this fix missed the 0.52.1 release--regression was introduced in 0.52.0

@jpakkane does this merit a 0.52.1.1 or such because non-English MSVC users may be nailed by this introduced in 0.52.0.

**Comment by jpakkane** [comment]
We don't really do four level release numbers so it would be 0.52.2. I guess whether we do that or not depends on how much people are hitting this in the wild.

**Comment by scivision** [comment]
OK thanks

**Pull request merged**
