### PR TITLE
gnome: Handle internal dependencies to generate gir files 

### PR DESCRIPTION
**Pull request by thiblahute**

### CODE REVIEW

**Comment by jpakkane** [comment]
There really should be a test for this.

**Comment by jpakkane** [comment]
gnome.generate_gir(
      girsubproject,
      sources : libsources,
      dependencies : [gobj, meson_gir],
      link_with : girsubproject,

`girsubproject` should not need to be here twice.

`g_autoptr` does not work on MSVC and since our aim is to support that natively, our test cases should be compatible with it.

**Comment by thiblahute** [comment]
Thanks for the review, I removed usage of g_autoptr (also I am really not sure g-ir-scanner is able to build with msvc anyway) I removed spurious  `link_with` and the test should now be fixed.

**Comment by thiblahute** [comment]
Thanks :)

**Pull request merged**
