### PR TITLE
gnome: Allow list of directories for gtk-update-icon-cache

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
NACK. This violates the icon theme specification and I have never commonly seen it being done.

Furthermore it's not even hard to use a project-specific install script. The advantage of the module method is that:
- when invoked multiple times on the common system location, it avoids running gtk-update-icon-cache multiple times
- it automatically handles calculating the location

None of this is relevant to projects with their own YOLO custom locations. They can simply run `meson.add_install_script('gtk-update-icon-cache', '-q', '-t', '-f', customdir, skip_if_destdir: true)`. It's not hard, and we don't have to add a confusing API that isn't recommended and adds a lot of code soup.

**Comment by xclaesse** [comment]
> NACK. This violates the icon theme specification and I have never commonly seen it being done.

It is recommended by GNOME doc: https://developer.gnome.org/documentation/tutorials/themed-icons.html#extending-the-icon-theme. It is what most GNOME apps actually do, I have many of the core GNOME apps in `/usr/share/*/icons`.

> They can simply run `meson.add_install_script('gtk-update-icon-cache', '-q', '-t', '-f', customdir, skip_if_destdir: true)`.

With that argument we can delete the whole gnome module. It litterally just a pile of wrappers for commands you can run manually. The whole point is making it easier. In your example you forgot find_program(), I'm not sure that's going to work when gtk is a subproject for example.

**Comment by xclaesse** [comment]
On my Ubuntu system right now: eog, evince, evolution, gnome-builder, gitg, seahorse and yelp all does that.

**Comment by xclaesse** [comment]
OTOH, I concede that they don't seems to actually put a cache for their icons. Maybe distro patch it out?

**Comment by eli-schwartz** [comment]
> In your example you forgot find_program(), I'm not sure that's going to work when gtk is a subproject for example.

Weirdly, we run find_program_impl on a custom target's first string arg, but not an install script... Maybe that should be changed...

**Comment by xclaesse** [comment]
CC @ebassi who probably knows a lot more about GNOME than we do.

**Comment by ebassi** [comment]
The documentation page predates GResources; the recommended way to ship assets as named icons is to use GResource, these days. I'll update the GNOME devel docs.

Personally, I think it's enough for older apps not using GResource to call `gtk-update-icon-cache` manually.

**Comment by eli-schwartz** [comment]
> Maybe distro patch it out?

No, they just don't run that for packaging at all because... it's in a destdir! :)

And they only run their own post update hooks on the common directory. I suppose someone could add bug reports to 50 distros asking them to investigate their packages for gitg and a handful of other badly behaved applications, then add manual install scripts to update the icon theme.

They can't unconditionally run it in the packaging, nor can meson assume unconditionally running even with a destdir if the location is specified, because this is a hairy policy decision. Maybe they *should* be run during packaging in a destdir, because it won't be shared with other applications. On the other hand, maybe they should not be, because where on earth are you supposed to install themes? You can't do it to the system location, because these private icon sets don't have properly namespaced icon names. Or do they? Maybe? Maybe not? If they don't have namespaced names, then themes should be installed to the private location. If they do have namespaced names, you can install themes to the system location.

Maybe what this PR really needs is:
- to make it accept a dict of `{'path1': true, 'path2': false` so that skip_if_destdir can be fine tuned on each location
- also a module option, so distros can decide whether they care about packaging themes at all


Alternatively, fix the gnome docs to recommend using the system icon theme directory, and just rename the stupid icons to `${appname}-action.png` instead of colliding on `action.png` and hiding the collision in a per-application directory.

Hint: non-gnome applications do this correctly, they namespace their icons.

**Comment by eli-schwartz** [comment]
By the way, no, I'm not actually recommending to accept a dict as an API here. You'd need to in order to make the proposed feature work properly, but it's way too confusing, and simply leaving it to applications to do themselves is the correct approach.

This is why I disagree with:
> With that argument we can delete the whole gnome module. It litterally just a pile of wrappers for commands you can run manually.

My argument is in fact that it's ***simple*** to do manually, and the API to do it automatically is ***more complicated*** than doing it manually.

Wrappers are supposed to simplify things, not complexify them while promoting bad practices.

**Comment by xclaesse** [comment]
Thanks @ebassi for updating the doc, I think it makes sense indeed to include app specific icons as GResource. Apps that still ship icons as files in their own directory does not need to run gtk-update-icon-cache at all, distro packages are not going to do it anyway. For example that script from gnome-builder can just be deleted plain and simple, it does not even need to be replaced by manual rule: https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/build-aux/meson/post_install.py.

**Pull request closed without merging**
