### PR TITLE
Optimize CLikeCompiler._get_file_from_list()

### PR DESCRIPTION
**Pull request by bruchar1**
Simplify and optimize the function. When not on Mac OS, it was iterating two times the list when there were no files in it.

### CODE REVIEW

**Comment by bruchar1** [comment]
For the records: on my project, time spent into that function goes from 15s to 9s after the optimization, according to the profiler (for a 70s setup time).

**Comment by xclaesse** [comment]
Makes sense, Ci failure is unrelated: "WARNING: The common suite contains duplicate "262" tests: "262 generator chain", "262 required keyword in has functions"".

**Comment by eli-schwartz** [comment]
> Makes sense, Ci failure is unrelated: "WARNING: The common suite contains duplicate "262" tests: "262 generator chain", "262 required keyword in has functions"".

That's a warning, not an error. The error is that one of the actual test tests failed:
```
=================================== 264/3 ====================================
test:         MPI C
start time:   13:07:55
duration:     0.34s
result:       exit status 1
command:      MALLOC_PERTURB_=136 '/__w/meson/meson/b 06166aa0de/exec'
----------------------------------- stderr -----------------------------------
[ca7a21c3642c:100324] *** Process received signal ***
[ca7a21c3642c:100324] Signal: Segmentation fault (11)
[ca7a21c3642c:100324] Signal code:  (128)
[ca7a21c3642c:100324] Failing at address: (nil)
[ca7a21c3642c:100324] [ 0] /usr/lib/libc.so.6(+0x38f50)[0x7f860cf0bf50]
[ca7a21c3642c:100324] [ 1] /usr/lib/libc.so.6(+0x1632cd)[0x7f860d0362cd]
[ca7a21c3642c:100324] [ 2] /usr/lib/openmpi/mca_rml_oob.so(orte_rml_oob_send_buffer_nb+0x39f)[0x7f86084c705f]
[ca7a21c3642c:100324] [ 3] /usr/lib/libopen-rte.so.40(pmix_server_log_fn+0x33f)[0x7f860d10d26f]
[ca7a21c3642c:100324] [ 4] /usr/lib/openmpi/mca_pmix_ext3x.so(+0x139c5)[0x7f860a7879c5]
[ca7a21c3642c:100324] [ 5] /usr/lib/libpmix.so.2(+0x13eafd)[0x7f860a6b3afd]
[ca7a21c3642c:100324] [ 6] /usr/lib/libpmix.so.2(pmix_plog_base_log+0x7c2)[0x7f860a6b9862]
[ca7a21c3642c:100324] [ 7] /usr/lib/libpmix.so.2(pmix_server_log+0x6c3)[0x7f860a606c73]
[ca7a21c3642c:100324] [ 8] /usr/lib/libpmix.so.2(+0x82ff5)[0x7f860a5f7ff5]
[ca7a21c3642c:100324] [ 9] /usr/lib/libpmix.so.2(pmix_server_message_handler+0x63)[0x7f860a5fa8a3]
[ca7a21c3642c:100324] [10] /usr/lib/libpmix.so.2(pmix_ptl_base_process_msg+0x236)[0x7f860a6d5566]
[ca7a21c3642c:100324] [11] /usr/lib/libevent_core-2.1.so.7(+0x1eb32)[0x7f860cd9db32]
[ca7a21c3642c:100324] [12] /usr/lib/libevent_core-2.1.so.7(event_base_loop+0x4ff)[0x7f860cd9f39f]
[ca7a21c3642c:100324] [13] /usr/lib/libpmix.so.2(+0x9c5ea)[0x7f860a6115ea]
[ca7a21c3642c:100324] [14] /usr/lib/libc.so.6(+0x85bb5)[0x7f860cf58bb5]
[ca7a21c3642c:100324] [15] /usr/lib/libc.so.6(__clone+0x44)[0x7f860cfdacb4]
[ca7a21c3642c:100324] *** End of error message ***
==============================================================================
```

**Comment by xclaesse** [comment]
> That's a warning, not an error.

ah, oops, indeed. But MPI test randomly fail since forever, some day we should fix that...

**Pull request merged**
