### PR TITLE
Performance optimize the install part generation

### PR DESCRIPTION
**Pull request by marcelhollerbach**
This brings down the overall build time of EFL from 20 sec. down to 13.

### CODE REVIEW

**Comment by marcelhollerbach** [comment]
Sorry, ignore the last commit it will be dropped after i saw that the tests have passed :)

**Comment by jpakkane** [comment]
Master is fixed now. Since this :crossed_swords: conflicts, rebasing should make it work.

**Comment by marcelhollerbach** [comment]
@jpakkane is anything blocking this ?

**Comment by jpakkane** [comment]
I was just about to push the button. :stuck_out_tongue:

**Comment by marcelhollerbach** [comment]
thats what i call a good timing :)

**Pull request merged**
