### PR TITLE
Add a meson.bat launcher for Windows Pypi version of Meson

### PR DESCRIPTION
**Pull request by pal1000**
Need for this was flagged in #3217, #2203 and #1877.

### CODE REVIEW

**Comment by jpakkane** [comment]
Does this get autoinstalled somehow? Wouldn't you need to tell `setup.py` to install this or does it do that automatically?

**Comment by pal1000** [comment]
Thanks for the warning.  At least I learned how to check my contributions before sending a PR when it comes to anything Python related.

**Comment by pal1000** [comment]
@jpakkane, I addressed your concern and made some other improvements too. It should be in a far better state now after some rounds of stress testing with hazardous use cases.

**Comment by nirbheek** [comment]
Another thing is that with the default installation settings (including when installed via Visual Studio), python.exe is not in `PATH`, but `py` is. `py -3` will find the right python and run it.

The purpose of this is to allow people to have multiple python versions installed and to use them all interchangeably without having to twiddle `PATH`.

**Comment by pal1000** [comment]
@jpakkane I thought about this and this is how I think it should behave:
- first it needs to check if it's on windows, if not just continue with the rest;
- if it is on Windows mix some batch scripting, something like this

````
@SET ERRORLEVEL=0
@where /q meson.exe
@IF ERRORLEVEL 1 set pypimeson=1

````
And then meson.bat should only be installed if env['pypimeson']==1.

**Comment by pal1000** [comment]
@nirbheek, Py launcher doesn't natter much here because you can have multiple meson.bat copies, each for a Pypi installation for different versions of Python.  In addition to this,  py.exe shortcomings make it impractical to capture Python installations locations

For example this is what it takes to locate latest Python 3.x and run its Pypi based Meson installation using py.exe:

````
  @FOR /F "tokens=* USEBACKQ" %%a IN (`py -c "import sys; print(sys.executable)"`) DO @SET pythonloc=%%a
"%pythonloc%" "%pythonloc:python.exe=%Scripts\meson.py" %*

````

Using the absolute/or relative path to meson.bat may actually be easier.

**Comment by nirbheek** [comment]
Fair enough, I guess pip3 installs are the primary use-case here anyway. We can't really help people who want to run meson directly from git on Windows, they have to setup `PATH` or whatever themselves.

**Comment by ignatenkobrain** [comment]
Flake8 detected 9 issues on a31e767e47f42b3b9697ca8128d38a5e07def9a3
Visit https://sideci.com/gh/19784232/pull_requests/3343 to review the issues.

**Comment by pal1000** [comment]
@jpakkane, I restricted when the batch script is installed using this formula:
- check if it's on windows using `os.name == 'nt'`;
- check if `meson.exe` is in PATH and install only if it isn't.  I used `distutils.spawn..find_executable("meson.exe") is None` to perform this check.

**Comment by jpakkane** [comment]
This is even trickier than that:

 - the pypi packages are created on a Linux machine
 - `meson.exe` is _never_ available when `setup.py` is run, it is only created afterwards

Basically the environment in which the end result is used is completely different from the one the package is created in.

I can't think of a way to make this work automatically in all cases. Maybe we should make it install the bat file always and have a command line option for `setup.py` to not do that.

**Comment by nirbheek** [comment]
There is now a test for checking if Meson can be run in various ways: `run_meson_commands_test.py`. Could you please add this to that test so we have CI that will ensure that this doesn't break?

**Pull request closed without merging**
