### PR TITLE
cuda: enable C++20 for CUDA 12

### PR DESCRIPTION
**Pull request by SoapGentoo**
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compilers

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@obilaniu

**Comment by obilaniu** [comment]
@SoapGentoo Yes this looks good. Does Meson promise to cross-check the requested C++ standard against the compiler version?

**Comment by SoapGentoo** [comment]
I don't see any indication that Meson has a whitelist of versions <-> supported C++ standards...

**Comment by obilaniu** [comment]
@eli-schwartz I think this is fairly low-risk and would uunblock fuller CUDA 12 support.

**Comment by eli-schwartz** [comment]
TBH meson could and maybe should "verify" that -- by which I mean if we know what version of a compiler added support for a given `-std` flag, there's no reason we can't dynamically build the list of allowed values based on mesonlib.version_compare checks against self.version.

We actually do do that sometimes, just inconsistently. See e.g. `compilers.c.GnuCCompiler`

**Comment by SoapGentoo** [comment]
I agree that it should, but could would still merge this before doing that?

**Comment by eli-schwartz** [comment]
It seems like a pretty easy change, though. Shouldn't take long at all.

**Comment by SoapGentoo** [comment]
@eli-schwartz Implemented, I tested it with CUDA 11/12 and checking that C++20 disappears/appears with CUDA 11/12.

**Comment by eli-schwartz** [comment]
Nice!

I restarted the CI jobs because one failure is a flake, and the other 4 seem to have been critical existence failure for something deep inside homebrew which will hopefully go away.

**Comment by SoapGentoo** [comment]
@eli-schwartz would this have to much of a blast radius for 1.0.1?

**Comment by obilaniu** [comment]
I would argue that it isn't BW-compat breaking for the simple reason that if you *did* use `-Dcuda_std=c++20` when not supposed to, then the build will fail. With this PR in, it can be caught at the (earlier) configuration stage. Fail-fast.

**Pull request merged**
