### PR TITLE
Fix extract_all_objects for custom targets with VS backend

### LINKED ISSUE #8020: extract_all_objects() with custom target results in invalid paths for subproject with Visual Studio backend
**Describe the bug**

I have a build script where the input to one target is the output of `extract_all_objects()`, with some of the original object files being the output of a custom target (generator):
```
nasm = find_program('nasm')
asm_sources = ['my_test.asm']
asm_gen = generator(nasm,
                    output: '@BASENAME@.o',
                    arguments: ['-f', 'win64', '@INPUT@', '-o', '@OUTPUT@'])
gen_objects = asm_gen.process(asm_sources)

static_lib = static_library('my_subproject-static', ['my_subproject.c', gen_objects])

lib = library('my_subproject', objects: static_lib.extract_all_objects())
```

When generating a Visual Studio solution with this project as a subproject on Windows, the paths to the object files generated by the generator are incorrect:

```
        <ItemGroup>
                <Object Include="subprojects\my_subproject\c490a2a@@my_subproject-static@sta\my_test.o"/>
                <Object Include="..\..\subprojects\my_subproject\c490a2a@@my_subproject-static@sta\my_subproject.c.obj"/>
        </ItemGroup>
```

**To Reproduce**

A minimal working example can be found [here](https://github.com/Myaamori/meson_mwe/tree/master/vs2019_custom_target).

Generate the solution using
```
meson build --backend=vs2019
```

and inspect `build/subprojects/my_subproject/[HASH]@@my_subproject@sha.vcxproj`.

`nasm` must be available.

**Expected behavior**

The paths should look like
```
        <ItemGroup>
                <Object Include="..\..\subprojects\my_subproject\c490a2a@@my_subproject-static@sta\my_test.o"/>
                <Object Include="..\..\subprojects\my_subproject\c490a2a@@my_subproject-static@sta\my_subproject.c.obj"/>
        </ItemGroup>
```

**system parameters**
* Native build
* Windows 10
* Python 3.8.6
* Meson 0.56.0

### PR DESCRIPTION
**Pull request by vvainola**
- Changed the object names built from generated sources on VS backend
to match filenames used in ninja backend

fixes #8020

### CODE REVIEW

**Comment by vvainola** [comment]
I don't know how to fix the unity builds

**Comment by jpakkane** [comment]
Test failure seems relevant:

```
ninja: error: 'subprojects/s1/libsub_a.a.p/meson-generated_sub_a-unity1.c.o', needed by 'subprojects/s1/libsub_b.a', missing and no known rule to make it
```

**Comment by CoffeeFlux** [comment]
Would love to see this land - any chance of re-running the lanes so I can see the failure?

**Comment by jpakkane** [comment]
There does not seem to be a button for that so it would need a rebase.

**Pull request closed without merging**
