### PR TITLE
build: Custom target with `.dll.a` output links dynamically

### PR DESCRIPTION
**Pull request by xclaesse**
Those are generally import libraries generated by mingw.

Fixes: #12120

### CODE REVIEW

**Comment by kasper93** [comment]
Fails when linking to libplacebo.dll `lld: error: unable to find library -lucrt_math.dll`

It add `-lucrt_math.dll` to pkg-config
```
Libs: -L${libdir} -lplacebo -lm -lshlwapi -lversion -lucrt_math.dll
```
while we already linked import library in, so it will be imported during run-time, no need to specify it again.

**Comment by xclaesse** [comment]
Damned :(

TBH the fact that your trick fails with newer mingw too makes me wonder if we should support this case at all...

**Comment by kasper93** [comment]
> TBH the fact that your trick fails with newer mingw too makes me wonder if we should support this case at all... 

It doesn't fail, with newer, it just fails on 23.04. I'm testing in MSYS2, which has latest mingw-w64, people are building it daily from git.

> Maybe fix pow perf in mingw? That would really benefit everyone...

Actually I would love that too, I poked them on IRC about it and here https://github.com/mstorsjo/llvm-mingw/issues/361, it is know issue. Also fixing it will help in like few years, once it hit Ubuntu LTS and other big distors.

> Damned :(

Ok, actually what I need is just `link_args`. But I need to connect `custom_target` somehow? And it cannot be `sources`, because it will add the output of custom target to sources, which I don't want.

How can I connect it differently? Do you have clever idea?

**Comment by eli-schwartz** [comment]
> It is just that we want this only for `.dll` linking. It is quite specific case, that I don't think meson can detect automatically and it was working before, only because meson was missing this import.... but then it likely caused issues, when we actually **do** want to link it.

Right, this may be a sign that meson should revert entirely and go back to warning you that it might not work but not actually erroring out, since we cannot actually guarantee that it doesn't, in fact, error out.

**Comment by xclaesse** [comment]
> Ok, actually what I need is just `link_args` (it works if .lib is already generated).

I indeed think that using `link_args` here is what matches the best your specific case. Sounds like something you would usually do with a linker script for example.

> But I need to connect `custom_target` somehow. And it cannot be `sources`, because it will add the output of custom target to sources, which I don't want.

Hmm, that's probably an issue in Meson too. Actually many issues...
- `declare_dependency()` is missing `link_depends` argument.
- `link_args` in both `library()` and `declare_dependency()` should ideally allow passing a CustomTarget and add the link_depends automatically.
- libraries passed to `sources` should probably be only passed to dynamic linker, not for static libraries.

1 and 2 is new API that could be added to 1.3.0, but 3 is something we could potentially fix in 1.2.2.

**Comment by xclaesse** [comment]
@kasper93 not ideal, but you can add `link_args` and `link_depends` directly to `library()` without using a `declare_dependency()`. Does that work?

**Comment by xclaesse** [comment]
Ok, closing this PR since it does not fix anything.

**Pull request closed without merging**
