### PR TITLE
fix style errors in fs.relative_to implementation

### PR DESCRIPTION
**Pull request by eli-schwartz**
In commit f52bcaa27fc125ab9ae583af466ba99c164169f3 a few issues were added:
- doc typo
- imports for utils.universal are not intended to be directly used, it's an internal wrapper that exists solely to make mesonlib work well as it always did while simultaneously allowing `meson --internal` codepaths to avoid importing anything other than an extremely stripped down core
- type annotation specific import was imported at runtime scope

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]

**Comment by tristan957** [comment]
https://github.com/mesonbuild/meson/actions/runs/5895033335/job/15989913509#step:8:2592

The error seems to be we are just missing the .exe? Why not just fix the mistake instead of backing the whole thing out?

**Comment by tristan957** [comment]
```
- if host_machine.system() == 'windows'
+ if host_machine.system() in ['windows', 'cygwin']
```

**Comment by tristan957** [comment]
:|

**Comment by tristan957** [comment]
had a PR up to fix it...........................................................................................................................................................................................................................

**Comment by xclaesse** [comment]
@eli-schwartz you are the one who tells people to respect policies, then merge stuff with no review? You added commits to this PR after @tristan957 approval, then merged without waiting. Especially when reverting his work... That's not nice!

If we can just merge stuff like that, I have like 20 PRs waiting...

**Comment by xclaesse** [comment]
That said, thanks for fixing the CI :)

**Comment by eli-schwartz** [comment]
@tristan957 sorry for not noticing your reply. There were some motivating factors here though:
- I had spent the evening debugging CI (btw this is frustrating to have to do, and also a time sink, so it makes me a bit grumpy FWIW)
- it was actually after midnight for me
- I hadn't checked this page, and I didn't notice the email, until this morning

@xclaesse 

> you are the one who tells people to respect policies, then merge stuff with no review? You added commits to this PR after @tristan957 approval, then merged without waiting. Especially when reverting his work... That's not nice!

Fortunately, I do not have to care. https://mesonbuild.com/Contributing.html#a-green-ci-run-is-mandatory-for-merging

"If a merge causes CI failure any developer can revert it out of master. It is then the responsibility of the original submitter to resubmit a fixed version."

At a certain point, I realized there wasn't much left of my PR. I didn't have to bother with a PR, and I didn't have to bother with seeking approval, and I am under no obligation to be nice when reverting someone's work, because... CI failed. As stated in the developer guidelines, that means I can git revert and push directly to master -- I don't even have to submit a PR.

Sure, if it can be fixed instead, that's great. But I wasn't sure how to fix it, it was late, and I wanted to finally be able to merge other PRs that have been patiently waiting instead of being merged with failing CI. And quite frankly, it is not my job after midnight to figure out how to fix someone else's broken CI.

If I may offer a personal recommendation -- don't merge PRs with failing CI, which is also not "nice". Then no one else will have to be "not nice" when they are at the end of their rope and trying to get master unblocked.

So, I'm not going to apologize for respecting the policies.

> If we can just merge stuff like that, I have like 20 PRs waiting...

You can't threaten me with something you already do lmao.

**Pull request merged**
