### PR TITLE
Add more version information to compiler

### PR DESCRIPTION
**Pull request by behlec**
Fixes issue #2762.

Add full_version variable to class Compiler and selected subclasses. It is passed as named parameter. For selected compilers the first line of `CC --version` is passed to full_version.

When the full_version is given it is printed as an additional version information.

This feature is currently only added to limited set of compilers.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Flake8 detected 6 issues on 1f3b41021d22b90e92e762a9b0230968957f5ba6
Visit https://sideci.com/gh/19784232/pull_requests/2791 to review the issues.

**Comment by jpakkane** [comment]
The output I get does not seem to have that:

    Project name: trivial test
    Native C compiler: gcc (gcc 7.2.0)
    Build machine cpu family: x86_64

**Comment by behlec** [comment]
Hmm, I will look into this.

Btw. let me know if the solution with kwargs is ok and whether I should extend it to all compilers or keep it to those where it is supported right now.

**Comment by jpakkane** [comment]
This is good. I'll merge this since it is useful on its own. If you wish to add this to more compilers, feel free to open new MRs.

**Comment by behlec** [comment]
OK, I will not add more without requests. I feel unkomfortable to add compiler without testing them. I do not want to have some garbage in that line. If somebody has a specific wish let me know, adding it would be trivial.

**Pull request merged**
