### PR TITLE
Fix depfixer on MIPS. Contributed by Aurelien Jarno.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
You know that there is 'git commit --author=', right?

**Comment by jpakkane** [comment]
No, I don't know that. Nor do I care. I hate git wanking more than most of the things in this world.

**Comment by TingPing** [comment]
One could argue clearly retaining authorship over code isn't *"git wanking"*

**Comment by nirbheek** [comment]
I think it's good to retain the author in commits if only because the person who wrote that patch can feel good knowing their name is in the log.

However, there are also legal reasons for doing that. You want your commit history to reflect exactly who has copyright on what parts of your code.

**Pull request merged**
