### PR TITLE
cmake: Fix dependency loops in custom targets (fixes #6632)

### LINKED ISSUE #6632: Meson incorrectly detects loop in CMake custom target
**Describe the bug**
 If a CMake subproject contains a custom target in which the basename of the output file is the same as the basename of the input file, importing it into meson will incorrectly generate the following error:
```
meson.build:3:0: ERROR: Cycle in CMake inputs/dependencies detected.
```
Building the same project in CMake works as expected.

**To Reproduce**
* Clone the example repository at https://github.com/conte91/meson_cmake_cycle_issue
* Run `meson build`

**Expected behavior**
The `test.txt` target is correctly detected to be an output file, depending on the input file at `subprojects/test_cmake/test.txt`.

**system parameters**
* Native build
* Arch Linux
* Python 3.8.1
* `meson --version` 0.53.0

### PR DESCRIPTION
**Pull request by mensinda**
Closes https://github.com/mesonbuild/meson/issues/6632

### CODE REVIEW

**Comment by nirbheek** [comment]
What are we blocked on to merge this? :)

**Comment by mensinda** [comment]
A review of the PR :) It was confirmed in #6632 that this PR fixes the issue.

**Comment by nirbheek** [comment]
@xclaesse @scivision maybe one of you can review this? Looks fine to me from a cursory read but I don't know this code.

**Comment by jpakkane** [comment]
Especially since this is the last item in 0.53.2. We should be able to craft a release once this MR is in.

**Comment by jpakkane** [comment]
LGTM and no-one raised issues, so merging. @nirbheek are you now ready to release 0.53.2 or are there still issues?

**Comment by nirbheek** [comment]
This PR seems to depend on https://github.com/mesonbuild/meson/pull/6432, @mensinda is that PR also safe to pull into the stable release or would you like to make a separate PR for the stable release?

**Comment by mensinda** [comment]
I would say that pulling #6432 would safe for the stable release (the majority is just moving code around).

**Comment by nirbheek** [comment]
Hmm, also needs https://github.com/mesonbuild/meson/pull/6531.

**Comment by mensinda** [comment]
That one shouldn't be required.

**Comment by nirbheek** [comment]
Could you open a PR that backports this please? I suspect I might mess up while backporting :)

**Comment by mensinda** [comment]
Done, see #6679.

**Pull request merged**
