### PR TITLE
Flatten suites

### PR DESCRIPTION
**Pull request by tristan957**
Flattening the suite value is more in-line with the rest of Meson

### CODE REVIEW

**Comment by tristan957** [comment]
Please let me know where the best place to place a test would be.

**Comment by jpakkane** [comment]
Please modify one of the existing suites to require flattening so we know that this works as expected.

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by tristan957** [comment]
Grrrr. Fixing now.

**Comment by jpakkane** [comment]
```
   File "/__w/meson/meson/mesonbuild/interpreter/interpreterobjects.py", line 730, in SubprojectHolder
    @permissive_unholder_return
NameError: name 'permissive_unholder_return' is not defined
```

**Comment by tristan957** [comment]
I literally don't understand my editor

**Pull request merged**
