### PR TITLE
n_debug support for D lang

### PR DESCRIPTION
**Pull request by dcbaker**
This makes two changes, first is that it generalizes n_debug, which previously always set `-DNDEBUG`, which of course doesn't make sense outside of a few languages. Instead this is now set in the compiler class with the `get_disable_assert_args` method. The second is to turn on n_debug for D language.

For D this means setting the `-release` flag (or similar for ldc2 and gdc). This turns off assertions, contracts, and array bounds checking in some cases.

Fixes: #7082

### CODE REVIEW

**Comment by jpakkane** [comment]
I'd really like to hear from D users if this behaviour makes sense for them conceptually. I guess maybe @ximion would know?

**Comment by denizzzka** [comment]
> I'd really like to hear from D users if this behaviour makes sense for them conceptually.

I use D and I agreed with this changes

Also maybe it makes sense (to avoid compilers defaults changes in future) add debug options:

`-debug` (Compile in debug code) for DMD and
`-d-debug` for LDC (can also be specified without options, in which case it enables all debug checks (i.e. asserts, boundschecks, contracts and invariants) as well as acting as -d-debug=1.)

**Comment by denizzzka** [comment]
ldc2 also supports `minsize` option by passing `--Oz` or `-Oz`
I am daily use it from cross file without problems.

**Comment by jpakkane** [comment]
Merging then. Thanks.

**Pull request merged**
