### PR TITLE
Let .pc files provide rpaths.

### PR DESCRIPTION
**Pull request by dankegel**
Marks injected buildtime rpaths with the suffix /./., and then removes only those when installing.

### CODE REVIEW

**Comment by dankegel** [comment]
@michaelkuhn, I also tested by verifying that this patch rescues spack's gtkplus build when dropped in as a replacement for spack's existing kludge var/spack/repos/builtin/packages/meson/rpath-0.54.patch.

**Comment by dankegel** [comment]
This is still a WIP.  
e.g. it still needs to remove rpaths added by the user's build_rpath, not just the ones synthesized by meson itself.

**Comment by jpakkane** [comment]
Perhaps it would be better if the function that determines rpaths would return a list of strings to be removed (that is, those added by Meson itself for build dir usage) which would then be passed to the rpath fixer script somehow.

**Comment by dankegel** [comment]
Probably, thanks.

**Comment by dankegel** [comment]
It would clearly be preferable to avoid the /./. mark in the actual RPATH.

Instead of marking rpaths in build_rpath_args, I could hand them to the caller (generate_link) which would save them in target; then generate_target_install would save them in InstallTargetData,
and install_targets() could pass them to fix_rpath()

I see three options for how to get the rpaths out of build_rpath_args:
- pass it a list to add to as a side effect
- have it return the pair (args, build_rpaths)
- refactor it into two functions, gather_rpaths() and build_rpath_args()

Maybe I'll try one of those approaches.  Comments welcome.

**Comment by dankegel** [comment]
Closing in favor of https://github.com/mesonbuild/meson/pull/7103

**Pull request closed without merging**
