### PR TITLE
summary: Add from which subproject each subproject have been called

### PR DESCRIPTION
**Pull request by xclaesse**
meson

### CODE REVIEW

**Comment by xclaesse** [comment]
I find that summary a bit too much loaded, but really useful information. Anyone has a better idea to present this?

**Comment by tp-m** [comment]
Looks ok to me, not sure how to make this 'lighter' without adding an option and not printing it by default (not sure that's warranted here though).

Alternative would be to print the 'from' hierarchy (e.g. `gst-plugins-good -> libsoup` for `libpsl`) in the main log when entering the subproject (don't remember if we do that already)

**Comment by jpakkane** [comment]
Looks nice indeed. The only thing that is a bit weird is the `(from pango)` which is a bit confusing. Maybe `(requested by pango)`? It gets a bit long-winded, though.

**Comment by xclaesse** [comment]
> Alternative would be to print the 'from' hierarchy (e.g. `gst-plugins-good -> libsoup` for `libpsl`) in the main log when entering the subproject (don't remember if we do that already)

I think we should do that too, yes. I was also wondering if I could add the hierarchy in summary too:
meson

**Comment by xclaesse** [comment]
Or move the call stack in the key side:
meson

**Comment by jpakkane** [comment]
Or maybe in tabular form so we can also add the info of a forwaring wrap file. Something like:

```
subproject            requested by          using from

foo                   main                        main
bar                   bar                          foo
```

Where bar is a subproject inside foo. Maybe "main" could even be left empty, so only non-standard ones are printed?

**Comment by xclaesse** [comment]
Rebased this PR, it prints the summary like screenshot from https://github.com/mesonbuild/meson/pull/7829#issuecomment-706727226.

Any objection?

**Comment by xclaesse** [comment]
ping?

**Comment by xclaesse** [comment]
@jpakkane @eli-schwartz @tristan957 any objection?

**Comment by tristan957** [comment]
What are your thoughts on the table-based output?

**Comment by xclaesse** [comment]
> What are your thoughts on the table-based output?

IMHO it takes more space, a summary should be more compact. But that can be revisited later too I guess.

**Comment by tristan957** [comment]
Then the design is fine with me!

**Pull request merged**
