### PR TITLE
Use global args in tests

### PR DESCRIPTION
**Pull request by jpakkane**
The `test test_preprocessor_checks_CPPFLAGS` will fail. However it does not seem to make any sense as a test. Why would you want to not use `CFLAGS` in compiler checks. Those matter a lot since they will be used for every compilation step so the thing you are testing for is different from usage.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I think @nirbheek said that we didn't want this. In any case, I like this. What about project args? is it handled same way as global args here?

**Comment by jpakkane** [comment]
Project and global args are never used in tests. Only ones coming from options such as `c_args` and `c_link_args`. We already do this for things like `c_std` options.

This is needed to, e.g., make Flatpak builds work because in it all libs are under `/app/lib` and this is dealt with by passing `-L/app/lib` in `LDFLAGS`.

**Comment by nirbheek** [comment]
> The test test_preprocessor_checks_CPPFLAGS will fail. However it does not seem to make any sense as a test. Why would you want to not use CFLAGS in compiler checks

The test is only for `cc.get_define()` which only runs the pre-processor, so it should only read the pre-processor flags, not the compiler flags because they may be invalid for pre-processing. IIRC this will cause an error with MSVC.

**Comment by nirbheek** [comment]
FWIW, this is also what other build systems do: tests that run the compiler in preprocessor-only mode only pass `CPPFLAGS` to it.

**Comment by jpakkane** [comment]
> IIRC this will cause an error with MSVC.

Specifically what will fail and how?

Also, I have a hard time understanding how this could possibly even work. We don't store CPPFLAGS et al anywhere except in `c_args` et al. How are they getting in the checks and more importantly if you run Meson reconfigure later when `CPPFLAGS` is unset, should it then not use those flags in the tests?

**Comment by nirbheek** [comment]
> Specifically what will fail and how?

The preprocessor-only flags on gcc `-E -P` and on MSVC `/EP` are incompatible with some compile/link options, so if we pass `CFLAGS` to the compiler check, it might fail depending on what the user has set. I believe this is why Autotools has the distinction between `CPPFLAGS` and `CFLAGS`, and preprocessor-only compiler checks in Autoconf only use `CPPFLAGS`.

> We don't store CPPFLAGS et al anywhere except in c_args et al.

We store it on coredata as `self.external_preprocess_args`.

> How are they getting in the checks 

See: `compilers/c.py:_get_compiler_check_args()` `mode == preprocess`, this was added in https://github.com/mesonbuild/meson/pull/1511

> and more importantly if you run Meson reconfigure later when CPPFLAGS is unset, should it then not use those flags in the tests?

It will, because it's stored in the coredata, just not in `self.compiler_options` because those are exposed to the user.

**Comment by jpakkane** [comment]
Could we do the same thing we do for weird flags in .pc files et al and just filter out all known bad args from the argarray for tests that require that?

**Comment by nirbheek** [comment]
I think the architecture in this PR should be changed instead, because we're already adding `CFLAGS`/`LDFLAGS`/etc to compiler checks, see: `_get_compiler_check_args()` for how we they're added. I am not sure why it doesn't get added for `find_library()` and we should figure that out instead of adding a new mechanism.

Also this new mechanism is always adding linker flags even when we're only compiling, which is also incorrect.

**Comment by nirbheek** [comment]
1) When `find_library_real()` calls `self.links()`, that runs a compiler check that *should* add `c_args`/`c_link_args`, etc. Need to verify that that is happening.
2) When we do a manual search, we need to also parse `c_link_args` for `-L` args and extract `extra_dirs` out of it; same as `PkgConfigDependency._set_libs()`.

**Comment by jpakkane** [comment]
> Also this new mechanism is always adding linker flags even when we're only compiling, which is also incorrect.

I thought about this and tested and at least on GCC having linker flags there do not harm. In addition many tests run the resulting binary so the link args should be there otherwise it might not link properly and the test fails.

**Comment by nirbheek** [comment]
> In addition many tests run the resulting binary so the link args should be there otherwise it might not link properly and the test fails.

We already add the linker flags correctly when we need to link the output.

> I thought about this and tested and at least on GCC having linker flags there do not harm

It might work with GCC, but I really don't think we should gimp our abstraction for reasons I don't even understand, since the mechanism in this PR shouldn't even be needed. We already have codepaths to do what this PR does, they just don't seem to be working for all compiler checks for some reason.

**Comment by nirbheek** [comment]
The correct fix for this (IMO) is in https://github.com/mesonbuild/meson/pull/3894.

**Comment by jpakkane** [comment]
Having `external_preprocess_args` is bad because it is hidden internal state, and you can't change it (or even know that it exists) afterwards. This is terrible usability.

**Comment by jpakkane** [comment]
No, there is still the case of hidden, cached CPPFLAGS. They must go. I planned to update this with that once there is some spare time.

**Comment by nirbheek** [comment]
I forgot to mention this earlier, but there's another use-case where we need to store `CPPFLAGS` separately from cflags. On MSVC, to build an assembly file with `#include` and `#define`, you must manually pass the file through the C pre-processor and then compile the output with the assembler. See: https://github.com/centricular/libffi/blob/meson/src/meson.build#L55

I'm planning to implement that in Meson directly (so we don't have to do ugly generator hacks) and It's a requirement for pushing the libffi meson port upstream. That will also require access to `CPPFLAGS` separately. 

I still believe that trying to clump the pre-processor and compiler flags into one list is a bad idea and will burn us in the future when more use-cases such as the MSVC one make themselves evident.

**Comment by jpakkane** [comment]
Filtering out the bad flags when doing MSVC calls is the nice UI of the two. CPPFLAGS is a very unixy concept (and not a particularly good one at that). If you have two places where to put compiler flags, the result is that people will get that wrong and they probably can't understand why. Every language designed since the 70s has two kinds of flags: compiler flags and linker flags. Some don't even have the latter.

If we can make it so that users don't have to even know what is the difference between CPPFLAGS and CFLAGS, then that is _good_.

**Comment by textshell** [comment]
I think the choice here is between hardcoding things in meson (and possibly requiring a new meson when new options are needed in the hard coded list) and having an UI where meson keeps these settings separate and the uses will often get the separation wrong.

But when we are going the hard coded way i would prefer to hardcode a whitelist for the preprocessor options rather than a blacklist. I would expect the speed of invention of new compiler options to be greater than the speed of invention of new preprocessor options.

**Comment by jpakkane** [comment]
Superseded so closing.

**Pull request closed without merging**
