### PR TITLE
coredata: store cross/native files in the same form they will be used

### PR DESCRIPTION
**Pull request by dcbaker**
Currently they're forced to absolute paths when they're stored in the
coredata datastructure, then when they're loaded we de-absolute path
them to check if they're in the system wide directories. This doesn't
work at all, since the ninja backend will generat a dependency on a
file that is in the source directory unless the path was already given
as absolute. This results in builds being retriggereed forever due to
a non-existant file.

The right way to do this is to figure out whether the file is in the
build directory, is absolute, or is in one of the system paths at
creation time, and store that path as absolute if it is outside the
build directory, or relative if it is within (so that a source
directory can be moved). Then the code that reads the file and the
code that generates the dependencies in the ninja backend just takes
the computed list and there is no mismatch between them.

### CODE REVIEW

**Comment by dcbaker** [comment]
@rossburton @Akaricchi, either of you interested in looking at this?

**Comment by Akaricchi** [comment]
This doesn't seem to work at all. Trying to set up a project (whether cross compiling or not; doesn't matter) invariably leads to this:

```
[130] [akari@navi] [/data/webshit/ports]
 % rm -rf taisei; meson setup ~/git/taisei taisei                    
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/environment.py", line 384, in __init__
    self.coredata = coredata.load(self.get_build_dir())
  File "/data/git/meson/mesonbuild/coredata.py", line 628, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/webshit/ports/taisei/meson-private/coredata.dat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/msetup.py", line 240, in run
    app.generate()
  File "/data/git/meson/mesonbuild/msetup.py", line 153, in generate
    env = environment.Environment(self.source_dir, self.build_dir, self.options)
  File "/data/git/meson/mesonbuild/environment.py", line 387, in __init__
    self.create_new_coredata(options)
  File "/data/git/meson/mesonbuild/environment.py", line 507, in create_new_coredata
    self.coredata = coredata.CoreData(options)
  File "/data/git/meson/mesonbuild/coredata.py", line 251, in __init__
    self.config_files = self.__load_config_files(options.native_file)
TypeError: __load_config_files() missing 1 required positional argument: 'ftype'
```

**Comment by dcbaker** [comment]
looks like my rebase broke :(

**Comment by dcbaker** [comment]
Okay, rebase fixed.

**Comment by Akaricchi** [comment]
Sorry for the delay. I've tested it now,; it seems to fix my problem indeed.

**Pull request merged**
