### PR TITLE
gnome: Re-use gobject-introspection-1.0 pkg-config dependency

### PR DESCRIPTION
**Pull request by nirbheek**
This avoids searching for gobject-introspection multiple times which is displayed multiple times too:

```
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
```

Also don't use `dependencies` as a module name since it is commonly used as a variable name too. Instead, directly import the classes that we use from that module.

### CODE REVIEW

**Comment by aduskett** [comment]
This would be useful as giscanner and gicompiler are still hardcoded to /usr/bin/ which is annoying in cross-compiled environments.

**Comment by xclaesse** [comment]
@aduskett this has been fixed 3 years ago ;-)

**Comment by aduskett** [comment]
Eh, gicompiler is still hardcoded as far as I can tell. Am I incorrect in this?

**Comment by xclaesse** [comment]
As far as I can tell it will look in your PATH. You can also override it in a cross/native file.

**Pull request merged**
