### PR TITLE
Run travis builds for all branches.

### PR DESCRIPTION
**Pull request by jameshilliard**
This restriction makes testing changes prior to pull requests annoying.

### CODE REVIEW

**Comment by scivision** [comment]
I am thinking of introducing a PR for staged CI that will run a quicker sanity check on changes for Azure and Travis, that checks for common problems before fanning out to all the different environments. That increases the overall test time a bit but avoids tying up all the CI parallel runs for trivially CI-failing PRs and future/prototype PRs

With that change, I think this PR would become less impactful on consumption of parallel CI images.

**Comment by scivision** [comment]
I attempted to do this in https://github.com/mesonbuild/meson/pull/5780 but either I made mistakes in .travis.yml or there are bugs in .travis.yml interpreter. It seems there are other issues open for Travis where there may be bugs. This is straightforward on Azure, I've done it elsewhere on Azure but Travis may break for this use case.

**Comment by jameshilliard** [comment]
> With that change, I think this PR would become less impactful on consumption of parallel CI images.

I'm not sure why this is a big issue, the only major difference should be that builds get run when new commits are merged/added to the main repo, builds done in repo fork branches would run in parallel to the pull request build.

**Comment by jpakkane** [comment]
We have kept Travis running only on master on purpose. The CI runs slow enough to get severely backlogged at times.

**Comment by jameshilliard** [comment]
> The CI runs slow enough to get severely backlogged at times.

Isn't that mostly because of pull request builds and not branch builds?

**Comment by jpakkane** [comment]
They come from the same pool methinks.

**Comment by jameshilliard** [comment]
> They come from the same pool methinks.

Sure, but my point is that the backlog is likely primarily due to pull request builds since those are likely updated much more often than changes are pushed to branches. At least that's been my experience for other projects. Regardless since builds are enabled for the master branch I don't see how enabling all branches would make a difference.

**Comment by tristan957** [comment]
We use GitHub Actions now, closing.

**Pull request closed without merging**
