### PR TITLE
Use a single ArgumentParser for all subcommands

### PR DESCRIPTION
**Pull request by xclaesse**
This has the adventage that "meson --help" shows a list of all commands,
making them discoverable. This also reduce the manual parsing of
arguments to the strict minimum needed for backward compatibility.

### CODE REVIEW

**Comment by jpakkane** [comment]
```
    setup               Configure the project
    configure           Change project options
    install             Install the project
    introspect          Introspect project
    init                Create a new project
    test                Run tests
    rewrite             Edit project files
    wrap                Wrap tools
    runpython           Run a python script
    help                Print help of a subcommand
```

`runpython` and `rewrite´ should not be there. The former is an internal thing and the latter does not work.

**Comment by xclaesse** [comment]
> `runpython` and `rewrite` should not be there. The former is an internal thing and the latter does not work.

That was more complicated than expected because of https://bugs.python.org/issue22848, but it's now done.

**Comment by nirbheek** [comment]
>  setup Configure the project
>  configure Change project options

Can we just take a moment to appreciate the beauty of this 😄

**Comment by xclaesse** [comment]
@nirbheek @jpakkane I resolved conflicts, can you please do a review to avoid having conflicts again, please? This PR move quiet a lot of code, so conflicts are likely.

**Pull request merged**
