### PR TITLE
Warn about .C and .H files

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
See https://github.com/mesonbuild/meson/pull/8239

### CODE REVIEW

**Comment by jpakkane** [comment]
The error message does not get printed in the way you'd expect it to:

```
WARNING: You are using .C or .H files in your project. This is deprecated.
         Currently, Meson treats this as C code, but this
            might change in the future, breaking your build.
         You code also might be already broken on gcc and clang.
         See https://github.com/mesonbuild/meson/pull/8239 for the discussions.
```

The indentation is there. The simplest way to fix this would be to make the error message a top level constant rather than having it inside the method.

**Comment by Volker-Weissmann** [comment]
> The error message does not get printed in the way you'd expect it to:
> 
> ```
> WARNING: You are using .C or .H files in your project. This is deprecated.
>          Currently, Meson treats this as C code, but this
>             might change in the future, breaking your build.
>          You code also might be already broken on gcc and clang.
>          See https://github.com/mesonbuild/meson/pull/8239 for the discussions.
> ```
> 
> The indentation is there. The simplest way to fix this would be to make the error message a top level constant rather than having it inside the method.

This is precisely the indentation that I wanted.

**Comment by jpakkane** [comment]
Actually, thinking further this might be ok (because the length of warning is always the same as Meson is not localised) but it should still be moved to a top level variable, having text strings with weird indentation inside Python code blocks looks unclean.

**Comment by Volker-Weissmann** [comment]
> Actually, thinking further this might be ok (because the length of warning is always the same as Meson is not localised) but it should still be moved to a top level variable, having text strings with weird indentation inside Python code blocks looks unclean.

Done

**Pull request merged**
