### PR TITLE
Adding dictionary entry using string variable as key.

### PR DESCRIPTION
**Pull request by franczc**
Hi,
I'd like to contribute this change which allows adding a dictionary entry using string variable as key, in addition to using string literal as key.

Example:
dict = {}
key = 'myKey'
dict += {key : 'myValue'}

### CODE REVIEW

**Comment by scivision** [comment]
This seems like a good feature and one a user would expect.

**Comment by scivision** [comment]
Adding as request for next major release so we don't forget about it.

**Comment by jpakkane** [comment]
Please add a failing test (in `test cases/failling`) that tries to use a non-string key, something like:

```meson
dict = {}
key = 1
dict += {key : 'myValue'}
```

**Comment by marc-h38** [comment]
This works only when I revert the second commit `Fixed issue that the key's value type wasn't checked correctly` of this PR on top of latest master 11639dd922aa. Ironically, with master 11639dd922aa alone I get:

 `ERROR: Key must be a string or string variable`

New test `common/228` passes with and without the revert, only my example is affected... I keep investigating.

**Pull request merged**
