### PR TITLE
vala: don't ignore vala_args. Closes #192

### LINKED ISSUE #192: vala: vala_args in executable() and add_global_arguments(language: 'vala') does donthing
If I use vala_args : 'blahblah' so nothing adds to `valac`

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by jpakkane** [comment]
retest this please

**Comment by jpakkane** [comment]
On ubuntu build fails with this:

../manual tests/7 vala composite widgets/mywidget.vala:3.2-3.12: error: glib 2.38 is required for using Gtk templates (with --target-glib=2.38)
[GtkTemplate (ui = "/org/foo/my/mywidget.ui")]
 ^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)

Detected dependencies:

Native dependency glib-2.0 found: YES 2.44.1
Native dependency gobject-2.0 found: YES 2.44.1
Native dependency gtk+-3.0 found: YES 3.14.13

**Comment by ignatenkobrain** [comment]
It looks like something happens with valac, not caused by my patch. And
this is not related to this PR. Support for --target-glib merged in
previous PR. This PR adds only support for vala_args.

-- 

-Igor Gnatenko

**Comment by jpakkane** [comment]
I get the exact same error on Fedora 21, too.

**Comment by ignatenkobrain** [comment]
```
[brain@x1carbon 7 vala composite widgets]$ ~/git/mesonbuild/meson/meson.py build/
The Meson build system
Version: 0.25.0-research
Source dir: /home/brain/git/mesonbuild/meson/manual tests/7 vala composite widgets
Build dir: /home/brain/git/mesonbuild/meson/manual tests/7 vala composite widgets/build
Build type: native build
Project name: composite
Native vala compiler: valac (unknown 0.29.2)
Native c compiler: ccache cc (gcc 5.1.1)
Warning, glib compiled dependencies will not work until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
Found pkg-config: /usr/bin/pkg-config (0.28)
Native dependency glib-2.0 found: YES 2.45.3
Native dependency gobject-2.0 found: YES 2.45.3
Native dependency gtk+-3.0 found: YES 3.17.4
Build targets in project: 3
[brain@x1carbon 7 vala composite widgets]$ ninja-build -C build
ninja: Entering directory `build'
[6/6] Linking target demo
[brain@x1carbon 7 vala composite widgets]$ 
```
vala-0.29.2-1.fc23.x86_64
glib2-devel-2.45.3-2.fc23.x86_64

**Comment by jpakkane** [comment]
Upgrade to Fedora 22, still fails:

    The Meson build system
    Version: 0.25.0-research
    Source dir: /home/jpakkane/meson/manual tests/7 vala composite widgets
    Build dir: /home/jpakkane/meson/work area
    Build type: native build
    Project name: composite
    Native vala compiler: valac (unknown 0.28.0)
    Native c compiler: cc (gcc 5.1.1)
    Warning, glib compiled dependencies will not work until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
    Found pkg-config: /usr/bin/pkg-config (0.28)
    Native dependency glib-2.0 found: YES 2.44.1
    Native dependency gobject-2.0 found: YES 2.44.1
    Native dependency gtk+-3.0 found: YES 3.16.4
    Build targets in project: 3
    localhost 0 > ninja -C work\ area                                   [ ~/meson ]
    ninja: Entering directory `work area'
    [4/6] Compiling Vala source '../manual...vala composite widgets/mywidget.vala'.
    FAILED: valac '-d' 'demo.dir' '-C' '--deps' 'demo.dir/mywidget.c.d' '--pkg' 'glib-2.0' '--pkg' 'gobject-2.0' '--pkg' 'gtk+-3.0' '--gresources=/home/jpakkane/meson/manual tests/7 vala composite widgets/my-resources.xml' '../manual tests/7 vala composite widgets/mywidget.vala'
    ../manual tests/7 vala composite widgets/mywidget.vala:3.2-3.12: error: glib 2.38 is required for using Gtk templates (with --target-glib=2.38)
    [GtkTemplate (ui = "/org/foo/my/mywidget.ui")]
     ^^^^^^^^^^^
    Compilation failed: 1 error(s), 0 warning(s)
    ninja: build stopped: subcommand failed.

Valac is version 0.28, glib is 2.44.1. If you add the --target-glib=2.38 flag manually it compiles and works.

**Comment by ignatenkobrain** [comment]
GH didn't closed PR as it was merged. https://github.com/mesonbuild/meson/commit/5cbcb144fa42cdf18e39212de7f82c537116d9a5

**Pull request closed without merging**
