### PR TITLE
logical operators on feature objects

### PR DESCRIPTION
**Pull request by bruchar1**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
How does this play together with the method-based approach that already works? 

Also I'm wary of overloading boolean operators here.

**Comment by bruchar1** [comment]
Maybe I took the wrong approach. Here is what I want to do:

I want features to disable parts of my build. Lets say I have three features: "with_a", "with_b", and "with_c". I can skip a dependency using `dependency('my_dep', required: get_option('with_a'))`.

Now suppose I have a dependency required "with_a" and "with_b", but not "with_c". I'd like to search for the dependency if either "with_a" or "with_b" is enabled. I can do something like:

```
if get_option('with_a').enabled() or get_option('with_b').enabled()
    my_dep = dependency(...)
else
    my_dep = dependency('', required: false)
endif
```

But since I will need this same logic in several places, it could by handful to be able to create a `feature` object that is 'enabled' if either 'with_a' or 'with_b' feature is 'enabled'. That way, I could then used this constructed feature as argument to `dependency(required: )`

**Comment by eli-schwartz** [comment]
```meson
get_option('with_a').enable_auto_if(get_option('with_b').enabled())
```

Maybe?

The enable_auto_if method returns an enabled feature if with_b is enabled, or else returns the same as with_a.

**Comment by bruchar1** [comment]
I'm not sure `enable_auto_if` really helps...

My first idea was to be able to logically combine features, to use them for the `required` argument of `dependency`.

Maybe an other approach would be to have a `feature` function to allow the dynamic creation of feature objects in meson.build files.

Or maybe I can just use `if` blocks...

**Comment by bruchar1** [comment]
I can do something without this. I'm closing now, because it doesn't seem to be the right approach.

**Pull request closed without merging**
