### PR TITLE
BasicLinkerIsCompilerMixin and Emscripten fixes

### LINKED ISSUE #5900: Emscripten: AttributeError: 'NoneType' object has no attribute 'get_allow_undefined_args'
Looks like there is no linker detected for emcc, which could be the issue.

```
$ meson --wipe ~/git/taisei
The Meson build system
Version: 0.51.999
Source dir: /data/git/taisei
Build dir: /data/webshit/ports/taisei
Build type: cross build
Project name: taisei
Project version: v1.4-dev
C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
C linker for the build machine: lld 8.0.1
C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: wasm32
Host machine cpu: wasm32
Target machine cpu family: wasm32
Target machine cpu: wasm32
DEPRECATION: Project targetting '>=0.45.0' but tried to use feature deprecated since '0.48.0': python3 module
Program thunk.py found: YES (/data/git/taisei/scripts/thunk.py)
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wpedantic: YES 
Compiler for C supports arguments -Werror=assume: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Wabsolute-value: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wcast-align=strict: NO 
Compiler for C supports arguments -Wcast-function-type: NO 
Compiler for C supports arguments -Wclobbered: NO 
Compiler for C supports arguments -Wduplicated-branches: NO 
Compiler for C supports arguments -Wduplicated-cond: NO 
Compiler for C supports arguments -Wfloat-overflow-conversion: YES 
Compiler for C supports arguments -Wfloat-zero-conversion: YES 
Compiler for C supports arguments -Wfor-loop-analysis: YES 
Compiler for C supports arguments -Wformat-pedantic: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wgcc-compat: YES 
Compiler for C supports arguments -Wgnu: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wlogical-op: NO 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wno-long-long: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-typedef-redefinition: YES 
Compiler for C supports arguments -Wnull-dereference: YES 
Compiler for C supports arguments -Wparentheses: YES 
Compiler for C supports arguments -Wshadow=compatible-local: NO 
Compiler for C supports arguments -Wsometimes-uninitialized: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wunneeded-internal-declaration: YES 
Compiler for C supports arguments -Wunreachable-code: YES 
Compiler for C supports arguments -Wunreachable-code-loop-increment: YES 
Compiler for C supports arguments -fexcess-precision=standard: YES 
Compiler for C supports arguments -fmerge-all-constants: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-signaling-nans: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -msse -mfpmath=sse: NO 
Looking for a fallback subproject for the dependency freetype2 because:
Use of fallback dependencies is forced.

|Executing subproject freetype method meson 
|
|Project name: freetype2
|Project version: 2.10.1
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|Compiler for C supports arguments -Wcast-function-type: NO (cached)
|Header <unistd.h> has symbol "_POSIX_VERSION" : YES 
|Has header "unistd.h" : YES 
|Has header "fcntl.h" : YES 
|Has header "stdint.h" : YES 
|Looking for a fallback subproject for the dependency zlib because:
|Use of fallback dependencies is forced.
|
||Executing subproject zlib method meson 
||
||Project name: zlib
||Project version: 1.2.11
||C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
||C linker for the build machine: lld 8.0.1
||C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
||Compiler for C supports arguments -Wno-implicit-fallthrough: YES 
||Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
||Build targets in project: 2
||Subproject zlib finished.
|
|Dependency zlib from subproject subprojects/zlib found: YES
|Configuring ftconfig.h using configuration
|Configuring ftoption.h using configuration
|Build targets in project: 3
|Subproject freetype finished.

Dependency freetype2 from subproject subprojects/freetype found: YES
Looking for a fallback subproject for the dependency opusfile because:
Use of fallback dependencies is forced.

|Executing subproject opusfile method meson 
|
|Project name: opusfile
|Project version: 0.11
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|
|subprojects/opusfile/meson.build:3:0: Exception: 'NoneType' object has no attribute 'get_allow_undefined_args'

Subproject opusfile is buildable: NO (disabling)
Dependency opusfile from subproject subprojects/opusfile found: NO
Looking for a fallback subproject for the dependency libpng because:
Use of fallback dependencies is forced.

|Executing subproject libpng method meson 
|
|Project name: libpng
|Project version: 1.6.37
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|Dependency zlib from subproject subprojects/zlib found: YES
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/msetup.py", line 244, in run
    app.generate()
  File "/data/git/meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/data/git/meson/mesonbuild/msetup.py", line 191, in _generate
    intr.run()
  File "/data/git/meson/mesonbuild/interpreter.py", line 3992, in run
    super().run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1053, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 778, in function_call
    return func(node, posargs, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3082, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3142, in dependency_impl
    return self.dependency_fallback(display_name, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3193, in dependency_fallback
    self.do_subproject(dirname, 'meson', sp_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 2524, in do_subproject
    raise e
  File "/data/git/meson/mesonbuild/interpreter.py", line 2508, in do_subproject
    return self._do_subproject_meson(dirname, subdir, default_options, required, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 2535, in _do_subproject_meson
    subi.run()
  File "/data/git/meson/mesonbuild/interpreter.py", line 3992, in run
    super().run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1053, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 457, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 490, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1020, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1020, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
    return self.method_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 815, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 325, in method_call
    return method(args, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 1564, in find_library_method
    linkargs = self.compiler.find_library(libname, self.environment, search_dirs, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 997, in find_library
    return self.find_library_impl(libname, env, extra_dirs, code, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 987, in find_library_impl
    value = self.find_library_real(libname, env, extra_dirs, code, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 946, in find_library_real
    largs = self.get_allow_undefined_link_args()
  File "/data/git/meson/mesonbuild/compilers/compilers.py", line 1044, in get_allow_undefined_link_args
    return self.linker.get_allow_undefined_args()
AttributeError: 'NoneType' object has no attribute 'get_allow_undefined_args'
```

### PR DESCRIPTION
**Pull request by Akaricchi**
Fixes #5900 

This PR kind of does two things at once; let me know if you want it split.

### CODE REVIEW

**Comment by Akaricchi** [comment]
It's pretty obvious that the emscripten support hasn't been tested at all after the linker separation stuff got merged. Can we add any emscripten-specific tests to the suite somehow?

**Comment by jpakkane** [comment]
That is not really the difficult bit. The problem is installing an emscripten toolchain in the CI image. It is already inconvenienly big at 4.5 gigabytes.

**Comment by dcbaker** [comment]
@jpakkane does it make sense to have a separate CI image that only runs project tests for some less common languages? We also don't test gdc or dmd from D, and a number of other cases like that.

**Comment by dcbaker** [comment]
I think this is fine as a single PR, there are two logical changes, butt they're tightly coupled in our abstraction already.

**Comment by scivision** [comment]
Might become more convenient to have multiple Docker images as Github Actions rolls out with their Docker registry, perhaps at least with regard to speed. Im quite impressed so far with Actions ease of use and performance.

**Comment by Akaricchi** [comment]
@jpakkane, @dcbaker can we get this in before #5912?

**Comment by jpakkane** [comment]
Tests are failing, they need to be fixed before this can be merged. The logs have been removed from azure, so needs at least a rebase to check that things work.

**Comment by Akaricchi** [comment]
@jpakkane @dcbaker 

I've fixed the previous D regressions in https://github.com/mesonbuild/meson/pull/5901/commits/04d6a439457d76b9cf4c4f98fce238219366e241, but I've no idea what the hell is wrong with optlink now and how it's relevant to my changes.

I can not reproduce the new test failures. I'm not a windows user. An honest attempt to set up meson and DMD in a Windows 10 VM has been made and failed. 

This is as much patience as I'm willing to lend to this hostile dumpster fire of a platform. I suggest we merge this and let someone who cares about both Windows and D fix this mess. The reason why the D compilers worked as-is is basically an accident anyway.

**Comment by Akaricchi** [comment]
Ok, I've fixed the D stuff. It's not a good fix, but it's exactly as bad as it was before, except the fact that it even works is not an accident anymore.

Ping @jpakkane, @dcbaker

**Pull request closed without merging**
