### PR TITLE
Better built-in hint

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
I don't want to open an issue about this, but I think it should be possible to silence the hint. Some projects keep a carefully curated list of warnings that they enable and disable, possibly depending on the compiler, and the meson hint is not useful. I'd prefer not to have this warning visible in systemd forever.

**Comment by scivision** [comment]
Would there be a command line option to mute the hints? This PRi s also good for certain compilers who need a list of project-speciifc options to avoid massive amounts of unneeded feedback.

**Comment by keszybz** [comment]
I had in mind an option e.g. to the `project()` definition. This hint is mostly for the project authors, while a command line options is mostly useful for project users.

**Comment by scivision** [comment]
OK cool, this is an option I'd like to use.

**Comment by jpakkane** [comment]
These hints should only be printed for things we have builtin options for, such as adding `-Wall` by hand. That should never be needed, it is usually just a superstition carried over from handwritten Makefiles when nothing was done for you. What flag is it warning about for you?

**Comment by keszybz** [comment]
It's warning about `-Wextra`.

In our case, we enable and disable specific warnings to have a fully quiet output when built without optimization, but still get warnings for things that recent gcc can reliably detect. We have a lot of tricky macros and variadic code and such, and simply enabling "all" warnings results in many many false positives. So we have reached some specific set of flags that works for us. Going through meson's warning_level just adds a level of indirection that doesn't buy us anything.

**Comment by jpakkane** [comment]
> Going through meson's warning_level just adds a level of indirection that doesn't buy us anything.

It's not quite as straightforward as that. One of the things we strive for in Meson is to try to make different Meson projects as similar as possible. The idea is that people should be able to switch between different Meson projects and pretty much understand what they are doing. In this way whenever you use existing functionality, people will immediately understand what they mean. If a project chooses to reimplement existing functionality (and, yes, there are valid reasons for doing that in rare cases), then participating becomes a little bit harder, because you need to grok what the code is and what it is doing.

In this particular case you are already using Meson's builtin warnings, because you are not adding `-Wall` by hand, it comes by default since your warning level option has its default value of 1. The "mesonic" way of setting this up would be to remove `-Wextra` from the list of flags you check and instead add a `default_options` that sets `warning_level` to 2. You can even add an `assert(get_option('warning_level') >= 2, 'some message')` if you are feeling paranoid.

All of that being said, we could make it so that the hint is not printed if the project has set its warning level to 0. This is for those very rare cases where people absolutely, positively have to micromanage every single warning flag.

But anyway, that is a discussion that should be held somewhere else than this MR. Merging, thanks.

**Comment by keszybz** [comment]
Makes sense. I submitted a PR to systemd to bump `warning_level` to 2: https://github.com/systemd/systemd/pull/13989.

**Pull request merged**
