### PR TITLE
Support gcovr >= 3.1 and add gcovr html report as fallback

### PR DESCRIPTION
**Pull request by thejk**
gcovr 3.1 changed the meaning of the -r/--rootdir option so includes a fix for that.
gcovr 3.0 added html report support so adding that as a fallback to lcov & genhtml (from 3.1 to keep things simple)

### CODE REVIEW

**Comment by jpakkane** [comment]
The variable name of `gcovr_3_1` is a bit confusing as it is a boolean. A more descriptive name would be useful. How about `gcovr_has_html`?

**Comment by thejk** [comment]
That was actually the name I used first, until I found the root dir problem which is in the first commit.
gcovr_newer_than_3_1, gcovr_new_rootdir?

**Comment by jpakkane** [comment]
`gcovr_new_rootdir` seems good. Let's do that.

**Comment by thejk** [comment]
I'm fairly certain these last failing checks are unrelated to my changes.
Travis fails with `ERROR: test_pkgconfig_gen_deps (__main__.LinuxlikeTests)` on Mac OS X
AppVeyor fails with `Command executed with exception: warning: mingw-w64-i686-python3-3.6.4-2 is up to date -- reinstalling` on msys2-mingw

**Pull request merged**
