### PR TITLE
Fix soname symlink generation

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by tp-m** [comment]
Why? What is the rationale for this? What does this fix? Please mention in the commit message :)

**Comment by nirbheek** [comment]
a) This will break ABI because we won't output the same shared libraries anymore, and more seriously...

b) This will mean that there is no way to exactly reproduce the versioning (and ABI) that Autotools produces. For instance, for gstreamer Autotools produces:

```
libgstreamer-1.0.so -> libgstreamer-1.0.so.0.404.0
libgstreamer-1.0.so.0 -> libgstreamer-1.0.so.0.404.0
libgstreamer-1.0.so.0.404.0
```

And so on for other Autotools-based projects. Currently, we get this in Meson by setting `soversion` to `0`, and `version` to `0.404.0`. We also get this by simply setting `version` to `0.404.0`.

From what I can see, with these changes there is no way to get this at all, which is unacceptable for any Autotools project with users in the wild that wants to move to Meson.

**Comment by jpakkane** [comment]
The reason I did this is that there is a project (Angelscript) that sets `soname` to `1.2.3`. We currently allow only single numbers. Then I fixed the symlinks to do what CMake does because I assumed that is also what Autotools does. Apparently not. Now we need to come up with a way to make both of these work.

If you build the CMake project you will find that it does the following:

    libbothset.so -> libbothset.so.1.2.3
    libbothset.so.1.2.3 -> libbothset.so.4.5.6
    libbothset.so.4.5.6

Note that the `so` points to `1.2.3` and not to `4.5.6.`, which is what Autotools points to. So the question is, which one of these is the correct thing to do?

**Comment by nirbheek** [comment]
Also, please detail the changes in the commit message. One-sentence commit messages are not useful. A commit message should explain why a particular change was made preferably with links to resources and documentation that were referred to while making that change. 

Without context, it makes it really hard (almost impossible) for anyone else to review or comment on the changes which defeats the purpose of having all changes go through PRs. ;) 

Worse, even if we all know what the changes are about, we will all forget after 2 months why we did this and the nuances that led to the decision to make this change.

**Comment by nirbheek** [comment]
Does Angelscript need the `soversion` and the `version` to be different? If not, why not just set the `version` to `1.2.3`?

**Comment by jpakkane** [comment]
It seems that they don't need to be different. But it needs to be of the form `1.2.3` and we currently only support single digit versions such as `1`.

**Comment by nirbheek** [comment]
If you set `version` to be `1.2.3` and don't set `soversion` at all, you will get this:

```
libtest.so -> libtest.so.1
libtest.so.1 -> libtest.so.1.2.3
libtest.so.1.2.3
```

Doesn't this work for Angelscript?

**Comment by jpakkane** [comment]
The `libtest.so.1` is the bit that's wrong. We should not generate it and in addition (I think) sets soname to `libtest.so.1` when it should be `libtest.so.1.2.3`.

**Comment by nirbheek** [comment]
One way to reconcile the two is as follows:

a) Recommend that people don't use `soversion` at all unless they are porting over from cmake

b) Make `version` behave the same as it does now

c) Make `soversion` behave the way it does with cmake

This will allow Autotools behaviour and CMake behaviour to co-exist.

**Comment by jpakkane** [comment]
Is this ok to merge now?

**Comment by nirbheek** [comment]
I'm fairly certain that this is ok now. Let's merge it and see if anything breaks. :)

**Pull request merged**
