### PR TITLE
machine file: Fix crash on empty value 

### PR DESCRIPTION
**Pull request by xclaesse**
Fixes: #12025

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Adding support for new features can't be backported as a bug fix...

**Comment by xclaesse** [comment]
It does fix the bug linked, currently it crash on empty value.

**Comment by tristan957** [comment]
Do you think we should raise a MesonException instead of allowing this?

**Comment by xclaesse** [comment]
> Do you think we should raise a MesonException instead of allowing this?

On 2nd thought, that's probably better indeed, I can't think about an actual use-case for empty value, an empty string should be `var=''`.

**Comment by tristan957** [comment]
Cool. At the very least, we can remove the exception in the future if there ends up being a usecase

**Comment by xclaesse** [comment]
Changed, and it can thus go to 1.2.1.

**Review by eli-schwartz — APPROVED** [review]

**Pull request merged**
