### PR TITLE
python.dependency() is not respecting 'required' kwarg

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Review by dcbaker — APPROVED** [review]

**Comment by xclaesse** [comment]
CI failure is unrelated.

**Comment by mensinda** [comment]
This PR seems to have broken `PythonTests.test_versions` on `vc2017x86ninja`.

**Comment by xclaesse** [comment]
Oops, you're right. That test assumes that requires is False by default which is inconsistent with dependency() function...  I think we should add `required: false`, is that fine with your?

**Comment by xclaesse** [comment]
Should be fixed by https://github.com/mesonbuild/meson/pull/7821

**Pull request merged**
