### PR TITLE
Fix import dependency from dub

### PR DESCRIPTION
**Pull request by Rogni**
#6586 
fix DubDependency._find_right_lib_path
if default_path is path to library and directory  of lib don't have subdirectory '.dub/build' -> return default_path

### CODE REVIEW

**Comment by jpakkane** [comment]
Would be possible to add a test for this?

You should also squash the commits here, the latter commit completely undoes the first one, there is no point in having it.

**Comment by Rogni** [comment]
in last commit also i'm added checking default_path. its try to fix feature dependency (method: dub) if subdependency have fullpath to lib in target/linkerFiles ( https://github.com/Rogni/meson/blob/debug_dub/mesonbuild/dependencies/base.py#L1645 ). it was discussed in #6586

**Comment by jpakkane** [comment]
The first commit has only this:

   +                         mlog.warning('Library not found: {}'.format(file))

and the second commit has this:

    -                        mlog.warning('Library not found: {}'.format(file))

Which is the exact opposite. You can see this in the entire changelist, since it only contains the other parts of the second commit.

**Comment by Rogni** [comment]
in the first commit, I added a warning for the log in travis build https://travis-ci.org/Rogni/meson_debug_dub/builds/646334749#L318 and on local device. after fix this warning is no longer needed

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
