### PR TITLE
Add a .copy() method to environment object and add a way to let the user know if a dependency is internal

### PR DESCRIPTION
**Pull request by thiblahute**

### CODE REVIEW

**Comment by nirbheek** [comment]
Related: #831 which discusses whether `configuration_data()` and the environment object should be copied on assignment to a new variable.

**Comment by jpakkane** [comment]
Instead of `is_internal` we probably want to have a more generic `type` method, which returns either `internal`, `pkgconfig`, `osxframework` or something like that. If we make it possible to do `dep.get_pkg_config_variable('foo')` then this is needed so users can know when to do that.

**Comment by thiblahute** [comment]
> Instead of is_internal we probably want to have a more generic type method, which returns either internal, pkgconfig, osxframework or something like that. If we make it possible to do dep.get_pkg_config_variable('foo') then this is needed so users can know when to do that.

Done, and added a new commit so that we try to first reuse subprojects before looking for native deps.

**Comment by tp-m** [comment]
Hrm, maybe I'm misreading what you merged here, but I strongly feel that adding an explicit copy method for the environment object is the wrong way to go, see the discussion in issue #831. This should be done automatically on assignment IMO.

**Comment by nirbheek** [comment]
I was also under the impression that we would copy on assignment or have further discussion since #831 still has a pending conversation w.r.t. this.

**Comment by jpakkane** [comment]
Let's take that to #831. We can still change that before the next release.

**Pull request merged**
