### PR TITLE
configure_file: Use utf-8 to write configured file

### PR DESCRIPTION
**Pull request by loshca**
as a second part of
https://github.com/mesonbuild/meson/issues/1085

### CODE REVIEW

**Comment by jpakkane** [comment]
Add yourself at then end of `authors.txt` and we'll merge this. Thanks.

**Comment by nirbheek** [comment]
Don't do a merge commit, please rebase on top of master if you want to update.

**Comment by loshca** [comment]
@nirbheek Is it ok? Should I do anything else?

**Comment by nirbheek** [comment]
Somehow there's 4 commits in this branch now including the merge commit, which hasn't gone away. :)

**Comment by loshca** [comment]
@nirbheek I am sorry. My first pull request in git) There are two small changes, I can create another pull request with another branch, if you want.

**Comment by nirbheek** [comment]
I force-pushed to your branch and fixed it for you. I made the following changes:

1) Git commit messages have a [specific format](http://chris.beams.io/posts/git-commit/): a subject and a body separated by an empty line. I edit the commit message for the main commit according to this.
2) I fixed the author used in the commit message itself for the commit that adds you to the authors list.
3) I removed a commit that adds your name to the authors list a second time
4) I reset the branch to origin/master and cherry-picked the two relevant patches to the branch, and force-pushed. This removes the merge commit.

It should be good to go now, does it look ok to you?

**Comment by loshca** [comment]
@nirbheek perfect!

**Pull request merged**
