### PR TITLE
Document the details of optimization+debug vs buildtype

### PR DESCRIPTION
**Pull request by nirbheek**
Otherwise you have to hunt through the source code. Specifically, this is defined in `mesonbuild/coredata.py`: `set_buildtype_from_others()` and `set_others_from_buildtype()`

### CODE REVIEW

**Comment by TheQwertiest** [comment]
Test failures are relevant: you have to somehow limit the scope of the section data in `test_builtin_options_documented`.
Current parsing code assumes that the section contains only a single table.
The relevant code is probably this:
```
# Extract the content for this subsection
sub_end = sub2.start() if sub2 is not None else len(content)
subcontent = content[sub1.end():sub_end]
# Find the list entries
arches = [m.group(1) for m in re.finditer(r"^\| (\w+) .* \|", subcontent, re.MULTILINE)]
```

**Comment by nirbheek** [comment]
I rewrote the tests. They were actually completely broken. Fixed now.

**Comment by TheQwertiest** [comment]
> They were actually completely broken.

Sorry for being a Python amateur  \<(．＿．)\>

**Comment by nirbheek** [comment]
> Sorry for being a Python amateur <(．＿．)>

No, your analysis was correct 😄. I was talking about the outer code which had some broken assumptions and had to be rewritten.

**Pull request merged**
