### PR TITLE
InternalDependency's are found if all of their dependencies are found

### PR DESCRIPTION
**Pull request by scott-d-phillips**
Make the found-ness of InternalDependencies true if either they
have no dependencies or all their dependencies are also found.

### CODE REVIEW

**Comment by nirbheek** [comment]
What is the reasoning behind this change? Does this fix some use-case for you? 

I wonder if we ever need to differentiate between a `DependencyHolder` and an `InternalDependencyHolder`. Probably not.

**Comment by scott-d-phillips** [comment]
I don't have some special case that fails without this, just seems logically consistent to assign some meaning to .found() for InternalDependency's.

**Comment by scott-d-phillips** [comment]
rebased

**Comment by jpakkane** [comment]
An alternative is to make internal dependencies always be `found` and then have a function such as `not_found_dependency()` that returns a dependency that has no state apart from being non-found.

The suggested approach might cause problems if you have a target that has an optional dependency but which can be built without it.

**Comment by nirbheek** [comment]
That's a good point.

**Comment by scott-d-phillips** [comment]
Agreed, this behavior would be quite surprising in the situation @jpakkane describes.

**Pull request closed without merging**
