### PR TITLE
pkgconfig: Add a simple version of the generator

### PR DESCRIPTION
**Pull request by xclaesse**
pkg.generate(mylib) should be enough to generate a minimal pc file.

### CODE REVIEW

**Comment by sarum9in** [comment]
Maybe separate method? Let's not put every functionality into a single one. You can always invoke it later as implementation detail. Thoughts?

**Comment by xclaesse** [comment]
IMO it's a nice extension of the current API, most of the time you generate a pc file for a single library object so it makes sense to pass it as positional argument. And you can still override default values, for example if your module version doesn't match project version: `pkg.generate(mylib, version: '1.0')`

**Comment by xclaesse** [comment]
Now that I think about it, I'm tempted to set the magical "generated_pc" flag only on Library objects passed as single positional argument. Because in that case the intention is clear that the user wants to generate the PC for that lib.

**Comment by xclaesse** [comment]
For the context, I'm generating pc file for all GStreamer plugins:
https://bugzilla.gnome.org/show_bug.cgi?id=794568

**Comment by jpakkane** [comment]
LGTM, please add a release note snippet and we can get this merged.

**Pull request merged**
