### PR TITLE
Make the expected output check mandatory for failing-meson and warning-meson tests

### PR DESCRIPTION
**Pull request by jon-turney**
A follow-up to #6620, this adds the expected output for tests added since that work was started, and makes it mandatory to have expected output for failing-meson and warning-meson tests, so it will (hopefully) get added for new tests when they are added.

### CODE REVIEW

**Comment by jon-turney** [comment]
Note: the current output for failing-meson tests 36, 67, 84 is a bit wonky, as noted in https://github.com/mesonbuild/meson/pull/6203#issuecomment-619432227

**Comment by dcbaker** [comment]
This looks really nice overall. I really like the work going into the test.json format.

**Comment by jpakkane** [comment]
This caused massive test failures for some reason even though it got green in CI, so I had to revert this out of master. Please reopen. I'll get the other master test issues fixed in the mean time (except msys, that requires an update to msys).

**Comment by jon-turney** [comment]
I think at least part of the problem is that this collides with #7123, which changes the text of a warning, which we were now validating.

**Comment by jon-turney** [comment]
No option to re-open this PR, so created a new one: #7197

**Pull request merged**
