### PR TITLE
java: support for linking jar files (using manifest)

### PR DESCRIPTION
**Pull request by noverby**

### CODE REVIEW

**Comment by jpakkane** [comment]
Looking good. The only piece that is missing is removing the classpath entries when installing. This means updating `depfixer.py` to work on Jar files. It should extract the manifest file, remove all classpath entries (optionally add the `install_rpath`) and then store the manifest back in the Jar.

**Comment by noverby** [comment]
How should the `install_rpath` be added to the manifest? Can you give an example?

**Comment by jpakkane** [comment]
By manually editing manifest file so the line describing the classpath is changed to what you need. See an existing jar file's manifest to see how the runtime classpath entries are stored.

**Comment by noverby** [comment]
Ok, now that the classpath entry in the manifest is removed will you accept this RP? Travis doesn't pass because homebrew fails fetching libraries. (Nothing to do with these commits.)

I have also changed the default install path of jar files to share/java, which is used by all major Linux distributions.

**Comment by jpakkane** [comment]
> Should I move that to a separate RP?

Please do, adding new build options is always a bit touchy of a subject.

**Comment by noverby** [comment]
Done: https://github.com/mesonbuild/meson/pull/3830

**Pull request merged**
