### PR TITLE
scripts: Make sure we load as little python modules as possible

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Review by eli-schwartz — COMMENTED** [review]
I think it's very odd and confusing to distinguish between mesonmain and mcli, and I actually have a better approach committed locally that I haven't had a chance to submit yet (it was on the back burner for a couple of weeks).

I do think it makes sense to reduce the impact of mesonlib, but I was wondering if the opposite approach, sort of, might make sense? Why does mesonlib contain all code? Maybe we should have mesonlib.core and mesonlib.universal would import * from core. Everywhere we currently `from . import mesonlib` we could do `from .mesonlib import universal as mesonlib` (this does look a bit funny, I admit). We would have a bit of freedom to organize code as "mesonlib" instead of just stuffing more things into additional top-level modules, and import some things via a much more targeted import.

Particularly, it feels pretty weird to have mesonlib expose the `from ..core import *` namespace.

(I don't necessarily oppose `mesonbuild.core` but I'm concerned that it may be the road to cluttering up the root of the source code.)

**Comment by eli-schwartz** [comment]
I also have an old PR that, for most of the common cases, completely avoids using `meson --internal exe` at all on Unix and msys2.

**Comment by xclaesse** [comment]
I totally agree that the split of core.py is ugly, I don't like it at all either. The issue I had to work around is `mesonlib/__init__.py` imports everything, so as soon as you import mesonlib you get a tone of code. I think your proposal is basically moving my core.py into mesonlib, and stop importing everything in `__init__.py`, that would make sense, yes.

> I think it's very odd and confusing to distinguish between mesonmain and mcli, and I actually have a better approach committed locally that I haven't had a chance to submit yet

I think that part is not too bad, mcli.py is basically all in a single class CommandLineParser (I should refactor a little bit more to actually put all code in the class tbh). If you have a better proposal for that please explain a bit the idea, I'm interested.

**Comment by xclaesse** [comment]
> I also have an old PR that, for most of the common cases, completely avoids using `meson --internal exe` at all on Unix and msys2.

The PR that uses `env`? I thought that was merged already. We still need to fastpath scripts because `env` cannot be used on Windows, and it's precisely on that platform that everything is super slow when wrapping commands.

**Comment by eli-schwartz** [comment]
> I think your proposal is basically moving my core.py into mesonlib, and stop importing everything in `__init__.py`, that would make sense, yes.

Yes, basically. I think the main reason to import everything in `__init__.py` is literally because `mesonlib.Foo` is more convenient to type, so `from .mesonlib import universal as mesonlib` is a nice solution to that.

**Comment by xclaesse** [comment]
> I think the main reason to import everything in `__init__.py` is literally because `mesonlib.Foo` is more convenient to type

I think it's even more stupid than that, mesonlib used to be a single py file that we split at some point. I think it has been done like that to avoid having to change the import everywhere.

**Comment by dcbaker** [comment]
Why can't this just move to mesonlib, which is basically free to import? I ran some tests to see how long it takes:
```python
>>> import timeit
>>> import importlib
>>> timeit.timeit(lambda: mesonlib.import_module('mesonbuild.mesonlib'), number=10000)
0.1453766640042886
>>> timeit.timeit(lambda: importlib.import_module('test'), number=10000)
0.11735846901137847
```
test.py contains only the `pass` statement, and nothing else. So I'm going to need to see more proof that `mesonlib` is a problem. I'm also not thrilled with creating yet another module and further spreading stuff like `HoldableObject` (which I really don't like, it's an Interpreter layering violation).

**Comment by dcbaker** [comment]
> Yes, basically. I think the main reason to import everything in __init__.py is literally because mesonlib.Foo is more convenient to type, so from .mesonlib import universal as mesonlib is a nice solution to that.

no, it's like that because universal implements all of the code that works everywhere, and then the other modules implement platform specific functions, where windows needs this, and *nix needs that

**Comment by xclaesse** [comment]
> I'm also not thrilled with creating yet another module and further spreading stuff like `HoldableObject` (which I really don't like, it's an Interpreter layering violation).

Yes, that's the ugliest part and completely useless too, I'm sure there must be a better way. The variable handling is not an interpreter thing at all, I wanted to make an EnvironmentVariablesBase class that don't inherit anything, and EnvironmentVariables that inherit both EnvironmentVariables and HoldableObject, but pickling that pulls the whole thing. I'm sure there must be a way to pickle only the base class or something like that?

**Comment by xclaesse** [comment]
> Why can't this just move to mesonlib, which is basically free to import?

That's a fair point, maybe I'm trying to go too far.

**Comment by eli-schwartz** [comment]
> The point is to encapsulate implementation details in the `mesonlib` package, so that consumers don't need to be aware that there are windows and *nix specific implementations of some of the functions.

I'm aware of that detail, but it's plainly wrong, because mesonlib.vsenv exists, for whatever reason.

**Comment by xclaesse** [comment]
> I'm aware of that detail, but it's plainly wrong, because mesonlib.vsenv exists, for whatever reason.

I did not think too much when I put it there, could have been a mistake. But I'm not sure what better places.

**Comment by eli-schwartz** [comment]
> Why can't this just move to mesonlib, which is basically free to import? I ran some tests to see how long it takes:

I ran the same tests, and the first time running `timeit` was dramatically faster than the second time. But only for mesonlib, not for `test`. Does timeit even allow testing import times?

**Comment by xclaesse** [comment]
> I ran the same tests, and the first time running `timeit` was dramatically faster than the second time.

Running it multiple times gives huge differences here too. In any case, I think it's better to avoid modules if we can, mesonlib can easily grow over time too. Since there is pretty much nothing requiring mesonlib in the script code path, why not avoid it. But it's not the end of the world if we can't find a solution that avoids mesonlib, I can live with that.

**Comment by dcbaker** [comment]
As I think about it, what I would see as a compromise: a `mesonlib.core` (or base, or scripts, or something) that contains bits scripts need, and *scripts* import directly, but is also imported into the the main `mesonlib` package, and that not script users keep just importing plain `mesonlib` for clarity, and because in the main meson case the cache makes additional imports of mesonlib basically free.

**Comment by xclaesse** [comment]
@dcbaker unfortunately `import mesonlib.core` still imports everything from mesonlib.

**Comment by eli-schwartz** [comment]
> As I think about it, what I would see as a compromise: a `mesonlib.core` (or base, or scripts, or something) that contains bits *scripts* need, and scripts import directly, but is also imported into the the main `mesonlib` package, and that not script users keep just importing `plain mesonlib` for clarity, 

A basic contract of python is that `import foo.bar` first imports `foo.__init__`.

This is why earlier I suggested maybe what's wanted is `from .mesonlib import XXX as mesonlib` to get an all-in-one version.

**Comment by xclaesse** [comment]
> This is why earlier I suggested maybe what's wanted is `from .mesonlib import XXX as mesonlib` to get an all-in-one version.

I think what we can do to avoid changing all imports is to rename the directory `mesonlib` to `utils` and have `mesonlib.py` that `import utils/*`.

**Comment by xclaesse** [comment]
> I think what we can do to avoid changing all imports is to rename the directory `mesonlib` to `utils` and have `mesonlib.py` that `import utils/*`.

Implemented that idea. I think this PR is not too bad with that change tbh.

**Comment by xclaesse** [comment]
@eli-schwartz @dcbaker would like to take a decision if this is something we want to do, before this PR gets conflicts. What do you think?

**Comment by eli-schwartz** [comment]
As stated above, I like the idea of the mesonlib split here although I don't think splitting up mesonmain is necessary at all. And in the current state of git master I don't think that particularly saves anything?

Moving stuff like traceback/mlog to only where they are needed is... I guess not terrible? But I wonder how much that actually saves...

What is the current timings for script cold startup time in git master vs. this PR vs. the stable release?

**Comment by xclaesse** [comment]
I ran a little experiment:
```
project('test', 'c')

python = import('python').find_installation()

foreach i : range(200)
    custom_target(output: f'foo@i@',
        command: [python, '-c', 'print("foo")'],
        capture: true,
        build_by_default: true)
endforeach
```

Running ninja on Windows (because everything is worse with that OS) 
- Master: 13s.
- This PR 7s.
- This PR but with CommandLineParser moved back into mesonmain: 9s.
- This PR but with CommandLineParser moved back into mesonmain and lazy import mesonlib in CommandLineParser.run(): 7s.
- Importing mlog has no significant difference.

I think importing the whole mesonlib is significant, and it can only get worse over time when we add more code there. It's true that it can be lazy loaded and in that case we can keep CommandLineParser in mesonmain, but I actually like mcli because it contains only a self contained class and makes mesonmain small which makes clear that the entry point contains the strict minimum. But that's not a hill I'm ready to die on if you strongly feels it's better to keep it in mesonmain.

**Comment by eli-schwartz** [comment]
Thanks for the timing tests!

Yes, I think it's better to keep it in mesonmain. Can we get the mesonlib split up and running on its own?

**Comment by eli-schwartz** [comment]
:crossed_swords: conflicts (due to competing edits to mesonlib which is getting moved).

**Comment by xclaesse** [comment]
> crossed_swords conflicts (due to competing edits to mesonlib which is getting moved).

Weird, it rebased without any conflict locally.

**Comment by eli-schwartz** [comment]
GitHub isn't actually any good at rebasing. Perhaps if we used gitlab. On the other hand then we'd have nuts docker containers or something.

It only knows how to do straight merges

**Review by eli-schwartz — APPROVED** [review]

**Pull request merged**
