### PR TITLE
Qt module generated sources

### PR DESCRIPTION
**Pull request by dcbaker**
This has two things in it, a fix for #9007, in which CustomTargets were erroneously excluded as inputs to the various `qt.preprocess` arguments, and then a series of patches to make the various `compile_*` arguments accept all forms of generated inputs, not just `CustomTargets` (including CustomTargetIndex and GeneratedList inputs`.

@nirbheek: the first patch to this series should be pulled for 0.59.1, but the rest should not.

@ximion: can you see if the first patch fixes your issue?

### CODE REVIEW

**Comment by nirbheek** [comment]
@dcbaker do you think you could put the first commit into a separate PR? It looks trivially correct, so we can merge it immediately, and that's also clearer for documenting what went into a stable release.

**Comment by dcbaker** [comment]
Sure, i can split it out.

**Comment by jpakkane** [comment]
:crossed_swords: conflicts now.

**Comment by dcbaker** [comment]
github is so strange, that rebased without conflicts

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by dcbaker** [comment]
@jpakkane, rebased

**Pull request merged**
