### PR TITLE
Add a note on relocatable pkg-config files to reference manual.

### PR DESCRIPTION
**Pull request by rgommers**
The builtin option works as advertised; having it mentioned in the reference docs for the `pkgconfig` module seems like a good idea (and would have saved me quite a bit of time reading through GitHub issues).

### CODE REVIEW

**Comment by eli-schwartz** [comment]
For consistency... do we mention our other module options in the module reference? If not, maybe we should add those too.

I haven't checked.

**Comment by xclaesse** [comment]
I don't think we do, but we should. Tbh, I think we should move the table from built-in doc to the module. It is more discoverable there.

**Comment by rgommers** [comment]
> For consistency... do we mention our other module options in the module reference? If not, maybe we should add those too.

I cross-checked only with the Python module, which does link to the builtin option in the same way. And it's the only other module with an option listed in https://mesonbuild.com/Builtin-options.html#module-options

> Tbh, I think we should move the table from built-in doc to the module. It is more discoverable there.

That seems reasonable to me. I can update this PR to do that, or open a new one, if that's the consensus here.

**Comment by eli-schwartz** [comment]
I find it significantly more discoverable in the consolidated "all options" page, but find it reasonable to cross-link them from the module page.

**Pull request merged**
