### PR TITLE
Revert "gnome.compile_resources: Add ld binary method"

### PR DESCRIPTION
**Pull request by jpakkane**
This reverts commit 59791fc56966901038aaaac23942bc8ac6e11494, reversing
changes made to e26b5a119e0b3f76cc93f65ecf4251dc6d52ecfe.

### CODE REVIEW

**Comment by jpakkane** [comment]
Closes #5049.

**Comment by ignatenkobrain** [comment]
I'd leave it for 0.51 as is (and noting it in breaking changes) and just revert it for 0.50...

What do you think @jpakkane ?

**Comment by nirbheek** [comment]
I think we need to enable this via an opt-in kwarg in 0.51.

**Comment by Ninja-Koala** [comment]
So how could i bring this back for 0.52?

**Pull request merged**
