### PR TITLE
ninja: Use platform dependent quote instead of shlex.quote() in gcc_rsp_quote()

### PR DESCRIPTION
**Pull request by byteblob42**
See also #12643

### CODE REVIEW

**Comment by dcbaker** [comment]
That listing error looks relevant

**Comment by byteblob42** [comment]
> That listing error looks relevant

Ok, so just purge the import yeah? Should i just make a new commit or what would you like?

**Comment by byteblob42** [comment]
I'll be gone until the middle of the first january week, feel free to close this if you wish, I'll make a new PR when I'm back in that case.

**Comment by byteblob42** [comment]
I have ammended the commit.

**Review by dcbaker — APPROVED** [review]
LGTM

**Comment by eli-schwartz** [comment]
Why is the location of the function moved around in the file?

**Comment by dcbaker** [comment]
quote_func is defined until after where the gcc_rsp function was originally defined

**Comment by eli-schwartz** [comment]
The order doesn't strictly matter since `quote_func()` is only used after the function is defined. That being said I don't strongly care one way or another.

**Comment by jon-turney** [comment]
I am very sceptical that this change is correct.

The unstatated assumption behind #12643 is that it's possible to write a `ninja.build` which simultaneously satisfies both:
1. response file contents are correctly quoted for the tools which use them
2. response file contents are quoted in the "platform native" style, which consumers of the ninja compdb are expecting

Even on pure Unix, this isn't 100% right, because things like `'\\'` have a different meaning under gcc response file and shell quoting rules. but I guess since this solves the OPs problem, it all happens to work in most cases.

It might be that meson just doesn't (currently) generate response files with problematic contents, but I suspect this is probably going to break down where these quoting styles are just incompatible (so perhaps something involving quoting a `"` character).

(As a thought experiment, maybe consider what happens if I've written some bonkers tool which defines it's response file quoting style involves using some bizaare non-standard quoting mechanism. I can write a `ninja.build` using that without problems, but naive expectations about the contents of the compdb are going to be broken...)

**Pull request merged**
