### PR TITLE
Add meson.override_dependency()

### PR DESCRIPTION
**Pull request by xclaesse**
Similar to meson.override_find_program() but overrides the result of the
dependency() function.

### CODE REVIEW

**Comment by xclaesse** [comment]
Another use-case for this, when some subprojects are only checking for libxml2 with `dependency('libxml2')` and don't lookup for the lib+header, I can in the parent project do the proper fallbacks and then override the libxml2 dependency. That way I can force them to use the library even if there is no pkg-config file on my platform.

**Comment by xclaesse** [comment]
I'm wondering if we should automatically register the override when doing the fallback case in `dependency('glib-2.0', fallback : ['glib', 'libglib_dep'])` if the subproject did not call meson.override_dependency().

**Comment by jpakkane** [comment]
I just realized that overriding a dependency is different from overriding an executable. The latter are never stored and persisted over Meson invocations, but dependencies are. We have to be careful with this so we don't cause deadlocks or something similar.

**Comment by xclaesse** [comment]
@jpakkane Right, the dependency cache persists over invocation, but not overrides. I think I made sure about that in this PR.

**Comment by xclaesse** [comment]
After some more investigations, this PR is not ready to be merged, for example it should at least take into account native/cross cases. I'll done an update later.

**Comment by jpakkane** [comment]
Closing to reduce clutter on the MR list. Please reopen when done.

**Pull request closed without merging**
