### PR TITLE
gnome: add support for update-mime-database

### PR DESCRIPTION
**Pull request by pbor**
Fixes https://github.com/mesonbuild/meson/issues/10865

### CODE REVIEW

**Comment by xclaesse** [comment]
Technically `update-mime-database` is a freedesktop thing and not gnome, but so is `desktop-file-utils` we already have. I don't think it's worth splitting this functionality.

LTGM, but please add a release snippet.

**Comment by eli-schwartz** [comment]
Considering skip_if_destdir exists and it's pretty easy to do this in a single line with add_install_script I wonder how much sense it makes to keep adding non-gnome things to the gnome module.

Granted this is fairly common... idk.

**Comment by xclaesse** [comment]
@eli-schwartz one reason I like to wrap those common tools is because if at some point we need to change how we search it, we can do it in Meson instead of patching thousands projects. That's the case for example if the tool path gets added in a pkgconfig file, or gets renamed like they did for gtk4, etc. Granted it's pretty unlikely in this case, but who knows...

**Comment by xclaesse** [comment]
Ah, also this PR means we update the db only once, instead of once per subproject.

**Comment by xclaesse** [comment]
macos CI failed but that seems unrelated. LGTM.

**Pull request merged**
