### PR TITLE
pkgconfig: Add support for Requires.internal

### PR DESCRIPTION
**Pull request by xclaesse**
We probably should wait for [Requires.internal patch](https://bugs.freedesktop.org/show_bug.cgi?id=105572) to be merged and release before merging this PR.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
JFYI, Fedora doesn't use freedesktop's pkg-config, but uses pkgconf... So would be nice to coordinate this work too.

**Comment by xclaesse** [comment]
Already done: https://github.com/pkgconf/pkgconf/commit/f03ec3ff90ee619a21826d23609adb5409dbe9a2

**Comment by Conan-Kudo** [comment]
@xclaesse As of right now, that's not available in a released pkgconf, so you can't count on it.

**Comment by xclaesse** [comment]
Let's close this for now actually. I'll reopen when pkg-config actually merge the proposed patches.

**Pull request closed without merging**
