### PR TITLE
Add handling Qt6's EntryPoint library.

### LINKED ISSUE #10792: Qt6 on Windows -> QtEntryPoint
**Describe the bug**

A very simple Qt 6 executable in the windows subsystem requires a WinMain function. Previously, this was provided by the static qtmain.lib, but, it seems, in Qt 6 it is provided by the new QtEntryPoint library. This is not heeded by the "main" keyword of the qt dependency().

**To Reproduce**
Trivial main.cpp
```
#include <QApplication>
#include <QPushButton>

auto main(int argc, char * argv[]) -> int
{
    auto Application = QApplication{argc, argv};
    auto Button = QPushButton{"Exit"};
    QObject::connect(&Button, &QAbstractButton::clicked, []() { QApplication::quit(); });
    Button.show();
    return Application.exec();
}
```

Trivial meson.build:
```
project('bug', 'cpp', default_options: ['cpp_std=c++17'])
qt_dep = dependency('qt6', modules: ['Core', 'Widgets'], main: true)
app = executable('app', 'main.cpp', dependencies: [qt_dep], win_subsystem: 'windows')
```

**Expected behavior**

This should compile successfully.

There are two options to solve this:
1. rely on the programmer to supply the 'EntryPoint' module in the dependency, and remove the 'main' argument for qt6
   I.e. this works: `qt_dep = dependency('qt6', modules: ['Core', 'EntryPoint', 'Widgets'])`
2. leave the interface as is and improve the Qt6 dependency handling to map from `'main': true` to the 'EntryPoint' module

It should be noted, that QtEntryPoint is not available on at least Ubuntu 22.04. So, the second options seems to be more portable, as it doesn't need OS-specific handling in the meson.build file.

**system parameters**
* no cross-compile
* OS: Windows, MSVC and Qt 6.3.2, run inside MSYS2
* meson --version: 0.63.2
* ninja --version: 1.11.1

### PR DESCRIPTION
**Pull request by punytroll**
- this fixes #10792
- Qt6EntryPoint(d) replaces qtmain(d) from Qt 4 & 5
- uses the same mechanism: `main: true`
- uses a special mixin class for pkg-config and config-tool dependency calculation

### CODE REVIEW

**Comment by punytroll** [comment]
I also renamed things with "qtmain" to "qtwinmain" to highlight the fact that functionality only pertains to WinMain.

**Comment by punytroll** [comment]
> This pull request **introduces 2 alerts** when merging [2109007](https://github.com/mesonbuild/meson/commit/210900720df045eca96014c19543372b5197ca67) into [2a76afc](https://github.com/mesonbuild/meson/commit/2a76afcef1fbd5cac0435cc9a11f765120a48fe9) - [view on LGTM.com](https://lgtm.com/projects/g/mesonbuild/meson/rev/pr-6022d29ae288b7e9dde13e3c72271337468c0942)
> 
> **new alerts:**
> 
>     * 2 for Conflicting attributes in base classes

Hm. I'd say, this is exactly as intended! But if the reviewer thinks this might actually be a code smell, I'll revise it.

**Comment by eli-schwartz** [comment]
> Hm. I'd say, this is exactly as intended! But if the reviewer thinks this might actually be a code smell, I'll revise it.

My opinion as a core reviewer is that this LGTM.com warning can be rephrased as "mixins can be confusing because it is possible to implement them incorrectly".

Which, no kidding, lots of things can be implemented incorrectly...

**Comment by eli-schwartz** [comment]
The mypy test failure is definitely just a matter of rebasing onto origin/master in order to grab a totally unrelated fix. It might not be the only trivial rebase fix, hmm...

**Comment by eli-schwartz** [comment]
The other ways to do this would be if/else in a single function checking `self.qtver`, but IIRC you said that didn't feel appealing to you.

**Comment by punytroll** [comment]
> The other ways to do this would be if/else in a single function checking `self.qtver`, but IIRC you said that didn't feel appealing to you.

Yah, that might be the best way of phrasing it. It is version-dependent behavior and I would like to see it introduced in the version-specific classes, as opposed to an if in the general _QtBase class. On the other hand, the PkgConfig- and ConfigTool-specific behavior makes multiple inheritance necessary. If not with a big refactoring, this is the simplest solution I came up with, that satisfies that (arbitrary) requirement.

How to proceed?

**Comment by punytroll** [comment]
Done ... I think. Too late for *.3, though. :/

**Pull request merged**
