### PR TITLE
meson: skip captured write if content didn't change

### PR DESCRIPTION
**Pull request by elmarco**
This should help saves some unnecessary recompilation

### CODE REVIEW

**Comment by nirbheek** [comment]
Thanks!

**Comment by bonzini** [comment]
This has the side effect of rebuilding the custom target on every subsequent recompilation. Since this only applies to `capture` targets, we could save the timestamp of the last update anyway, like

    build output: PHONY output.stamp
        restat = 1
    build output.stamp: CUSTOM_COMMAND input
        COMMAND = python3 meson --internal exe foo.dat

**Comment by elmarco** [comment]
> This has the side effect of rebuilding the custom target on every subsequent recompilation. Since this only applies to `capture` targets, we could save the timestamp of the last update anyway, like

```
project('custom target', 'c')

mytarget = custom_target('first',
  output : 'first',
  input : 'input.txt',
  capture : true,
  command : ['cat', '@INPUT@'],
)
```

```
$ ninja -v first
[1/1] meson --internal .....
$ ninja -v first
ninja: no work to do.
$ touch ../input.txt
$ ninja -v first
[1/1] meson --internal .....
$ ninja -v first
ninja: no work to do.
```

It seems to do the right thing, not sure how/why...

> ```
> build output: phony output.stamp
>     restat = 1
> build output.stamp: CUSTOM_COMMAND input
>     COMMAND = python3 meson --internal exe foo.dat
> ```

So meson exe would touch foo.dat.stamp ?

**Comment by bonzini** [comment]
Nevermind; I didn't know that `restat = 1` state is carried across ninja invocations.

**Pull request merged**
