### PR TITLE
Don't try to use build machine dependency finders for host

### PR DESCRIPTION
**Pull request by dcbaker**
Even if the build machine == host machine, we can't use dependencies from the build machine for the host machine. This can happen when using a system to build a new machine image. for example when compiling chromeos. It's completely possible to build an x86_64-linux host for an x86_64-linux build machine, but not have all of the same runtime dependencies. In particular, if meson tries to use cmake from the build machine for host dependencies it will result in trouble.

Fixes: #7276

### CODE REVIEW

**Comment by dcbaker** [comment]
This is conceptually similar to #7099

**Comment by mensinda** [comment]
I am not 100% sure if this is the right approach for CMake since this would only change a few default search paths at best.

Using CMake from the build machine should always be OK (and probably the best solution) once we support propper CMake cross-compilation with [toolchain files](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html).

**Comment by dcbaker** [comment]
Changing the default search paths is 100% the problem. /usr/bin/cmake will find cmake files in /usr, which are completely wrong almost all of the time. It's also super inconsistent with the way we find other binaries, which if not specified in the cross file are automatically treated as "not found"

**Comment by mensinda** [comment]
In that case, we can also set [CMAKE_FIND_ROOT_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH.html), [CMAKE_SYSROOT](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSROOT.html), etc. I would argue that CMake *is* a special binary since it has it's own cross-compilation logic.

Wouldn't this also mean that we would need to invoke CMake with an exec wrapper (so `wine /path/to/cmake.exe` for mingw-w64)?

I am fine with changing the default variables by using the host CMake binary, but I would like to keep the option open for using the build CMake binary with a toolchain file in the future.

**Comment by dcbaker** [comment]
What this does is gives binaries a way to opt out of the default for cross builds through a boolean, so in the future you could change that boolean to something like `allow_default=bool(has_toolchain_file)`, which seems like a reasonable thing to do.

**Pull request merged**
