### PR TITLE
Prefer user-set *FLAGS from the env over external deps

### PR DESCRIPTION
**Pull request by nirbheek**
Includes a test.

Closes https://github.com/mesonbuild/meson/issues/1718

### CODE REVIEW

**Comment by jpakkane** [comment]
Based on the description alone, isn't this exactly backwards? If you have `-L/usr/local/lib` in LDFLAGS and `-L/home/user/devroot/lib` in an external dep (pkg-config) then what you want to use is the latter. If LDFLAGS overrides and a library with the same name is in both dirs, then the one in `/usr/local/lib` is _always_ used which seems to not be correct (and also what bug #1718 reports to be happening).

The _behaviour_ might still be correct but the nomenclature here is just confusing and I'd prefer to get that straightened out first so everyone agrees on what we are trying to do.

**Comment by jpakkane** [comment]
I created a test case in the l_order branch (no MR) that ensures that if you have [dep1, dep2] then all -L flags from dep 1 should come before dep2. Don't have a good grasp yet on how to solve this.

**Comment by lantw44** [comment]
Yes, your patch fixes my problem in jhbuild environment. However, the test added doesn't look like an expected use case. I have uploaded another example in [this comment](https://github.com/mesonbuild/meson/issues/1718#issuecomment-307634167).

**Comment by nirbheek** [comment]
The test case tests exactly what you want. It builds libz.so in a "separate prefix" and uses that instead of libz.so found via pkg-config.

**Comment by lantw44** [comment]
> The test case tests exactly what you want. It builds libz.so in a "separate prefix" and uses that instead of libz.so found via pkg-config.

Yes, I know the test case is similar to the description of the issue, and it can be used to test the change. It is just not obvious to know why it exists by reading the code of the test case.

**Comment by nirbheek** [comment]
> Yes, I know the test case is similar to the description of the issue, and it can be used to test the change.

Perhaps, but that's the nature of tests. They are restricted by the capabilities of the test suite.

> It is just not obvious to know why it exists by reading the code of the test case.

That's why comments exist ;)

**Comment by nirbheek** [comment]
Superseded by https://github.com/mesonbuild/meson/pull/1932

**Pull request closed without merging**
