### PR TITLE
configure_file: Fix infinite loop in some cases

### LINKED ISSUE #1865: Chaining configure_file() can cause ninja to go in an infinite loop
```meson
cfg1 = configure_file(
    ...
)
cfg2 = configure_file(
    input: cfg1,
    ...
)
```

Currently this is not possible, because cfg1 is saved in builddir and absolute path of the cfg1 File object  is trashed -
 https://github.com/mesonbuild/meson/blob/7882549f860730dda43fcc825b5beb75b0209410/mesonbuild/interpreter.py#L2338,  thus cfg2 is looking for cfg1 in the sourcedir.

### PR DESCRIPTION
**Pull request by nirbheek**
We were adding built files to the list of source files to check for regen. We were also not adding source files to regen when `command:` was used.

Fixes #1865

### CODE REVIEW

**Comment by nirbheek** [comment]
CI failure was all spurious, re-pushing.

**Comment by nirbheek** [comment]
Test failure is strange. That test doesn't use `configure_file()` at all. @jon-turney do you know what could be causing it?

**Comment by jon-turney** [comment]
@nirbheek  No idea, I can't reproduce that test failure locally or on appveyor.

**Comment by nirbheek** [comment]
Re-pushed. Let's see if it was just appveyor being weird.

**Comment by nirbheek** [comment]
Wow, appveyor lies about the time jobs take to run. It took several hours to provision VMs and doesn't count that time, so even though I started the job 4 hours ago, it's still running and saying that only 25 min were spent.

**Comment by nirbheek** [comment]
Everything passed. This can be merged now.

**Pull request merged**
