### PR TITLE
Update Users.md

### PR DESCRIPTION
**Pull request by amitdo**
Remove "(not the default yet)" from GLib, GStreamer, Orc and Pango

### CODE REVIEW

**Comment by amitdo** [comment]
Meson is also the solo build system for GStreamer, but currently only in its master branch.

**Comment by tp-m** [comment]
> Meson is also the default build system for GStreamer, but currently only in its master branch.

It's also the recommended build system for the stable branch (1.16), even if it still ships with an autotools build in 1.16 too, so I think it's ok to update it for GStreamer as well.

**Comment by amitdo** [comment]
You're right.

https://gstreamer.freedesktop.org/releases/1.16/

>The Meson build is now feature-complete (\*) and it is now the recommended build system on all platforms. The Autotools build is scheduled to be removed in the next cycle.

I'll update the PR soon.

**Comment by amitdo** [comment]
Done.

**Pull request merged**
