### PR TITLE
Ninja now supports backslash in command args, so we can too

### PR DESCRIPTION
**Pull request by nirbheek**
At the same time, this also adds a bunch of tests that document and keep track of how we expect quoting to pass through via Ninja to the compiler.

Ninja support was added in https://github.com/ninja-build/ninja/pull/702

This fixes https://github.com/mesonbuild/meson/issues/489

### CODE REVIEW

**Comment by nirbheek** [comment]
Hah, this fails because we're using too-old Ninja. We need at least 1.6 which was released last year.

**Comment by nirbheek** [comment]
... and the failing test passes because the failure is supposed to happen when the test executable is run. I'll remove it from the patchset. The same type of test is done in the ordinary tests too. I just added it to preserve the failing test numbering and for some redundancy.

**Comment by nirbheek** [comment]
Hmm, Ninja version checking depends on the version-checking patch in https://github.com/mesonbuild/meson/pull/640, so I'll only update this PR once that's resolved.

**Comment by nirbheek** [comment]
I've tested all this on Linux with GCC and Clang (both with Ninja) and on Windows with MinGW/GCC/Ninja, MSVC/Ninja, MSVC/MSBuild, and MSVC/VisualStudio2015. I haven't tested on OS X, but I think it's safe to assume that it works there too.

**Comment by jpakkane** [comment]
Our CI system runs on OSX so it works on that too. Will merge soon.

**Comment by nirbheek** [comment]
I was also worried about quoting inside xcode project files, but I suppose the xcode backend probably has worse problems to worry about right now. :)

**Pull request merged**
