### PR TITLE
python3: Fix 'sysconfig_path' for platform-dependant paths

### PR DESCRIPTION
**Pull request by arteymix**
Include 'platbase' for stripping the prefix for 'platlib' and 'platinclude'.

This is necessary for installing platform-dependant Python modules such as GI overrides.

### CODE REVIEW

**Comment by jpakkane** [comment]
This really needs a test.

**Comment by arteymix** [comment]
I'll extend the current basic test to ensure that correct relative paths are emitted for all the documented paths.

It's sort of tricky to test because these could be defined at configure-time when Python is compiled from sources.

**Comment by arteymix** [comment]
@jpakkane It is be mergeable now and I extended the substitution for all the supported paths.

**Comment by jpakkane** [comment]
I have to admit that I don't understand this part of Python pathtitude to really approve. Anyone else want to comment?

**Comment by arteymix** [comment]
Well at least for the three coverted in this testcase:

 - `include` is necessary for retrieving your Python headers when writing extensions
 - `platlib` is a destination for architecture-dependant shared libraries that accompany Python modules
 - `purelib` is a pure Python destination and thus architecture-independant

You could argue that `include` is useless since we can simply do `pkg-config --cflags python3` and thus `dependency('python3')` to retrieve it, but the two lasts are necessary for installing Python modules properly.

Also, we expose the API, so let's do it correctly at least.

**Comment by ignatenkobrain** [comment]
dependant -> dependent ;)

**Comment by arteymix** [comment]
@ignatenkobrain I'm messing with french I think, a/e is a tough choice for me.

**Pull request merged**
