### PR TITLE
interpreter: Support hex, binary, and octal in str.to_int()

### PR DESCRIPTION
**Pull request by nirbheek**
Closes https://github.com/mesonbuild/meson/issues/2047

### CODE REVIEW

**Comment by jpakkane** [comment]
Since there still has not been an actual use case for this I'm inclined to close it. All features need to be actually needed rather than be "nice-to-haves".

**Comment by tp-m** [comment]
The use case is in #2047 - making sense of the (string) result from cc.get_defined() or such. I remember needing/wanting it once as well, but not the exact context, sorry.

**Comment by nirbheek** [comment]
When making this PR I was actually surprised that we didn't already automatically detect the base of the integer representation and convert to a base-10 integer. It's such a basic and useful feature, and headers often contain defines in hex, octal, or binary. For instance, some libraries (such as some boost modules) export their version number via a define pointing to a hex integer.

The implementation is also really simple, so I don't see why this shouldn't go in. :)

**Comment by keszybz** [comment]
Yeah, it's the kind of thing that one expects to work by default: 0x..., 0o.... I expect people _try_ to use such syntax, then realize it's not supported, and fall back to decimal numbers, without reporting this. I think this should go in.

**Comment by keszybz** [comment]
OK, we have an actual use case now: https://github.com/systemd/systemd/pull/7530#discussion_r154522485. Instead of using the natural format we use decimal and put hexadecimal in a comment.

**Comment by jpakkane** [comment]
Why is the value being stored as a string here? Would a better solution instead be something like this:

    option('dynamic-uid-min', type : 'int',
           description : 'minimum dynamic UID',
           value : 0x0000EF00)

**Comment by keszybz** [comment]
Yeah, that'd be even nicer, but I though that `option` only supports string, bool, and combo types.

**Comment by jpakkane** [comment]
Well I'll be damned. We've had the code to do this for ages but apparently it has never been exposed (but I have thought it has for ages). Will be in the next release.

**Comment by keszybz** [comment]
If it is exposed, you probably want to merge this PR too: after all it'd be weird to support some notation in literals but not programatically.

**Comment by jpakkane** [comment]
Hex number literals and integer options are in trunk and will be in the next release. Closing this to remove clutter. If there is still requirement for something like this, please open a new PR with updated info. Thanks.

**Pull request closed without merging**
