### PR TITLE
msubprojects: do not follow symlinks when purging

### LINKED ISSUE #8891: `subprojects purge` should not follow symbolic links
**Describe the bug**
`meson subprojects purge` currently follows symbolic links. That is, if `subprojects/foo` is a symbolic link to `/home/reimu/git/foo`, then `meson subprojects purge` will offer to delete the actual `/home/reimu/git/foo` directory instead of the symbolic link. This is dangerous and makes no sense; I sometimes use symbolic links like that to replace a wrap dependency with my own version locally, and I wouldn't like it to get wiped.

**To Reproduce**
Setup:
```bash
cd /tmp
mkdir foreignproj
mkdir myproj
cd myproj
meson init
mkdir subprojects
ln -s ../../foreignproj subprojects/foo
cat <<EOF > subprojects/foo.wrap
[wrap-git]
directory=foo
url=https://example.com/foo.git
EOF
```
Purge:
```
$ pwd
/tmp/myproj
$ file /tmp/foreignproj
/tmp/foreignproj: directory
$ file subprojects/foo
subprojects/foo: symbolic link to ../../foreignproj
$ meson subprojects purge --confirm
Deleting /tmp/foreignproj
$ file /tmp/foreignproj
/tmp/foreignproj: cannot open `/tmp/foreignproj' (No such file or directory)
$ file subprojects/foo
subprojects/foo: broken symbolic link to ../../foreignproj
```

**Expected behavior**
`meson subprojects purge` should remove the symbolic link and not touch the real directory.

**system parameters**
* what operating system: openSUSE Tumbleweed
* what Python version are you using: 3.8.10
* what `meson --version`: 0.58.999 (6fb2f8637)
* what `ninja --version`: 1.10.2

### PR DESCRIPTION
**Pull request by Akaricchi**
Fixes #8891

### CODE REVIEW

**Comment by Akaricchi** [comment]
I've added a hack to still print out the full/resolved paths up to the subproject dir, just because that's what the tests expect. I'm not sure if there's any practical reason to not just operate on relative paths.

**Comment by Akaricchi** [comment]
Azure failures look unrelated.

**Comment by jpakkane** [comment]
CI settings have been changed, hopefully a rebase will fix it.

**Comment by Akaricchi** [comment]
@jpakkane done

**Pull request merged**
