### PR TITLE
environment: use ExternalProgram to find ninja

### PR DESCRIPTION
**Pull request by bonzini**
This allows the NINJA environment variable to support all the Windows special
cases, especially allowing an absolute path without extension.

Based on a patch by Yonggang Luo.

Fixes: #7659

### CODE REVIEW

**Comment by bonzini** [comment]
@lygstate

**Review by mensinda — APPROVED** [review]
LGTM

**Comment by lygstate** [comment]
lgtm

**Comment by eli-schwartz** [comment]
LGTM.

Since this uses ExternalProgram it should automatically parse a shebang and therefore correctly handle #7637 for free. Right?

**Comment by bonzini** [comment]
It actually should!

**Comment by bonzini** [comment]
Would be nice to have this in 0.55.2 if possible, after it soaks for a bit in master and once @lygstate has tested it for #7637 too.

@nirbheek?

**Comment by lygstate** [comment]
@bonzini  you have already queued a series of patches of mine about qemu, where are they,.i can rebase on it and check this fix

**Comment by bonzini** [comment]
You can use the `tags/for-upstream` tag at https://gitlab.com/bonzini/qemu.git

**Comment by lygstate** [comment]
High, this patch are verified with qemu, can this to be released with 0.55.2?

**Comment by nirbheek** [comment]
It's on my list for 0.55.2. I just need to run some tests on it :)

**Pull request merged**
