### PR TITLE
Detect OpenMP on macOS with Apple's Clang

### LINKED ISSUE #7435: Add OpenMP support on clang / macOS
At this moment there is no way to detect OpenMP dependency on clang / macOS using Meson Build.
However OpenMP can be used with clang on macOS with `brew install libomp` and `-Xpreprocess` compiler option.

### PR DESCRIPTION
**Pull request by dcbaker**
This has been opened as a draft because it is probably not sufficient yet, but it's a start.

Fixes #7435

### CODE REVIEW

**Comment by dcbaker** [comment]
@lesteve, this seems to be working in our CI, does this this work for you?

**Comment by tristan957** [comment]
Looks like this needs a rebase. Than I can review it

**Comment by lesteve** [comment]
> @lesteve, this seems to be working in our CI, does this this work for you?

I can confirm that this PR fixes my original issue. In particular with my minimal reproducer repo https://github.com/lesteve/meson-openmp-osx, OpenMP is detected without having to set any environment variable. Also I checked the compiled binary does indeed uses multiple threads.

Sorry it took me a while to get back to this ...

**Comment by lesteve** [comment]
Looks like this branch now has conflicts, but quickly looking at this, they seem straightforward to fix.

Let me know if there is something I can do to help move this forward!

**Comment by tristan957** [comment]
Could be good to get this to 1.5. I know @dcbaker is a busy guy. Could you take his branch, rebase it, and add that it supersedes this PR? Might be the quickest way to resolution.

**Comment by lesteve** [comment]
> Could you take his branch, rebase it, and add that it supersedes this PR? Might be the quickest way to resolution.

Thanks @tristan957, I have opened #13350 that does this.

**Comment by dcbaker** [comment]
Superseded by #13350

**Pull request closed without merging**
