### PR TITLE
cuda: avoid test failure without GPU available

### LINKED ISSUE #13269: 1.4.1 breaks cuda 17 separate compilation linking test
As of Meson 1.4.1, `run_tests.py` fails in a cuda test. Meson 1.4.0 is still fine.

**system parameters**
* Arch Linux
* Cuda 12.5.0-1
* Python 3.12.3-1
* Meson 1.4.1
* Ninja 1.12.1-1

<details><summary><strong>Test failure log</strong></summary>

```
Mesonlogs of failing tests


=============================== cuda: 17 separate compilation linking ==============================
 

Failed during: test
Reason: Running unit tests failed.
 

(inprocess) $ setup --prefix /usr --libdir lib 'test cases/cuda/17 separate compilation linking' '/build/meson/src/meson-1.4.1/b baa2750840' --backend=ninja
The Meson build system
Version: 1.4.1
Source dir: /build/meson/src/meson-1.4.1/test cases/cuda/17 separate compilation linking
Build dir: /build/meson/src/meson-1.4.1/b baa2750840
Build type: native build
Project name: device linking
Project version: 1.0.0
C++ compiler for the host machine: c++ (gcc 14.1.1 "c++ (GCC) 14.1.1 20240522")
C++ linker for the host machine: c++ ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Cuda compiler for the host machine: nvcc (nvcc 12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0)
Cuda linker for the host machine: nvcc nvlink 12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
test cases/cuda/17 separate compilation linking/meson.build:12: WARNING: Module CUDA has no backwards or forwards compatibility and might not exist in future releases.
Message: NVCC version:   12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
Message: NVCC flags:     -gencode arch=compute_80,code=sm_80
Build targets in project: 2

device linking 1.0.0

  User defined options
    backend: ninja
    libdir : lib
    prefix : /usr

Found ninja-1.12.1 at /usr/bin/ninja
ninja explain: deps for 'app.p/main.cu.o' are missing
ninja explain: app.p/main.cu.o is dirty
ninja explain: deps for 'libdevicefuncs.a.p/b.cu.o' are missing
ninja explain: libdevicefuncs.a.p/b.cu.o is dirty
ninja explain: libdevicefuncs.a is dirty
ninja explain: app is dirty
ninja explain: meson-test-prereq is dirty
ninja explain: output meson-benchmark-prereq of phony edge with no inputs doesn't exist
ninja explain: meson-benchmark-prereq is dirty
ninja explain: libdevicefuncs.a is dirty
ninja explain: app is dirty
[1/4] Compiling Cuda object libdevicefuncs.a.p/b.cu.o
[2/4] Linking static target libdevicefuncs.a
[3/4] Compiling Cuda object app.p/main.cu.o
[4/4] Linking target app
ninja explain: output build.ninja older than most recent input ../test cases/cuda/17 separate compilation linking/meson.build (1717095069265791924 vs 1717095070669117141)
[0/1] Regenerating build files.
The Meson build system
Version: 1.4.1
Source dir: /build/meson/src/meson-1.4.1/test cases/cuda/17 separate compilation linking
Build dir: /build/meson/src/meson-1.4.1/b baa2750840
Build type: native build
Project name: device linking
Project version: 1.0.0
C++ compiler for the host machine: c++ (gcc 14.1.1 "c++ (GCC) 14.1.1 20240522")
C++ linker for the host machine: c++ ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Cuda compiler for the host machine: nvcc (nvcc 12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0)
Cuda linker for the host machine: nvcc nvlink 12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
../test cases/cuda/17 separate compilation linking/meson.build:12: WARNING: Module CUDA has no backwards or forwards compatibility and might not exist in future releases.
Message: NVCC version:   12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
Message: NVCC flags:     -gencode arch=compute_80,code=sm_80
Build targets in project: 2

device linking 1.0.0

  User defined options
    backend: ninja
    libdir : lib
    prefix : /usr

Found ninja-1.12.1 at /usr/bin/ninja

Generating targets:   0%|          | 0/2 eta ?
                                              

Writing build.ninja:   0%|          | 0/30 eta ?
                                                
Cleaning... 0 files.
ninja explain: output meson-benchmark-prereq of phony edge with no inputs doesn't exist
ninja explain: meson-benchmark-prereq is dirty
ninja: no work to do.
10/1 cudatest FAIL            0.01s   exit status 1
>>> MALLOC_PERTURB_=178 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 '/build/meson/src/meson-1.4.1/b baa2750840/app'


Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /build/meson/src/meson-1.4.1/b baa2750840/meson-logs/testlog.txt
No tests defined.
 

                                                  


Total passed tests:  677
Total failed tests:  1
Total skipped tests: 77

All failures:
  -> cuda: 17 separate compilation linking
```

</details>

### PR DESCRIPTION
**Pull request by SoapGentoo**
Fixes #13269

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@heftig

**Review by eli-schwartz — APPROVED** [review]
Thanks. I locally reproduced the failure since I don't have nvidia hardware either, and had to specially install cuda to actually run the tests and watch them mostly run except for this one.

As such I can also confirm this fixes it for me. :)

**Comment by heftig** [comment]
This works; thanks.

**Comment by eli-schwartz** [comment]
All test failures are accounted for. Other than the Windows/rust one, they are CI image builders known to currently fail, which isn't a problem since we only care about updating the cuda image builder.

**Pull request merged**
