### PR TITLE
intl dep: support static kwarg

### PR DESCRIPTION
**Pull request by eli-schwartz**
/cc @lazka who asked for this

### CODE REVIEW

**Comment by lazka** [comment]
I can confirm that this works for my project. And the changes also lgtm, for what it's worth.

**Review by dcbaker — APPROVED** [review]
This all looks good to me

**Comment by jpakkane** [comment]
The first commit should probably not be there...

**Comment by dcbaker** [comment]
That's already merged and should rebase out, right?

**Comment by jpakkane** [comment]
FWICT yes.

**Comment by jpakkane** [comment]
Also this :crossed_swords: conflicts now.

**Comment by eli-schwartz** [comment]
Right, the first commit was there because I rebased this on top of the codecov.yml PR in order to test out the latter. Rebased to fix conflicts...

**Comment by eli-schwartz** [comment]
Oops, I was too hasty to merge this. It passed CI before the rebase... but now there is `[UNEXSKIP]   frameworks: 6 gettext    (static=true)` on macOS, which I guess isn't shocking since I had investigated the static case for msys2. But I do wonder why it reports skipped instead of failed.

**Comment by dcbaker** [comment]
cvan't find intl maybe?

**Pull request merged**
