### PR TITLE
Run all D tests if a recent enough GDC is used

### PR DESCRIPTION
**Pull request by ximion**
A while back, the GDC D compiler didn't have shared library support, but that feature is there now for more than a year. That means it's safe to enable these tests now.

This PR also resolves a few typos.

### CODE REVIEW

**Comment by ximion** [comment]
Okay, do NOT merge this... It looks like the GDC version used on Travis is still too old to work well with this (I thought it was updated...).

If there are no plans to update GDC in the very near future, I would close this PR and open a new one that contains only the trivial typo fixes.

**Comment by QuLogic** [comment]
How about adding a version check?

**Comment by jpakkane** [comment]
Is this ready to merge now?

**Comment by ximion** [comment]
@jpakkane Yes, this should all be fine now. I have no idea why Codecov thinks this would decrease coverage by 0.01%, it should not do anything to coverage (unless your GDC is recent enough, in which case it should actually *increase* coverage).

**Pull request merged**
