### PR TITLE
treewide: internally avoid deprecated machine file uses of "pkgconfig"

### PR DESCRIPTION
**Pull request by eli-schwartz**
We support this in a machine file:

```
[binaries]
pkgconfig = 'pkg-config'
pkg-config = 'pkg-config'
```

and you can use either one, because internally we look up both. If you only set *one* of them, this plays awkwardly with setting $PKG_CONFIG, since we don't know which one you set in the machine file and the *other* one will be initialized from the environment instead.

In commit 22df45a31981874310a78dde0df59a6a7c5ebb29 we changed program lookup of config-tool style dependencies to use the regular tool names and only fall back on the strange internal names. This affected the pkg-config class too.

The result is that instead of preferring `pkgconfig =` followed by $PKG_CONFIG followed by `pkg-config =`, we inverted the lookup order. This is a good idea anyway, because now it behaves consistently with `find_program('pkg-config')`.

Unfortunately, we documented the wrong name in a bunch of places, and also used the wrong name in various testsuite bits, which meant that if you set $PKG_CONFIG and then ran the testsuite, it would fail.

Correct these references, because they are buggy.

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]

**Comment by mhmdanas** [comment]
Thanks for the quick fix, can confirm that with this the tests pass. Cheers!

**Comment by xclaesse** [comment]
LGTM, but CI seems unhappy.

Should we also actually deprecate pkgconfig? Something along the line of https://github.com/mesonbuild/meson/commit/d5f4228827d68e40ca8a038ea45d442ab7667b0c

**Comment by eli-schwartz** [comment]
> LGTM, but CI seems unhappy.

The failing test is... interesting.

It happens only during cross builds, and it happens because we test that pkgconfig generation works by inserting a manual requires on `'glib-2.0'` as a string.

The test case uses `find_program('pkg-config', required: false)`, which previously found nothing from the cross file, but now finds something because the lookup value in the global cross file for tests is `pkgconfig -> pkg-config`. This means that:
```meson
pkgconfig = find_program('pkg-config', required: false)

env = environment()
env.prepend('PKG_CONFIG_PATH', meson.current_build_dir() / 'meson-private')

test(
  'pkgconfig-validation',
  pkgconfig,
  args: ['--validate', 'simple'],
  env : env,
)
```
now runs a cross pkg-config test:
```
PKG_CONFIG_PATH='/__w/meson/meson/b 752d8a5fd7/meson-private' /usr/bin/x86_64-w64-mingw32-pkg-config --validate simple
```

whereas before, it ran a native pkg-config test:
```
PKG_CONFIG_PATH='/__w/meson/meson/b 752d8a5fd7/meson-private' /usr/bin/pkg-config --validate simple
```

Naturally, the cross environment doesn't have a mingw glib-2.0 installed...

**Pull request merged**
