### PR TITLE
Replace testing options with a "test command" option.

### LINKED ISSUE #1885: Move stdsplit to mesontest
Currently stdsplit is a top level Meson option. This made sense when it was created because Mesontest did not exist at the time. Now it does and it might make more sense to remove the option and turn it into a command line argument to mesontest.

This would mean that a plain `ninja test` would always keep stderr and stdout separate.

### PR DESCRIPTION
**Pull request by trhd**
Remove testing options `stdsplit` and `errorlogs` and allow one to freely define the test command to be used from the `test` target.

Also removes the corresponding options from the main meson command so this could perhaps be considered as an API breaking change?

By allowing developer's to choose the test command they can even replace the mesontest altogether if they would so choose.

Current revision uses `%m` in the test command to expand to the meson itself. E.g.

```
$ ../meson/meson.py configure b
[snip]
  Option       Current Value                                        Description
  ------       -------------                                        -----------
  test_command %m test --no-rebuild --no-stdsplit --print-errorlogs The command to invoke to run tests.
[snip]
```

Fixes #1885.

EDIT: PR no longer replaces the testing options with a "test command" but only updates them.

### CODE REVIEW

**Comment by jpakkane** [comment]
I appreciate what this is trying to do but I'm not sure if this is the correct way to do it or even if we should do this at all. We have tried to express everything as an option rather than exposing command line switches to users. This one goes in the opposite direction.

Completely replacing the test command is sort of already possible with `run_target`.

**Comment by trhd** [comment]
In that case I think there are three different approaches that can be taken here:

1) Allow developers to modify the test command (the approach suggested by this patch).
2) Have explicit project/testing options for (eventually) every option that can be given to the the "meson test" command. This is what the `stdsplit` and `errorlogs` options were/are already doing.
3) Have a `test` target that does something. If that doesn't meet your needs create a new alternative testing target.

The downside for each (that I can immediately come up with are):
1) What jpakkane said above + new testing options would not necessarily end up being used in projects that have already overridden the testing command.
2) Eventually there will probably be _too many_ of these. Also quite redundant to define these as they already exist for the `meson test` command anyway.
3) Would be nice if one could expect a meson project to have a target called `test` that would just _do the right thing_ (as defined by the project developers). I think it would be a missed opportunity if the users end up needing to check from a project's README file what the name of the real testing target is, that should be used.

I'm fine with whatever approach is chosen. Just thought that I should point this out before closing the PR.

**Comment by jpakkane** [comment]
Could we estimate how many different togglable options could there be (for the default case, not extra options to run with Valgrind etc)? How many of them affect behavior rather than just be "nice-to-have"s like `stdsplit`?

**Comment by trhd** [comment]
From the currently supported options someone could perhaps have a use case for a corresponding option:

> optional arguments:
>   -h, --help            show this help message and exit

Nope.

>   --repeat REPEAT       Number of times to run the tests.

Maybe.

>   --no-rebuild          Do not rebuild before running tests.

Don't know.

>   --gdb                 Run test under gdb.

Probably not.

>   --list                List available tests.

Nope.

>   --wrapper WRAPPER     wrapper to run tests with (e.g. Valgrind)

Probably not needed as a test setup would probably make more sense.

>   -C WD                 directory to cd into before running

Nope.

>   --suite SUITE         Only run tests belonging to the given suite.

Yes. I could imagine someone would like to run only a subset of all the defined tests as part of the _official set of tests_.

>   --no-suite SUITE      Do not run tests belonging to the given suite.

The same as the previous.

>   --no-stdsplit         Do not split stderr and stdout in test logs.

I personally think this is quite important. The split messes up the order in which messages are shown and thus makes certain debugging situations a pain. Or perhaps if the default was changed to not do the split...

>   --print-errorlogs     Whether to print failing tests' logs.

Perhaps a _nice to have_ feature.

>   --benchmark           Run benchmarks instead of tests.

Probably not.

>   --logbase LOGBASE     Base name for log file.

Maybe.

>   --num-processes NUM_PROCESSES
>                         How many parallel processes to use.

I can imagine cases where no tests should be run in parallel but this could probably be defined in the meson.build files themselves.

>   -v, --verbose         Do not redirect stdout and stderr

Someone would probably want this.

>   -q, --quiet           Produce less output to the terminal.

Same as above.

>   -t TIMEOUT_MULTIPLIER, --timeout-multiplier TIMEOUT_MULTIPLIER
>                         Define a multiplier for test timeout, for example when
>                         running tests in particular conditions they might take
>                         more time to execute.

Maybe. If you know all your tests take a really long time. Then again, you'd probably define better time limits for individual tests.

>   --setup SETUP         Which test setup to use.

Sure.

>   --test-args TEST_ARGS
>                         Arguments to pass to the specified test(s) or all
>                         tests

Maybe not.

Soo... `suite`, `setup`, `stdsplit` and `verbosity`? `verbosity` could combine `quiet`, `verbose` and `errorlogs`. As an absolute minimum, I think, `suite` and `setup` would be needed. Others may of course feel otherwise. Definitely less than I would have thought.

**Comment by trhd** [comment]
It started to feel like the 2nd approach was a better one. So here goes...

Testing options now include `suite`, `setup`, `stdsplit` and `output`.

**Comment by nirbheek** [comment]
It's usually a bad idea to prematurely implement features without a specific "user-story"/use-case in mind. You just end up with a lot of unused options that need to be supported, tested, documented, and so on. It also restricts other features by taking up 'API-space'.

The original issue was about moving `stdplit` to `mesontest` so that we have one *less* option in `default_options:`. This PR does the opposite and adds *more* options to `default_options:`.

Let's stay away from this till someone comes to us with a compelling user-story. Closing till then.

**Pull request closed without merging**
