### PR TITLE
summary: Wrap lines when printing lists

### PR DESCRIPTION
**Pull request by xclaesse**
When a list_sep is provided (e.g. ', ') all items are printed on the
same line, which gets ugly on very long lists (e.g. list of plugins
enabled).

### CODE REVIEW

**Comment by dabrain34** [comment]
dont you think it should be configurable instead in the summary call ?

**Comment by xclaesse** [comment]
I'm not sure. I don't like hard coding an arbitrary number coming from another century, but making it configurable means that if 2 projects picks different value you'll have inconsistent output. 80 chars still makes sense today, it's the default size of most terminals (at least on Linux) when the window is not maximized.

We can always make it configurable later, maybe for example choosing the max value of all summary() calls.

**Comment by dabrain34** [comment]
yes you're right. It would make sense to configure it on meson command line livel, otherwise it does not make any sense, inside the projects.(I dont like neither to hardcode values like that)

**Comment by xclaesse** [comment]
Updated to use `shutil.get_terminal_size().columns` instead of hard coding 80 chars.

**Comment by tp-m** [comment]
> Updated to use `shutil.get_terminal_size().columns` instead of hard coding 80 chars.

perfect! :heart:

**Pull request merged**
