### PR TITLE
Add zsh completion function for Meson

### PR DESCRIPTION
**Pull request by porrided**
There are features not yet implemented, like completing
build targets and build options; more on this in the comments.

### CODE REVIEW

**Comment by jpakkane** [comment]
Would it make more sense to submit this to zsh upstream instead?

**Comment by porrided** [comment]
We already have a major mode for Emacs and Meson syntax highlighting for Vim as part of the source tree.
Moreover, Meson is in active development, so IMHO it makes sense to update this in sync with Meson release cycle and not depend on zsh upstream.
For example, systemd, Ninja, youtube-dl all do it the same way.

**Comment by nirbheek** [comment]
Hum, can you name it a bit better? Such as `data/completions/zsh`? Please also move the `syntax-highlighting` dir under `data` and also move the emacs mode into it.

**Comment by porrided** [comment]
> Please also move the syntax-highlighting dir under data and also move the emacs mode into it.

Great idea, done.
Opted to skip CI as I'm not touching Meson itself, only `data/`

I'm also planning to write a bash completion function (probably if/after singleexe is merged in to account for new CLI syntax) and to take a try at teaching mesonintrospect to output CSV, but that is outside the scope of this PR.

**Comment by jpakkane** [comment]
If we eventually want to submit this upstream will there be a license issue? AFAICR zsh is BSD and we are Apache.

**Comment by porrided** [comment]
> If we eventually want to submit this upstream will there be a license issue? AFAICR zsh is BSD and we are Apache.

As this is basically a short and simple helper utility, I see no issue with picking the same license as the project we're submitting this to.

If we merge this and ship this together with Meson, this is going to be Apache, and the zsh license is irrelevant, as it is for any separately maintained zsh script (e. g. Meson is written in Python, but this does not in any way mean we had to use Python licenses).
If we instead settle on not shipping our own shell completions, then we close this PR, this will go to zsh upstream, be distributed with zsh upstream and thus is going to be BSD.

**Comment by jpakkane** [comment]
This is a standalone script so it is possible to add a BSD license header at the top. Just the fact that it is shipped alongside an Apache licensed project does not mean it has to be Apache.

**Comment by jpakkane** [comment]
Ping.

**Comment by porrided** [comment]
We've migrated to singleexe so this obviously needs a slight heads-up to support the subcommands before it can be merged.
Sorry, but I'm busy ATM, let's give it some time.
I'll also rebase the PR on latest master for convenience when the completion is ready.

On licensing: I do not object to putting this under BSD but am still failing to understand what exactly is wrong with distributing this under Apache.

Another related question while we're still at it: we're clearly getting rid of the old executables, but did we as well deprecate the old builddir generation syntax (`meson "dir1" "dir2"`) altogether in favour of `meson setup "dir1" "dir2"`? Or are there no such plans?

**Comment by jpakkane** [comment]
> what exactly is wrong with distributing this under Apache

Because we want to be able to submit this directly to zsh. A more thorough lookup shows that zsh is actually under a MIT-like license and not BSD. So it would probably need to be that then.

**Comment by porrided** [comment]
Ok, I've finally got back to the script.
Would it be OK if I just put a licence header there equivalent to zsh's licence?

**Comment by jpakkane** [comment]
Sure.

**Comment by Muffo** [comment]
This sounds very useful! Is there a guide on how this can be installed? I have only used oh-my-zsh until now and never had to install an autocompletion file manually.

**Comment by porrided** [comment]
> This sounds very useful! Is there a guide on how this can be installed? I have only used oh-my-zsh until now and never had to install an autocompletion file manually.

Questions about Zsh _(but not about oh-my-zsh)_ are best directed to [the zsh project's mailing lists](http://zsh.sourceforge.net/Arc/mlist.html). In your case that would be zsh-users@.

What system are you using zsh and meson on?

This is intended to be installed along with Meson itself, especially if you use a package manager. For example, on Debian, when you install the `meson` package, this gets installed to `/usr/share/zsh/vendor-completions/`. On macOS something like Homebrew can take care of this.

There is a way to install the completion manually: by putting the file into a directory of your choosing, e. g. `~/.config/zsh/completions/`, and then appending this directory to the front of your fpath array in the .zshrc:
```zsh
fpath=(
    ~/.config/zsh/completions
"${(@)fpath}")
```
From then on you can put completion files to that directory, and zsh will load them on startup.

**Comment by Muffo** [comment]
Thanks a lot!

**Pull request merged**
