### PR TITLE
Pylint fixes, a first slice

### PR DESCRIPTION
**Pull request by dcbaker**
I've take a few patches from #10767, and pulled them out into a former that's easier to review.

### CODE REVIEW

**Comment by tristan957** [comment]
Nothing stands out as a regression to me

**Comment by dcbaker** [comment]
Any case where you have a const evaluatable set, python will optimize that into a pre-computed frozenset. So you do a single hash computation and lookup on a pre-computed set, vs two character by character comparisions.

**Comment by tristan957** [comment]
I see. Makes more sense with the explanation.

**Review by eli-schwartz — APPROVED** [review]
Enabling newly added warnings by default (??? probably? pylint docs don't seem to be clear on the matter) seems fine to me, if we don't like any of them it will be really easy to get CI working again by just disabling them when pylint updates.

Aside for that, the reasoning to list the disabled ones instead of the enabled ones is solid logic, and the actual code changes are all good too.

I did have an odd moment where this PR caused lots of new warnings to appear, but it turned out to be because I needed to update pylint, so never mind that.

**Pull request merged**
