### PR TITLE
mtest: Return 1 when no test is found

### LINKED ISSUE #4913: meson test TEST returns 0 if TEST does not exist
Hello,

I just discovered that running `meson test TEST` returns 0 even if `TEST` does not exist.
A clear `No suitable tests defined.` message is outputted to the user.

Would it not make more sense to return non-zero in this case?
The current behavior can be misleading, as users will most probably expect that the test has been executed successfully, not that it has not been executed at all — notably in CI scripts.

#### Tested version
- meson-0.49.2
- ninja-1.8.2

### PR DESCRIPTION
**Pull request by mpoquet**
Fixes #4913

### CODE REVIEW

**Comment by dcbaker** [comment]
the failures look relevant.

**Comment by jpakkane** [comment]
Since this is a behavioural change, it should get a mention in the release notes. This is done by adding a file in the `docs/markdown/snippets` directory. Thanks.

**Comment by jpakkane** [comment]
Ping.

**Comment by mpoquet** [comment]
Sorry, I have no time to work on this for the moment :(.

**Comment by jpakkane** [comment]
No prob, feel free to reopen when it is ready.

Thanks.

**Pull request closed without merging**
