### PR TITLE
Add custom libgcrypt dependency using libgcrypt-config

### LINKED ISSUE #3563: Add gcrypt-config support
As used by libgcrypt. This is useful as the upstream refuses to have a pkg-config file because they don't understand how it works.

### PR DESCRIPTION
**Pull request by TingPing**
Fixes #3563

### CODE REVIEW

**Comment by TingPing** [comment]
```
meson.build:5:2: ERROR:  Problem encountered: MESON_SKIP_TEST: libgcrypt-config not installed
```

This used the same test layout as the other dependency tests so I guess `MESON_SKIP_TEST` is broken? But also may want to add this to the image to test.

**Comment by jon-turney** [comment]
> I guess `MESON_SKIP_TEST` is broken

Yes, it needs to be in the image.  Framework tests aren't skippable in CI for Linux to ensure dependency detectors aren't broken.

See 0097ce4c4ed872aee9e8cd58b6981b4cfd62e089

**Comment by jpakkane** [comment]
The CI image can only be updated next week once I get to my home computer.

**Comment by jpakkane** [comment]
Image updated. Please add `libgrypt11-dev` to the Docker file and push.

**Pull request merged**
