### PR TITLE
Made build. options mirror plain ones when native compiling

### PR DESCRIPTION
**Pull request by jpakkane**
Yet another approach for #5590. May need some work.

The basic idea is that having separate _options_ for build and host does not make sense when compiling natively. For example there should be only one `c_std` that is used for all targets. Build flags defined _inside_ build files remain as currently.

This is done because needing to understand the difference between host and build machine compilation is confusing for people who don't care about it. It has already lead to bug reports from people doing native compilation only and things going wrong in unexpected ways.

This also reduces the number of options printed with `meson configure`. They were useless noise for most people so this is also a nice usability improvement.

### CODE REVIEW

**Comment by Ericson2314** [comment]
This is an implementation based off of https://github.com/mesonbuild/meson/issues/5590#issuecomment-511491290 ? If so let's drill down on what you mean there first. I really want to end up with something that doesn't use `is_cross_build`, as that is irredeemably dynamic and global, and I feel like perhaps there is a variation of what you are saying that does that.

**Comment by jpakkane** [comment]
> as that is irredeemably dynamic and global

How is it dynamic? Whether a build dir is native or cross building is set when first configuring the build dir and can't be changed thereafter.

**Comment by Ericson2314** [comment]
It's "dynamic" in the sense that it depends on user-specific settings "at run time", rather being determinable from the meson file itself.

**Comment by jpakkane** [comment]
> being determinable from the meson file itself

You can determine it just fine with `meson.is_cross_build()`.

**Comment by nirbheek** [comment]
> You can determine it just fine with `meson.is_cross_build()`.

I think that's what @Ericson2314 means by 'dynamic and global', although I still don't understand what the objection is, exactly.

**Comment by Ericson2314** [comment]
Sorry I meant not that the meson.build can determine the information, but that the information just depends on the meson.build files. The source alone determines the information, and not user-provided arguments like the options and machine and cross files.

I'll try to be less terse once I'm back from vacation, but here's a pithy way to state my goal: just as you should be able to ignore the cross case and just support the cross case, you should be able to support the cross case and "ignore" the native case, just treating it as also cross where it so happens build = host.

If we start changing the rules for native vs cross builds, you can't do that. The simplifications that are meant to make native-only authors' lives easier mean the cross-supporting meson.builds need to litter their code with `if is_cross_build` to cope with the change in behavior.

The choosing whether to support cross is a choice of the package author, while the build and host platforms are a choice of the user. Changing the rules based on `build == host` is trying to guess the author's choice from the user's choice.

**Comment by nirbheek** [comment]
@Ericson2314 do you know when you'll be back? This is blocking the 0.51.2 stable release, and since we need your input if it'll take too long we can punt it to 0.51.3 🙂 

Over IRC we had the following discussion:

1. Unprefixed options apply to host targets, and when compiling natively build == host so they should apply to all targets. If that doesn't happen, that's a bug. (**must go into a stable release**)

2. `build.` options should not be visible when not cross-compiling, and even setting them should be an error when not cross-compiling. (**must go into a stable release**)

3. The UI/UX of `build.` options should probably be improved in some way to make them more discoverable in the cross case (**not needed for a stable release**)

**Comment by jpakkane** [comment]
Sadly there does not seem to be one way of selecting the "best" approach. One makes things simpler for cross builders while at the same time making things a lot more confusing to native builders. Since there are a lot more of the latter than former, we should probably optimize for that common case. Unfortunately it will mean some extra work for cross builders.

**Comment by Ericson2314** [comment]
I think we can have the best of both worlds. I'm fine with all of this PR until the final commit, too. I'm back Sunday and will try to push a full solution by the end of next week, and hopefully smaller steps sooner.

**Comment by dcbaker** [comment]
I'm going to read through this discussion, think hard about it, and try to have some kind of opinion shortly, we're seeing the fallout of this in [mesa right now](https://bugs.freedesktop.org/show_bug.cgi?id=111126).

**Comment by jpakkane** [comment]
FTR that Mesa regression on its own would be serious enough to rollback the entire feature.

**Comment by dcbaker** [comment]
@Ericson2314, could you give a brief code example of what the problem with @jpakkane's approach is? aliasing `build` to `host` for cases of "native" compiling seems reasonable to me, but I'm willing to be convinced that it's not.

**Comment by Ericson2314** [comment]
The problem is `set_options` is used both for CLI args (user provided stuff) and certain functions in the meson file. For CLI args the patch is fine, but for a project that supports cross, I want `add_project_arguments(..., native: false)` to only affect `native: false` targets, and likewise for `is_true`. Making the semantics of `add_project_arguments` *more complicated* by depending on whether `build == host` just means the author has to use more `meson.is_cross_build()`, which is silly and easy to forget.

Instead I want to have
```meson
project(..., supports_cross: a_bool)
```
if the project has `supports_cross = true` then `native` kwargs are disallowed, and `add_project_arguments` and friends always affect all targets. But if the project has `supports_cross = false`, then `add_project_arguments` works as I described above: it always affects exactly the targets with the matching `native` flag, regardless of whether `build == host`.

This is the best of both worlds because the native-only author doesn't have to worry about the cross, and the cross-aware author doesn't have to worry about native as a special case with different rules.

-------

The the package config path thing is a separate issue. I've long wanted to fix #3969 and doing so will fix that issue.

**Comment by jpakkane** [comment]
Could someone with Mesa experience check that whether this PR fixes the issue referenced above?

**Comment by jpakkane** [comment]
The silence means it's merge time. @nirbheek this means that 0.52.2 should be ready for release.

**Comment by Ericson2314** [comment]
@jpakkane that silence was the rest of my vacation. I had started rebasing your PR to try to find a solution we'd both find acceptable. Sorry I thought i said here or IRC that I would try to get it done by the end of this week back, but I cannot find the message now.

**Comment by Ericson2314** [comment]
If we could wait to do the release to give me a little time to try to finish that, I would very much appreciate that.

**Comment by jljusten** [comment]
@jpakkane: Sorry for the delay. I can confirm that 5fd49637 appears to fix the issue for me with mesa.

**Comment by nirbheek** [comment]
@Ericson2314 do poke me when you've got another PR ready, will block the 0.51.2 release on that.

**Comment by Ericson2314** [comment]
Thanks @nirbheek.

**Comment by jpakkane** [comment]
Letting things drag on indefinitely is not good either. I'm putting a hard deadline for this to be the next Friday. If this has not been solved by then the point release will go out as is and any issues will be fixed in later releases.

**Comment by Ericson2314** [comment]
That's fair. I am at http://icfp19.sigplan.org/ next week so I will push harder this week. If anyone else can look at the build failures in #5786 and #5786 that would be much appreciated, as it will depend on them `--force-cross` for tests.

**Comment by xclaesse** [comment]
I believe this MR is wrong, `meson build -Dpkg_config_path=/foo -Dbuild.pkg_config_path=/bar` result in pkg_config_path being /bar instead of /foo when not cross building.

**Comment by xclaesse** [comment]
> I believe this MR is wrong, `meson build -Dpkg_config_path=/foo -Dbuild.pkg_config_path=/bar` result in pkg_config_path being /bar instead of /foo when not cross building.

Fixed as part of https://github.com/mesonbuild/meson/pull/7574.

**Pull request merged**
