### PR TITLE
CompilerArgs: Put start/end-group around shared libs too

### PR DESCRIPTION
**Pull request by nirbheek**
Closes https://github.com/mesonbuild/meson/issues/2096

### CODE REVIEW

**Comment by jpakkane** [comment]
I'm a bit concerned about this now. It's good that we do aggressive dedupping but needing linker groups always is a bit worrisome. (In hindsight, if I was starting Meson today, I would dedup everything and put everything in a single linker group because it's the only sane thing to do, but too late for us now.)

Are there cases where we need to support some linker that does not have group support?

**Comment by nirbheek** [comment]
> Are there cases where we need to support some linker that does not have group support?

I think we discussed this already in the [old PR](https://github.com/mesonbuild/meson/pull/1545#issuecomment-305994816)?

"Library grouping" is a hack that GNU ld (both bfd and gold) came up with because their symbol resolution is idiotic. It reads the argument list left to right, maintains a list of undefined/needed symbols, and resolves them as it encounters libraries/objects. This means you need to specify libraries multiple times to resolve circular dependencies, and you need to specify them in the 'correct' order (this order is unknowable to the build system). To work around this, they added `--start/end-group` in which it will go over the library list repeatedly till all symbols are resolved.

All other linkers that we support (MSVC, Apple ld, Clang lld) do not need this. I do not know exactly how they do symbol resolution, but I would guess that they maintain a datastructure with known symbols and resolve undefined/needed symbols against that (which seems like the saner way to do it).

We have a test for this precisely so we can know if some unknown linker is broken in the same way.

**Comment by jpakkane** [comment]
I see this is tagged 0.41.3 but it's been a while since the last proper release so maybe we should go to 0.42.0 instead.

**Comment by nirbheek** [comment]
The milestone is ok, if we don't need a stable release, we can ignore it. I just set it in advance because it's easier to constantly keep track.

**Pull request merged**
