### PR TITLE
Support gl-libs

### PR DESCRIPTION
**Pull request by SolarAquarion**

### CODE REVIEW

**Comment by sarum9in** [comment]
Why not `dependency('wxwidgets', modules : ['gl'])`?

**Comment by SolarAquarion** [comment]
True enough but I have no idea about how meson does stuff

**Comment by sarum9in** [comment]
`dependency('wxwidgets', modules : ['gl', 'stc'])` becomes
```
$ wx-config --libs gl stc
-pthread   -lwx_baseu-3.0 -lwx_gtk2u_gl-3.0 -lwx_gtk2u_stc-3.0
```

You can specify what modules you need from `wxwidgets` this way.

**Comment by sarum9in** [comment]
I believe I covered `wxwidgets` in documentation. Please reopen if not.

**Pull request closed without merging**
