### PR TITLE
config data: add .set_quoted() convenience method to set quoted string

### PR DESCRIPTION
**Pull request by tp-m**

### CODE REVIEW

**Comment by tp-m** [comment]
Rationale: writing

``` cdata.set('FOO', '"@0@"'.format(string))```

gets tedious after a while and doesn't look nice, same goes for

``` cdata.set('FOO', '"' + string + '"')```

**Comment by jpakkane** [comment]
Makes sense. Should we do something about double quotes inside the strings or just say that it is the user's problem?

**Comment by tp-m** [comment]
Hrm, good point, I hadn't thought of that. If we say it's the user's problem, then we will sooner or later have to provide an escape function.

Since configuration_data is for C-style header files (?) it'd probably be okay and The Right Thing to Do to automatically escape? Are there any languages we know of where that would not work? The user can still do the manual set if the escaping is not right for their use case.

Or we add a `language:` kwarg to the `configuration_data()` call. Or just add a `string_escape` kwarg to disable it if it ever turns out to be a problem.

**Comment by nirbheek** [comment]
`configuration_data` can be used for doing macro expansion in arbitrary files, so even if the most-common case is for C sources/headers, someone is going to do it for some other language or some other purpose and be surprised.

I think we can have an `escape_for` kwarg for the string method (not `configuration_data`) that takes a language name, and for now we can just implement it for C.

**Comment by nirbheek** [comment]
Sorry, I wasn't clear enough and didn't think it through in detail. I'm proposing this:

```
string = 'this-"omg"-ok'
cdata.set('SUBST', string) 
```
This would set `SUBST` to `this-"omg"-ok`

```
string = 'this-"omg"-ok'
cdata.set('SUBST', string.quoted()) # same as for : 'none' (just adds quotes around it)
```
This would set `SUBST` to `"this-"omg"-ok"`

```
string = 'this-"omg"-ok'
cdata.set('SUBST', string.quoted(for : 'plain')) # Just adds quotes around the string and does " → \"
```
This would set `SUBST` to `"this-\"omg\"-ok"`

We can implement more complicated quoting later, such as:
```
string = 'this-"omg"-\nok'
cdata.set('SUBST', string.quoted(for : 'c')) # Quoting for use in C strings
```
This would set `SUBST` to `"this-\"omg\"-\nok"` (note that without `'c'`, the `\n` would not be quoted and would be a literal newline)

The reason why I think this is nicer than putting it as a `cdata` method is because it's generally useful, and it might be used outside of `set_quoted` too. For instance if you're handling quoting inside C macros and want to just substitute literally without quotes.

**Comment by jpakkane** [comment]
Meson has a specific approach to string quoting. All generated strings are kept unquoted and as close to original as possible and only quoted at point of use (where users can't get to them). This is the only way to stay sane and is how e.g. command line argument expansion works. And even then we have bugs in quoting. Allowing (or even expecting) users to do quoting is poor usability.

Let's not add a quote function and instead keep the set_quoted method but have it quote double quotes in the C way. The behaviour of configdata is currently tied to generating C source so it should work for the most common case. If (and only if) people start requiring other quotation styles we can do `configure_file(..., quote_style : 'java')` or whatever.

This need will probably never arise because other languages do not have a need for C style autoconf work, they have new & improved builtin ways of dealing with this.

**Comment by nirbheek** [comment]
Then I propose that we keep the quoting really dumb: only escape `"`" → `\"` within the string and nothing else.

**Comment by jpakkane** [comment]
Yep.

**Pull request merged**
