### PR TITLE
backends/ninja: Add native files to rebuild dependencies

### PR DESCRIPTION
**Pull request by dcbaker**
Just like cross files.

### CODE REVIEW

**Comment by dcbaker** [comment]
ping

**Comment by nirbheek** [comment]
I really want a 'merge when CI passes' button on github :)

**Comment by dcbaker** [comment]
That really is one of the best features of gitlab :)

**Comment by nirbheek** [comment]
Removed from the 0.50.1 milestone because the datastructures for storing cross and native(config) files changed significantly and I don't want to break anything.

**Pull request merged**
