### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/mesonbuild/meson/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/mesonbuild/meson).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by nirbheek** [comment]
The code quality alerts are interesting and mostly correct, but adding code quality badges without adding corresponding CI seems pointless. Why does this PR not include that?

Also, what tools do you run for these alerts? We already run `flake8`, but that didn't catch these.

**Comment by xcorail** [comment]
Hello @nirbheek 

Thanks for your feedback!

> adding code quality badges without adding corresponding CI seems pointless. Why does this PR not include that?

Indeed. The badge is purely informatory. The PR doesn't include CI because only an admin of the repo dan do it. It's a [one-click operation](https://lgtm.com/projects/g/mesonbuild/meson/ci/). Please give it a try and let me know

> Also, what tools do you run for these alerts?

We do not aggregate alerts from other tools. These alerts are ours. Our technology (extract code as data in a DB and run queries on this DB) allows us to do deeper analysis than the usual tools while keeping a low level of false positives, this is certainly why we catch alerts that others don't. If you want to have a look at what the queries look like, they are open source at https://github.com/Semmle/ql (The queries are open source, our engines that run them are proprietary)

**Comment by jpakkane** [comment]
I did the one click thing. After a few clicks I got this:

> This application will be able to read and write all public repository data.

Is this some sort of a limitation of the Github model? Why does every single code analysis tool want full write access to the repository? It really should not have it. Write access to the pull requests themselves is fine, but I _really_ don't want to give full write access to third parties.

**Comment by xcorail** [comment]
Hello @jpakkane 

You are right, we don't actually need full write access to your repo, we just want to be able to **comment on PRs**. And this is the only write operations that we are doing.
We are planning to switch to the Github checks API in the near future (discussing our next quarter plan atm), and we will switch to needing more fine-grained permissions. 

Cheers

**Comment by jpakkane** [comment]
Let's merge this now, we can add the other ones once the security model change is done.

**Pull request merged**
