### PR TITLE
Add 'compiles' and 'has_multi_arguments' for dlang.

### PR DESCRIPTION
**Pull request by MikeWey**
Add the `compiles` and `has_multi_arguments` to the DCompiler objects, so we can check for supported arguments when using dlang.

One thing to note is that `dependency.get_compile_args()` usually results in arguments the D compiler doesn't support, but that currently also happens when using a `build_target` with a dependency.

### CODE REVIEW

**Comment by jpakkane** [comment]
Looks nice, but the test need some work. The current tests just call the function but do not check the outcome. The tests should assert that the return value is true and there should also be a test for a compiler flag that none of the D compilers supports and it should assert that it returns false.

Multi args should have similar tests, currently it does not seem to have any.

Thanks,

**Comment by MikeWey** [comment]
I've updated the test case.

**Comment by jpakkane** [comment]
This should use assert and string concatenation as it makes everything simpler. The error messages should also say which test went wrong. So this:

    if not compiler.compiles('int i;')
      error(''.join(['compiles is broken for d compiler: ', compiler.get_id()]))
    endif

becomes this:

    assert(compiler.compiles('int i;'), 'Basic code test does not comple: ' + compiler.get_id())

And so on for the other tests. Thanks.

**Comment by MikeWey** [comment]
Done.

**Comment by jpakkane** [comment]
Thanks.

**Pull request merged**
