### PR TITLE
Extract MachineFile code to its own file

### PR DESCRIPTION
**Pull request by jpakkane**
Standalone part of the optionrefactor branch.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I haven't been closely following that branch -- what's the advantage of splitting it out into its own file?

**Comment by jpakkane** [comment]
Twofold, really. Firstly it is a large enough of a piece to be in its own file rather than being buried in existing files.

Secondly the current code works by converting everything option-like into option objects as quickly as possibly and then joining those together. This means that options lose the information of where they came from which is needed for some operations in the new code. The new code rearranges options so that they stay in the "original data" format and are only converted to actual values in one, specific location. Basically "given that command line arguments were X, meson.build files say Y and native files say Z, what should be the value of option W at this point".

Debugging the logic currently is very difficult, because the decisions are splattered around the code base and original "ground truth" is lost. With this we keep that information.

**Comment by eli-schwartz** [comment]
> Twofold, really. Firstly it is a large enough of a piece to be in its own file rather than being buried in existing files.

Ehhh I don't really think so. It's a hundred lines -- it doesn't need to be its own file. If every hundred lines were their own file we would spend more time stat'ing and opening files on the filesystem than actually computing a configuration. And I've done a lot of work on reducing both how much code gets evaluated on startup, and the number of files imported on startup.



> Debugging the logic currently is very difficult, because the decisions are splattered around the code base and original "ground truth" is lost. With this we keep that information.

Maybe I'm missing something, but doesn't all the logic you moved come from the same place?

**Comment by jpakkane** [comment]
> Maybe I'm missing something, but doesn't all the logic you moved come from the same place?

Yes. But this is only a preparatory change. Other changes will come later.

Another advantage of keeping this standalone and isolated is that you can make the implementation and API such that you can write unit tests that use that directly rather than having to write a full project for it. Both of these types of tests are needed, but currently we can really only do the latter type, which does have its downsides (mostly that running them is slow).

**Pull request merged**
