### PR TITLE
Support for nested subprojects

### PR DESCRIPTION
**Pull request by meisenzahl**
As discussed in #422, it would be nice if you could build nested projects. This is an initial implementation.

I tested it with nested subprojects that use `.wrap` files: https://github.com/meisenzahl/meson-dependency-test

The question is whether nested projects in this form should be built by default or whether you can optionally enable the behavior via configuration.

I look forward to feedback.

### CODE REVIEW

**Comment by jpakkane** [comment]
As is said in the bug report, nested subprojects will _not_ be supported. They are fundamentally unreliable. Subprojects to be used _must_ be in the top level subprojects directory.

**Comment by xclaesse** [comment]
I think we should allow something like nested search for .wrap files. It's really annoying to have to `meson wrap promote` everything to the parent project. Then the actual checkout all goes to master's `subporject/` dir. Something along those lines.

**Comment by meisenzahl** [comment]
Would it be possible to support nested subprojects as configurable option?

Especially for monorepos, where you encapsulate external libraries in your own modules, support for nested subprojects would be very helpful.

**Comment by xclaesse** [comment]
A concrete use-case I face last week, when building GStreamer I have that chain of subprojects:

  gst-build -> gst-plugins-good -> libsoup ->sqlite3

sqlite3 is an internal dependency of libsoup, it has at first sight nothing to do with GStreamer. It's annoying to have to promote the .wrap to gst-build.

**Comment by xclaesse** [comment]
What I would suggest:
1) Check if the .wrap exists in master project. If it does, then just use that one.
2) If master project does not have a .wrap, then check if one and only one subproject has it, recursively. If only one is found, then use it.
3) If more than one subproject (or sub-sub-...-project) has that .wrap, then make an error and tell user that he has to promote one to master project to solve the conflict.

**Comment by meisenzahl** [comment]
That sounds reasonable to me. I could implement it that way.

@jpakkane would this procedure be okay for `.wrap` files?

**Comment by dcbaker** [comment]
It sounds like what @xclaesse is proposing is automatic promotion, ie, if you have subproject A that requires subproject B as long as B is unambiguous meson could automatically promote B? I haven't thought about it too hard, but that seems like a reasonable thing to do to me. I'd be fine bailing in a case where there is any ambiguity at all with an error message.

**Comment by Qix-** [comment]
> As is said in the bug report, nested subprojects will not be supported. They are fundamentally unreliable.

# THIS MAKES NO SENSE.

You have chosen not to respond to any of the points I made in the other issue, you're simply refusing to even entertain the issue.



> Subprojects to be used must be in the top level subprojects directory.

**Comment by dcbaker** [comment]
@Qix-, I understand that you disagree with our decision not to have nested dependencies, and that you're frustrated that you aren't winning us over. You are free to not like our decision, and you're free to not use meson because you don't like it's design goals. I think that Jussi's explanation in the linked bug was clear, as is your position that we're wrong.

Please refrain from using degrading names like "dog" here, it's insulting and doesn't reflect well on you.

**Comment by nioncode** [comment]
> It sounds like what @xclaesse is proposing is automatic promotion, ie, if you have subproject A that requires subproject B as long as B is unambiguous meson could automatically promote B? I haven't thought about it too hard, but that seems like a reasonable thing to do to me. I'd be fine bailing in a case where there is any ambiguity at all with an error message.

Just wanted to chime in as original author of the linked issue. This promotion will happen automatically during configuration time and not put a .wrap file in the parent or something, correct? Also, this should work for all types of subprojects, not just ones that are defined through wrap files.

E.g. I have the following layout:
```
app/subprojects/lib/subprojects/internal-lib-foo
app/subprojects/other-lib/subprojects/internal-lib-bar
```
And `app/meson.build` would have only `lib` and `other-lib` listed as subproject. Since `app` does not care about `internal-lib-foo` or `internal-lib-bar` they can be safely used when resolving the subprojects as long as there is no conflicting subproject in the tree.

Imo, this is a fairly trivial change. Subprojects simply get resolved recursively and if there are any conflicts, meson errors out. One of the subprojects with the same name must then be promoted to the parent to resolve the conflict: a subproject defined in the parent project always wins.

To simplify the promotion, we should also support something like: `subproject('third-lib/internal-lib-foo', overrides: 'lib/internal-lib-foo')`, which would allow the subproject of third-lib to override the subproject of `internal-lib-foo` and resolve both to the same subproject (both names don't even have to be identical, which would allow to resolve two subprojects of a different name to resolve to the same actual subproject).

**Comment by Qix-** [comment]
@dcbaker Jussi's explanation dismissed every single point **multiple people** have made in the other thread. It's actually frustrating at this point - nobody chooses to respond, they just seem to dismiss.

> You are free to not like our decision

Because your decision hasn't been justified, it hasn't been explained, it hasn't acknowledged anyone's concerns and what's worse is that you're basically telling users "you're stupid, we're smart" by dismissing legitimate concerns with your bizarre dogmatic approach to software.

Jussi's explanation hand waved away a laundry list of crucial points without addressing a single one of them. Your team seems to be adamantly against nested submodules but nobody seems to know why. This is absolute madness.

I'm never going to use Meson again. My frustration comes when I have to consume projects that are built by Meson. I'll have little choice in the matter and now I'll have to jerry-rig those projects into my own.

Your bad decisions affect not only your users.

**Pull request closed without merging**
