### PR TITLE
tests: disable Dlang tests on windows

### PR DESCRIPTION
**Pull request by dcbaker**
These don't work and no one has fixed them. When I've tried to
download dmd for windows I can't get a valid installer from their
website. Let's at least turn the CI green.

### CODE REVIEW

**Comment by dcbaker** [comment]
@jpakkane, @nirbheek. Opinions?

**Comment by jpakkane** [comment]
There's not much else we can do.

**Comment by TheQwertiest** [comment]
Thank you!

**Comment by nirbheek** [comment]
The next time someone shows up wanting to fix something with D on Windows we can ask them to look at it!

**Comment by GoaLitiuM** [comment]
Did you ever consider asking the person who enabled the D tests for Windows to maybe take a look at it? 🙄

**Pull request merged**
