### PR TITLE
configure_file: Add a new action 'copy'

### PR DESCRIPTION
**Pull request by nirbheek**
This will copy the file to the build directory without trying to read it or substitute values into it.

Also do this optimization if an empty `configuration_data()` object is passed to the `configuration:` kwarg, and print a warning about it. The purpose of this is to make the new action discoverable.

Closes https://github.com/mesonbuild/meson/issues/1542

It seemed a waste to create a new top-level function just for copying files, and it seemed like people would misunderstand its purpose anyway — they might expect to use it to copy files to/from arbitrary locations. We are also not sure what other use-cases people might have that are 'adjacent' to copying files from the srcdir to builddir, so this is probably the best place to add it right now.

We can deprecate it later if we feel it fits better somewhere else.

### CODE REVIEW

**Comment by infirit** [comment]
I fail to see how a copy option supersedes #3135. #3135 is __not__ about copying but actually configuring a non utf8 file.

**Comment by nirbheek** [comment]
@infirit sorry, my bad. I thought the issue was that using `configure_file()` to copy binary data to the build directory was failing due to the encoding. Corrected the description.

**Comment by jpakkane** [comment]
Let's get this in. Needs doc updates and changing 0.46.0 to 0.47.0.

**Comment by nirbheek** [comment]
Done. Doc looks ok?

**Pull request merged**
