### PR TITLE
Fix custom_target whose input is extract_objects of generated sources

### PR DESCRIPTION
**Pull request by bonzini**
Fix yet another extract_objects corner case.  This time however the fix is generic and removes some ugly hooking from build.py to the backend. Crossing fingers that it works on Xcode and VS...

### CODE REVIEW

**Comment by anarazel** [comment]
I suspect this would fix #10394

**Comment by bonzini** [comment]
Yes it's the same backtrace. Are Postgres and QEMU discovering the same tricks at the same time? :)

**Comment by anarazel** [comment]
> Yes it's the same backtrace. Are Postgres and QEMU discovering the same tricks at the same time? :)

Or maybe rather hitting the same meson limitations, requiring workaround like extract_objects...

**Comment by bonzini** [comment]
I think it's different based on your bug report, QEMU is using the .o file names just as a key for compile_commands.json lookup. But in general it does look like static_library()+extract_objects() is a common escape hatch.

**Comment by bonzini** [comment]
Failure is due to Win2k16 brownout

**Comment by bonzini** [comment]
Ping @jpakkane.

**Pull request merged**
