### PR TITLE
Replace Unix shell commands with scripts.

### PR DESCRIPTION
**Pull request by jpakkane**
This has been around for years. It started failing now. No idea why.

### CODE REVIEW

**Comment by xclaesse** [comment]
OOC, could you link to a failed CI job please?

**Comment by eli-schwartz** [comment]
POSIX requires that these commands be available as binaries in e.g. /usr/bin for exactly situations like this. Though, it's possible there are distros that fail to provide these. (The GNU coreutils will install these binaries, though...)

**Comment by jpakkane** [comment]
It's Windows, so no.

**Comment by eli-schwartz** [comment]
Woah. And these weren't unix-specific tests or run inside msys2 or cygwin???

**Comment by jpakkane** [comment]
Because of this we have a specific rule that no test cases are are allowed to use Unix shell tools. Probably the CI machines have some unixy toolset installed and it got picked up.

**Comment by xclaesse** [comment]
I think that test never worked on Windows. What changed recently is that Meson does `find_program('echo')` that now fails at configure time instead of blindly using `'echo'` string in the command and fail at run time.

**Comment by xclaesse** [comment]
Test program with a simple `run_target('plop', command: 'echo')`.

Meson 0.56.0 fails at run time:
```
PS C:\Users\Collabora\xclaesse\meson-test> python ../meson/meson.py build --wipe
The Meson build system
Version: 0.56.0
Source dir: C:\Users\Collabora\xclaesse\meson-test
Build dir: C:\Users\Collabora\xclaesse\meson-test\build
Build type: native build
Project name: manytests
Project version: 0.1
C compiler for the host machine: cl (msvc 19.28.29336 "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64")
C linker for the host machine: link link 14.28.29336.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.0 at C:\ProgramData\chocolatey\bin\ninja.EXE
PS C:\Users\Collabora\xclaesse\meson-test> ninja -C build plop
ninja: Entering directory `build'
[0/1] Running external command plop
Could not execute command "echo". File not found.
FAILED: meson-plop
"C:\Python38\python.exe" "C:\Users\Collabora\xclaesse\meson\meson.py" "--internal" "commandrunner" "C:\Users\Collabora\xclaesse\meson-test" "C:\Users\Collabora\xclaesse\meson-test\build" "" "C:\Python38\python.exe" "C:\Users\Collabora\xclaesse\meson\meson.py" "echo"
ninja: build stopped: subcommand failed.
```
Meson master fails at configure time:
```
PS C:\Users\Collabora\xclaesse\meson-test> python ../meson/meson.py build --wipe
The Meson build system
Version: 0.57.999
Source dir: C:\Users\Collabora\xclaesse\meson-test
Build dir: C:\Users\Collabora\xclaesse\meson-test\build
Build type: native build
Project name: manytests
Project version: 0.1
C compiler for the host machine: cl (msvc 19.28.29336 "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64")
C linker for the host machine: link link 14.28.29336.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program echo found: NO

meson.build:5:0: ERROR: Program 'echo' not found
```

**Pull request merged**
