### PR TITLE
ifort windows fixes

### PR DESCRIPTION
**Pull request by TyBalduf**
Fixes builds on certain msys2/mingw64 setups.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Could you be more descriptive in the commit message about what issues this is fixing? :)

**Comment by TyBalduf** [comment]
I'm going to open a separate pull request explaining things better. I was proposing a pull from an old fix made by a coworker, but I should have clarified the description before trying to merge it.

**Comment by eli-schwartz** [comment]
You can just update the commit message by force-pushing. :)

**Comment by TyBalduf** [comment]
@eli-schwartz just seeing your reply now. I made a [new pull request](https://github.com/mesonbuild/meson/pull/10493). This one is from my own fork, so I have a bit more flexibility in making any edits needed.

**Comment by eli-schwartz** [comment]
> This one is from my own fork, so I have a bit more flexibility in making any edits needed.

Ha, fair point, that's a great reason to submit a new one.

**Comment by eli-schwartz** [comment]
> I was proposing a pull from an old fix made by a coworker

If there's substantial changes involved (which to be fair the new PR doesn't seem to be particularly, but OTOH some would say "better safe than sorry", though perhaps there are others -- I notice the fpp change isn't included?) you can add git tags at the end of the commit message:

```
Co-authored-by: name <name@example.com>
```

**Pull request closed without merging**
