### PR TITLE
pkgconfig module: automatic add external library in Libs.

### PR DESCRIPTION
**Pull request by KrullKorg**

### CODE REVIEW

**Comment by tp-m** [comment]
Shouldn't these be pulled in usually by setting dependencies in the pkg-config file as pkg-config module?

**Comment by KrullKorg** [comment]
not if it is an ExternalLibrary, for example if it is a dependency returned by compiler.find_library

**Comment by jpakkane** [comment]
I did some testing with linkers and it seems that if you build a shared library X and link it against another library Y (that comes via find_library), you don't need to specify Y when linking an application that uses X. You do need it if the application uses Y directly but then it needs to set it up by itself anyway.

Can you give an real world example of where the current way fails?

**Comment by KrullKorg** [comment]
i haven't an example, i didn't test linkers; i simply usually add in pkg-config file each library my library depends on; but if it works as you tested, why "pkg-config --libs" returns each library in "Requires"?

**Comment by jpakkane** [comment]
Probably people do that just to be sure (or maybe some platforms do require it). However we should not put all libraries there randomly because that is inefficient and may cause some weird issues.

**Comment by KrullKorg** [comment]
therefore, it can be useful to be able to add ExternalLibrary to "Libs"

without "automatism" the pkgconfig module is quite useless, because if i need to write too much "meson code" it takes me less to write the pkg-config file by hand

**Comment by jpakkane** [comment]
This is a bit old MR and the pkg-config module has changed a lot during this time (and is changing more as we speak). Thus closing, but if this is still an issue for you, please open a bug explaining your use case and how you would want it to work. Thanks.

**Pull request closed without merging**
