### PR TITLE
Add Azure pipelines CI

### PR DESCRIPTION
**Pull request by jon-turney**
See #4154 

Sample run https://dev.azure.com/admin0564/meson/_build/results?buildId=54&view=logs

### CODE REVIEW

**Comment by jpakkane** [comment]
Is there a page similar to appveyor that has the full build matrix and pass/fail/duration for each of them? I could not find one.

**Comment by jpakkane** [comment]
What is the goal for this PR and the future? Specifically:

 - is it ready to merge
 - is there anything extra needed to tie it to pull requests
 - will we remove one or more Appveyor jobs once this is in
 - are there other issues that need to be changed before the transition is complete

**Comment by jon-turney** [comment]
> * is it ready to merge

Yes
 
> * is there anything extra needed to tie it to pull requests

* install azure pipelines through github marketplace
* create an account 
* create an organization (e.g. meson)
* create a new build pipeline, selecting the meson repository

> * will we remove one or more Appveyor jobs once this is in

I would suggest we leave it for some period (a week or so?), in case problems emerge, then the vc2017x64ninja and vc2017x64vs jobs can be removed from appeveyor.

> * are there other issues that need to be changed before the transition is complete

Not that I am aware of.

**Comment by jpakkane** [comment]
The pipeline setup requires a template selection. There are dozens of them. Which one should I pick?

**Comment by jon-turney** [comment]
> The pipeline setup requires a template selection. There are dozens of them. Which one should I pick?

If there is a azure-pipelines.yml already in the repository, it should notice it and not make you to use a template.

Otherwise, after choosing a template, it will ask you if you want to create a branch or commit that template to master (this seems  a bit of a weird workflow). I guess you could choose the minimal starter template on a branch and then merge my branch to that branch

**Comment by jpakkane** [comment]
Basic build [succeeded at least.](https://dev.azure.com/jussi0947/jussi/_build/results?buildId=2&view=logs) Dunno if it works with pull requests yet.

**Comment by jpakkane** [comment]
The documentation on enabling PR builds leaves things to be desired to say the least. It basically just says "use the designer" but there is nothing like that anywhere on the web UI. :(

**Comment by jon-turney** [comment]
> The documentation on enabling PR builds leaves things to be desired to say the least. It basically just says "use the designer" but there is nothing like that anywhere on the web UI. :(

The settings are under "Triggers" if you "Edit" the build pipeline.

But yes.

**Comment by jpakkane** [comment]
Okay, it seems to be enabled. It did not trigger a build when I merged a branch but according to some documentation it is expected to do that. Now to find where they have stashed the build status badge urls. Googl searches only come up with PRs that add them to other repos, but no instruction pages on where to get the link for your own projec.t

**Comment by jon-turney** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github#validate-contributions-from-forks

https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts#get-the-status-badge

**Comment by jpakkane** [comment]
Pull requests [are not working](https://github.com/mesonbuild/meson/pull/4368). :(

**Comment by tp-m** [comment]
I think this addition:
```
diff --git a/.gitattributes b/.gitattributes
index de66d2ba..5c53af99 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,3 +1,3 @@
 .gitignore export-ignore
 .gitattributes export-ignore
-
+* text eol=lf
```

may not have been quite right? I now get git warnings about carriage returns in .png files, e.g.:

```
tpm@xps:~/Devel/meson$ git diff
warning: CRLF will be replaced by LF in docs/markdown/images/buildtime.png.
The file will have its original line endings in your working directory
(repeated for all files)
```

**Comment by jon-turney** [comment]
> Pull requests [are not working](https://github.com/mesonbuild/meson/pull/4368). :(

It doesn't look like pushes are triggering builds either.

Are the azure webhooks installed for the meson repository?

**Comment by jon-turney** [comment]
> ```
> +* text eol=lf
> ```
> 
> may not have been quite right? I now get git warnings about carriage returns in .png files, e.g.:

I'm not able to reproduce this.  But maybe this needs a `*.png -text` line as well?

**Pull request merged**
