### PR TITLE
Fix cross test and run them if a cross compiler is available.

### PR DESCRIPTION
**Pull request by jpakkane**
Needs the pending cross fixes to actually work.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
⚔conflicts!

**Comment by jpakkane** [comment]
Fixed. Was on my OSX machine, though, so could not test if it works. Travis will tell.

**Comment by QuLogic** [comment]
Which build is actually running these tests?

**Comment by jpakkane** [comment]
Travis Linux builds.

**Comment by QuLogic** [comment]
Well, yes, but on the ones that show it, "Total passed/failed/skipped cross tests" is 0. There's also the "Running cross compilation tests." line, but nothing is printed after that, so it's not clear if it passed or just nothing happened.

**Comment by jpakkane** [comment]
So it does. Need to fix that.

**Pull request merged**
