### PR TITLE
mtest: asynchronous TAP parsing, improved progress report

### PR DESCRIPTION
**Pull request by bonzini**
The next part after #8001. Adds:
* to the progress report a clock and, for TAP tests, the number of passed+run subtests.
* to the final test report for TAP tests, the number of subtests that have passed.

[Demo available here](https://asciinema.org/a/LIimxKSIyh8TNwq9U076vq0WU).

### CODE REVIEW

**Comment by jpakkane** [comment]
Sorry for the delay in reviewing, but there is a lot of stuff in this one. 👍

Overall it looks nice, but there are minor issues in the formatting that jump at me. Specifically the alignments:

```
85/86 qemu:unit / test-char                           OK             5.47s (38 tests passed)                           
86/86 qemu:unit / ptimer-test                         OK             12.90s (528 tests passed)   
```

The times and numbers of tests run do not line up, which makes the output unpleasant to read. Come to think of it, the parentheses seem to be a bit superfluous as well. Maybe something like this instead:

```
85/86 qemu:unit / test-char                           OK              5.47s   38 subtests passed
86/86 qemu:unit / ptimer-test                         OK             12.90s  528 subtests passed
```

That is, pad the time with spaces to tens of seconds and the test count to hundreds. I'm guessing tests that take more than 99 seconds are rare as are tests that have more than 999 subtests.

**Comment by bonzini** [comment]
The parentheses (and left justification of the number of tests) are there because they align with the `(killed by signal)` message (also demonstrated in the asciinema recording).

Padding the time is a good idea, but the formatting is the same as in current Meson master. Should I open a separate pull request for it or modify this one? I guess it depends also on the fate of #7860 since I'm waiting for that one before rebasing again.

**Comment by jpakkane** [comment]
> Should I open a separate pull request for it or modify this one? 

You can put it in this one. No need to complicate things needlessly.

**Comment by bonzini** [comment]
For now I have only rebased on top of the Rust module, I'll add the alignment tweak next.

**Comment by bonzini** [comment]
The LGTM failure is for `NamedTuple`, which is from the `typing` module. I can use it as `T.NamedTuple` but it's uglier than just using the class name.

**Comment by dcbaker** [comment]
Please don't double import it, `T.` is not a lot of typing anyway.

**Comment by bonzini** [comment]
Ok, it was more a matter of looking untidy than extra typing. I'll fix it.

**Comment by dcbaker** [comment]
I don't think using namespaces is untidy, I tend to view polluting the local exported namespace as worse. Probably because I'm primarily a python programmer and think about things like that, lol

**Comment by eli-schwartz** [comment]
> Ok, it was more a matter of looking untidy than extra typing. I'll fix it.

What's really untidy is going against the project coding style for a couple of lines while being surrounded by lines of a different, conflicting coding style in the same file and class. :p

**Comment by jpakkane** [comment]
LGTM, are there still things that people want to see fixed?

**Pull request merged**
