### PR TITLE
Add cc.get_export_dynamic_link_args()

### PR DESCRIPTION
**Pull request by xclaesse**
This is needed by glib to expose in gmodule-export-2.0.pc.

### CODE REVIEW

**Comment by jpakkane** [comment]
Instead of exposing the flags to everyone, could we instead add a kwarg like `export_dynamic` or something like that to actually do the magic behind the scenes?

**Comment by xclaesse** [comment]
Could be added in pkg.generate() API but that seems awfully specific method just for glib. A method on the compiler seems more natural to me and could be useful to other use cases, even if I couldn't think about one now.

**Comment by jpakkane** [comment]
For comparison, would the following work for you in all cases:

    if cc.has_link_argument('-rdynamic')
      ldflags_to_put_in_pc_file += '-rdynamic'
    endif

**Comment by xclaesse** [comment]
We can always do it manually of course. The point here is meson already know what flag to pass for each compiler/platform to implement `executable(export_dynamic:true)`, so better use those same flags to not duplicate them. Autotools also expose it in its default variables.

**Comment by jpakkane** [comment]
Well yes. But the thing that concerns me here is that we are getting into very specific an niche use cases. Adding a top level function that will only be used by a few projects in the entire world is heading deeply in the death-by-a-thousand-paper-cuts territory.

In theory we could add a more generic function, something like:

    args = cc.get_linker_flags_for_feature('export-dynamic')

which could then be used more generally, but that requires more use cases than just this one.

This has also the very unfortunate downside that people _will_ start doing something stupid like this:

    executable(..., link_args : cc.get_linker_flags_for_feature('export-dynamic'))

rather than:

    executable(..., export_dynamic : true)

You may laugh, but every feature we have that can be used in a similar way has been used in exactly that incorrect way, even if we specifically tell people not to. This makes Meson look bad because  if they see the former being used they will think that is how Meson should be used and the syntax on that just looks awful.

**Comment by xclaesse** [comment]
Could add a warning in executable() if it finds export-dynamic in link_args. That would be good in any case since export_dynamic:true is pretty new and I'm sure many projects already passed that flag manually.

**Comment by xclaesse** [comment]
> jpakkane (IRC) In that format it won't be accepted. As part of a more general solution, maybe, but it needs more real world use cases.

I personally disagree with that decision, but let's abandon this PR then.

**Pull request closed without merging**
