### PR TITLE
Add dependency('lapack') for several configurations

### PR DESCRIPTION
**Pull request by scivision**
LAPACK is one of the most widely used numerical libraries for linear algebra.
We use PkgConfig to find Lapack across operating systems, compiler vendors and lapack vendors.

This is a library where CMake often has trouble, leading users (including myself) to write their own [FindLapack.cmake](https://github.com/scivision/lapack-cmake/blob/master/cmake/Modules/FindLAPACK.cmake).

### CODE REVIEW

**Comment by QuLogic** [comment]
What about OpenBLAS?

**Comment by scivision** [comment]
@QuLogic for MKL and Atlas, Blas is part of those packages.
For Netlib Lapack, OpenBLAS is used via PkgConfig

**Comment by QuLogic** [comment]
I guess I don't understand the module naming; why does netlib find OpenBLAS?

**Comment by scivision** [comment]
Blas does fundamental linear algebra operations like matrix multiply. Lapack does intermediate linear algebra operations like SVD, some of which require Blas operations.
High performance Lapack implementations like MKL and Atlas include their own Blas.

There are a lot of possible combinations of these libraries, but I think most users want it to "just work".

**Comment by jpakkane** [comment]
I agree that `modules` is not really a good name for this use case. It is meant for selecting a subset of a large dependency, whereas this selects an implementation of lapack. So this would make more sense as:

```meson
d = dependency('lapack', provider: 'atlas')
```

or just plain

```meson
d = dependency('mkl')
d2 = dependency('atlas')
d3 = dependency('netlib')
```

**Comment by scivision** [comment]
A dependency could be requested either way. I think the end user mostly knows they want Lapack. The idea here is to set the right linking options for them automatically, rather than like CMake make the end user figure it out.

The approach I'm taking is to help abstract away details but still give user full choice of vendor. Another PR could give additionally the opposite approach, to select by vendor, module instead of as I did here. The two approaches could share internal Python functions.

With the present approach, the end user can do a simple foreach that requests Lapack in order of preference (high performance first, falling back to other implementations).

**Comment by jpakkane** [comment]
A thing that has been considered is to make `dependency` accept many names just like `find_program` does. Then you'd do:

```meson
lapack_dep = dependency('mkl', 'atlas', 'netlib')
```

and it would pick the first one that can be found.

**Comment by scivision** [comment]
That's a neat compact way to have fallbacks, and still allows for explicit in specification when wanted.
I can workaround this for now with cmake, if there were a way to pass "components" to make from meson..

**Comment by scivision** [comment]
I think this PR should be rethought of in light of new ways to interact with CMake; it may not be prudent to reinvent logic that took a lot of effort to make in CMake in Meson. That is, it may be best (if not as fast, but more robust and lower maintenance burden) to use CMake from Meson to find Lapack instead.

**Pull request closed without merging**
