### PR TITLE
gettext: Add update-po target

### PR DESCRIPTION
**Pull request by TingPing**
~~Will need to be rebased for #916 but still~~ open for comments.

### CODE REVIEW

**Comment by nirbheek** [comment]
Please add an explanation of what this target does to the commit message.

**Comment by TingPing** [comment]
It.. updates po files, but I can expand on that I suppose.

**Comment by tp-m** [comment]
I get:
```
tpm@xps:~/gst-meson/gstreamer/build$ ninja gstreamer-1.0-update-po
[0/1] 'Running external command gstreamer-1.0-update-po.'
Traceback (most recent call last):
  File "/home/tpm/Devel/meson/meson.py", line 26, in <module>
    sys.exit(main())
  File "/home/tpm/Devel/meson/meson.py", line 23, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/home/tpm/Devel/meson/mesonbuild/mesonmain.py", line 245, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/tpm/Devel/meson/mesonbuild/mesonmain.py", line 235, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/tpm/Devel/meson/mesonbuild/scripts/gettext.py", line 75, in run
    datadirs = args[3][11:] if args[3].startswith('--datadirs=') else None
IndexError: list index out of range
FAILED: gstreamer-1.0-update-po 
'/usr/bin/python3' '/home/tpm/Devel/meson/meson.py' '--internal' 'commandrunner' '/home/tpm/gst-meson/gstreamer' '/home/tpm/gst-meson/gstreamer/build' 'po' '/usr/bin/python3' '/home/tpm/Devel/meson/meson.py' '--internal' 'gettext' 'update_po' 'gstreamer-1.0' 'af@@az@@be@@bg@@ca@@cs@@da@@de@@el@@en_GB@@eo@@es@@eu@@fi@@fr@@gl@@hr@@hu@@id@@it@@ja@@lt@@nb@@nl@@pl@@pt_BR@@ro@@ru@@rw@@sk@@sl@@sq@@sr@@sv@@tr@@uk@@vi@@zh_CN@@zh_TW'
```

**Comment by TingPing** [comment]
@tp-m Give me a few and I'll convert that file to use `argparse` instead of the ugly manual handling.

**Pull request merged**
