### PR TITLE
mtest: improvements to logging

### PR DESCRIPTION
**Pull request by bonzini**
This pull requests includes several improvements to logging. In particular:
* in --verbose mode, the JSON and text file logs now include the output of the tests
* also in --verbose mode, the console log (similar to ninja) does not mix the output of multiple tests that are being run in parallel
* the console log and the text file log employ slightly different formatting, so that each medium gets the best readability
* the error logs for --print-errorlogs are emitted during the first part of the output, and not limited to 10 tests anymore.

### CODE REVIEW

**Comment by bonzini** [comment]
Some examples of the new-style verbose logging: [parallel](https://asciinema.org/a/qYHQSBRjZIYvwrYNVmugzGeu4), [--num-processes 1](https://asciinema.org/a/IJ4etyLDCqsTWrAMrt1x5VW6n), [--print-errorlogs](https://asciinema.org/a/6Vs9FZbHj3MdGKxLxC6p4DJqg).

**Comment by bonzini** [comment]
I dropped the emoji because it failed on non-UTF8 locales. I replaced them with a colored `>>>`, which can be kept as a fallback even if emoji are added back later.

Apart from the cuteness factor, the purpose of emoji was to let people identify easily output lines with the command line, for cut-and-paste into a terminal. The `>>>` marker serves the same purpose.

**Comment by jpakkane** [comment]
The cleanups look nice. Anyone want to comment on the new output format?

**Comment by bonzini** [comment]
Ok, let me extract the cleanups so that we can fix #8212. There are other small bugfixes at the beginning of the branch.

**Comment by jpakkane** [comment]
To reiterate, this looks fine to me. If anyone has reasons why these should not be merged speak now, or forever hold your peace (or file MRs to improve the situation later).

**Pull request merged**
