### PR TITLE
Add VS2019 backend - fix #4640

### LINKED ISSUE #4640: Possible incompatibility with Visual Studio 2019 Preview (releasing in April)
After installing Visual Studio 2019 Preview, which (I suppose) upgraded the MSVC compiler, it appears that the executables produced by Meson debug builds no longer have debugging information. It also appears that they aren't debug executables, actually, because my unit tests seem to be running much too fast for debug.

I wanted to investigate what options are passed to the compiler, but on Windows the arguments are passed in a `@file`, and after ninja finishes, these files are gone.

### PR DESCRIPTION
**Pull request by XVilka**
Trying to address this issue:

https://github.com/mesonbuild/meson/issues/4640

### CODE REVIEW

**Comment by nirbheek** [comment]
Note that failures in the D tests cases on vs2017 are known, you can ignore them.

**Comment by XVilka** [comment]
So, what you have decided?

**Comment by nirbheek** [comment]
The changes LGTM. Is VS 2019 available on Azure yet? Would be nice to have CI for it. If not, I'd like to test this by hand on my machine.

**Comment by XVilka** [comment]
See https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md

**Comment by nirbheek** [comment]
Great, sounds like we can add it.

**Comment by XVilka** [comment]
See https://github.com/mesonbuild/meson/pull/5117

**Comment by XVilka** [comment]
I don't understand, why it can't find vcvarsall.bat? Hmm.

**Comment by Joshua-Ashton** [comment]
It doesn't work. 

meson.build:1:0: ERROR: Unknown backend "vs2019".

It shows up as a backend but is unusable.
Please test your work.

**Comment by XVilka** [comment]
Well, I figured it doesn't.

**Comment by Joshua-Ashton** [comment]
> 
> 
> Well, I figured it doesn't.

Why make the PR if it doesn't work... 🐸

**Comment by XVilka** [comment]
It is work in progress and I don't have Windows.

**Comment by jpakkane** [comment]
I've tagged this as "WIP". Please remove it when you think this is ready.

**Comment by jpakkane** [comment]
Created  #5252 with the rest of the changes in this MR. Closing this one.

**Pull request closed without merging**
