### PR TITLE
Interpreter: Add "in", "not in", "break", and "continue" operators

### PR DESCRIPTION
**Pull request by xclaesse**
This adds "in" keyword, which is not backward compatible change.

### CODE REVIEW

**Comment by xclaesse** [comment]
While at it, added `continue` and `break` too. If we are going to add new keywords, better do them in one shot.

**Comment by ePirat** [comment]
Test failures seem to be meson.build files where these new keywords were used as variable names.

**Comment by jpakkane** [comment]
This needs to wait until 0.48.0 is out so people have at least one release cycle to update their projects.

**Comment by nirbheek** [comment]
> This needs to wait until 0.48.0 is out so people have at least one release cycle to update their projects.

The warnings will be in the 0.47.2 stable release too, so that will also give people a bit more time.

**Comment by jpakkane** [comment]
:crossed_swords: conflicts. I'm ok with merging this for this cycle. Is there anyone who thinks it might be too aggressive?

**Comment by xclaesse** [comment]
@jpakkane Should I click the merge button, or do you think we should wait a little bit longer?

**Pull request merged**
