### PR TITLE
ci: Add Ubuntu Bionic image

### PR DESCRIPTION
**Pull request by mensinda**
Also includes some documentation fixes and additional options for skipping tests if a tool version is to old.

### CODE REVIEW

**Comment by mensinda** [comment]
About the current failures in the new image:
- `1 boost` is expected to fail until #6909 is merged
- `23 hotdoc` fails with an `UnicodeEncodeError` exception
- two `_changes_cause_rebuild` fail, which looks really concerning to me
- also `LinuxlikeTests.test_pic` fails
- `test_guessed_linker_dependencies` fails on `self.assertRebuiltTarget`

Can someone check if these errors also occur on a real system, if someone is already running Ubuntu Bionic or has a Bionic VM (or does anyone already know why the tests fail)?

Similar to #6900, `OS Comp Tests / Ubuntu Bionic` fails because it cannot test what doesn't exist yet.

**Comment by jpakkane** [comment]
Dammit, I upgrade my last Bionic machine (well, work machine) just today. I'll have to see if I have a VM image lying somwhere.

**Comment by mensinda** [comment]
Thanks, otherwise I will set up one. Let's hope I didn't discover some sort of regression :)

**Comment by jpakkane** [comment]
Hotdoc can be ignored. Nobody is using it on Bionic, it's too new for that.

**Comment by mensinda** [comment]
The pylint error is unrelated and the bionic test fails because the image does not exist yet.

**Comment by jpakkane** [comment]
I tried rerunning the tests but they still failed.

**Comment by mensinda** [comment]
@jpakkane Which test are you concerned about? The pylint failure is a known issue and `OS Comp Tests / Ubuntu Bionic (pull_request)` fails because the docker image does not exist (yet) and will only be pushed once this PR is merged.

**Pull request merged**
