### PR TITLE
cmake: fix detection of libraries with .so version

### PR DESCRIPTION
**Pull request by mensinda**
Fixes that also "../libinternalLib.so.1.2.3" is detected and used with `link_with`.

### CODE REVIEW

**Comment by xclaesse** [comment]
Hm, I already did a fix in that commit, but judging from your test case, there are different ways of setting the SOVERISON? https://github.com/mesonbuild/meson/pull/5981/commits/3fd8b1db615e421371938e53b7aaecca8cca3733

**Comment by mensinda** [comment]
Apparently. If you apply 5592a28 to the current meson master, there will be an error.

**Comment by mensinda** [comment]
To be honest I had already forgotten that you fixed something similar :)

Also, your solution would have probably blown up on macOS, [similar to my first try](https://travis-ci.org/mesonbuild/meson/jobs/593077427#L3762). This is because on macOS the version is *between* the library name and the `.dynlib`. If you have nothing against it, I would revert 3fd8b1d, once the CI passes, in favor of this PR, since it fixes both `VERSION` and `SOVERSION` (and all the other properties we have missed).

**Comment by xclaesse** [comment]
You're right that your way is better. Thanks :-)

**Pull request merged**
