### PR TITLE
Hotdoc: use template for Commands.md instead of generating the entire file

### LINKED ISSUE #8061: hotdoc module generates broken "Edit on github" links
- Browse to https://mesonbuild.com/Hotdoc-module.html
- Click "Edit on github"
- Be redirected to https://github.com/mesonbuild/meson//edit/master/docs/builddir/markdown/Hotdoc-module.md
- notice "builddir/" in the url

/cc @thiblahute

### PR DESCRIPTION
**Pull request by eli-schwartz**
Fixes #8061 and is all-around cleaner IMHO.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Fixed unittests to expect the new layout...

**Comment by eli-schwartz** [comment]
Test failures are not relevant --  unittests-appleclang has clock skew, cygwin is known to be misbehaving.

**Comment by MathieuDuponchelle** [comment]
lgtm

**Comment by TheQwertiest** [comment]
Copy pasted comment: 
@eli-schwartz , can't say I agree with your changes: it now edits the file in-tree and not out-of-tree, which is not a mesonic way (and dirties the source tree).

**Comment by eli-schwartz** [comment]
I suggest you reread the PR!

Hotdoc processes an in-tree .md template, an out of tree include path, and generates an out of tree html file.

**Comment by TheQwertiest** [comment]
> I suggest you reread the PR!

My bad, I've misread `cur_bdir` as current source dir.

**Comment by eli-schwartz** [comment]
The commit diff for the gen_docs target hasn't really changed, --output-directory just had its join_paths and second component removed due to its un-mesonic use of a subdirectory for emitting outputs.

**Comment by eli-schwartz** [comment]
Rebased on master in order to grab CI improvements, because why not.

**Comment by jpakkane** [comment]
Merged and web site recreated. Report issues if any pop up.

**Pull request merged**
