### PR TITLE
Make source file names more unique.

### PR DESCRIPTION
**Pull request by jpakkane**
We currently have many duplicate base filenames (like four different `interpreter.py`s).

This is annoying. There are many tools that only show the "base" name (like IDEs in editor tabs) so you constantly have to keep checking if you are looking at the thing you expected to. Also when you get some errors and need to open a specific file and then use the "go to file" and type the filename you get multiple choices and have to go back because you already forgot which one you were supposed to open.

I propose a new coding standard whereby there can only be one Python source file with a given base name in the project source dir. This MR fixes one of them to show how it could be done.

We might need to define a new naming convention, like having all module files be named `somethingmod.py`. There are several collision between those and compilers.

### CODE REVIEW

**Comment by dcbaker** [comment]
A blanket ban on two files with the same name feels like the tail wagging the dog to me. We have folder structures for a reason, and having a clear, simple, consistent naming scheme within those folders is important. compilers/ has `<language>.py` in it currently, renaming `java.py` to `javac.py` is confusing because now it doesn't match that convention, and I am *not* in favor of having 1 python file for each compiler. 

Modules sometimes have the same name as a compiler (rust and java), but to me, at least, that isn't confusing, I'm either clearly working on compilers or on modules.

The case of the interpreters I agree is a problem. not only do we have lots of sibling directories all containing an `interpreter.py`, but we have several cases of one `interpreter.py` importing another `interpreter.py` from those sibling directories. On the other hand, we have some clearly different `interpreter.py` files, like the ones in the CMake and Cargo modules.

**Comment by jpakkane** [comment]
> javac.py is confusing because now it doesn't match that convention,

This is just a single example. Conventions can be changed.

> I am not in favor of having 1 python file for each compiler.

Of course not. Nobody is proposing that. It would be terrible.

> 'm either clearly working on compilers or on modules

This is exactly the issue. In _am_ working on all of them when doing the option refactor. I have to keep using brain power all the time to verify that I'm in the correct `interpreter.py` this time.

**Comment by dcbaker** [comment]
You're IDE doesn't differentiate? Mine notices that there are multiple files with the same name and disambiguates, like right now I have linkers/detect.py and compilers/detect.py open, and it notices and renders them as `detect.py (linkers)` and `detect.py (compilers)`

**Comment by eli-schwartz** [comment]
> This is just a single example. Conventions can be changed.

Well, the point of the convention is that when I'm working on the "java" language, I'm probably going to look in the "java" driver of the mesonbuild.compilers package.

I don't really get the convention you propose to change to, though. The logical next step after taking:
- compilers/java.py -> javac.py
- modules/java.py

is to change this:
- compilers/rust.py -> rustc.py
- modules/rust.py

Which is going to be pretty unintuitive when we add gcc-rs support.

So, if this is just an example then I'd like to hear a better example from which to derive a new convention. Personally, I agree with @dcbaker that I've never had this confusion before. My tabbed editor doesn't limit the tab names to the basename either. :)

> Also when you get some errors and need to open a specific file and then use the "go to file" and type the filename you get multiple choices and have to go back because you already forgot which one you were supposed to open.

Some editors / IDEs allow you to click on the filename in the error message and it will open the right file for you, and even send you to the right line, which is quite handy.

**Pull request closed without merging**
