### PR TITLE
[WIP] Boost: avoid non-mt version overriding mt.

### LINKED ISSUE #2436: boost log on mac os x is not using -mt variant
Hi,

the correct `-mt` version of boost_thread is chosen on mac, but not for `boost_log`. Also re-arranging the boost components did not trigger a reconfiguration, but this changes if I clean out build and rebuild.

* https://github.com/astroidmail/homebrew-astroid/blob/master/Formula/astroid.rb#L23-L24

Error:
* https://gist.github.com/yeled/30f665b228ce9e1a09338827589af4f4

### PR DESCRIPTION
**Pull request by NickeZ**
This fix has to be reviewed by someone with access to OS X. If you have the `-mt` version installed of all boost libraries please check in the ninja.build file that the `-mt` versions are picked. You can also try `dependency('boost', threading:'single')` and see if the non-`-mt` versions are picked.

I'm pretty sure the reason of the issue is that the glob expansion matched both `libboost_log.dylib` and `libboost_log-mt.dylib` and then simply the last one overrode the first one.

Fixes #2436

### CODE REVIEW

**Comment by jpakkane** [comment]
I have an OSX machine but not enough understanding of Boost usage to be able to test this properly.

**Comment by NickeZ** [comment]
I think the only complex part with boost is that if you enable features it renames the targets. This means that you can have boost installed both non-threadsafe and threadsafe. For example `libboost_log.dylib` would be non-threadsafe (`threading=single`) and `libboost_log-mt.dylib` would be threadsafe (`threading=multi`).

So to test this patch you must have both installed since the bug is that it picked boost libraries with different features, that is, it mixed `mt` with non-`mt` libraries.

To make it even more confusing, Debian and Fedora both compile with `threading=multi` but give the libraries the featureless names...

**Comment by NickeZ** [comment]
This PR probably breaks fedora so it shouldn't be merged yet

**Comment by jpakkane** [comment]
The CI machines should have Boost now. Please rebase and fix conflicts so this gets rerun.

Also, any estimates on whether this still breaks Fedora?

**Comment by NickeZ** [comment]
This might not be needed any more. Closing for now

**Pull request closed without merging**
