### PR TITLE
Improve project naming and build configuration in genvslite projects

### PR DESCRIPTION
**Pull request by RogerSanders**
This change fixes two usability issues with the genvslite project generation. Unlike when using the full VS backend, under genvslite the `ProjectName` property wasn't being set for generated projects. This means projects end up being named according to the project files, which includes suffixes like "@exe" in the solution, which is undesirable. This change adds the `ProjectName` field in for genvslite projects, to keep the naming consistent with projects under the VS backend.

Additionally, previously under genvslite, no projects were set to build under any solution configuration by default. This is inconvenient, as the user has to manually edit the build settings for each solution configuration before they can compile at the solution level. There was a note in the code to do something about this. This change enables compilation at the solution level for the default startup project in the solution, so the user can now just press F5 to build the solution and run the default startup project, as they would typically expect.

What things looked like before this change:
image

And after:
image

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> This change adds the `ProjectName` field in for genvslite projects, to keep the naming consistent with projects under the VS backend.

So if I understand correctly, when implementing genvslite, this field was erroneously factored into the non-genvslite portion. Seems like a sensible improvement.

**Comment by eli-schwartz** [comment]
I would probably include some/all of the explanatory text into the commit message as well.

**Comment by RogerSanders** [comment]
> I would probably include some/all of the explanatory text into the commit message as well.

No worries, I've updated the commit message to include the additional text.

**Comment by RogerSanders** [comment]
Anything I can do to help move this review forward?

**Review by eli-schwartz — APPROVED** [review]
Changes look reasonable and are well explained.

**Pull request merged**
