### PR TITLE
CMake module: Allow paths of generated CMake sources for include directories

### PR DESCRIPTION
**Pull request by w0xel**
Fixes: https://github.com/mesonbuild/meson/issues/7666

Meson will then just assume directories of generated files will appear during build.

### CODE REVIEW

**Comment by mensinda** [comment]
This needs a test case. You can probably add it to `test cases/cmake/8 custom command`.

**Comment by w0xel** [comment]
Your call to create a test case was right, as it always is, as explicitly creating the directory is indeed required, if the cmake-project does not do this. I also used the `${CMAKE_COMMAND} -E copy` instead of `mycpy`, as it will create the fully path required for the copy implicitly (the new meson code does only create `some`, but `some/directory` is required in the CMake project).

This test case reflects what happens in krpc.

**Comment by w0xel** [comment]
Also deleted an unnecessary newline that slipped in...

**Review by mensinda — APPROVED** [review]
LGTM, assuming the CI is green

**Pull request merged**
