### PR TITLE
Add 'b_pie' compiler option

### PR DESCRIPTION
**Pull request by xclaesse**
On Android executables must be position independent, many distributions
enable it by default too.

### CODE REVIEW

**Comment by xclaesse** [comment]
Based on a patch from ajax.

**Comment by ePirat** [comment]
> Option should probably be [false, pie, PIE]

What is the difference between `pie` and `PIE`?

**Comment by xclaesse** [comment]
> What is the difference between pie and PIE?

I've no idea actually, and I just saw the is PIC and pic, too.

**Comment by nirbheek** [comment]
Since we only support `-fPIC` in Meson, and no one has complained about missing support for `-fpic`, we should do the same for PIE and only support `-fPIE` for now.

**Comment by xclaesse** [comment]
If I understand correctly, PIC/PIE produce bigger code that works everywhere, and pic/pie produce smaller code that could fail to link on some platforms. Seems interesting to support both. At least Android seems to be using -fpie.

**Comment by nwnk** [comment]
> Option should probably be [false, pie, PIE]

I think I think so. I don't love that you might want to set this differently per architecture, but I'd rather have that than force capital PIE all the time.

> What if PIE objects from an executable are extracted and used in a shared library?

It will likely fail to link, so we shouldn't allow that. If the same source is used in both a shared library and a PIE, then either it needs to be built twice, or built just once as PIC.

> What if non-PIE objects are extracted from a shared library and used in a PIE executable?

If they were in a shared library, they were almost certainly PIC (or you're doing something gross on i386), so this would be suboptimal codegen but otherwise harmless.

> When a PIE executable links with a static library, that lib must be PIC and/or PIE?

Correct.

**Comment by xclaesse** [comment]
Ok here is an update of my patch:
- I don't think we need to worry too much about mixing pie/pic objects. If the user does weird things he'll get linker error. What matters is that by default `-Db_pie=true` works because pic is enabled by default.
- I think it's better to default to the more optimized lower case pic/pie and give the choice to the user to use upper case PIC/PIE when needed. For that I changed b_staticpic from boolean to `true`/`false`/`portable` tristate. `true` means `pic`, `portable` means `PIC`. Likewise for the new b_pie option. That change should be backward compatible I think (except we change from -fPIC to -fpic by default).

**Comment by xclaesse** [comment]
@nirbheek @jpakkane I think this is ready to be reviewed :)

**Comment by dcbaker** [comment]
Can I make your day less pleasant? ICC doesn't differentiate `-fpic` and -`fPIC`, they're the same. it also doesn't set `-fpie` by default like GCC and Clang do.

**Comment by xclaesse** [comment]
> Can I make your day less pleasant? ICC doesn't differentiate -fpic and -fPIC, they're the same.

I don't think that's a problem, as long as ICC accepts both -fpic and -fPIC. As far as I understand on most platforms `-Db_staticpic=true` and `-Db_staticpic=portable` will produce the exact same code any way.

> it also doesn't set -fpie by default like GCC and Clang do.

gcc/clang doesn't set `-fpie` by default neither (at least not Android's toolchain I tested), this PR adds it if you set `-Db_pie=true` option.

**Comment by dcbaker** [comment]
In my testing it looks like GCC and Clang do default to pie at least on recent versions. ICC fails to link a number of test in the test base that I can get GCC to fail in exactly the same way by passing -fno-pie to.

**Comment by dcbaker** [comment]
although the documentation for gcc says that it doesn't build pie by default... hmmmm

**Comment by dcbaker** [comment]
Ahh, the difference is that ICC only seems allows fPIC static libs to be linked into pie executables, not -no-pie exectuables. That's going to be annoying to fix properly, yay me.

**Comment by xclaesse** [comment]
I think distro patch gcc/clang to default to PIE, because as far as I know there is no generic way with autotools to pass "-fpie" only for executables.

**Comment by xclaesse** [comment]
> Ahh, the difference is that ICC only seems allows fPIC static libs to be linked into pie executables, not -no-pie exectuables.

Oh, so ICC is completely broken in Meson for a long time. We have been defaulting to pic for a few releases now, AFAIK.

**Comment by dcbaker** [comment]
There is a --enable-default-pie option, which seems to affect gcc itself, but not the documentation.

**Comment by dcbaker** [comment]
getting ICC all working correctly is going to be fune :)

**Comment by dcbaker** [comment]
I have a patch that just sets pie for executables with ICC, that gets things working, but I'm sure there are a lot of corners.

**Comment by xclaesse** [comment]
Anyway, all this shouldn't block this PR, we could need some follow-up PRs to fix ICC, but this PR doesn't make anything worse than before.

**Comment by xclaesse** [comment]
Maybe we should just set b_pie default to true, tbh.

**Comment by dcbaker** [comment]
I think so. I think we should have pie arguments return -fno-pie when the target isn't pie, that way no matter how the compiler is configured you always get the same results.

**Comment by jpakkane** [comment]
Picking this one up from the backlog:

> Since we only support -fPIC in Meson, and no one has complained about missing support for -fpic, we should do the same for PIE and only support -fPIE for now.

Is there a case where `-pie` would actually be needed?

**Comment by dcbaker** [comment]
-pie or -fpie?

ICC defaults to no pie of either. GCC recommends using -pie for the linker if you use -fpie. Clang also doesn't add either by default, but most distros seem to patch it. GCC has a configure option to choose pie or no pie by default.

**Comment by xclaesse** [comment]
As far as I understand -fPIE/-fPIC (upper case) works in all cases but could produce bigger executables. On some platforms -fpie/-fpic (lower case) produce smaller executable but could fail to link in some circumstances. Android toolchain uses lower case.

IMHO we should default to lower case, because better have smaller executables by default, and if you get a link error you can always change that option. But I'm fine either way.

**Comment by dcbaker** [comment]
I think the GCC manpage:

If supported for the target machine, emit position-independent code, suitable for dynamic linking and avoiding any limit on the size of the global offset table. This option makes a difference on the m68k, PowerPC and SPARC .

So I think we should actually use fPIC/fPIE if possible

**Comment by jpakkane** [comment]
If those are the only platforms where any of this matters, then we should default to PIC and PIE. Then having the lower case ones would be an optimization that people on rare platforms can enable if they so choose. This ties in with our desire to do the safe and reliable thing by default and as an added bonus this would maintain backwards compatibility since we currently default to `-fPIC`.

**Comment by xclaesse** [comment]
Ok, I'll change my PR to have -b_staticpic/-b_pie=[true, false, optimized] where true means upper-case and optimized means lower-case? Any suggestion for another name than "optimized"?

**Comment by jpakkane** [comment]
Preferably something that indicates that it is a rare and unneeded option so people don't try to enable it blindly. ("What? Optimized? Sure, I want all the optimizations! Enable! Enable! Enable!")

**Comment by ePirat** [comment]
> Preferably something that indicates that it is a rare and unneeded option

Why though? If I understand correctly, `optimized` would set `-fpie` which is what you want most of the time and `-fPIE` would be rarely needed only when `-fpie` does not work?

**Comment by jpakkane** [comment]
It's not really "optimized" in the classical sense, but rather "if you are on one of these three weirdo platforms _and_ you have a very small program _and_ you want to make it a bit faster (maybe) then use this".

The only question is Android. They use lowercase pic by default. Do we know if uppercase pic works? Asking for a friend, who is skeptical about the Android toolchain because it has traditionally done weird things.

**Comment by xclaesse** [comment]
Ok, let's add only -fPIE for now, we can always add a 3rd value to b_staticpic/b_pie to choose -fpic/-fpie later.

**Comment by dcbaker** [comment]
I asked one of my colleagues who likes less mainstream architectures. His take was that unless you're working on a bootloader, device firmware, or some equally low level component it's unlikely that you would ever want the `-fpie` or or `-fpic` version. I think we're safe to not support `-fpie` or `-fpic`.

This all seems good to me, although there should be a snippet for the release notes.

**Comment by jpakkane** [comment]
Indeed.

**Comment by xclaesse** [comment]
Added release notes snippet, and added missing documentation of the new kwarg.

**Comment by jpakkane** [comment]
Green at last!

**Pull request merged**
