### PR TITLE
New templates for Meson build.

### PR DESCRIPTION
**Pull request by michaelbadcrumble**
I saw that there was no new templates in Meson so I cooked up some for `Objective-C`, `Dlang` and `Rust`.  I simply provided  template types for `library` and `executable` to match the `-t` or `--type` flags.

I also moved the const definitions of the templates into a new package `mesonbuild.templates` to make it easier to add new project templates for languages like `Objective-C++`, `Java` and `Vala` for example.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Flake8 detected 9 issues on c9a3081e6db5d38d25493f645135df4555c79dc9
Visit https://sider.review/gh/repos/19784232/pulls/6112 to review the issues.

<sub>posted by Sider</sub>

**Comment by ignatenkobrain** [comment]
Flake8 detected 18 issues on 43b4ffb4ebb096f36059aa3dcc8691c015f7db81
Visit https://sider.review/gh/repos/19784232/pulls/6112 to review the issues.

<sub>posted by Sider</sub>

**Comment by scivision** [comment]
unless there is an objection I'm not thinking of off-hand, I think this is a nice modularization.

As a note to self, after this PR is accepted I would then like to do in the future:

* add Fortran template
* update some of the Python 2.x syntax (make it cleaner since we assume Python > 3.5)
* add type annotation

**Comment by michaelbadcrumble** [comment]
Got it.  I will get on that for the next PR when adding Fortran, Objective-c++ and Java.

**Comment by michaelbadcrumble** [comment]
Got it.  I will get on that for the next PR when adding Fortran, Objective-c++ and Java.

**Comment by jpakkane** [comment]
Please update the `test_templates` method in `run_unittests.py` so that the tests are run for all languages.

**Comment by michaelbadcrumble** [comment]
@jpakkane and @scivision I am not sure what to make of this.

**Comment by jpakkane** [comment]
One of the log messages is this:

```
Using "tmpl620qo_u" (project name) as name of executable to build.
No recognizable source files found.
Run me in an empty directory to create a sample project.
```

So something wrong with the invocation maybe? D tests pass, so this would seem to be a problem with the Rust project.

Also, you probably need to check if a compiler for each given language exists before trying to generate the project. They are not all available on all platforms.

**Comment by michaelbadcrumble** [comment]
I can look into swiping Rust for something else.  What language can I swop Rust for that targets platforms missed my Rust?

**Comment by scivision** [comment]
Because of the burden of putting each and every library and compiler in, not every CI build used by Meson has every such test. In this case, as long as Rust is tested on one of the CI's, maybe that's sufficient.

It may be that jpakkane would have to  add Rust to one of the CI Docker images to check this? Or as you suggest, another language that's already on a CI Docker image used by Meson .

**Comment by scivision** [comment]
Fortran is one of the languages already on the Meson CI images if you did want to swap languages :-)

**Comment by scivision** [comment]
@michaelbadcrumble here is a commit adding Fortran template to your work:

https://github.com/scivision/meson/commit/1b7c1d4918176004e36d5c27ee3723a652c97ec0

**Comment by michaelbadcrumble** [comment]
Sorry it looks like I’m going to be helping the fam for most of the day maybe I can just open a new pull request later with Objective-c, Dlang and as suggested Fortran if that’s ok.

**Comment by scivision** [comment]
@michaelbadcrumble I think if you incorporate scivision@1b7c1d4 into your branch it will work. Oh, I forgot to remove 'rust' from run_project_tests.py

**Comment by scivision** [comment]
replaced by #6121

**Pull request closed without merging**
