### PR TITLE
aix: avoid -bsvr4 flag

### PR DESCRIPTION
**Pull request by peterh**
The svr4 linker flag causes issues, especially when compiling c++.
Replace `-z` options with the equivalent non-svr4 flags. When using
`-blibpath`, we must be careful to include the default system library
path, or the resulting executables will not be able to find libc.

This patch was suggested by @andreaskem in #7581.

### CODE REVIEW

**Comment by andreaskem** [comment]
Thank you very much for preparing this MR, I unfortunately got distracted along the way.

I tested this change and successfully built C++ and C executables on AIX 7.2.5 using GCC 8.3 from the Linux toolbox. The original issue I mentioned no longer occurs and these executables appear to function normally.

I encountered two other issues. Firstly, dependencies found via pkconf do not have their library path added to the `libpath` but this is most likely unrelated to this MR or AIX support in general. I might just misunderstand how this mechanism is supposed to work. Secondly, GCC seems to add `/opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8/../../..` on its search path automatically before the paths added by the user. If I link e.g., `libxml2` using `find_library`, the flag `-lxml2` is placed on the linker command line. GCC then links `/opt/freeware/lib/libxml2.a` but with `libpath` looking like `/usr/lib:/lib:/opt/freeware/lib:...`, the library `/usr/lib/libxml2.a` is used at runtime leading to errors like
```
        0509-136   Symbol _GLOBAL__AIXI_libxml2_so (number 979) is not exported from
                   dependent module /usr/lib/libxml2.a(libxml2.so.2).
```
This can be worked around by `LIBPATH=/opt/freeware/lib`. Should `/opt/freeware/lib` be placed first if GCC is used to link? Not sure how this is should to work because I cannot quite wrap my head around how the `/opt/freeware/lib` stuff is supposed to be integrated in general, on AIX.

**Comment by peterh** [comment]
Hmm. In general, I want to use the /usr/lib libraries, not the /opt/freeware/lib libraries, even when building with gcc. I suspect we should be picking up the library path at configure time, not hard coding it to /lib:/usr/lib:/opt/freeware/lib (or any other ordering).

The docs say that if you omit libpath, it adds all the -L values. But then how do we specify the rpath?

I'll dig deeper and see what I can come up with. Thanks for looking!

**Comment by dcbaker** [comment]
Is this ready to merge, or do you want to wait?

**Comment by peterh** [comment]
@dcbaker I'd like to wait a day or two. As much as I want this fix in, I would like to address the issues raised by andreskam first. (I was going to look at this today, but then meetings happened).

**Comment by dcbaker** [comment]
sounds good.

**Comment by peterh** [comment]
Okay, the force-pushed version (just now) changes the way the system path is calculated:

- the system path is placed last, same as when gcc invokes the linker without a libpath specified
- the path from gcc -print-search-dirs is preferred over the hard-coded `/usr/lib:/lib` path (on my machine, that includes `/usr/opt/freeware/lib` and a couple other gcc-specific paths ahead of `/usr/lib:/lib`)

As much as I'd prefer the system paths ahead of the freeware/lib dirs, I can't argue with "what gcc does by default".

@andreaskem does this version work for you?

**Comment by peterh** [comment]
...if there are any other CI failures, I'll take a look tomorrow.

/me shakes fist in general direction of linters.

**Comment by peterh** [comment]
Those two Azure failures have a 100% fail rate since January 24. I don't think they were caused by this merge request.

**Comment by dcbaker** [comment]
No, it's caused by a regression in cygwin (not meson).

**Comment by andreaskem** [comment]
@peterh You are awesome! The new version seems to work just fine, for me. I conducted the same testing procedure as before and did not have to muck with the LIBPATH environment variable anymore.

I am not happy that non-system paths are preferred, but that is how GCC seems to handle it on AIX. On the other hand, GCC is not a native package, itself. Maybe GCC will be packaged differently by IBM in the future, but your solution should gracefully handle that.
I dare not think about what `xlc/xlC` support should look like on AIX, though.

(I'm still not sure about my pkgconf problem, but that still seems completely unrelated)

Thank you very much!

**Pull request merged**
