### PR TITLE
Fix visual studio /utf-8 removal

### PR DESCRIPTION
**Pull request by dcbaker**
And a few other bugs I noticed

### CODE REVIEW

**Comment by eli-schwartz** [comment]
@fanc999 Seems like you broke everything a second time?

**Comment by dcbaker** [comment]
It's also complicated by the fact that most of the developers of meson don't use MSVC, and even when we do we use a recent version, so it's easy for changes targeting old versions to break things :/

**Comment by fanc999** [comment]
> @fanc999 Seems like you broke everything a second time? #11269
> 
> Edit: okay no, this is just too many people messing around with the same broken compiler or something? I hate MSVC... it's so fragile.

ugh..., sigh...
facts of life that I had to deal with... :)

**Comment by nirbheek** [comment]
Thanks for taking care of this Dylan :)

**Pull request merged**
