### PR TITLE
Windows compiler fixes: PGI, Intel

### PR DESCRIPTION
**Pull request by scivision**
Windows users of PGI and Intel compilers will benefit from these additions:

* Intel compiler now works for C / C++ projects on Windows
* PGI compiler detection now respects distinction between OSX, Windows and other (which is important for Windows PGI users)

The compiler search order adds Windows Intel compilers for C, C++ and Fortran.
The Fortran compiler search order had obsolete choices removed, and Flang added (Flang should have been in there already).

This PR lays the groundwork for Intel Fortran on Windows, but will require a future PR as Intel Fortran on Windows is unlike any other compiler, it's the only MSVC-like Fortran compiler I know of. Intel Fortran on other OS's is already supported.

### CODE REVIEW

**Comment by dcbaker** [comment]
I'm really concerned about the approach of saying that ICL is MSVC. because it's like MSVC's...... special needs cousin. We really need a lot more code to make ICL work sanely than just "it's MSVC".

**Comment by scivision** [comment]
Yes all the little options of ICL will need to have specific functions, but as a starting point at least ICL is recognized and compiles programs using default settings. This is the status other compilers are in with Meson as well

**Comment by dcbaker** [comment]
But this doesn't even detect ICL, it detects ICL as MSVC.

**Comment by dcbaker** [comment]
The code is completely broken, it's worse than not supporting it, it's claiming that we support something we don't. ifort on windows fails to compile the "1" test, and we get warnings about options that *we're injecting* into ICL being unsupported!

**Comment by scivision** [comment]
OK this is important. I got overly excited about ICL "working" with particular projects, but not actually passing the tests, which should be the first thing I tested. So I agree it is not appropriate to merge this, sorry about my lapse in judgement.

**Comment by scivision** [comment]
When this PR is reverted, what I will do is readd the other parts of the PR (better search order for Fortran compilers) and specifically exclude `ifort` on Windows

**Comment by scivision** [comment]
also, it will be important to more carefully scrutinize PGI and Flang on these same topics.

**Comment by jpakkane** [comment]
There is a `GnuLike` base class, maybe there could be a `MsvcLike` one as well?

**Comment by scivision** [comment]
MsvcLike is what would be needed for Ifort on Windows, and probably Intel Icl as well.
Despite my careless attempt, Icl does indeed compile and link executables that run successfully via this branch, so correct Icl support is probably a matter of setting all the common options correctly by overriding the base MsvcLike class methods

**Comment by dcbaker** [comment]
I've a WIP branch that I've been rebasing/rewriting for ICL that was about 80% working when I got sidetracked last. I can push that and open a WIP PR if you want that. I've added both an MSVCLike class and and a separate IntelMSVCLike class, the first is used to differentiate clang-cl and msvc, the second inherits the first for Intel.

**Comment by dcbaker** [comment]
BTW, if @scivision, I don't know anything about Fortran at all, so I would still really appreciate if you could handle ifort on Windows (and look at what I did on Linux) because I am less than a noob there. I am actively working on ICL, we finally got autotools dropped from Mesa, and ICL support was one of the requirements for dropping scons (which we only use on windows), so I'd like to get support merged ASAP so that it's been in a few versions before I try to delete scons.

**Comment by scivision** [comment]
Yes @dcbaker that would be good to have that branch/pr. I work daily in Fortran and on Windows, Ifort is the easiest choice overall for numerical work and interoperating with other libs that typically were built with Intel compilers. Currently I use CMake on Windows, which works pretty well with Icl/Ifort

**Pull request merged**
