### PR TITLE
Don't add C warning args while building Vala C code

### LINKED ISSUE #864: Don't warn about unused variables when compiling C code generated by the Vala compiler
The Vala compiler tends to generate unused variables. So when compiling Vala code with Meson I get a lot of warnings from the C compiler that do not look nice and clutter the output.

You might argue that this is a bug of the Vala compiler but I don't think so. I agree that in hand-written code unused variables are something bad but for a compiler that outputs C code eliminating unused variables is an additional step that might not be worth it because the C compiler will eliminate them anyway.

### PR DESCRIPTION
**Pull request by nirbheek**
The code generated by `valac` is usually really crap and has tons of unused variables and such, so disable warnings for this Vala targets. Sadly, if you include `.c` files in that target, warning flags will get disabled for that too. There's no easy way around this right now.

Fixes #864

### CODE REVIEW

**Comment by jpakkane** [comment]
Disabling warnings on unrelated C files is not acceptable. Whatever solution we choose for this must keep warnings on plain C files unaltered.

**Comment by nirbheek** [comment]
These commits now do the following:

1) Ensure that only `.c` files generated from `.vala` files have warnings suppressed
2) Adds a test to ensure (1)
3) Adds a test to ensure that warnings from other `.c` files are not suppressed

To implement (3), I had to add a new type of test that fails only at build time (not at meson/configure time) — `test cases/failing build`.

Along the way, I also implemented a test that fails only when the unit tests are run (`test cases/failing tests`). Nothing uses it right now, but I'm sure we should have such tests. I've wanted to add such tests in the past and didn't because the default failing tests didn't allow it.

**Comment by jpakkane** [comment]
There is also the unittest branch that can (in the future perhaps) be used for this. The idea is that you run it and then parse the compile commands data base and check that args are as expected. Probably won't get done in time for this feature, though, so more of a heads up.

**Comment by nirbheek** [comment]
That makes a lot of sense and would be much faster and more direct to test that we're getting what we expect. Once we get that in, we can start getting much higher test coverage.

I haven't been creating tons of tests for small things so far because the overhead for each test that we have is quite large.

**Comment by nirbheek** [comment]
I've rebased this on master, and I've added a unittest for this too.

**Pull request merged**
