### PR TITLE
cmake: Use new JSON trace format for CMake >= 3.17

### PR DESCRIPTION
**Pull request by mensinda**
Add support for the new JSON trace format, which is easier to parse (it is just JSON) and there is no longer any ambiguity with spaces. So we no longer have to do arcane magic tricks to determine which space is part of a path and which space separates arguments (at least once we have 3.17 as the minimum CMake version).

CMake merge request: https://gitlab.kitware.com/cmake/cmake/merge_requests/4102 (**currently open**)

The merge request is still open, but it should be in the final phases of the review and I don't expect any changes to the actual format. I am opening this PR already in the hope of getting this change into 0.53.0 just in case the CMake MR is merged before 22/12.

### CODE REVIEW

**Comment by jpakkane** [comment]
We can't really merge this until the corresponding functionality is in CMake master. However we can make a freeze exception for this and merge it after dev freeze.

**Comment by mensinda** [comment]
Thanks, I am also against merging this before the CMake MR is master. I have only opened this now to avoid a last-minute PR.

**Comment by KyleFromKitware** [comment]
Please keep in mind that even after the CMake MR is merged, things could still change during our development cycle. Only once 3.17 is out will the CMake compatibility be frozen (though in this case I don't anticipate any issues that would cause such a change.)

**Comment by audiofanatic** [comment]
> Please keep in mind that even after the CMake MR is merged, things could still change during our development cycle. Only once 3.17 is out will the CMake compatibility be frozen (though in this case I don't anticipate any issues that would cause such a change.)

Reverts and previously unreleased interface changes do happen, including during the release candidate phase. The CMake 3.17 release is likely to be around the March 2020 timeframe.

**Comment by mensinda** [comment]
Seeing the latest development with the CMake side MR, I would stop targeting this PR for 0.53.0. The risk that the format and/or flags might change is too high, especially with [this issue](https://gitlab.kitware.com/cmake/cmake/issues/19438) also being open.

**Comment by mensinda** [comment]
Closing, since this is PR is incompatible with #6432.

**Pull request closed without merging**
