### PR TITLE
tests/hdf5: set C++ standard to c++11, which is required for macos CI

### PR DESCRIPTION
**Pull request by dcbaker**

### CODE REVIEW

**Review by bruchar1 — APPROVED** [review]
Yes, I realized that too. Unfortunately, that doesn't fix the broken CI caused by the broken homebrew package...

**Comment by dcbaker** [comment]
Yeah, we can't fix homebrew. sigh

**Comment by eli-schwartz** [comment]
It's easy to fix homebrew. Homebrew just needs a PR to revert their hdf5 package to use autotools instead of cmake -- like everyone else builds it.

hdf5 has a totally broken h5cc when built with cmake -- and possibly other issues as well. It's been a long time, but in the past there used to be serious concerns that the cmake build was altogether totally broken on unix, and as a result, no one built with it or reported issues with it so I'd be hesitant to claim it's well tested even.

**Comment by jpakkane** [comment]
```
Undefined symbols for architecture x86_64:
  "_H5close", referenced from:
      _main in main.c.o
  "_H5get_libversion", referenced from:
      _main in main.c.o
  "_H5open", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[3/4] c++ -Iexecpp.p -I. '-I../test cases/frameworks/25 hdf5' -I/usr/local/include -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -Wall -Winvalid-pch -std=c++11 -O0 -g -MD -MQ execpp.p/main.cpp.o -MF execpp.p/main.cpp.o.d -o execpp.p/main.cpp.o -c '../test cases/frameworks/25 hdf5/main.cpp'
ninja: build stopped: subcommand failed.
```

**Comment by eli-schwartz** [comment]
Yes, this is https://github.com/Homebrew/homebrew-core/issues/159691

**Comment by dcbaker** [comment]
It looks like using h5cc is deprecated, and they have pkg-config and cmake-config support. Sounds like we should deprecated the config-tool method, and support for pkg-config and cmake-config, and skip this on macos

**Comment by thesamesam** [comment]
We hit this in Gentoo before as well (https://bugs.gentoo.org/813924, https://bugs.gentoo.org/820158).

See also https://github.com/HDFGroup/hdf5/issues/1814 and https://github.com/Homebrew/homebrew-core/issues/159691.

**Comment by dcbaker** [comment]
@eli-schwartz Is it really correct to raise in that case? shouldn't it just be set to `self.found = false; return` and let the normal code go on to say "couldn't find anything, sorry"?

**Comment by eli-schwartz** [comment]
Raising a DependencyException would also mean that it logs the exception text in the log file, and if it cannot resolve via a different method then detect() will use that exception text as part of the "error: dependency hdf5 not found" message.

**Comment by eli-schwartz** [comment]
I think this was fixed in #12802

**Pull request closed without merging**
