### PR TITLE
rewriter: Add support for kwargs modification

### PR DESCRIPTION
**Pull request by mensinda**
This PR adds support for rewriting select `kwargs` of the `project()`, `dependency()` and build target functions (`executable()`, `library()`, etc.).

Kwargs of these functions can be set and removed. If the kwarg is a list, elements can also be added and removed.

Again, no docs because this feature is still in beta :smiley:

### CODE REVIEW

**Comment by mensinda** [comment]
Ping :)

**Comment by jpakkane** [comment]
I'll try to get this done tomorrow evening.

**Comment by mensinda** [comment]
Thanks. I just wanted to make sure this didn't slip under the radar.

**Comment by jpakkane** [comment]
Having class names like `MesonFoobar` is a bit vague. Could we come up with a name that is more specific?

**Comment by mensinda** [comment]
Sure. How about `MTypeFooBar`, or would you prefer a full name like `MesonTypeFooBar`?

**Comment by mensinda** [comment]
I went ahead and renamed the classes in question.

**Pull request merged**
