### PR TITLE
consistent invalid escape sequence behaviour

### PR DESCRIPTION
**Pull request by jon-turney**
Document that unrecognized escape sequence behaviour is similar to python, not C.

See also #3188

### CODE REVIEW

**Comment by QuLogic** [comment]
There's at least [one exception for invalid escapes](https://github.com/mesonbuild/meson/blob/master/mesonbuild/mparser.py#L183), so I'm not sure this is exactly right.

**Comment by jon-turney** [comment]
> There's at least [one exception for invalid escapes](https://github.com/mesonbuild/meson/blob/master/mesonbuild/mparser.py#L183), so I'm not sure this is exactly right.

Good point.  I've no idea how that exception can be raised (@NickeZ ?).  The error message doesn't seem to quite match the exception though, since it could be caused by *any* unicode codec error decoding the escape (although it's hard to see how they could occur since the file has already been utf-8 decoded before we start lexing?)

Unrecognized python escapes aren't a codec error, since by python rules, they are unmodified.

```
message('\c')
message('\u123')
message('\u12345')
message('\ufffe')
message('\u')
```

```
Message: \c
Message: \u123
Message: ሴ5
Message: ▒
Message: \u
```

**Edit:** Found one:

```
message('\u123 ')
```

```
ERROR: Failed to parse escape sequence: '\u123 ' in string:
  '\u123 '
``

So it seems the statement I suggested is correct.  I don't know if we want to say anything about 'recognized but invalid escape sequences'

**Comment by jon-turney** [comment]
https://github.com/NickeZ/meson/blob/9da14bb933acd1348e6dc1cce7e879e2b0c3e3c2/mesonbuild/mparser.py#L22-L29

It's interesting that the regex used here uses `[0-7]` for octal digits, but `.` for decimal and hexidecimal digits.

**Comment by QuLogic** [comment]
> Unrecognized python escapes aren't a codec error, since by python rules, they are unmodified.

That's only true for Python < 3.8, and it's a warning in 3.7. Though I think from the regex, Meson doesn't pass invalid escape sequences to Python.

**Comment by jon-turney** [comment]
> That's only true for Python < 3.8, and it's a warning in 3.7. 

Interesting, I wasn't aware of that.

> Though I think from the regex, Meson doesn't pass invalid escape sequences to Python.

It will pass `\U`, `\u` or `\x` with non-hex digits.

**Comment by NickeZ** [comment]
I guess the regex should be updated to only accept [A-Fa-f0-9] instead of those dots..

**Comment by jon-turney** [comment]
> I guess the regex should be updated to only accept [A-Fa-f0-9] instead of those dots.

Added this, and a test.

I guess a future piece of work could be to warn on invalid escape sequences.

**Pull request merged**
