### PR TITLE
gettext: Use argparse to handle arguments

### PR DESCRIPTION
**Pull request by TingPing**
This should be more reliable than hardcoded positions.

@tp-m can you verify it fixes your issue from #918

### CODE REVIEW

**Comment by tp-m** [comment]
Sadly not, but fails differently now :)

```
tpm@xps:~/gst-meson/gstreamer/build$ ninja gstreamer-1.0-update-po 
[0/1] 'Running external command gstreamer-1.0-update-po.'
xgettext: warning: file 'gst/parse/grammar.y' extension 'y' is unknown; will try C
gst/parse/grammar.y:217: warning: Empty msgid.  It is reserved by GNU gettext:
                                  gettext("") returns the header entry with
                                  meta information, not the empty string.
gst/parse/grammar.y:222: warning: Empty msgid.  It is reserved by GNU gettext:
                                  gettext("") returns the header entry with
                                  meta information, not the empty string.
xgettext: warning: file '' extension '' is unknown; will try C
xgettext: error while reading "/home/tpm/gst-meson/gstreamer/": Is a directory
FAILED: gstreamer-1.0-update-po 
'/usr/bin/python3' '/home/tpm/Devel/meson/meson.py' '--internal' 'commandrunner' '/home/tpm/gst-meson/gstreamer' '/home/tpm/gst-meson/gstreamer/build' 'po' '/usr/bin/python3' '/home/tpm/Devel/meson/meson.py' '--internal' 'gettext' 'update_po' '--pkgname=gstreamer-1.0' '--langs=af@@az@@be@@bg@@ca@@cs@@da@@de@@el@@en_GB@@eo@@es@@eu@@fi@@fr@@gl@@hr@@hu@@id@@it@@ja@@lt@@nb@@nl@@pl@@pt_BR@@ro@@ru@@rw@@sk@@sl@@sq@@sr@@sv@@tr@@uk@@vi@@zh_CN@@zh_TW'
```

**Comment by tp-m** [comment]
The warnings I also get with autotools fwiw.

**Comment by TingPing** [comment]
I don't think that would be an issue related to any of these changes, did `ninja gstreamer-1.0-pot` work before?

**Comment by tp-m** [comment]
The `Index out of range` error I mentioned also happens with commit 70265c37 which is before the #918 merge, so you're right it's unrelated.

**Pull request merged**
