### PR TITLE
Several fixes to how versioned dependencies are handled + tests

### PR DESCRIPTION
**Pull request by nirbheek**
Add various tests for versioned dependency checking
interpreter: Compare the version of a cached dependency() before using it
interpretor: Correctly check the version of a fallback dependency
interpreter: Set declare_dependency version from the project version if missing
mesonlib: Fix typo in version_compare error
Also reuse subproject-based fallback dependencies
interpreter: Check if subproject version is defined before comparing

### CODE REVIEW

**Comment by jpakkane** [comment]
Tests using zlib must not be in common because the must be runnable on all platforms without any third party data, even wrapd (specifically, Visual Studio installed from scratch with no dependencies installed). Put them in linuxlike instead along with the rest of them.

**Comment by nirbheek** [comment]
Done! Btw, can we rename the tests so that they can be sorted alphabetically? 001, 002, ..., 010, 011, ... 100, etc? Right now it's difficult to even know what the highest-numbered test is.

**Comment by jpakkane** [comment]
Whenever you add zeros to file names to make them sort correctly, god kills a kitten. If your tools don't do proper sorting, file a bug in that tool instead.

**Comment by nirbheek** [comment]
What's wrong with prefixing zeroes to filenames?

**Comment by jpakkane** [comment]
[This](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/).

**Pull request merged**
