### PR TITLE
cmake: Fix empty -D due to empty strings (closes #5522)

### LINKED ISSUE #5522: empty -D flag passed to g++ causes build to fail
meson 0.51.0 generates this compile command and the resulting error:

```
c++ -Imeson-out/25a6634@@alphabot@exe -Isrc -I../src -I/usr/include/libdrm -I/usr/include -I/usr/include/SDL2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -g -D_REENTRANT -D -MD -MQ 'meson-out/25a6634@@alphabot@exe/main.cpp.o' -MF 'meson-out/25a6634@@alphabot@exe/main.cpp.o.d' -o 'meson-out/25a6634@@alphabot@exe/main.cpp.o' -c ../src/main.cpp
cc1plus: error: to generate dependencies you must specify either ‘-M’ or ‘-MM’
```

The error is caused by the empty -D after -D_REENTRANT which confuses g++ 9.1.0.

the meson.build file looks like this:
```
libgl         = dependency('GL')
libpng        = dependency('PNG')
libsdl2       = dependency('SDL2')
libsdl2_mixer = dependency('SDL2_mixer')
libfreetype2  = dependency('freetype2')

executable('alphabot',
           'main.cpp',
           implicit_include_directories: true,
           dependencies: [libgl, libpng, libsdl2, libsdl2_mixer, libfreetype2],
           #cpp_args : '-DTEST',
           install: true)
```

Uncommenting #cpp_args : '-DTEST' will result in "-D_REENTRANT -D -DTEST" and allow the compilation to succeed.

### PR DESCRIPTION
**Pull request by mensinda**
Fix that empty strings were processed in the dependency, due to generator expressions, etc.

### CODE REVIEW

**Comment by mensinda** [comment]
Just to clarify: I have decided to do the filtering in the `CMakeDependency`, just in case there are other edge cases with the properties (specifically looking at the CMake subprojects).

This should probably also go int 0.51.2.

**Comment by jpakkane** [comment]
Test failures seem relevant.

**Comment by nirbheek** [comment]
This branch didn't cleanly apply on top of 0.51 because it depends on https://github.com/mesonbuild/meson/pull/5457 which is a huge pull request. Do you think you could backport this to 0.51 and open a new PR targetting the 0.51 branch for it?

**Comment by mensinda** [comment]
Yeah, should be possible. When do you need it?

**Comment by nirbheek** [comment]
It's the only thing blocking the 0.51.2 release, so whenever you have time :)

**Comment by mensinda** [comment]
Done: #5704

**Comment by jpakkane** [comment]
Well there is the question of #5674 for 0.51.2. Otherwise people might start to depend on the current behaviour.

**Comment by nirbheek** [comment]
> Well there is the question of #5674 for 0.51.2. Otherwise people might start to depend on the current behaviour.

Ah, missed that conversation. Added.

**Pull request merged**
