### PR TITLE
python module: Only run command once to get all info

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
@MathieuDuponchelle can you review this PR please, since you're the author of that module.

**Comment by MathieuDuponchelle** [comment]
Looks good to me, ooc why was that a problem in practice? :)

**Comment by nirbheek** [comment]
During configuration, `exec()` calls always take overwhelmingly the largest amount of time. Minimizing them is good.

**Comment by MathieuDuponchelle** [comment]
OK noted, @nirbheek you can push that fwiw :)

**Comment by xclaesse** [comment]
I have no numbers to back it up, but it seemed a wast of time to spawn a whole python interpreter many times. Probably won't make a huge difference anyway.

**Comment by nirbheek** [comment]
It probably wasn't huge this time, but small numbers add up!

**Pull request merged**
