### PR TITLE
Ninja: Use OrderedDict in places where order matters

### PR DESCRIPTION
**Pull request by nirbheek**
Specifically, wherever we have sources or outputs, we want to use an `OrderedDict` so that the build is always deterministic. It was reported by @obilaniu that `ar D` creates static libraries with different checksums depending on the order of the object files. See: https://github.com/mesonbuild/meson/pull/951

We don't actually want to preserve the order in which they are listed. We just want the order to be deterministic and predictable.

This patch series also adds a unit test that ensures that the file order is deterministic.

### CODE REVIEW

**Comment by nirbheek** [comment]
I will note that even though preserving the order is not a requirement, for pre-existing (i.e., not generated) sources the order is now preserved unless you use Vala. Order is always deterministic in any case.

**Comment by obilaniu** [comment]
@nirbheek @jpakkane I confirm this solves my problem (at least to 1.-2.**(-6) = 98.4% certainty and climbing fast)

**Comment by obilaniu** [comment]
Now my builds are 100% reproducible, although `build.ninja` and `compile_commands.json` are both randomly ordered.

If I sort `diffA/build/build.ninja` and `diffB/build/build.ninja`, their diff is
```
55c55
< build all: phony perfs/perf_sich 3rdparty/libgtest_main.a src/libsich.so.0.0.0 tests/test_sich
---
> build all: phony 3rdparty/libgtest_main.a src/libsich.so.0.0.0 tests/test_sich perfs/perf_sich
```
and if I sort `diffA/build/compile_commands.json` and `diffB/build/compile_commands.json`, their diff is _empty_ (Yay!).

@nirbheek Could you please add an OrderedDict to whatever is spitting out the `build all` target line? I suppose the ordering of the rules within the file will be harder, but I'm sure there's a dict behind it too.

Once that's fixed the `build.ninja` and `compile_commands.json` will be fully deterministic!

**Comment by nirbheek** [comment]
Making the list of targets ordered is not going to make the order in which ninja invokes the targets deterministic, and there is really no benefit to doing that.

**Comment by jpakkane** [comment]
The change would not affect building in any way but would make debugging easier the next time we run into reproducibility issues (it's less effort to make the output deterministic than to convince different people again and again that this particular thing is not an issue).

**Comment by kvtb** [comment]
It is not completely fixed: if there is a source with many files (for example `Boost` with many libraries), the order of those files is not deterministic.

**Pull request merged**
