### PR TITLE
Pool feature

### PR DESCRIPTION
**Pull request by BeChris**
Add possibility to limit concurrent jobs running at the same time for a given target.
At work, I use proprietary code generation tools which rely on token server.
As the token server can't deliver several tokens at the same time, file generation fails.

I propose to implement a feature called 'pools' (as in Ninja) to be able to declare custom pools and then reference them in targets so that they are built using a limited amount of concurrent jobs.

I updated Reference manual but not automatic tests yet.

Consider following meson.build file:

```python
project('test', 'c')

# Sources to compile
srcs = ['file0.c', 'file1.c', 'file2.c', 'file3.c', 'file4.c', 'file5.c', 'file6.c', 'file7.c', 'file8.c', 'file9.c', 'file10.c']

# Declare a custom pool
pool(name: 'one_at_a_time', depth: 1)

# Build a library without specifying any particular pool : its files will be compiled in parallel (using N jobs determined automatically by Ninja)
library('lib1', sources: src)

# Build a library specifying a pool : its files will be compiled sequentially (because pool depth is 1) 
library('lib2', pool: 'one_at_a_time', sources: src)

```

### CODE REVIEW

**Comment by nirbheek** [comment]
> At work, I use proprietary code generation tools which rely on token server.
> As the token server can't deliver several tokens at the same time, file generation fails.

Could you please describe in more detail what this setup looks like and what this means?

Where are the source files coming from? Do you have a custom target that generates them or something else?

**Comment by jpakkane** [comment]
If I understand your problem correctly, then an alternative solution is to invoke the code generation via a wrapper script that does roughly this:

    open file file /tmp/gentool.lock, creating it if it does not exist
    lock the file with fcntl.lockf(lockfile.fileno(), fcntl.LOCK_EX)
    call the generator tool with the rest of the arguments
    return the tool's exit value as the script's exit value

This helper tool will work with any build system and will even support compiling many different targets at the same time while still achieving maximum parallelisation.

The problem with this sort of pool implementation is that we can't support it on all backends because they don't have equivalent functionality. These sorts of features have traditionally had a very hard time getting merged.

**Comment by BeChris** [comment]
You are right, this is exactly the problem I try to address but on Windows.
It seems there is way to do exclusive file locking in Python using [msvcrt](https://docs.python.org/3/library/msvcrt.html?highlight=msvcrt#msvcrt.locking) module.

What a pity the pool feature is not implemented in other backends because I find it elegant ans easier to use than writing lock/unlock logics in a wrapper script.

**Comment by BeChris** [comment]
An alternative (and maybe more robust) way would be to implement this wrapper directly in meson.
This internal wrapper would be used by all but Ninja backends.
I think about improving internal commandrunner to take into account this feature.
For users it will avoid the pain to write themself a multiplatform 'pool' wrapper taking the risk to implement a buggy one.
I can try to to do the commandrunner improvement.
What do you think about this proposal ?

**Comment by jpakkane** [comment]
What I don't like about this is that the entire issue is caused by incompetent tool vendors (charging actual money) and rather than they fixing their shit, it places a maintenance burden on us (who are unpaid volunteers).

**Comment by jpakkane** [comment]
Thanks for filing this but this issue will not be merged for now. Closing this to reduce clutter on the MR page. Thanks.

**Pull request closed without merging**
