### PR TITLE
Add ARMCLANG compiler support for C/C++ languages

### PR DESCRIPTION
**Pull request by sompen**
- The changes include support for cross-compiling C and C++ code with ARMCLANG.
- 'armlink' is used as linker internally, so the path to armlink should be set in the user environment PATH variable before running meson.
- Building shareable libraries is not supported with current implementation.
- The PIC support related options are expected to be added by user explicitly.
- The current implementation doesn't have support for compiling assembly files with arm syntax and only supports gnu syntax.
- The 'target' compiler command line option is required to be set for running the sanity check, so passing this option from cross-file, cross/armclang.txt.

The changes tested on Windows with ARM compiler version 6.5(MDK 5.21).
The attached files are the cross test results obtained from running the following command line
**python .\run_cross_test.py cross\armclang.txt**
[armclang_cross_test_log.txt](https://gist.github.com/sompen/c0e64d52f2566217d9e6933680b3bfcb)
[meson-cross-test-run.txt](https://gist.github.com/sompen/145b985bb7587da41eb098a6c0e63876)
[meson-cross-test-run.xml](https://gist.github.com/sompen/1f4b2a01ebcd892ede60f629f226502a)

Currently 45 tests are failing, 4 are being skipped and 149 tests are passing.

### CODE REVIEW

**Comment by jpakkane** [comment]
Please don't do merges but rebases instead.

**Comment by sompen** [comment]
@jpakkane, Did you get a chance to look at my changes?

**Comment by jpakkane** [comment]
Roughly this looks nice, but please rebase against current trunk and remove the merge commit as mentioned above.

**Comment by sompen** [comment]
@jpakkane I have created a new pull request, #3717, with the changes rebased on latest trunk.

**Comment by sompen** [comment]
Duplicate of #3717

**Pull request closed without merging**
