### PR TITLE
WIP: Rewrite gtkdoc() to use custom_target() instead of script

### PR DESCRIPTION
**Pull request by xclaesse**
This has a few adventages:
- Easier to debug because command lines are writted in ninja file
- Source file generated is compiled as a regular executable which ensure
  exact build arguments are passed to the compiler. Passing args to
  gtkdoc-scan was error prone in the past and probably still have
  issues.
- gtkdoc binaries are found using find_program() which allows overriding
  them when using gtkdoc as subproject.

### CODE REVIEW

**Comment by xclaesse** [comment]
This is still WIP because it depends on a few patches to be merged into gtk-doc: https://gitlab.gnome.org/GNOME/gtk-doc/merge_requests/1

**Comment by lantw44** [comment]
How does it handle `LD_LIBRARY_PATH`? I can't find `LD_LIBRARY_PATH` in new code. Since `-Wl,-rpath` isn't a reliable way to set runtime library paths, `gtkdochelper.py` handles it by finding `-Wl,-rpath` in `ldflags` and prepending them to `LD_LIBRARY_PATH` before running the command.

**Comment by xclaesse** [comment]
I was assuming that since I'm not compiling a regular executable() meson/ninja will do the right thing for me. How is that difference from any compiled unit test that we need to run ?

**Comment by lantw44** [comment]
> I was assuming that since I'm not compiling a regular executable() meson/ninja will do the right thing for me. How is that difference from any compiled unit test that we need to run ?

I think there is no difference: the fact is that meson doesn't work reliably when you have `LD_LIBRARY_PATH` set in the environment, while `LD_LIBRARY_PATH` is required for JHBuild to work. https://github.com/mesonbuild/meson/issues/1383 and https://github.com/mesonbuild/meson/issues/1635 were opened to track the issue, but both of them haven't been fixed. Running a compiled executable with `custom_target` isn't reliable, and it was why I proposed a workaround for colord in https://github.com/hughsie/colord/pull/68. Running unit tests isn't reliable as well, and it was why I added `-Wl,--disable-new-dtags` to `LDFLAGS` in GLib `.gitlab-ci.yml`.

This issue doesn't affect `gnome.generate_gir` and `gnome.gtkdoc`. `g-ir-scanner` handles `LD_LIBRARY_PATH` itself, so it can be used directly in ninja files. `gtkdoc-scangobj` doesn't handle it, and it currently relies on meson `gtkdochelper.py` to set the environment correctly.

**Comment by xclaesse** [comment]
Looks like a larger issue that should be deal globally and not specifically for gtkdoc. But I agree that's probably a blocker for this PR then :(

**Comment by jpakkane** [comment]
Since this won't be fixed soon, I'll close this to reduce clutter on the PR page. Feel free to reopen when done.

**Pull request closed without merging**
