### PR TITLE
type annotations cleanup

### PR DESCRIPTION
**Pull request by eli-schwartz**
One minor fix for a broken annotation. Various stuff moved to typing-only imports.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
@lazka seems like the msys2 CI has regressed.

```
[UNEXSKIP]   frameworks: 15 llvm    (method=cmake link-static=True)
 [SUCCESS]   frameworks: 15 llvm    (method=config-tool link-static=False)
 [SUCCESS]   frameworks: 15 llvm    (method=config-tool link-static=True)
```

**Comment by lazka** [comment]
We updated to llvm 14 just now. Hm, the logs aren't very helpful.

**Comment by lazka** [comment]
If I run this locally I get:

```
 [SKIPPED]   frameworks: 15 llvm    (method=cmake link-static=True)
Reason: llvm not found.
 [SUCCESS]   frameworks: 15 llvm    (method=config-tool link-static=False)
 [SUCCESS]   frameworks: 15 llvm    (method=config-tool link-static=True)
```

**Comment by lazka** [comment]
It's this: https://github.com/llvm/llvm-project/issues/53950

**Comment by lazka** [comment]
I've filed #10249

**Review by dcbaker — APPROVED** [review]
Sorry it took me so long to review this, looks good to me.

**Comment by eli-schwartz** [comment]
Did a clean rebase to retrigger CI with the llvm 14 fix.

**Pull request merged**
