### PR TITLE
Several fixes to how we handle objects in build targets

### PR DESCRIPTION
**Pull request by nirbheek**
We now handle all compiler and linker determination in each target instead of doing it in `backend/backends.py`. This unifies, simplifies, and corrects a lot of places where we were doing compiler-specific things.

This fixes a bunch of things that were broken such as #1169, build targets consisting of only generated objects or only prebuilt objects. Also extends the linker determination support to also include languages other than C/C++.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Windows is broken

**Comment by ignatenkobrain** [comment]
Failed test: test cases/common\125 extract all shared library
Reason: Compiling source code failed.
Succeeded test: test cases/common\125 shared module
Failed test: test cases/common\126 object only target
Reason: Compiling source code failed.

**Comment by nirbheek** [comment]
Good, this was always broken. Now I can fix it.

**Comment by jpakkane** [comment]
The tests need to be renumbered and conflict fixed, but otherwise good to go.

**Comment by nirbheek** [comment]
Tests renumbered (assuming #1184 will be merged first) and conflicts fixed.

**Pull request merged**
