### PR TITLE
Add cc.preprocess() method

### PR DESCRIPTION
**Pull request by xclaesse**
This exposes any clike compiler's preprocessor. Many projects preprocess their files using a custom_target() or a generator() but that implies knowing the command line syntax of different compilers (especially MSVC) which is something Meson already knows. It's makes preprocessing unconsistent because they don't use the same CFLAGS as normal compilation because a custom target does not always have access to cflags added via `add_project_arguments()`, `-Dc_args`, etc.

The way it is implemented in the ninja backend ensures that the preprocessing uses exactly the same command line than normal compilation, there is almost no special casing for preprocessor. Howerver, things are more complicated for other backends, so it internally converts to a Generator to reuse existing infrastructure.

Lots of the infrastructure introduced in this PR could be used in the future to add support for assemblers and transpilers in vs/xcode backend.

### CODE REVIEW

**Comment by jpakkane** [comment]
Out of curiosity, why is this functionality needed? What problem do projects solve by preprocessing like this?

**Comment by xclaesse** [comment]
I have seen a couple times non source files that needs to be preprocessed, like https://github.com/libffi/libffi/blob/master/libffi.map.in.

The other use-case is for gobject-introspect, basically it's a python script that does:
1. generate a file
2. preprocess the file
3. parse the preprocessed file
4. generated a source file
5. compile and run the source file
6. parse output of the program

Compiling code in an external script is a very bad idea and causes tones of issues, I would like to do steps 2 and 5 in Meson because meson/ninja knows exactly how to preprocess/compile/run, with the right flags and dependencies, etc. technically that use-case does not require to expose the preprocessor as public API, but it needs the internal support any way.

@dcbaker also had the same idea of adding cc.preprocessor() in a WIP branch a long time ago, I think it was needed for Mesa, not sure about the exact use-case for him.

And finally, preprocessing can be useful when the compiler is not already supported by Meson, for example libffi preprocess assembler source files with cl.exe before passing them to ml.exe to compile them.

**Comment by tristan957** [comment]
This would also be useful in the case of using the C preprocessor as a templating engine for other languages.

**Comment by eli-schwartz** [comment]
So, like https://gitlab.freedesktop.org/xorg/app/xinit/-/blob/master/startx.cpp#L26

**Comment by jpakkane** [comment]
Test failure is related:

```
FAILED: src/preprocessor.p/file.map 
"cl" "/EP" "/P" "-Isrc\preprocessor.p" "-Isrc" "-I..\test cases\common\255 preprocess\src" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/Od" "/Zi" "-DFOO=0" "-DBAR=0" "-x" "assembler-with-cpp" "/Fdsrc\preprocessor.p\file.pdb" /Fisrc/preprocessor.p/file.map "/c" "../test cases/common/255 preprocess/src/file.map.in"
cl : Command line warning D9002 : ignoring unknown option '-x'
assembler-with-cpp
c1: fatal error C1083: Cannot open source file: 'assembler-with-cpp': No such file or directory
file.map.in
```

**Comment by xclaesse** [comment]
@jpakkane Should be fixed now.

**Pull request merged**
