### PR TITLE
Add missing type annotation

### PR DESCRIPTION
**Pull request by petere**
I noticed during unrelated work that the lint/mypy check was failing on this, so I propose this fix.

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]

**Comment by petere** [comment]
I don't see this commit in the master branch. Was this merged correctly?

**Comment by tristan957** [comment]
Hmm this is very strange. The commit that GitHub thinks is this commit on the master branch is something completely different. Wanna just re-open a PR, and we can try this again?

**Comment by eli-schwartz** [comment]
This is a fascinating GitHub bug... @dcbaker since GitHub *thinks* you clicked merge on this (but I can't even be sure of that at this point) do you recall if this succeeded at any time?

**Comment by petere** [comment]
> Wanna just re-open a PR, and we can try this again?

Ok, let's try that.

**Comment by petere** [comment]
Actually, this was already committed independently as 8bc8f9343. So it's all done, just GitHub being a bit confused.

**Comment by eli-schwartz** [comment]
That's... definitely *one* way of resolving a cherry-pick by determining that the resulting patch would be empty.

**Comment by dcbaker** [comment]
I was confused since I thought I’d already fixed this, but convinced myself it was a second instance of the same issue. Very strange behavior from GitHub indeed

**Pull request merged**
