### PR TITLE
macos 10.13 fixes

### PR DESCRIPTION
**Pull request by dcbaker**
I noticed a few things don't work correctly on macOS 10.13 as I've been trying to get mesa building there.

### CODE REVIEW

**Comment by nirbheek** [comment]
I am not sure I understand the has_function test changes. The purpose of that test is to check that a workaround we placed for a breakage that Apple shipped still works; namely that when you are running and targetting macOS 10.11 but building with XCode 8 or later, `clock_gettime()` gets mistakenly 'found' even though it was not available in macOS 10.11 (it started being shipped 10.12 onwards).

Your changes seem to disable that test with XCode 9 or later? If the test is failing, that needs to be looked at I think.

**Comment by dcbaker** [comment]
My 10.13 system has xcode 9 and only has one SDK, 10.13. I couldn't find a way to install another one, so those tests fail because neither 10.11 or 1.12 SDK's exist. Maybe the better solution is to check that the SDK directories exist?

**Comment by nirbheek** [comment]
You can still target an older macOS with the newer SDK I believe.

Do the tests pass if you run `export SDKROOT=$(xcodebuild -version -sdk macosx Path)` before running the tests? We set that in `.travis.yml`, and it should mitigate the need to pass `-isysroot`. Maybe we should set that in `run_project_tests.py`.

**Comment by dcbaker** [comment]
Doesn't like that either, I just get an error about not finding clock time for mac osX 10.12

**Comment by jpakkane** [comment]
I can verify. There is only `MacOSX10.13.sdk` in that dir, which is a symlink to `MacOSX.sdk`. There does not seem to be a simple way to make this test work with XCode 9.

**Comment by dcbaker** [comment]
Apple is pretty clear in their documentation that the only support previous versions of macOS for a while and then stop, mostly to give app developers a chance to port from the old SDK to the new one.

**Comment by jpakkane** [comment]
Let's merge this. Having it in is better than not, because CI is entirely broken without it. The test is still valid on old XCodes and the actual test can be fixed later if needed.

**Pull request merged**
