### PR TITLE
Add tests for sources that are disablers.

### PR DESCRIPTION
**Pull request by jameshilliard**
This is the part of #5427 that fixes handling of disablers being passed to sources.

### CODE REVIEW

**Comment by jameshilliard** [comment]
Not sure why some of these tests are timing out but the failures don't seem related to this change.

**Comment by jpakkane** [comment]
Checking whether arguments contain disablers should all be in `interpreterbase.py`. Spreading them all over the code base is big maintenance burden. Please move all the checking logic there instead.

**Comment by jameshilliard** [comment]
So looks like this may have already been fixed in #5687, I've changed it to just adding tests.

**Comment by nirbheek** [comment]
Thanks! More test coverage is always good to have :)

**Pull request merged**
