### PR TITLE
Retry downloads in Appveyor

### PR DESCRIPTION
**Pull request by sarum9in**
This patch should prevent failing build because of single download failure.

### CODE REVIEW

**Comment by jpakkane** [comment]
Failure seems very relevant...

**Comment by sarum9in** [comment]
That's why it's WIP...

**Comment by sarum9in** [comment]
@jon-turney would you mind taking a look at this code? I believe you have a lot of Windows experience.

**Comment by sarum9in** [comment]
Ready for review.

**Comment by jon-turney** [comment]
> @jon-turney would you mind taking a look at this code? I believe you have a lot of Windows experience.

Well, maybe.  I try to stay as far away as possible from PowerShell, so all I can say is "that looks ok".

How have you tested this?  e.g. have you tried simulating a failure (perhaps by using the wrong URL) and seeing if the code retries?

**Comment by sarum9in** [comment]
Yes, it does. I also have evidence of retries with a different failure pattern, I messed up with shell escaping in caller code in former version of this PR and this [resulted in retries](https://ci.appveyor.com/project/mesonbuild/meson/build/115/job/6mworrdv97c7iaah).

**Pull request merged**
