### PR TITLE
Make MSVC accept gnu11 as a language standard version. Closes: #7611.

### PR DESCRIPTION
**Pull request by jpakkane**
Not actually tested ...

### CODE REVIEW

**Comment by xclaesse** [comment]
That's not enough AFAIK, it should also accept gn89, gnu99, basically anything other compilers could use. Also could add a comment there that it is a work around until we have a proper solution, and link to relevant issue.

**Comment by jpakkane** [comment]
Updated. Thinking more, maybe the language standard version should not be set by each compiler? Instead the set of values could always be the same, the compiler classes would just error out or fallback on versions they don't support.

**Comment by xclaesse** [comment]
@jpakkane the tricky part is for projects like glib that uses GNU features, but with lots of #ifdef can also build without. Some other projects could instead require GNU compiler and simply fail otherwise.

**Review by dcbaker — COMMENTED** [review]
I think it would be best to give some kind of warning that gnuXX was selected, but cXX is going to be used, and that this behavior is deprecated and will change in the future.

**Comment by dcbaker** [comment]
I have a patch that moves the std down to the CCompiler or CPPCompiler, asks then reach complier updates the choices it supports. I think that's what you were thinking about?

**Comment by xclaesse** [comment]
> I think it would be best to give some kind of warning that gnuXX was selected, but cXX is going to be used, and that this behavior is deprecated and will change in the future.

I'm fine with deprecating, but only if we have an alternative which we currently don't have for 0.56.0 release. Unless `c_std=c99` does enable GNU extensions on gcc/clang?

**Comment by dcbaker** [comment]
I'm pretty sure that c99 on gcc doesn't provide gnu extensions. At least a warning that you're falling back and things may not work would be good

**Comment by xclaesse** [comment]
The problem is that would be a warning that glib and many other project will have no way to get ride of. A warning with no alternative is not good. But I'm all for a warning once we can provide an alternative syntax for that use case.

**Comment by dcbaker** [comment]
But not having the warning is going to leave people who's project *cant* fall back to c99 saying "meson configured, but it always fails to compile, what gives!". The warning could well be "requested gnu99, but only c99 available. This may or may not work." We have similar warnings for requesting C++11 with msvc, as it only has C++98 and C++14, so we auto promote C++11 to C++14.

Here's the cleanup I mentioned earlier: #7866

**Comment by dcbaker** [comment]
@jpakkane, I noticed in #7866 that clang-cl has the exact same problem. If you would, could you just merge that instead? if not, could you pick the clang-cl and warnings patches over to this?

**Comment by nirbheek** [comment]
> But not having the warning is going to leave people who's project _cant_ fall back to c99 saying "meson configured, but it always fails to compile, what gives!".

This is how meson has always behaved before 0.56. By making gnuXY not fallback to cXY on compilers that don't support it, we are changing the meaning of the `c_std=` argument in a backwards-incompatible way with no way around it for projects.

I would argue that the vast majority of cross-platform projects do not want to be strict about gnustd vs cstd because they handle that using `#ifdef` in the code, so we should _definitely not_ change the default behaviour. However, some projects may indeed want to require gnustd (and these probably don't care about cross-platform support, so they won't even hit the issue where a compiler doesn't support a gnustd), and for that we should add new syntax.

**Comment by dcbaker** [comment]
No, that's how msvc and clang-cl have behaved. If you pass `c_std=gnu24` to gcc it will straight up error. The problem here is that MSVC and Clang-CL didn't implement standard handling at all, and that resulted in them accepting anything. But no other C compiler's have that behavior. Frankly, what does 'c_std=gnu99' mean if it doesn't mean "I need gnu99?" because if it doesn't mean "gnu99 or else" I'm going to have to change a lot of projects in the xorg camp because we're relying on gnu99 means gnu99 not c99.

**Comment by nirbheek** [comment]
> The problem here is that MSVC and Clang-CL didn't implement standard handling at all, and that resulted in them accepting anything

Yes, and they still don't really implement standard handling (c11 support is incomplete, older stds will never be implemented, and all this is experimental). MSVC implements random bits of POSIX and GNU libc APIs, so if it helps, you can look at it as "msvc supports all the standards, as best as you can expect". So the old implementation was _more correct_ than what we have today.

But you're doing all the work, so it's your call. I won't say anything more on the subject.

**Comment by nirbheek** [comment]
0.56.1 will be fixed with https://github.com/mesonbuild/meson/pull/7946

0.57 can be discussed in https://github.com/mesonbuild/meson/pull/7866

Closing.

**Pull request closed without merging**
