### PR TITLE
Allow not-required not-found dependencies in subprojects

### PR DESCRIPTION
**Pull request by nirbheek**
Closes https://github.com/mesonbuild/meson/issues/1474

### CODE REVIEW

**Comment by jpakkane** [comment]
There should also be a test for the case where the subproject exists but the dependency variable is not declared in it.

**Comment by nirbheek** [comment]
That's what the test already does, unless I misunderstood what you're saying.

**Comment by jpakkane** [comment]
Damn, I got it backwards. Yes, that is what is tested, but what about the case of:

    dependency('foobar', fallback: ['nonexistingsubproj', 'foodep'], required : false)

**Comment by nirbheek** [comment]
We already have a test for that: `common/95 dep fallback`:

```meson
jimmy = dependency('jimmylib', fallback : ['jimmylib', 'jimmy_dep'], required: false)
```

The subproject `jimmylib` doesn't exist.

**Comment by nirbheek** [comment]
I'll move this test there; I guess it makes more sense that way.

**Comment by nirbheek** [comment]
PR should be ready to merge now.

**Pull request merged**
