### PR TITLE
Enhance mesonconfig.py help

### PR DESCRIPTION
**Pull request by winksaville**
Added code to output the 'Possible values' and
also titles for the columns.

Added code so 'choices' is allowed for all
UserOption's.

For testing I created a trivial meson_options.txt:
```
[wink@wink-envy c-mpscfifo]$ cat meson_options.txt 
option('string_option', type : 'string', value : 'String B', description : 'The description', choices : ['String A', 'String B'])
option('bool_option', type : 'boolean', value : false, description : 'A boolean')
option('combo_option', type : 'combo', value : 'two', decription : 'Select the option', choices : ['one', 'two', '3'], )
```
Here is the old output:
```
[wink@wink-envy c-mpscfifo]$ mesonconf build
Core properties

Source dir /home/wink/prgs/c-mpscfifo
Build dir  /home/wink/prgs/c-mpscfifo/build

Core options

buildtype Build type          debug
warnlevel Warning level       1
strip     Strip on install    False
coverage  Coverage report     False
pch       Precompiled headers True
unity     Unity build         False

Compiler arguments

cargs []

Linker args

clinkargs []

Directories

prefix     Install prefix        /usr/local
libdir     Library directory     lib64
bindir     Binary directory      bin
includedir Header directory      include
datadir    Data directory        share
mandir     Man page directory    share/man
localedir  Locale file directory share/locale

Project options

bool_option   A boolean       False
combo_option  combo_option    two
string_option The description the value of string_option
```
Here is the new output with the 'Possible Values' plus column titles and using two character
indentation:
```
[wink@wink-envy c-mpscfifo]$ ~/foss/meson/mesonconf.py build
Core properties:
  Source dir /home/wink/prgs/c-mpscfifo
  Build dir  /home/wink/prgs/c-mpscfifo/build

Core options:
  Option    Description         Current Value Possible Values
  ------    -----------         ------------- ---------------
  buildtype Build type          debug         ['plain', 'debug', 'debugoptimized', 'release']
  warnlevel Warning level       1             ['1', '2', '3']
  strip     Strip on install    False         [True, False]
  coverage  Coverage report     False         [True, False]
  pch       Precompiled headers True          [True, False]
  unity     Unity build         False         [True, False]

Compiler arguments:
  cargs []

Linker args:
  clinkargs []

Directories:
  Option     Description           Current Value 
  ------     -----------           ------------- 
  prefix     Install prefix        /usr/local    
  libdir     Library directory     lib64         
  bindir     Binary directory      bin           
  includedir Header directory      include       
  datadir    Data directory        share         
  mandir     Man page directory    share/man     
  localedir  Locale file directory share/locale  

Project options:
  Option        Description     Current Value Possible Values
  ------        -----------     ------------- ---------------
  bool_option   A boolean       False         ['True', 'False']
  combo_option  combo_option    two           ['one', 'two', '3']
  string_option The description String B      ['String A', 'String B'] 
```

### CODE REVIEW

**Comment by jpakkane** [comment]
Thanks, something like this seems very useful. However why did you add choices to a string option? A string option is meant to be an arbitrary string so a set of choices does not really make sense.

In the project option list you have column Option whose elements all end with `_option`. This is a bit repetitive. Maybe have the column be called `Type` with values `boolean`, `combo` etc.

Python's str function prints true and false with capital letters, whereas in Meson they are written in lowercase so to avoid user confusion we should print them in lowercase also. This is an old issue and not really caused by your patch, I'll need to get that fixed at some point.

This MR has an unfortunate clash with the compileroptions MR. It adds a new option type for string arrays. I'll try to get that merged to trunk before merging this.

**Comment by winksaville** [comment]
I added choices to string so that the author could indicate the choices allowed for the string, if any.
The "Project options" I just made up and were an example, I've changed the example to drop the "_option". And I suggest we continue to call that first column "Option" rather than "Type" unless I miss understood your comment.

Also, I'll be happy to rebase this when the compileroptions MR gets merged.
```
[wink@wink-envy putchar_dbg]$ ~/foss/meson/mesonconf.py build
Core properties:
  Source dir /home/wink/prgs/libs/putchar_dbg
  Build dir  /home/wink/prgs/libs/putchar_dbg/build

Core options:
  Option    Description         Current Value Possible Values
  ------    -----------         ------------- ---------------
  buildtype Build type          debug         ['plain', 'debug', 'debugoptimized', 'release']
  warnlevel Warning level       1             ['1', '2', '3']
  strip     Strip on install    false         [true, false]
  coverage  Coverage report     false         [true, false]
  pch       Precompiled headers true          [true, false]
  unity     Unity build         false         [true, false]

Compiler arguments:
  cargs []

Linker args:
  clinkargs []

Directories:
  Option     Description           Current Value 
  ------     -----------           ------------- 
  prefix     Install prefix        /usr/local    
  libdir     Library directory     lib64         
  bindir     Binary directory      bin           
  includedir Header directory      include       
  datadir    Data directory        share         
  mandir     Man page directory    share/man     
  localedir  Locale file directory share/locale  

Project options:
  Option   Description         Current Value Possible Values
  ------   -----------         ------------- ---------------
  fpu      Enable hardware FPU false         ['true', 'false']
  mode     mode                left          ['forward', 'reverse', 'left', 'right']
  temp_dir Temporary directory temp          ['tmp', 'temp', 'temporary']
```

**Comment by jpakkane** [comment]
The smoke raised by compiler options MR has mostly settled now. Feel free to update this MR, it would be a nice improvement to the UI.

Thanks,

**Comment by winksaville** [comment]
I've rebased please review.

**Comment by jpakkane** [comment]
Looking nice, thanks. There is one issue, though. Boolean core option choices are printed like this:

    [True, False]

Whereas boolean project option choices are printed like this:

    ['True', 'False']

This is inconsitent. Please make them both print `[true, false]` (in lowercase) and this is good to merge.

**Comment by winksaville** [comment]
Updated to always print lower case true/false.

**Comment by rhd** [comment]
This is a really nice addition - thanks!

On existing directories it throws an exception though.

```
mesonconf clangbuild/
Traceback (most recent call last):
  File "/home/u/bin/mesonconf", line 193, in <module>
    c = Conf(builddir)
  File "/home/u/bin/mesonconf", line 40, in __init__
    self.coredata = pickle.load(open(self.coredata_file, 'rb'))
AttributeError: Can't get attribute 'UserComboOption' on <module 'mesonlib' from '/opt/meson/share/meson/mesonlib.py'>
```

**Comment by jpakkane** [comment]
That's the price you pay when living on trunk. :)

On release versions this does not happen, you get an error instead.

**Pull request merged**
