### PR TITLE
Metrowerks improvements

### PR DESCRIPTION
**Pull request by Nomura-RH**
Accidentally deleted my old PR's branch (#12241)

I was asked to split the changes into multiple commits, and had to fix some linting errors as well.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I'd probably include a bit more of the context from the other PR's description in the individual commit messages.

**Comment by Nomura-RH** [comment]
> I'd probably include a bit more of the context from the other PR's description in the individual commit messages.

What kind of information should I add? Also, wouldn't adding it make the commit messages too long?

**Comment by eli-schwartz** [comment]
e.g. for the first commit message:

```
Metrowerks: remove duplicate optimization args
```

You could change it to:

```
Metrowerks: remove duplicate optimization args

The args are in both buildtype and optimization. This broke buildtypes other
than plain or custom unless manually setting the optimization level to
0, because Metrowerks does XXXXXXXXX.
```

> Also, wouldn't adding it make the commit messages too long?

In general, this is probably not possible. :) The distinction is that the base summary on the first line should be short, but adding additional paragraphs of explanatory "why" is fine and also if the rationale isn't obvious from the code itself then usually preferred.

It's like the difference between a Github Issue's "Title" vs. its "Leave a comment" when first opening a bug report.

**Comment by Nomura-RH** [comment]
> e.g. for the first commit message:
> 
> ```
> Metrowerks: remove duplicate optimization args
> ```
> 
> You could change it to:
> 
> ```
> Metrowerks: remove duplicate optimization args
> 
> The args are in both buildtype and optimization. This broke buildtypes other
> than plain or custom unless manually setting the optimization level to
> 0, because Metrowerks does XXXXXXXXX.
> ```
> 
> > Also, wouldn't adding it make the commit messages too long?
> 
> In general, this is probably not possible. :) The distinction is that the base summary on the first line should be short, but adding additional paragraphs of explanatory "why" is fine and also if the rationale isn't obvious from the code itself then usually preferred.
> 
> It's like the difference between a Github Issue's "Title" vs. its "Leave a comment" when first opening a bug report.

Updated

**Pull request merged**
