### PR TITLE
add loongarch support

### PR DESCRIPTION
**Pull request by yetist**
Add loongarch64 support for meson, please review, thanks.

Before:
```
$ meson _build5 --prefix=/usr
The Meson build system                                          
Version: 0.49.2                     
Source dir: /home/yetist/checkout/04-la64/systemd
Build dir: /home/yetist/checkout/04-la64/systemd/_build5           
Build type: native build                                                          
Project name: systemd                 
Project version: 241                                                             
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6.lnd.4) 8.3.0")
WARNING: Unknown CPU family 'loongarch64', please report this at https://github.com/mesonbuild/meson/issues/new with theoutput of `uname -a` and `cat /proc/cpuinfo`
Build machine cpu family: loongarch64
Build machine cpu: loongarch64                                                
Program tools/meson-check-compilation.sh found: YES (/home/yetist/checkout/04-la64/systemd/tools/meson-check-compilation.sh)
Program tools/meson-build.sh found: YES (/home/yetist/checkout/04-la64/systemd/tools/meson-build.sh)
```
After:
```
$ ../meson/meson.py _build4 --prefix=/usr                                                               
The Meson build system                                                                                                                         
Version: 0.56.99                                                                                                                               
Source dir: /home/yetist/checkout/04-la64/systemd
Build dir: /home/yetist/checkout/04-la64/systemd/_build4
Build type: native build
Project name: systemd
Project version: 241
C compiler for the host machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6.lnd.4) 8.3.0")
C linker for the host machine: cc ld.bfd 2.31.1.20190122
Host machine cpu family: loongarch64
Host machine cpu: loongarch64
Program tools/meson-check-compilation.sh found: YES (/home/yetist/checkout/04-la64/systemd/tools/meson-check-compilation.sh)
Program tools/meson-build.sh found: YES (/home/yetist/checkout/04-la64/systemd/tools/meson-build.sh)
```

### CODE REVIEW

**Comment by jpakkane** [comment]
I tried to look up details about the architecture but sadly most of the information available is in Chinese, which I can't read. Is the loongarch a completely new ISA or is is still a MIPS64 one?

**Comment by dcbaker** [comment]
I'm assuming this is the architecture for the loongson chips, which are mips, is that correct @yetist?

**Comment by yetist** [comment]
@jpakkane @dcbaker

LoongArch is a new instruction set of Loongson 3A5000 CPU, currently in the development of the system, has completed the Loongarch64 version based on Debian 10, the 32-bit version has just started development.

We also started to submit patches to the community, such as binutils, autotools, etc. The one that is more related to meson is config.git, please see here: https://git.savannah.gnu.org/gitweb/?p=config.git;a=commitdiff;h=c8ddc8472f8efcadafc1ef53ca1d863415fddd5f

**Comment by dcbaker** [comment]
Okay. That seems reasonable then. Can you add longarch to the documentation, docs/markdown/refereence-tables.md has a table of support cpu families in it that needs to be updated.

**Comment by yetist** [comment]
@dcbaker 

> Okay. That seems reasonable then. Can you add loongarch to the documentation, docs/markdown/refereence-tables.md has a table of support cpu families in it that needs to be updated.

Done.

**Comment by jpakkane** [comment]
That binutils patch also has `loongarch32`. Should this one have it also?

**Comment by yetist** [comment]
> That binutils patch also has `loongarch32`. Should this one have it also?

Yes, but there is no loongarch32 system that can test meson, so I removed the parts that have not been tested.
Maybe it should be added later.

**Comment by jpakkane** [comment]
> Maybe it should be added later after 32 bit system can test meson?

That works fine.

**Pull request merged**
