### PR TITLE
Make backend option read-only

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Review by eli-schwartz — APPROVED** [review]
LGTM, very nice approach.

**Comment by xclaesse** [comment]
Hm, there is a complication: `--backend=vs` will change the option value to `vs2022` automatically and that's causing the unit test to fail on CI. We can easily allow that change by passing `first_invocation=True`, but then `--reconfigure --backend=vs` will fail even if user just repeated the exact option they initially gave. I would say we can ignore that problem and use is forced to use `--reconfigure --backend=vs2022`?

**Comment by xclaesse** [comment]
@eli-schwartz added an extra commit to make it pass the CI.

**Comment by xclaesse** [comment]
macos failure seems unrelated, it fails in master too.

**Pull request merged**
