### PR TITLE
Use python3 in some tests which were still using python

### PR DESCRIPTION
**Pull request by seb128**
The unversioned command is deprecated and removed from some distributions

### CODE REVIEW

**Comment by jpakkane** [comment]
Should this go in 0.53.1?

**Comment by seb128** [comment]
0.53 failed to build on Ubuntu, i've added that patch but seems it's probably missing one edit since the update failed with
https://launchpadlibrarian.net/460020647/buildlog_ubuntu-focal-amd64.meson_0.53.0-1ubuntu1_BUILDING.txt.gz

'  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python': 'python'


meson.build:18:2: ERROR: <ExternalProgram 'python3' -> ['/<<PKGBUILDDIR>>/tmpt1fpn9vs/binary_wrapper0.py']> is not a valid python or it is missing setuptools'

**Comment by seb128** [comment]
I'm probably not going able to figure out/resolve that remaining problem before calling a day today, sorry, I will try to pick that up after the w.e but if someone has a clue what's wrong and want to fix it before please do

**Comment by jpakkane** [comment]
Let's merge this since it is useful on its own.

**Pull request merged**
