### PR TITLE
Add completion scripts for Bash and Zsh

### PR DESCRIPTION
**Pull request by 1ace**
Haven't had time to try and get the list of options to complete `-D`, but I'll try and add that as a follow up when I get the time.
Also left to do: `meson configure`, `meson test`, `meson introspect`.

### CODE REVIEW

**Comment by jpakkane** [comment]
How does this compare functionality-wise to #2071?

**Comment by 1ace** [comment]
> How does this compare functionality-wise to #2071?

I wasn't aware of it, I didn't think to check :see_no_evil:

I didn't test it, but from a quick look, #2071:
- has partial support for completing arguments for `mesonconf`/etc., but using the old, deprecated names
- doesn't support completing the value of the arguments, except the ones taking a file or folder, and the tests for `mesontest`
- is for zsh only, while I'm adding bash completion as well (I mostly use bash personally so I care about it more :P)

I'm happy to drop the zsh script in my PR, let you merge the bash completion only.
That said, there's no urgency, I'll try and add the features I mentioned to both scripts anyway, so you can also simply consider this PR a WIP and wait for me to do this all before merging.

Should I import @porrided's good parts into my script, or let him modify his PR to add the good parts from mine?

**Comment by jpakkane** [comment]
The reason that was not yet merged was that we wanted to match zsh's license so it could be submitted upstream if they wanted it. What about this one? Bash is probably trickier because IIRC the FSF requires a CLA.

**Comment by 1ace** [comment]
Completion scripts belong to with the program they complete, otherwise they would go out of date and basically never work.
For the license, my go to is usually MIT, but I'm happy to put it under whatever licence is best for you and/or bash/zsh.

**Comment by 1ace** [comment]
Oh btw, I have an almost ready implementation of the "complete this option" feature for `-D` (including option values for combo and booleans), I'm hoping to include it to this PR on Sunday.

**Comment by bluetech** [comment]
@1ace Can you install the completions? According to [systemd](https://github.com/systemd/systemd/tree/master/shell-completion):

- For bash, it should be installed in `completionsdir` from the `bash-completion` pkgconfig, or to `$(datadir)/bash-completion/completions` otherwise.
- For zsh, it should be installed in `$(datadir)/zsh/site-functions/`.

> Completion scripts belong to with the program they complete

I agree with that FWIW.

**Comment by bluetech** [comment]
BTW, since meson appears to be using `argparse`, it might make sense to try and generate the completions automatically, instead of writing them by hand. From a quick search I found two projects which claim to do that: [argcomplete](https://argcomplete.readthedocs.io/en/latest/), [python-selfcompletion](https://github.com/dbarnett/python-selfcompletion). Might serve as inspiration.

**Comment by porrided** [comment]
> from a quick look, #2071:
> has partial support for completing arguments for `mesonconf`/etc., but using the old, deprecated names

Now it supports modern ones as well. :) Even more, I dropped the old syntax for `meson setup`.

> Should I import @porrided's good parts into my script, or let him modify his PR to add the good parts from mine?

If you'd prefer to work on the `bash` completion script, one way to handle this would be to keep this PR for the `bash` script and #2071 for `zsh`.

As of now your PR puts the completions in another top-level directory. A tidier place for them would be something like `data/shell-completions/bash/meson`

> I have an almost ready implementation of the "complete this option" feature for -D
That would be awesome!

**Comment by jpakkane** [comment]
That MR has been merged, please update this to match. Thanks.

**Comment by jpakkane** [comment]
ping

**Comment by 1ace** [comment]
Haven't forgotten, just haven't had time to work on it much :upside_down_face:
I'll try to finish this during these holidays, should be done well in time for 0.45

**Comment by jpakkane** [comment]
ping

**Comment by jpakkane** [comment]
Ping again. It would be nice to get this merged.

**Comment by jpakkane** [comment]
What's the status of this MR? Will it be updated or should we just close it to reduce clutter on the tracker?

**Comment by 1ace** [comment]
Sorry for always forgetting to reply, but I've been working on it every now and then.

I just updated it with the current state. It's not done, but a lot of it works :)

**Comment by jpakkane** [comment]
Is the current state good enough for merging (i.e. improves things and does not obviously break anything)?

**Comment by 1ace** [comment]
Well technically yes, it's strictly better than not having completion, but let me have a quick pass to double-check and cleanup a bit before you merge it :)

**Comment by jpakkane** [comment]
Standing by ...

**Comment by 1ace** [comment]
I just had a quick look, not everything works and there's a bunch of flags that are not being suggested, so lots of work still, but it's good enough, so just go ahead and I (or other people) can fix it up later.

Thanks for your patience 🙈

**Pull request merged**
