### PR TITLE
docs: fix one 'target' that should be 'host'

### PR DESCRIPTION
**Pull request by Ericson2314**
The target platform of cross compiler is the host platform of the project being built.

CC @eternaleye

### CODE REVIEW

**Comment by sarum9in** [comment]
Please add `[skip ci]` to commit first line when you make documentation-only changes.
http://mesonbuild.com/Contributing.html#skipping-integration-tests

**Comment by Ericson2314** [comment]
Sorry about that. I force pushed with that. (hopefully the old builds  can be canceled releatively easily.)

**Comment by sarum9in** [comment]
It's okay, but you need to put it into the first line of commit as documentation says.

**Comment by Ericson2314** [comment]
..3 AppVeyor builds later :sweat_smile:

**Comment by Ericson2314** [comment]
Happy to provide more explanation if anyone wants it, too.

**Comment by jpakkane** [comment]
Thanks for spotting this.

**Comment by Ericson2314** [comment]
This is sort of an "opaque" fix, so I added more information in https://github.com/mesonbuild/meson/pull/3281 . Hope it's useful!

**Pull request merged**
