### PR TITLE
Normalize the path of a configured file to avoid dupes

### PR DESCRIPTION
**Pull request by nirbheek**
Several targets can refer to the same input file to configure_file in different paths, so normalize it to avoid duplicate filenames in the build file. Ninja warns about this, and we test for it too now.

This is easy to reproduce with the attached test case on Windows. The conffile gets added once as `subdir/testinput.in` and once as `subdir\testinput.in`. Then the first path is converted to the second path while writing out the Ninja build file. `os.path.normpath` converts `/` to `\` and avoids it in the first place.

Again, this would not have been a problem if we used an immutable `File` type. ;)

### CODE REVIEW

**Comment by nirbheek** [comment]
Tests were failing because we use `ninja` `1.5.3.git` for the tests and the `-w dupbuild=err` option was added in `1.6.0`. I've fixed `run_tests.py` to check the ninja version before adding that option, but maybe we should upgrade one of the CIs to use the latest ninja and the other should keep running the oldest Ninja version that we support.

**Comment by jpakkane** [comment]
Both Fedora and Debian unstable have Ninja >=1.6.0. Let's just raise the minimum required Ninja version to 1.6. rather than add conditional logic.

**Comment by nirbheek** [comment]
PR updated! But now the CIs fail, so please fix CIs. ;)

**Comment by jpakkane** [comment]
CI updated, repoking should make it work.

**Comment by nirbheek** [comment]
Fixed!

**Pull request merged**
