### PR TITLE
Wrap: Use git instead of patch by default

### PR DESCRIPTION
**Pull request by xclaesse**
This solves problems with Strawberry Perl providing patch.exe on Windows with an unconsistent line ending support.

Fixes: #12092

### CODE REVIEW

**Comment by tristan957** [comment]
s/unconsistent/inconsistent

**Comment by tristan957** [comment]
> Well, I think there's a decent chance we need to hard mask perl's version of patch.exe, if it's going to behave unusually surprisingly.

Do you think this PR should tackle this comment too? I think we already do something for pkg-config?

**Comment by tristan957** [comment]
https://github.com/mesonbuild/meson/blob/d2dfef5205f031ab10591899a1fc5048ea6f4134/mesonbuild/dependencies/pkgconfig.py#L216

**Comment by tristan957** [comment]
Looks not possible to discover this given the discussion in the issue thread.

**Review by tristan957 — APPROVED** [review]

**Comment by xclaesse** [comment]
I think it's not limited to Perl, there are different patch implementation and it depends how they deal with line ending. I think using git gives us a least something consistent across all platforms.

**Review by dvrogozh — APPROVED** [review]
This should improve applying patches to submodules which is one of key features of meson. Suggest to merge.

patch.exe is available from multiple origins which proves to have inconsistent behavior due to patches applied on top (or not applied) during build of the application. Like MSYS is well patched, but original patch.exe is not. See #12092 for details.

**Pull request merged**
