### PR TITLE
Fix dep.get_variable() with empty string default_value

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
This fix regression introduced by https://github.com/mesonbuild/meson/pull/9729.

**Comment by xclaesse** [comment]
CC @dcbaker 

I haven't reviewed the rest of that PR, maybe there are other similar cases?

**Review by dcbaker — APPROVED** [review]
LGTM, thanks for fixing this.

**Comment by nirbheek** [comment]
https://github.com/mesonbuild/meson/pull/9729 is not in 0.61, so this doesn't need cherry-picking. However, I have backported the unit test so we know that this is still working.

**Pull request merged**
