### PR TITLE
setup.py: install scripts from build_dir 

### PR DESCRIPTION
**Pull request by floppym**
This ensures the installed scripts will have updated shebangs.

Fixes: #1677

### CODE REVIEW

**Comment by floppym** [comment]
This is an alternative to #1678 which avoids symlinks.

**Comment by jpakkane** [comment]
Seems reasonable to me. @nirbheek?

**Comment by nirbheek** [comment]
+1 as long as it works as expected on Windows too.

**Comment by floppym** [comment]
It seems to be have the same way it did before on Windows.

**Pull request merged**
