### PR TITLE
Fix bogus parameter passed to LLVMDynamicLinker (llvm-mingw regression)

### LINKED ISSUE #6799: TypeError when setting up a build directory with LLVM linker
**Describe the bug**
https://gist.github.com/Akaricchi/23cde7c6782a150af568db920f17a5af

**To Reproduce**
Try to set up a build directory with the [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) cross toolchain. Not sure if native compilation is affected.

**Expected behavior**
Successful generation of the build directory.

**system parameters**
* Cross build (windows i686 via llvm-mingw)
* openSUSE Tumbleweed
* Python 3.8.2
* meson 0.53.999 (b54e557a40497a0f9080e32cd0da91b2b59762cc)
* ninja 1.10.0

### PR DESCRIPTION
**Pull request by Akaricchi**
Dynamic typing sucks!

Fixes #6799

### CODE REVIEW

**Comment by Akaricchi** [comment]
@jpakkane test failure looks totally irrelevant

```
[2/4] rustc --crate-type cdylib --crate-name stuff -g --emit dep-info=stuff.d --emit link -o libstuff.so -C prefer-dynamic '../test cases/rust/4 polyglot/stuff.rs'
[3/4] /usr/bin/python3 /home/runner/work/meson/meson/meson.py --internal symbolextractor '/home/runner/work/meson/meson/b cbbf05b2b1' libstuff.so libstuff.so 'stuff@sha/libstuff.so.symbols' 
[4/4] cc  -o prog 'prog@exe/prog.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libstuff.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/' '-Wl,-rpath-link,/home/runner/work/meson/meson/b cbbf05b2b1/'
FAILED: prog 
cc  -o prog 'prog@exe/prog.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libstuff.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/' '-Wl,-rpath-link,/home/runner/work/meson/meson/b cbbf05b2b1/'
/usr/bin/ld: warning: libstd-c32b051c3aafd36c.so, needed by libstuff.so, not found (try using -rpath or -rpath-link)
libstuff.so: undefined reference to `std::io::stdio::_print::h7e1d4022dd9ebaea'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by jon-turney** [comment]
Odd that this didn't show up in existing msys2 clang tests, so maybe a clang cross to Windows test is also needed...

**Comment by dcbaker** [comment]
I think this only shows up if you're using vanilla clang on windows compiled with gnu-style ld, I think with mingw we hit the nix_linker path instead. I've got a WIP branch to finish breaking up the linker and compiler representations that combines the windows + nix logic into a single function that I hope will be more reliable than what we have now.

**Comment by Akaricchi** [comment]
>I think this only shows up if you're using vanilla clang on windows compiled with gnu-style ld, I think with mingw we hit the nix_linker path instead.

This triggered in a cross build from Linux, with gnu-style LLD.

**Comment by dcbaker** [comment]
In that case we really should run at least some tests with clang -> windows in the CI

**Comment by jon-turney** [comment]
> In that case we really should run at least some tests with clang -> windows in the CI

This should be very straightforward to add now:  Hopefully just install the packages, add the cross-file, and reference it in the appropriate place in .travis.yml.

**Pull request merged**
