### PR TITLE
Always use utf-8 to write configured file and warn if the encoding is not UTF-8 compatible

### LINKED ISSUE #1085: UnicodeEncodeError in mesonlib.do_conf_file()
```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 283, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 171, in generate
    intr.run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1336, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1358, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1352, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1473, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 66, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2209, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1358, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1352, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1473, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2257, in func_configure_file
    mesonlib.do_conf_file(ifile_abs, ofile_abs, conf.held_object)
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonlib.py", line 292, in do_conf_file
    f.writelines(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 13: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by nirbheek**
Closes #1085

### CODE REVIEW

**Comment by QuLogic** [comment]
The locale is about text (consoles, file contents, sorting, etc.), but the file system is not tied to it. For that, you can check `sys.getfilesystemencoding`. Theoretically, one should always use that encoding when referring to files on disk (or treat the values as `bytes`; there is no prescribed encoding on many filesystems.) Practically, utf-8 seems to have won on Linux systems, but I'm not so sure about others. For example, this check causes a warning on AppVeyor, and I doubt Windows even has a 'utf-8' setting.

**Comment by tp-m** [comment]
As I understand it, `sys.getfilesystemencoding` is about the encoding of the **filenames** not the **content** of the files. Writing out files in UTF-8 seems fine to me, and makes sense IMO.

**Comment by nirbheek** [comment]
@tp-m is right; Python always writes bytes to files. It requires the input data to be of type `bytes` if you use `wb` (which means you need to manually convert the `str` to `bytes`). If you use `w` and pass it a `str` string, it will try to encode that into your preferred locale before writing to the file. This will fail if you try to write utf-8 strings to a file when your encoding is a strict subset of utf-8. However, this should work if you use any Unicode encoding since conversion there is always lossless.

Windows does have a [UTF-8 locale](https://msdn.microsoft.com/en-us/library/windows/desktop/dd374081(v=vs.85).aspx): [code page 65001](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx). However, I can't seem to figure out how to actually make Windows use it. `chcp` doesn't have any effect anywhere.

I agree though that just reporting a warning without mentioning a resolution is useless. Will dig more.

**Comment by QuLogic** [comment]
Yes, I know the difference, but I'm pointing out that both the comment and the warning are muddling both of these things together.

**Comment by nirbheek** [comment]
This PR wasn't ready to be merged because of @QuLogic's concerns, but I guess I'll just open a new PR with a proper fix for Windows.

**Pull request merged**
