### PR TITLE
Various yelp fixes

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by TingPing** [comment]
Maybe I'm blind but I don't see the error in the failing CI?

**Comment by jpakkane** [comment]
The list of installed files is not up to date:

    Reason: Expected file usr/share/help/de/meson-symlink/media/test.txt missing.

**Comment by TingPing** [comment]
It is being made: `Symlinking /root/i di57clii/usr/share/help/de/meson-symlink/media/test.txt to /usr/share/help/C/meson-symlink/media/test.txt`

Does it not understand symlinks?

**Comment by jpakkane** [comment]
If the symlink points to a non-existing file then that probably gets flagged as not existing.

**Comment by TingPing** [comment]
Hmm, well it not existing is correct because of DESTDIR. Dunno if making that a non-fatal issue is wanted for potential future tests.

**Comment by jpakkane** [comment]
Changing the check to check for existance or symlinkness is fine by me.

**Pull request merged**
