### PR TITLE
Recognise more include search path opts when populating 'NMakeIncludeSearchPath'...

### PR DESCRIPTION
**Pull request by GertyP**
field, used by visual studio intellisense in the lighter weight nmake-style vcxprojs (these are the style of project's generated through meson setup with '--genvslite')

Added to existing '/I' and '-I' extraction with '-isystem', '/clang:-isystem', '/imsvc', '/external:I', which are forms of 'system' header include search path options for gcc, clang, clang-cl, and cl (msvc).

Factored 3 separate 'extract_...(...)' functions into one since they were always called together on the same args; a new combined '_extract_nmake_fields(...)' func avoids repeated iterations and checks.

### CODE REVIEW

**Comment by tristan957** [comment]
I added it to the 1.3.0 milestone.

**Comment by GertyP** [comment]
Just wondering, since this has been pending for a while, if there's anything I've missed that people still want changing or anything that would help get this pulled in to master, or is it just a case of waiting for someone to find the time while I occasionally check and keep this rebased with updates from master to keep on top of potential conflicts?

**Comment by tristan957** [comment]
@bruchar1 why chance you can test this?

**Comment by GertyP** [comment]
@jpakkane It would be helpful to know if there's anything I've overlooked that's preventing this from being merged.  I'd also understand if there's a bottleneck on reviewers getting overloaded with PRs but either way, it would be good to clarify this situation.

The only check failure that I can see seems to be a cmake zlib version regex issue that I think corresponds to [this](https://gitlab.kitware.com/cmake/cmake/-/issues/25200), which looks like it requires an updated cygwin cmake package to fix.

**Pull request merged**
