### PR TITLE
add meson.get_external_property()

### PR DESCRIPTION
**Pull request by scivision**
`meson.get_external_property()` replaces `meson.get_cross_property()`, and also works for native files.

This allows Meson native-file `[properties]` to be used, avoiding the need for cumbersome platform-specific build processes like

* calling meson from a platform-specific Bash or Python script file
* long command line invocation of `meson setup`
* difficult to understand deeply nested `if..elif` to handle different platforms
* the need for end users to edit meson.build for their platform

In short, the platform-specific issues faced in cross builds are also partially faced where the end-user needs to load numerous external libraries, for example across various HPCs. 
Before this feature, I needed to use techniques as in the bullet-points above, which are generally anti-Mesonic.

---

Now I can make a `meson/` directory in my project with native-files for various HPC and OS containing the needed info for a complex stack with lots of external libs, and I tell the end users to configure like

* meson setup --native-file meson/pleiades.ini
* meson setup --native-file meson/homebrew.ini
* meson setup --native-file meson/tempest.ini
* meson setup --native-file meson/msys2.ini

And so on. The HPC systems in particular use arbitrary setups with broken or missing pkg-config files, with configs that change periodically.

---

The method meson.get_external_property('prop', 'fallback', native: true/false) is added.
The native file can contain properties like

```
[properties]
myprop1 = 'foo'
mydir2 = 'lib/custom'
```

Then from within `meson.build`

```meson
x1 = meson.get_external_property('myprop1')

thedir = meson.get_external_property('mydir2', 'libs')
```

fallback values are optional

### CODE REVIEW

**Comment by jpakkane** [comment]
Could we make the interface work like other cross/native properties that we have? That is, deprecate `get_cross_property` and instead have something like:

```meson
meson.get_external_property('foo')
meson.get_external_property('bar', native: true)
```

That is, if `native` kwarg is not defined gets the value from the native file when native compiling and from the cross file when cross compiling.

**Comment by scivision** [comment]
@jpakkane I reimplemented this as meson.get_external_property() as you noted above.

**Comment by jpakkane** [comment]
The version numbers should be updated to 0.54. A rebase should also be done, just to get the CI confirmation once more.

**Comment by scivision** [comment]
@jpakkane this PR was rebased and all CI passes

**Comment by Ericson2314** [comment]
Oh I missed this, the `[properties]` section is kinda gross because it is so unstructured. I hope this won't make it harder to deprecate?

**Comment by dcbaker** [comment]
@Ericson2314, I'm still working towards properties being just a place to put random stuff for get_external_properties, and everything else will move to a structured section.

**Pull request merged**
