### PR TITLE
Let's try QuLogic's ninja patches again.

### PR DESCRIPTION
**Pull request by nirbheek**
This reverts commit 5eb64a6f3e47b570f544524ef48dc6ef0e4dce59.

### CODE REVIEW

**Comment by QuLogic** [comment]
Looks like Windows is working; are you trying to restore codecov at the same time?

**Comment by nirbheek** [comment]
No, the `--cov` was a merge conflict mistake by me. I'll do that separately. This is more important because it's been messing up our CI times massively.

The Linux build problems are new, but they seem relevant. Are you looking into them?

**Comment by QuLogic** [comment]
OK, that's weird; were there warnings when building? I cannot reproduce this locally. I checked out this PR, and ran `MESON_FIXED_NINJA=1 python3 run_tests.py` (using system ninja) which failed as expected and then ran `MESON_FIXED_NINJA=1 PATH=$PWD/../ninja:$PATH python3 run_tests.py` which worked.

**Comment by QuLogic** [comment]
I fetched the docker image, cloned ninja and meson in it and tests seemed to pass/fail in the expected manner as well.

**Comment by QuLogic** [comment]
`objdump -T ninja | grep strtoll` from your binary doesn't show anything, but it does in my local build; are you sure it's built from my branch?

**Comment by nirbheek** [comment]
My bad, I built the wrong branch on Linux :/ Updating and uploading now. Sorry!

**Comment by nirbheek** [comment]
Pushed, with the `--cov` argument removed which was added by mistake.

**Comment by nirbheek** [comment]
> test_source_changes_cause_rebuild (__main__.AllPlatformTests) ... ok

Works! This can go in now.

**Pull request merged**
