### PR TITLE
Invoke pip via the Python binary because the nonversioned binary no l…

### PR DESCRIPTION
**Pull request by jpakkane**
…onger exists.

### CODE REVIEW

**Comment by jpakkane** [comment]
Now changed to remove coverage altogether since it seems to be a constant source of problems.

**Comment by nirbheek** [comment]
I don't think it's a source of problems. I think we need to remove the "disable it only on windows for docs changes" bits and it'll be really nice to have.

**Comment by nirbheek** [comment]
Also, I think you can use `python3.4` and `pip3.4` and everything will work fine.

**Comment by jpakkane** [comment]
Don't some test platforms have different Python versions? One would think that brew would install 3.6 at least.

**Comment by nirbheek** [comment]
I'm away from my computer so I can't test it, but we can add platform-specific code as needed, can't we?

**Comment by jpakkane** [comment]
Presumably yes, but who volunteers to do that? Currently this is broken, it's preventing all merges and the only way to debug it is to submit PRs, wait 30 minutes or so and then do blind debugging.

**Comment by nirbheek** [comment]
Let's merge this for now then. I'll look at the codecov/pip problem tomorrow.

**Comment by QuLogic** [comment]
https://github.com/travis-ci/travis-ci/issues/8363 ?

**Comment by nirbheek** [comment]
So I guess we should use `pyenv global system 3.4`? FWIW, my older PRs which still use the old pip3 command are magically working again: https://travis-ci.org/mesonbuild/meson/jobs/273827893

**Pull request merged**
