### PR TITLE
dependencies: Don't let pkg-config strip out -I${prefix}/include cflags

### PR DESCRIPTION
**Pull request by nirbheek**
Sometimes pkg-config tries to be extra-smart and removes includes that are in the "standard prefix", which it derives from the location of the .pc file. This causes all '-I${prefix}/include' cflags to be stripped and causes a compilation error with the MSVC compiler because the headers aren't found. It is likely that the same problem will occur with gcc/clang when using external dependencies provided by the system.

### CODE REVIEW

**Comment by nirbheek** [comment]
To clarify, this behaviour by pkg-config is a major problem when `prefix` is not `/usr.

However, after thinking about it, I realized that `cc.has_header` has the same issue when `prefix` is not `/usr`, so one really needs to set `C_INCLUDE_PATH` on gcc/clang and `INCLUDE` on msvc for everything to work. Same with `cc.find_library` and `cc.links`, etc (`LIBRARY_PATH` and `LIB` need to be set). Same thing happens with autotools.

Since this behaviour by `pkg-config` is only unexpected when `prefix` is not `/usr`, perhaps instead of setting `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` we can pass `--dont-define-prefix` which disables the auto-detection of prefix for a pkg-config file. This will cause pkg-config to only discard `-I/usr/include` from Cflags.

**Comment by jpakkane** [comment]
It seems weird that the latter is not the default for pkg-config. Is there any particular reason for the current behaviour apart from hysterical raisins?

**Comment by nirbheek** [comment]
According to commit messages, pkg-config overrides `$prefix` based on the installation directory so that you can move your prefix around and have pkg-config use the new (correct) `$prefix` value.

```
* main.c: (Win32): Add option --dont-define-prefix on Windows. The
option prevents pkg-config from automatically defining an
overriding value for the "prefix" variable.

Unless this option is used, set "prefix" to pkg-config's
installation directory, i.e. assume that the packages whose
configuration files are found in the same tree where
pkg-config.exe itself is, also have been configured to use the
same prefix. This means that a typical "developer package"
containg a subtree of headers, libraries, etc, including .pc
files, can be installed in any random location. As long as
pkg-config.exe is installed the same tree, things just should
work.
```

This sounds like a reasonable thing to do. The other feature that pkg-config has, is to strip out `${prefix}/include` and `${prefix}/lib`:
```
* pkg.c (verify_package): actually strip system -I/-L out of the
cflags/libs, unless you set an environment variable asking to
leave them in.
```
The warnings it used to give for that were:
```
Package %s has -I/usr/include in Cflags; this may cause problems and is not recommended
Package %s has -L/usr/lib in Libs; this may cause problems and is not recommended
```
It's not clear what these "problems" are. Perhaps it refers to include/library path orders getting messed up? System includes/paths should always be added last, and packages adding those themselves can cause the wrong headers/libraries to get picked up for other packages. A UNIX compiler will already look in those as a fallback (it will often even have other directories in that list for libc/compiler-specific things), so it isn't a problem most of the time.

However, with MSVC the compiler has its own list of 'system' prefixes and what pkg-config thinks is the 'system' prefix is a custom prefix for MSVC. Also in the case of a prefix that has been moved, the UNIX compiler's list will be wrong.

I think the system-flag-stripping should be disabled by pkg-config if the prefix in the file doesn't match the prefix of the file itself. What do you think?

However, we have to live with old pkg-config too, so I think we should also document this behaviour (and the workaround of setting `C_INCLUDE_PATH`, `INCLUDE`, `LIBRARY_PATH`, `LIB`) in the Reference Manual under `dependency()`.

**Comment by jpakkane** [comment]
> I think the system-flag-stripping should be disabled by pkg-config if the prefix in the file doesn't match the prefix of the file itself. What do you think?

With `--dont-define-prefix` or something more complex? Should we only do this on Windows or are there cases where cross compilation will come to bite us?

**Comment by nirbheek** [comment]
> > I think the system-flag-stripping should be disabled by pkg-config if the prefix in the file doesn't match the prefix of the file itself. What do you think?

> With --dont-define-prefix or something more complex? Should we only do this on Windows or are there cases where cross compilation will come to bite us?

Sorry for not being clear. I meant that we can't reliably fix this behaviour of pkg-config, and the behaviour is a bug, so it should be fixed upstream. On our end, I think we should only document this behaviour under the `dependency()` section of the reference manual or somewhere similar.

**Comment by nirbheek** [comment]
I've filed a bug about this; closing PR.

https://bugs.freedesktop.org/show_bug.cgi?id=94729

**Pull request closed without merging**
