### PR TITLE
coredata: refactor options to remember their names

### PR DESCRIPTION
**Pull request by Akaricchi**
All UserOption initializers now take a string name as the first argument.

Options are usually stored in `OptionKey: UserOption` dictionaries. For this reason, two helper functions were added to make instantiating such dictionaries easier and less error-prone.

`coredata.key_option_pair()` takes a string name or OptionKey instance, a UserOption-derived class, and a variable number of arguments. It returns a tuple of `(OptionKey, UserOption instance)`, where the OptionKey is the first argument (passed as-is or converted from the string), and the UserOption is instantiated with the name derived from the OptionKey, and the rest of the arguments passed through.

Example:
```python
p = coredata.key_option_pair('foo', coredata.UserStringOption,
                             'foo description', '')
# Equivalent to:
key = OptionKey('foo')
opt = coredata.UserStringOption(str(key), 'foo description', '')
p = (key, opt)
```

`coredata.key_option_dict` takes a variable number of tuples or list, each representing an option. It returns a `MutableKeyedOptionDictType`.

Example:
```python
opts = coredata.key_option_dict(
        (
                'foo', coredata.UserStringOption,
                'foo description', '',
        ),
        (
                'bar', coredata.UserStringOption,
                'bar description', '',
        ),
)
# Equivalent to:
opts = OrderedDict(
        coredata.key_option_pair(
                'foo', coredata.UserStringOption,
                'foo description', '',
        ),
        coredata.key_option_pair(
                'bar', coredata.UserStringOption,
                'bar description', '',
        ),
)
```

### CODE REVIEW

**Comment by Akaricchi** [comment]
The inspiration to do this came from tracking down test failures on #11175. One of the tests expected to see an option name in an error message which actually prints out option descriptions, which is not ideal behavior. It worked in the past because of the empty description to option name fallback, which that PR removes. I then realized that options don't know their names at all, except for feature options, where I discovered this line: https://github.com/mesonbuild/meson/blob/2fd5bd934e0e6dd26ad8c326a156a710f912b335/mesonbuild/coredata.py#L277

**Comment by Akaricchi** [comment]
I have no idea why the MPI tests are failing on macos-clang, but it doesn't look related to my changes.

**Comment by dcbaker** [comment]
I’ll try to have a look later, but the MPI tests are just flaky, sometimes their unit tests don’t work

**Comment by bruchar1** [comment]
This was done in #69d579415b924a6da5e24b354e338cb60ded78f6

**Pull request closed without merging**
