### PR TITLE
gnome: allow gdbus-codegen inputs to be generated at build time

### PR DESCRIPTION
**Pull request by bonzini**
Custom targets as sources to `gnome.gdbus_codegen` worked until version 0.60 of Meson, but broke in 0.61 because of the conversion to `typed_pos_args` and `typed_kwargs`. Reinstate this by adding custom targets to the decorators and mypy annotations.

Other methods in the gnome module accept generated sources just fine, since they (and `gnome.gdbus_codegen` too) are just syntactic sugar for custom_target; there is no reason to reject at least `custom_target`s and `CustomTargetIndex` objects. Generators are a bit more debatable because the generator is invoked twice; that should not be a problem for most uses, and it is in general preferrable to treat custom targets and generators the same way, but it could be considered a bug too. Therefore I left generator support as a separate commit, in case the preference is to leave them out.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
How exactly is a generator supposed to work here since that is usually produced into a compiled executable/library's private directory? At least semantically.

If somehow it works *anyway*, it's... hardly surprising that the generator is invoked too many times.

**Comment by eli-schwartz** [comment]
I actually did write out a clumsy version of this first commit that didn't include typing updates, a year ago. Yours is better.

But the reason I didn't submit it was because I couldn't find a case where it was being used in the wild in a practical manner, so I was not sure it mattered... presumably you do have a use case though.

**Comment by bonzini** [comment]
> hardly surprising that the generator is invoked too many times.

Absolutely, I wasn't sure how it's supposed to work so I made a separate commit.

The use case is simply compiling old versions of software with new meson. The usage has been removed since upstream, but behavioral changes in meson mean that packages in LTS distros fail to rebuild after a meson update.

In particular, when updating meson in RHEL to a newer version we found that 60 packages broke, all due to various deprecations that weren't keyed by the minimum version in project() or due to bugs like this one. If a package wants newer meson, distros should be able to do it with 2 package updates, not 62. Otherwise it's Autoconf 2.5x all over again, just without the m4. ;)

Rants aside, this wasn't even documented and it works for other methods in the module, so I don't think it was intentional.

**Comment by bonzini** [comment]
Ping @jpakkane

**Pull request merged**
