### PR TITLE
Fix D module version declaration.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Weird, how did this used to work?

BTW this was added in b13a95c30156c0c9ebf11ceb664acee08a835b2c so it seems very wrong to remove it. If the test case is wrong, then it still does need fixing in order to test the desired functionality another way.

**Comment by jpakkane** [comment]
It passes two arguments, `-fversion=testversion and -fversion=1` (or maybe it used colons instead of equal signs or something). Removing `1` drops the second `-fversion`. Maybe this is a thing that only works in DMD and/or LDC, but nod GDC?

**Comment by eli-schwartz** [comment]
```
$ ninja -C builddir/ -v                                                                        
ninja: Entering directory `builddir/'
[1/2] gdc -Itest-dep.p -I. -I.. -Wall -Wdeprecated -O0 -g -fversion=TestVersion -fversion=1 -J../views -Jviews -MD -MQ test-dep.p/test.d.o -MF test-dep.p/test.d.o.deps -o test-dep.p/test.d.o -c ../test.d
[2/2] gdc  -o test-dep test-dep.p/test.d.o -Wl,--allow-shlib-undefined -shared-libphobos
```

Works for me, using gdc. What was the error you got?

**Comment by jpakkane** [comment]
I have version 13.1 and there are both deprecation warnings about those numbers as well as plain out build failures (also in test case 9).

For example `bad argument for `-fdebug: 1`.

**Comment by eli-schwartz** [comment]
@jpakkane maybe my original patch -- made without much knowledge of D -- was incomplete because e.g. it never actually looks up that feature in the source code and is triggering some kind of unused-arguments lint? That's the only thing I can think of.

@rtbo, as someone that contributed a fair amount to D support in meson -- and as the original author of this test case (before I made that commit which is being reverted here) -- do you have an idea of what might be going on here?

**Comment by jpakkane** [comment]
What is fairly clear is that GDC 12 accepts `-fversion:1` as a command line argument but it causes a compilation error in GDC 13.

**Comment by eli-schwartz** [comment]
So 3 days ago Debian migrated gcc-defaults to default to 13 instead of 12, and this new gdc version triggers test issues. I see.

**Pull request closed without merging**
