### PR TITLE
interpreterbase: Add warning when built-in object method has no kwargs

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by jpakkane** [comment]
This would work better as decorator, like the one already in `interpreterbase` (though that one hard errors, so it can't be used here yet).

**Comment by xclaesse** [comment]
@jpakkane done.

**Comment by jpakkane** [comment]
Test failure seems relevant:

```
mesonbuild/ast/interpreter.py:319:43: error: Argument 1 to "flatten_kwargs" of "AstInterpreter" has incompatible type "Dict[BaseNode, BaseNode]"; expected "Dict[str, Union[Union[Union[str, int, float, bool], List[Any], Dict[Any, Any], InterpreterObject, ObjectHolder[Any]], BaseNode]]"
Found 1 error in 1 file (checked 27 source files)
```

**Comment by xclaesse** [comment]
@jpakkane remaining CI failure are not relevant, afaik.

**Comment by jpakkane** [comment]
Indeed.

**Pull request merged**
