### PR TITLE
WIP: get_option(): new type "path" that maps to pathlib.Path()

### PR DESCRIPTION
**Pull request by scivision**
following with #5768, #5611 we provide a new type "path" for `get_option()` and in `meson_options.txt` .
The primary purpose of the `path` option type is that it is expanded by `pathlib.Path` so that `-Dmyvar=~/foo` becomes `myvar == c:\users\username\foo` or /home/username/foo etc. as system-appropriate.

The future purpose of this type will be realized when Python 3.6 is the minimum version for Meson, in that we will be able to use pathlib.Path for paths throughout Meson instead of having to pass around str for Python 3.5 for shutil.which() and the like.

### CODE REVIEW

**Comment by QuLogic** [comment]
`find_program` with `~`? That doesn't sound right to me, hardcoding user-directories in your build file. The other ones made sense since they were specified by the user.

**Comment by scivision** [comment]
It's about finding programs where the location is specified with -Dfoopath=~/bin option.
Specifically, like when one has multiple versions of the same program installed and then the user can do
```sh
meson setup -Dfoopath=~/bin/foo2.1.0
```

and inside meson.build
```meson
find_program(get_option('foopath') / 'fooexec')
```

**Comment by nirbheek** [comment]
For that I'd rather we added a new option type called 'path' which will do the expansion while reading the value, so we don't have to litter the whole codebase with this.

**Comment by xclaesse** [comment]
+1 for annotating the option that it's a path, and do the conversion at startup.

**Comment by dcbaker** [comment]
It would be nice if this `path` type handled ~ and environment variables like `$HOME`.

**Comment by scivision** [comment]
I updated the first comment in this conversation to reflect the new direction of this PR as per suggestions above:
a new get_option() type "path" is processed by pathlib.Path().expanduser().

In the future, when we can assume Python >= 3.6, pathlib.Path() type may be freely passed in/out of classes and functions since in 3.6 Python stdlib functions and classes can work directly with pathlib.Path() instead of needed only `str`.

**Comment by xclaesse** [comment]
Looks good to me. Just a few comments:
- Would be nice to split type annotation in separate commit, it makes review harder to have many unrelated changes mixed.
- I guess at least the "prefix" builtin option could be changed from UserStringOption to UserPathOption. Probably sysconfdir, localstatedir and sharedstatedir too.

**Comment by scivision** [comment]
Thanks, I split the too-squashed commit and made all the built-in directory options UserPathOption

**Comment by scivision** [comment]
I am waiting with this PR as I can do what I need with a combination of:

* #6161 
* #6196 

Also, when Python 3.5 is deprecated ~2020 this will become more natural as we can more freely use pathlib.Path throughout Meson.

**Pull request closed without merging**
