### PR TITLE
cmake: Add CMake file API support

### PR DESCRIPTION
**Pull request by mensinda**
The file API will automatically be used when CMake >= 3.14
is detected. This new API is meant as a replacement for the
now deprecated CMake server API.

The new API (mostly) provides the same information in a
different format. Thus only a slight bit of refactoring was
necessary to implement this new backend.

### CODE REVIEW

**Comment by mensinda** [comment]
CMake 3.14 ist still fairly new, so I don't know if this code path is actually tested in the CI. If I am parsing things correctly, Travis should be currently using 3.12 because the docker image is based on Ubuntu cosmic.

**Comment by jpakkane** [comment]
It's using cosmic, because in disco running `dub` immediately segfaults. I'll try to update the CI image to eoin this weekend, the issue should be fixed in it.

**Comment by mensinda** [comment]
As far as I can tell from the [ubuntu packages list](https://packages.ubuntu.com/search?suite=eoan&searchon=names&keywords=cmake) eoan also only provides 3.13 in the repositories. However, the file API was first introduced in 3.14.

Maybe use pip: https://pypi.org/project/cmake ?

**Comment by jpakkane** [comment]
Oh, it seems that Debian has not updated CMake after Buster's release. I wonder why, that's a bit problematic...

**Comment by mensinda** [comment]
Not sure what's going on with debian / ubuntu packaging. I also haven't found a PPA for CMake. Installing CMake via pip seems to be the best option for now.

Alternatively, are you open for an Arch-based docker image https://hub.docker.com/r/archlinux/base? I would be willing to set up the docker file.

**Comment by jpakkane** [comment]
We use an Ubuntu image on purpose because it is by far the most popular platform for Linux development.

**Comment by jpakkane** [comment]
CI image is updated. FWICT Azure should run a new enough CMake. It is a bit unfortunate that we don't print the CMake version. Could you add a function in `run_project_tests.py` called `print_tool_versions` that is called after `detect_system_compiler` that detects if CMake is installed and, if it is, prints its version string? We can add other auxiliary tools to that same function as necessary.

**Comment by mensinda** [comment]
Done. In Azure, the CMake version is new enough (even in cygwin). However, [Travis still uses 3.13.4](https://travis-ci.org/mesonbuild/meson/jobs/600285959#L859). Do we keep it this way, to also test the legacy CMaker server API code path?

**Comment by jpakkane** [comment]
Travis will use whatever the latest Ubuntu ships with. It'll be that way at least until 20/04 is released, since they don't update software versions within a release (only bugfixes).

**Comment by scivision** [comment]
So it sounds like we test the CMake file API on Azure and the deprecated CMake server API on Travis?

**Comment by mensinda** [comment]
Essentially yes.

**Pull request merged**
