### PR TITLE
Fix macOS dylib naming and compatibility version — DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by nirbheek**
This is v2 of https://github.com/mesonbuild/meson/pull/680, to fix our dylibs a bit.

* Include the major version in the dylib name (not the minor or micro)
* Add `-compatibility_version` (after testing, I will also add `-current_version`)
* Add tests that check whether you can actually link against the built libraries with `-lfoo` syntax
* Add a test to ensure that the compatibility version is set properly by trying to run with a different library with an older compatibility version at run time.

### CODE REVIEW

**Comment by nirbheek** [comment]
screenshot from 2017-03-04 19-19-03

I don't know why you can't push to the branch though...

**Comment by jpakkane** [comment]
Is this ready for review now?

**Comment by jpakkane** [comment]
:crossed_swords: conflicts.

**Comment by jpakkane** [comment]
This message is posted to every outstanding merge request.

We have transitioned from Github wiki to our new documentation system that generates all documentation directly from the Git repo. This means that from now on every merge request must come with corresponding documentation changes.

If your MR requires documentation changes, do the necessary changes to files in `docs/markdown`.

If your MR adds a new feature, add a description to the release notes in `docs/markdown/Release-notes-for-0.41.0.md`.

If this commit is just a bugfix with no functional changes, you don't need to do anything.

Thank you

**Comment by jpakkane** [comment]
Ping.

**Comment by jpakkane** [comment]
This is out of date and there are other MRs already so closing this to reduce clutter.

**Pull request closed without merging**
