### PR TITLE
Add get_path() and get_version() methods to the python3 module

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by jpakkane** [comment]
We have been moving away from methods starting with `get_` into ones without it. Would it make sense to call these `python_version()` and `sysconfig_path()` to make it clearer what they refer to?

Also, sysconfig returns just the two first numbers of the version (i.e. `3.5`). People probably expect it to return all three like what `python3 --version` does. A more appropriate name for the first two numbers could possibly be `language_version` or somesuch.

**Comment by TingPing** [comment]
> We have been moving away from methods starting with get_ into ones without it. Would it make sense to call these python_version() and sysconfig_path() to make it clearer what they refer to?

This seems inconsistent with the verbiage of the built-in functions, they are always verb_noun. So `get_foo` fits in. Your call though.

> Also, sysconfig returns just the two first numbers of the version (i.e. 3.5). People probably expect it to return all three like what python3 --version does. A more appropriate name for the first two numbers could possibly be language_version or somesuch.

I was wondering which people would prefer and I think x.y is probably most often needed, for example if you are manually building a path or something you don't want to deal with splitting yourself. The micro version is rarely used even in dependency checks so it seemed fine.

Renaming it for clarity makes sense.

**Comment by nirbheek** [comment]
built-in functions are inconsistent. We have `get_cross_property()`, `get_compiler()`, but we also have `backend()`, `current_source_dir()`, `project_version()`, `version()`, etc. I think it makes sense to avoid the `get_` verb if possible because it's a bit redundant.

**Comment by jpakkane** [comment]
These should be tested. Does not need to be fancy, a `version_compare` for the language version and not startswith / for sysconfig_path. They don't need their own dir, just add to `python3/1 basic`.

**Pull request merged**
