### PR TITLE
Made has_function survive optimization flags. Closes #1053.

### LINKED ISSUE #1053: has_function fails to detect missing dependencies with CFLAGS=-O1
GStreamer uses `cc.has_function('backtrace', prefix : '#include <execinfo.h>')` to check whether it can use backtrace-related functions. Using these functions doesn't require linking extra libraries on GNU/Linux, but it is required to link with `-lexecinfo` on FreeBSD. Therefore, I have to write a meson alternative to autoconf `AC_SEARCH_LIBS` macro.

I implemented it with this patch: https://bugzilla-attachments.gnome.org/attachment.cgi?id=339827
However, this only worked with `CFLAGS=-O0`:
```
Has header "execinfo.h": YES
Checking for function "backtrace": NO    # without -lexecinfo
Library execinfo found: YES
Checking for function "backtrace": YES   # with -lexecinfo
```

If I set `CFLAGS=-O1` in the environment, the first `has_function` test didn't fail and caused undefined reference error when linking `libgstreamer-1.0.so`:
```
Has header "execinfo.h": YES
Checking for function "backtrace": YES   # without -lexecinfo
...
[99/442] Linking target gst/libgstreamer-1.0.so.0.1100.0
FAILED: gst/libgstreamer-1.0.so.0.1100.0 
gst/gstreamer-1.0@sha/gstinfo.c.o: In function `generate_backtrace_trace':
gst/gstinfo.c:2707: undefined reference to `backtrace_symbols'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tested it on FreeBSD 11.0 with clang 3.8.0 and binutils 2.27.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by nirbheek** [comment]
I'm fairly certain we should fix this by changing the order in which we add the `-O0` to CFLAGS.

**Comment by jpakkane** [comment]
The tests themselves need to be robust against any combination of optimization flags. Otherwise this will keep breaking in subtly different ways over and over again.

**Comment by nirbheek** [comment]
On the contrary, trying to fix tests by trying to be smarter than a compiler is an arms-race against compiler developers that we cannot win. Meson will magically/mysteriously keep breaking with newer versions of compilers, or with different compilers.

The sane way out is to force the compiler to not do any optimization at all, which is what we try right now but we pass the flags in the wrong order so it gets overriden.

**Comment by jpakkane** [comment]
We should do both, because defense in depth is the only way to go.

**Comment by nirbheek** [comment]
Fair enough! I'll be back tomorrow, and will make a PR for that + unit tests.

**Pull request merged**
