### PR TITLE
Always run all framework tests on all platforms

### PR DESCRIPTION
**Pull request by jon-turney**
Always run all framework tests on all platforms, but allow them to be skipped, when not running under CI for linux.

This should:
- make framework tests more useful in a non-CI environment, where all the prereqs might not be installed, as tests are allowed to be skipped
- run applicable framework tests on platforms other than linux
- preserves the original intent of having framework tests run under CI be required to pass, not get skipped

### CODE REVIEW

**Comment by jon-turney** [comment]
Closes #2325

**Comment by nirbheek** [comment]
We probably want to find a way to have these error out instead of skipping when run on CI environments that are supposed to have those dependencies available. Otherwise the CI will silently signal success if something breaks in a special way, or if dependencies disappear without us knowing.

**Comment by jon-turney** [comment]
> preserves the original intent of having framework tests run under CI be required to pass, not get skipped

> We probably want to find a way to have these error out instead of skipping when run on CI environments that are supposed to have those dependencies available.

I'm sorry, I don't understand what change you are asking for here.

**Comment by nirbheek** [comment]
> I'm sorry, I don't understand what change you are asking for here.

Oops, I guess I should've read the patch. :)

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Pull request merged**
