### PR TITLE
Add a testcase for linking C and C++ static archives into a shared li…

### PR DESCRIPTION
**Pull request by dcbaker**
…brary

This exercises a regression where the C rather than C++ linker is
chosen, resulting in symbol errors.

Test for #1653 

This test fails against master, but passes against 0.39.1

### CODE REVIEW

**Comment by nirbheek** [comment]
I've added commits that should fix this for internal C++ libraries and for external libraries found with `cxx.find_library()`. Extending this to other dependency types is possible, and I'll add patches for that next. I think the changes are too invasive to go into tomorrow's release.

In the meantime we have two other issues with this:

1) We need a way to test linking to external C++ libraries
2) The test currently fails to build on MSVC 2010:

```
c:\projects\meson\test cases\common\146 c and cpp link\foo.cpp(18) : error C2552: '`anonymous-namespace'::numbers' : non-aggregates cannot be initialized with initializer list
        'std::vector<_Ty>' : Types with a base are not aggregate
        with
        [
            _Ty=int
        ]
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
A third problem is on Cygwin (GCC 5.4):

```
FAILED: cppfoo@sta/foo.cpp.o 
c++  '-Icppfoo@sta' '-I.' '-I../test cases/common/146 C and CPP link' '-fdiagnostics-color=always' '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-O0' '-g' '-MMD' '-MQ' 'cppfoo@sta/foo.cpp.o' '-MF' 'cppfoo@sta/foo.cpp.o.d' -o 'cppfoo@sta/foo.cpp.o' -c '../test cases/common/146 C and CPP link/foo.cpp'
../test cases/common/146 C and CPP link/foo.cpp:18:35: error: in C++98 ‘{anonymous}::numbers’ must be initialized by constructor, not by ‘{...}’
     std::vector<int> numbers = {61};
                                   ^
../test cases/common/146 C and CPP link/foo.cpp:18:35: error: converting to ‘std::vector<int>’ from initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<int>]’
```

For ease of reading, that last error is:

> converting to ‘std::vector<int>’ from initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<int>]’

**Comment by dcbaker** [comment]
That is legal in C++11, but not in earlier standards. GCC 6 defaults to C++11, while GCC 5 and clang default to C++03/98 (I now know). I've pushed a change to set the std to C++11, but I can change the code to C++03 if that's better.

**Comment by dcbaker** [comment]
...and that doesn't work for vs10, I'll change it to use c++98 instead.

**Comment by nirbheek** [comment]
Do you think you could also find a way to link to an external C++ library from C in the same test? At least Boost and Qt will be available on the CI.

**Comment by dcbaker** [comment]
sure. Boost should be relatively easy since it has a vector-like class or two.

**Comment by nirbheek** [comment]
Using Boost this way doesn't really test that though, because the static library is already C++. We need a C++ library that exports an `extern "C"` API that must be accessed by linking to that C++ library.

It'll probably be very difficult to find that in Boost or Qt, so we'll have to undertake a hack. I'll add some commits.

**Comment by dcbaker** [comment]
hmm, and that change is causing the build to fail anyway :/

**Comment by nirbheek** [comment]
That's because boost is only available on some of the build matrices. I'll revert that change.

**Comment by nirbheek** [comment]
I think this PR can go in as it is now. It covers all the cases that have been reported so far.

What's missing is support for deducing the implementation language of external dependencies other than `ExternalLibrary`. That's easy for some dependency types (Boost) and impossible for others (pkgconfig, frameworks). For pkgconfig and frameworks, we'll probably want to expose a kwarg that lets users set it. For Boost, we need to implement support for the `static:` kwarg so that the test actually works.

I have a WIP patch to do some of this, but it's a lot of churn so we should punt that bit for the next release.

**Pull request merged**
