### PR TITLE
Avoid use of deprecated command form on the cross compilation doc page

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
It is probably somehow because the author of the page assumed that people wouldn't create the cross files inside the source directory but *would* do so in the directory immediately above it.

It is plausible behavior...

**Comment by rgommers** [comment]
If you want to keep the `srcdir` I can add it back - but `setup` seems needed here to not use deprecated form, and the order of positional arguments to `meson setup` is first builddir then sourcedir, so that still looks like a typo (right?) and it'd become:
```meson
meson setup builddir srcdir
```

**Comment by eli-schwartz** [comment]
> and the order of positional arguments to `meson setup` is first builddir then sourcedir, so that still looks like a typo (right?)

The order doesn't matter, but python's argparse module wants a name for each positional argument, and it was imagined to be most common that people started in `sourcedir` and passed `builddir` only, so I think that's why the argparse attributes got named the way they did. :)

I'm not too fussed either way about whether srcdir is kept, though. Elsewhere in this same file we already use builddir-only, even. My real nitpick is about the commit message. :D

**Comment by rgommers** [comment]
> My real nitpick is about the commit message. :D

Updated now - I hope that works.

Quick contribution question: should I be adding something to the commit message to avoid Azure spinning its wheels on doc-only PRs?

**Comment by eli-schwartz** [comment]
`skip_ci.py` has custom logic to handle PRs which only modify specific subdirectories of the repository, with a rule to detect docs/ only PRs and skip them.

Example for this PR: https://dev.azure.com/jussi0947/jussi/_build/results?buildId=20467&view=logs&j=5015ea34-1c35-577b-b206-c8bea8465a58&t=00c5cf7c-b41c-5970-0bf5-8751e484378e&l=14

I can never keep track of which commit message tokens work with which CI providers.

**Pull request merged**
