### PR TITLE
mtest: fix skipping with various prefixes

### PR DESCRIPTION
**Pull request by elmarco**
According to the specification:
https://testanything.org/tap-specification.html#skipping-tests

  The harness should report the text after # SKIP\S*\s+ as a reason for
  skipping.

(it's not exactly like the TODO directive, the phrasing/presentation of
the spec could be improved).

### CODE REVIEW

**Comment by elmarco** [comment]
@bonzini Ping

**Comment by bonzini** [comment]
LGTM

**Comment by dcbaker** [comment]
@elmarco, if you can rebase this on master and ping me I'll merge for you.

**Comment by elmarco** [comment]
@dcbaker  if CI pass, should be good. thanks

**Pull request merged**
