### PR TITLE
travis.yml: Test against gcc on macOS

### PR DESCRIPTION
**Pull request by nirbheek**
Enables Fortran tests on macOS and real GCC too.

### CODE REVIEW

**Comment by jeandet** [comment]
From what I understand the solution is to do:
```
brew install --only-dependencies gcc
brew cask uninstall oclint
brew install gcc
```

**Comment by jpakkane** [comment]
Still failin.

**Comment by nirbheek** [comment]
Yeah, the issue needs to be debugged and fixed. It was discovered by @jeandet on his CI.

**Comment by jeandet** [comment]
@jpakkane yes failure is a success in this case :) I wanted to show that fortran tests cases fails on OSX.
Now we need to find somebody to fix this :(

**Comment by QuLogic** [comment]
It appears to be broken running the tests, but seems to say "No tests defined." which is not something that happens on working systems. The output from the log doesn't seem to be there, so it's hard to say much from that output.

**Comment by jpakkane** [comment]
We now have GCC on macOS. This is no longer needed.

**Pull request closed without merging**
