### PR TITLE
Cmake: popen_safe(..., errors='ignore')

### PR DESCRIPTION
**Pull request by scivision**
probably something to consider making a default for mesonlib/Popen_safe() in general, 
but at least for cmake/executor, using 

```python 
ret = subprocess.run(..., universal_newlines=False, ...)
stdout = ret.stdout.decode(errors='ignore')
```

instead of Popen_safe() avoids Meson crash/traceback when a `dependency(..., method: 'cmake')` search goes wrong, and the compiler or Cmake feed back binary garbage not suitable for .decode() implicit in mesonlib/Popen_safe()

That is, this change allows Meson to simply note the dependency as "not found" instead of crashing Meson.

### CODE REVIEW

**Comment by scivision** [comment]
Hmm, Python 3.5 bites again. Oh yea that's what CI is for :octocat:

**Comment by mensinda** [comment]
We should probably remove this from 0.52.2, if this get's much more complicated.

Also, I doubt that there will be a 0.52.2 at all with `0.53.0 dev freeze 22/12, release 29/12 `

**Comment by scivision** [comment]
great good to know--this is worth fixing for 0.53.0

**Comment by scivision** [comment]
Actually I think the fix in cmake/executor.py is to use `subprocess.run(, errors='ignore')` instead of Popen_safe(), which has undesired and fallback behavior not helpful for this application. There are other areas of Meson where I did similar, where I was not interested in non-UTF8/non-ASCII or other fancy things, just wanted simple text.

**Comment by mensinda** [comment]
Python 3.5 `subprocess.run` also [does not have the errors key](https://docs.python.org/3.5/library/subprocess.html). It was added in 3.6 from what I can tell. I guess this would be another reason for #6297.

**Comment by scivision** [comment]
Hmm, then maybe 
```python
if sys.version_info >= (3, 6):
    ret = subprocess.run(..., errors='ignore')
else:
    try:
        ret = subprocess.run(...)
    except UnicodeDecodeError:
        ret = 1  
```

that's pretty easy to detect with a regex when Python 3.5 is deprecated

**Comment by mensinda** [comment]
To be honest, I don't see the point in having the `if sys.version_info >= (3, 6)`, since the try-catch block does basically the same thing (unless I missed something).

**Comment by scivision** [comment]
yes it was needless, it's much simpler as in edited comment

**Pull request merged**
