### PR TITLE
Exposes the install names of targets in introspection. Closes #829.

### LINKED ISSUE #829: mesonintrospect: Expose install_dir for targets
Mentioned on the [gnome-builder issue](https://bugzilla.gnome.org/show_bug.cgi?id=743280) this would be useful information.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by TingPing** [comment]
```python
  File "/home/tingping/.local/bin/mesonintrospect", line 4, in <module>
    __import__('pkg_resources').run_script('meson==0.36.0.dev1', 'mesonintrospect')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/home/tingping/.local/lib/python3.5/site-packages/meson-0.36.0.dev1-py3.5.egg/EGG-INFO/scripts/mesonintrospect", line 20, in <module>
    sys.exit(mintro.run(sys.argv[1:]))
  File "/home/tingping/.local/lib/python3.5/site-packages/meson-0.36.0.dev1-py3.5.egg/mesonbuild/mintro.py", line 204, in run
    list_targets(coredata, builddata, installdata)
  File "/home/tingping/.local/lib/python3.5/site-packages/meson-0.36.0.dev1-py3.5.egg/mesonbuild/mintro.py", line 84, in list_targets
    t['install_filename'] = determine_installed_path(target, installdata)
  File "/home/tingping/.local/lib/python3.5/site-packages/meson-0.36.0.dev1-py3.5.egg/mesonbuild/mintro.py", line 51, in determine_installed_path
    raise RuntimeError('Something weird happened. File a bug.')
RuntimeError: Something weird happened. File a bug.
```

**Comment by jpakkane** [comment]
Which project did this happen on?

**Comment by TingPing** [comment]
gnome-builder, it has quite a few targets and worked with current master.

**Comment by jpakkane** [comment]
Should work now.

**Pull request merged**
