### PR TITLE
gnome: Fix usage of gobject-introspection as subproject

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by xclaesse** [comment]
To work as subproject it also need fix in g-i: https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/206.

Together with https://github.com/mesonbuild/meson/pull/6902 it means that gnome.generate_gir() will automatically configure g-i subproject if there is a wrap file for it.

**Comment by jpakkane** [comment]
I know nothing about GIR as such but looks fine to me. Anyone with knowledge want to comment?

**Comment by nirbheek** [comment]
I'll review this today.

**Comment by xclaesse** [comment]
Thanks, I merged it already we can always fix #7051 in a new PR if needed.

**Comment by jon-turney** [comment]
This change seems to break using g-ir-compiler on a generated .gir file.  I don't understand the details, but bisection lands on this commit.

See:
https://travis-ci.org/github/jon-turney/meson-corpus-test/jobs/680779244
https://travis-ci.org/github/jon-turney/meson-corpus-test/jobs/680779219

**Comment by xclaesse** [comment]
@jon-turney should be fixed by https://github.com/mesonbuild/meson/pull/7088, if you can give it a try.

**Pull request merged**
