### PR TITLE
Add warning level zero

### PR DESCRIPTION
**Pull request by jml1795**
This merge request adds a `warning_level` of zero to meson. A setting of 0 causes no static analysis flags to be added to the compiler args.

Unfortunately, not all projects can build successfully with with warning level 1 however they do enable a subset of the flags turned on by e.g. `-Wall` along with setting `werror = true`. In these cases, it appears the project either needs to disable `werror` or not use meson at all. This allows the project to build with `werror = true` and turn on a subset of the flags.

This change does not change the current flags used in existing levels or change the default level. Thanks.

### CODE REVIEW

**Comment by scivision** [comment]
I think something like this is needed for legacy libraries. Right now I manually set `-w -std=legacy` in Gfortran

**Comment by jpakkane** [comment]
Looks good, but since this is new functionality, it should have a release note snippet. Ok to merge once that is added. Thanks.

**Comment by jml1795** [comment]
@jpakkane Where do I list release notes? I'm assuming that is different than docs/markdown/snippets/warning_level_0.md? Sorry if I missed that in the documentation somewhere

**Comment by jpakkane** [comment]
Those are exactly them. Sorry, I missed that file on the changes page. :man_facepalming:

**Pull request merged**
