### PR TITLE
Make sure we support "<lang>_args" kwarg for all languages

### PR DESCRIPTION
**Pull request by xclaesse**

### CODE REVIEW

**Comment by tristan957** [comment]
Steal my test from the other PR

**Comment by tristan957** [comment]
Also needs to backend fix for Cython if you are including that in this PR I guess.

**Comment by xclaesse** [comment]
> Steal my test from the other PR

done.

**Comment by tristan957** [comment]
I approve this PR as a non-voting contributor :). Hopefully this can be backported.

**Pull request merged**
