### PR TITLE
Add headers_only flag to pkg-config

### LINKED ISSUE #826: Need dependency(..., headers_only : true) and so on for use with Valgrind
Similar to #726 but not the same.

Use case: I want to detect valgrind via pkg-config and pass the right includes for valgrind/valgrind.h to my build, but not link to the valgrind libs (which fails because they're static libs and not built with -fPIC, but is also unnecessary because everything we need is in the headers via magic macros).

I know of other use cases where this is needed, e.g. where glib headers are used for portable typedefs but no linking is done.

`cflags = run_command('pkg-config', '--cflags', 'dep').stdout().strip().split()` is not cross-compile friendly, so doesn't seem like a good solution.

### PR DESCRIPTION
**Pull request by dcbaker**
This adds a new keyword argument to dependency, headers_only, which can
be used to flag pkg-config to use the --cflags-only-I. This is useful
specifically for valgrind, which provides static libraries compiled
without PIC, and does magic in its headers.

Fixes #826

### CODE REVIEW

**Comment by nirbheek** [comment]
This will break when the pkg-config dependency is cached and re-used in a place without `headers_only: true`. I think this is better implemented as a `.headers()` (or similar) function on the dependency itself.

**Comment by dcbaker** [comment]
Okay, I was implementing the solution proposed in the bug report, but if that's
not going to work I'll spin up a v2.

Thanks for looking at my patch.

**Comment by nirbheek** [comment]
Yeah, sorry, we've had a lot of edge-cases w.r.t. dependency caching, and adding more types of dependencies isn't going to help. Adding a method on dependencies to only get include-flags makes a lot of sense and it will also work with other types of dependencies besides `PkgConfigDependency`.

**Comment by jpakkane** [comment]
I'm going to close this to reduce clutter. Please open a new MR once you have v2 ready. Thanks.

**Pull request closed without merging**
